### ISSUE TITLE
Screenshot referenced in addon.xml doesn't exist

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#1]
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/c42106d631c3f831264726158457bd274d47b6ec/addon.xml#L21

There is no screenshot image available at `resources/screenshot-01.jpg` 😦

**Comment by jurialmunkey** [comment]
Whoops! Fixed now. Thanks 😃

**Comment by drinfernoo** [comment]
I'll update the repo in a while 👌
