### ISSUE TITLE
[Bug] Hidden Trakt Titles appearing in lists

### ISSUE THREAD

**Issue by abbaskip** [jurialmunkey/plugin.video.themoviedb.helper#100]
I have some TV shows that I've hidden in Trakt so that they don't appear in Next Up etc, but TMDB Helper seems to ignore this and show them anyway - even in Trakt lists like "Your Next Episodes".

**Comment by jurialmunkey** [comment]
I'll look into. Can you tell me exactly which lists are affected.

**Comment by abbaskip** [comment]
Your Next Episodes as mentioned.

Your Recently Watched seems to hide as expected.

**Comment by jurialmunkey** [comment]
Can confirm. Unfortunately it looks like Trakt API doesn't hide shows from watched history.

**Comment by abbaskip** [comment]
Ha, what great API functionality. There isn't a toggle or similar when calling?

**Comment by jurialmunkey** [comment]
> 
> 
> Ha, what great API functionality. There isn't a toggle or similar when calling?

Nope. 

It's possible to pull a list for hidden items and compare. However, the lists of hidden items are split per section - i.e. separate hidden lists for calendar, progress watched, progress collected, and recommendations. So it's not entirely clear which list to compare against because it is a mix of calendar, watched, and collected really.

I could add a compare to these lists but it will add extra overhead and will need a bit of work to implement (rather than just setting a flag to the API to tell it whether you want all or only non-hidden, which is how you would expect it to work!)

**Comment by abbaskip** [comment]
> > Ha, what great API functionality. There isn't a toggle or similar when calling?
> 
> Nope.
> 
> It's possible to pull a list for hidden items and compare. However, the lists of hidden items are split per section - i.e. separate hidden lists for calendar, progress watched, progress collected, and recommendations. So it's not entirely clear which list to compare against because it is a mix of calendar, watched, and collected really.
> 
> I could add a compare to these lists but it will add extra overhead and will need a bit of work to implement (rather than just setting a flag to the API to tell it whether you want all or only non-hidden, which is how you would expect it to work!)

Yeah that's unnecessary overhead and will slow down list population - which really isn't ideal.

Crazy that Trakt don't have it in their API. I wonder if there is somewhere to raise a feature request there.

**Comment by ZefXyde** [comment]
@abbaskip Out of curiosity, did you try removing or resetting your progress for those series instead of hiding them?

**Comment by abbaskip** [comment]
I don't want my progress reset. I like to know which episodes I've actually watched if I manually check Trakt - just don't want them appearing on episode lists etc

**Comment by jurialmunkey** [comment]
Yeah it's a pain. The main usage for me personally is that there are some shows like Judge Judy that I might watch on occasion but am not particular invested in "finishing" the show. It's just something I like to put on in the background occasionally whilst I'm doing other things. I don't want to see it in my next episodes but I do want to know which episodes I've watched before.

On that note, hopefully I will have something for this issue soon.

**Comment by abbaskip** [comment]
Yeah exactly... Well not Judge Judy, more Property Brothers and MasterChef...

Plus if I watch an episode of a 90s soap (90210 or Dawson's Creek) or Baywatch after my wife's gone to bed I don't want her realising my guilty pleasures 🤣

**Comment by jurialmunkey** [comment]
@abbaskip - Can you test latest? Should hopefully hide hidden items from inprogress and your next episodes sections now.

It will hide anything that was hidden from calendar or progress -- Trakt has separate hidden settings for both but I think it makes more sense to make it so it doesn't matter where you hide it from.

Let me know if that differs from how you think it should work (you can check your hidden items for each section in "settings" on Trakt website from top right profile menu).

Also please let me know if there are other sections that should hide the hidden items.

**Comment by jurialmunkey** [comment]
Okay it seems to be working properly on my end. Please let me know if there's any issues. Closing for now though since it appears to be fixed properly.
