### ISSUE TITLE
Add MPAA rating to filter options 

### ISSUE THREAD

**Issue by Colin66** [jurialmunkey/plugin.video.themoviedb.helper#1001]
### Describe the feature that you'd like

Add MPAA rating (by country) to filter settings, e.g  in Discover movies / Discover TV menu.
Eg Region : UK ; filter by rating : PG13, 12, G (multiple options as in genres)

### Why is this feature needed? What problem does it solve?

It's useful for people with kids.  The old OpenInfo / Extended info was able to do this.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
In next release.

Only available for Discover Movies. The TMDb Discover API does not provide this option for TV Shows.

**Comment by jurialmunkey** [comment]
FYI it appears to break if the certification has a special character (e.g. `MA 15+`). All other ratings work (e.g. `M` `PG` PG-13` etc.) just not ones with a `+`
