### ISSUE TITLE
[BUG] Items with custom titles have trouble finding ratings

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/plugin.video.themoviedb.helper#1004]
### Describe the bug

For some items I use custom titles to add some info about them.

For example: Dawn of the Dead - The Argento Cut (1978).mkv

For these items I create .nfo files like this::

`<movie>
    <title>Dawn of the Dead - The Argento Cut</title>
    <originaltitle>Dawn of the Dead</originaltitle>
</movie>
https://www.imdb.com/title/tt0077402/`

Any item that I've done this has trouble getting the ratings (imdb, rottentomatoes). If I refresh the item it finds the ratings correctly but they disappear again after a while.

### Steps To Reproduce

1. Rename item to include info as shown above
2. Create .nfo as shown above
3. Update Kodi library - ratings are likely missing
4. Refresh the item - ratings are found
5. Wait a couple of days and the ratings will be gone again

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Do you have imdb IDs or TMDb IDs as your main ID in your scraper?

**Comment by Aemstel2** [comment]
Not sure what you mean..

I use the default information provider, The Movie Database Python. In its settings I've set the default rating to IMDb.

**Comment by jurialmunkey** [comment]
Please try v5.0.50 -- it will allow monitor lookups using TMDb ID for movies/tvshows.

**Comment by Aemstel2** [comment]
Great, thank you! I did a quick test with the new version. I removed one of those items from my database and updated the database again and it found the ratings correctly. So that works. If any ratings still disappear after a while, I will report back here.
