### ISSUE TITLE
[Question] Providers filter

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1005]
### Describe the bug

I use this line to filter content by provider.
`&amp;exclude_key=providers&amp;exclude_value=is_empty`
I'm only interested when I change the language and country in the tmdb helper, the content is significantly reduced. What does this filtering depend on? For example, I know that the movie is from Netflix, the service is supported in the selected country, but it is not there.

### Steps To Reproduce

/

### Debug log

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by matke-84** [comment]
I think I remembered. You correct me if I'm wrong. Providers data comes from JustWatch. If there is a movie for the selected country, it will be shown.

**Comment by jurialmunkey** [comment]
Yep that's correct just watch.

So movie needs to be available in region on TMDb + just watch needs to support that region + just watch data needs to say that item is provided by that provider in that region.
