### ISSUE TITLE
Playback failed 

### ISSUE THREAD

**Issue by Dappakid13** [jurialmunkey/plugin.video.themoviedb.helper#1008]
### Describe the bug

I having been using tmdb helper and umbrella (source select) as a player and I keep running into a issue where I get playback failed. For "is resolveable" when player is being configured, it  is set to true by default. It plays when set to false or if I choose umbrella auto play. It works for fen, seren etc  is there is a fix or workaround?

### Steps To Reproduce

Go to tmdb settings 
Go to player
Select source select for movie/tvshow
Go into to tmdb helper 
Go to trakt for example 
Go to in progress episode 
Select a episode 
Select a source 
U should get the playback error 

### Debug log

[kodi1.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/10772863/kodi1.log)
I have attached the log on one of the devices.

### Screenshots and Additional Info

Was able to replicate the issue on a firestick 4k, nvidia shield and xbox series s. I removed addon data it open wizard and also uninstall and reinstalled the app with the same issue. I noticed a issue as well where it keeps starting over from the beginning of a tv even though there is resume point. This bug only happens for tv Shows for me, movies are just fine.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
TMDbHelper is functioning correctly according to your log. 

This is a player issue and I don't maintain 3rd party players. 

>  It plays when set to false or if I choose umbrella auto play. 

You already provided the solution.

set isresolveable to false because clearly the method you are using in the player does not support setresolvedurl().
