### ISSUE TITLE
Local Library Items Not Played from some lists

### ISSUE THREAD

**Issue by abbaskip** [jurialmunkey/plugin.video.themoviedb.helper#101]
Some Episode lists don't play local library items and default to the TMDB Helper player.

I believe this is related to the issue that was quickly closed here, https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/99 the reason being, the episode widgets that don't display correctly (both without the red ribbon, and with the episode number repeated) are the same ones that don't play from local library.

i.e. those that display correctly as a widget in Aura mod, plays from local library; those that don't only plays from default TMDB player (in my case Seren) and displays incorrectly with the episode number repeated in the title and the grey text box over the bottom of the thumbnail.

I have noticed some other TMDB Helper lists also only play from the default player instead of local too:
TV shows - Your Recently Watched
TV Shows - Trending This Week
Trakt - Based on Host Watched TV Shows
TV shows - Your Most Watched

Don't play local, whereas

TV shows - Collection 
Trakt - TV shows Collection

All work properly, playing local first.

I don't have time to check every list obviously, but hope this points you in the right direction. 

Edit: i now can't recreate getting episode widgets from this add-on to display correctly, so they may not be related. Definitely can recreate episodes not playing locally though.

**Comment by jurialmunkey** [comment]
Enable `Allow fuzzy matches (ignore year) for tvshows` in player settings.

**Comment by abbaskip** [comment]
> Enable `Allow fuzzy matches (ignore year) for tvshows` in player settings.

Thanks, will try this now. But isn't it strange that the same episode plays from some places and not others if this is the work around? That would suggest different info is sent to match the local library or similar I imagine? Sorry, you're defo the expert here, just trying to get my head around it.

**Comment by jurialmunkey** [comment]
> 
> 
> > Enable `Allow fuzzy matches (ignore year) for tvshows` in player settings.
> 
> Thanks, will try this now. But isn't it strange that the same episode plays from some places and not others if this is the work around? That would suggest different info is sent to match the local library or similar I imagine? Sorry, you're defo the expert here, just trying to get my head around it.

Most likely a difference between Trakt and TMDb info.

**Comment by abbaskip** [comment]
Great. Well it fixes the issue it seems. Raised another issue in Auramod for me though 😂
