### ISSUE TITLE
[Question] Anyway to return the plugin page value 

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1010]
In MyVideoNav.xml is there a way to return the current page that a plugin path is on?

I currently use Container.PluginCategory as the header for my view but would like to also include the page number as well, for example

Anticipated TV Shows - Page 4

This would aid in knowing how far you need to back navigate to get back out.

**Comment by jurialmunkey** [comment]
In media windows, for the main view you can get any container params using a container property
`Container.Property(param.page)`

For widgets, container properties aren't available so you can get it from the listitem instead
`Container(id).ListItem.Property(param.page)`

This should work for any param.

**Comment by roidy** [comment]
Thanks 👍

**Comment by roidy** [comment]
>This should work for any param.

Doesn't work for `param.type`

**Comment by jurialmunkey** [comment]
tmdb_type is the correct param. 

type is converted internally to tmdb_type

**Comment by roidy** [comment]
Thanks 👍
