### ISSUE TITLE
Keeps failing to get resume point

### ISSUE THREAD

**Issue by Dappakid13** [jurialmunkey/plugin.video.themoviedb.helper#1012]
### Describe the bug

I'm running in a issue with the resume point in tmdb helper for umbrella, this only happens with tv shows (movies work just fine) and then I get a playback failed message. Umbrella dev released a update today to remove bad include from ah2, that resolved the playback failed issue for the widget on ah2, but it still happens in the tmdb appe and does not resume. 
Here is some of the error in the log, can u tell me where the issue is and a possible fix?

[plugin.video.themoviedb.helper]
                                                   CACHE: Locked: Retrying DB commit...
2023-02-19 18:04:30.649 T:30150    info <general>: [plugin.video.themoviedb.helper]
                                                   CACHE: _database ERROR ! -- 
2023-02-19 18:04:30.653 T:30149    info <general>: [plugin.video.themoviedb.helper]
                                                   CACHE: Locked: Retrying DB commit...
2023-02-19 18:04:31.917 T:30075    info <general>: Skipped 11 duplicate messages..
2023-02-19 18:04:31.916 T:30075 warning <general>: "resumetime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions

### Steps To Reproduce

Go to tmdb helper
Go to trakt 
Select a tv show with source select player (umbrella)
Playback failed will show up (movies are okay)

### Debug log

[download (1).txt](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/10778269/download.1.txt)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by Dappakid13** [comment]
On the latest version sent out today with the same issue.
[download (2).txt](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/10799741/download.2.txt)

**Comment by jurialmunkey** [comment]
These logs do not show you attempting to play an item. 
Otherwise you would have a log message "lib.container.router - Attempting to play item"

Also you need to enable debug logging.

**Comment by Dappakid13** [comment]
Thank you for that, I just enabled the debugging logs and did the test on my xbox. 

Still the same playback when trying to play from tmdb helper, it works on the widget but never resume the scrobble point.

Here is the new log.

@jurialmunkey 

[download (3).txt](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/10803991/download.3.txt)

**Comment by jurialmunkey** [comment]
TMDbHelper is functioning correctly.

Sounds like the player file for end plugin does not support setResolvedUrl. You should disable the is_resolveable flag (set to false) for the player.
