### ISSUE TITLE
[Feature] Add Trakt Seasons Watchlist

### ISSUE THREAD

**Issue by florence-wolfe** [jurialmunkey/plugin.video.themoviedb.helper#1014]
### Describe the feature that you'd like

TMDB Helper currently supports both Movies and TV Show watchlists from Trakt. However, there isn't a watchlist view for Seasons, which can be a useful feature for users who want to keep an eye on a particular season of a series.

I suggest adding a new Trakt watchlist view for Seasons in TMDB Helper.

The watchlist URL is available at `https://trakt.tv/users/{username}/watchlist?display=season&sort=rank,asc`.
In other words, it uses the same [/watchlist](https://trakt.docs.apiary.io/#reference/users/watchlist) endpoint as TV Shows and Movies. The only difference is the `mediatype` specified as `seasons` and the response payload.

### Why is this feature needed? What problem does it solve?

- Adding a Seasons watchlist could enhance the user experience for TMDB Helper users who want to keep track of their favorite seasons
- This feature could be also useful for users who have already seen a series up to a certain point and want to catch up on new seasons.
- Likely other uses I haven't thought of.

### Out of Scope

- An `episodes` watchlist and mediatype is also available on Trakt, but it is not within the scope of this proposal.
- Adding and removing to/from the seasons watchlist. I believe this adds unnecessary complexity to the initial proposal

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
This is an interesting idea. I didn't even realise you could watchlist individual seasons.

I think this shouldn't be too difficult to achieve. I assume each season in the watchlist should link directly to the episodes for the season rather than the tvshow?

**Comment by florence-wolfe** [comment]
Yes exactly.

Here's the response body for my seasons watchlist:

```json
[
  {
    "rank": 1,
    "id": 797760672,
    "listed_at": "2023-02-23T05:17:17.000Z",
    "notes": null,
    "type": "season",
    "season": {
      "number": 4,
      "ids": {
        "trakt": 317254,
        "tvdb": null,
        "tmdb": 329524,
        "tvrage": null
      }
    },
    "show": {
      "title": "Tournament of Champions",
      "year": 2020,
      "ids": {
        "trakt": 157664,
        "slug": "tournament-of-champions",
        "tvdb": 376197,
        "imdb": "tt11173298",
        "tmdb": 100095,
        "tvrage": null
      }
    }
  },
  {
    "rank": 2,
    "id": 797760692,
    "listed_at": "2023-02-23T05:17:47.000Z",
    "notes": null,
    "type": "season",
    "season": {
      "number": 5,
      "ids": {
        "trakt": 307276,
        "tvdb": 2031336,
        "tmdb": 317592,
        "tvrage": null
      }
    },
    "show": {
      "title": "The Circle",
      "year": 2020,
      "ids": {
        "trakt": 151342,
        "slug": "the-circle-2020",
        "tvdb": 368012,
        "imdb": "tt9581768",
        "tmdb": 97083,
        "tvrage": null
      }
    }
  }
]
```

It seems to return both the TV Show as well as the specific details to the season that is on the watchlist. In this case, I only have 2 seasons for 2 separate shows in my seasons watchlist and neither of the "parent" shows are in another watchlist on my trakt.

Here's a screenshot of how that looks: ![image](https://user-images.githubusercontent.com/87673558/221206487-2f72f547-677f-4562-8b50-8adcf9ebe9f0.png)

Clicking on either of those seasons brings you to the specific season page. For example, in the case of `Tournament of Champions` we can see that the hyperlink is for the specific season:  ![image](https://user-images.githubusercontent.com/87673558/221206797-525f1bd2-5b9e-47f2-bbfb-46fd70ef2385.png)

**Comment by xyzfre** [comment]
This new feature is GREAT💯 Thank you @jurialmunkey
