### ISSUE TITLE
[Update necessary] Gaia player for TMDB Helper

### ISSUE THREAD

**Issue by RunAway189** [jurialmunkey/plugin.video.themoviedb.helper#1015]
### Describe the bug

Hello,

I recently have setted up my Kodi with Gaia add-on. Unfortunately it's not possible to use it as a TMDB Helper player so I decided to text to Gaia dev who kindly replied to me and updated the add-on in order to make the player working. Unfortunately there's another step to do which must be done for TMDB Helper. I don't know what exactly because I'm not expert in python or anything related so I'm attatching here below his message:

"Thanks for reporting this. I've made the necessary changes. Please use Gaia v6.1.8 or later. It still has to be fixed from TMDBHelper's side.

I've noticed you already filed a ticket on TMDBHelper's github. Could you please post this link there as well:

https://github.com/gaiakodi/gaiasource/blob/938de3bf536b48ba399fd19990addfafed20dd0a/plugin.video.gaia/addon.py#L2399

There is a long comment I added in v6.1.8 to addon.py under the "scrape" endpoint. It describes all aspects of creating as scraping command, including various examples. They essentially just have to copy those examples and replace their parameters.

In the old TMDBHelper command they passed a bunch of unnecessary parameters, which are only internal to Gaia. You just have to pass 1 or more IDs, or the title+year. Gaia does the rest."

### Steps To Reproduce

-

### Debug log

-

### Screenshots and Additional Info

-

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I don't make third party players for piracy addons. I'm sure there are people on reddit you can find to help you.
