### ISSUE TITLE
[BUG] Can't get new Recommendations Dialog to grab info for episodes

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1019]
As title.

`Runscript(plugin.video.themoviedb.helper,recommendations=5000|info=cast|true|info||5001|info=crew|true|info||5002|info=episode_thumbs|true|browse,window_id=1191,tmdb_type=tv,tmdb_id=$INFO[Container(99999).ListItem.Property(TMDb_ID)],season=$INFO[ListItem.Season],episode=$INFO[ListItem.Episode],episode_year=$INFO[ListItem.Year])`

Just returns info for the main show not the episode.

**Comment by jurialmunkey** [comment]
Tmdb ids are for base tvshow. Put the episode details in the path you want them. 

Eg
`5000|info=cast&season=1&episode=1`

**Comment by roidy** [comment]
Thanks, I assumed the season and episode were added as extra params to the runscript, never occurred to me to add them to the info= 

Do I need to supply episode_year, like when calling normally?

`plugin://plugin.video.themoviedb.helper?info=cast&amp;type=tv&amp;query=$INFO[ListItem.TvShowTitle]&amp;episode_year=$INFO[ListItem.Year]&amp;season=2&amp;episode=1`

**Comment by jurialmunkey** [comment]
You dont have to use it but episode_year will help get a better match when you don't have the ID.

**Comment by roidy** [comment]
Thanks 👍
