### ISSUE TITLE
Discover - Fanart

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#102]
When using Discover via library view or adding as a widget, TMDBh is not adding fanarttv=True or widget=true, so I am not getting additional artwork.

Was this by design or can you change so fanarttv is enabled?

Thanks.

**Comment by jurialmunkey** [comment]
Ah, no not intentional - just an oversight. 

I think it should be fixed now. Can you test latest and confirm?

**Comment by skyfsza** [comment]
Working in both library view and widget now.

Thanks!

**Comment by jurialmunkey** [comment]
Excellent! Thanks for the bug report and confirming.
