### ISSUE TITLE
[BUG] Error when selecting Movies-Trakt Watchlist (Released)

### ISSUE THREAD

**Issue by jluftman** [jurialmunkey/plugin.video.themoviedb.helper#1022]
### Describe the bug

No issues when selecting Movies-Trakt Watchlist but selecting Movies-Trakt Watchlist (Released) returns an error and back to menu.  Tried on two separate installations with same result. Log is for installation on Chromebox, other system is Firecube.  Both Android, latest stable Kodi, latest TMDB Helper.

### Steps To Reproduce

1. Go to tmdb helper
2. Click on movies, click on [Trakt] Watchlist (Released)

### Debug log

https://paste.kodi.tv/seyanoboli

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Oops! Looks like I accidentally broke the filter functionality need for those lists a while ago. I'm surprised no one has reported it until now. Easy fix, will be in next release.

**Comment by jluftman** [comment]
I know it’s been 3+ years but this issue has kinda resurfaced. No errors but movies-Trakt watchlist (released) has items I added months ago but doesn’t seem to add any new watchlist items (that were released in the past few years.  Regular watchlist shows all.
