### ISSUE TITLE
UPNext Add-on Launches but fails to play next episode[BUG] 

### ISSUE THREAD

**Issue by MrC001** [jurialmunkey/plugin.video.themoviedb.helper#1024]
### Describe the bug

UPNext add-on installed and edited player file to make Upnext (Next Up playlist) and at end of episode the Upnext popup comes up .. so all good there but fails to play next episode.  Also tried playlist instead of UpNext and fails as well.

Bug or maybe something I did wrong or maybe it's not supposed to work?

### Steps To Reproduce

Install UpNext Addon
Install Player files for whatever player
Edit Player to build playlist (Set to UpNext)
Tried different players, same resault on all so far..Pop-up but fails to play next episode.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
In order to work with the make_playlist setting, the player must be compatible with setResolvedURL -- i.e. it must work with is_resolvable set true. Most banned addons that scrape sources will not work because they hack the Kodi videoplayer to control playback instead of following the proper Kodi methods of using setResolvedURL.

SlyGuy/MattHuisman plugins should work correctly. Pretty much anything that uses inputstream adaptive will work as it must go via setResolvedURL. Other official plugins like YouTube should also work. I think Netflix would also work but it has its own integration with UpNext anyway, so a bit irrelevant.

**Comment by MrC001** [comment]
Ahh well that prob explains it then.  Sorry to waste your time.

**Comment by jurialmunkey** [comment]
Also note that @MoojMidge has an UpNext fork which has better integration with TMDbHelper
https://github.com/MoojMidge/service.upnext/releases

I'm not sure if it is ready for general use yet or not but the changes will address a lot of these types of issues.

**Comment by MoojMidge** [comment]
@MrC001 - my fork of UpNext should be fine for everyday use if you want to try and see how it works for you. Easy to remove afterwards if you need to. 

Without a debug log it is difficult to say exactly what is happening, but it looks like the TMDBHelper player is working, however the next episode is not being found in whatever video plugin you are using, or the video plugin directly stopping/starting video playback is causing problems with the generated playlist.

There are a few settings in my fork of UpNext that may help this work:
- UpNext > Settings > Expert > Troubleshooting > Enable TMDbHelper integration
  - enable this
- UpNext > Settings > Expert > Troubleshooting > Enable TMDbHelper integration > Exact match only
  - disable this to allow you manually select an episode if it is not found automatically
- UpNext > Settings > Expert > Troubleshooting > Enable TMDbHelper integration  > Queue all episodes
  - disable this to disable the player `make_playlist` setting, which, as jurialmunkey noted, won't work unless the video plugin starts video playback in the correct way

**Comment by MrC001** [comment]
Ok Thanx -- I was just messing around as I do, playing.  It wasn't the end of the world.....was trying a very minimalistic player to play from my premiumize storage.  Of course easiest is webdav link it to library.  Anyway I shall play around with it tomorrow..thanx again !!

**Comment by peter-mogaka** [comment]
> @MrC001 - my fork of UpNext should be fine for everyday use if you want to try and see how it works for you. Easy to remove afterwards if you need to.
> 
> Without a debug log it is difficult to say exactly what is happening, but it looks like the TMDBHelper player is working, however the next episode is not being found in whatever video plugin you are using, or the video plugin directly stopping/starting video playback is causing problems with the generated playlist.
> 
> There are a few settings in my fork of UpNext that may help this work:
> 
> * UpNext > Settings > Expert > Troubleshooting > Enable TMDbHelper integration
>   
>   * enable this
> * UpNext > Settings > Expert > Troubleshooting > Enable TMDbHelper integration > Exact match only
>   
>   * disable this to allow you manually select an episode if it is not found automatically
> * UpNext > Settings > Expert > Troubleshooting > Enable TMDbHelper integration  > Queue all episodes
>   
>   * disable this to disable the player `make_playlist` setting, which, as jurialmunkey noted, won't work unless the video plugin starts video playback in the correct way

hi @MoojMidge how do you install your addon? I´m facing the problem above.

I´ve authenticated trakt on tmdbhelper, setup players using setresolveurl -true and make_playlist yes. A playlist is created but contains all the episode, it´s not able to filter out on watched episode from trakt. It also doesn´t play the next episode when I click on the upnext widget(it plays the current episode). I´ve noticed delayed sync with track to mark episode as watched etc, even though %watched is configure on players and trakt app. 

@MoojMidge @jurialmunkey 3 questions/issues;

- how make tmdb filter out watched episodes in the playlist created?
- how do i make it play the next episode? 
- do i need the trakt addon for kodi or is the tmdp trakt helper enough to sync progress in a timely manner?

I´m using latest kodi version, fen, trakt kodi addon and AH2. I´ve also disbaled retoute PLaymedia to xbmc.player(). next episode sort method recently watched/airdate have the same result. no playlist is created if i configure make_playlist(upnext)

**Comment by MoojMidge** [comment]
I responded to your question about installation here: https://github.com/MoojMidge/service.upnext/issues/32

For the rest of your questions suggest reading the Wiki: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function, or asking your questions to the plugin or player authors
