### ISSUE TITLE
[Feature] please add tubed.json

### ISSUE THREAD

**Issue by mariofenech** [jurialmunkey/plugin.video.themoviedb.helper#1025]
### Describe the feature that you'd like

I would like to add tubed.json to my players..
Just editing the youtube.json witl all pointing to Tubed doesn't work..it just brings the tubed addon up but doesnt search.

### Why is this feature needed? What problem does it solve?

Thanks for any help

### Screenshots and Additional Info

This is what i tryed;

`{
    "name": "Tubed",
    "plugin": "plugin.video.tubed",
    "is_resolvable": "true",
    "play_movie": [
        "plugin://plugin.video.tubed/search/?q={name_url}&search_type=notvalid",
        {
            "title": "(?i){title}"
        }
    ],
    "play_episode": [
        "plugin://plugin.video.tubed/search/?q={name_url}&search_type=notvalid",
        {
            "dialog": "True"
        }
    ],
    "search_movie": "plugin://plugin.video.tubed/search/?q={name_url}&search_type=notvalid",
    "search_episode": "plugin://plugin.video.tubed/search/?q={name_url}&search_type=notvalid"
}`

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
I can't make players for plugins I dont personally use.

The wiki contains documentation for creating players
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

Additionally the plugin contains a player template generator to get you started.
