### ISSUE TITLE
[Feature] fullscreen widget artwork option

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#1028]
### Describe the feature that you'd like

In tmdb helper settings, under widgets, there’s already an option for preferred artwork for thumbs. Would it be possible to have an option for preferred artwork for the AH2 fullscreen widget? So you could set it as the episode thumb instead of the shows fanart.

### Why is this feature needed? What problem does it solve?

It would be nice to have the option for episode thumbs for the AH2 fullscreen widget so that you didn’t keep seeing the same images over again (say you’re binging a tv show and the fullscreen widget is set to next episodes, it will only ever show that tv shows one fanart picture)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Thumbs are generally too low quality and low resolution to use fullscreen.
