### ISSUE TITLE
[Enhancement] Browse Season/ Browse Show Context

### ISSUE THREAD

**Issue by abbaskip** [jurialmunkey/plugin.video.themoviedb.helper#103]
Is there any chance of adding a context when clicking episodes to browse season or browse show?

This was an OpenMeta function and extremely useful when watching shows that you don't necessarily want to watch in any particular order (Simpsons, South Park, Seinfeld etc come to mind).

**Comment by drinfernoo** [comment]
OpenMeta does not have this functionality.

**Comment by jurialmunkey** [comment]
Yeah I've been thinking something like this would be useful for up next. 

For instance, someone else in the house watched an episode without you (or you forgot what happened at the end of the episode etc.), so you want to go back and watch that episode first before moving on to the next one.

I'll keep you posted.

**Comment by abbaskip** [comment]
> OpenMeta does not have this functionality.

Is it OpenInfo then? They're the only two addons i uninstalled and it's gone from my context

**Comment by abbaskip** [comment]
> Yeah I've been thinking something like this would be useful for up next.
> 
> For instance, someone else in the house watched an episode without you (or you forgot what happened at the end of the episode etc.), so you want to go back and watch that episode first before moving on to the next one.
> 
> I'll keep you posted.

Essentially what i would use it for - apart from the random watching that i mentioned.

My Next Episodes widget is sorted by last watched, so the shows i regularly put on as background noise i like to be able to not just watch in order etc.

**Comment by jurialmunkey** [comment]
> 
> 
> > Yeah I've been thinking something like this would be useful for up next.
> > For instance, someone else in the house watched an episode without you (or you forgot what happened at the end of the episode etc.), so you want to go back and watch that episode first before moving on to the next one.
> > I'll keep you posted.
> 
> Essentially what i would use it for - apart from the random watching that i mentioned.
> 
> My Next Episodes widget is sorted by last watched, so the shows i regularly put on as background noise i like to be able to not just watch in order etc.

You know that there is a last specifically for recently watched tvshows:
Trakt > Your Recently Watched TV Shows

That will list all shows you've recently watched in order of last watched. I use that list specifically for the purpose that you're describing.

**Comment by abbaskip** [comment]
> > > Yeah I've been thinking something like this would be useful for up next.
> > > For instance, someone else in the house watched an episode without you (or you forgot what happened at the end of the episode etc.), so you want to go back and watch that episode first before moving on to the next one.
> > > I'll keep you posted.
> > 
> > 
> > Essentially what i would use it for - apart from the random watching that i mentioned.
> > My Next Episodes widget is sorted by last watched, so the shows i regularly put on as background noise i like to be able to not just watch in order etc.
> 
> You know that there is a list specifically for recently watched tvshows:
> Trakt > Your Recently Watched TV Shows
> 
> That will list all shows you've recently watched in order of last watched. I use that list specifically for the purpose that you're describing.

Yeah, thanks i saw that, but 75% of the time i want Next Episodes functioning exactly as is - and it feels like a duplicate having them both there.

**Comment by jurialmunkey** [comment]
@abbaskip - Okay, I've added a context menu item to `Browse Seasons` for episodes. Let me know how it goes.

**Comment by Demonseeed** [comment]
I tested it out, working for me 👌

**Comment by jurialmunkey** [comment]
> 
> 
> I tested it out, working for me 👌

Thanks for confirming. Yeah I'm pretty sure it should work fine, so I'm going to close this one now.

**Comment by abbaskip** [comment]
@jurialmunkey  this functionality seems to be gone from the current version?

I used it quite a bit, did you mean to remove it - I know you rewrote a load of code?

**Comment by jurialmunkey** [comment]
@abbaskip - Location just moved slightly. It's now:
`Context Menu > Browse lists > Seasons`

You can now use the context menu to browse any of the lists (e.g. Recommendations Cast Posters etc.) that you would normally be able to with the old "browse" action. I combined the Seasons with the rest of them because I was trying to limit the number of top level context items.
