### ISSUE TITLE
[Feature] Wikipedia text formating

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1030]
### Describe the feature that you'd like

Is there a possibility to format text in the wikipedia script, more precisely to avoid linked blue text, italic font...

### Why is this feature needed? What problem does it solve?

It matters because of the skins. For example, in my skin, which is the main color red, the blue text does not fit and italic font is not good if you want to set the text to be justify. Part of the letter is cut.

### Steps to reproduce.

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
```
Skin.SetString(TMDbHelper.Wikipedia.Format.Link,[COLOR=red]{}[/COLOR])

.Link = <a href=> tags
.Bold = <hx> <b> <th> and class:mw-headline tags
.Emphasis = <em> <i> tags
.Superscript = <sup> tags

```

**Comment by matke-84** [comment]
Thanks. But I'm not sure what the line should look like for the other three tags. Can you write some examples.

**Comment by matke-84** [comment]
Okay. I think I got it. I just noticed a few details. Shouldn't this go on a new line?
![bug](https://user-images.githubusercontent.com/74268331/226187221-552f3a93-30fc-462e-bb8b-7d918f76169f.png)
There are many of these cases. On the original Wikipedia page, it is in a new line.

**Comment by jurialmunkey** [comment]
HTML formatting cannot perfectly be replicated in a single textbox with only text. There are no divs or spans or tables etc.

Additionally it is based on mobile formatter not desktop.
