### ISSUE TITLE
[Feature] Description

### ISSUE THREAD

**Issue by taiseer999** [jurialmunkey/plugin.video.themoviedb.helper#1031]
### Describe the feature that you'd like

 show rating in widgets when Arabic Saudi Arabia is assigned as language and in TMDbHelper.

### Why is this feature needed? What problem does it solve?

It works with or regions and languages but not in ours

### Screenshots and Additional Info

Select region as us
![IMG_1433](https://user-images.githubusercontent.com/118752825/225946473-aae724d1-a01e-4c4b-adae-cff4703381a6.jpeg)

Select as Saudi 
![IMG_1431](https://user-images.githubusercontent.com/118752825/225946612-e84376c3-d04a-4818-9061-c4b7fd3af094.jpeg)
![IMG_1432](https://user-images.githubusercontent.com/118752825/225946643-86733d99-ac70-4085-8913-e21e2959feae.jpeg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
I can't magically make information appear out of nowhere... If the classification for that region doesn't exist on TMDb website then it won't be available in tmdbhelper.

**Comment by taiseer999** [comment]
Is that right? Thanks for your reply anyway.
