### ISSUE TITLE
[Question] Option to limit/filter the providers list!

### ISSUE THREAD

**Issue by diimaan** [jurialmunkey/plugin.video.themoviedb.helper#1035]
### Describe the feature that you'd like

The provider list in the TMDB Helper is so huge especially if I use that as a stacked widget in AH2! Is there any way to filter which providers I want or I can see? 
I see that there is an option called configure provider data allowlist. But it does only allow update from specific provider but not limit them or hide them!

### Why is this feature needed? What problem does it solve?

.

### Steps to reproduce.

.

### Screenshots and Additional Info

.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Use library node editor to make nodes according to your specifications.

**Comment by jurialmunkey** [comment]
https://kodi.wiki/view/Add-on:Library_Node_Editor
