### ISSUE TITLE
When selecting a episode from Home Screen Widgets a TMDb error pops up 

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/plugin.video.themoviedb.helper#1036]
### Describe the bug

With the latest update v5.1.9 Selecting a episode from home screen widgets (example) Next Episode a error pops up and doesn't play ,also trying to use context menu Select Player the same error ,, selecting Movies from what I tested works fine ,I don’t use library only Trakt,,Fen/Windows 11 Pro K20.1

### Steps To Reproduce

//

### Debug log

My apologies didn’t get a chance to grab a log did take a screenshot from OW 

### Screenshots and Additional Info

![2B01BF88-5505-4859-9EFD-915213944597](https://user-images.githubusercontent.com/49699869/229012984-078a6db0-0227-41ae-b1f4-9988a258098f.jpeg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by khalilpeter2** [comment]
I’m having this exact same issue and I have a log http://paste.kodi.tv/ohidisugak.kodi

**Comment by khalilpeter2** [comment]
I’m still getting this error, should I just downgrade until you send out an update? paste.kodi.tv/wuweqatiwi.kodi

**Comment by jurialmunkey** [comment]
@khalilpeter2 

If you don't update the plugin then of course you will continue to get the error.

Your log shows v5.1.9 installed yet latest release containing the fix is v5.1.10 which was made 8 hours ago. 

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases

**Comment by khalilpeter2** [comment]
Ahh I see, I needed to refresh the repo because it still had the old version

**Comment by xyzfre** [comment]
Thank you @jurialmunkey working perfected👌🏼 again
