### ISSUE TITLE
[Question] Resuming netflix videos (and possibly from other addons)

### ISSUE THREAD

**Issue by pgranat** [jurialmunkey/plugin.video.themoviedb.helper#1038]
### Describe the feature that you'd like

Hi,
according to https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/178 in Matrix resuming videos may work in some players/addons, although I found no proof here, that's why I ask whether it should. If it should and I am doing something wrong then I will provide logs.

Using: 
- Os: Raspbian GNU/Linux 11 (bullseye)
- Platform: Linux ARM 32-bit
- Kodi (19.4 (19.4.0) Git:20221007-166303c4f0)
- plugin.video.themoviedb.helper: v5.0.55 (last for matrix)
- plugin.video.netflix: v1.21.0  Enable STRM resume workaround, Ask to resume the video turned on

### Why is this feature needed? What problem does it solve?

Resuming videos is very nice to have feature

### Steps to reproduce.

1. Go to netflix plugin
2. Play random episode of random series
3. Scroll to 00:05:00
4. Stop video
5. Go back to the same video in netflix plugin it shows possibility of resuming from 00:05:00
6. Go to tmdb helper plugin
7. Select same series and episode from point 2 and 5
8. Use Play in Netflix (stock netflix.json unmodified)
9. Video starts from the beginning
10. Scroll video to 00:06:00
11. Stop video
12. Go back to netflix plugin - available resume from 00:06:00 so resume point is saved
13. Go back to tmdb helper - video starts from beginning

### Screenshots and Additional Info

Thanks for your work!

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Kodi saves resume point in the item that you played from. If you play from TMDbHelper then the resume point is saved to the TMDbHelper item. If you play from Netflix, the resume point is saved to the Netflix item. Playing an item from TMDbHelper will not use the Netflix resume point (and vice versa). This is simply how Kodi resume points work and is not something that can be fixed without a hack.
