### ISSUE TITLE
Trakt slug in Up Next

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#104]
When trying to play an episode via "Up Next" I am getting an error due to no Trakt ID being passed to the player (similar to #80).

Playing the same episode directly via TMDBh --> tvshow --> season 1 --> episode, works fine.

"McMillion" is an example show with the problem.

**Comment by skyfsza** [comment]
I was using the following onclick to trigger the play:

PlayMedia(plugin://plugin.video.themoviedb.helper/?info=play&amp;season=$INFO[Container.ListItem.Season]&amp;type=episode&amp;episode=$INFO[Container.ListItem.Episode]&amp;tmdb_id=$INFO[Container.ListItem.Property(tmdb_id)])

Changing to the following has fixed the issue
PlayMedia($INFO[Container.ListItem.FileNameAndPath]) 

It looks like the TMDB_Id for the item is being set incorrectly:
Container(53012).ListItem.Property(tmdb_id) 2050636
plugin://plugin.video.themoviedb.helper/?info=play&season=1&type=episode&episode=3&tmdb_id=96213

**Comment by jurialmunkey** [comment]
No that's the correct tmdb_id - it's just that it's for the episode and you need the tvshow tmdb id.

You can get tvshow tmdb it with episode widgets with
`$INFO[Container.ListItem.Property(tvshow.tmdb_id)]

**Comment by skyfsza** [comment]
Thanks, will update.

Did this change?  been using just tmdb_id without problem up until recently.

**Comment by jurialmunkey** [comment]
> 
> 
> Thanks, will update.
> 
> Did this change? been using just tmdb_id without problem up until recently.

I think it's always been that way for episodes but I might have just forgotten about a change. It's more "correct" this way (though maybe slightly less convenient from the skin side of things).

**Comment by skyfsza** [comment]
Cool, updated my side.

Wiki example uses Property(tvdb_id), might want to update.

Thanks!

**Comment by jurialmunkey** [comment]
Ah yeah whoops! Updated now.
