### ISSUE TITLE
[BUG] trakt lists no longer visible 

### ISSUE THREAD

**Issue by Toweliechaos** [jurialmunkey/plugin.video.themoviedb.helper#1042]
### Describe the bug

The only lists visible from trakt now are default watchlists.

Consequently cannot import to library from curated lists

### Steps To Reproduce

1. Open settings
2. Go to library
3. Choose trakt list for library
4. Only 2 watchlists appear, no user lists

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Works fine for me.

![screenshot00313](https://user-images.githubusercontent.com/4618719/230773399-40ba1bd7-0c4c-4028-9c96-01322f560d7a.jpg)

**Comment by Toweliechaos** [comment]
v.4.10.14 installed 22/03/23 on kodi 20.1

![PXL_20230409_152845836](https://user-images.githubusercontent.com/67342652/230781844-8e1a1aa2-bbc7-44fc-b4b7-5c5a281c60bb.jpg)

Been like this for a week or two

**Comment by Toweliechaos** [comment]
Installed the jurialmunkey repository and then installed 5.1.10~nexus. Still the same, so reset library to default settings and then it worked.
