### ISSUE TITLE
Unable to filter by multiple languages

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1043]
I can't seem to get the following to work:-

`plugin://plugin.video.themoviedb.helper/?info=discover&amp;type=tv&amp;with_genres=Animation&amp;with_original_language=ja / en&amp;with_separator=OR&amp;page=1&amp;nextpage=false`

I can filter using using just one language code but not multiple.

**Comment by roidy** [comment]
Sorry, it's seems like it's an api limitation, with_original_language only accepts one language code :(

**Comment by jurialmunkey** [comment]
It should work. Use a pipe

`with_original_language=ja|en`

**Comment by roidy** [comment]
Big thanks, I'll give this a try.
