### ISSUE TITLE
[BUG] Matrix Dependency issue between AH2 and TMDB helper

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/plugin.video.themoviedb.helper#1044]
### Describe the bug

The latest version defines TMDB Helper 5.1.11 as a dependency. While people on Matrix cannot download it. Therefore, people on Mattix cannot update AH2 to the latest version because they cannot fulfill the dependency.

        <import addon="plugin.video.themoviedb.helper" version="5.0.52~nexus" />
        <import addon="plugin.video.themoviedb.helper" version="5.1.11~nexus" />

### Steps To Reproduce

Try to update AH2 on Matrix. 
max TMDB helper version available for Matrix is 5.05 i think

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by Mr-7mdan** [comment]
Sorry it should be on Ah2 repo not here

**Comment by jurialmunkey** [comment]
Matrix is no longer supported.
