### ISSUE TITLE
[BUG] Stuck to 0.0.54 version

### ISSUE THREAD

**Issue by tmbt78** [jurialmunkey/plugin.video.themoviedb.helper#1045]
### Describe the bug

I can't upgrade to the latest Artic Horizon version because Themoviedbhelper dependencies is not satisfied so i checked the latest version i can installa from your Repo and noticed i'm stuck to 0.0.54 version.
I tried to manually download the latest Themoviedbhelper version and install it from zip but if i try i got an error about xbmc.python.3.0.1 not installed.
I then checked the python version i got installed on my OSMC box and i got python 3.9.2-3 so i can't understand what the problem is 

Thanks
Mattia

### Steps To Reproduce

Just trying to update themoviedbhelper

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Debug log?

**Comment by tmbt78** [comment]
Should I enable debug log in Kodi and post the log here or there is a function inside your plug-in?

**Comment by jurialmunkey** [comment]
I just need some sort of log otherwise I can't see what is happening.

Note that I no longer support Matrix. It sounds like you're expecting to be able to update to a Nexus version whilst still in Matrix.

**Comment by tmbt78** [comment]
You're right mate! OSMC is still based on Kodi Matrix ... so i guess i've to wait until they release a Nexus version ...
Thanks and sorry for the bug report.

Mattia
