### ISSUE TITLE
[BUG] library_airingnext stuck showing episodes that have already aired

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1048]
`plugin://plugin.video.themoviedb.helper/?info=library_airingnext&tmdb_type=tv`

There seems to be a bug with this widget. If a show airs all it's episodes at once and has no more episodes to air then the last episode is never removed from the widget.

For example the show Tiny Beautiful Things aired all 8 of it's episodes on  April 7th, it is now April 19th and episode 1 is still stuck in the widget :(

![screenshot00007](https://user-images.githubusercontent.com/4118048/233171457-4c5739fe-f6b7-4b5d-a7a9-7a89b19da85c.jpg)

**Comment by jurialmunkey** [comment]
Please don't delete the bug report template. It's there for a reason to help me keep bug reports organised.
