### ISSUE TITLE
Translation does not work.

### ISSUE THREAD

**Issue by PostnikovArtem** [jurialmunkey/plugin.video.themoviedb.helper#105]
Hello! I use your plugin with the installed language "Russia". As well as the arctic zephyr 2 theme for kodi leia. Tell me why he does not translate the status of the series?
<img width="1885" alt="eeeeee" src="https://user-images.githubusercontent.com/27950783/74991878-564d8e80-5458-11ea-846f-c974ccfd620d.png">

**Comment by PostnikovArtem** [comment]
On the official website, everything looks correct. 
<img width="697" alt="2121" src="https://user-images.githubusercontent.com/27950783/74992225-8eed6800-5458-11ea-8a19-795c8d4ec332.png">

**Comment by drinfernoo** [comment]
Not all of the strings have been translated yet, especially in AZ2, since the add-ons are still in development.

**Comment by PostnikovArtem** [comment]
In AZ2, I did not find a single line with a similar name, as they directly expect from the site?

**Comment by PostnikovArtem** [comment]
There is only a line in the code that is responsible for the output of the line:

`        <include content="Object_Info_TextPairs">
            <param name="pad" value="16" />
            <param name="name" value="Status" />
            <param name="label" value="ListItem.Property(Addon.Status)" />
        </include>`

**Comment by jurialmunkey** [comment]
Unfortunately the TMDb API doesn't appear to translate the status.

Here is a snippet of the API response I get for `ru-RU` language/country for The Expanse. As you can see, the plot overview is translated but the status field is not.

```json
{
  "backdrop_path": "/beIjmWr3OBOtcWK4tKMObOIDJ1C.jpg",
  "original_language": "en",
  "original_name": "The Expanse",
  "overview": "Действие фильма разворачивается через двести лет со дня сегодняшнего, когда конфронтация между Землёй, бывшими марсианскими колониями и астеридными посерениями достигла максимального напряжения.\n\nСыщик, привыкший, не смотря ни на что, доводить всё до конца, расследует дело об исчезновении дочере одного из богатейших и влиятельных людей на Земле. В ходе расследования его путь пересекается с необычным экипажем новейшего боевого космического корабля. И кто бы мог подумать, что поиск молодой женщины приведёт к раскрытию величайшего заговора, поставившего человечество на грань полного уничтожения?..",
  "popularity": 41.358,
  "poster_path": "/oiz6iy7oiwiT4DmiNuXKURaV0zb.jpg",
  "status": "Returning Series",
  "type": "Scripted",
  "vote_average": 7.7,
  "vote_count": 837
}
```

I imagine it is this way to allow for consistent comparing. It would be difficult for skins to check if the status is "Continuing" or "Ended" etc. if it was translated.

**Comment by PostnikovArtem** [comment]
Thanks for the answer! Is it possible in this case to add a check of the incoming value? For example, if "status" returned "Returning Series", then replace it with "В эфире", otherwise "Окончен".

**Comment by jurialmunkey** [comment]
> 
> 
> Thanks for the answer! Is it possible in this case to add a check of the incoming value? For example, if "status" returned "Returning Series", then replace it with "В эфире", otherwise "Окончен".

It is possible but as I explained before then I will need to maintain translations for every possible language in the addon and it will prevent skinners from checking the status.

Really the translation needs to be done inside the skin.

**Comment by PostnikovArtem** [comment]
How is this possible to realize inside the skin? If it’s not difficult for you, could you help me with this? The ru-RU key for the TV statuses are - [here](https://github.com/travisbell/tmdb-web-translations/blob/master/locales/ru-RU.yml#L2872-L2878) Thanks.
