### ISSUE TITLE
🖐️Search with Pastebin via Tmdb Helper HS✔️

### ISSUE THREAD

**Issue by victore447** [jurialmunkey/plugin.video.themoviedb.helper#1051]
### Describe the bug

👋**Search with vstream player via pastebin in Tmdb Helper is HS**.  
![Pastebin (6)](https://user-images.githubusercontent.com/48101775/236528442-2687ca03-ebce-4c13-a125-2247b11b4601.jpg)

☝️**On the other hand when I go to the vstream addon via pastebin there is no problem.**
![Pastebin (3)](https://user-images.githubusercontent.com/48101775/236529493-aa688971-6ce3-428c-a7a8-813eb167c27e.jpg)

 ☝**The message is “protect by Cloudflare, try FlareSolverr”.**
![46](https://user-images.githubusercontent.com/48101775/236531040-06b24a9a-6ac3-467d-b561-b1928058f1f2.gif)
![Pastebin (4)](https://user-images.githubusercontent.com/48101775/236529523-fd0fa2ba-ce97-451e-a9d2-31cdc1907193.jpg)
![Pastebin](https://user-images.githubusercontent.com/48101775/236529554-566c7d18-435f-456a-9429-6beb84e76f24.jpg)

 ☝ **It's Uptobox, Doodstream etc.. which are displayed for the results.**
![46](https://user-images.githubusercontent.com/48101775/236531873-4672196a-c4bd-49bf-a961-c0352feb91b9.gif)
![Pastebin (2)](https://user-images.githubusercontent.com/48101775/236532046-af65dad9-fd21-4a6b-b3f5-3e55ec1475b4.jpg)

### Steps To Reproduce

☝️

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I don't make 3rd party players. Ask the author of the player

**Comment by victore447** [comment]
👋![195](https://user-images.githubusercontent.com/48101775/236627997-8d2fc882-f1b3-46c3-a5d1-17c3704add36.gif)
**OK**
