### ISSUE TITLE
Search by person is a blank screen

### ISSUE THREAD

**Issue by SJ1O** [jurialmunkey/plugin.video.themoviedb.helper#1052]
### Describe the bug

Search by person / actor is a blank screen after doing the search the actor shows up but when you click on the actor the screen is just 100% blank. I'm using the auramod skin. It shows up ok in the stock Kodi skin but not in the auramod skin

### Steps To Reproduce

Search - search people - enter actor name - click the actor = blank screen

Using auramod skin not tried any other skins but the stock Kodi skin.

I receive no error notification or anything 

### Debug log

![20230516_232558](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/121204283/0a458ec9-924f-4e67-b522-23d7fd3d4df6)
![20230516_232550](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/121204283/b357da39-01dc-4baa-add4-22c51c036776)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
>  It shows up ok in the stock Kodi skin but not in the auramod skin

There's your answer, it's a skin problem. You'll need to speak to the skin author.

Works fine in both AH2 and Estuary.
