### ISSUE TITLE
V5.1.14~nexus Clear logos show up as text in Info screen

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/plugin.video.themoviedb.helper#1053]
### Describe the bug

I Tried version v5.1.14~nexus clear logos show up fine on the main widget but on the info screen only clear logos show up as text not sure if it’s a bug or this is the new way now just wanted to keep you posted @jurialmunkey using Windows 11 Pro/ v21 alpha Omega,, thank you for all your dedication on this project ,AH2 is AMAZING 💯

### Steps To Reproduce

1. Click on a movie or TV show 2. Bring up the information screen and clear logos show up as text 

### Debug log

//

### Screenshots and Additional Info

![5AF0C1A7-9A60-4AC5-ABDF-FF04CFF78E3F](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/49699869/f8836f92-f314-410c-8a36-2176a392565c)
![E847D081-CEBA-4BAD-9A82-F1E9CBDAC7B6](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/49699869/d92e0e43-1313-424c-9dba-73238ffb09c1)
![D74E9B25-0609-4E1B-8EE7-37B7463179A1](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/49699869/a7dc943f-d3c0-40e2-ace3-d05383e67ab0)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
5.1.14 hasn't even been released. Latest release version is 5.1.12

Either way, both versions display clearlogos properly for me on Nexus.

**Comment by xyzfre** [comment]
> 5.1.14 hasn't even been released. Latest release version is 5.1.12
> 
> 
> 
> Either way, both versions display clearlogos properly for me on Nexus.

I downloaded 5.1.14 from GitHub yesterday just to try it and I got that issue with clear logos on Nexus and Omega,,but on 5.1.12 clear logos work Perfect everywhere

**Comment by xyzfre** [comment]
I did some testing on my end it starts to happen right after this commit ✨ UseLocalWidgetContainer allows widgetcontainer property in infodial ,,I downloaded commit poll speed tweak ,and from this commit down clear logos still work perfect everywhere , Trying to explain the best that I can 🙁

**Comment by jurialmunkey** [comment]
I can't reproduce. What are the exact steps to cause the issue?

Sounds like a skin issue incorrectly setting a widgetcontainer id property to the info dialog when it shouldn't - but it must be in a specific scenario because when I click info from a widget row it works for me.

**Comment by jurialmunkey** [comment]
Only from fullscreen widget info button due to a Kodi bug. Fix in latest skin master,

For reference to skinners encountering this issue:
Kodi takes window ID from active window rather than window SetProperty is called from. If the SetProperty command happens after launching the dialog due to refocusing a control on Home with an `<onfocus>SetProperty()</onfocus>` trigger then the propery goes to the wrong window. Workaround by explicitly specifying the window ID in SetProperty.

**Comment by xyzfre** [comment]
Thank You @jurialmunkey for the workaround💯💯
