### ISSUE TITLE
TMDB is showing alot of indian shows 

### ISSUE THREAD

**Issue by daveftw84** [jurialmunkey/plugin.video.themoviedb.helper#1054]
### Describe the bug

in almost all the tmdb menus for tv shows are full of indian shows. anyway to filter these?

### Steps To Reproduce

open addon, go to tv shows, click currently airing

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Yes, it's really annoying but unfortunately nothing can be done with the options currently available in the TMDb API.

You can see on their API trello page that there's a ticket to address this issue with regional popularity spikes:
https://trello.com/c/LwiwQWmX/224-popularity-should-boost-by-a-visitors-region

Also this discussion page where Travis confirmed that nothing can be done until he adds that API feature:
https://www.themoviedb.org/talk/63bbd4e1a6e2d2008b3e74f1?language=en-AU

**Comment by jurialmunkey** [comment]
Recommend using the Trakt lists for popular/trending instead. Don't need a Trakt account to use these and generally have more relelvant results

**Comment by daveftw84** [comment]
while i got you can i bug you for something else. when adding search movies or tv show  tmdbhelper menus to my skin. enter search query menu keeps poping up after trying to search.

**Comment by daveftw84** [comment]
> Recommend using the Trakt lists for popular/trending instead. Don't need a Trakt account to use these and generally have more relelvant results
any chance trakt has data to make a currently airing menu?

**Comment by jurialmunkey** [comment]
There's already a Trakt calendar in TMDbHelper...

**Comment by daveftw84** [comment]
when adding search movies or tv show tmdbhelper menus to my skin. enter search query menu keeps poping up after trying to search. i tried two different skins now

**Comment by jurialmunkey** [comment]
Please keep issue threads to one issue. Closing this issue as it's an api limitation.
