### ISSUE TITLE
[BUG] library_airingnext stuck showing episodes that have already aired

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1056]
### Describe the bug

`plugin://plugin.video.themoviedb.helper/?info=library_airingnext&tmdb_type=tv`

There seems to be a bug with this widget. If a show airs all it's episodes at once and has no more episodes to air then it is never removed from the widget.

For example the show FUBAR aired all it's episodes on May 25th, it is now June 2nd and episode 1 is still stuck in the widget, see attached image. This happens for every show which airs all it's episodes at once and the only way to remove them from the widget is to delete the add-ons database and start again, which is not an ideal solution.

In fact this show should never even appear in the library_airingnext widget. Because it is season 1 of the show and was never in my library to begin with then before May 25th the widget would have no reference to it in the library and after May 25th the show would have no next airing episodes.

### Steps To Reproduce

No steps to reproduce it's just a bug with the widget.

### Screenshots and Additional Info

![fubar](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/4118048/e0367dbe-5645-40f2-9aba-95a2db7674ab)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Can you try that version and see if it fixes it? Added an extra check to make sure the "next aired" date from TMDb is actually in the future.

I think it might be due to users on TMDb inputting the wrong status as a placeholder before the show airs. If the status is Ended or Cancelled then TMDbHelper caches the item for 30 days to avoid unnecessarily rechecking the show for new episodes. An ended show shouldn't have a next aired date so normally it wouldn't show up in the list **unless** someone incorrectly adds the status before it airs.

As to why this show is showing up at all for you despite not being in your library, that I'm not sure. Probably something else in your library either with the wrong TMDb ID set or not enough metadata but similar, so the TMDb ID lookup can't get a proper match and that's the closest it finds.

**Comment by roidy** [comment]
Thanks, that cleared the item from the widget 👍 

I'll keep an eye on it and see what happens with the next show that aires all it's episodes.

**Comment by roidy** [comment]
After some more testing the initial problem seems to be solved, however this change introduces a new issue.

Episodes are disappearing from the widget on the exact day they air, meaning if an episode airs on the 7th of June then the episode disappears on that day, meaning you never get to see todays airing episodes. This never happened before the change, the episode always remained in the widget for at least the duration of the day it aired, sometimes a bit longer depending on air time.

**Comment by roidy** [comment]
The fix for this seems to be to change the `days` from -1 to -2

```
        items = [
            i for i in item_queue if i
            and is_future_timestamp(
                i['infoproperties'].get(f'{prefix}.original'),
                time_fmt="%Y-%m-%d", time_lim=10, days=-2)]
```

Does this look like an ok solution to you?

**Comment by jurialmunkey** [comment]
There should be no need for -2. We want to see items with airdates after yesterday which is what `days=-1` covers.

What exactly are you basing the idea that it isn't working correctly on? Are you sure the airdate, *as displayed in TMDbHelper*, is not a day earlier than you think?

For me it is working correctly as is. For instance, the show `From` airs today (11th June) and is showing in my list on 11th June as you can see in the screenshot:

![screenshot00355](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/4618719/47772664-e832-49d8-ace5-f062e402b870)

**Comment by roidy** [comment]
That's not the behaviour I'm seeing. At the time of posting in the UK its 9:40am on the 11th of June, as you can see 'From' has already been removed from the widget.

![days-1](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/4118048/5b926b51-49e8-4f3e-bc36-208905e9f5fc)
![days-2](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/4118048/0bb0fe34-e177-4411-9fbd-07e54db2d932)

Could this be a timezone issue? And as I said this was never an issue before the changes.

**Comment by jurialmunkey** [comment]
> Could this be a timezone issue? And as I said this was never an issue before the changes.

It shouldn't be a timezone issue because I'm in Australia UTC+10, so if anything it should affect me worse

I'm not quite sure what the problem could be but there's definitely something going wrong and it needs to be addressed. Expanding the date range will just cause the inverse issue for those not experiencing this bug.

**Comment by roidy** [comment]
Is the date checking base on just the day or is it based on the air time as well?

I'm stumped as I said the widget worked ok in this regard before the change but now episodes are clearly being remove for me early.

**Comment by jurialmunkey** [comment]
> Is the date checking base on just the day or is it based on the air time as well?

Makes a datetime object from the airdate only (no time) and then compares against datetime object for `now()` with time delta -1 day.

A datetime object from a date without a time should default to midnight. So a datetime object for 11/06/2023 should remain greater than `now() + timedelta(days=-1)` up until midnight of that day.
