### ISSUE TITLE
[BUG] Movie Set Specific

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1058]
### Describe the bug

I have some problems with the movie set details. When I use for movie set, for example:
`$INFO[Container(99950).ListItem.Property(Set.Years)]`
I don't get any info.
When I use in same container for regular movie, for example:
`$INFO[Container(99950).ListItem.Director]`
I get info without problems.
Am I doing something wrong or is this a bug?

### Steps To Reproduce

/

### Debug log

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
That's not a property for sets. That's a property for movies.

These are set specific properties:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Detailed-Item#movie-set-specific

**Comment by jurialmunkey** [comment]
Sorry, you're right, service monitor is not working for sets for some reason. Let me look
