### ISSUE TITLE
Title in base64

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#106]
Hi, 
I've opened an issue in the EmbyCon plugin repository and its creator has been very helpful in providing hints on how a player for his plugin would look like. Currently I've been able to get to search for films but only those that its name is a single word. According to him, the plugin is expecting the title to come base64 encoded. Is there any function available to do this?
Thanks.

**Comment by jurialmunkey** [comment]
Got a link to the issue thread?

**Comment by jurialmunkey** [comment]
@juanma-cvega - Can you test with latest. You should now be able to add `_url` to the keys to get a url encoded string.

e.g. 
`{title}` becomes `{title_url}` if you want it url encoded

**Comment by juanma-cvega** [comment]
I'll try once I get home tonight. In any case, have you had the time to read the whole issue thread on the EmbyCon repo? I guess one of the problems I mentioned there comes from using 'play_movie' instead of 'search_movie' as the configuration faush01 provided me with seems to do only searches. Is there anything that can be done from your addon to show the list of results as a dialog box (it now takes you to the results screen on the addon) or is this something on the targeted addon side?

**Comment by jurialmunkey** [comment]
See my comment in that thread:
https://github.com/faush01/plugin.video.embycon/issues/94#issuecomment-589579033

Basically you should use the `play_movie` method and use steps to ensure you get the correct item. 

You don't need a direct path to the addon's player - you just need a search url and then you can locate the correct item to play by matching in the next step.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#additional-steps

**Comment by jurialmunkey** [comment]
I've also just now add the option to use `{"dialog": "True"}` as a player step, which will open the current folder as a dialog to select the item to play. (@drinfernoo this option may interest you too)

**Comment by juanma-cvega** [comment]
As mentioned in the other thread, the `{title_url}` option works as well as the `{"dialog":"True"}` one. There are some things that would be nice if they could be improved as I mentioned in that thread but they are outside of the scope of this issue so I think it could be closed.

**Comment by jurialmunkey** [comment]
@juanma-cvega 

> Adding the step {"title": "{title}"} also works. It picks the first one available. Adding the year didn't work, it complains it cannot find any movie.

There might be differences between the year in tmdb and the year on embycon (also possible that embycon doesn't return year value).

> {"dialog":"True"} also works. But in this case it only returns a list repeating the same name as many times as videos found. No information available to tell the difference from one video to the other.

Can you get me a screenshot of this issue? That seems strange - it should show the label of each item, so unless embycon is returning the same label for every item this really shouldn't happen.


> Another thing to notice here is that, because the step to load a video by its title cannot be used when using the dialog option, there is no way to further refine the search.

I should be able to add something along these lines without too much difficulty. I'll keep you updated.

> In any case, there is always a popup saying 'No media type set' before showing the result, it being either the list of found movies, a dialog or just playing the first movie found.

Hmmm. That might be an issue on embycon end. Debug log would be needed to see what that's about.

> One thing I've noticed is that it may take some seconds before a video starts when not using {"dialog":"True"}. That's fine as the addon needs to make the proper call to start the video but there is no loading icon so it looks like nothing is actually happening. Is there any way to add some notification the video is being loaded?

I'm not sure that there is much that can be done about this issue. I'm pretty sure it is a gap from when TMDbHelper calls the Kodi player and the point where the player has resolved the file to play -- in that gap, TMDbHelper has already exited so it can't load a busy dialog and the plugin it is calling isn't active either (it's just kodi taking it's time to resolve the url).

**Comment by juanma-cvega** [comment]
> Can you get me a screenshot of this issue? That seems strange - it should show the label of each item, so unless embycon is returning the same label for every item this really shouldn't happen.

Here is a link to the screenshot. https://pasteboard.co/IVLWVaG.png

> Hmmm. That might be an issue on embycon end. Debug log would be needed to see what that's about.

In the other thread I added the logs I took when I was testing the player. Do you also need logs from your addon? I think I didn't see anything relevant there last time I checked. 

> I'm not sure that there is much that can be done about this issue. I'm pretty sure it is a gap from when TMDbHelper calls the Kodi player and the point where the player has resolved the file to play -- in that gap, TMDbHelper has already exited so it can't load a busy dialog and the plugin it is calling isn't active either (it's just kodi taking it's time to resolve the url).

That's a shame. Sometimes it's quite fast but some others it may take up to 10 seconds. Without any information it really seems like nothing is going on. But I guess nothing can be done about it.

**Comment by jurialmunkey** [comment]
> Do you also need logs from your addon? I think I didn't see anything relevant there last time I checked. Here is a screenshot of the error. It pops up right before the dialog box. https://pasteboard.co/IVM2z7r.png

Okay the "No Media Type Set" seems to be an EmbyCon issue (I've never seen that error message before). I'm guessing that something in your search path is not configured correctly - most likely EmbyCon expects a parameter that tells it the media type and maybe you've used the incorrect syntax.

I don't need the log as I don't think that's anything from my end (I thought it might be initially but with that screenshot I'm fairly certain it isn't anything that TMDbHelper is doing.)

> Here is a link to the screenshot. https://pasteboard.co/IVLZZDs.png

I see what you mean about the select dialog. I'm not quite sure what else I could do from my end of things. I could show the file path but I think that might make things just as confusing. I think the only solution is for EmbyCon to append something to the item label to identify the quality.

> That's a shame. Sometimes it's quite fast but some others it may take up to 10 seconds. Without any information it really seems like nothing is going on. But I guess nothing can be done about it.

Yeah it's frustrating. I don't know why Kodi isn't calling the busy dialog. I can't really keep my plugin alive to show the busy dialog until the player starts playing because it would interfere with plugins that need to show a progress dialog or a folder of sources to select from.
