### ISSUE TITLE
[BUG] Missing PVR info and artworks from pvr widgets

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1061]
### Describe the bug

As the title says. When I put it as content:
```
pvr://channels/tv/*
pvr://channels/tv/*?view=lastplayed
```
tmdb helper doesn't return any data or artwork. 
I'm using container method for monitor. Any other widget works without problems. Also the default kodi listitems works as it should with pvr widgets, also skin helper service. Can something be done here?

### Steps To Reproduce

-

### Debug log

-

### Screenshots and Additional Info

-

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
How to recreate exactly and what version of TMDbhelper are you using? Because pvr widgets work for me and I recently made changes specifically to fix them.

**Comment by jurialmunkey** [comment]
You can see the commit which covers the conditions here https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/bfe42a8dfc9a4a090c1a23929a6403f7e992e4c5#diff-f1e5768999a9f644137cb9d3bebc82456093cb3e3f14b2d94f28a3d61d80f519

As long as the listitem has channelnumberlabel and you haven't set the setting to disable pvr lookups then it should be treated as a pvr widget.

Also note pvr lookups are very fuzzy and don't always work because some pvr items don't provide good metadata

**Comment by matke-84** [comment]
Are you kidding me? I didn't even notice that there was a new version 3.1.17. I was on 3.1.16. Thanks.
I just have one more question. How to use tmdb helper monitor for OSD? It's not very clear to me.

**Comment by jurialmunkey** [comment]
> Are you kidding me? I didn't even notice that there was a new version 3.1.17. I was on 3.1.16. Thanks.

Haha good timing.

> I just have one more question. How to use tmdb helper monitor for OSD? It's not very clear to me.

Do you mean for the currently playing item? Via standard window properties:
`$INFO[Window(home).Property(TMDbHelper.Player.PROPERTY)]`

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor#player-monitor

**Comment by matke-84** [comment]
I tried with:
```
$INFO[Window(home).Property(TMDbHelper.Player.Poster)]
$INFO[Window(home).Property(TMDbHelper.Player.Art.Poster)]
```
Does not work.

But for example this works
`$INFO[Window(Home).Property(TMDbHelper.Player.Director.1.Thumb)]`

Where am I wrong?

**Comment by jurialmunkey** [comment]
Do you have fanarttv enabled for service monitor?

**Comment by matke-84** [comment]
Yes.

**Comment by matke-84** [comment]
No, definitely something is wrong with the player artwork. Have you tried to test it yourself? Do I need to open an new issue?

**Comment by matke-84** [comment]
This is driving me crazy. Now the posters work for standard content, but they still don't work when I play a live program. I don't know where the problem is. I have the name of the movie, plot, year... but no artwork, except for the channel logo. All this is work in PVR dialog info.

**Comment by jurialmunkey** [comment]
Player monitor is not enabled for pvr. Channel  switches are too difficult to manage

**Comment by matke-84** [comment]
Ohhhhh. A pity. If nothing else, it's easier for me now. I started to go crazy thinking that I was doing something wrong.
