### ISSUE TITLE
[Question] MultiSearch

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1062]
How do I perform a multisearch, I want a widget that returns mixed search results for movies, tv and person in one list. I've tried:-

```
plugin://plugin.video.themoviedb.helper?info=search&type=movie|tv|person&;query=foobar
plugin://plugin.video.themoviedb.helper?info=search&type=movie,tv,person&;query=foobar
```

Neither work, how do I specify a multisearch in the plugin path.

The code seems to indicate it should be possible:-

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/0d3529bc8b18fea50eb29f3f33f1553ded0fb775/resources/tmdbhelper/lib/api/tmdb/search.py#L55-L72

**Comment by jurialmunkey** [comment]
That is the directory which lists all the different search endpoints and history when you go into tmdb->search. 

There is no multi search in tmdbhelper currently. Kodi doesn't really do well with mixing content types so I never implemented a search function that allows it.

**Comment by roidy** [comment]
>That is the directory which lists all the different search endpoints and history when you go into tmdb->search.

Right, my mistake, sorry.

>Kodi doesn't really do well with mixing content types

Sure in the library views you can't mix content but in a general list like a widget you can without any problems. I have a custom plugin for my skin that supplies multiple mixed content widgets that contain movies, episodes and tv shows all in the same list. I also have a custom search widget that mixes movies, tv shows and episodes,  which is why I would also like to be able to do the same with content from TMDb.

Here's an example of my search plugin that mixes movie, tv show and episode content types:- 
![search](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/4118048/e04971dc-6d6b-47b2-8c68-7fd1a8c943ad)

**Comment by roidy** [comment]
Any chance of getting a widget that returns movie, tv and people search results in one list please.

**Comment by Uka-Uka** [comment]
@roidy Hello! Cool theme! Which one is that, mate?

**Comment by roidy** [comment]
@jurialmunkey Thanks, that works perfectly 👍 Couple of quick questions:-

1. What exactly does this return? From my testing I'm assuming just movie, tv and person, is that correct?
2. Is there a property on person listitems to denote it's a person? For example movies have the DBTYPE of movie.

@Uka-Uka It's a skin I'm creating based on the Roku design. Keep an eye on the Kodi forums, I'll be announcing it in a few weeks.

**Comment by jurialmunkey** [comment]
It uses search/multi endpoint which is movie, tv, person according to docs
https://developer.themoviedb.org/reference/search-multi

You can get item's path params with item property prefix (just like you can get container path params with param prefix). You can use type param to determine type of the item
`String.IsEqual(ListItem.Property(item.type),person)`

**Comment by roidy** [comment]
> It uses search/multi endpoint which is movie, tv, person according to docs

Thanks, didn't know tmdb api had a multi endpoint, I haven't used the api in awhile and looking at your link it looks like the api is in the process of being updated. Also the naming of the new type `both` threw me a little bit as it returns 3 different types.

>You can get item's path params with item property prefix (just like you can get container path params with param prefix). You can use type param to determine type of the item
String.IsEqual(ListItem.Property(item.type),person)

Perfect, I only asked what was returned because if it is only the 3 types movie, tv and person then person can be determined by DBTYPE not being movie or tvshow, but yep the property item.type is probably safer.

**Comment by jurialmunkey** [comment]
"both" definitely was a poor type name choice. I made it years back for trakt lists which combine types. It really should've been called "all" or "multi" but no sense changing it now and breaking skins.

Yeah item.type property will be more future proof, especially if they expand the multi search endpoint in the future to allow collections, keywords and companies etc
