### ISSUE TITLE
[Feature] Episode name

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1063]
### Describe the feature that you'd like

Is there a possibility, that is, does the tmdb api support the episode name? Now we have the season number and the episode number, it would be very useful for example for PVR content.

### Why is this feature needed? What problem does it solve?

-

### Steps to reproduce.

-

### Screenshots and Additional Info

-

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
`Container(MONITORID).ListItem.Title`
`Window(Home).Property(TMDbHelper.ListItem.Title)`

**Comment by matke-84** [comment]
No, this doesn't work with episodes in PVR. It gives the name of tv show, not the episode. That's why I asked.

**Comment by jurialmunkey** [comment]
Works for me. Maybe your PVR doesn't have good enough season and episode numbers to get a proper match.

**Comment by jurialmunkey** [comment]
![screenshot00357](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/4618719/ed0bbf30-18dd-469d-aec6-34a837bb8114)

**Comment by matke-84** [comment]
Interesting that it gives me a good number for the season and episode but not for the episode title.

**Comment by jurialmunkey** [comment]
Are you sure it isn't the **total** Episode and Season count for the tvshow? Remember that ListItem.Season is the same as ListItem.Property(totalseasons) for dbtype=tvshow, and ListItem.Episode is the same as ListItem.Property(totalepisodes) for dbtype=tvshows/seasons.

Does your PVR put anything in ListItem.Season and ListItem.Episode (the item itself NOT TMDbHelper)? TMDbHelper isn't a magic crystal ball -- it needs some indication of what season and episode it is from the PVR.

**Comment by matke-84** [comment]
When it works for you, it's probably up to my pvr.
