### ISSUE TITLE
🖐️Context menu (Create custom list)

### ISSUE THREAD

**Issue by victore447** [jurialmunkey/plugin.video.themoviedb.helper#1064]
![155](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/48101775/5ad5bdc7-335e-4a3b-b204-167a5bd37023)**Hello**,
 Developers of video plugins like "**Cumination**" have long integrated into their contextual menu the possibility of creating a custom list (_Create Custom List)_ in the home page.  [👉Home Cumination Repo.](https://github.com/dobbelina/repository.dobbelina)
 ![46](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/48101775/92f6c879-d98a-470c-8a6d-fdcc06cec8e6)
 ![custom list](https://github.com/Kodi-vStream/venom-xbmc-addons/assets/48101775/b8ae4095-8dec-4136-ae43-260ddc7c3eee)

 ☝️ On the Tmdb site It is possible to create a personal list.  Can't you do this so we can create our own custom list of movies or series etc.  (by genre etc.) in a folder?

 👆 Because when there are a lot of additions it takes time after going through each page.

 **Thanks for the reply** ✅

**Comment by jurialmunkey** [comment]
You can make custom lists of films and tv on trakt and see them under trakt > user lists.

You can make folders of folders using library node editor addon

**Comment by victore447** [comment]
> ![155](https://user-images.githubusercontent.com/48101775/246115725-5ad5bdc7-335e-4a3b-b204-167a5bd37023.gif)**Hello**, Developers of video plugins like "**Cumination**" have long integrated into their contextual menu the possibility of creating a custom list (_Create Custom List)_ in the home page. [👉Home Cumination Repo.](https://github.com/dobbelina/repository.dobbelina) ![46](https://user-images.githubusercontent.com/48101775/246105120-92f6c879-d98a-470c-8a6d-fdcc06cec8e6.gif) ![custom list](https://user-images.githubusercontent.com/48101775/246105252-b8ae4095-8dec-4136-ae43-260ddc7c3eee.jpg)
> 
> ☝️ On the Tmdb site It is possible to create a personal list. Can't you do this so we can create our own custom list of movies or series etc. (by genre etc.) in a folder?
> 
> 👆 Because when there are a lot of additions it takes time after going through each page.
> 
> **Thanks for the reply** ✅



> You can make custom lists of films and tv on trakt and see them under trakt > user lists.
> 
> You can make folders of folders using library node editor addon

👋I don't understand what this library node editor add-on is. Can you clarify?

**Comment by jurialmunkey** [comment]
https://kodi.wiki/view/Add-on:Library_Node_Editor

It allows you to make folders (nodes) in the library containing other folders or content.

**Comment by victore447** [comment]
🖐️Thank you, 
☝️But **the Library Node Editor addon** only works with the local kodi media library (Music, Movies, etc.)? 
👆I looked at how it works and can't see the paths to follow to synchronize with Tmdb Helper.  ✔️

**Comment by jurialmunkey** [comment]
You are wrong. Library node editor also allows you to add plugin paths as folders. I use it all the time myself to create custom folders of shortcuts

If you want a custom list of movies and tvshows then use trakt lists or mdblists - both of which tmdbhelper supports

If you want custom directories of shortcuts to specific folders then use library node editor.

All the tools to do what you want already exist without me coding anything.

**Comment by victore447** [comment]
👋**Good thank you**, 
I will only use Trakt which is simple but limited to 10 lists after asking to pay. 
☝️For "Library note editor" and "Mdblist" you need to have time because too many readings and things to do (too complicated  ).  ✔️

**Comment by jurialmunkey** [comment]
As of 5.1.22 there is a context menu item to create your own nodes. These will appear in TMDbHelper > Nodes.

**Comment by victore447** [comment]
👋![205](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/48101775/8739ee9a-55ce-445c-9585-ff59b2dc2da1) **_Hello,_** 
_I just tested this.
Thank you for creating this contextual 
menu for creating our own nodes._



![22645-applause01](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/48101775/b8f401da-df65-421b-8278-a86333300b09).      ✅
