### ISSUE TITLE
[BUG] OMDB timeout error

### ISSUE THREAD

**Issue by luckylukz02** [jurialmunkey/plugin.video.themoviedb.helper#1065]
### Describe the bug

Frequent OMDB timeout error. Using Arctic Horizon 2 whilst browsing widgets. 

### Steps To Reproduce

Browsing widgets setup with Arctic Horizon 2

### Debug log

2023-06-20 23:14:59.181 T:40490    info <general>: [plugin.video.themoviedb.helper]
                                                   ConnectionTimeOut: HTTPSConnectionPool(host='www.omdbapi.com', port=443): Read timed out. (read timeout=15)
2023-06-20 23:14:59.187 T:40490    info <general>: [plugin.video.themoviedb.helper]
                                                   ConnectionError: timeout HTTPSConnectionPool(host='www.omdbapi.com', port=443): Read timed out. (read timeout=15)
                                                   Suppressing retries for 30 seconds

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Nothing I can do about that. It means omdb server has failed to provide the request. I can't make their server better.

**Comment by jurialmunkey** [comment]
Also you can disable the notification dialog for connection errors in 
`TMDbHelper Settings > Other > Connection Error Notifications`

Disable the notificaitons, press OK to save settings and then restart Kodi to apply.

**Comment by luckylukz02** [comment]
> Also you can disable the notification dialog for connection errors in `TMDbHelper Settings > Other > Connection Error Notifications`
> 
> Disable the notificaitons, press OK to save settings and then restart Kodi to apply.

Thanks, that should take care of it. Wasn't causing any issues other than the frequent notification.

**Comment by jurialmunkey** [comment]
Ignore above commit. Unrelated to this issue. Accidentally referenced wrong issue number.
