### ISSUE TITLE
[Feature] Clearing property, hide control...

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1066]
### Describe the feature that you'd like

I'm using container method for monitor. The problem is that every time I open some dialog the label or anything else contains the old data from the last item on second. E.g. I open local Movie sets, then I go to addons and start opening tmdb helper, everything I use from tmdb helper (ratings, plot, year...) appears for a second from the previously opened movie set and then opens a dialog that i wanted. Can this be improved somehow or is there some way to overcome it. Thanks.

### Why is this feature needed? What problem does it solve?

-

### Steps to reproduce.

-

### Screenshots and Additional Info

-

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
It sounds like you should be using window properties instead. This is the trade-off of using the container method - the whole point is that it keeps the items in different windows and dialogs separate.

**Comment by jurialmunkey** [comment]
Also you can easily get around this issue by using variables which compare the current item details with what's in the monitor

A good option for simple comparison is property(base_label) in your container with listitem.label

Or you can get a "perfect" match using property(folderpath) with listitem.folderpath

Both those properties come directly from the base item rather than online, so they're easy to match..

The other option is to check the is updating status
String.IsEmpty(Window(Home).Property(TMDbHelper.IsUpdating))

**Comment by matke-84** [comment]
I'm not sure I understand all of this. I would like to keep the container monitor system because you said that it is faster and puts less strain on the processor, and that is important to me because of Android. Here's how I use it.
```
<variable name="GetYear">
	<value condition="!String.IsEmpty(Container(99950).ListItem.Property(Set.Years))">$INFO[Container(99950).ListItem.Property(Set.Years)]</value>
	<value condition="!String.IsEmpty(ListItem.Year)">$INFO[ListItem.Year]</value>
	<value condition="!String.IsEmpty(Container(99950).ListItem.Year)">$INFO[Container(99950).ListItem.Year]</value>
</variable>
```
```
    <include name="Year_Details_Row">
        <control type="label" id="6114">
            <visible>!String.IsEmpty(Control.GetLabel(6114))</visible>
            <posy>6</posy>
            <height>35</height>
            <width>auto</width>
            <aligny>center</aligny>
            <font>Reg26</font>
            <textcolor>$INFO[Skin.String(BingieDeatailsTextColor)]</textcolor>
            <label>$VAR[GetYear]</label>
            <include>Default_Visible_Fade</include>
        </control>
    </include>
```
Can you explain to me on this example?

**Comment by jurialmunkey** [comment]
`String.IsEqual(Container(99950).ListItem.Property(folderpath),ListItem.FolderPath)`

**Comment by matke-84** [comment]
You mean like this?
```
<variable name="GetYear">
	<value condition="!String.IsEmpty(Container(99950).ListItem.Property(Set.Years)) + String.IsEqual(Container(99950).ListItem.Property(folderpath),ListItem.FolderPath)">$INFO[Container(99950).ListItem.Property(Set.Years)]</value>
	<value condition="!String.IsEmpty(ListItem.Year)">$INFO[ListItem.Year]</value>
	<value condition="!String.IsEmpty(Container(99950).ListItem.Year) + String.IsEqual(Container(99950).ListItem.Property(folderpath),ListItem.FolderPath)">$INFO[Container(99950).ListItem.Year]</value>
</variable>
```

**Comment by matke-84** [comment]
This is a solution, but it has the same effect as the window properties. Each time an item is updated, it flashes on a second. It just doesn't go smoothly. I will have to find some other solution, such as showing only for movies, tvshows... Given that all the data comes from tmdb... Or if you have any other suggestion...

**Comment by jurialmunkey** [comment]
There is no solution to the delay. The monitor cannot set the container item before it exists.

**Comment by matke-84** [comment]
Ok. Thanks.
