### ISSUE TITLE
[Bug] Mark as Watched Context Menu not working correctly

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#107]
Hi,
I've been testing how to replace library integration with Trakt TV show collection. Among the TV shows I've seen there seems to be some episodes not marked as watched so I tried the context menu to fix this. But it didn't do anything. It seems like it tries to do something but then nothing happens. I've checked in Trakt and the episodes are still not marked as watched. As far as I know, the context menu comes from Kodi but is there any way to link the 'Mark as watched' option with Trakt when triggered from the addon?

**Comment by jurialmunkey** [comment]
In the Kodi library, the "Mark as Watched" marks it as watched in the local db - nothing to do with my addon and I can't change that action.

When a file is added to the library, it is the equivalent of a shortcut with a link to the play command - anything you do to that shortcut has no connection to my addon (just like if you changed the name of a shortcut on your desktop wouldn't do anything to the program itself).

If you want the details of your library watched status to be synced with Trakt, then you will need to use the Trakt addon.

**Comment by juanma-cvega** [comment]
Sorry, I think I didn't explain myself properly. I'm inside your addon when I use the context menu 'mark as watched', not in the Kodi library. I was just trying to ask if it was possible to provide the same functionality as when in the Kodi library so I can mark a movie or TV show as watched in Trakt while browsing Trakt lists on your addon.

**Comment by jurialmunkey** [comment]
Ah, actually I see what you mean - it only shows on playable items not the folders. Kodi seems to add that - maybe there is a way to do something with it... I'll have a look at the Kodi ListItem python docs.

**Comment by jurialmunkey** [comment]
Also, just use the "Add/Remove from Trakt History" context menu item to mark as watched in Trakt.

**Comment by juanma-cvega** [comment]
I just tried 'Add/Remove from Trakt history' and it actually removed the episode from the collection instead of adding it to the list of watched ones. Not really sure of what happened there. There is an addon trakt context menu in the official kodi repo that adds options to control videos on trakt but it seems it's not compatible with your plugin. I just tested it and it throws an exception.

**Comment by jurialmunkey** [comment]
Ah yep seems something weird is still going on with the context menu entry. It really is the bane of my existence - the in list options in the details section were easy to implement and work properly but the context menu options are being a real pain!

I can't seem to find a way to alter what the mark as watched does. I'll ask around the kodi team as it seems weird that kodi would add the option but then give no way to modify it's action.

And I'll look into the trakt add to history context menu option as something weird is going on there (I really thought I had all the bugs for that ironed out but apparently not!)

**Comment by abbaskip** [comment]
> Also, just use the "Add/Remove from Trakt History" context menu item to mark as watched in Trakt.

Regarding this context menu item, is there a way to be able to always be able to unwatch or watch? Occasionally it seems the add-on gets the Trakt history wrong and thinks something is marked as unwatched, so i can't remove Trakt history from it (as this menu item only allows you to do the opposite to what it believes is current state). Ideally i would always be able to say Mark this as unwatched or mark this as watched - regardless of current state.
