### ISSUE TITLE
[BUG] Watchlist widget not updating

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/plugin.video.themoviedb.helper#1070]
### Describe the bug

when creating a watchlist widget using themoviedb helper (Trakt>Your Lists> Watchlist) is displayed fine. However when you update the list on Trakt, this is not reflected, the widget is not being updated with the added/removed movies from the watchlist.

### Steps To Reproduce

add a watchlist (Trakt> Your Lists> Watchlist)
widget is displayed normally as it should
remove/add a movie to the Trakt watchlist on the web
widget is not updated

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
You need to make Kodi refresh the widget. 

Once TMDbHelper has created the items and hands them over to Kodi, the TMDbHelper instance no longer exists and so cannot update or change items. Kodi needs to reload the widget for TMDbHelper to be called again and make changes to the items.

Kodi will reload widget containers after playback stops or after a library update.
