### ISSUE TITLE
[Feature] Significant improvement in search results

### ISSUE THREAD

**Issue by The-cpu-max** [jurialmunkey/plugin.video.themoviedb.helper#1072]
### Describe the feature that you'd like

There are cases where the movie is not in the add-on
What I suggest is that the plugin will perform a pre-search
And write next to each extension how many sources it has

### Why is this feature needed? What problem does it solve?

The feature will help to know beforehand if there are sources or not
Also on Netflix and others

### Screenshots and Additional Info

![ללא שם](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/102416233/1747374e-5bf9-455c-bcfb-7720f2da5f8d)

I made an example
### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
This would be ridiculously slow and it's not really possible anyway.
