### ISSUE TITLE
[BUG] RTL Problem Solution

### ISSUE THREAD

**Issue by The-cpu-max** [jurialmunkey/plugin.video.themoviedb.helper#1073]
### Describe the bug

https://github.com/xbmc/xbmc/issues/23445
A solution to the problem of the RTL was found

### Steps To Reproduce

A solution to the problem of the RTL was found

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
As mentioned in that thread, it is a dirty hack rather than a proper solution. I do not want to add a hack.

**Comment by The-cpu-max** [comment]
> As mentioned in that thread, it is a dirty hack rather than a proper solution. I do not want to add a hack.

What will happen if you use it?
It will only solve the problem
It won't hurt anything else

**Comment by jurialmunkey** [comment]
It will break search history and any internally constructed param which is already in the correct order.
