### ISSUE TITLE
[Feature] Add TMDB Lists 

### ISSUE THREAD

**Issue by rahaaatul** [jurialmunkey/plugin.video.themoviedb.helper#1074]
### Describe the feature that you'd like

I'd like **TMDB lists** to be added in the addon.

### Why is this feature needed? What problem does it solve?

I have some lists in TMDB that I'd like to display in Kodi. 

Because It's easy to add and replace contents inside TMDB list, and Trakt is complicated for me.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Unfortunately TMDb doesn't have a good method to authenticate user accounts suitable for Kodi devices without a web browser.

The authentication process for TMDb needs a web browser. Embedded versions of Kodi like LibreELEC will not have a usable web browser and I don't want to add things which are platform specific.

The reason Trakt is possible is because it allows authentication from another device using a one time code. TMDb doesn't have an authentication method like that.

**Comment by rahaaatul** [comment]
But we can at least search and save lists from TMDB without authentication, no? @jurialmunkey 

For example, this is my public list: https://www.themoviedb.org/list/8259563

Can't I add by searching or adding the list number or a link? This won't be platform specific.

**Comment by jurialmunkey** [comment]
```
plugin://plugin.video.themoviedb.helper/?info=tmdb_list&list_id=3&tmdb_type=both
```

`list_id=` is the ID for the list
`tmdb_type=` can be `movie` `tv` or `both`

**Comment by rahaaatul** [comment]
@jurialmunkey can we do the same for the networks? I searched for [this network](https://www.themoviedb.org/network/866-tvn) but couldn't find it in the providers and networks.

`https://www.themoviedb.org/network/866-tvn`

Can we use **866-tvn** as an example in network provider `list_id=`/`network_id=` ?

Also **search network** in `TheMovieDB Helper` > `Search` is missing.
![image](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/86149861/1aa40cc5-e5f2-46eb-a39b-e0c0828e50b0)

**Comment by jurialmunkey** [comment]
Networks are companies. API only allows searching the studio ID of the company, not the network ID.
Use discover if you know the ID.

**Comment by jurialmunkey** [comment]
`plugin://plugin.video.themoviedb.helper/?info=discover&tmdb_type=tv&with_id=True&with_networks=866`

**Comment by rahaaatul** [comment]
> `plugin://plugin.video.themoviedb.helper/?info=discover&tmdb_type=tv&with_id=True&with_networks=866`

Thank you. It's working correctly. I was hoping to create something like Providers, but for Asian Dramas only. 

By the way, would you mind looking at [MyDramaList](https://mydramalist.com)? It's strictly for asian dramas, we can get lot of useful data from it to display in Kodi. But it has a private API. Here's what they are saying:

> _The MyDramaList API is currently in private beta. If you're interested in accessing it, please email contact@mydramalist.com with your intended use details. Include the title of your app or project in the subject line. Kindly note that access is not granted for data analysis, recommendation projects, or any use related to LLM or GPT-related applications. We appreciate your understanding._

I hope you do because it will help a lot of Asian drama fans, because in tmdb/trakt, it's rare for Asian drama shows to appear in the trending or most popular lists.

Currently I'm working around it by creating my own lists. But having an automated list would be much better.
