### ISSUE TITLE
[BUG] No Browse sorted list for Your Next Episodes

### ISSUE THREAD

**Issue by rahaaatul** [jurialmunkey/plugin.video.themoviedb.helper#1075]
### Describe the bug

Browse sorted list missing for Your Next Episodes and some others too.

### Steps To Reproduce

1. Go to Trakt
2. Find Your Next Episodes
3. Open Context Menu for Your Next Episodes

### Screenshots and Additional Info

![Missing Option](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/86149861/95f3e485-afdc-4692-bb7b-0985a6371657)

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/86149861/78c9957f-f0dc-4d31-aa0c-b2f02c0c2be0

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Your next episodes, in-progress shows, and still to watch sort method is defined in the TMDbHelper Settings

`TMDbHelper Settings > Widgets > Next episodes sort method`

You can set sort by airdate, lastweek, todays, recentlywatched

lastweek is a combo of recentlywatched and airdate -- items are sorted by recentlywatched but shows/episodes which aired in the last week are temporarily moved up to the front of the queue. 

The "todays" option does the same as lastweek but only for shows airing that same day.
