### ISSUE TITLE
[Feature] Like/Dislike

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1076]
### Describe the feature that you'd like

I wonder if there is any way to get this option? Since my skin is based on the Netflix look, I would like to somehow get a like/dislike button, like I have for local content. Is this possible with tmdb helper? Do any of api support this or is there already something similar that I could use for this purpose?

### Why is this feature needed? What problem does it solve?

-

### Steps to reproduce.

-

### Screenshots and Additional Info

-

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
I think the closest equivalent on Trakt is the "favorites" feature.

**Add/Remove Item from Favorites**
`Runscript(plugin.video.themoviedb.helper,sync_trakt,sync_type=favorites,tmdb_id=TMDBID,tmdb_type=tv)`
Replace TMDBID with $INFO containing the ID.
Alternatively you can use query params instead but much better to use ID.

**Favourites will appear in the favourites list**
`plugin://plugin.video.themoviedb.helper/?info=trakt_favorites&tmdb_type=tv`

**Use a hidden container filtered by TMDb ID to check if the item exists**
`plugin://plugin.video.themoviedb.helper/?info=trakt_favorites&tmdb_type=tv&filter_key=tmdb_id&filter_value=TMDBID`
Replace TMDBID with $INFO containing the ID. 

Alternatively you can filter by title instead if you don't have the ID but much better to use ID.
`plugin://plugin.video.themoviedb.helper/?info=trakt_favorites&tmdb_type=tv&filter_key=title&filter_value=TITLE`
Replace TITLE with $INFO containing the title.

**Comment by matke-84** [comment]
Yes, i thought of this too, but it still doesn't help me much. I need two buttons. One button will be like, the other will be dislike. As far as I understand, one button would do everything here, like the add to trakt list button, I don't know if I'm right?

**Comment by jurialmunkey** [comment]
Yes the command is a toggle but that doesn't mean you can't still have two buttons. Just set the onclick action of each button to check whether the item is in the hidden container or not e.g.
`<onclick condition="String.IsEqual(Container(1234).ListItemAbsolute(0).Property(TMDb_ID),Container(99950).ListItem.Property(TMDb_ID))"> Runscript(plugin.video.themoviedb.helper,sync_trakt,sync_type=favorites,tmdb_id=$INFO[Container(99950).ListItem.Property(TMDb_ID)],tmdb_type=tv)</onclick>`

And check for the reverse `!` condition for the other button.
