### ISSUE TITLE
widgets are adding menu title to widget titles

### ISSUE THREAD

**Issue by daveftw84** [jurialmunkey/plugin.video.themoviedb.helper#1078]
### Describe the bug

All the widgets i made with tmdbhelper is all of a sudden displaying the menus name next to the names i create for widgets. so trending movies is called trending trending movies. popular is popular popular movies, etc etc.

### Steps To Reproduce

create widgets out of menus in tmdbhelper using tmdbhelper 5.1.22

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by SJ1O** [comment]
You could delete the widget label and just put - or something. I had this issue when I was testing out auramod skin. Decided to just change skin. Using arctic fuse now and don't have that issue

**Comment by daveftw84** [comment]
Thanks for the tip!  I ended up removing label and using one given from
tmdb helper
