### ISSUE TITLE
playing from widgets is freezing kodi with 5.0.55

### ISSUE THREAD

**Issue by daveftw84** [jurialmunkey/plugin.video.themoviedb.helper#1079]
### Describe the bug

playing any item from a tmdb helper widget is causing my kodi to crash everytime. when i downgrade to the version on kodis offical repo. items play fine

### Steps To Reproduce

install auramod
set widgets with tmdbhelper
set default player to embycon

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [x] I have uploaded my debug log.

**Comment by daveftw84** [comment]
it happens only when i set the player to resolve, system freezes up, i tired windows and android... setting it to playmedia crashes kodi to OS home page. letting user pick plays when selecting resolve

**Comment by daveftw84** [comment]
[https://anontv.net/kodi.log](url)

**Comment by daveftw84** [comment]
setting debug logging seems to fix it?

**Comment by daveftw84** [comment]
ive updated log

**Comment by jurialmunkey** [comment]
I don't support Matrix anymore. 

This version of the plugin is massively out of date. Either use the official repo version or upgrade to nexus. I'm not bug fixing Matrix.

**Comment by daveftw84** [comment]
ok, sorry sir. i have it "fixed" by having it select addon instead of
preselcting
