### ISSUE TITLE
[Question] Upcoming question

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1086]
### Describe the feature that you'd like

Where does data for `plugin://plugin.video.themoviedb.helper?info=upcoming&amp;type=movie` come from because if I directly access the api endpoint `https://api.themoviedb.org/3/movie/upcoming` from a browser it gives me a completely different list.

The upcoming movies from the plugin returns a list of really obscure movies I've never heard of half of them, where as direct from the api I get a list of major releases and big budget movies.

### Why is this feature needed? What problem does it solve?

No problem just an odd difference between the plugin and the api.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Literally that path.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/060fc04b81af04f9860fede56bad4276b15184ad/resources/tmdbhelper/lib/addon/consts.py#L216-L218

**Comment by jurialmunkey** [comment]
Note that the api endpoint accepts region and language params so the results will differ depending on that setting.

**Comment by roidy** [comment]
That's strange, I've even deleted the plugin database to make sure I'm not getting cached results.
![screenshot00036](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/4118048/041be7c7-b112-4922-b49f-8ef0732161e2)
(I've deleted unnecessary data from the json response to fit more in)

As you can see the addon response is nothing like the api response. I'm not adding any region or language params to either the api call or the plugin so shouldn't both lists be identical?

**Comment by roidy** [comment]
I've used a custom discover to replicate the upcoming list using:-

`plugin://plugin.video.themoviedb.helper?info=discover&amp;type=movie&amp;with_id=True&amp;with_spearator=AND&amp;sort_by=popularity.desc&amp;primary_release_date.gte=T-7&amp;release_type=1&amp;region=US&amp;with_original_language=en&amp;nextpage=false`

This gives a much better list of upcoming movies. Still strange that the upcoming endpoint of the plugin doesn't match the api endpoint :(

**Comment by jurialmunkey** [comment]
>  I'm not adding any region or language params to either the api call or the plugin so shouldn't both lists be identical?

It is impossible not to have region and language. These params are set in the plugin settings.

API output I'm getting now for US region is pretty close to what you're getting:
`https://api.themoviedb.org/3/movie/upcoming?region=us`

```
"original_title": "Meg 2: The Trench",
"original_title": "Talk to Me",
"original_title": "Frozen",
"original_title": "Haunted Mansion",
"original_title": "THE FIRST SLAM DUNK",
"original_title": "Beauty and the Beast",
"original_title": "Dead Shot",
"original_title": "Blue Beetle",
"original_title": "Gran Turismo",
"original_title": "Teenage Mutant Ninja Turtles: Mutant Mayhem",
"original_title": "The Last Voyage of the Demeter",
"original_title": "Strays",
"original_title": "The Baker",
"original_title": "올드보이",
"original_title": "Sympathy for the Devil",
"original_title": "The Devil Comes to Kansas City",
"original_title": "Go West",
"original_title": "The Collective",
"original_title": "Dreamin’ Wild",
"original_title": "All Fun and Games",
```


If you enable the setting "ignore release filter" then you will get the same as an empty region call.
