### ISSUE TITLE
"Language" menu title

### ISSUE THREAD

**Issue by patkino** [jurialmunkey/plugin.video.themoviedb.helper#1087]
### Describe the feature that you'd like

Please add "language" list to the helper menu

### Why is this feature needed? What problem does it solve?

For users outside US/UK it'll be very useful, since for example Serbian movies never get to "trending" and "recommended" lists.
Tmdb has the feature of showing movies/shows in certain language (its actually more convenient, than "country", cuz the choice is wider).

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
You can already set language and country in the settings.

**Comment by patkino** [comment]
You didn't get me right. 
I'm talking about tmdb lists. Such as "popular", "trending", "genre", etc.
Tmdb has an option to list movies/shows at certain language.
I suggest to add it to addon.

So that users for example in Brazil could add "movies in Portuguese " widget to homepage

**Comment by jurialmunkey** [comment]
> I'm talking about tmdb lists. Such as "popular", "trending", "genre", etc.
> Tmdb has an option to list movies/shows at certain language.

No it doesn't. You can see the query params it accepts here:
https://developer.themoviedb.org/reference/movie-popular-list

The language param is for specifying the translation language returned. It does not filter the results. The only filter is region.

> So that users for example in Brazil could add "movies in Portuguese " widget to homepage

You can already do this with Discover.
Use the rule `With original language` set to `Portuguese (pt)`

**Comment by jurialmunkey** [comment]
e.g. Most Popular Action Movies in Portuguese
`plugin://plugin.video.themoviedb.helper/?info=discover&sort_by=popularity.desc&tmdb_type=movie&with_genres=Action&with_original_language=pt`

**Comment by patkino** [comment]
Thanks
