### ISSUE TITLE
[BUG] In-progress Movies under "Still to Watch" list are appearing twice

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/plugin.video.themoviedb.helper#1088]
### Describe the bug

Hi @jurialmunkey,

Hope you are doing well. I noticed that there is a bug in the "Still to Watch Movies" list. All In-progress movies are appearing twice in that list.

### Steps To Reproduce

Start watching any movie and stop watching it at the middle so that it gets added to the Trakt In-progress movies list. Now go to the "Still to watch Movies" list. The Movie will appear twice in that list. See attached screenshot which shows the "Justice League: Warworld" movie appearing twice in that list.

### Screenshots and Additional Info

![IMG20230730013803](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/65297828/7f75421f-660f-4811-8d7b-f64dae8cba3e)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I can't recreate this issue. Are these movies also in your watchlist?

**Comment by AakashC2020** [comment]
> I can't recreate this issue. Are these movies also in your watchlist?

Yes, these movies are in my watchlist.

**Comment by jurialmunkey** [comment]
That'd be why. The "Still to Watch" list combines in progress with watchlist. Let me see if I can use a set instead of a list to avoid dupes

**Comment by AakashC2020** [comment]
> That'd be why. The "Still to Watch" list combines in progress with watchlist. Let me see if I can use a set instead of a list to avoid dupes

Fine @jurialmunkey.

**Comment by AakashC2020** [comment]
Thank you @jurialmunkey !
