### ISSUE TITLE
[Question] Nodes

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1089]
### Describe the feature that you'd like

I didn't quite understand this about nodes. Can I combine two lists, for example recommended and similar, and use it as a one list in the skin.
Something similar to what you did in the randomized lists with tv show and movies.

### Why is this feature needed? What problem does it solve?

-

### Steps to reproduce.

-

### Screenshots and Additional Info

-

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
See the wiki.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Node-Customisation

A node is a folder containing shortcuts to other folders - e.g. The "Movies" node contains shortcuts to "Search" "Popular" "Trending" and so on.

I don't really know what there is to explain. If you read the wiki entry and try out the example it provides then you should be able to understand what it does.

**Comment by matke-84** [comment]
Sorry my bad. I went through the changes that were in the previous period, so I noticed this one too, but I didn't go to the wiki page to check if it was there. Sorry again.
