### ISSUE TITLE
Go to next episode automatically in TV Shows

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#109]
Is it possible to add an option to automatically go to the next episode when selecting a TV show from the 'In progress TV shows' list from Trakt? I use this list as a widget (given there is no automatic library integration with Trakt lists as far as I know) so it'd be nice if there was an option to, once a TV show is selected from this list, automatically go to the episode in the show the same way the Kodi library does.

**Comment by jurialmunkey** [comment]
Why not use "Your Next Episodes" instead? You can always browse into the season if you need to play a different episode by using the context menu.

**Comment by juanma-cvega** [comment]
It's just convenience. I'm used to use OpenMeta library integration with Trakt collections and sometimes, for whatever reason, watched episodes are not synced with trakt. Using 'Your next episodes' gives you the next episode trakt 'thinks' it's the next one. If that's not the case, you need to go to the TV show, the right season and the right episode manually. From the library it's fast but when doing it through and addon that needs to fetch the information for each step from internet, it could take a little while. A little off-topic but there is currently no automatic import of trakt collections into the library like OpenMeta does, right?

**Comment by jurialmunkey** [comment]
No automatic import. I'm not really in favour of it but it seems something that a lot of people would like so I'm looking into it.

Currently you can add shows individually to the library. There is an option in the settings to update those shows on startup with any missing episodes.

Also, doesn't In-Progress Shows already go to the first next-up episode anyway? The first episode in the list should be the first next-up episode (according to Trakt).

**Comment by juanma-cvega** [comment]
No, In progress shows only gives you the list of shows with unwatched episodes. But then is up to you to go to the one you want

**Comment by jurialmunkey** [comment]
Unless I'm misunderstanding what you're saying, that's not how it works.

In-Progress Shows:
![Honeyview_screenshot530](https://user-images.githubusercontent.com/4618719/75101062-11c61c80-562b-11ea-9d30-449e323ab764.jpg)

Here's The Goldbergs where I still have 13 episodes to watch.
![Honeyview_screenshot531](https://user-images.githubusercontent.com/4618719/75101063-138fe000-562b-11ea-892f-0095b27864e3.jpg)

When I open the folder I see all my unwatched episodes with the next one to watch up first:
![Honeyview_screenshot532](https://user-images.githubusercontent.com/4618719/75101064-14c10d00-562b-11ea-8508-c8a82f837fb0.jpg)

**Comment by juanma-cvega** [comment]
Hmm, I think I didn't noticed that view only showed unwatched episodes instead of all of them. Personally I prefer being able to see all episodes and just be taken to the next to watch but that's me. In any case, it seems my request is just a personal preference given this option exists so feel free to close this issue. Btw, what's the view you use in your setup? I guess you're using artic zephyr 2 but I haven't seen it.

**Comment by jurialmunkey** [comment]
It shows the Up Next episodes as according to Trakt.

For all episodes I tend to use the "Your Recently Watched TV Shows" list. You can also browse all episodes/seasons by using the context menu option.

Either way, yeah not possible for the addon to set the focus (and probably not advisable either considering the many different use cases).

That's a new skin/mod of Arctic that I'm working on that's not released yet:
https://forum.kodi.tv/showthread.php?tid=351756
