### ISSUE TITLE
[Feature] Copy settings from another player

### ISSUE THREAD

**Issue by test01203** [jurialmunkey/plugin.video.themoviedb.helper#1090]
### Describe the feature that you'd like

There is sometimes a similarity between one player and another
Then you have to set everything up again
I want it to be possible to copy between one player and another with a click

### Why is this feature needed? What problem does it solve?

Copying the information of another player to the player I want

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Settings are defined in the player file. It makes no sense to "copy" them from another player -- if the player file is configured incorrectly and needs settings changed then the person who made the player file should fix it so that it has the correct settings.

**Comment by test01203** [comment]
> Settings are defined in the player file. It makes no sense to "copy" them from another player -- if the player file is configured incorrectly and needs settings changed then the person who made the player file should fix it so that it has the correct settings.

If there is an add-on there that is identical to another add-on, there is no need to configure it again
But just copy the exact same settings

**Comment by jurialmunkey** [comment]
> > Settings are defined in the player file. It makes no sense to "copy" them from another player -- if the player file is configured incorrectly and needs settings changed then the person who made the player file should fix it so that it has the correct settings.
> 
> If there is an add-on there that is identical to another add-on, there is no need to configure it again But just copy the exact same settings

Players are just json formatted text files. If you want a copy then just copy the file.

**Comment by test01203** [comment]
> > > Settings are defined in the player file. It makes no sense to "copy" them from another player -- if the player file is configured incorrectly and needs settings changed then the person who made the player file should fix it so that it has the correct settings.
> > 
> > 
> > If there is an add-on there that is identical to another add-on, there is no need to configure it again But just copy the exact same settings
> 
> Players are just json formatted text files. If you want a copy then just copy the file.

This is exactly the point, I now had an add-on that is based on the Fen add-on but with a different name
I had to change the files manually
It is indeed easy, but if there is an easier way it is better

**Comment by jurialmunkey** [comment]
>  It is indeed easy, but if there is an easier way it is better

You're asking me to spend my free time coding something for you because you find it difficult to open the player folder in your file explorer and press Ctrl+C then Ctrl+V ?

You can even do this in Kodi. Just add the player folder as a source in the file manager then use the context menu to copy the file.
