### ISSUE TITLE
[BUG] (TV Shows) resume point bug in widgets

### ISSUE THREAD

**Issue by SJ1O** [jurialmunkey/plugin.video.themoviedb.helper#1091]
### Describe the bug

When resuming a episode via a widget it asks to resume or play from beginning I select resume but it always plays from the beginning. This is using the tmdb helper resume in progress episodes widget. If I open the tmdb helper addon and navigate to in progress episodes and select the episode it resumes as it should so appears to only be happening within widgets.

I have included a log.

This only happens with TV shows.

Kodi version: 20.2 
Skin: arctic fuse (seems to happen on all skins I have tried)
Device: Amazon firestick and Amazon fire cube 3rd gen
Tmdb helper version: 5.1.26-nexus

### Steps To Reproduce

1.Create a in progress episodes widget (only happens with widgets)

2. Try to resume a episode via the widget.
3. It probably won't resume.

### Debug log

https://paste.kodi.tv/fadahukake

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Not a TMDbHelper issue. Resume points are managed by Kodi via setResolvedURL()

Sounds like you're attempting to playback via a plugin which doesn't use setresovledurl correctly or attempts to manage its own resume points by overridding Kodi's playback.

If the plugin does correctly use setresolvedurl, then the other possibility is that the is_resolvable flag is either disabled in the player file despite it being compatible, or you have disabled it in TMDbHelper settings.
