### ISSUE TITLE
[BUG] mark episode as watched failed for TMDB ID ...

### ISSUE THREAD

**Issue by AdamNo2** [jurialmunkey/plugin.video.themoviedb.helper#1095]
### Describe the bug

i can not set trakt state to "un/wachted" on TvShow episodes.
![Screenshot from 2023-08-04 16-03-21](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/113284561/6c42583e-a5ad-44be-a5a3-b175b85e5d11)

kodi.log
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/12261672/kodi.log)

setting "un/wachted" on whole TvShow works fine!

i am using 5.1.28

### Steps To Reproduce

- in main menu go to tvshow
- select a tvshow (i.e. from recently added)
- hit enter key to get to episode view
- select an episode and hit i key
- on left pane select trakt button
- click mark as watched 

and see error message from above screenshot.

kodi log with enabled debug in themoviedb.helper:
[themoviedb.helper.debug.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/12261659/themoviedb.helper.debug.log)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Full logs only please. No snippets.

Also why are you running python 3.10? Probably the most broken version of python for kodi - generally want 3.11.2
