### ISSUE TITLE
[Question] Close DialogVideoInfo on back from recommendation dialog

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1096]
Is there a way to close the underlying DialogVideoInfo.xml when going back from the script-tmdbhelper-recommendations.xml dialog.

What I'm trying to do is remove all the content from my DialogVideoInfo and just use the recommendations dialog.

In my DialogVideoInfo.xml I'm just running the recommendations script like this:-

DialogVideoInfo.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<window> 
  <onload>Runscript(plugin.video.themoviedb.helper,recommendations=1000|info=cast|true|info||1001|info=similar|true|info||1002|info=recommendations|true|info||1003|info=posters|true|info||1004|info=fanart|true|info,window_id=1191,$VAR[TMDBQueryType],$VAR[TMDBQuery],$VAR[TMDBYear])</onload>

  <controls />
</window>

```

This works great, when I press info I get straight to the recommendations dialog, however when I back navigate I get to a blank DialogVideoInfo dialog. Is there a way to auto close the DialogVideoInfo when going back?

**Comment by jurialmunkey** [comment]
Have you tried simply force closing the info dialog onload after launching recommendations?

e.g.

```
<onload>Runscript(plugin.video.themoviedb.helper,recommendations=1000|info=cast|true|info||1001|info=similar|true|info||1002|info=recommendations|true|info||1003|info=posters|true|info||1004|info=fanart|true|info,window_id=1191,$VAR[TMDBQueryType],$VAR[TMDBQuery],$VAR[TMDBYear])</onload>
<onload>Dialog.Close(movieinformation,true)</onload>
```

Or possibly with an alarm clock to make sure it triggers after:

```
<onload>AlarmClock(closeinfo,Dialog.Close(movieinformation,true),00:00,silent)</onload>
```

**Comment by roidy** [comment]
I never considered just closing the info dialog after the call to recommendations, for some reason I thought the info dialog needed to be open for the recommendations window to work.

Thanks, that works great.
