### ISSUE TITLE
[BUG] Recommendations return bug

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1098]
### Describe the bug

When opening DialogVideoInfo.xml for an episode and then navigating through the Recommendations dialog and then returning to the original DialogVideoInfo.xml it no longer contains the episode information, instead it contains the base TV Show info.

This bug is repeatable in the Arctic Horizon 2 skin as well.

### Steps To Reproduce

1. Open DialogVideoInfo for an episode.
2. Navigate into the Recommendations dialog and into a different item so DialogVideoInfo is populated with new information.
3. Navigate back to the starting DialogvideoInfo and it now contains TV Show information instead of the original Episode info.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by roidy** [comment]
Could you confirm weather this is a bug or expected behaviour?

**Comment by jurialmunkey** [comment]
It's expected because it has to fake it on return.

 Can't have more than one info dialog open so it means the original gets closed.

There's no way for me to capture the actual dialog so instead the script generates the online version using the ID that was given.

**Comment by roidy** [comment]
Yep, sure, I realise that. I think we had that conversation before. I know that on return to the original info dialog you need to rebuild the item from an online lookup.

The issue I'm referring to here is that it's returning to a completely different item and item type, not the original item with rebuilt online info.

Open Info on an EPISODE and you get returned to the TV SHOW not the starting episode.

It makes navigation very jarring when you get returned to an unexpected item you never started at.
