### ISSUE TITLE
[Feature] Hide movies in cinema

### ISSUE THREAD

**Issue by unicornsandcandies** [jurialmunkey/plugin.video.themoviedb.helper#1099]
### Describe the feature that you'd like

It's the feature that is available at stremio. Basically hiding movies that are still in cinema and don't have digital release, so you can't watch them anyway (maybe as recordings from cinema or something). It would be super useful and there's apparently some API for it.

### Why is this feature needed? What problem does it solve?

I have a movies widget that shows me my watchlist. I would love to have something like with tv shows, where my widget shows me newly released episodes as first. It would be possible if tmdb could hide movies that are currently only in cinema. This would also make everything easier - I don't need to check movie every couple weeks if it's available already, I see only movies that are not only released but available to watch in any way. It would be super helpful and make life easier, especially for new users or people using Kodi as a couch watching experience. Also if someone's caching sources in any way - they wouldn't cache a source that is a scam or a camera recording, because if movie isn't possible to watch digitally yet, it's often full of scam or virus links and not the actual movie itself

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by Omarscomin** [comment]
This would be amazing!!!

**Comment by jurialmunkey** [comment]
You can already do this for any list by using the `available_releases` property and filter params:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Lists-Additional-Params#optional-exclusion-and-filter-parameters

For example:

**Watchlist Movies with a Digital release**
`plugin://plugin.video.themoviedb.helper/?info=trakt_watchlist&tmdb_type=movie&filter_key=available_releases&filter_value=Digital`

**Top Rated Movies with a Physical release**
`plugin://plugin.video.themoviedb.helper/?info=top_rated&tmdb_type=movie&filter_key=available_releases&filter_value=Physical`

The problem you will soon find is that the TMDb data for anything other than the "Theatrical" release is poor (sometimes "Physical" is listed; very rarely "Digital" is listed).

For instance, if you look at the Godfather you will see it only lists Theatrical release dates for most countries:
https://www.themoviedb.org/movie/238-the-godfather/releases

This is despite it being 50 years old and the highest rated movie on TMDb.

**Comment by unicornsandcandies** [comment]
> You can already do this for any list by using the `available_releases` property and filter params: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Lists-Additional-Params#optional-exclusion-and-filter-parameters
> 
> For example:
> 
> **Watchlist Movies with a Digital release** `plugin://plugin.video.themoviedb.helper/?info=trakt_watchlist&tmdb_type=movie&filter_key=available_releases&filter_value=Digital`
> 
> **Top Rated Movies with a Physical release** `plugin://plugin.video.themoviedb.helper/?info=top_rated&tmdb_type=movie&filter_key=available_releases&filter_value=Physical`
> 
> The problem you will soon find is that the TMDb data for anything other than the "Theatrical" release is poor (sometimes "Physical" is listed; very rarely "Digital" is listed).
> 
> For instance, if you look at the Godfather you will see it only lists Theatrical release dates for most countries: https://www.themoviedb.org/movie/238-the-godfather/releases
> 
> This is despite it being 50 years old and the highest rated movie on TMDb.

Is it possible to filter out digital, physical etc and in theaters but airing for more than 4 months for example? Would that make it more accurate? I feel like in this time it's usually released somewhere, so it would help with tmdb having the wrong data.

It's kinda hard for me to understand the syntax and make it myself but I think that it would make sense. Of course if filters work that way. Either this or just this time period. It would be nice to have delay option at least, if anything else doesn't work out.

How (if possible) could I do it for watchlist?

**Comment by jurialmunkey** [comment]
Next version will add a `$DAYS[]` filter which can be used to generate a date X days from today

e.g.
`$DAYS[-120]` = The date 120 days ago (approx 4 months)

Combine with the `lt` "less than" operator to filter for movies with premiere date from at least 4 months ago or older.

`plugin://plugin.video.themoviedb.helper/?info=trakt_watchlist&tmdb_type=movie&filter_key=premiered&filter_value=$DAYS[-120]&filter_operator=lt`
