### ISSUE TITLE
Error with French langage

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/plugin.video.themoviedb.helper#110]
I use themoviedb helper with kodi Leia 18.5 on Nvidia Shield.

My setup is done in French
When I click on an element that has an accent, I get an error. Is it because this language is not yet supported?

![IMG_0917](https://user-images.githubusercontent.com/49578130/75099637-daeff800-5591-11ea-9d25-7e4185cf8b7e.jpg)

Thank you :)

**Comment by jurialmunkey** [comment]
Debug log please.

What section does this occur in?

**Comment by alKODIque** [comment]
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/4240195/kodi.log)
Here is my last log... hoping this will help. I have debug function on in TheMovieDb helper
This happen when I was in "Popular" section of TV Shows

**Comment by jurialmunkey** [comment]
Thanks for the log. 

Okay I think it should be fixed now. Can you test latest version and confirm?

**Comment by alKODIque** [comment]
It’s now working like a charm :))

Thanks a lot!

**Comment by jurialmunkey** [comment]
No problem! Thanks for the bug report and testing 😀
