### ISSUE TITLE
[BUG] Variables changes based on Language

### ISSUE THREAD

**Issue by WoWP120** [jurialmunkey/plugin.video.themoviedb.helper#1101]
### Describe the bug

When changing language the item data such as: showname changes to the same language
maybe constant variables are better because i prefer not to make another call to tmdb by myself

### Steps To Reproduce

1.Log showname under English
2.log showname under Non-English

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by WoWP120** [comment]
previous discussion cleared that it is not doable

**Comment by jurialmunkey** [comment]
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#api-language-and-country

The wiki tells you how to set a different language for a player
