### ISSUE TITLE
[BUG] Trakt on skin

### ISSUE THREAD

**Issue by BrownQ8** [jurialmunkey/plugin.video.themoviedb.helper#1102]
### Skin section

Other

### Current Behavior

Error on tmdb every time skin loading if i have account trakt signing in .. but without account nothing showing 

### Expected Behavior

Checking log

### Steps To Reproduce

1.tmdb trakt 
2. Authorization account 

### Screenshots and Additional Info

https://paste.kodi.tv/hiyuhaqeyo

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I'm failing to understand what this has to do with the skin? 

TMDbHelper issue so I'm transferring there.

**Comment by BrownQ8** [comment]
There’s no error with ur previous skins .. only with fuse
