### ISSUE TITLE
[BUG] Page multiply breaks date sorting

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1103]
### Describe the bug

Referring to this issue #819 that pushed items without a date to the end of lists. When setting page multiply to anything other than 1 items without a release date are now moved to the beginning of the list.

### Steps To Reproduce

1. n/a

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Hmm, it really shouldn't affect it at all. Do you have an example list / items that I can use to test?

**Comment by roidy** [comment]
`<content sortby="year" sortorder="ascending">plugin://plugin.video.themoviedb.helper/?info=trakt_anticipated&amp;tmdb_type=tv&amp;filter_key=language.1.iso&amp;filter_value=en&amp;detailed=true&amp;with_id=true&amp;without_genres=99 / 10763 / 10764 / 10767&amp;with_separator=OR</content>`

**Comment by jurialmunkey** [comment]
More so, what items are appearing out of order?

And btw these don't go with `info=trakt_antipated` as these are discover params:
`&amp;with_id=true&amp;without_genres=99 / 10763 / 10764 / 10767&amp;with_separator=OR`

**Comment by jurialmunkey** [comment]
BTW I don't see any sort method in your path, so these should be in whatever order Trakt returns them in.

If you look on Trakt website you'll see that the shows are not in airdate order either:
https://trakt.tv/shows/anticipated

**Comment by jurialmunkey** [comment]
In fact, anticipated list doesn't even give enough metadata by default to sort by date:
https://trakt.docs.apiary.io/#reference/shows/anticipated/get-the-most-anticipated-shows

All it returns are IDs and titles which is not enough to provide any sorting
```
  {
    "list_count": 838,
    "show": {
      "title": "Dr. Ken",
      "year": 2015,
      "ids": {
        "trakt": 98913,
        "slug": "dr-ken-1969",
        "tvdb": 295557,
        "imdb": "tt3216608",
        "tmdb": 62776
      }
    }
```

**Comment by roidy** [comment]
One moment and I'll post screen shots.

**Comment by roidy** [comment]
![list](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/4118048/d130af35-8ce3-4d4c-a045-e13ea75fc835)

**Comment by roidy** [comment]
As I said you added all the code in issue 819 to make this work, and it's been working fine until the page multiplier was added.

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/d558ee792c7cab2b706ec9e166e01d7b68af13b7
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/248c5e54e8ecf5e47c6c9ca48ff9ecdac4e5040d

**Comment by roidy** [comment]
> BTW I don't see any sort method in your path, so these should be in whatever order Trakt returns them in.
 
That's right but then Kodi sorts them:- `<content sortby="year" sortorder="ascending">`

**Comment by jurialmunkey** [comment]
If you're applying sortby=year in Kodi then that's going to override any plugin sorting.

**Comment by jurialmunkey** [comment]
> As I said you added all the code in issue 819 to make this work, and it's been working fine until the page multiplier was added.
> 
> [d558ee7](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/d558ee792c7cab2b706ec9e166e01d7b68af13b7) [248c5e5](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/248c5e54e8ecf5e47c6c9ca48ff9ecdac4e5040d)

These are additions for **watchlist anticipated** not plain anticipated list.

As I said above, there is no metadata to sort the Trakt's "anticipated" list by (in fact it would be pointless to sort because it contains all items in the future).

**Comment by jurialmunkey** [comment]
As far as I see, Kodi is sorting your content correctly based on the year.
You have two items with no year in Kodi, then everything 2023, then everything 2024 (Galaxy Quest and Marlow have year 2024, but no premiere date).

**Comment by jurialmunkey** [comment]
The only difference now is that you're getting two pages of content at a time, so there's more items for Kodi to apply its sorting to.

Kodi sort method will always override plugin sort method because Kodi applies sorting after plugin exit.

**Comment by roidy** [comment]
Ok thanks. I'll just use page x1, that works fine.

**Comment by jurialmunkey** [comment]
I guarantee this has nothing to do with the multiplier and everything to do with your sort method in kodi.


Kodi sort by year first sorts year and then premiere date. If you look at the year of those items without a premiere date you will see that they are in correct position - the ones in the middle will have year 2024.

Its not "working fine" with one page with what you've set - it's just that randomly the items you got on first page without premiere dates still have years in 2024 which puts them at the end of the list because the rest of items on the first page are all 2023.
