### ISSUE TITLE
[BUG] In progress TV not populating properly

### ISSUE THREAD

**Issue by Suspire73** [jurialmunkey/plugin.video.themoviedb.helper#1104]
### Describe the bug

Using In progress TV shows are now only showing a single episode whereas in previous versions the whole list of remaining episodes showed. I don’t know if this is an intended design feature or not but if it is I would certainly like to see an option added to the settings.

### Steps To Reproduce

See above

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Ah yep, I see what I did. That ^^ should fix it.

**Comment by Suspire73** [comment]
Amazing work & response time!
