### ISSUE TITLE
[BUG] Unable to increase Page Multiplier to 4 for Trakt sync lists after latest update

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/plugin.video.themoviedb.helper#1106]
### Describe the bug

Hi @jurialmunkey,

After the latest update I'm not able to change the Page Multiplier for Trakt sync lists to 4 like I could after the previous updates. The maximum is now 3. I guess this was intentional but the ability to change it to 4 was really useful for large lists like Trakt Watchlists. Originally before the Page Multiplier feature addition also we could view 80 items for Trakt sync lists like Watchlists. So, is it possible to make the maximum number for Trakt sync lists to 4 again? Kindly advise. 

### Steps To Reproduce

Go to TMDB Helper settings -> Other -> Page Multipliers -> Page Multiplier (Trakt sync lists) and try to change the slider to 4, but the maximum you can select now is 3.

### Debug log

https://paste.kodi.tv/mocumisenu

### Screenshots and Additional Info

![IMG20230815211334](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/65297828/691c9bf6-192e-47f0-a14c-a6a24d94a28a)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
The limit was always meant to be 3. You shouldn't need more than 60 items in a widget.

If you need to see more items, use the library multiplier. It applies to all lists when opened from inside the addon (i.e. not widgets).

**Comment by AakashC2020** [comment]
> The limit was always meant to be 3. You shouldn't need more than 60 items in a widget.
> 
> If you need to see more items, use the library multiplier. It applies to all lists when opened from inside the addon (i.e. not widgets).

I mainly use TMDB Helper widgets. Actually my next episodes list is quite large, around 80. So previously I could see all my next episodes in 1 widget row. Now I've to go to the next page to view the remaining items. However, this is not a big issue. I can live with it. I was only checking with you if it was feasible to add back the 4 page multiplier for Trakt sync lists. Nevertheless, no problem, the 3 page multiplier is also fine. 60 items per widget row is not bad at all. Thank you for your quick reply!

**Comment by aryank420** [comment]
> The limit was always meant to be 3. You shouldn't need more than 60 items in a widget.
> 
> If you need to see more items, use the library multiplier. It applies to all lists when opened from inside the addon (i.e. not widgets).

Jurialmunkey im sorry to say but because of this i had to downgrade the addon to version 5.1.28 and then disable future updates! Im not being rude or anything but if a feature is not bothering anyone in anyway then you shouldn't take it of thats called downgrading instead of upgrading i just wished you brought that functionality back again in future updates so that i can start upgrading again to the latest version if not then im gonna have to stick to the version i have right now. Ps my trakt watchlist count of movies and tv shows are over 70.

**Comment by jurialmunkey** [comment]
There are good reasons for the limit. It is not up for debate.
