### ISSUE TITLE
[Feature] Add a [movie set] option into [context menu]>[Browse lists]

### ISSUE THREAD

**Issue by tielis** [jurialmunkey/plugin.video.themoviedb.helper#1109]
### Describe the feature that you'd like

Hi @jurialmunkey ,

I find it really handy having the option [Movie Set] in the [context menu]>[Browse lists]  in order to see all the movies of a specific sequel. It is easier to add the movies of that sequel to the library and make sure we are not missing anything.

TMDB already gives us this info. We just need to add it into the context_menu.

I added this feature to my MOD a 2~3 years ago, and I was trying to rebase and PR it, but the structure of the addon has changed quite a bit, so I didn't manage to rebase it. lol

If that helps, I still have the MOD  for matrix. It doesn't really work any more, but at least you can have a look.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/7d0658e05d94d87ed7cd25a8567ed1889d3a1aab

I remember that I had to add one line of code into the [context.themoviedb.helper] too.
I think I had to send the 'db_id' in case it already exists in kodi DB. Not sure though

Please, let me know your thoughts. 

Regards

### Why is this feature needed? What problem does it solve?

I find it really handy having the option to see all the movies of a specific sequel. It is easier to add to the library and make sure we are not missing any movie of that sequel.

It also helps us when deciding to watch a movie and we can see how many movies that sequel has.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Yep good suggestion - it's the movie equivalent of "seasons".

I had a similar thought a while back when I was wanting to browse a collection but then I forgot about it -- so I'm glad you made this request!

I've only tested internally with TMDbHelper items -- I haven't tested the context menu add-on but technically it should work too with this change.

**Comment by tielis** [comment]
Thanks @jurialmunkey
