### ISSUE TITLE
Failures pulling specific TV Shows

### ISSUE THREAD

**Issue by vitadome** [jurialmunkey/plugin.video.themoviedb.helper#111]
Hi,
I noticed failures for specific TV Shows which generate a Check Log error.  I'm able to search for the TV Show and select but fails at the season level.  I was using 2.2.63 without issue for several weeks.  Noticed the error for specific TV Shows earlier this past week.  I tried to remedy issue by installing release 2.2.72 but that hasn't solved the problem.

EXAMPLE:
 - Search for the TV Show "American Idol" fails
 - Search for the TV Show "The Blacklist" success

I have uploaded my log at pastebin: https://pastebin.com/pQbwJqUb

Any insight to the error is appreciated.

Thank you.

**Comment by jurialmunkey** [comment]
@vitadome - Can you test latest version (v2.2.73)? I think this should fix the issue.

**Comment by vitadome** [comment]
@jurialmunkey  - Works great... thanks for the quick turnaround!

**Comment by jurialmunkey** [comment]
Can you get me another log of the other shows not working.

**Comment by vitadome** [comment]
@jurialmunkey I went through about 150 shows and only one popped up that is not working.  It's 90 Day Fiance.  Here's the log capture... https://pastebin.com/9s9jyqjZ

**Comment by jurialmunkey** [comment]
@vitadome - Please test with an **unmodified** version of my script. This line is causing the error and it is not my code!
```
firstitem.label = '[COLOR=fff0e68c][I]{}[/I][/COLOR]'.format(firstitem.label)
```
