### ISSUE TITLE
TMDB Context Menu fails to open on TV Shows[BUG] Description

### ISSUE THREAD

**Issue by MrC001** [jurialmunkey/plugin.video.themoviedb.helper#1113]
[TMDB_ERROR.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/12470532/TMDB_ERROR.log)
### Describe the bug

Running on CoreELEC

When attempt to open context menu on a TMDB Helper TV Show item. Get spinning Please wait and does not open, and sometime will open after a min or two.  Movies it opens just fine.  Tested on multiple Boxes but all CoreELEC and all act the same. Skin is Arctic Fuse.

### Steps To Reproduce

Goto a TV Widget or in TMDB Helper itself any TV SHOW item.

Click on 'C' or menu button for context menu.

Hangs on Please Wait .. occasionally will open after a few min.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
This would be either a Kodi issue or a CoreELEC issue. You would need to report to either of those.

Add-ons aren't actually involved at all in the process of displaying the context menu. The context menu is just a list of labels with a corresponding action Kodi should perform when the user clicks it -- Kodi is in charge of generating and displaying the context menu.

**Comment by jurialmunkey** [comment]
Also the error you attached is likely unrelated but impossible to tell because you haven't included the full log.

**Comment by MrC001** [comment]
Yes it just keept hammering and log was insanely large, amyway reset all TMDB Helper settings to default. Noticed some settings gone.  And now all seems good. So I donno..lol... sorry to bother you. I do try to figure things out but was a bit stumped.  But clearing and redoing settings seemed to fix it.  I really am liking Artic Fuse.  Oh only thing..is it possible to toggle the Add/Remove to node context item??
