### ISSUE TITLE
[BUG] No longer able to make a “playlist” of movies through Trakt list

### ISSUE THREAD

**Issue by TheBlueEagle** [jurialmunkey/plugin.video.themoviedb.helper#1116]
### Describe the bug

Prior to the last update of Umbrella and TMDBHelper, if you set your Umbrella to “auto play” when you went into a Trakt list, you were able to select option “Play from Here” in Kodi and TMDBHelper/Umbrella would play the first movie, and continue with the second one automatically and continue in that pattern until it reached the end of the list. Now, when you do this, playback simply ends and it returns to the selection screen. 
I liked to use this feature to “queue” up movies to continuously play while I’m laying down/sleeping. Is there any way to get this feature back? Thanks!

### Steps To Reproduce

1. TMDBHelper settings > Players > > Configure Players > Umbrella (auto play). 
2. Umbrella player settings > Default Action > Autoplay. 
3. TMDBHelper > Trakt lists > Long hold select “Play from Here” action. 
4. TMDBHelper/Umbrella would autoplay all movies in the Trakt list until the list is complete or it gets to the end of the page of the list. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Nothing to do with Tmdbhelper. This was never a context menu option provided by tmdbhelper . Ask the author of the plugin you're using for playback.
