### ISSUE TITLE
Themoviehelper error message

### ISSUE THREAD

**Issue by No-Dot7369** [jurialmunkey/plugin.video.themoviedb.helper#1118]
### Describe the bug

I get an error message for the moviedbhelper at start of Kodi. This error happens randomly on kodi startup

### Steps To Reproduce

on first click to open Kodi while loading I get the moviedbhelper error message

### Debug log

https://paste.kodi.tv/oregisalur

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by No-Dot7369** [comment]
I deleted the zaxxon709 account manager and have not received an error message since then, that was 2 days ago

**Comment by jurialmunkey** [comment]
Ok sounds like it's caused by an external addon modifying the settings configuration and changing a setting to the incorrect type. Will close.
