### ISSUE TITLE
[Feature] Unified search for everything together

### ISSUE THREAD

**Issue by test01203** [jurialmunkey/plugin.video.themoviedb.helper#1119]
### Describe the feature that you'd like

When choosing a movie or series
It will search in all add-ons that we have defined together
And then it will display a list of each add-on title and list of sources, title and list of sources
The more extensions there are, the longer it will take
But it will be possible to set a period of time to search for all add-ons
Think how important that is! Because there is no such add-on

### Why is this feature needed? What problem does it solve?

Happens to me a lot of times
There is a movie that has it in a dubbed add-on
And another add-on doesn't have it
But I want him to display both to decide which to choose

### Steps to reproduce.

Entering Kodi and choosing a movie

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Not possible due to addons having scripted windows and significantly different ways of providing content.
