### ISSUE TITLE
Automatically play video from dialog when it's the only one

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#112]
This is something related to the new functionality you added to show a dialog with the list of files found by a query to an addon. I think I've been able to make the Emby player work, both for movies and TV shows (I'm still waiting to see if the developer can provide some information about why movies don't show any data about the file quality) but I'd like to leave the `{"dialog":"True"}` always enabled, even for Emby servers where there is no duplication of movies. Would it be possible to have an option to automatically play the file when it's the only one returned by the addon?

**Comment by jurialmunkey** [comment]
This commit should give the option to set `{"dialog": "auto"}` 
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/a6b32a2f7c45424701ce3437d8d485ca94d1b8fb

Can you test and confirm it is working correctly?

**Comment by juanma-cvega** [comment]
Just tested it and it seems to work fine. Thanks.

**Comment by jurialmunkey** [comment]
Excellent! 😃
