### ISSUE TITLE
[BUG] Back to recommendations dialog

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1120]
### Describe the bug

When I enter the recommendation window, then open the info about the actor or some other info about the movie and then return to the basic dialog info, retrying to enter the recommendation window is no longer possible. It is interesting that this happens with the android device but not on the windows platform. The same thing happens with the AH2 skin.

### Steps To Reproduce

//

### Debug log

https://paste.kodi.tv/inubonezod

### Screenshots and Additional Info

//

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by matke-84** [comment]
My mistake. It happens on all platforms. Sometimes when this procedure is repeated twice, a bug appears. I've noticed that it happens especially with the tmdb helper. Please fix this bug.
https://www.veed.io/view/e4c4bb61-f642-48ee-985a-c856558c1b14?sharingWidget=true&panel=

**Comment by matke-84** [comment]
Sorry this is a good link.
https://streamable.com/blm2qi

**Comment by roidy** [comment]
This is the same bug I reported here #950

**Comment by matke-84** [comment]
@roidy Yes, I see now. Unfortunately, I don't think @jurialmunkey will deal with this anymore, considering that his main focus is on arctic fuse skin and I don't think he uses this script, maybe I'm wrong. I see that it is a similar story with other bugs and requests. He's just not interested in anything that isn't related to arctic fuse right now. Unfortunately, it makes things a little difficult for us who use the tmdb helper in our skins. But ok, he has done so much so far with tmdb helper that now it is our turn to be patient.

**Comment by jurialmunkey** [comment]
> Unfortunately, I don't think @jurialmunkey will deal with this anymore

@matke-84 - This is simply untrue. 

I have already spent considerable time looking into this bug (many many hours). More recently, I have been able to reproduce the issue but I still haven't been able to identify the cause. That's the only reason it hasn't been fixed. 

If I have a light-bulb moment that reveals the cause to me, then I'll fix it but I'm not going to sit here banging my head against the wall for hours in a futile search for a solution.

> I see that it is a similar story with other bugs and requests. He's just not interested in anything that isn't related to arctic fuse right now

I really don't appreciate this tone and implication here. I already give up many many hours of my free time fixing bugs and adding features for things I don't even use at all myself.

This is a really good way to make me not want to deal with this issue further. Honestly it is mind boggling just how entitled people think they are to my time when I already give so much of it so freely. 

Like what the fuck honestly... you're getting annoyed that I more frequently spend my free time working on things I use?!

Also, I was clear from the start that the recommendations script was experimental and incomplete -- the fact that you're getting annoyed that I haven't immediately fixed a minor bug in a complicated experimental feature is fucking absurd...

**Comment by matke-84** [comment]
@jurialmunkey I think you misinterpreted my comment. I'm very grateful for everything you've done so far, and I've always emphasized that. I even said that in my last sentence. I just mentioned that your focus right now is with arctic fuse, which is a fact, because mostly all recent changes are related to arctic fuse. And I don't mean anything bad about it. You are simply working now on something that is important to you, and as I mentioned, it is up to us to be patient. Sorry if you were offended in any way, it was not my intention.
