### ISSUE TITLE
[Feature] Text viewer for reviews

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1121]
### Describe the feature that you'd like

When we used:
`plugin://plugin.video.themoviedb.helper?info=reviews&amp;tmdb_type=movie&amp;tmdb_id=348`
it is necessary to add an option when we click on the review, textviewer opens. 

### Why is this feature needed? What problem does it solve?

It is necessary to make it easier to read larger text.

### Steps to reproduce.

-

### Screenshots and Additional Info

-

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by matke-84** [comment]
First of all, Happy New Year. I wanted to ask if there is a chance to implement this in the tmdb helper. I saw that this works in artic fus, but it is not at all clear to me in what way. I saw the code, but it still doesn't open textviewer dialog. Can you give me a little help? It would be really good if there was a possibility to open textviewer for either tmdb or trakt reviews. Thank you in advance.

**Comment by jurialmunkey** [comment]
https://github.com/jurialmunkey/script.skinvariables/wiki/Skin-GUI-Dialogs

**Comment by matke-84** [comment]
Thanks, but there is still some problem with textviewer. When there is a comma in the text, the text ends there. Any solution for this?

**Comment by jurialmunkey** [comment]
$ESCINFO

> $ESCINFO[] should be used when passing an infolabel to a built-in function, when this infolabel is likely to contain commas (,) and/or quotes ("). 


https://kodi.wiki/view/Label_Parsing

**Comment by matke-84** [comment]
That's right, I just remembered. Thank you very much for your help as always.
