### ISSUE TITLE
[BUG] TMDB Helper Tagger Notification

### ISSUE THREAD

**Issue by RentreX** [jurialmunkey/plugin.video.themoviedb.helper#1123]
### Describe the bug

I constantly get notifications about TMDBHelper Tagger.

I am not exactly sure when it started though it 8s happening on 2 different devices. (Windows 11 and Google TV with Chromecast)

I was using Arctic Horizon 2 though have changed to Arctic Fuse and the same notifications appear.

### Steps To Reproduce

 I am not sure how to reproduce as the notifications started awhile ago and I have not been able to figure out why.

### Screenshots and Additional Info

![20231002_152318](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/60731904/590bd08c-e0d8-440c-b121-4ebf0b7a4cb1)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by RentreX** [comment]
A bit more information:

Once it reaches 100%, it then restarts again. 

If the trakt add-on is enabled (not the TMDB helper integration), it will then start the sync for tv shows and movies and then the tagger restarts.

**Comment by jurialmunkey** [comment]
It is part of the library integration.

If you are monitoring Trakt lists to add to your library, then the tagger runs after a library update to tag the items so that they will be added to the appropriate playlist.

**Comment by RentreX** [comment]
Oh okay that makes sense. Now I need to figure out why Kodi is updating the library constantly.

**Comment by RentreX** [comment]
It was a add-on that was updating trakt every 5 minutes and would force the library to be scanned

**Comment by dm2912** [comment]
> It was a add-on that was updating trakt every 5 minutes and would force the library to be scanned

what addon? out of interst

I have the same issue and the only things i have installed are tmdbhelper, ezra (which is not authorised with track and does not do anything library related) and jellyfin (which has automatic library updating turned off)

but tmdb helper does its thing about every five minutes :D

**Comment by dm2912** [comment]
ok, I have figured out the trigger.

Every time a new music track starts it triggers tmdbhelper to do an update :')

for some reason Jellyfin does a psuedo-library-update every single track, go figure

**Comment by jurialmunkey** [comment]
> ok, I have figured out the trigger.
> 
> Every time a new music track starts it triggers tmdbhelper to do an update :')
> 
> for some reason Jellyfin does a psuedo-library-update every single track, go figure

Oh wow that's excessive.

 jellyfin/embycon/plex-composite all directly edit the library db, which is why they aren't on official repo - has too many unintended consequences like this. 

I could add an option in TMDbH to skip playlist creation so it doesn't need to tag modified items - it doesn't really "solve" the underlying issue of these addons updating the library constantly though!
