### ISSUE TITLE
[BUG] TMDB crashes grabbing sources from ScrubsV2 

### ISSUE THREAD

**Issue by EggShweg** [jurialmunkey/plugin.video.themoviedb.helper#1124]
### Describe the bug

When I use ScrubsV2 with TMDB it crashes when grabbing sources. ScrubsV2 works fine standalone, but not with TMDB

### Steps To Reproduce

1. Have TMDB setup on Kodi
2. Install ScrubsV2
3. Configure TMDB to use ScrubsV2 as a player
4. Try to watch any movie or TV show with TMDB
5. Crash when preparing sources

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Sounds like a player issue but impossible to tell anything without a debug log and crash log.

**Comment by EggShweg** [comment]
Will get that to you asap, I'm using Kodi on a Tivo so its not easy to extract
