### ISSUE TITLE
[BUG] Trakt list showing in Trakt / "Liked Lists" after un-liked

### ISSUE THREAD

**Issue by booyakafoo** [jurialmunkey/plugin.video.themoviedb.helper#1133]
### Describe the bug

I have a Trakt list that I created and it shows up in Trakt / "Your Lists".  I liked it at some point and it showed up in Trakt / "Liked Lists" along with other Trakt lists that I liked.  I have since un-liked my Trakt list but it remains in "Liked Lists".  I have tried to clear cache but it remains.  I did have caching enabled and have disabled that as well.  It's been longer than a day and when I browse Trakt I can confirm that my list is no longer liked and other addons don't show it in my Trakt Liked Lists.  

### Steps To Reproduce

1. Like a personal Trakt list
2. In TheMovieDB Helper addon, browse to Trakt / Liked Lists
3. You will see your personal list along with other liked lists
4. Un-like the personal list in the addon or Trakt website
5. Personal list remains in Trakt / Liked Lists section of the addon 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by booyakafoo** [comment]
I can't figure out where this info is stored.  I logged out of Trakt and back in with a separate account and all liked lists were gone.  When I log back in with my regular Trakt account all the liked lists are back, including ones I have un-liked previously.  Shutdown Kodi and deleted all the .db files.  Restarted and all dbs get rebuilt and the liked lists remain.

**Comment by jurialmunkey** [comment]
The info is saved in Tmdbhelper's trakt db in its addon_data folder. So if you deleted that file then you deleted the local cached info and what you're getting is what the server is providing. 

I remember someone having a similar issue in the past. Deleted all local cached info but sever still returning old data for several days later.

**Comment by booyakafoo** [comment]
Thanks for the info.  That must be what's happening. I'll wait for it to clear.

**Comment by booyakafoo** [comment]
Trakt lists that were un-liked did clear out on their own eventually
