### ISSUE TITLE
[BUG] Suddenly getting constant errors/spamming log

### ISSUE THREAD

**Issue by GoonerM466** [jurialmunkey/plugin.video.themoviedb.helper#1134]
Hi,

I hope I'm able to get some help with this here.

Everything working well for months and suddenly today I'm getting constant error notifications from TMDB Helper.  I checked the log but can't figure out whats cuasing it.

Log attached - any help is much appreciated.

### Steps To Reproduce

See log

### Debug log

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/13386917/kodi.log)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Looks like TMDb API is not letting you download the genre IDs for some reason, so anything relying on the genres is failing (other possibility is the cached version of the file is corrupted).

Can you try version 5.2.5 and see if that helps?
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v5.2.5

**Comment by GoonerM466** [comment]
Amazing! Thank you. 

That has solved that problem, although seems to have introduced another.
The ratings line on widgets for your skin (AH2) has vanished. It's was there before. Any widget with "full" Expanded information has that line missing, and also the streaming providers footer is missing.
Tried reinstalling the skin, deleting my settings.xml, but it won't return. 

The line displays perfectly when set to "plot".

Nothing of note in the log except perhaps:

_JSONRPC: Could not parse type "settings.details.settingslist_

I appreciate this is somewhat unrelated perhaps, so I can take this elsewhere if you would prefer. 

Edit: Don't worry, I'm an idiot. All sorted.

Thank you very much for your time!
