### ISSUE TITLE
[Feature] Setting to update Kodi library cache before or after playback of a TV show

### ISSUE THREAD

**Issue by booyakafoo** [jurialmunkey/plugin.video.themoviedb.helper#1135]
### Describe the feature that you'd like

A user setting/option to refresh the cached Kodi library details before playing a new episode of a show or right after an episode has played.  So if a new episode of the show has been added to the library during playback the next episode will play from the library instead of being handled by an addon player.

**My library is shared using a mysql database so it's possible that the cache is updated when a library update has happened but my client isn't doing or seeing it because the actual library update is happening on a headless Kodi instance that is just used for library management.

I know all the tagging happens after the library update so I'm guessing the cache update happens then also.

### Why is this feature needed? What problem does it solve?

I use Sonarr to grab my Trakt User Watched list every 15 minutes and if there is something new it grabs all episodes for the first season of the new shows.  This results in the first season of a new show I start watching, being added to my Kodi library after watching a couple episodes with an addon player.  After the shows are in my Kodi library the TMDb helper widget I use for Next Up/In-Progress shows will not play the next episode from my library until I manually run the TMDb helper setting, Other, "Refresh cached Kodi Library details" option.

I know not everyone would need something like this but it would really help me with my automation setup.

**My library is shared using a mysql database so it's possible that the cache is updated when a library update has happened but my client isn't doing or seeing it because the actual library update is happening on a headless Kodi instance that is just used for library management.

I know all the tagging happens after the library update so I'm guessing the cache update happens then also.

### Steps to reproduce.

Play an episode from TMDb helper widget that doesn't exist in the Kodi library, episode will be scraped and played by the configured addon player
Add the next episode of the show to a MySql database Kodi library
The next episode can be seen in the Kodi library
Use TMDb helper widget to play the next episode and it will again be scraped by the addon player, not played local from the library.

Navigate to TMDb helper settings, other, "Refresh cached Kodi Library details"

Now use TMDb helper widget to play the next episode and it will play locally from the Kodi library.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Do you not have a way to trigger a `RunScript()` command on the client machines after a library update?

Because you can recache the Kodi DB with 
`RunScript(plugin.video.themoviedb.helper,recache_kodidb)`

I don't mind adding an option to refresh on an attempt to play -- but if you've got a way to trigger the recache after an update instead, then that's probably a better route overall rather than forcing it to refresh every time you want to play something.

**Comment by booyakafoo** [comment]
Awesome.  I should be able to do that.  Thank you!

**Comment by jurialmunkey** [comment]
In case that doesn't work out, I've added an option to force recaching:
`TMDbHelper Settings > Expert > Recache Kodi library details when building players`

**Comment by booyakafoo** [comment]
Thanks for adding this.  I ended up using the RunScript command that you suggested and it is doing the refresh fine.  Makes more sense to run this only when needed instead of every time.  Thanks again.

**Comment by jurialmunkey** [comment]
Yeah definitely agree that's going to be the better approach to refresh only periodically.

Was easy enough to add the option and I'm sure it will be useful for someone out there with a setup I hadn't considered.
