### ISSUE TITLE
[BUG] Videos with commas " , " in filenames will not play when "Reroute PlayMedia to xbmc Player()" is NOT checked

### ISSUE THREAD

**Issue by booyakafoo** [jurialmunkey/plugin.video.themoviedb.helper#1138]
### Describe the bug

Just noticed that if I do not select the expert option, "Reroute PlayMedia to xbmc Player()" , Then any videos with a comma in the filename will not play and give a failed to play error.  If I check that setting the video will play fine but the next episode will not play with the help of the UpNext addon (v2.0.27+dev.0) which is the only way I have found to get the next episode to play properly with media in my local library and using TMDb Helper Next Episode widget.  I feel like the next episode playing properly from the library is another issue but this comma issue should probably be fixed as well?  

video path and filename in my example is 

`smb://192.168.1.250/Synology NAS/TV Shows/A.P. Bio/Season 2/A.P. Bio - S02E03 - Wednesday Morning, 8 AM WEBDL-720p.mkv` 

https://paste.kodi.tv/vasatekuwu.kodi

`2023-11-27 15:21:46.746 T:32075   error <general>: CVideoPlayer::OpenInputStream - error opening [smb://192.168.1.250/Synology NAS/TV Shows/A.P. Bio/Season 2/A.P. Bio - S02E03 - Wednesday Morning]`

### Steps To Reproduce

Make sure that "Reroute PlayMedia to xbmc Player()" is NOT checked
Make sure Play local Kodi library files is set to Automatic
Play an in progress show in the Kodi library, using TMDb helper widget for an episode that has a comma in the filename.

### Debug log

https://paste.kodi.tv/vasatekuwu.kodi

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Commas are argument separators in kodi commands, so unencoded filename with commas will break the PlayMedia() command - kodi will treat everything after the comma as a separate argument.

The bigger question is why local content is being routed through this command at all. It sounds like you disabled using setresolvedurl using the "restrict to library strm" setting. This setting should be disabled if you have playable local files in your library.

The setting should only be enabled on systems with no local files. Even then, it's not recommended, as it is another layer of hack on top of the dummy video resolve hack to deal with badly coded plugins that don't use setresolvedurl properly.

**Comment by booyakafoo** [comment]
Actually I only have Resend local files checked.  I used the UpNext addon because there seems to be some issues with the playlist creation with local content.  UpNext and Trakt addons in my testing right now are disabled. 

Currently I have the following settings.

Dummy video and delay set to .1s
Stop before attempting playback, unchecked
Restrict to library strm, unchecked 

Reroute PlayMedia to xmbc.player, unchecked 
Resend local files , checked

![20231127_170204](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/3913228/4c7014fa-d22b-4b7b-9536-a32f2340c548)


Should I have the Kodi setting of "Play next video automatically" set to: Episodes?
When I set this to play next episodes.  Episodes play from my library fine and next episodes play fine as well.  They do not play properly from TMDb helper widget though.


With Kodi set to play next episode automatically
Library, select show, play episode.  Look at playlist while current episode is playing and I see all of the episodes in the playlist. with the current episode highlighted  Fast forward to the end and the next episode plays fine.

This is what the playlist looks like when an episode is played from the library.
![20231127_171330](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/3913228/b9ccfd55-b97d-4258-bbc9-5a41eeab551c)

From TMDb helper in progress widget.
Play episode, look at playlist and it only shows the current episode, showing smb:// path.  Forward to the end and I am returned to the homescreen.  

Playlist when played from TMDb helper widget
![20231127_171403](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/3913228/0f029150-0688-4590-a90c-6f7a6b4bdaa3)
 
Playlist when played from TMDb helper widget, with Resend local files unchecked.  Only one episode plays.  Also I notice that sometimes the playlist doesn't update when I switch shows.  As you can see the episode shown is not the same as the one currently playing.  If I change to a different show entirely, the same episode remains.  Or exit Kodi and restart, play an episode and the playlist is blank/empty.  
![20231127_172516](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/3913228/b1c4ab07-66ff-4d2d-bb30-874c2b3805d5)

**Comment by jurialmunkey** [comment]
> Actually I only have Resend local files checked

Ah, right. Yeah that does effectively the same thing - passes the file back through either `xbmc.Player()` or `PlayMedia()` (depending on your setting) so will have the same issue. That will also break TMDbHelper's playlist creation.

I'll have a look at ~url encoding the playmedia path because that should work around the issue~ (EDIT: encoding path breaks things but enclosing argument in doublequotes appears to work). Always a bit hesitant to mess with anything about playback because all these hacks to get other addons to work are basically held together with spit and glue -- whenever I change something in it I inevitably break someone's magic ritual to get some esoteric addon to work.

**Comment by booyakafoo** [comment]
Awesome.  Thank you so much.  Just tested and it is working on media with a comma in the filename.
