### ISSUE TITLE
[BUG] Kodi crashes before opening players selection dialog

### ISSUE THREAD

**Issue by kolekan** [jurialmunkey/plugin.video.themoviedb.helper#1139]
### Describe the bug

With latest 5.2.7 kodi crashes right before the player selection dialog opens. Kodi 20.2 on android 11 device. 

### Steps To Reproduce

1. Go to tmdb helper settings and select "Refresh cached Kodi library details"
2. Go and select any movie title to get the players selection dialog.
3. Kodi crashes.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Debug log please.

And please make sure debug logging is enabled. Not just a plain log
`Settings > System > Logging > Enable debug logging`

**Comment by sean-burner** [comment]
Seeing this same issue. 

https://pastebin.ubuntu.com/p/CNjw3VgG9k/

**Comment by jurialmunkey** [comment]
@sean-burner Thanks really appreciate the log. A little bit of a long shot but can you try install the master version via zip: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/refs/heads/nexus.zip

I can see that the progress dialog is closing before it has completed the step to build the players, so possibly when the build step attempts to update the progress (which no longer exists) it gets blocked from progressing further and never completes. Also I know there is some issue on nexus with busy dialog blocking some things, so I've moved up the process to force it closed earlier.

**Comment by jmh2002** [comment]
I'm using a Chromebook running Version 119.0.6045.158 / Android 11 and seeing a similar problem since updating to v5.2.7

However instead of a crash I just see a never ending 'Working' dialog after pressing Enter / Select on an episode. I can press 'Back' to stop this 'Working' process and Kodi continues to function normally.

But if I try to 'Select Player' manually via the Context Menu, I can get the player list, choose a player, and continue to providers and sources which are then able to be played normally.

**Comment by jurialmunkey** [comment]
@jmh2002 - Please try the zip I provided above and let me know if it fixes the issue.

**Comment by JaySmoka187** [comment]
Hi
I have tested the new players.py. It solve the problem for me but i use the latest omega nightly build.

Thank you :)

**Comment by urs45** [comment]
The Master Version in the Link above solved the issue for me too on Nexus.
Thanks.

**Comment by kolekan** [comment]
5.2.8 fix the issue. Thanks!!
