### ISSUE TITLE
[Feature] Can traktlists be accessed without Trakt Login

### ISSUE THREAD

**Issue by RussellRego** [jurialmunkey/plugin.video.themoviedb.helper#1141]
### Describe the feature that you'd like

Would it be possible to access traktlists without a trakt account?  I was previously able to.  Example: Dolby Vision, Dolby Atmos.  I never have had a trakt account.  Now if I try to access that same list, it first gives pop-up  error TraktAPI Token you must authenticate your Trakt Account to use this feature.   I click Never, and get no results or it crashes kodi. On subsequent kodi restarts it does the same thing.   One would expect choosing Never, would never bring up that popup again

### Why is this feature needed? What problem does it solve?

It will prevent kodi crashes when trying to access traktlists without a trakt login

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
You already don't need to be authenticated to access public Trakt lists.

How are you attempting to open these lists?

**Comment by RussellRego** [comment]
Kodi 20.2 Diggz Xenon Nexus Build ver 4.0

**Comment by jurialmunkey** [comment]
There's your problem. Don't use a build... Probably badly configured.

I need a way to replicate the issue that doesn't involve me installing some dodgy build full of crap. Otherwise I have to assume it is the fault of the build.

**Comment by jurialmunkey** [comment]
I cannot reproduce this issue. Only lists in the "Your lists" or "Liked lists" sections require authentication, or lists with the `owner=True` flag (which indicates the user is the owner and therefore should authorise first in case of a private list).

**Comment by JayDee696969** [comment]
@jurialmunkey . So, just to add a little info.. I see the same issue, but its ONLY when using the Search lists function. When you click Search Lists, it prompts for Trakt authorization. Im guessing the links in the build used the search function and then set that list as a shortcut. Something changed recently with that because Trakt auth. wasnt needed before to search user lists as far as I can remember..

**Comment by jurialmunkey** [comment]
> I see the same issue, but its ONLY when using the Search lists function.

This is a different issue and just an oversight. Easily fixed.

**Comment by RussellRego** [comment]
"Easily fixed" by dev or usr?

**Comment by jurialmunkey** [comment]
> "Easily fixed" by dev or usr?

Either. But I don't offer support for builds.

But I wasn't talking about that anyway. I was saying it is easy for me to fix the oversight in the search function asking for authorisation.

**Comment by RussellRego** [comment]
Thank you very much.  My first time posting on github so I'm unfamiliar
with some terminology and lingo.  I was wondering if I had done or said
something wrong.
