### ISSUE TITLE
[Feature] Option to remove episode groups / up next from season lists

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1142]
### Describe the feature that you'd like

As the title could you add the option to remove the episode groups and up next entries from season lists.

### Why is this feature needed? What problem does it solve?

I just don't want these entries cluttering up my season list.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Already exists:
`Settings > Navigation > Special season folders`

Should be able to show/hide any combo of upnext/specials/groups seasons

**Comment by roidy** [comment]
Thanks, I looked but completely missed the setting :(

**Comment by jurialmunkey** [comment]
No worries! I know what it's like to be looking for a setting and somehow not see it despite staring right at it,
