### ISSUE TITLE
[TMDb Helper UI] Indian language movie titles not showing properly

### ISSUE THREAD

**Issue by Vishwamoorthy** [jurialmunkey/plugin.video.themoviedb.helper#1143]
### Describe the bug

TMDb helper not showing movie names for many Indian movies. The database has info, but, the UI now showing. Pls, update

### Steps To Reproduce

Check Indian movie names on home UI of TMDb helper

### Screenshots and Additional Info

![tmdb-helper-ui-bug-v0-uegqu6nec1](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/87605110/f48c3cf2-6ed3-4615-81f6-50c93abbc81c)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Nothing to do with the addon. This is a skin issue issue with the font it uses. 

You need a skin with a font that supports Devenagari glyphs. The skin you are using does not.

Kodi has poor font management for fall backs. There is not good solution for the skin you are using. If having Devenagari based language is important to you then you should use Estuary.

**Comment by Vishwamoorthy** [comment]
Can we infuse the font with Artic Horizon? Pls help me with that or post a guide... Will be helpful for many in the future.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Vishwamoorthy** [comment]
*One Reddit guy guided me in this way. So I downloaded Noto Sans
Devanagari, renamed and Installed the zip. The situation got even worse,
font not supported I guess. I am looking for Indian movie titles to show in
English. pls check the screenshot*



*1-* you will need a .tff font that supports Indian and Latin "English"
languages.

*2-* download the zip file for the skin here
<https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/tags/v0.8.27.zip>

unzip the file go inside the *fonts* replace all *RobotoCondensed* variants
with the Indian font you have with the same name RobotoCondensed... .tff

after that zip the skin again and manually install it in Kodi

**Comment by jurialmunkey** [comment]
> Can we infuse the font ... Pls help me with that or post a guide.

No, I cannot guide you in how to merge font files together. Designing and editing fonts is complicated and if you are already having trouble simply renaming files then you will struggle to merge fonts.

If you are asking for a guide on how to replace the font in the skin, then you've already been given that. The instructions the Reddit user gave you were simple and correct. If you cannot follow those simple instructions, it is unlikely I can help you.

If you are asking me to replace the font in the skin for you with Noto Sans Devangari, the answer is no I will not do that for you. The skin is designed for use with Roboto Condensed not Noto Sans. Changing the font set changes the skin design.

**Comment by Vishwamoorthy** [comment]
I've followed the instructions and implemented. I've also added screenshot of the output. The only thing I am curious to know is I want the UI to be in English (that shows Indian movies properly) only, not hindi. I used devangari, guess it's not working. Pls suggest some other font for my need. I'll follow the reddit user instructions and get it working.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Vishwamoorthy** [comment]
I tried this only. https://fonts.google.com/noto/specimen/Noto+Sans+Devanagari

Also pls check the screenshot for the result. It's not that i cannot follow that user's simple instructions. I've done and came up with the result.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
