### ISSUE TITLE
Context menu "choose default player" error

### ISSUE THREAD

**Issue by rhinhold** [jurialmunkey/plugin.video.themoviedb.helper#1146]
### Describe the bug

Here is link to current open ticket from:
https://github.com/mrgsi/tmdbh.players/issues/9

It includes log file along with steps already taken

Thank You

### Steps To Reproduce

1. From tv or movie home pages.
2. Right click on a show to bring up context menu
3. Select default player for series, episode (after selecting player, notification indicates player successfully added)
4. Then select the show to play it
Error is displayed saying "TMDB error check log"

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Sorry for the delay getting to this one.

Can you test latest version (v5.2.14) and let me know if it fixes the problem? I think it is the same error as this issue: #1151
