### ISSUE TITLE
[Font Suggestion] For Indian movies

### ISSUE THREAD

**Issue by Vishwamoorthy** [jurialmunkey/plugin.video.themoviedb.helper#1148]
### Describe the bug

Please suggest a font that shows Indian movie titles/tv shows properly in English. I don't want it to display in Hindi/any other regional languages. I just need it to show titles in English properly. I'll get the font file and replace it with Ronoto font files.

### Steps To Reproduce

Go to Indian movie list

### Screenshots and Additional Info

![image](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/87605110/8807d55c-d801-4fbd-b0a8-5378ce031c59)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Nothing to do with the plugin.

Change font to Arial.

**Comment by Vishwamoorthy** [comment]
change on TV? or replace file?

**Comment by Hitcher** [comment]
Kodi Settings > Interface > Skin > Fonts.
