### ISSUE TITLE
[BUG] Can't play content

### ISSUE THREAD

**Issue by Misioslav** [jurialmunkey/plugin.video.themoviedb.helper#1151]
### Describe the bug

My setup first:
I have jellyfish as backend for the library. I have Netflix, Disney and HBO subscriptions. TMDB Helper is set to export specific playlists from trakt for Disney and HBO to my library and sync it. Netflix is set similarly but it's set in the Netflix plugin settings to export My List.
Jellyfin uses my local library + strm files created by tmdb helper and Netflix plugin to feed Kodi the library. The whole library is on a NAS with dockers set up.
Kodi is installed on my Google TV directly (I have no other device currently to run it on but it does the trick).
In Kodi I have the following plugins for content: Netflix, Disney+, HBO Max, Jellyfin

When I play my local content it works fine, the same goes when I want to play a Netflix plugin series.
But when I want to play something from Disney+ or HBO Im getting an error. Previously I could pick which player should play the content of the show now it does not show up but when I go to TMDB helper and try to play it from there with preselected player by me it still gives the same result.
In short whenever I try to play something that was imported by TMDB Helper it throws error and I can't play it but if I use the dedicated plugin it works just fine but then it becomes a bit of nonsens to use TMDB Helper for that but I do not know how to create strm files automatically for shows from Disney and/or HBO to try to play it directly.

### Steps To Reproduce

1. Go to a show imported by TMDB Helper
2. try to play it
3. after building the player Kodi shows an error

### Debug log

https://paste.kodi.tv/oziwafuxut.kodi

### Screenshots and Additional Info

Additionally, Ive tried to rebuild the players for TMDB Helper because maybe something changed recently but still no luck.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Can you test latest version (v5.2.14) and let me know if that fixes the issue?

**Comment by Misioslav** [comment]
Oh, there was a newer version, it was not showing in the update section ;/
Anyway, I lost patience at one point yesterday and reinstalled Kodi from scratch. Now from what I see, I have 5.2.14 installed and it works fine.

In the TMDB Helper menu the issue was that conducting play action resulted in an error but then selecting from the context menu select player usually worked. But setting a default player and then using play would not work.
But I did not have that context menu in the library (as it's being added via Jellyfin).

Now each time I want to play a strm file added by TMDB Helper I have an additional step that asks me to pick the player to play the content with and it works.
Just the speed of starting the playback is a bit slow but I'm not sure why that is, Im just happy it works.

Thank you for checking this case. I will close the issue for now as it seems to work. Thank you also for great plugins :)
