### ISSUE TITLE
[BUG] Trailer problem

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1152]
### Describe the bug

I have a very interesting situation. I'm trying to use tmdb hleper as a fallback for playing auto trailers. I do that with the alarmclock and onfocus function. What happens is that when the trailer goes through the tmdb helper, it always goes to the trailer of the previously selected movie, regardless of whether the focus is currently on another movie. This only happens with the tmdb helper. Kodi, skin helper service, bingie helper... everything works as it should. What am I doing wrong? I use the container method for service monitor (Container(99950).ListItem.Trailer).

### Steps To Reproduce

1. I start to choose a movie.
2. I scroll through the movies one by one.
3. I stop for example on the movie Dark Knight.
4. Instead of starting a trailer for Dark Knight start a trailer for a previously focused film, for example Batman Begins.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by Bequiet19** [comment]
Yes, I had a similar experience with this problem so at some point I gave up from tmdb helper trailers. It would certainly be nice @jurialmunkey to fix this bug.

**Comment by matke-84** [comment]
@jurialmunkey It's definitely a bug with the tmdb helper. I just replaced in code of artic fuse `ListItem.Trailer` with `Container(99950).ListItem.Trailer` and it behaves the same as mine in the skin, always plays the trailer of previously focused movie. Try it, you'll see what I'm talking about.

**Comment by jurialmunkey** [comment]
The service cannot lookup item details until after the item has been focused. This is not a bug.

What you're expecting is magic! You want it to somehow see into the future which item the user will select next and then update the details before it is focused!

**Comment by matke-84** [comment]
I don't know if you understood me and if you read it well? I don't know where you read that it should predict something in advance. I'm talking about the fact that when I focus the movie after a certain number of seconds it should play the trailer, that's how I set it up in the skin and it works normally with the default Kodi `ListItem.Trailer`. When I use this same thing with tmdb helper `Container(99950).ListItem.Trailer`, instead of playing the trailer of the focused movie after a few seconds, it plays the trailer on previously focused movie. This is absolutely not normal behavior. I tell you again, with kodi default `ListItem.Trailer` it has always worked normally as well as with bingie helper. I don't know if you understand now, do you need a video with an example to see?

**Comment by jurialmunkey** [comment]
No I understood completely.

When do you set TMDbHelper.WidgetContainer? It is `<onfocus>`
When do you set the alarm to play the trailer? It is also `<onfocus>`

So when does the window property change for the TMDBHelper container to update to new container ID and item? **After** the `<onfocus>` commands have already fired. That's **after** you have set the alarm. 

You set the alarm **before** TMDbHelper has updated to contain the new item. $INFO is evaluated when `<onfocus>` fires, so your alarm command contains the previous value. It is all working exactly how you told it to act.

>  as well as with  bingie helper

That's because it is a script and not a service.... An entirely different thing.

**Comment by Bequiet19** [comment]
Ok, thanks for the clarification. So tmdb helper trailers can only be used for individual content, for example for playing in dialogvideoinfo, if I understand correctly?

**Comment by matke-84** [comment]
@jurialmunkey  Thanks for the answer, it's clearer to me now. @Bequiet19 Yes, I think it is best to use in video info dialog.
