### ISSUE TITLE
[Question] Get TMDB ID from player side

### ISSUE THREAD

**Issue by CaptainBlagbird** [jurialmunkey/plugin.video.themoviedb.helper#1153]
### Describe the feature that you'd like

(This is more a question than a feature request, there was no issue template for that.)

Hi, I'm working on a video plugin that can configured and used by TMDBH as a player.
When I click play on a movie, my plugin gets launched, and I can see that the QUERYKEY is replaced with the movie title.

Is it somehow possible that the TMDBH provides the TMDB ID to the player instead / in addition to the movie title?

Thanks for your help

### Why is this feature needed? What problem does it solve?

(This is more a question than a feature request, there was no issue template for that.)

My video plugin would proccess additional stuff for the selected movie. Having the TMDB ID would be less error prone than using the movie title which could be the same for multiple movies.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Yes. `{tmdb}`

All the available key names are documented in the wiki:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#available-keys

**Comment by CaptainBlagbird** [comment]
Ah how did I not see that... Thanks a lot!
Sorry for the inconvenience.
