### ISSUE TITLE
TMDB error check log 

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/plugin.video.themoviedb.helper#1156]
### Describe the bug

Hey tonight I've noticed on several occasions the error message appearing, it can be triggered by bringing up the video osd after starting kodi during playback and sometimes when exiting playback, I'm on the omega tmdb version as I'm running beta 2 on artic fuse with my nvidia shield, I've attached a log below

https://paste.kodi.tv/gihimuteci

Many thanks

### Steps To Reproduce

Start kodi
Bring up osd during playback 

### Debug log

https://paste.kodi.tv/gihimuteci

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Why did you close this issue?

**Comment by JFG1000** [comment]
I believe it may be an error on my end it was a certain episode i was on, I'm happy to re open it though if you was still wanting to look into it

**Comment by jurialmunkey** [comment]
> I believe it may be an error on my end it was a certain episode i was on, I'm happy to re open it though if you was still wanting to look into it

It's caused by being on the last available episode and TMDb not having a recommendation for next show to watch (or if it can't get the episodes for the show from TMDb)

I should catch the error as that's a valid scenario. Above will stop it from erroring if there's no next episode or recommendation to display.

**Comment by JFG1000** [comment]
Oh that's awesome many thanks and apologies for closing, I assumed it was something on my end. Thankyou for fixing this, I've just donated money for a coffee as a saying of thankyou it's greatly appreciated
