### ISSUE TITLE
[BUG] Context menu missing

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/plugin.video.themoviedb.helper#1157]
### Describe the bug

I'm not sure if this is the right place to ask but I'm on omega beta 2 and can't find where to install the global context menu. I have repo v3.4 installed and am using Arctic Fuse

### Steps To Reproduce

1. Open repo
2. no context menu option

### Screenshots and Additional Info

<img width="1237" alt="Screen Shot 2024-01-30 at 10 12 35 AM" src="https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/43726430/d2ab1c56-0f97-4af0-8929-71b6478bb1c9">

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
https://github.com/jurialmunkey/context.themoviedb.helper/releases

Have to install it manually from there. It really desperately needs an update for omega so I haven't included it on the repo. 

it probably works okay for most things and no real harm to installing it - just don't be surprised if it doesn't work properly sometimes.

**Comment by Liquidrag** [comment]
Thanks!
