### ISSUE TITLE
[Feature] Trakt Your Next Episodes - Sort Order

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/plugin.video.themoviedb.helper#1158]
### Describe the feature that you'd like

Would it be possible for the Trakt Your Next Episodes function to return the episode list sorted in the order that the shows have been played (i.e. the last show watched appears first in the list). I think the In Progress TV Shows function returns the shows in this order. At the moment the only sort option id "Date". 

### Why is this feature needed? What problem does it solve?

Provide a more logical sort order for Next Episodes

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
TMDbH Settings > Widgets > Next episodes sort method > recentlywatched

**Comment by berkhornet** [comment]
Brillia t! thank you
