### ISSUE TITLE
'Play using' not working from videos added to the library

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#116]
As the title says I just realised for those videos added to the library from the addon, the 'Play using' option from the context menu defaults to the built-in option from Kodi (select video player). Would it possible to change this behaviour so it lets you select the player to use?

**Comment by jurialmunkey** [comment]
See comment here: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/98#issuecomment-593048783
