### ISSUE TITLE
[BUG] Service monitor label empty inside version folder

### ISSUE THREAD

**Issue by Hitcher** [jurialmunkey/plugin.video.themoviedb.helper#1163]
### Describe the bug

When using the 'Show videos with multiple versions as folder' option in Kodi and opening the info dialog on a version the label `$INFO[Container(99950).ListItem.Label]` is empty.

Tested this on Arctic Fuse just to make sure it wasn't the code in my skin.

### Steps To Reproduce

1. Enable 'Show videos with multiple versions as folder'
2. Enter a video version folder
3. Open the info dialog

### Debug log

First info dialog is on the folder, second is on the version inside the folder.

https://paste.kodi.tv/abamakamib.kodi

### Screenshots and Additional Info

Info on the folder:
![screenshot00000](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/133808/bba34733-4efe-4370-a0f4-10f52eb8c998)

Info on a version in the folder:
![screenshot00001](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/133808/b6b449c2-06cd-4abb-85a3-40977cb67122)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I can reproduce but I think it's more likely a bug with Kodi versions than the plugin itself.

Ill test properly later today after work but I suspect label will be blank for any plugin container in info, not just TMDbH

**Comment by Hitcher** [comment]
That was my first thought but it seems odd that `ListItem.Label2` and `ListItem.Art(poster)` get filled.

![screenshot00000](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/133808/153490a4-9844-4f7a-8fef-09ea42d9e587)

**Comment by jurialmunkey** [comment]
Definitely not TMDbHelper.

Related to using getVideoInfoTag() method of ListItem inside version folder.

I can reproduce with a very simple plugin in Estuary:
https://github.com/jurialmunkey/plugin.video.testcase/tree/label_test

I replaced cast list with that simple plugin. Here's showing correctly outside of versions:
![screenshot00396](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/4618719/bfef88fc-daec-4ca6-b713-48aa58927ec9)


Then inside version folder label disappears
![screenshot00395](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/4618719/030cdc57-c821-4230-8d7c-2e3872e14541)

**Comment by jurialmunkey** [comment]
Bug reported in issue above ^^^

**Comment by Hitcher** [comment]
Thanks for looking into it.
