### ISSUE TITLE
Disable Trakt query in the settings

### ISSUE THREAD

**Issue by DWH-WFC** [jurialmunkey/plugin.video.themoviedb.helper#1164]
### Describe the feature that you'd like

Hello from Germany.

I've been using your addon for a long time.
Recently, when you start Kodi, a Trakt message pops up asking you to log in. I and I'm sure many other users don't use Trakt but just your addon.

Could you please install in the settings so that you don't have this tract query and it doesn't pop up all the time?

If you could remedy this, I and perhaps other users would be very grateful.

Best regards

### Why is this feature needed? What problem does it solve?

It solves the problem that no tract query pops up when starting Kodi.

### Screenshots and Additional Info
addons\plugin.video.themoviedb.helper\resources\tmdbhelper\lib\api\trakt\api.py

`
self.dialog_noapikey_header = f'{get_localized(32007)} {self.req_api_name} {get_localized(32011)}'
self.dialog_noapikey_text = get_localized(32012)
`

_No response_

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
You are only asked to login to Trakt if you are using a feature which relies on Trakt authorisation

Hard to tell without a debug log but most likely you've added a widget that uses Trakt sync. You need to remove whatever widget that is from your setup.

**Comment by DWH-WFC** [comment]
Then I have to check it again. But I actually don't use anything from Trakt. But thanks for the information.
