### ISSUE TITLE
[BUG] I added a new player and it doesn't appear

### ISSUE THREAD

**Issue by test01203** [jurialmunkey/plugin.video.themoviedb.helper#1171]
### Describe the bug

I added a new player and it doesn't appear

### Steps To Reproduce

I entered the extension
I chose player settings and manually added the extension I wanted
And it doesn't appear

### Screenshots and Additional Info

![image](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/104188844/7cacda9b-6a44-483c-98dd-94b92115841e)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

editing
The problem was discovered, it turns out that when there is an extension with a capital letter, then it does not recognize it

**Comment by jurialmunkey** [comment]
It is a kodi rule that addon id must only be lower-case. Addons which use capital letters will break many kodi features. You need to speak to that addon author and tell them to fix their id.
https://kodi.wiki/view/Addon.xml#id_attribute
