### ISSUE TITLE
[BUG] Cannot save DB to SMB

### ISSUE THREAD

**Issue by PostTraumaticOS** [jurialmunkey/plugin.video.themoviedb.helper#1172]
### Describe the bug

When going into “Extras” menu, and select an SMB location for DB Cache and Image Cache, an error will occur and files wont save to SMB. 

It does, however, create the default folders, so it doesnt seem like a writing permissions issue.

### Steps To Reproduce

1. Add SMB location to Files
2. Use that location in Extras Menu, DB Cache/Image Cache
3. Save
4. Reload skin

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I believe this was resolved via this commit https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/8421944625470028f24a0734647df04fefaf0a88
