### ISSUE TITLE
[Feature] Custom url lists

### ISSUE THREAD

**Issue by v4vale** [jurialmunkey/plugin.video.themoviedb.helper#1173]
### Describe the feature that you'd like

I would like to have the ability to populate a list from a custom URL.
For this to work, the external URL should return data in a defined format, and the URL configuration should support some pseudo variables (e.g. pagination or sort).
Regarding the format, I think a good starting point, which will also reduce the amount of work, could be the mdblist format, with maybe some extensions (e.g. episode or season support).

### Why is this feature needed? What problem does it solve?

This would give a boost in the customization of our hubs and provide a simple but incredible powerful way for developer to provide a way to integrate their work in kodi without the additional work to create an ad-hoc plugin. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
^^^ This will get us partly the way there. Allows for a locally saved MDblist in JSON format to be loaded.

Plugin path to load a custom file is 
```
plugin://plugin.video.themoviedb.helper/?info=mdblist_locallist&&path/to/your/json/file.json
```

Note the double ampersand `&&` must be used to specify the path to the file.

The file follows the standard MDbList format as per their API
https://docs.mdblist.com/docs/api#list-items

```json
[
    {
        "id":496243,
        "rank":1,
        "adult":0,
        "title":"Parasite",
        "imdb_id":"tt6751668",
        "mediatype":"movie",
        "release_year":2019,
        "language":"en",
        "spoken_language":"en",
    },
    {
        "id":361743,
        "rank":2,
        "adult":0,
        "title":"Top Gun: Maverick",
        "imdb_id":"tt1745960",
        "mediatype":"movie",
        "release_year":2022,
        "language":"en",
        "spoken_language":"en",
    },
]
```

So for instance if you save that in `addon_data/plugin.video.themoviedb.helper/lists/mylist.json` then you can access it with the following path:

```
plugin://plugin.video.themoviedb.helper/?info=mdblist_locallist&&special://profile/addon_data/plugin.video.themoviedb.helper/lists/mylist.json
```

**Comment by jurialmunkey** [comment]
^^^ And this commit will allow for seasons or episodes.

Examples for TV show item, season item and episode item:

TV Show item
```json
   {
        "id": 1399,
        "rank": 3,
        "title": "Game of Thrones",
        "mediatype": "show"
    }
```

Season item
```json
    {
        "id": 1399,
        "rank": 4,
        "description": "Game of Thrones: Season 2",
        "mediatype": "season",
        "season": 2
    }
```

Episode item
```json
    {
        "id": 1399,
        "rank": 5,
        "description": "Game of Thrones: Season 2 Episode 4",
        "mediatype": "episode",
        "season": 2,
        "episode": 4
    }
```

**Comment by jurialmunkey** [comment]
^^^ And custom list from a http url now supported

Example http json file
https://raw.githubusercontent.com/jurialmunkey/plugin.video.themoviedb.helper/d056a28374973de7881200a76193108d430475c8/resources/jsondata/example_mdblist_locallist.json

Example path to load from http file

```
plugin://plugin.video.themoviedb.helper/?info=mdblist_locallist&&https://raw.githubusercontent.com/jurialmunkey/plugin.video.themoviedb.helper/d056a28374973de7881200a76193108d430475c8/resources/jsondata/example_mdblist_locallist.json
```
