### ISSUE TITLE
[Request] Please create player for POV

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/plugin.video.themoviedb.helper#1174]
### Describe the feature that you'd like

Hi mate, hope its not much of a bother I was wondering if you please help me create a json file for the POV video-addon to be used as one of the players with TMDbhelper?
More info on POV here https://www.firesticktricks.com/pov-kodi-addon.html

### Why is this feature needed? What problem does it solve?

Gives me an option to select POV as a player :)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Considering that's a banned addon, sorry, no, definitely won't be making a player for it.

**Comment by onlytanmoy** [comment]
> Considering that's a banned addon, sorry, no, definitely won't be making a player for it.

Oh ok, wasn't aware of that, cheers for the info mate.
