### ISSUE TITLE
[Question] How to return "Because you watched header"

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1177]
When using endpoint:-

plugin://plugin.video.themoviedb.helper?info=trakt_becauseyouwatched&amp;type=tv

How do I return the "Because you watched {title}" string for use as a widget header. I've tried:-

`$INFO[Container(9000).ListItem.Property(param.plugin_category)]`

But I can't figure out how to return it.

**Comment by roidy** [comment]
Ok, figured it out, its:- 

`ListItem.Property(widget)`

Is this in the documentation anywhere? I couldn't find it :(

**Comment by daviddia5** [comment]
Hi, could you explain to me how to do it? I would like the same thing, that "because you watched (title)" appears in the widget

**Comment by jurialmunkey** [comment]
`$INFO[Container(widget_id_goes_here).ListItem.Property(widget)]`
