### ISSUE TITLE
[BUG] ListItem.Property(IsSpecial)

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1178]
### Describe the bug

The add-on does not set the `ListItem.Property(IsSpecial)` boolean for special seasons.

### Steps To Reproduce

No steps to reproduce.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I could be wrong but I don't think this is something plugins can set (at least I can't see a method to set it). I think it is something kodi evaluates only for the library.

All specials will have season 0 so you can check against that.

**Comment by roidy** [comment]
>I could be wrong but I don't think this is something plugins can set (at least I can't see a method to set it). I think it is something kodi evaluates only for the library.

No you can set boolean properties I do it in one of my custom plugins:-

```
li = xbmcgui.ListItem(.........)
li.setProperty('IsSpecial', 'true')
```

It can then be evaluated in skin:-

`<visible>ListItem.Property(IsSpecial)</visible>`

>All specials will have season 0 so you can check against that.

Yep, completely missed that, Thanks.

**Comment by jurialmunkey** [comment]
> No you can set boolean properties I do it in one of my custom plugins:-

Ah didn't realise it could just be set, I thought it was something Kodi evaluated. Okay I can add this in.

I've never actually used it before. I assume it gets used on Season and Episode items, or is it only applied to Season items ?

**Comment by roidy** [comment]
I only ever use it with Seasons but the skinning docs say it is used with both seasons and episodes and after a quick test I can confirm it is set for all episodes in the Special season.

Thanks

**Comment by roidy** [comment]
Tested and working perfectly for both seasons and episodes. Thanks 👍

**Comment by roidy** [comment]
Sorry to be a pain but could we also get the `Episode groups` and `Up Next` seasons marked as IsSpecial. You do refer to them as Special in the settings.

**Comment by jurialmunkey** [comment]
> Sorry to be a pain but could we also get the `Episode groups` and `Up Next` seasons marked as IsSpecial. You do refer to them as Special in the settings.

I did have that thought too.

**Comment by roidy** [comment]
Prefect, Thanks 👍
