### ISSUE TITLE
[BUG] API Keys not registering

### ISSUE THREAD

**Issue by AnOnlineGuyy** [jurialmunkey/plugin.video.themoviedb.helper#1185]
### Describe the bug

In the TheMovieDb Helper settings, I'm trying to add my MDblist and OMdb API keys and after I exit the setting they disappear and don't add. I've reinstalled the addon a few times but nothing works.

The same happens for the 'Default player for movies' and 'Default player for episodes' settings. Set to Umbrella source select, go off the settings and it disappears.

I am on v.5.2.21 using the Arctic Fuze theme.

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/164583913/87ebfe81-0ddf-45d2-91bf-8660f7e3a30f

### Steps To Reproduce

1. Go to TheMovieDb Helper Addon
2. Click on Settings
3. Navigate to API Keys
4. Add API Keys
5. Exit TheMovieDb Helper Settings

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
You didn't press OK on the left side to confirm the changes.

**Comment by AnOnlineGuyy** [comment]
I'm special. I apologise. My search and settings have also disappeared. Didn't change anything overnight.  Loaded it up and they're gone. Any tips?

![IMG_4899](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/164583913/b8b87cc0-bd10-4b9a-8271-a5239e8f519d)

**Comment by jurialmunkey** [comment]
> I'm special. I apologise.

Don't worry, I forget all the time myself that Kodi needs OK to be pressed to save the changes. It's a bit annoying that it doesn't warn you that the changes will be discarded.

> My search and settings have also disappeared. 

The fixed position icons have been removed from the skin.

You can add a search icon to the menu via Customise widgets screen. The shortcut can be found under the Hubs section.

The options menu can be accessed by pressing back from the home menu.

**Comment by AnOnlineGuyy** [comment]
Thanks for the help! I've added the search from my video apps to each of the side menu icons.
