### ISSUE TITLE
[BUG] Issue with new focus_id option on recommendations window.

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1188]
### Describe the bug

I've run in to an issue with this pull request #1187 :-

Using the following recommendations string (basically filling 5001-5008 with a cast list, or any list):-

`5001|info=cast|true|noop||5002|info=cast|true|noop||5003|info=cast|true|noop||5004|info=cast|true|noop||5005|info=cast|true|noop||5006|info=cast|true|noop||5007|info=cast|true|noop||5008|info=cast|true|noop`

When using the `focus_id` property only the first 4 lists get filled with data, the rest are empty. If I remove the `focus_id` property then all the list are correctly filled with data.

### Steps To Reproduce

none

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by roidy** [comment]
The only way I can get it to work is instead of setting the control focus in code `self.setFocusId(list_id)`

Is to use an option to not set focus in code and rely on the `<defaultcontrol>` tag in the skin ie:-

```
if list_id:
     _mon.waitForAbort(0.1)  # Wait to ensure first list is visible
    if not self._use_default_control_tag: 
        self.setFocusId(list_id)  # Setfocus to first list id or custom control
    list_id = None
```

`Runscript(plugin.video.themoviedb.helper,recommendations=5000|info=cast|true|info,window_id=1191,use_default_control_tag=true,.........)`

Then the default control can be set like any other Kodi window using the `<defaultcontrol>` tag.

**Comment by jurialmunkey** [comment]
Shouldn't be necessary. What's your log say? I expect the script is breaking because due to a type error in setFocusId.

https://romanvm.github.io/Kodistubs/_autosummary/xbmcgui.html#xbmcgui.Window.setFocusId

Expects `int` but you pass `str` from kwargs. Needs to be typecast to int

Instead of this line
```python
self._focus_id = kwargs.get('focus_id')
```

Try this instead
```python
self._focus_id = int(kwargs['focus_id']) if 'focus_id' in kwargs else None
```

**Comment by roidy** [comment]
Yep, that fixed it 👍 

Strangely the log shows no Type Errors. Is that because the function `_add_items` captures the TypeError and silently returns?

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/1ce133b4a4d547c60223fbd85a0db3af936da448/resources/tmdbhelper/lib/window/recommendations.py#L197-L206

**Comment by jurialmunkey** [comment]
> Yep, that fixed it 👍
> 
> Strangely the log shows no Type Errors. Is that because the function `_add_items` captures the TypeError and silently returns?
> 

Nah, the setFocusId happens outside that try block.

I get a TypeError (with the old code). It's inside a Thread so it appears differently in the log than a normal error (Thread class catches and re-raises) but I definitely get a TypeError when a str is passed.

Anyway, not too important as long as it is working correctly now.
