### ISSUE TITLE
[Question] Recommendations fanart

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1189]
### Describe the feature that you'd like

When calling the recommendations window to grab fanart or poster with:-

`5000|info=fanart|true|noop`

This only returns fanart from TMDB, is it possible to also grab the fanart from fanart.tv or is that call too costly performance wise?

I've tried:- `500|info=fanart&fanarttv=true|true|noop` but that doesn't work.

### Why is this feature needed? What problem does it solve?

Not a feature, just a question...... (Could we get a dedicated question template?)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
> This only returns fanart from TMDB, is it possible to also grab the fanart from fanart.tv or is that call too costly performance wise?

Less about performance and more that the API returns results differently so I'd need to wrangle the output to be compatible. 

Also makes pagination and item limits a real pain to manage if two different APIs are providing results in one list.


> Could we get a dedicated question template?

Just realised the discussions tab wasn't activated. Can now use Q+A section in discussions:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/discussions/categories/q-a

**Comment by roidy** [comment]
>Less about performance and more that the API returns results differently so I'd need to wrangle the output to be compatible.
Also makes pagination and item limits a real pain to manage if two different APIs are providing results in one list.

No problem, was more of an "am I doing something wrong" question than a feature request.

>Just realised the discussions tab wasn't activated. Can now use Q+A section in discussions:

Thanks 👍
