### ISSUE TITLE
[BUG] Trakt Watchlists do not update immediately.

### ISSUE THREAD

**Issue by JukeBoX87** [jurialmunkey/plugin.video.themoviedb.helper#1190]
### Describe the bug

For example, I add a film from the official Trakt website to Watchlist and in TMDB Helper the film does not appear in the list.

### Steps To Reproduce

1. Go To Trakt.tv
2. Add a film in your Watchlist
3. Go to TMDB Helper / Trakt / Watchlist
4. The added movie is not available

### Debug log

jurialmunkey, is it possible to provide me with a script to clear the Trakt cache and reload the skin so I can add a custom command to do this quicker than going into the TMDB Helper options.
By clearing the Trakt cache it is the only solution to refresh the list and display new items.
Thank you in advance for your support.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
```
RunScript(plugin.video.themoviedb.helper, delete_cache=Trakt)
```

**Comment by JukeBoX87** [comment]
Thank you so much! Is it possible to do this without a confirmation message?

**Comment by jurialmunkey** [comment]
No, can't override confirmation.

**Comment by JukeBoX87** [comment]
Thank you I will do with the confirmation message. How can I now automate this script and then refresh the skin, all in one command? Thanks
