### ISSUE TITLE
[BUG] latest/next episode title flashes on episode change

### ISSUE THREAD

**Issue by decknine** [jurialmunkey/plugin.video.themoviedb.helper#1192]
### Describe the bug

Hi, first I'm not sure if this is a bug but it has been annoying me lately. when using either: $INFO[Window(Home).Property(TMDbHelper.ListItem.Last_Aired) or next aired if I navigate too quickly through episodes displayed on screen, in episode view,  the displayed text for last aired/next aired flashes. looks like its updating or something? like its checking for each episode instead of deferring to the season or tv show itself. 

### Steps To Reproduce

as described above

### Debug log

this happens on both my windows install and android 

### Screenshots and Additional Info

![Capture](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/42182450/5fad3ee2-1bfd-4929-99c4-c65725eb5fb9)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Properties will be cleared when switching items before setting new values. If you don't want this to occur, you need to use the container method instead.

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor#container-method

**Comment by decknine** [comment]
ah that makes perfect sense, thank you!
