### ISSUE TITLE
[BUG] Playing a show from trakt "your next episodes" only plays two then stops

### ISSUE THREAD

**Issue by Narowang** [jurialmunkey/plugin.video.themoviedb.helper#1193]
### Describe the bug

When I play a show with the your next episodes (widget and in the add-on) it will only play two episodes. At the end of the first episode it brings up the box asking if I want to watch the next episode and moves on fine but at the end of the second episode it doesn't come up and just returns to the home screen after it finishes playing. I'm using seren but not sure if that is important

### Steps To Reproduce

1. Play a show through the "your next episodes" section in the trakt section of the add-on (one with more than two episodes remaining
2. Watch two episodes and wait for the second one to finish

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by Mahava** [comment]
Got the reply, thanks.    Is there a rmdbhelper version coming for Omega?

**Comment by jurialmunkey** [comment]
This is to do with the end addon used to play content, not the TMDbHelper.

**Comment by roberestarkk** [comment]
Just in case anyone else has this issue and finds it from Google like I did, A4kPlayers seems to be the relevant culprit:
https://github.com/a4k-openproject/json.openplayers/issues/96 

The 'players' config hasn't been updated for Seren 3.0.
