### ISSUE TITLE
Show original language of a movie or tv show

### ISSUE THREAD

**Issue by ananias47** [jurialmunkey/plugin.video.themoviedb.helper#1196]
### Describe the feature that you'd like

Hi 
Firstly thank you for your amazing work
It would be great if you can add the original language of the movie or tvshow to add it on my skin 

### Why is this feature needed? What problem does it solve?

Because many links like from rd has not have the original language of the movie or tv show by default it is difficult to determine the original language

### Screenshots and Additional Info

![1](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/6560173/6233c45f-1d3d-4d19-8270-b7ee94a158bd)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by manolischania** [comment]
hi i was grabbing the original language with info label but it's stop working is something i have to do ? 
`<label>b$INFO[Container(9143).ListItem.Property(original_language)]b</label> `

**Comment by jurialmunkey** [comment]
@manolischania - Will be fixed when I push next version (6.8.11). I just forgot to map it. Fixed here: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/01ead973e6d1834f415e5627d4106194adab3399

Previously cached details will require a refresh to get the new data.

**Comment by manolischania** [comment]
Hi sorry to reopen it .. < at series > in the beginning we was having the language also at the episodes now i can not see the language at the episodes
Thanks in advance
