### ISSUE TITLE
[FEATURE] Add filter by Library Movies for discover or trending list

### ISSUE THREAD

**Issue by ntls2000** [jurialmunkey/plugin.video.themoviedb.helper#1198]
### Describe the feature that you'd like

Not found this function in filter
Display movies from the local library first on discovery or trending list

Practical for quickly identifying on trending lists when you have a lot of movies on kodi, if you not have a premium trakt

### Why is this feature needed? What problem does it solve?

Not a premium trakt
Display first local library when use discovery or trending list

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
See filter and exclude params here
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Lists-Additional-Params

Exclude by dbid and with value is_empty.

All library items have dbid so if it is empty then it is not a library item.
