### ISSUE TITLE
[Request] Player Documentation

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#12]
Hoping you'll give us some guidance in how to write and distribute player files soon... There are some third-party add-ons that have similar functionality, but it appears that the player files are quite a bit different.

**Comment by jurialmunkey** [comment]
Still ironing out some bugs but it's pretty straightforward. I'm planning on keeping it fairly simple.
For an example, see the netflix player:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/players/netflix.json

Put player files in `userdata/addon_data/plugin.video.themoviedb.helper/players/`

- "name": label in the pop-up select dialog
- "plugin": plugin ID which is used to check if addon is installed. 
- "search_movie": movie plugin url passed to `ActivateWindow(videos, url, return)`
- "search_episode": episode plugin url passed to `ActivateWindow(videos, url, return)`
- "play_movie": movie plugin url passed to `PlayMedia(url)`
- "play_episode": episode plugin url passed to `PlayMedia(url)`

Use play_movie/episode if the url will directly play the item.
Use search_movie/episode if the url will open a search folder of items.


Curly brace {keys} are used to format the url with the appropriate info. Keys that can be used:
- {id}
- {tmdb}
- {imdb}
- {tvdb}
- {trakt} `trakt number id`
- {slug} `trakt slug id`
- {name} `Title (Year)`
- {season}
- {episode}
- {firstaired}
- {premiered}
- {released}
- {clearname}
- {thumbnail}
- {poster}
- {fanart}
- {epid} `tvdb episode id`
- {epimdb} `imdb episode id`
- {eptmdb} `tmdb episode id`
- {eptrakt} `trakt episode id`
- {now} `Current timestamp`

Use special suffixes to replace spaces with appropriate url formating (replace KEY with one from above list)
- {KEY_+} replaces spaces with `+`
- {KEY_-} replaces spaces with `-`
- {KEY_escaped} replaces spaces with `%2520`
- {KEY_escaped+} replaces spaces with `%252B`

**Comment by notoco** [comment]
Can you unlink {title} - Title (year) to only {title} and add {year} separately?

**Comment by jurialmunkey** [comment]
You already can.
Sorry I missed a few of the possible tags:
{title} = `episode title or movie title`
{showtitle} or {tvshowtitle} or {clearname} = `tvshow title or movie title`
{year} = `year only e.g. 1999`
{originaltitle} = `original language title`

**Comment by notoco** [comment]
cool. All in all, I looked at the code and saw that it was.

**Comment by jurialmunkey** [comment]
> 
> 
> cool. All in all, I looked at the code and saw that it was.

No worries! Let me know if any other infolabels are needed. I can pass through pretty much any, just not sure what others are useful.

**Comment by notoco** [comment]
You also need to improve on the Wiki. I am looking forward to when it will be added to the ArcticZephyr2 skin

**Comment by drinfernoo** [comment]
@notoco AZ2 already uses TMDbHelper in it's info dialog.

**Comment by notoco** [comment]
I know, but I don't see the play option

**Comment by notoco** [comment]
okay - I found, I searched earlier after entering information, and not after entering directly.
