### ISSUE TITLE
[Feature] Additional Fanart

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#120]
Would it be possible for you to add additional fanart artwork (where available)?
eg:
ListItem.Art(fanart1)
ListItem.Art(fanart2)
ListItem.Art(fanart3)

Thanks!

**Comment by xyzfre** [comment]
When using AuraMod Netflix Hub landscape view The clear logos don’t show up,,but if I go inside TMDB Helper for example next up episodes landscape view the clear logos show up ,,trying to explain the best that I can

**Comment by jurialmunkey** [comment]
@xyzfre that's not a tmdbhelper issue. Please discuss auramod skin issues on its own github page.

**Comment by xyzfre** [comment]
My apologies wasn’t too sure if it was a AuraMod issue or TMDB Helper,,,,, You have done an AMAZING job with TMDB H It gets better and better appreciate all your hard work that goes into this development

**Comment by xyzfre** [comment]
I got it working I went into TMDB Helper settings and enabled use fanart.tv for widget artwork ,did the trick ,sorry just wanted to share that in case Someone may come across this Clear logo thing ,, GREAT WORK on TMDB Helper

**Comment by drinfernoo** [comment]
I'd like to say as well, additional fanart would be great 👍 I always miss the fanart "slideshow" backdrop in AZ2 when using TMdbHelper widgets 😅

**Comment by jurialmunkey** [comment]
Okay, v2.2.77 should add support for extrafanart (requires fanarttv enabled).

@skyfsza @drinfernoo - Can you test and confirm that it's working for you? It looks like it is working correctly on my end.

---
Relevant Commit: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/66c5cd90952db1ead7ee2b4a0859f0a3d51c16c5

**Comment by skyfsza** [comment]
Working my side, thanks!

**Comment by jurialmunkey** [comment]
Excellent 😁
