### ISSUE TITLE
Context menu> TMDbHelper options> Trakt options ...doesn't work

### ISSUE THREAD

**Issue by Mahava** [jurialmunkey/plugin.video.themoviedb.helper#1202]
### Describe the bug

Using context menu on TMDB widget artwork on kodi homepage to add title to Trakt lists doesnt work.  Screen dims but no dialogue box appears.
[log.txt](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/15172592/log.txt)

### Steps To Reproduce

From widget art on the homepage select context TMDbHelper options
Then select trakt options to add that title to a trakt list

### Debug log

[log.txt](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/15172605/log.txt)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
There is no reason to use the context menu addon for TMDbHelper items. 

These context menu entries are in the main context menu for a TMDbHelper item. Use the proper context menu entry, not the one in subfolder, and it will work correctly.

The context menu addon is only for Library items and requires a lot of guess work to try to work correctly, but will sometimes fail.
