### ISSUE TITLE
[BUG] bug in translation function for title and plot of episode 

### ISSUE THREAD

**Issue by teletcl** [jurialmunkey/plugin.video.themoviedb.helper#1207]
### Describe the bug

I've found a bug in translation function for title and plot of episode - function for players return title and plot for tvshow instead of episode when use prefix of language. (For movies works ok.)

### Steps To Reproduce

Test configuration (fragment)
```json
 "api_language": "en-US", 
 "language": "pl", 
 "play_movie":     "plugin://plugin.video.xxx/?action=play&title={title_url+}&localtitle={pl_title_url+}&year={year}&imdb={imdb}&tmdb={tmdb}&originalname={originaltitle_url+}&plot={pl_plot_url+}", 
 "play_episode":   "plugin://plugin.video.xxx/?action=play&title={title_url+}&localtitle={pl_title_url+}&tvshowtitle={showname_url+}&localtvshowtitle={pl_showname_url+}&year={year}&season={season}&episode={episode}&tmdb={tmdb}&imdb={imdb}&epimdb={epimdb}&originalname={originaltitle_url+}&plot={pl_plot_url+}",
```
So tags `{pl_title}` and `{pl_plot}` are works wrong in such case. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Example tvshow episode to reproduce the issue?.

Edit: nvm. see the issue.
