### ISSUE TITLE
[Feature] Please add back the Seasons and Episode Nos. in Next Episodes folder

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/plugin.video.themoviedb.helper#1208]
### Describe the feature that you'd like

Hi @jurialmunkey,

Hope you're doing well.

Could you please add back the recently removed Season and Episode Nos. in Next Episodes folder? It really helps while using it as a widget rather than going to each episode separately and have a look at the info details.

### Why is this feature needed? What problem does it solve?

It helps while having a glance when using the Next Episodes folder as a widget.

### Steps to reproduce.

Go to Next Episodes folder and see the Episode titles.

### Screenshots and Additional Info

In TMDB Helper:

![IMG20240516222225](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/65297828/57605506-c35f-4ac8-96ec-c9f834b21a0c)

In other add-ons (how TMDB Helper used to show the Episode titles earlier):

![IMG20240516222210](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/65297828/8f10ef37-de43-4bb0-8f2f-62f39946f7a7)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by booyakafoo** [comment]
That info is included under the Title logo, WEB - **1x4** - Date.  I prefer the cleaner title names.

**Comment by jurialmunkey** [comment]
I have not removed anything.

Tmdbhelper is behaving correctly and is  as close as possible to the same behaviour of the kodi library.

It is up to the skin to decide how to display this information.

Addons which force other numbers or stupid colours etc into the title are the ones which are wrong and are a  pains for skins because they don't allow choice. 

The title should be the title with no other information.

The title isn't "s01e01 - name". The title is just "name" and so should be that way in the plugin. 

The skin decides how the interface looks, not the plugin.

**Comment by AakashC2020** [comment]
> That info is included under the Title logo, WEB - **1x4** - Date. I prefer the cleaner title names.

Hi @booyakafoo,

Yes, I know that. However, for that we need to go to each episode separately and see the numbers. That's why I raised the request, but no issues...

**Comment by AakashC2020** [comment]
> I have not removed anything.
> 
> Tmdbhelper is behaving correctly and is as close as possible to the same behaviour of the kodi library.
> 
> It is up to the skin to decide how to display this information.
> 
> Addons which force other numbers or stupid colours etc into the title are the ones which are wrong and are a pains for skins because they don't allow choice.
> 
> The title should be the title with no other information.
> 
> The title isn't "s01e01 - name". The title is just "name" and so should be that way in the plugin.
> 
> The skin decides how the interface looks, not the plugin.

Hi @jurialmunkey,

No problem. Thanks for letting me know that this is not possible! I can manage with whatever is available. It's not a big issue...
