### ISSUE TITLE
[Feature] Option to include Specials in Trakt Next Episodes, In-Progress etc

### ISSUE THREAD

**Issue by Ade-AV** [jurialmunkey/plugin.video.themoviedb.helper#1209]
### Describe the feature that you'd like

Would like to have an option to include Specials in Trakt lists

### Why is this feature needed? What problem does it solve?

Sometimes shows have actual episodes as specials, so would like to see these appear in my widgets when they air if possible

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
This is not provided in Trakt data for next episodes (nor would it make sense).

Next/In-Progress tells you the next episode in order after the one you last watched. A special always has season 0 so it will never be in this order. If you've just watched S03E06 it makes no sense to show S00E03 special as the next episode. The only next episode will be S03E07 or S04E01 (if it was seasons finale).

Specials are already shown in Trakt calendars (where it does make sense).

**Comment by Ade-AV** [comment]
Get what you're saying about Next/In-Progress

Is there any way of showing in tmdb helper shows that have unwatched specials? e.g. I've watched all Ghosts (UK) seasons but have not watched any of the (ended) specials?

Thanks

Edit: If I mark an episode as watched in a fully watched show then that episode appears as the next in Your Next Episodes and the show also appears in Your In-Progesss TV Shows, if I mark a special episode as unwatched in a fully watched show then that episode and show do not appear in Your Next/In-Progess
