### ISSUE TITLE
[Feature Request] Ignore files in library

### ISSUE THREAD

**Issue by miguelms11** [jurialmunkey/plugin.video.themoviedb.helper#121]
By default the player function will play local files found in the library. Also, when clicking 'more episodes' on a TV show it shows only local files if the show is found in the library. 

Would it be possible to add an option to disable this behaviour? So the dialog for the user to select a external player will be displayed even if the files are found in the library, and clicking 'more episodes' will behave as if no files were found in the library.

Thanks for your help.

**Comment by jurialmunkey** [comment]
Ah I was having this exact same thought the other day. I'll let you know when I have something working.

**Comment by jurialmunkey** [comment]
This commit https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/c8332c55abd0d2165fbcf3f60007696d59fe0513 should provide the option to "Play With Kodi" in the player dialog if an item is found in the local library.

I'm not sure what you mean by the "More Episodes" option? Doesn't sound like something from TMDbHelper. Can you get a screenshot of this issue?

**Comment by miguelms11** [comment]
You are right. The "More Episodes" options is not something from TMDbHelper. Sorry for the confusion.

The "Play With Kodi" option works great. Thank you!

**Comment by jurialmunkey** [comment]
> The "Play With Kodi" option works great. Thank you!

No worries! Thanks for testing.
