### ISSUE TITLE
[BUG] Notification bug popups

### ISSUE THREAD

**Issue by Fred-IV** [jurialmunkey/plugin.video.themoviedb.helper#1212]
### Describe the bug

I keep getting popup notifications while watching shows that TheMovieDB Helper is updating.
I have the notification OFF in Kodi, yet it keeps happening.
I cannot find a setting within the addon to disable notifications.
It must have it's own notifications outside of the Kodi UI, and ignores the Kodi prefs.

### Steps To Reproduce

Watch movies or show. I am not sure of the frequency, but it keeps happening.

### Debug log

not a debug issue, no crash, this is a by design bug.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Turn off library integration in TMDbHelper settings and you will no longer have notifications about TMDbHelper updating the library.
