### ISSUE TITLE
[BUG] tmdb connection error on kodi.

### ISSUE THREAD

**Issue by Ravangergg** [jurialmunkey/plugin.video.themoviedb.helper#1214]
### Describe the bug

it used to work fine before and without any changes made by me it stopped updating my library and just throws the error something along the lines " failed to connect to remote site" "connection error: suppressing retries for 30 seconds" etc. I have attached the log for more info

### Steps To Reproduce

1. Run Kodi
2. Wait for the error message to pop up on its own 
3. Also When searching/browsing for any movies or updating library

### Debug log

https://paste.kodi.tv/lotuvasuco

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Not sure what you want me to do about it?

Either TMDb api server is down, they're rate limiting you, or your ISP is blocking you.

**Comment by Ravangergg** [comment]
I am really sorry to bother you but can I know what can I do in each of the cases. (I don't know much about all these and am very new to these)

**Comment by Ravangergg** [comment]
I am really sorry to bother you but can I know what can I do in each of the cases. (I don't know much about all these and am very new to these)
![Screenshot_2024-06-04-10-44-17-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/129038721/00c90dcf-cd63-463e-9f6f-3ac2da5b9c24)

**Comment by jurialmunkey** [comment]
When you make a lot of requests to the api, it rate limits you and stops you from making more requests. In response the plugin prevents you from making more requests for 30 seconds as a cool down.

It doesn't matter that the api is showing as up. If you spam them with an excessive amount of requests then they will stop serving for a time.

There also could be other factors at play such as your ISP blocking you, or your firewall preventing requests from kodi etc

**Comment by Ravangergg** [comment]
Thanks for your support .
I figured it out.
It was me connecting to mobile hotspot but when I turned on the cloudflare warp network which works as a vpn it was all back in place.
And do I need to mark this solved and if so how do I do it?

**Comment by jurialmunkey** [comment]
Glad you figured it out.

No need to do anything for the issue. I already closed it.
