### ISSUE TITLE
[BUG] Cannot retrieve artwork for a specific movie title

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/plugin.video.themoviedb.helper#1215]
### Describe the bug

It looks like the Movie ID is different from what is shown when refreshing artwork in Kodi, compared to the TMDB website.

When I refresh artwork, I am getting "No artwork found for movie ID 1296838"
When I searched the TMDB website, I found the [movie](https://www.themoviedb.org/movie/1299386-die-hart-2-die-harter) with a different movie ID 1299386

### Steps To Reproduce

1. try to refresh artwork for Die Hart 2: Die Harter movie
2. no artwork found (notice movie ID)
3. search for movie in TMDB website (notice different movie ID)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
When I search the other id on google it comes up in the results.

Likely what happened is that the movie was originally created with one id then it was deleted for some reason and now exists at a new id. I've seen it happen once or twice before.

If this is in your library you'll need to refresh library meta data. If it's in tmdbhelper then you'll need to refresh the tmdb and item cache.

It's also possible the server still has the old value cached and will need to wait a while for it to update.

**Comment by jurialmunkey** [comment]
Actually even your second id doesn't work on the website now either.

This sounds like there is debate on the website about whether it not this should be listed as a movie. People probably try to keep adding it and then it gets deleted by admin.

**Comment by jurialmunkey** [comment]
"Die Hart 2: Die Harter is a re-release of the TV show's second season as a feature film"

This will be why. Tmdb will say this still counts as a season - they generally don't allow duplicate entries for different release types. Re-releasing the episodes all joined together doesn't count as a separate film.

**Comment by vella9** [comment]
Thank you for the info jurial. Appreciated

**Comment by adamosborne83** [comment]
> "Die Hart 2: Die Harter is a re-release of the TV show's second season as a feature film"
> 
> This will be why. Tmdb will say this still counts as a season - they generally don't allow duplicate entries for different release types. Re-releasing the episodes all joined together doesn't count as a separate film. 

I ended up deleting it out of my library, every time it rescraped it came up different. Frustrating to say the least.
