### ISSUE TITLE
 TMDB Access Blocked in India Causing Plugin Failures

### ISSUE THREAD

**Issue by ajay01994** [jurialmunkey/plugin.video.themoviedb.helper#1216]
### Describe the bug

Description
The TMDB API is currently blocked in India, leading to failures in fetching TV shows, movies, and other related information within the plugin.video.themoviedb.helper. Users in India are encountering TMDB errors that prevent the plugin from functioning correctly.

Steps to Reproduce
Attempt to use the plugin from an IP address in India.
Try accessing any movie or TV show information.
Observe the TMDB error that occurs due to the blockage.
Expected Behavior
The plugin should be able to fetch and display TV shows, movies, and other relevant information without encountering an API blockage issue.

Actual Behavior
When attempting to access TMDB data, the plugin fails and displays an error related to TMDB being blocked.

Possible Solution
A potential fix is to implement an alternative API  within the plugin to bypass the TMDB blockage in India. This method has been discussed and successfully implemented in similar scenarios, as detailed in this issue: [elgatito/plugin.video.elementum#1027](https://github.com/elgatito/plugin.video.elementum/issues/1027). and 
https://github.com/elgatito/plugin.video.elementum/issues/1049

Additional Context
The TMDB blockage issue has been confirmed by multiple sources, including this forum post: [Indian Government has blocked TMDB](https://forum.moviebase.app/t/indian-government-has-blocked-tmdb/1874).

Implementing a workaround similar to the one used in the Elementum plugin could provide a solution for users affected by this issue.

### Steps To Reproduce

Attempt to use the plugin from an IP address in India.
Try accessing any movie or TV show information.
Observe the TMDB error that occurs due to the blockage.
Expected Behavior
The plugin should be able to fetch and display TV shows, movies, and other relevant information without encountering an API blockage issue.

### Screenshots and Additional Info

Actual Behavior
When attempting to access TMDB data, the plugin fails and displays an error related to TMDB being blocked.

Possible Solution
A potential fix is to implement an alternative API  within the plugin to bypass the TMDB blockage in India. This method has been discussed and successfully implemented in similar scenarios, as detailed in this issue: [elgatito/plugin.video.elementum#1027](https://github.com/elgatito/plugin.video.elementum/issues/1027).

Additional Context
The TMDB blockage issue has been confirmed by multiple sources, including this forum post: [Indian Government has blocked TMDB](https://forum.moviebase.app/t/indian-government-has-blocked-tmdb/1874).

Implementing a workaround similar to the one used in the Elementum plugin could provide a solution for users affected by this issue.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by OfficerKD637** [comment]
I am not exactly familiar with this issue, but if your ISP is geoblocking TMDB as a whole, you can simply change the DNS servers of your main router (which should then apply to any APs connected and any/all devices on your network) to Google (8.8.8.8 or 8.8.4.4) or Cloudflare (1.1.1.1 or 1.0.0.1) to bypass your ISP's restrictions. Do an A/B test to see which servers provide better speeds/stability but in most cases the difference is miniscule. 
And these new servers should theoretically provide equally good if not better performance than your current ISP's servers.

This is a very simple fix. Just login to your router's IP and you should find the setting under Network > WAN > Advanced (specific steps may vary depending on the brand of the router).

**Comment by jurialmunkey** [comment]
I have added a setting under expert settings to allow toggling to the alternative API url. You should restart Kodi after enabling it to ensure it takes full effect.

It's not really a long term solution though. If your ISP is actively attempting to block TMDb traffic then as soon as they discover this alternative URL, I would expect they will block it as well -- at which point you will either need to look into alternative DNS options (if it's just a DNS block), a VPN, or a different ISP.
