### ISSUE TITLE
[Feature] Watchlist combined

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1217]
### Describe the feature that you'd like

It would be nice if this list (and some other trakt lists) were given the possibility to combine movies and TV shows.

### Why is this feature needed? What problem does it solve?

It would be nice if we had the possibility to have one list where both, movies and tv shows, would be compiled. Also then we could set only one widget and not have two separate ones. For example Netflix has a list like this.

### Steps to reproduce.

-

### Screenshots and Additional Info

-

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
You can do this with a SkinVariables filter to combine whatever paths you like
https://github.com/jurialmunkey/script.skinvariables/wiki/Filtering-Plugin-and-Library-Directories


```
plugin://script.skinvariables/?info=get_filter_dir&library=video&&plugin://firstpath&&plugin://secondpath
```

**Comment by matke-84** [comment]
Thanks. It's not a bad solution, although it would be nice to have the option "both" in the list itself so that skinners don't have to use skin variables. But I see that skin variables has evolved and now has a lot of options.
Although you wrote in wiki of skinvariables that some details are not available due to the performance, I think that the basic info like is the duration of the movie or tv show season or episode is necessary and it will not affect the performance much.
