### ISSUE TITLE
[Feature] Artworks for collections

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1218]
### Describe the feature that you'd like

It would be nice if it had artworks for collections. I see that fanart.tv has a lot of artwork for collections so I hope it can be implemented in tmdb helper. I'm primarily thinking of the clearlogo, since it's the one that's missing the most.
https://fanart.tv/movie/10/star-wars-collection/

### Why is this feature needed? What problem does it solve?

-

### Steps to reproduce.

-

### Screenshots and Additional Info

-

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Didn't realise it wasn't working. Easy fix.

**Comment by matke-84** [comment]
Thanks. ;-)
