### ISSUE TITLE
[BUG] Random movies and tv shows genre list - Missing clearlogo

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1219]
### Describe the bug

Hi Jurial. There is a small bug with the lists "Random Movies Genre" and "Random TV Shows Genre". When I enter these lists, if I have not previously opened a movie or tv show, the clearlogo doesn't appear on first page. In fact, it shows the clearlogo only if it has been previously cached. Also if I go to the next page they start to appear. I only noticed this from these two lists.

### Steps To Reproduce

1. Open Randomised/Random Movies Genre or TV Shows Genre
2. No clearlogo
3. I go into the menu (Маnage artworks/Select artwork) to check if it has clearlogo.
4. Clearlogo exists
5. I go to the next page, clearlogo appears on movies/tv shows.

### Debug log

-

### Screenshots and Additional Info

![qqq](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/74268331/5a2de180-12f0-472a-b140-12ce4c4198b6)
![www](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/74268331/f06b2254-cc13-4e23-98f3-98781114be96)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Works fine for me. What makes you think this is an addon issue and not an issue with the skin or a connection issue?

If the clearlogo exists in the info, the the addon has done its job. It is not in charge of rendering, only adding the url metadata to the infolabel.

**Comment by jurialmunkey** [comment]
Also, if the clearlogo has not been cached, then it has to be downloaded first before it can be cropped. This process takes time. It isn't magic - you have to wait for it to download, be cropped, then cached both by TMDbHelper and Kodi.

**Comment by matke-84** [comment]
I tried several skins and the same thing happens. I think your skins display clearlogo differently. If I'm not mistaken, you use the tmdb helper service monitor for clearlogo but i use standard kodi ListItem.Art(clearlogo) like many other skins. It also appears only with these two lists ("Random Movies Genre" and "Random TV Shows Genre"). I guess there would be a problem with some other lists.

**Comment by jurialmunkey** [comment]
Is ListItem.Art(clearlogo) empty? Or is the skin simply not displaying it? And why do you think it is not simply a connection error to FanartTV? Do you have retrieve extra details enabled?

As I said it works fine for me. The clearlogo is listed both in the crop and the standard value.

And when I say it works, I don't mean "Oh my skin displays a logo". I'm inspecting the value of `$INFO[ListItem.Art(clearlogo)]` using JSON-RPC via DevKit in SublimeText3 and it is filled, so it is there regardless of it being my skin or someone elses.

**Comment by jurialmunkey** [comment]
I see what is possibly happening. Cache only value inherited from seed list and depending on config is overriding values.

**Comment by matke-84** [comment]
And this solved the problem... Thanks.
