### ISSUE TITLE
[Enhancement] GUI

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#122]
I was thinking how nice it might be if TMDBH could incorporate the GUI of Extended Info Mod. Any interest in making that happen?
![Screenshot_5](https://user-images.githubusercontent.com/45118866/75822664-53af3b00-5d6e-11ea-873d-597ea344088e.jpg)

**Comment by jurialmunkey** [comment]
That's up to skinners to implement. The info screen in TMDbHelper doesn't run as a script so it functions differently to Extended Info et al. 

TMDbHelper actually now allows for native use of the video info dialog, which I believe is a better approach as it allows for better integration.

For instance, here is the TMDbHelper info screen in Arctic Horizon:

![Honeyview_screenshot597](https://user-images.githubusercontent.com/4618719/75824054-f4e1d400-5df6-11ea-8a47-99da80c088c7.jpg)

**Comment by JayDee696969** [comment]
> That's up to skinners to implement. The info screen in TMDbHelper doesn't run as a script so it functions differently to Extended Info et al.
> 
> TMDbHelper involves native use of the video info dialog, which I believe is a better approach as it allows for better integration. It also means that it is impossible to ship a "default" skin for TMDbHelper because it just uses whatever is in the skin being used.
> 
> For instance, here is the TMDbHelper info screen in Arctic Horizon:
> 
> ![Honeyview_screenshot597](https://user-images.githubusercontent.com/4618719/75824054-f4e1d400-5df6-11ea-8a47-99da80c088c7.jpg)

Hmm, Ok. Maybe its possible to add an option to the "Default select action in addon" to open extended info by default?

**Comment by jurialmunkey** [comment]
> Hmm, Ok. Maybe its possible to add an option to the "Default select action in addon" to open extended info by default?

Why? What would be achieved by shelling out to a different script when TMDbHelper has all those functions?

**Comment by JayDee696969** [comment]
Well I guess i just like the GUI of Extended Info Mod as opposed the the GUI of the details section in TMDBH when you click a title. Preferably an all in one solution to have all the options that TMDBH has in the details section as buttons in the Extended INFO GUI like add to library, add to Trakt, Videos/Trailers. That way wouldnt need to authorize trakt in Openmeta and TMDBH and the addons that we use with the players for TMDBH.

**Comment by JayDee696969** [comment]
Oh, and whats arctic horizon? I dont see that skin in your repo?

**Comment by drinfernoo** [comment]
@JayDee696969 It is an as-yet unreleased skin: https://forum.kodi.tv/showthread.php?tid=351756

**Comment by drinfernoo** [comment]
If you are using a skin that uses TMDbHelper in the standard information dialog, there's absolutely no reason to use EIS or any of its derivatives any longer, as that functionality has been replaced by TMDbHelper.

**Comment by JayDee696969** [comment]
> @JayDee696969 It is an as-yet unreleased skin: https://forum.kodi.tv/showthread.php?tid=351756
> 
> If you are using a skin that uses TMDbHelper in the standard information dialog, there's absolutely no reason to use EIS or any of its derivatives any longer, as that functionality has been replaced by TMDbHelpeIm 

> @JayDee696969 It is an as-yet unreleased skin: https://forum.kodi.tv/showthread.php?tid=351756
> 
> If you are using a skin that uses TMDbHelper in the standard information dialog, there's absolutely no reason to use EIS or any of its derivatives any longer, as that functionality has been replaced by TMDbHelper.

Well im not talking about functionality, im talking about the look and feel, hence [Enhancement] GUI in the title. And yea, there is a "reason". The GUI of Openinfo looks a heck of a lot better IMO.

**Comment by drinfernoo** [comment]
@JayDee696969 What I'm referring to is the fact that the information dialog doesn't look a thing like the "details" list view inside the add-on, as it is an (standard) info dialog with TMDbHelper functionality built in, similar (but better) to how EIM and it's variations use an (non-standard) info dialog with EIS functionality.

The "details" view you're referring to is neither of these things.

**Comment by jurialmunkey** [comment]
> 
> 
> Well im not talking about functionality, im talking about the look and feel, hence [Enhancement] GUI in the title. And yea, there is a "reason". The GUI of Openinfo looks a heck of a lot better than the standard details list of TMDBH IMO. Thats why I was asking.

@JayDee696969 - You can achieve this effect by setting Default Select Action in the addon to Play and then set Kodi's default select action to show information.

**Comment by drinfernoo** [comment]
Very good idea!
