### ISSUE TITLE
[BUG] Trakt metadata and 'in-progress' is lost when the plugin is updated

### ISSUE THREAD

**Issue by ditydot** [jurialmunkey/plugin.video.themoviedb.helper#1222]
### Describe the bug

Every plugin update I'm forced to remove and re-authorise my Trakt account information.

### Steps To Reproduce

1. Update the plug-in
2. Try to view/load anything to do with Trakt via TMDB Helper.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Works fine for me. Settings are separate from the addon.

Sounds like you have a lot of problems on your system. Without a debug log it is impossible to see the problem.

**Comment by ditydot** [comment]
I'll grab a debug log when I have time later today.

**Comment by ditydot** [comment]
[kodilog.txt](https://github.com/user-attachments/files/16078480/kodilog.txt)

Ok, there's my most recent log file.

I don't do anything overly complex so I'm not really sure how I'm ending up with a lot of problems with my setup. Aside from updates I rarely change anything.

**Comment by OfficerKD637** [comment]
Hi,

Do you have some sort of 'Clean-up' add-on installed that's cleaning the cache and database on every startup? Those can sometimes cause unexpected issues.

I'm not sure if that's what's affecting your system, but can you try switching off that addon and check if it resolves your issue?

**Comment by ditydot** [comment]
I had Open Wizard, actually. '_Had_' as I have uninstalled it to see how I go.

After doing that I deauthorised Trakt and left my widgets in place, reauthorising when prompted to do so on a reboot. My shows and movie widgets are loading in again, but I don't think it's automatically marking items as watched (I can do so manually via the context menu provided by TMDBh though).

**Comment by jurialmunkey** [comment]
Tmdbhelper does not scrobble trakt playback. That's the responsibility of the trakt addon (for library content) or the addon used (for streaming content).
