### ISSUE TITLE
[Feature] Recommendation properties on DialogVideoInfo or Home

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1224]
### Describe the feature that you'd like

Could we get these properties:- 

```
Window.Property(List_5000_IsUpdating)
Window.Property(List_5000_Visible)
Window.Property(List_Main_Visible)
```

On either the Home Window or DialogvideoInfo. I need to sync animations on my DialogVideoInfo page with when the recommendation's lists are visible but currently the properties are only available on the script-tmdbhelper-recommendations.xml window.

Thanks

### Why is this feature needed? What problem does it solve?

See above

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Do you not need these anymore?

**Comment by roidy** [comment]
Please if it's possible, I had ago myself in this pull request #1227 before realising that the properties would never get cleared :(

**Comment by jurialmunkey** [comment]
> realising that the properties would never get cleared 

Oh. I didn't think of that myself either! It should be possible to manage - I'll just have to think a bit about best way to clear it.

**Comment by roidy** [comment]
Yep, I wasn't sure if it was best to clear the properties when the dialog is initialised or when its closed or even on both to catch any edge cases where the script might exit abnormally and leave the props still set. Or am I just over thinking it.

**Comment by jurialmunkey** [comment]
> Or am I just over thinking it.

No, I don't think so. I think you're right in it needing to clear both on close and open.

Open for cleaning up the abnormal exit case. But would still need close as well for going from recs to info (open would only cover other way from info to recs).

**Comment by roidy** [comment]
Don't want to be a pain...... But any progress on this :)
