### ISSUE TITLE
[Feature] Recommendations override onBack

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1229]
### Describe the feature that you'd like

Could we get the ability to override `onback` for containers in the recommendations dialog like the old embuary info script. https://github.com/sualfred/script.embuary.info?tab=readme-ov-file#overwriting-onback-or-provide-an-additional-onclose-action

### Why is this feature needed? What problem does it solve?

Sometimes you don't want to close the recommendations dialog when pressing `onback` on a list. I would like to use `onback` to reset a list to the first item and only close the recommendations dialog when the user scroll up past the top of the group of lists.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by Hitcher** [comment]
Have you tried it because I use it on my recommendation lists:

https://github.com/Hitcher/skin.ftv/blob/master/xml/Includes_Dialog_Movie_TV_Information.xml#L344

**Comment by roidy** [comment]
Thanks, but you're not using `script-tmdbhelper-recommendations.xml`. From a list in a script managed dialog that won't work :(

**Comment by jurialmunkey** [comment]
@roidy - Can you test linked PR above? There's two different methods to set the override close action. It works similar to how you set the action of the list - either in the runscript in the pipe separated arguments, or as an onload.

**Comment by roidy** [comment]
Thanks, after testing I can confirm both methods work perfectly 👍
