### ISSUE TITLE
[BUG] Short click operation for left mouse button for recommendation.py

### ISSUE THREAD

**Issue by kittmaster** [jurialmunkey/plugin.video.themoviedb.helper#1231]
### Describe the bug

Buttons in my skin that use mouse control need left mouse button short select. Long select works, but that is not normal workflow on a windows pc. I've already worked out the logic, just needs implementation (paste) into recommendation.py. This is affecting the entire operation of my extended info within skin to select actors, related videos, collections etc. Please consider adding this.

### Steps To Reproduce

Modifications to recommendations.py

ACTION_MOUSE_LEFT_CLICK = (100,)
ACTION_CONTEXT_MENU = (117,)
ACTION_SHOW_INFO = (11,)
ACTION_SELECT = (7, )
ACTION_CLOSEWINDOW = (9, 10, 92, 216, 247, 257, 275, 61467, 61448,)
ID_VIDEOINFO = 12003

(in this order)

    def onAction(self, action):
        _action_id = action.getId()
        if _action_id in ACTION_CLOSEWINDOW:
            return self.do_close()
        if _action_id in ACTION_SHOW_INFO:
            return self.do_action()
        if _action_id in ACTION_MOUSE_LEFT_CLICK:
            return executebuiltin(self._context_action) if self._context_action else self.do_action()            
        if _action_id in ACTION_CONTEXT_MENU:
            return executebuiltin(self._context_action) if self._context_action else self.do_action()
        if _action_id in ACTION_SELECT:
            return self.do_action()

### Debug log

NA since it is not an error

### Screenshots and Additional Info

NA,

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Why should Left mouse do context menu? That doesn't make sense to me. Surely it should do the select action.

**Comment by kittmaster** [comment]
After seeing your adjustment, that now makes sense, I made the change locally and it works exactly the same way. Thanks for the adjustment.
