### ISSUE TITLE
[BUG] Description playing a movie form home screen widgets "IMDB ID is not provided "

### ISSUE THREAD

**Issue by Tarek-Depp** [jurialmunkey/plugin.video.themoviedb.helper#1236]
### Describe the bug

Hi Jurial,
When playing a movie form home screen widgets using any skin with umbrella addon and try to get subtitle, a messuage popup "IMDB ID is not provided"
**Note ** This issue happened only when playing form a movie home screen widgets.
Thank you in advance, I really don't know if it's a bug or there is setting for this issue.

### Steps To Reproduce

1-Add a TMDB Helper Widget to the home screen.
2-Playing a movie form home screen widgets.
3-Movie poster, clearlogo are not showing.
4-Trying to download the subtitle then a messuage popup "IMDB ID is not provided"

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
This is not a bug with the tmdbhelper. This is an issue with whatever player/addon you're using.

 I don't make third party player files. You will need to speak with the author if the addon and/or player file to fix it.

There's plenty of documentation in the wiki for creating players, including passing an imdb id.
