### ISSUE TITLE
Trakt - Based of Recent Watched Movie often don't work 

### ISSUE THREAD

**Issue by minhgi** [jurialmunkey/plugin.video.themoviedb.helper#1238]
### Describe the bug

When clicking on it first time, the progress displayed just spin and stop.  After about the 4th clicks, then it displays the movies. 

Kodi 21
TheMovieDataBase Helper latest

### Steps To Reproduce

1) Authorization to Trakt.
2) Navigate to Trakt
3) Click Based on Recent Watched Movies

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Debug log required.

**Comment by minhgi** [comment]
Hi dev,

There no log available. It don't produce any error.  Just sometime it works.

**Comment by jurialmunkey** [comment]
Without a log I cannot help you.

**Comment by minhgi** [comment]
Sorry I misunderstood the error log from a debug log.  Attach is a debug log.
[kodi.zip](https://github.com/user-attachments/files/16574169/kodi.zip)
