### ISSUE TITLE
[Feature Request/Help] Can we please decrease the minimum 'Random seed pool for recommendations' down to 1? 

### ISSUE THREAD

**Issue by OfficerKD637** [jurialmunkey/plugin.video.themoviedb.helper#1239]
### Describe the feature that you'd like

Hi Jurial!

Hope you've been doing well!

I love the 'Based on Recently Watched' section so much! It automatically updates the recommendations as I watch new things!

I was wondering if it'd be possible to allow the random seed pool to go below 5 (I wanted to set it to 1) to just show the recommendations based on only the most recently watched item.
I love the random seed function, but sometimes there's a great move that pops up on the list but Kodi decides to randomly refresh and I end up with a different set of recommendations. 

I could either keep refreshing the skin to get that list back or just search for the movie manually. But it would be awesome to set the random seed below 5.

Let me know what you think.

### Why is this feature needed? What problem does it solve?

To give users the option to get recommendations based on only the most recently watched item and prevent Kodi refreshes to alter the list. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Yep that's easy.

Though the way I like my setup in AF as widget is to have a "Recently Watched" widget then a "Stacked Recommendations" widget underneath. That way you can get recommendations based upon your choice rather than just random or only most recent.

**Comment by OfficerKD637** [comment]
Thank you so much! And woah that's a very cool idea!

I have recently gotten back to a simple setup and have the 'Based on Recently Watched' as the fallback path for the first widget when my 'In Progress' movies is empty.
Although I love complex and all it's cool customizability, I am really liking the simple setup so far. Loads very fast and feels snappy!

**Comment by adamosborne83** [comment]
> Yep that's easy.
> 
> Though the way I like my setup in AF as widget is to have a "Recently Watched" widget then a "Stacked Recommendations" widget underneath. That way you can get recommendations based upon your choice rather than just random or only most recent.

Been a few months since you shared a video of your setup......
