### ISSUE TITLE
[Question] Format addon response in dialog

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#124]
Again related to the EmbyCon player. I was looking into their API and I found out there is an extra parameter that could be passed that returns information about video files and their audio tracks. Here you can find an [example](https://pastebin.com/2xejftRL). 
There you can find all the needed information to show in the dialog (file size, codec used, resolution, SDR/HDR, audio languages, codecs and number of channels and more). 
So the question is, is there any way from your addon to use this information in the dialog or would it be up to the target addon to create a list with the names to show?

**Comment by jurialmunkey** [comment]
Yeah it depends on whether it exposes streamdetails info to Kodi or not. I'll have a look.

**Comment by juanma-cvega** [comment]
Thanks. Do you need any help with that or can you figure it out without an Emby server?

**Comment by jurialmunkey** [comment]
I'll have a look later when I'm back at home. It shouldn't be difficult to add stream details in general. It's just a matter of whether they are passed through or not by embycon.

**Comment by jurialmunkey** [comment]
@juanma-cvega - Can you test latest? The dialog should now show streamdetails if they're made available by the addon.

If they aren't showing then most likely the addon isn't providing them at that stage.

---
Relevant Commit: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/097df276fe12bef63dcc97f3a0a8e8395c64e4bb

**Comment by juanma-cvega** [comment]
Ok, I'll give a try tonight

**Comment by juanma-cvega** [comment]
It works! Now it's only a matter of formatting the data. Is it possible to do it multiline so more data can fit in the screen?
https://pasteboard.co/IXSGNf5j.png

**Comment by jurialmunkey** [comment]
Ah, good idea. Please try latest.
Should now display detailed select list with Thumb, Label + Label2 with details.

---
Relevant Commit: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/f4aff62c7573b919353ac8d9036c7d14201a6106

**Comment by juanma-cvega** [comment]
Great! I wasn't expecting it was possible to get to show information in the dialog like this. This is how it looks like. https://pasteboard.co/IXTPsSH.png
But I think some information is redundant there. For instance the year (which I think is wrong as it always shows 1601), the season, the episode and the thumbnail shouldn't be needed as to get to the dialog you have to navigate to the episode anyway. In my opinion, the dialog should show more technical information to let you choose the right link from the ones available. So, I would say (in my order or preference) resolution, file size (in GB/MB), video codec, SDR/HDR (maybe the type of HDR if available?) and audio tracks (language, channels and codec). 
Another thing I'd say whoever is watching the video is tech savvy enough to not need a tag in front of the values (like Resolution: 1080). That would save quite a lot of space to show more relevant data.

**Comment by jurialmunkey** [comment]
The detailed select dialog always shows a thumb. If I don't add a thumb then it will just be a blank space.

Kodi doesn't provide HDR info.

Can you try latest. Should now get if available:
`Resolution | Video Codec | Audio Codec (1st Stream) | Audio Channels (1st Stream) | Languages (All Streams) | Duration | Filesize`

---
Relevant Commit: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/b7c7766d89f2eec7de55182604059e0d66f6502c

**Comment by juanma-cvega** [comment]
I tested and the only part missing is the file size, which I think would be great to have to distinguish between same resolution files. Here is the [screenshot](https://pasteboard.co/IXXTxmg.png).

> The detailed select dialog always shows a thumb

Ok, I didn't know that. I thought the dialog was like the ones from addons like Venom that gives you just a list of strings with details about the stream. 

> Kodi doesn't provide HDR info.

Isn't it possible to fetch it from the streamdetails? I saw the information in the response from EmbyCon but maybe it's stripped out from the response?
One last request, would it be possible to include whether there are subtitles in the stream as well? Maybe with the language. I was thinking of something like:
`| LAN: ENG, FR | SUB: FR`

**Comment by jurialmunkey** [comment]
> Isn't it possible to fetch it from the streamdetails? I saw the information in the response from EmbyCon but maybe it's stripped out from the response?

It's not supported in Kodi afaik. Anything that shows HDR flags in Kodi is based upon filename tags and not the actual file.

This is the data provided by streamdetails - as you can see there isn't a key related to HDR:
```xml
{u'video': [{
    u'language': u'',
    u'stereomode': u'',
    u'width': 640,
    u'codec': u'h264',
    u'aspect': 0.0,
    u'duration': 2731,
    u'height': 360}],
u'audio': [{
    u'channels': 2,
    u'codec': u'aac',
    u'language': u'en'}],
u'subtitle': []}
```

  
>
>
> I tested and the only part missing is the file size, which I think would be great to have to distinguish between same resolution files.

If you don't have size, then it's not being passed through - so not much I can do about that. It definitely works as shown with this dialog of local files that aren't scanned to the library. I assume it doesn't work for many addons because they need to resolve the url first before Kodi can retrieve the file size.

![Honeyview_screenshot607](https://user-images.githubusercontent.com/4618719/76141780-98630b00-60bb-11ea-8248-42303346086d.jpg)

**Comment by juanma-cvega** [comment]
> If you don't have size, then it's not being passed through - so not much I can do about that. It definitely works as shown with this dialog of local files that aren't scanned to the library. I assume it doesn't work for many addons because they need to resolve the url first before Kodi can retrieve the file size.

Then it must be the EmbyCon addon not doing it because I can see in the results from the request all the information about the file, size included. One last request, could the results be sorted by resolution in descending order?

**Comment by jurialmunkey** [comment]
> Then it must be the EmbyCon addon not doing it because I can see in the results from the request all the information about the file, size included.

I'm not sure. It's also possible that size is only provided in Kodi JSON-RPC for local files.

>
> One last request, could the results be sorted by resolution in descending order?

It's possible but it's a bit of a pain. Plus I think in a lot of scenarios users would prefer the default sorting. Of course I could make it optional but I can't really see a way to make an option that isn't just an ad hoc hard-coded approach. I would really prefer something that is extensible but it is difficult because the streamdetails are in a nested data structure rather than a flat one, so not all keys are available in the same way.

**Comment by juanma-cvega** [comment]
> It's also possible that size is only provided in Kodi JSON-RPC for local files

Other addons like Venom give you the file size in format in GB format so I don't think only the Kodi library can do it. And it's quite informative, you can select the best quality available by just looking at it. And there is no thumbnail be shown, that's why I asked you before about it. Here is a snapshot https://pasteboard.co/IXZlH2YM.png
In any case, if that's all information available that can be shown, you can close the issue if you think there is nothing more to add.

**Comment by jurialmunkey** [comment]
Yeah but I don't scrape content from the web. That addon would be scraping details about file size from the Webpages that it gets its links. Its not resolving every file and checking the size - it is just whatever is reported on the web page. 

I can only show whatever information that the addon linked by the player provides to kodi and is available via json rpc. If it's not available in json rpc get directory method then I can't use it. I show the size property if it is available. 

Also the example I showed specifically wasn't from the kodi library - it was just a random folder on my hard drive of video captures. Kodi doesn't even have it listed as a source let alone scanned to the library
