### ISSUE TITLE
Option to change the sort order of ‘Your Next Episodes’

### ISSUE THREAD

**Issue by OfficerKD637** [jurialmunkey/plugin.video.themoviedb.helper#1242]
### Describe the feature that you'd like

Hi Jurial!

Hope you’ve been doing well!

I was hoping if you could add an option to change the sort order of ‘Your Next Episodes’ (provided by Trakt) from alphabetical to ‘Recently Watched’.

The other Trakt lists have a ‘Browse sorted lists’ option in the context menu, but that’s missing from ‘Your Next Episodes’. Maybe there’s a parameter in the widget sort options (I tried dateadded, lastplayed, lastupdated, etc.) but I couldn’t find the right one.

Let me know what you think.

### Why is this feature needed? What problem does it solve?

Having your next episodes sorted by most recently watched might be more intuitive than alphabetical 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
This list is never sorted alphabetically..
The list is sorted by default by recently watched.

You can change the sort mode in TMDHelper Settings > Widgets > Next episodes sort method

Airdate = sorted by date recent episode aired
RecentlyWatched = sorted in order of your Trakt watched history
Todays = RecentlyWatched but episodes which aired today are put to the front
LastWeek = RecentlyWatched but episodes which aired in the last week are put to the front (in airdate order).

**Comment by OfficerKD637** [comment]
My apologies. I don't know how but my sort method was set to 'airdate' (which coincidentally made it appear as alphabetically lol).

I think recently watched doesn't have the premiere banners, so Todays or Last Week should be fine.

Thank you!

**Comment by jurialmunkey** [comment]
Yep recent won't have banners because it only uses the basic sync - so faster to pull and calculate (not by much in real use due to caching but from fresh with completely cleared cache it is noticable).

Today is what I think the default behaviour should be because then you notice season premieres for a show you might not have watched for a year (because on break) - but if you don't watch it then it goes back to its place in the list the next day so that it isn't in the way of shows you are currently watching.

**Comment by OfficerKD637** [comment]
Yeah Today is perfect! And like you said, the caching takes care of the loading speed so I'm very happy with this option.

Thank you!

**Comment by Ade-AV** [comment]
For Today is there any way of stopping shows airing today going to the front if I have just watched a previous episode?

Or how about tweaking RecentlyWatched so the returning show premier goes the front for a number of days

Thanks
