### ISSUE TITLE
Playlist sort option

### ISSUE THREAD

**Issue by tielis** [jurialmunkey/plugin.video.themoviedb.helper#1243]
### Describe the feature that you'd like

Is it possible to add an option to select how the playlists should be sorted?

Quite often I sort my TV Shows by Rating ( not "My rating"), but for some reason this option is not available with TV Shows playlists, only on Kodi normal library.

I used to get around this by forking your add-on and add this option when the playlists were created, but this was a while ago.

### Why is this feature needed? What problem does it solve?

Kodi doesn't give us the option to sort TV Shows by Ratings when we use playlists. So adding this option on tmdb.helper would kind of fix this while we wait Kodi main repository fix it there.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
What do you mean by "playlist" exactly?

If you just mean something like a Trakt Collection list or Watchlist etc. then these can already be sorted via the context menu.

Open the plugin, open context menu on list you want to sort and choose "Browse sorted list"

**Comment by tielis** [comment]
Sorry. Yes I'm referring to the trakt playlists.

This is the thing... Kodi doesn't give us the option to sort TV Shows by Rating ( only movies).

It is kind of a bug. Around 2020, I did PR the fix on the Kodi repository and they accepted. This was before the Matrix. But for some reason the fix has never come up on the official builds.

It's literally one line code. But no one there seems to care.

It seems I'm the only person in the world who likes to sort things by Rating 🤣

Anyway... I gave up on waiting, so what I've been doing is changing your tmdb instead. If the playlist is sorted by Rating, all of sudden the option shows up on Kodi.

**Comment by jurialmunkey** [comment]
You can already sort by rating if you follow the instructions I listed above. 

Highlight "Watchlist" folder and open context menu.
Choose "Browse Sorted List" and then "Sort by: Rating" and you can view your watchlist sorted by Trakt rating.
