### ISSUE TITLE
Movie Tracking

### ISSUE THREAD

**Issue by soundsofmath** [jurialmunkey/plugin.video.themoviedb.helper#1245]
### Describe the feature that you'd like

Non library movie tracking

### Why is this feature needed? What problem does it solve?

I don't needed it I would like to have the option I'm a logical thinker only. and it solves the I'm lazy or refuse to evolve problem where people don't want to live structured lives and schedule movie watching or anything else for that matter instead of needing a feature to to track your progress at falling asleep during a movie. All sarcasm. my work around is to use the original addon instead of tmdb at least for non library movie progress if said addon has feature it doesn't carry over to other devices like trakt would but its a Band-Aid humanity has been putting Band-Aid on everything for centuries. but yeah

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Addons which correctly use setresolvedurl and have players correctly configured pass through resume status.

I cannot make it work if the end addon does things in a non-standard way.
