### ISSUE TITLE
[Question] Cast/Crew Info in OSD

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1248]
### Describe the bug

I am trying to get the cast/crew information within the OSD window. I get a list of cast/crew and their names, but not other information, biography, date of birth, place of birth... I use it:
`$INFO[Container(50).ListItem.Property(Born)]`
`$INFO[Container(50).ListItem.Property(Biography)]`
...
This works in dialog info but not in osd. Where am I wrong? Can you help? Thanks in advance.

### Steps To Reproduce

-

### Debug log

-

### Screenshots and Additional Info

-

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by Hitcher** [comment]
List ID 50 is a Kodi list and only have the cast and crew labels.

**Comment by matke-84** [comment]
@Hitcher 
It's not that. I changed id. Same thing again. There is obviously something else that has to be done.

**Comment by jurialmunkey** [comment]
These details are not available from `info=cast`

These details are only available for the detailed item
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Detailed-Item

If you want to get these for cast members then you must use a hidden list to retrieve the detailed item for the currently focused cast member as you cannot rely on the service monitor in the player windows.

i.e. `plugin://plugin.video.themoviedb.helper?info=details&amp;tmdb_type=person&amp;tmdb_id=$INFO[Container(ID).ListItem.Property(tmdb_id)]`

**Comment by jurialmunkey** [comment]
Alternatively, you can add the `detailed=true` flag to the cast list.

**Comment by jurialmunkey** [comment]
Note also that if the detailed item already exists in the cache then the extra details get added to the cast items when the list loads  -- which is why you probably have seen it on some items. 

However, these don't get looked up for the list itself because cast/crew could be 100s of people and doing that many lookups in one go will quickly get you rate limited by TMDb.

**Comment by matke-84** [comment]
@jurialmunkey 
I knew there was something. :-) I will see if I should insert that information at all. Maybe just a picture, name and role is enough. This with a hidden container is always a bit slower. Thank you very much for your reply. ;-)
