### ISSUE TITLE
Can not play movie directly from library

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/plugin.video.themoviedb.helper#125]
Hi!

I have a new issue since yesterday... 
Now, when I select a movie that I already have in my library, I have a context menu showing up to ask me from where I want to play. If I select a player (as Netflix or my personal one), there is no issue. But if I chose "Play with Kodi", nothing happen.  I also tried to long press the same movie to chose the "play with" option and I got thesame issue.

Here is my Log file and 2 screen shot hoping that it will help to understand my issue.

Regards,
alKODIque

![Kodi_20200305_123753](https://user-images.githubusercontent.com/49578130/76009500-4a91ab80-5edf-11ea-97e8-2c2752ad7f24.png)
 
![Kodi_20200305_123814](https://user-images.githubusercontent.com/49578130/76009524-554c4080-5edf-11ea-9cf8-f7ce62c29a3c.png)

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/4294318/kodi.log)

**Comment by jurialmunkey** [comment]
Why do you have colour tags in the filename of a strm file?

`/storage/emulated/0/Movies/AD ASTRA [COLOR violet]Uptobox[COLOR] [COLOR lightseagreen](2019)[COLOR]/AD ASTRA [COLOR violet]Uptobox[COLOR] [COLOR lightseagreen](2019)[COLOR].strm`

**Comment by alKODIque** [comment]
The only way I can play the movie I have on my premium uptobox account, is to use an addon because of the API, I guess.. the  addon  I use make different colour for year of the movie and the name « uptobox »... Beacause i use nvidia shield, i don’t know how to bulk rename my strm files.

**Comment by alKODIque** [comment]
I will come back to you for letting you know if it’s working or not

**Comment by alKODIque** [comment]
Ok now it’s working, but only if I use the context menu. If I clic directly on the movie, nothing happen.

I,m fine with it if nobody else having this trouble. Not a big deal for me

**Comment by alKODIque** [comment]
Ok...
I tried to change my default Action when selecting a medi from « show information » to « chose action » in my kodi setting and now, it’s working like before...

I can send you my log if you need it. Just let me know :)
