### ISSUE TITLE
[Feature] clear logo fallback language 

### ISSUE THREAD

**Issue by Peter3344** [jurialmunkey/plugin.video.themoviedb.helper#1250]
### Describe the feature that you'd like

Is it possible to add a fallback language to clear logo 

### Why is this feature needed? What problem does it solve?

I use English as main language but the clear logo available in my original language but not available in English so if it possible to add a fallback 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
There is an option to fall back to English already in settings. There is no point falling back to other languages as English is overwhelmingly the most common for clearlogos.

Alternatively you can use the manage artwork context option to manually select.
