### ISSUE TITLE
[BUG] Get additional details from Kodi library is broken

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1254]
### Describe the bug

When the option Get additional details from Kodi library is turned on then incorrect episode details are pulled.

![broken](https://github.com/user-attachments/assets/7395154d-7d11-47a2-9c0b-d252c7d59e1f)

This happen on multiple TV Shows but only on a few episodes in each show.

### Steps To Reproduce

1. Turn on Get additional details from Kodi library.
2. Browse the plugin

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I think I've finally figured out the cause for this one.
