### ISSUE TITLE
TmdbHelper Kodi library integration bug

### ISSUE THREAD

**Issue by alvaro89vl** [jurialmunkey/plugin.video.themoviedb.helper#1256]
### Describe the bug

I am running Tmdbh 5.2.31 on Kodi Omega with AH2R skin.
If I delete a Series from the Kodi library and then I try to add that same Series back to the library with Tmdbh, it is no possible and the Series doesn't appear in my library anymore.  Tmdbh scans and finds the series correctly, but fails to add it to the library. 
However, if I attempt do the same with a new show that has never been kep in the library, the process is completed correctly. Therefore, the helper only fails with series that have been previously deleted from the library but not with new ones. 
Plus, when it takes places, I'm not provided with any log error message. 

### Steps To Reproduce

1. Go to The MovieDb Helper
2. Click on Search
3. Click on TV shows
4. Seek some TV show title 
5. Long press on the cover
6. Scroll to add to library and click on it
7. Go to Kodi library
8. Scroll to that TV show we have previously add 
9. Long press on the cover 
10. Click on Manage
11. Click on Remove from library
12. Click on Yes
13. Go to The MovieDb Helper
14. Click on Search
15. Click on TV shows
16. Seek that same TV show title again
17. Long press on the cover
18. Scroll to add to library and click on it
19. The TV show doesn't appear in the Kodi library anymore.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by Evo589** [comment]
I also have this issue. I think it started happening when I switched to Kodi Omega.  I tried deleting the cache files in the pickle folder but it still didn't add the missing episodes.

**Comment by jurialmunkey** [comment]
I don't know what AH2R is... but the skin used should not matter.

If you remove a show from the library manually, you must clean the library afterwards to remove any entries. 
`Kodi Settings > Media > Library > Clean library (videos)`

You must also rebuild TMDbHelper's library cache after cleaning 
`TMDbHelper Settings > Other > Refresh cached kodi library details`

You must then close Kodi and delete the pickle files for tvshows
`kodi/userdata/addon_data/plugin.video.themoviedb.helper/pickle/`

Then restart Kodi and update your library.


All actions in the library updater are logged in the files:
`kodi/userdata/addon_data/plugin.video.themoviedb.helper/log_library/`

Find the date and time for the last update and you can read exactly what items were skipped/added etc. and for what reason.


Finally if you have issues with auto updates you can do a forced update from settings:
`TMDbHelper Settings > Library > Update library now > Forced update`

**Comment by Evo589** [comment]
Thank you for your response. However, the problem still exists after following all the steps you listed. I even uninstalled Kodi and did a clean reinstall. 

Looking at the library updater log, It looks like its saying all the episodes are "found in library" but the path is incorrect. It's showing the path to a few of the same shows for all the shows. 

[2024-10-06-183355.json](https://github.com/user-attachments/files/17281687/2024-10-06-183355.json)

**Comment by alvaro89vl** [comment]
Thanks, jurialmunkey, for your answer. 
I've followed all your steps, except for deleting the pickle files because Android 11 doesn't allow me to access system folders.
I keep having the same issue, and it only happens with the TV shows library, not with the films library.
And AH2R is indeed a skin, specifically a modified version of Artic Horizon 2. 

Thanks for your help!

**Comment by Evo589** [comment]
> Thanks, jurialmunkey, for your answer. I've followed all your steps, except for deleting the pickle files because Android 11 doesn't allow me to access system folders. I keep having the same issue, and it only happens with the TV shows library, not with the films library. And AH2R is indeed a skin, specifically a modified version of Artic Horizon 2.
> 
> Thanks for your help!

Did you check the log library file for your forced library update? Mine is showing the wrong path for all the episodes. Curious to know if you have the same issue.

**Comment by alvaro89vl** [comment]
This is what I get when I run the Kodi log viewer ...
Like you, the path of the TV shows is incorrect because I'm saving the library in another folder. 

![PXL_20241015_161840622](https://github.com/user-attachments/assets/7a615e2f-8e4e-4be2-8bb1-2e860964a773)

**Comment by Evo589** [comment]
> This is what I get when I run the Kodi log viewer ... Like you, the path of the TV shows is incorrect because I'm saving the library in another folder.
> 
> ![PXL_20241015_161840622](https://private-user-images.githubusercontent.com/183132952/376707452-7a615e2f-8e4e-4be2-8bb1-2e860964a773.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTI0MTQsIm5iZiI6MTcyOTAxMjExNCwicGF0aCI6Ii8xODMxMzI5NTIvMzc2NzA3NDUyLTdhNjE1ZTJmLThlNGUtNGJlMi04YmIxLTJlODYwOTY0YTc3My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxNzA4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjNiNDBhZGIwZjE3NTkzMjBiNzFiYmRmYjM0Y2I3ZDJjZjhkMTNhZDk3NzgzYjQyZDY2NTJhOWNlZjExNWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tA78CCMtVK6eOJgMilMH6p8v5yZ3pMUQhTAtRZ_oR3g)

I don't think that's the TMDB Helper library updater log found here:
`kodi/userdata/addon_data/plugin.video.themoviedb.helper/log_library/`

If you can't access the data folder try this: https://forum.kodi.tv/showthread.php?tid=376035&pid=3185214#pid3185214

**Comment by jurialmunkey** [comment]
> Thanks, jurialmunkey, for your answer. I've followed all your steps, except for deleting the pickle files because Android 11 doesn't allow me to access system folders. I keep having the same issue, and it only happens with the TV shows library, not with the films library. And AH2R is indeed a skin, specifically a modified version of Artic Horizon 2.
> 
> Thanks for your help!

You need to delete the pickle files or force the update from the settings.

Never heard of AH2R and can't find it on google. I do know of a AZ2R though, which is a reboot of zephyr 2. Or there is AZR which is a reboot of AZ1 available on the official repo. But I can't find a AH2R anywhere... Not that it matters, just don't know what that skin is.

**Comment by alvaro89vl** [comment]
You are right, jurialmunkey! 
Thanks to Evo's guidance, I was able to delete the pickle files, and my TV show library is working again. The problem was that I couldn't access the pickle folder due to Android restrictions. 
Thanks to both of you!!

**Comment by alvaro89vl** [comment]
> > This is what I get when I run the Kodi log viewer ... Like you, the path of the TV shows is incorrect because I'm saving the library in another folder.
> > ![PXL_20241015_161840622](https://private-user-images.githubusercontent.com/183132952/376707452-7a615e2f-8e4e-4be2-8bb1-2e860964a773.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTI0MTQsIm5iZiI6MTcyOTAxMjExNCwicGF0aCI6Ii8xODMxMzI5NTIvMzc2NzA3NDUyLTdhNjE1ZTJmLThlNGUtNGJlMi04YmIxLTJlODYwOTY0YTc3My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxNzA4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjNiNDBhZGIwZjE3NTkzMjBiNzFiYmRmYjM0Y2I3ZDJjZjhkMTNhZDk3NzgzYjQyZDY2NTJhOWNlZjExNWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tA78CCMtVK6eOJgMilMH6p8v5yZ3pMUQhTAtRZ_oR3g)
> 
> I don't think that's the TMDB Helper library updater log found here: `kodi/userdata/addon_data/plugin.video.themoviedb.helper/log_library/`
> 
> If you can't access the data folder try this: https://forum.kodi.tv/showthread.php?tid=376035&pid=3185214#pid3185214

Here you go.
In my case, the path for the library episodes is correct.
![PXL_20241015_223338414](https://github.com/user-attachments/assets/bce01cf7-4ed8-48a9-b6af-8d2a7438e000)

**Comment by Evo589** [comment]
> You are right, jurialmunkey! Thanks to Evo's guidance, I was able to delete the pickle files, and my TV show library is working again. The problem was that I couldn't access the pickle folder due to Android restrictions. Thanks to both of you!!

Glad you solved your issue. Looks like my issue is different. 

I've deleted my pickle files many times but it still wouldn't add the missing strm files back.

@jurialmunkey Would you have any idea why the library updater would flag the show/episode as "found in library" but the path isn't for the correct show? 

[2024-10-06-183355.json](https://github.com/user-attachments/files/17387618/2024-10-06-183355.json)

**Comment by jurialmunkey** [comment]
> Would you have any idea why the library updater would flag the show/episode as "found in library" but the path isn't for the correct show?

Could be to do with the scraper being used. If the ID numbers in your library do not match with TMDb you'll get weird results.

It could also be that you didn't refresh the TMDbHelper's KodiDB cache before updating.

Other possibility is a that recently resolved bug with the tvshow cache for the plugin paths is having a weird interaction with the library updater (I believed it to be limited to plugin paths but possible it was also impacting here). 

This was resolved about 5 days ago and is fixed in v5.2.33 from my repo -- check that you're using that version, and, if not, update to the version from my repo to see if it makes a difference (repeat the steps to clear/clean/refresh after updating to 5.2.33).

**Comment by Evo589** [comment]
> > Would you have any idea why the library updater would flag the show/episode as "found in library" but the path isn't for the correct show?
> 
> Could be to do with the scraper being used. If the ID numbers in your library do not match with TMDb you'll get weird results.
> 
> It could also be that you didn't refresh the TMDbHelper's KodiDB cache before updating.
> 
> Other possibility is a that recently resolved bug with the tvshow cache for the plugin paths is having a weird interaction with the library updater (I believed it to be limited to plugin paths but possible it was also impacting here).
> 
> This was resolved about 5 days ago and is fixed in v5.2.33 from my repo -- check that you're using that version, and, if not, update to the version from my repo to see if it makes a difference (repeat the steps to clear/clean/refresh after updating to 5.2.33).

Looks like the update fixed it. I repeated the steps again after updating and it was able to fine the correct path and add back the missing shows. Thank you for you help!
