### ISSUE TITLE
[Question] mdblist & omdb rating priorities

### ISSUE THREAD

**Issue by rizreflects** [jurialmunkey/plugin.video.themoviedb.helper#1260]
### Describe the feature that you'd like

Hi Jurial, I hope you're doing well. I have a quick question for you. If I use both my mdblist & omdb keys in tmdbhelper, which of the 2 would be prioritised in this instance? I think it would be ideal if mdblist took priority over omdb as the ratings are much more regularly updated.

I ask this question as I've ran into a problem. When both mdb and omdb are enabled in tmdbhelper settings, it seems omdb is being priotised, which is leading to outdated ratings. I would ideally like to keep omdb enabled, just incase I go over my api limit for mdb.

Could you please provide some clarity on this if possible, and if omdb has priority over mdb, could you please reverse this so it's the other way around?

Thank you very much for your time.

### Why is this feature needed? What problem does it solve?

. 

### Steps to reproduce.

. 

### Screenshots and Additional Info

. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by rizreflects** [comment]
The updates working great. Thanks again.

**Comment by jurialmunkey** [comment]
Yeah I honestly completely forgot ratings from omdb had priority until you pointed it out. 

I know why I did it that way originally (so that mdblist wouldnt overwrite trakt/tmdb ratings with its own), but did intend to switch it eventually (with tmdb/trakt filtered out) but just forgot - so the reminder was good.
