### ISSUE TITLE
[Feature/Help] Please add ListItem.Property(TotalSeasons) and (TotalEpisodes)

### ISSUE THREAD

**Issue by OfficerKD637** [jurialmunkey/plugin.video.themoviedb.helper#1263]
### Describe the feature that you'd like

Hey Jurial!

Hope you've been doing well!

I am so sorry I missed the launch of AF2. Got a bit busy with life/work haha.
The skin looks phenomenal!! 

I've been trying to migrate all my cool fonts and customizations from Fuse 1 to 2 and it's been such a seamless experience!

I was a bit inspired by the new 'Last Aired' tag and while I was editing the info line, I noticed that ListItem.Property(TotalSeasons) doesn't seem to work with Container(99950)
I'm currently using a makeshift solution of ListItem.Season but it breaks when the focused item is a season/episode (only works when the focused item is a TV show)

I checked the Wiki and it was missing. Would it please be possible to add this?

### Why is this feature needed? What problem does it solve?

I noticed you added a 'Last Aired' condition in the info line for Returning shows without a Next_Aired date. This is awesome!

I found a few fringe cases (Stranger Things, Black Mirror, etc.) that have a new season or episode title but don't have a next_aired date. 
So I decided I could try 'Returning TBC' or 'Anticipated' for such shows.

Currently, this is what I'm using:
```
<!-- Anticipated/Returning TBC -->
		<value condition="[String.IsEqual(Container(99950).ListItem.Property(Status),Returning Series) | String.IsEqual(Container(99950).ListItem.Status,Returning Series)] + String.IsEmpty(Container(99950).ListItem.Property(Next_Aired)) + Integer.IsLess(Container(99950).ListItem.Property(Last_Aired.Season),Container(99950).ListItem.Season)">$LOCALIZE[31543]</value>
```
This only works when the focused item is a TV show or the unreleased season (Season 5 for Stranger Things and 7 for Black Mirror respectively).

It'd be great if I could replace ListItem.Season with ListItem.Property(TotalSeasons) for more consistency.

Let me know what you think.

Thank you!

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by OfficerKD637** [comment]
Yo Jurial!

Hope you've been doing well!

The new custom baseitems per skin is phenomenal! I was able to add these two infolabels (totalseasons and totalepisodes) very easily!

Now I know that I had the wrong approach to begin with haha. Even with totalseasons, I can't get the 'Anticipated' status to work when dbtype is season/episode.

So this is more of an general question but do you know a way to retrieve the total number of seasons of a TV show when the focused listitem is a season/episode? 

This is what I currently have:
```
<!-- Anticipated/Returning TBC -->
		<value condition="[String.IsEqual(Container(99950).ListItem.Property(Status),Returning Series) | String.IsEqual(Container(99950).ListItem.Status,Returning Series)] + String.IsEmpty(Container(99950).ListItem.Property(Next_Aired)) + Integer.IsLess(Container(99950).ListItem.Property(Last_Aired.Season),Container(99950).ListItem.Season)">$LOCALIZE[31543]</value>
```

And this works only when the focused listitem is a tvshow (or the latest unreleased season, eg. Season 5 of Stranger Things)

Thank you!

**Comment by jurialmunkey** [comment]
> So this is more of an general question but do you know a way to retrieve the total number of seasons of a TV show when the focused listitem is a season/episode?

No, there isn't any way to retrieve these natively.

Of course it could be done in addon code, but it starts getting convoluted to merge properties from tvshows into episodes etc. and would be slower due to the separate lookup.

**Comment by OfficerKD637** [comment]
Thank you for letting me know!
Now it's time to learn Python I suppose.... how hard can it be?😂
