### ISSUE TITLE
[BUG] Discover not working for release_date

### ISSUE THREAD

**Issue by shahaf1122** [jurialmunkey/plugin.video.themoviedb.helper#1264]
### Describe the bug

I have notice that when I try to discover with release_date.desc
it does not show any movie. but with release_date.asc it shows movies.
I looked into the tmdb api and in the api, the sort with release_date.desc works.

### Steps To Reproduce

1. go to discover
2. add role with with_genres
3. add romance
4. short by release_date.desc

### Screenshots and Additional Info

the screenshots from the discover in af2 but it the same from inside the addon itself.

screenshot of release_date.desc
![relese_desc](https://github.com/user-attachments/assets/ecc3671f-ce04-437f-9b5f-e0c567841c82)

screenshot of release_date.asc
![relese_asc](https://github.com/user-attachments/assets/68b9e72f-d281-4021-acb2-d0718fc15e17)

screenshot of tmdb api http
![http req](https://github.com/user-attachments/assets/d5611521-6c0e-4260-92d3-2f72c4923aa1)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Turn off setting to hide unaired/unpremiered.
