### ISSUE TITLE
[BUG] Some TMDb lists are a little weird

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1265]
### Describe the bug

Trending today list for Movies and TV Shows, Popular list for TV Shows gives completely different (weird) results than the tmdb site.

### Steps To Reproduce

-

### Debug log

-

### Screenshots and Additional Info

-

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Region settings.

**Comment by matke-84** [comment]
The region is set correctly as you can see. Example TMDb list - TV Shows - Popular.

![11111111](https://github.com/user-attachments/assets/c41d1d42-c16d-41e1-bc05-3fdf7de6bb81)
![44444](https://github.com/user-attachments/assets/063dc9e7-5618-4121-bf77-818383f00249)
![22222222](https://github.com/user-attachments/assets/815295c6-c1de-4238-87bc-496c2920d8c4)
![3333333333](https://github.com/user-attachments/assets/7f1a0dfe-1470-43e9-980b-5539e4c7b9e8)

**Comment by jurialmunkey** [comment]
Not sure what you want me to do about this? It is literally what the API returns

This request
https://api.themoviedb.org/3/tv/popular?language=en-US&page=1

Produces this result
https://gist.github.com/jurialmunkey/5d5e27d8d61dda05b85dbc2b8db1846e#file-popular-json

See also:
https://www.themoviedb.org/talk/64d88edc37109700ac41768d

**Comment by jurialmunkey** [comment]
If you want more control, use discover.

**Comment by jurialmunkey** [comment]
e.g. this discover path will get you closer to what you're expecting by filtering out shows which aren't English language

```
plugin://plugin.video.themoviedb.helper/?info=discover&tmdb_type=tv&with_id=True&sort_by=popularity.desc&with_original_language=en
```

And this will help further refine it by filtering out some less desirable genres like Talk, News, Soap, and Reality
```
plugin://plugin.video.themoviedb.helper/?info=discover&tmdb_type=tv&with_id=True&sort_by=popularity.desc&without_genres=10762+%2F+10763+%2F+10764+%2F+10766+%2F+10767&with_original_language=en
```

**Comment by matke-84** [comment]
Thanks for the explanation and help.
