### ISSUE TITLE
[BUG] Landscape artwork from fanart.tv doesn't show if there are spaces in the image file name

### ISSUE THREAD

**Issue by ambulancePilot** [jurialmunkey/plugin.video.themoviedb.helper#1266]
### Describe the bug

Basically the title... I've noticed it for a while but ignored it thinking it was something with my setup. But then I installed everything again on a fresh device and the same issue ocurred. I even changed DNS servers thinking it was something to do with my personal DNS but no bueno.

### Steps To Reproduce

For example, the show How I Met Your Mother. The landscape artwork it is choosing as preferred has spaces in the URL. The file name is H_75760 (3).jpg so it doesn't work. The second image has no spaces and works if selected. The third image once again has a space in it so it doesn't work.

No one else is reporting this and I've noticed it for over a year. Surely this has to be something with my network? It was reproducible on two different devices but I was using the same network.

How can I begin to troubleshoot this? I have already tried deleting FanartTV.db as well as Textures13.db to no avail.

Thanks for all you do! Here's hoping you have some ideas what I could be doing wrong. If not, it's all good. Don't spend too much time thinking about. It's easy enough to change artwork manually when I see this crop up.

### Debug log

https://paste.kodi.tv/fexawugibu.kodi

You can see the issue clearly in the last few lines of the log.

### Screenshots and Additional Info

Thanks so much!

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
These are valid paths. I picked a random one from your log and I can open it fine in a web browser e.g.
`https://assets.fanart.tv/fanart/tv/83462/tvthumb/C_83462 (6).jpg`

I'm guessing Kodi is being unnecessarily strict about percent encoding URLs because if I swap the space for `%20` then it will read
`https://assets.fanart.tv/fanart/tv/83462/tvthumb/C_83462%20(6).jpg`

**Comment by jurialmunkey** [comment]
Seems like the data returned from FanartTV has unencoded spaces and Kodi doesn't like that. I don't think it's anything I'm doing wrong particularly, but also easy enough for me to workaround.

**Comment by jurialmunkey** [comment]
^^^ This should fix it. You'll most likely need to either refresh artwork / reselect for individual items; or go the nuclear route and delete your caches.

**Comment by ambulancePilot** [comment]
Thank you so much for addressing this! I ran into this issue with another add-on, the unencoded spaces being returned, but it was from a different API and it caused streams to fail to resolve. Somehow I think Kodi stopped accepting URLs with spaces in Nexus because prior to that I can't ever remember it being an issue.

Thanks again! I have a feeling it will work without having to delete any databases, but I'll edit and report back.

**Comment by jurialmunkey** [comment]
I'm getting a weird circular import bug in the requests utils module. Since the module is external, I'll change the function to do the replace manually instead (importing the utils just to do this was a bit overkill anyway).

**Comment by ambulancePilot** [comment]
Ah, okay. I was scratching my head trying to figure out if anything else had changed in my setup between yesterday and today. I was just in the process of preparing a logfile for you. I was getting an error on boot up from tmdb helper.

As usual you are ahead of it!

Deleting itembuilder.db cleared up the previous issue and all images are loading as expected. And I didn't have to delete over 4GB of cached artwork!
