### ISSUE TITLE
[BUG] TMDBH Service Monitor crash

### ISSUE THREAD

**Issue by DenDyGH** [jurialmunkey/plugin.video.themoviedb.helper#1267]
### Describe the bug

Changing views on empty/unfocused item or however call it causes crash.
Sometimes it happens on the first try, sometimes it happens after a few tries, but still it happens so often and it's easy to reproduce.
I tested the whole thing on a fresh installation of Kodi, on your skin `Arctic Fuse 2`, but it happens also on `Fuse` and `Horizon 2`.
Everything on default settings.
Changing the view on a non-empty item does not cause a crash.
Also after commenting `<include>Defs_TMDbHelper_Loader</include>` in `MyVideoNav.xml` everything is fine.
That's why suspicion fell on TMDBH Monitor.
Is there anything can be done about that? Sadly log file is empty.

Kodi 21.1
Skin Variables - 2.1.18
TMDB Helper - 5.2.33
Arctic Fuse 2 - 2.0.19
Windows 11 - but crash appears on other platforms too

### Steps To Reproduce

1. Go to `Library > Movies > Titles` or `TMDBH > Movies > Popular`
2. Keep focus on `back` item/button
3. Change the view
4. After change press right arrow to focus item.
5. If it doesn't crash, press left arrow to focus `back` item again.
6. Change the view
7. Press right arrow
8. Repeat until it crashes (won't take long)

Here is a short video, lucky enough to crash on the first try ^.^
https://streamable.com/fjvr9h

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
It needs to be fixed in Kodi.

**Comment by jurialmunkey** [comment]
This should no longer be an issue in latest versions of AF2+TMDbHelper as I've changed AF2 to use the service monitor with a "safer" window property setter approach.

It will, however, continue to be an issue for other skins using the container method because the underlying issue with that method is due to a bug in Kodi.
