### ISSUE TITLE
[Feature] Option to add Spotlight to desired categories and not all

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/plugin.video.themoviedb.helper#1269]
### Describe the feature that you'd like

The spotlight currently gets globally applied across all the categories while using the 1101 > Hub under customise hubs.

### Why is this feature needed? What problem does it solve?

I would like to maintain separate spotlight for diff categories like most watched movies of the week for the Movie category, most watched shows of the week for TV Shows category etc, and even no spotlight for a category.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
What does this have to do with tmdbhelper?

**Comment by onlytanmoy** [comment]
> What does this have to do with tmdbhelper?

Haha, my bad mate, raised in the wrong space.
