### ISSUE TITLE
Add support for IMDB TOP250

### ISSUE THREAD

**Issue by DimitarCC** [jurialmunkey/plugin.video.themoviedb.helper#127]
Add a support for IMDB top250 ranking so to be possible to replace the same functionality in old SkinHelper

**Comment by jurialmunkey** [comment]
IMDB doesn't have an API. SkinHelper uses a website html scrape hack which I'm not sure is completely within IMDBs usage terms. Plus I don't like the idea of scraping html as I would need to update my plugin if they ever change their layout.

If you know of an API that provides top250 data then I will happily use it.

**Comment by jurialmunkey** [comment]
Okay, I found a Trakt list with IMDB top 250 that is update regularly:
https://trakt.tv/users/nielsz/lists/active-imdb-top-250?sort=rank,asc

Using that list to get Top250 data for Detailed Item and Service Monitor:
`$INFO[ListItem.Top250]`
`$INFO[Window(Home).Property(TMDbHelper.ListItem.Top250)]`

Can you test latest and confirm that everything is working correctly for you?

---
Relevant Commit: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/7a23c3cc4bf64245adc0fa3ab976f63d89ab8da2

**Comment by DimitarCC** [comment]
@jurialmunkey It works and parse the chart from that tract list. Well the list is quite different that official IMDB Top250 but is much better than nothing. Thanks.

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey It works and parse the chart from that trakt list. Well the list is quite different that official IMDB Top250 but is much better than nothing. Thanks.

Hmmm maybe I'll have to find a better Trakt list of IMDB Top 250
