### ISSUE TITLE
[BUG] New episodes fail to refresh in video media library

### ISSUE THREAD

**Issue by rosscm** [jurialmunkey/plugin.video.themoviedb.helper#1272]
### Describe the bug

I use the Umbrella plugin to populate my Kodi library with TV Shows and Movies. When I try to refresh the information for a currently running TV Show by selecting 'Refresh' from the context menu, I get a nondescript 'The MovieDB Helper' error message in the GUI. I've attached a full logfile that details the various errors. I also use the Titan Bingie Mod skin, if that adds any context to this issue.

My system specs:

- Kodi version: 20.3-Nexus
- Platform: Linux ARM 32-bit (RPI4)
- TheMovieDB Helper plugin version: 5.2.25

### Steps To Reproduce

1. Navigate to the TV Shows menu
2. Select a currently running TV Show (e.g., "FROM") to open the context menu
3. Click on 'Refresh' to update the information, ignoring local data
4. Watch as information does not refresh

### Debug log

[kodi.log](https://github.com/user-attachments/files/17592588/kodi.log)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
You aren't using most recent version of TMDbHelper. You're also using an old version of Kodi.

And TMDbHelper has nothing to do with refreshing details, especially not from some other plugin.
