### ISSUE TITLE
[BUG] constant error when running Kodi

### ISSUE THREAD

**Issue by kattza** [jurialmunkey/plugin.video.themoviedb.helper#1274]
### Describe the bug

Every time I run Kodi, TMDB immediately shows up an error, and whenever I finish or close a video wether tv show or movie, it also triggers an error. Although everything seems to be running fine on the surface. 

On a side note, on this my new setup with a windows, it randomly causes some sluggish behavior on playback. Not sure if is anything related to this bug…?

debug log attached 

[kodi.old.log](https://github.com/user-attachments/files/17608028/kodi.old.log)

### Steps To Reproduce

(Basically run Kodi; whenever close a video)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
```
HTTP Error Code: 401
Request: https://www.omdbapi.com//?&r=xml&i=tt15677150&plot=full&tomatoes=True
```

401 Error mean Unauthorised

Your OMDb api key is incorrect.

If you do not have an OMDb key, you may have accidentally entered some text or a space into the setting in TMDbHelper settings.
