### ISSUE TITLE
Text Input Prompt Appears on Apple TV for TMDb Addon, Preventing Automatic Stream Playback

### ISSUE THREAD

**Issue by jonij** [jurialmunkey/plugin.video.themoviedb.helper#1275]
### Describe the bug

When selecting a movie from the TMDb addon on Kodi for Apple TV, it is expected that the stream will automatically play through the xStream addon. However, a text input prompt appears instead, preventing the automatic playback. The stream only plays after manually entering the title. This issue does not occur on macOS, where the automatic playback works as intended.

### Steps To Reproduce

1.	Launch Kodi on an Apple TV device.
2.	Navigate to the TMDb addon and select a movie.
3.	Observe that a text input prompt appears instead of the stream automatically starting.
4.	Manually enter the movie title to start the stream.

### Screenshots and Additional Info

![Screenshot 2024-11-04 at 00 03 53](https://github.com/user-attachments/assets/236b18ca-5bb7-4175-8ce7-907500d28767)
Text Input Prompt

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
This is a player configuration issue, not a TMDbHelper issue.

This player is not provided by TMDbHelper. I cannot help with support for 3rd party players.
