### ISSUE TITLE
[BUG] info=collection type=collection query= "Title" return nothing when accent in collection name

### ISSUE THREAD

**Issue by Nanomani** [jurialmunkey/plugin.video.themoviedb.helper#1276]
### Describe the bug

When I want to list all item for a collection from online there is no result when there is an accent in collection name.

I use this command line in "DialogVideoInfo.xml" : 

`plugin://plugin.video.themoviedb.helper/?info=collection&amp;type=collection&amp;query='"$INFO[ListItem.Label]"'&amp;nextpage=false`

eg for the collection in TMDb site: 
"[La Planète des singes - Saga](https://www.themoviedb.org/collection/173710-planet-of-the-apes-reboot-collection)"

So the command is like that : 
`plugin://plugin.video.themoviedb.helper/?info=collection&amp;type=collection&amp;query='"La Planète des singes - Saga"'&amp;nextpage=false`

there is no result : 

![101](https://github.com/user-attachments/assets/54c26075-dc18-4be9-8a73-e3117ee26c37)

with this error in log : 
`error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=collection&type=collection&query='"La Planète des Singes - Saga"'&nextpage=false`

if you replace characteres with accent by characteres without accent : 
"La Planète des singes - Saga"
by
"La Planete des singes - Saga"

So the command is like that : 
`plugin://plugin.video.themoviedb.helper/?info=collection&amp;type=collection&amp;query='"La Planete des singes - Saga"'&amp;nextpage=false`

this works perfectly : 

![102](https://github.com/user-attachments/assets/1fe1800b-5347-480b-8fc6-9ad5cda27dbf)

It is not an encoded issue. my code works if there is "&" in collection name

![103](https://github.com/user-attachments/assets/26d83869-d93a-4650-9639-28f516b42f9a)

It the same issue with every collection with an accent in his name.

Perhaps it is a know limitation or issue in api TMDb.
So You are free to close this issue if no solution.

### Steps To Reproduce

1 - open movies => collection library  
2 - select an item "set" with an accent in his name
3 - open "context menu"
4 - select "information"

### Debug log

https://paste.kodi.tv/fenerelolo.kodi

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
> It is not an encoded issue. my code works if there is "&" in collection name

It is an encoding issue. If you double encode the accent letter it will work e.g. this works:

```
plugin://plugin.video.themoviedb.helper/?info=collection&amp;type=collection&amp;query='"La Plan%25C3%25A8te des singes - Saga"'&amp;nextpage=false
```

**Comment by jurialmunkey** [comment]
Due to decomposed unicode forms. This was originally added to deal with Arabic and other RTL not being correctly handled by Kodi edit control but I don't think the issue still exists so I can remove it.

Let's see if I break something for someone else in the process... 😆

**Comment by jurialmunkey** [comment]
You'll need v0.1.19 of `script.module.jurialmunkey`
https://github.com/jurialmunkey/script.module.jurialmunkey/releases/tag/v0.1.19

I'll push to my repo soon.

**Comment by Nanomani** [comment]
Thanks a lot for this very quick answer. 
It is perfect. All works fine now :)
