### ISSUE TITLE
Can’t update the moviedb helper

### ISSUE THREAD

**Issue by blatorone** [jurialmunkey/plugin.video.themoviedb.helper#1277]
### Describe the bug

When i try to update this addon, i get a Message „dependence on Script.modul.jurialmunkey in Version 0.1.19 can Not be satisfied
Kodi 21.1 Omega

### Steps To Reproduce

Update the addon 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by Nanomani** [comment]
IMHO if you install addon "TMDb Helper" from repo "repository.jurialmunkey" the update must works well : 
https://jurialmunkey.github.io/repository.jurialmunkey/repository.jurialmunkey-3.4.zip

Anyway I not a expert here. 
But a workaround it is to install yourself v0.1.19 of script.module.jurialmunkey from here : 
https://github.com/jurialmunkey/script.module.jurialmunkey/releases/tag/v0.1.19

Direct download : 
https://github.com/jurialmunkey/script.module.jurialmunkey/archive/refs/tags/v0.1.19.zip
