### ISSUE TITLE
[BUG] Artwork english fallback not working anymore

### ISSUE THREAD

**Issue by smokyy12** [jurialmunkey/plugin.video.themoviedb.helper#1279]
### Describe the bug

I use TMBD-Helper in german with fanart.tv api-key and it used to give me clear art titles for every movie and show when i enabled the fallback to english option in settings. now it stopped working on all my devices and different kodi setups and only gives me clear art when there is german available. when i set tmdb helper to english i get clear art for every movie and show. 
Maybe you can help, thx in advance

### Steps To Reproduce

Set tmdb language to german --> no clear art, even with fallback to english setting
Set i back to english --> clear art is there

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I haven't changed the code handling the artwork selection in a long time.

Do you have examples of how I can recreate this issue to test?

**Comment by smokyy12** [comment]
Yes, set your tmdb-helper metadata language to german and see if you get clear art titles for movies and shows. i find it very strange too, i use arctic horizon 2 and arctic fuse on 3 devices. i noticed that the clear art was gone on my pc setup, then i turned on my shield tv where kodi was still open, closed and reopened kodi and clear art was also gone there.
maybe its a problem with fanart.tv api if you havent changed anything? i also created a new api key and tested, no success.

**Comment by jurialmunkey** [comment]
Please give me examples of specific movies titles to test with.

**Comment by smokyy12** [comment]
Oh sorry, i misunsterstood. For example the show „mr. robot“ has no clear art in german, in english it works. Same for „Reacher“. For „Rings of Power“ i still get clear art in german, i think its because theres a translated title „Ringe der Macht“.

**Comment by jurialmunkey** [comment]
Both work fine for me in TMDbHelper

![screenshot00879](https://github.com/user-attachments/assets/15a38658-85b7-416e-87e6-846efdacfe16)

![screenshot00881](https://github.com/user-attachments/assets/e28371c7-0eec-46c7-8e18-9a8704f8b8c8)

<img width="952" alt="Screenshot 2024-11-12 103740" src="https://github.com/user-attachments/assets/a485da3a-eaa3-4d5d-8771-60a98f8987ee">

![Screenshot 2024-11-12 103714](https://github.com/user-attachments/assets/fe08aee3-4ca3-46cb-b98c-ff3bedc91dd8)

**Comment by matke-84** [comment]
I have written before about similar problems.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/1181

**Comment by jurialmunkey** [comment]
> I have written before about similar problems. #1181

This sounds like a different matter.

Either way, without reproducible examples it is difficult for me to fix. 

From the examples provided here I cannot reproduce the issue. As seen in my screenshots, it appears to be working correctly.

**Comment by smokyy12** [comment]
Thx for checking, it seems like the problem is somewhere on my side if its working for you. As i stated earlier, it used to work without a problem for years and  stopped working now on three different devices from one second to another without changing anything. maybe its some network related problem on my side. 
If a log would help you i will see to upload it as soon as i get to it.

**Comment by matke-84** [comment]
@jurialmunkey 
Turn off all three "Use fanart.tv..." and you will see that it doesn't work, of course delete cache. I wrote in my issue step by step what is happening just read carefully.

**Comment by smokyy12** [comment]
I just deleted tmdb-helper from addons and userdata and fresh installed it, it seems to work now as it used before. thx again for your fast replies.
