### ISSUE TITLE
MPAA rating not get for all movies

### ISSUE THREAD

**Issue by DimitarCC** [jurialmunkey/plugin.video.themoviedb.helper#128]
Currently MPAA rating is not get for all movies for some reason. For example it is not get for movie Star Wars Episode VII but is get nicely for Star Wars Episode VIII. Also there is no fallback to the kodidb MPAA rating value.
If i play with visibility like this 
`<include content="Object_Info_Line_Label">
                    <param name="id" value="$PARAM[uid]02" />
                    <param name="label" value="$INFO[Window(Home).Property(TMDbHelper.ListItem.MPAA)]" />
                    <param name="textcolor" value="$PARAM[textcolor]" />
                    <param name="visible" value="![String.IsEqual($PARAM[container]ListItem.DBType,artist) | String.IsEqual($PARAM[container]ListItem.DBType,album) | String.IsEqual($PARAM[container]ListItem.DBType,song)] + !String.IsEmpty(Window(Home).Property(TMDbHelper.ListItem.MPAA))" />
                </include>
                <include content="Object_Info_Line_Label">
                    <param name="id" value="$PARAM[uid]02" />
                    <param name="label" value="$INFO[$PARAM[container]ListItem.MPAA]" />
                    <param name="textcolor" value="$PARAM[textcolor]" />
                    <param name="visible" value="![String.IsEqual($PARAM[container]ListItem.DBType,artist) | String.IsEqual($PARAM[container]ListItem.DBType,album) | String.IsEqual($PARAM[container]ListItem.DBType,song)] + String.IsEmpty(Window(Home).Property(TMDbHelper.ListItem.MPAA))" />
                </include>`
it results to initially show up the kodidb value and then after a second go overwritten by TMdB Helper one.

**Comment by jurialmunkey** [comment]
Mpaa works fine for me. Where are you saying it is not available? In the service monitor or in a list or in the details screen?

In lists details of a movie are only retrieved if they have previously been cached. In service monitor or details screen the info should be retrieved every time

**Comment by jurialmunkey** [comment]
Ah I see what is happening. For US releases, the digital release for Star Wars VII has no certification.

This is the response from TMDB:
```
{
        "iso_3166_1": "US",
        "release_dates": [
          {
            "certification": "",
            "iso_639_1": "",
            "note": "",
            "release_date": "2016-04-01T00:00:00.000Z",
            "type": 4
          },
          {
            "certification": "PG-13",
            "iso_639_1": "",
            "note": "",
            "release_date": "2015-12-18T00:00:00.000Z",
            "type": 3
          },
          {
            "certification": "PG-13",
            "iso_639_1": "",
            "note": "Los Angeles, California",
            "release_date": "2015-12-14T00:00:00.000Z",
            "type": 1
          },
          {
            "certification": "PG-13",
            "iso_639_1": "",
            "note": "",
            "release_date": "2016-04-05T00:00:00.000Z",
            "type": 5
          }
        ]
      },
```

**Comment by jurialmunkey** [comment]
Okay should be fixed now. I've made it so that theatrical release is the preference for certifications. If there is no certification for theatrical release, TMDBHelper will then check the other release types for a certification.

---
Relevant Commit: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/589a94ad62924acd78ba588b3a46e4e1a5c99926

**Comment by DimitarCC** [comment]
@jurialmunkey I still think that there needs to fall back to the kodidb stored values. 
For example i have a playlist/library  that uses "Local Information". For that case obviously there is no way TMDBHelper to get certification from somewhere......and it stays empty. If i do the trick above with visibility it have very bad side effects of that shown standard values and visually replacing it with TMDBHelper one.

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey I still think that there needs to fall back to the kodidb stored values.
> For example i have a playlist/library that uses "Local Information". For that case obviously there is no way TMDBHelper to get certification from somewhere......and it stays empty. If i do the trick above with visibility it have very bad side effects of that shown standard values and visually replacing it with TMDBHelper one.

This addon is specifically for retrieving information from online. There is no reason for TMDBHelper to retrieve local information when you can get the local info with a standard skin variable:

```xml
<variable name="Label_MPAA">
    <value condition="!String.IsEmpty(Container.ListItem.MPAA)">$INFO[Container.ListItem.MPAA]</value>
    <value condition="!String.IsEmpty(Window(Home).Property(TMDBHelper.ListItem.MPAA))">$INFO[Window(Home).Property(TMDBHelper.ListItem.MPAA)]</value>
<variable>

---

<label>$VAR[Label_MPAA]</label>
```

There's absolute no reason for you to use multiple label controls when you can use a single variable.

**Comment by DimitarCC** [comment]
Well i know it can happen with a variable but there is some flaws:
1. Variable is not useful in the case i have a container from include param (i dont know a way to pass a param to variable)
2. The way you specified it it always will show the Container.ListItem.MPAA when it is available and never TMDBHelper.ListItem.MPAA
3. If  swap places of the values in your example it now load conditionally  Container.ListItem.MPAA or TMDBHelper.ListItem.MPAA depending on which exists BUT the visual result is exactly the same like with multiple labels..... It loads Container.ListItem.MPAA (because that is very very fast) and when TMDB value is ready it swap it with TMDBHelper.ListItem.MPAA. Thats very annoying for the user visually as you see different values goes in and out in front of your eyes.

I understand the addon is designed for online results but in the current state it means it can not be used in environment where you have scraped local nfo and also have scraped online items due to heavy visual glitches.

**Comment by jurialmunkey** [comment]
> Also is there something like **isloaded** variable for TMDBHelper so to wait till info is parsed?

`Window(Home).Property(TMDBHelper.IsUpdating)`
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor

>
>The way you specified it it always will show the Container.ListItem.MPAA when it is available and never TMDBHelper.ListItem.MPAA

Why would you want online info if you have local info? 

I don't understand what you're trying to do.

**Comment by DimitarCC** [comment]
@jurialmunkey OK here is my case:
I have several media sources - one is using TMDB for info parsing and the second is using local .nfo (generally some asian movies that doesnt exists in TMDB).
Since that 2 sources are in the same library for movies they are shown at same place/view so i need to be possible conditionally to to show Container.ListItem.MPAA or TMDBHelper.ListItem.MPAA depending what is existing.
Also for the movies that exists in TMDB i prefer getting the info from TMDBHelper since appears to be much more reliable.

**Comment by jurialmunkey** [comment]
So why can't you use?

<variable name="Label_MPAA">
    <value condition="!String.IsEmpty(Window(Home).Property(TMDBHelper.ListItem.MPAA))">$INFO[Window(Home).Property(TMDBHelper.ListItem.MPAA)]</value>
    <value condition="!String.IsEmpty(Container.ListItem.MPAA)">$INFO[Container.ListItem.MPAA]</value>
<variable>

**Comment by DimitarCC** [comment]
Well because:
1. "Container." is a variable in my case passed to the include as a param. So that cant be used in variable.
2. in that example since !String.IsEmpty(Container.ListItem.MPAA) is always true it first loads Container.ListItem.MPAA which you see it on the screenthen after sometime about 2 seconds it loads TMDBHelper.ListItem.MPAA and replaces the value. In my opinion this is not cool for the end user. Let me give you an example...
Since my TMDB scrapper is configured to use Bulgarian as parsing language (that includes europe/bulgarian certification) when a movie is parsed for example it shows "BG-C" for certification. But TMDBHelper shows US certification that for the same movie is PG-13 so the result of that variable is first show BG-C then after 2 seconds shows "Rated PG-13". I want to avoid this visual changing.
Also TMDBHelper.IsUpdating is alwyas true for some reason when i have selected an item that is parsed by local .nfo. On the log it says error that TMDBHelper can not parse the info for that movie.

**Comment by jurialmunkey** [comment]
>     2\. But TMDBHelper shows US certification that for the same movie is PG-13 so the result of that variable is first show BG-C then after 2 seconds shows "Rated PG-13". I want to avoid this visual changing.

Then set Bulgarian as the language in TMDBHelper.

**Comment by DimitarCC** [comment]
The problem is it results in a strange values like BG-ж wich is wrong because there is no such certificastion

**Comment by jurialmunkey** [comment]
I still don't understand the need to use TMDBHelper if you already have local information. Just fix your local information so that it is correct.

Also your original code in OP is wrong because you reuse the same ID for both labels. Each label needs a unique ID number because if you look at `<include name="Object_Info_Line_Label">` you will see that it checks `<visible>!String.IsEmpty(Control.GetLabel($PARAM[id]))</visible>`

You also need to check that `$PARAM[container]ListItem.MPAA` is not empty in the control where you show it.

All the issues you are raising are either to do with issues in your local database or issues with poor skin implementation, and are not issues with TMDBHelper.

**Comment by DimitarCC** [comment]
@jurialmunkey Well i not say its an issues to TMDBHelper. Just in my opinion it parsing mechanism needs to be refined so when it not find info online to fallback to the local info.
And besides how do you suggest to fix my local info? The movie is parsed via TMDB including its wrong certification. I can not edit this (well i can but needs to edit the kodidb). So i want this movie certification to be parsed by TMDBHelper since it brings the correct value.

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey Well i not say its an issues to TMDBHelper. Just in my opinion it parsing mechanism needs to be refined so when it not find info online to fallback to the local info.
> And besides how do you suggest to fix my local info? The movie is parsed via TMDB including its wrong certification. I can not edit this (well i can but needs to edit the kodidb). So i want this movie certification to be parsed by TMDBHelper since it brings the correct value.

Check your scraper settings.
Use refresh in the info dialog to select the correct movie if the wrong one has been selected.
If all else fails, use an nfo file
https://kodi.wiki/view/NFO_files

**Comment by DimitarCC** [comment]
well also to be precise in Object_Info_Line_Label if you refer you AZ2 implementation it is used in that  way
` <control type="label">
                <width>auto</width>
                <label>  |  </label>
                <height>40</height>
                <aligny>top</aligny>
                <textcolor>$VAR[ColorHighlight]</textcolor>
                <font>font_small</font>
                <visible>!String.IsEmpty(Control.GetLabel($PARAM[id]))</visible>
                <visible>$PARAM[divider]</visible>
                <visible>$PARAM[visible]</visible>
            </control>`
that is just for that "  |  " label that shows vertical line separator and since the 2 labels are for the same thing isnt it they have to be with same ID?
You have same structure for
`<include content="Object_Info_Line_Label">
                    <param name="id" value="$PARAM[uid]10" />
                    <param name="label" value="$INFO[$PARAM[container]ListItem.Genre]" />
                    <param name="textcolor" value="$PARAM[textcolor]" />
                    <param name="visible" value="String.IsEqual($PARAM[container]ListItem.DBType,album)" />
                </include>
                <include content="Object_Info_Line_Label">
                    <param name="id" value="$PARAM[uid]10" />
                    <param name="label" value="$INFO[Window(Home).Property(SkinHelper.ListItem.WatchedCount),, $LOCALIZE[20163] ]$INFO[Window(Home).Property(SkinHelper.ListItem.Count),, [LOWERCASE]$LOCALIZE[16102][/LOWERCASE]]" />
                    <param name="textcolor" value="$PARAM[textcolor]" />
                    <param name="visible" value="String.IsEqual($PARAM[container]ListItem.DBType,set)" />
                </include>`
you use for 2 labels same $PARAM[uid]10 ID.

**Comment by DimitarCC** [comment]
Ahh yes i know i can always fallback to .nfo but since i have too much items with wrong certification that will take ages. Still i believe that the proper implementation should be to have a fallback to the Container.ListItem.MPAA if TMDBHelper fails to retrieve value online.

**Comment by jurialmunkey** [comment]
> well also to be precise in Object_Info_Line_Label if you refer you AZ2 implementation it is used in that way

You are talking about a skin that is in Alpha. It is NOT complete. That is clearly a mistake and the second should have $PARAM[uid]11 as you can see that every single other include has a unique ID.

Also those includes are not intended to be used the way you are using them. There are plenty of other approaches to achieve what you want to do.

**Comment by jurialmunkey** [comment]
> 
> 
> Ahh yes i know i can always fallback to .nfo but since i have too much items with wrong certification that will take ages. Still i believe that the proper implementation should be to have a fallback to the Container.ListItem.MPAA if TMDBHelper fails to retrieve value online.

The service monitor is not meant to exist to fix poorly managed local databases. It is intended to provide additional information from online sources. The information it provides should always come from online. If you want to use local information, then use the local information in the ListItem properties that you have. I'm not adding something because you are too lazy to fix your local database.

**Comment by DimitarCC** [comment]
Well its your choice. But as a software developer i believe that nothing should be left to rise error in the log and to not have fallbacks (like it is now an empty string). Ok if the fallback fails leave it empty but why not get a value if exists.
The what bothering me here is not that this is missing in your code but that it can not be made in the way that doesnt have visual glitches.
It is not a matter of faulty local or not local DB its a matter of that when something works it should works correct.
Now it not works at all when you have mixed library with online and offline scrapped content and want to use TMDBHelper for the online content only. Not matter how you will made it (the only way i currently know is by conditional showing of labels)  it always will be visually unpleasant for the online scrapped content.
since for online scraped content it will ALWAYS return first Container.ListItem.MPAA since this always exists and it is retrieved very fast.
If you have a suggestion how that visual glitch should be overcomed i will be glad to hear.

**Comment by jurialmunkey** [comment]
What is the error in the log?

**Comment by DimitarCC** [comment]
OK my bad...there is indeed an error but probably it is not related to the TMDBHelper
The error were ERROR: Open - error probing input format but probably its something from Kodi itself and not from TMDBHelper.
So forget about the error. But all the rest i still think should be refined.
