### ISSUE TITLE
[BUG/Question] Were there any changes to how CropImage is handled? Having some issues with making it persistent on AF1

### ISSUE THREAD

**Issue by OfficerKD637** [jurialmunkey/plugin.video.themoviedb.helper#1280]
### Describe the bug

Hey Jurial!

Hope you're doing well!

The last few changes to TMDb Helper have been awesome!

I was working on the AF1 Mod recently and noticed that the CropImage goes away and fallbacks to the title when the shutdown menu is activated. This is also the case for the unmodded AF1.

 AF2 is unaffected so I'm assuming that it handles the cropimage in the info box differently.

If I roll back to TMDb Helper v5.3.0, everything works again (for both AF1 and AF1 Mod). 

If you think this is not a TMDb Helper issue but more of a skin issue, could you kindly let me know what changes I would need to make to the AF1 Mod to fix it? 

Thank you so much!

### Steps To Reproduce

1. Have the latest version of TMDb Helper (v5.4.5)
2. Install AF1
3. Activate shutdown menu and notice the clearlogo (CropImage) of the items on your home page fallback to the text title
4. Go back to TMDb Helper v5.3.0 and everything works again 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
https://github.com/jurialmunkey/skin.arctic.fuse.2/blob/d32eeab10cd9b65b50910ae1d80d4c59dfc972b1/1080i/Custom_1170_Dialog_HomeMenu.xml#L6

**Comment by OfficerKD637** [comment]
Thank you so much!! I was looking in the wrong place haha. I need to get better at troubleshooting and learning how to locate the cause of problems. I don't think I could catch up to you even if I did this  for 10 years! 🏃🏃

**Comment by jurialmunkey** [comment]
>I need to get better at troubleshooting and learning how to locate the cause of problems. 

tbf, that property isn't documented.

It is effectively the same as servicepause which is documented [here](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor)
```
SetProperty(TMDbHelper.ServicePause,True)
```

The main difference is that ServicePause only pauses the service to prevent clearing the properties, whereas ContextMenu also passes through the existing item in the service to the dialog -- so e.g. with ContextMenu property you can add the 99950 container to the custom dialog if you wanted to get details about the item "underneath" the dialog like how the context menu gets the poster/fanart etc.

**Comment by OfficerKD637** [comment]
Oh I see... Thank you so much for explaining it!
And yeah I forgot to mention that Window(Home).Property(TMDbHelper.ListItem.base_*whatever*) stopped working on AF1. So the context menu wasn't pulling the title or posters/fanarts. 
I replaced those with Container(99950).ListItem.Property(base_properties) and it's working again.

**Comment by jurialmunkey** [comment]
> And yeah I forgot to mention that Window(Home).Property(TMDbHelper.ListItem.base_whatever) stopped working on AF1

That's because AF1 uses the container method and I fixed the code in TMDbHelper (these actually shouldn't have ever been set to the window properties - only the container). 

AF2 does not use that method. It uses the "classic" method which sets the properties to the home window instead of using a listitem in the container (wiki describes how both work), so that's why they work there.

I switched back to classic because of an underlying bug in Kodi that the container method triggers. If it didn't cause crashes I'd still use container approach as it is better in every other way (especially in terms of convenience from a skinning perspective).

**Comment by OfficerKD637** [comment]
I see.... So AF1 Mod is going to stay on the dark side for now 😈 
~~The original AF1 had `Window(Home).Property(TMDbHelper.ListItem.base_whatever)` for [Label_ContextMenu_Title](https://github.com/jurialmunkey/skin.arctic.fuse/blob/6a2c9d463a1b1ae4e38eeddf2673c003f321bf5f/1080i/Includes_Labels.xml#L1588-L1593), [Image_ContextPoster](https://github.com/jurialmunkey/skin.arctic.fuse/blob/6a2c9d463a1b1ae4e38eeddf2673c003f321bf5f/1080i/Includes_Images.xml#L123-L126), [Image_ContextFanart](https://github.com/jurialmunkey/skin.arctic.fuse/blob/6a2c9d463a1b1ae4e38eeddf2673c003f321bf5f/1080i/Includes_Images.xml#L128-L131), [Image_ContextClearlogo](https://github.com/jurialmunkey/skin.arctic.fuse/blob/6a2c9d463a1b1ae4e38eeddf2673c003f321bf5f/1080i/Includes_Images.xml#L133-L136) and [Image_ContextIcon](https://github.com/jurialmunkey/skin.arctic.fuse/blob/6a2c9d463a1b1ae4e38eeddf2673c003f321bf5f/1080i/Includes_Images.xml#L138-L141) which used to work up until a few versions ago (don't remember the exact version number).~~
(Sorry I just noticed that you’re already aware of this)
