### ISSUE TITLE
[BUG] ListItem.Property(base_xxx) seems not working anymore from TMDb Helper 5.4.8

### ISSUE THREAD

**Issue by Nanomani** [jurialmunkey/plugin.video.themoviedb.helper#1281]
### Describe the bug

I use in "DialogContextMenu.xml" some code to show the local poster (or plot from Kodi db).

```
    <variable name="Image_Poster_Context_Menu">
        <value condition="!String.IsEmpty(Container(99950).ListItem.Property(base_poster))">$INFO[Container(99950).ListItem.Property(base_poster)]</value>
        <value condition="!String.IsEmpty(Container(99950).ListItem.Art(poster))">$INFO[Container(99950).ListItem.Art(poster)]</value>
        <value condition="!String.IsEmpty(Container(99950).ListItem.Art(tvshow.poster))">$INFO[Container(99950).ListItem.Art(tvshow.poster)]</value>
        <value>fallback/fallback.png</value>
    </variable>
```

So this has always worked without issue from now.
But from TMDb Helper 5.4.8 when I open "context menu" for a local movie I see the poster from TMDb online.

I have make some test with : 

- Kodi stable v21.1 windows x64 
- Kodi v22 nightly windows x64
- thumbnail, TMDb database, texture.db deleted 

The behaviour is always the same.
(of course "Get additional details from the local Kodi Library database" is enable in TMDb Helper settings)

I have make a test with your skin AH2 what use methode container in "DialogContextMenu.xml"
The behaviour is the same too.

I don't know if all this is normal?
I may have missed something...

### Steps To Reproduce

what is expected : 

1. Use skin AH2
2. insall TMDB Helper 5.2.25 from Kodi repo
3. Set a custom poster for a local movie A stored in Kodi db
4. Open context menu for the movie A
5. The poster show must be the "custom" poster

behaviour with lastest TMDb Helper Addon

6. then install the latest TMDB Helper 5.4.29
7. restart Kodi
8. Select movie A from widgets or views layout
9. Open context menu for the movie A
10. The poster show is come from TMDb online

### Debug log

https://paste.kodi.tv/ohudokikey.kodi

### Screenshots and Additional Info

From Movie A : 

![01](https://github.com/user-attachments/assets/08357519-bdea-4a03-8d97-f40854ef5787)

Context menu with TMDb Helper 5.2.25 : 

![2024-11-25_190824](https://github.com/user-attachments/assets/674bb27c-4bf3-4747-8e43-922ce372637f)

Context menu with TMDb Helper 5.4.9 : 

![2024-11-25_191055](https://github.com/user-attachments/assets/523114e3-0326-4c51-ad0c-d1abbaa08da2)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
How this is handled has now changed and is defined skin side as to which properties are required.

See af2 for an example of how it is implemented
 https://github.com/jurialmunkey/skin.arctic.fuse.2/blob/omega/extras/tmdbhelper/baseitem.json

**Comment by Nanomani** [comment]
Thanks for your quick answers.
I'd never have found the solution myself.

Whaow it is a big move :)
From my very quick test it is works well like that.

If I all understand "Service Monitor" must be always disable.
Container method can't be use anymore.

I would to know if this new way is definitively or it is a tempory workaround because there is some bug with Kodi.

In other way I would to know if I must change all necessary code in my skin right now (no problem with that ) or if I must be just patient and wait that bug with Kodi was fixed.

I hope to be understable. google translate isn't always magic :)
Anyway like always thanks a lot for your time.

PS : this post can be closed

**Comment by jurialmunkey** [comment]
>  I'd never have found the solution myself.

It's not documented yet because I only just added it

> Whaow it is a big move :)

It should give a lot more control because it lets you define which properties you need from the base item and what fallbacks to use.

> If I all understand "Service Monitor" must be always disable.

No, there is no need to disable the service monitor. It needs to be enabled to use the base item properties. The base item properties are in addition to the properties the service retrieves from TMDb API.

>  Container method can't be use anymore.

It can still be used.

The problem with the container method has always existed since its introduction. 

It is because the underlying Kodi interface it uses is slightly unstable and can occassionally cause a crash, especially when using ReloadSkin()

The only reason I switched to window properties for AF2 is because I decided that I preferred the stability more. However, if you find the container method is stable enough for you, then you can continue to use it.

**Comment by Nanomani** [comment]
> It's not documented yet because I only just added it

No problem I don't blame you. Like you said all of this is new :)

> It should give a lot more control because it lets you define which properties you need from the base item and what fallbacks to use.

more control is always welcome :)

> No, there is no need to disable the service monitor. It needs to be enabled to use the base item properties. The base item properties are in addition to the properties the service retrieves from TMDb API.
> It can still be used.

Thanks for your explaind very clear

> The problem with the container method has always existed since its introduction.
> It is because the underlying Kodi interface it uses is slightly unstable and can occassionally cause a crash, especially when using ReloadSkin()

I understand some of the behavior or crash better now.

> The only reason I switched to window properties for AF2 is because I decided that I preferred the stability more. 

More stability is always welcome

> However, if you find the container method is stable enough for you, then you can continue to use it.

Not really. Specialy from some week with Libreeelec and Android.
Perhaps this will better with Python 3.13.x : 
https://github.com/LibreELEC/LibreELEC.tv/pull/9374

With Windows is less dramatic but Indeed there some crash when using ReloadSkin().
So my choice is clearly already done :)

So after migrate the code for an old skin from Embuary.Helper and Embuary.Info, etc.. to TMDb Helper, script.skinvariables, script.texturemaker, this new approach shouldn't be too difficult to adapt from I have seen here : 

https://github.com/jurialmunkey/skin.arctic.fuse.2/commit/b044f84ed04f67ee5d3d953a555304bedd5b8ed9

Thanks you so much
