### ISSUE TITLE
API Language and Country for Players

### ISSUE THREAD

**Issue by mac-88** [jurialmunkey/plugin.video.themoviedb.helper#1288]
Hello, I have  small question, I don't seem to understand something.
I have set TMDBhelper to German and start the content with a player for fen light. The title transfer to the addon should also be in German. Now I have the "language: de" in the player (not "api_language", because I set tmdbhelper to German) but the addon looks for the English title. I also try with "de_title" in the play_movie if i missunderstand something, but it dont work. Have I overlooked or misunderstood something or could it be that the addon itself resets the title?

Thank you a lot for the help

```
{
    "name": "fenlight",
    "plugin": "plugin.video.fenlight",
    "priority": 500,     
    "language": "de",
    "is_resolvable": "true", 
    "play_movie": "plugin://plugin.video.fenlight/?mode=playback.media&media_type=movie&query={name}&year={year}&poster={poster}&title={title}&tmdb_id={id}&autoplay=false",
    "play_episode": "plugin://plugin.video.fenlight/?mode=playback.media&media_type=episode&query={showname}&year={year}&season={season}&episode={episode}&ep_name={title}&tmdb_id={tmdb}&premiered={firstaired}&autoplay=false"
}
```

### Steps To Reproduce

start content with player

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [ ] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
`{title}` is returned in language set in settings.

`language: de` must be used with `{de_title}` etc. and is used to retrieve additional translations independent of the language set in TMDbHelper settings

if your language is German in settings and `{title}` is returning an English title then this is the information returned by the API.

>  could it be that the addon itself resets the title?

Yes this is very much a possibility and depends on how the addons works. It is possible that it looks up the information based upon the ID and it doesn't matter what values you pass it for the title.
