### ISSUE TITLE
[BUG] Season and Episode level paths don't set Container.Art(fanart)

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1293]
### Describe the bug

As the title. When navigating to the season or episode levels of items the plugin doesn't set Container.Art(fanart)

In fact it's doesn't seem to set and of the container art.

### Steps To Reproduce

Try to access Container.Art(fanart) from a season or episode level.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I don't think plugins can set this. At least I'm not aware of a method to do so.

You can get tvshow artwork from the item though with `ListItem.Art(tvshow.fanart)` etc.

**Comment by roidy** [comment]
Thanks
