### ISSUE TITLE
Player for Jacktook addon

### ISSUE THREAD

**Issue by Sudiar31** [jurialmunkey/plugin.video.themoviedb.helper#1295]
### Describe the feature that you'd like

Please add Jacktook addon player to https://bit.ly/tmdbplayers.
Cause I can't insert   .json.file. on Kodi 21.1. due to validation issue.
Thanks

### Why is this feature needed? What problem does it solve?

Cause ia can't play movies of Jacktook addon from Tmdb Helper widget

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
I am not a4k. 
I do not make this player set. 
Ask the author.

**Comment by Sudiar31** [comment]
Ok
Thanks
