### ISSUE TITLE
What am I doing wrong? I keep getting an  OMDb - Uauthorised 401 Error

### ISSUE THREAD

**Issue by jonny-fairplay** [jurialmunkey/plugin.video.themoviedb.helper#132]
Hi

I'm new to the Arctic Zephyr 2 skin, but I am absolutely loving the way this skin looks.

However, I'm having some issues with the OMDb API key and get this error (see image).

I've added my personel OMDb API key in both:
TheMovieDb Helper settings
script.modules.metadatautils (under Skin - Manage dependencies)

What am I doing wrong?

![OMDb error](https://user-images.githubusercontent.com/62239001/76742164-f86b4880-6770-11ea-88cf-c3746eb6bc71.jpg)

**Comment by jurialmunkey** [comment]
It means that your API key is wrong.

Check that you've entered your key correctly. Keys are case sensitive. Also make sure you haven't added an errrant space at the end or beginning of the key.

**Comment by jonny-fairplay** [comment]
Thanks a bunch for a very quick reply jurialmunkey :-)

I tried copy pasting it directly, to avoid any typos, can you tell me if all this info should be included in the beginning, as I have done that: 
http://www.omdbapi.com/?i=

**Comment by jonny-fairplay** [comment]
Or should I instead include everthing after the =

Also, can I use my personel key, for KODI on my Windows PC as well as my 2 Raspverri Pi's (both running LibreELEC)?

**Comment by jonny-fairplay** [comment]
Ok, so I tested with the string after =, but still got the same 401 Error, so cleary I'm still doing something wrong :-(

I copy/pasted the string, so no errors should from a typo

**Comment by jonny-fairplay** [comment]
I'm such a noob (sorry) :-(
I've entered the 8 characters after apikey=, I get no 401 error now, but besides stars and TMDB, I get no other ratings?

**Comment by jonny-fairplay** [comment]
So I finally got ir working, however some movies, like Captain Marvel, is only displaying stars and TMDB ratings, I even tried moving it to the same folder as the rest of my movies, and then removing and adding the folder as source, but still no luck.

**Comment by jurialmunkey** [comment]
AZ2 doesn't use tmdbhelper for ratings so I'm closing this as not a tmdbhelper issue anymore.

**Comment by jonny-fairplay** [comment]
Oh ok, I must have misunderstood, where are the ratings coming from?

![ratings in skin](https://user-images.githubusercontent.com/62239001/76831280-565a6780-6827-11ea-9fc1-41eb6f599de2.PNG)

![ratings specific](https://user-images.githubusercontent.com/62239001/76831285-56f2fe00-6827-11ea-857b-6484d28e10b3.PNG)

**Comment by jurialmunkey** [comment]
In AZ2 those ratings come from skinhelper. You need to follow the instructions in the first post of the AZ2 thread. You must install the beta version of skinhelper from marcelveldts repo.

**Comment by jonny-fairplay** [comment]
Ok thank you and again sorry for being a noob :-)

What does themoviedb.helper do and what are all the ratings in the 2nd. screenshot I've attached?

**Comment by jurialmunkey** [comment]
> 
> 
> Ok thank you and again sorry for being a noob :-)
> 
> What does themoviedb.helper do and what are all the ratings in the 2nd. screenshot I've attached?

TMDbHelper can provide ratings and I use it for that purpose in Arctic Horizon. 

That feature just isn't supported in AZ2 - in AZ2 you need to use Skin Helper for online ratings.
