### ISSUE TITLE
Local library not updating 

### ISSUE THREAD

**Issue by justinkruit** [jurialmunkey/plugin.video.themoviedb.helper#134]
I've restarted Kodi multiple times. I'm certain there is a new episode of Brooklyn 99 available (checked within the plugin and from there it's available), but it seems like the plugin doesn't want to add the items to the library.

Also, could you potentially add a function that checks for new episodes every day or so? I keep my Shield TV running which means my Kodi barely restarts, and it's nice to just have them added in the background.

**Comment by jurialmunkey** [comment]
Debug log please.

Also, some questions:
- Have you previously added an episode of Brooklyn 99?
- Does the library folder in TMDBhelper settings match the location where you added the Brooklyn 99 episodes? The plugin only checks the folder set in the settings for shows that it needs to update, and it will only pick-up shows that were added by TMDbHelper.
- Is the folder where the strm files are added by the plugin unmodified? If you modify the structure or other aspects manually, it might interfere with things.

You can force a manual recheck/auto-update by running the following command by either adding it to a keymap or attaching it to a menu shortcut (assuming you use a skin with skinshortcuts)
`RunScript(plugin.video.themoviedb.helper,library_autoupdate)`

**Comment by justinkruit** [comment]
Made a log while starting up Kodi. Wasn't able to copy and paste the content (on mobile), so I uploaded the log file. https://cdn.justinkruit.me/kodi.log 

- Yes, Brooklyn 99 is already in my library using the plugin, just not the latest episode.
- the folder is still the original location that the plugin starts in. I created a new source in Kodi and pointed it to that folder.
- it's unmodified except by the plugin itself of course, as far as I know.

I added that script as a custom item to the skin, but it doesn't seem to add the episode either.

**Comment by jurialmunkey** [comment]
Thanks for the log. It is very strange. I can see that the library auto updater is running correctly and has no errors. It is updating other shows that you've added but I can't see any mention of Brooklyn 99 at all.

Can you double check the actual folder ( the default is in `userdata/addon_data/plugin.video.themoviedb.helper/tvshows` ) and make sure that there is a Brooklyn 99 folder in there and that it has a `tvshow.nfo` file in the folder?

If it definitely does, can you test again with the update that I just pushed (v2.2.85). It's possible that might fix the issue.

**Comment by justinkruit** [comment]
Now that I checked, `tvshow.nfo` indeed seems to be missing. It also seems to be missing in 2 other show folders (Elementary and Human Planet). Should I just re add them to the library to fix that file being missing?

**Comment by jurialmunkey** [comment]
> 
> 
> Now that I checked, `tvshow.nfo` indeed seems to be missing. It also seems to be missing in 2 other show folders (Elementary and Human Planet). Should I just re add them to the library to fix that file being missing?

Yeah if you add to library again it should be added. The nfo file is what the script checks to autoupdate the shows. If it isn't there then it won't autoupdate.

**Comment by justinkruit** [comment]
That seems to fix it. Although now I see another problem, and that's even though the option to update library after adding items is enabled, it doesn't actually do it. I need to manually update the library to see the new items.

**Comment by jurialmunkey** [comment]
I haven't been able to recreate this issue where the library needs to be manually updated. It's working fine for me.
