### ISSUE TITLE
[BUG] Add to Kodi library via context menu.

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#135]
I noticed a bug with the add to Kodi library context menu option. This issue only happens when the setting "Default select action in addon" is set to Play/Open. When you open context menu on a TV Show title and click Add to Kodi library it brings up the player selection dialog and keeps looping over and over.

**Comment by jurialmunkey** [comment]
I can't replicate this issue. Works fine for me.

**Comment by JayDee696969** [comment]
Ok, ill give it another go all fresh..
