### ISSUE TITLE
TV Show Missing - But Appears on The Movie DB

### ISSUE THREAD

**Issue by abbaskip** [jurialmunkey/plugin.video.themoviedb.helper#136]
So this show appears on the Movie DB site:
https://www.themoviedb.org/tv/55638-jamie-and-jimmy-s-food-fight-club

And on IMDB:
https://m.imdb.com/title/tt4410492/

And trakt:
https://trakt.tv/shows/jamie-and-jimmy-s-food-fight-club

But whenever i watch an episode, in My Next Episodes it comes up as N/A and doesn't display the show. Any ideas?

I'm watching from local library if that helps. Is it an issue linking trakt and TMDB?

**Comment by abbaskip** [comment]
I closed this as I noticed a load of episodes were missing from TMDB - but they're all the now, and still getting the error.

**Comment by jurialmunkey** [comment]
Trakt doesn't have a TMDb ID listed for it, so there isn't an ID to lookup the details on TMDb.

You can see this in the left bar on the Trakt page down the bottom. It has links for TVDB IMDB Fanarttv Wikipedia and JustWatch, but no TMDB link. 

If there was no episodes previously, it probably wasn't listed on TMDB when Trakt did initial scrape. I'm not sure if they have to manually add it now or if it gets pulled in on an automated job at some stage.

**Comment by abbaskip** [comment]
Great.

FYI I chatted to Trakt and to link to TMDB (if TVDB exists), you simply need to edit TMDB with the TVDB ID. Then every 24 hours Trakt does a refresh based on that.

I then had to watch an episode so your add-on would refresh. Sorted now.

**Comment by jurialmunkey** [comment]
> 
> 
> Great.
> 
> FYI I chatted to Trakt and to link to TMDB (if TVDB exists), you simply need to edit TMDB with the TVDB ID. Then every 24 hours Trakt does a refresh based on that.
> 
> I then had to watch an episode so your add-on would refresh. Sorted now.

That's really useful information to know! Thanks for following up about this issue with them.
