### ISSUE TITLE
[Feature Request] Some Way to Refresh Metadata

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#137]
Particularly when faced with repeated Fanart.tv outages, I find that often artwork on widgets fed by TMDbHelper ends up missing or "stale". Is there any way to have a "clear cache" or "refresh metadata" option, so that the add-on will force retrieve them?

**Comment by jurialmunkey** [comment]
You already can. It is in the details page:

![Honeyview_screenshot661](https://user-images.githubusercontent.com/4618719/77402796-51874c00-6e03-11ea-8067-68bec97b55e0.jpg)

Also, if a lookup for artwork fails on fanarttv then it doesn't get cached. Only successful requests get cached.

**Comment by drinfernoo** [comment]
Oh, nice! That works for me 😁
