### ISSUE TITLE
Hide Watched in Widget?

### ISSUE THREAD

**Issue by swisslis** [jurialmunkey/plugin.video.themoviedb.helper#139]
Thank you for adding 'sort by aired date' so quickly!
Though it has brought another issue - i cannot seem to hide watched series. So fully watched shows are in my list due to widget limit of 20, it isnt showing a number of older shows. Is this a possibility to be added?

**Comment by jurialmunkey** [comment]
Are you talking about in the "Up Next Episodes" list?
Watched episodes shouldn't be showing there.

Or are you talking about some other list?

**Comment by swisslis** [comment]
Yes in the up next episodes list. I thought the same, and have hidden watched episodes everywhere possible (and they don't show within the trakt list within tmdb helper) but yet the shows still come up on widget. They have the watched tick indicator, and the suggested episode is the very first episode of said programme.

**Comment by jurialmunkey** [comment]
Can you test latest version? Hopefully this bug should be fixed now.

**Comment by swisslis** [comment]
Tested and appears to be working perfectly! Thanks really appreciate 2 really quick awesome fixes ive requested. Cheers :)
