### ISSUE TITLE
Default Player Selection

### ISSUE THREAD

**Issue by sttephan** [jurialmunkey/plugin.video.themoviedb.helper#141]
Hi jurialmunkey,

first, thanks for yr. great contributions to kodi - Really appreciate it.

For me there is an issue with tmdb helper not picking up external default players anymore (from other addons) Means in settings only „youtube search“ shows up when hitting „default player“

Obviously I downloaded the players list before and had a look into user data folder, where all the .json files are there...

I tried multiple times now on Shield with fresh installs/updates of kodi, tmdb helper & Arctic Horizon... but I can not fix it. By the way, e.g. with openmeta everything works as expected.

Maybe you could have a look & point me into right direction.

Thanks and pls. keep up the excellent work ! :-)

**Comment by drinfernoo** [comment]
Do you have any other add-ons installed? The players won't show up unless you do.

**Comment by sttephan** [comment]
Hi,
Thanks for yr. answer.

Sure I have. That‘s why I was mentioning that e.g. openmeta is showing them. I tried with installing multiple add-ons/players...nothing works. 

Does it work on yr. end with the latest version of tmdbh ?

**Comment by drinfernoo** [comment]
Yes, I can choose and use default and "Play Using" players. Are you using players that match the format shown in the wiki?

**Comment by sttephan** [comment]
Honesty speaking, I have no idea.
I‘m just using the formats that come from bit.ly/openplayers. And for some reason it worked for me as well a few versions of tmdbh ago.

But thanks for confirming that it works in general. I will try digging into the tmdbh wiki...
(don‘t wanna hold up jurialmunkey from working on his beautyful skin :-)

**Comment by drinfernoo** [comment]
> Honesty speaking, I have no idea.
> I‘m just using the formats that come from bit.ly/openplayers. And for some reason it worked for me as well a few versions of tmdbh ago.
> 
> But thanks for confirming that it works in general. I will try digging into the tmdbh wiki...
> (don‘t wanna hold up jurialmunkey from working on his beautyful skin :-)

Those are players made for OpenMeta, which aren't compatible with this add-on. You can try out https://bit.ly/tmdbplayers 😉

**Comment by sttephan** [comment]
Oh my God ! This is what I did differently back then. Thank you so much drinfernoo !
Can somebody please delete my posts, I feel stupid now.... :-)

Take care.

**Comment by uebmaster** [comment]
I have exactly the same issue and I'm using the URL mentioned above https://bit.ly/tmdbplayers

I have installed balandro, palantir 2, Alfa, etc.

And the addon just detect YouTube and upnp.

What I'm doing wrong?

**Comment by drinfernoo** [comment]
@uebmaster That package doesn't include players for any of those add-ons.
