### ISSUE TITLE
[Bug] Fallback Player not working

### ISSUE THREAD

**Issue by shinji95** [jurialmunkey/plugin.video.themoviedb.helper#143]
For some odd reason the Fallback Option in a Player is Not working for me. Adding "fallback": {"play_movie": "youtube.json search_movie"} to my Netflix Player does nothing even with YouTube Setup corectly.
What am i doing wrong?

**Comment by jurialmunkey** [comment]
Are you adding this to the default Netflix player shipped with the plugin (i.e. in `addons/plugin.video.themoviedb.helper/resources/players`) or have you made a copy in the user player folder (i.e. in `userdata/addon_data/plugin.video.themoviedb.helper/players`)

Can you post your Netflix and Youtube player json files?
Also, does your Youtube player work correctly by itself?

**Comment by shinji95** [comment]
I tried both. Added the line to the shipped Player, it didn´t work. Added the line to the version in my player folder and it also didn´t work. the youtube player works fine for me. After trying to play with Netflix it just says "Item not found" and returns to the player selection menu. Here is my netflix player:

{
    "name"              : "Netflix",
    "plugin"            : "plugin.video.xstream",
    "priority"          : 500,
    "assert"            : {
                            "play_movie":       ["title", "year"],
                            "play_episode":     ["showname", "season", "episode"],
                            "search_movie":     ["title"],
                            "search_episode":   ["showname"]
                          },
    "play_movie"        : [
                            "plugin://plugin.video.netflix/directory/search/search/{title}/",
                            {"title": "{title}", "year": "{year}"}
                          ],
    "play_episode"      : [
                            "plugin://plugin.video.netflix/directory/search/search/{showname}/",
                            {"title": "{showname}"},
                            {"season": "{season}"},
                            {"season": "{season}", "episode": "{episode}"}
                          ],
    "search_movie"      : "plugin://plugin.video.netflix/directory/search/search/{title}/",
    "search_episode"    : "plugin://plugin.video.netflix/directory/search/search/{showname}/",
	"fallback": {"play_movie": "youtube.json search_movie"}
}

**Comment by jurialmunkey** [comment]
Why does your netflix player have this?
`"plugin" : "plugin.video.xstream",`

**Comment by shinji95** [comment]
Good Question, think i edited it because the netflix player wasn´t showing up im my list and i tried to change the addon it looks for to something different. Still changing the line to     
"plugin"            : "plugin.video.netflix",
isn´t doing the trick for me. Do you see anything else in this player files, which is wrong? They seem to work well, exept of the fallback option. If not still thank you for your time and your great addon :)

**Comment by jurialmunkey** [comment]
No it looks fine otherwise. However, if you have two versions of the player file, one will overwrite the other. If you have the player file in the addon_data player folder, then you will need to disable the inbuilt players.

I would need a debug log of you attempting to play a video and the fallback not working to tell what is happening.

**Comment by jurialmunkey** [comment]
Hmm actually I reproduce. I'm not quite sure what the issue is yet.

**Comment by jurialmunkey** [comment]
@shinji95 - Can you test latest version? I forgot to account for if there isn't a default player set. This commit should fix the issue.

---
Relevant Commit: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/9f5eede9da03b5db7c71b4d241cc67c6bacda327

**Comment by shinji95** [comment]
Thank you so much, it works like a charm!
You´re the best! :)

**Comment by jurialmunkey** [comment]
Excellent! Thanks for the bug report and testing - I would've missed that otherwise since I have a default player setup.

Also, thanks for pointing out the error in the wiki - I've updated the page
