### ISSUE TITLE
[Question] Player Add

### ISSUE THREAD

**Issue by minixb4286** [jurialmunkey/plugin.video.themoviedb.helper#147]
Hi. jurialmunkey
I asked the creator of the WATCHA add on path. So I applied it to Custom Search and confirmed that it works. I now wanted to add a Player, so I checked the Netflix example and the Player Function. I applied it as follows, but nothing happened.
I applied the Available Keys value one by one, but nothing happened.
I think TMDB and TVDB are not working in WATHCA Add on. I am wondering if I am right.
I wonder if there is a way to add a player in this situation.
It is so enjoyable because of your skin and add on. Thank you always.

`{
    "name"              : "watchaM",
    "plugin"            : "plugin.video.watchaM",
    "priority"          : 500,
    "assert"            : {
                            "play_movie":       ["title"]
                          },	
    "play_movie" 		: 
						  "plugin://plugin.video.watchaM/api_path=-&mode=SEARCH&stype=-&page=1&search_key=/{title}" 
}`

**Comment by jurialmunkey** [comment]
Use `search_movie` instead of `play_movie` if the endpoint produces a list of results.

**Comment by minixb4286** [comment]
I did what I told you, but nothing happens.
When I click Play Using in the Context Menu, the only choices in the Choose Action window are Play winth Netflix, Search Netflix, and Search YouTube. Why is Search WatchaM not displayed?
I am not sure what I am doing wrong.

`{
  "name" : "watchaM",
  "plugin" : "plugin.video.watchaM",
  "priority" : 500,
  "assert" : { "search_movie": ["title"] },
  "search_movie" : "plugin://plugin.video.watchaM/?api_path=-&mode=SEARCH&stype=-&page=1&search_key=/{title}/"
  }`

**Comment by jurialmunkey** [comment]
If the plugin ID doesn't match then it won't display the player.

**Comment by minixb4286** [comment]
I checked the "addon/plugin.video.watchaM/addon.xml" file. I know the addon id is displayed in this file. So I checked and [addon id = "plugin.video.watchaM"] is correct. Am I wrong?
I installed another video addon and created .json file, but the result was exactly the same. I don't know why it doesn't appear in the Choose Action.
If you say install *** video addon and create ***. Json file in the format below, do you mean search *** appears in Choose Action?
I'll try a few more, but I installed another video addon and created .json file, but the result is still the same.
I understand your words correctly, but I don't know why. I am so upset. However, I will continue to try without giving up.

`{
    "name"              : "xxxxx",
    "plugin"            : "plugin.video.xxxxx",
    "priority"          : 200
}`

**Comment by jurialmunkey** [comment]
If the player is not showing either you have put it in the wrong folder or the plugin id does not match.

What folder are you putting the file in?

**Comment by jurialmunkey** [comment]
Also, where is this plugin from, as I can find no mention of it on google at all.

**Comment by jurialmunkey** [comment]
Also, just as an aside, I would never ever trust a python program that uses obfuscated code like this watchaM addon does: https://github.com/kym1088/watchaM-v18/blob/master/resources/lib/watchaCore.py

Who knows what they are trying to hide here...

**Comment by minixb4286** [comment]
The path of the json folder is `C:\Users\XB\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.themoviedb.helper\players`
The plugin ID was also wrong. I checked with the addon creator. Profile is not used.
I tested various other video addons and confirmed that the player displays normally.
I think this problem is whatchaM's path is wrong.
I asked the creators of whatchaM, but replied that I didn't know anything other than what I had told me before.
I studied python for this opportunity. As you said, I noticed a warning that this obfuscation code should be careful.
I haven't solved this problem, but I will study python and apply it by myself. It may take a long time, but it seems to be the best way to solve this problem.

**Comment by drinfernoo** [comment]
@minixb4286 It seems that you just need to find the correct playback path in the add-on, and write a correct player file.

**Comment by minixb4286** [comment]
> @minixb4286 It seems that you just need to find the correct playback path in the add-on, and write a correct player file.

Yes I know.
But what I was wondering is that the path I used works fine in the custom search of skin settings. But I don't know why it doesn't work if I enter the same path in the json file to add the player.

**Comment by jurialmunkey** [comment]
The only reason a player doesn't display in the select dialog is for the following reasons:
The json file is not in the correct folder. 
The plugin id does not match
The plugin is disabled
The assert value is not met
The json file has incorrect syntax


It does not matter if the plugin path is wrong - the player will still display in the select dialog, it will just fail to get results.

**Comment by drinfernoo** [comment]
@minixb4286 The path you need here will be a different path than for a search... that's probably why.

**Comment by jurialmunkey** [comment]
> 
> 
> @minixb4286 The path you need here will be a different path than for a search... that's probably why.

It doesn't matter - they are saying that the player doesn't show in the Player Select dialog. Even if the path is wrong, it will still display in the Player Select dialog it will just fail to retrieve results.

**Comment by jurialmunkey** [comment]
The issue is that the plugin ID in the addon uses a capital letter and Kodi doesn't like capital letters in plugin ID `plugin.video.watchM`

Plugin IDs and folders should all be lowercase.

The WatchaM addon needs to change its directory to
`addons/plugin.video.watcham`

The addons.xml needs to change the addon ID to
`plugin.video.watcham`

And in the player file, the addon ID needs to match
`plugin.video.watcham`

**Comment by minixb4286** [comment]
I changed the plugin ID and changed it in the json file to run it, but it still does not appear in the player. The plugin ID doesn't seem to change this way. The reason is that "twitchab" and "netflixab" are changed in the same way for twitch and netflix addon, and if the original plugin ID "plugin.video.twitch" / "plugin.video.netflix" is used for the json file, twitch and netflix are displayed on the screen. .
I found out by testing various add-ons that this problem is path independent. I checked what you told me one by one.

I tested this with various video addons.
"name": "xxxxx"
"plugin": "plugin.video.xxxxx"
"search_movie": "plugin: //plugin.video.xxxxx"

As you said, the route didn't matter. The normal addon is displayed by the player on the play using screen.

**Comment by jurialmunkey** [comment]
You also need to change the FOLDER name of the addon to be lowercase. Then you need to restart Kodi and RE-ENABLE the addon inside My Addons.

Follow these steps.
1. Change folder name `kodi/addons/plugin.video.watchaM/` to `kodi/addons/plugin.video.watcham/`
2. Inside `kodi/addons/plugin.video.watcham/addon.xml` change `id="plugin.video.watchaM"` to `id="plugin.video.watcham"`
3. In `kodi/userdata/addon_data/plugin.video.themoviedb.helper/players/` change `watchaM.json` to `watcham.json`
4. Inside `watcham.json` change `"plugin" : "plugin.video.watchaM"` to  `"plugin" : "plugin.video.watcham"`
5, Restart Kodi
6. Go to `Addons > My Addons > Video Addons` and enable watchaM addon.
7. The player will now display.

**Comment by minixb4286** [comment]
oh my god !!
I solved all the problems following your instructions
Thank you so much. Text was a problem.
I have a few questions about the tmdb helper add-on, but since it's different, I'll ask again later.
thank you very much. Have a nice day.
