### ISSUE TITLE
[Feature] UpNext Integration

### ISSUE THREAD

**Issue by shinji95** [jurialmunkey/plugin.video.themoviedb.helper#148]
So you think it would be possible to add Support for the UpNext Addon in your addon? Its a script that automaticly plays the next episode of a Season once the current is close to the end. Or is the addon dependent on the chosen player (e.g. Netflix) and not themoviedb Helper? 
Here is a link to the Wiki page of the UpNext Addon: [UpNext Wiki](https://github.com/im85288/service.upnext/wiki/Integration) 

Thank you and have a good day :)

**Comment by jurialmunkey** [comment]
As far as I understand, it depends on the player.
