### ISSUE TITLE
[Request] Hide Trakt Management Options When Trakt is not Authorized

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#15]
It's in the title 😄

**Comment by jurialmunkey** [comment]
They already shouldn't show without auth. I check for whether the auth token has been saved and only show if it is - maybe there's a bug in my code. I'll have a look later today

**Comment by drinfernoo** [comment]
I did notice that you've combined them into a single item on the main context menu, but it still seems to show even without Trakt authorization.

**Comment by jurialmunkey** [comment]
> 
> 
> I did notice that you've combined them into a single item on the main context menu, but it still seems to show even without Trakt authorization.

Oh, I didn't realise you meant in the context menu - I thought you meant in the addon browser.

I'm not sure if it is possible because it needs to be based on xbmc conditional visibility - i.e. I cant run a script *before* the context menu is shown to check whether authorised and I don't think I can check addon settings as an xbmc conditional.

**Comment by drinfernoo** [comment]
I looked a bit at the code, and realized it may be a bit more substantial change, but my proposed solution would be to remove the context menu definitions from `addon.xml`, and simply add context menu items to your `ListItem`s whenever your menus populate. This way, you can control visibility easier (add the item or don't) based on various conditions, like Trakt being authorized 😉

It would essentially just need the endpoints defined, so you can add them by path, rather than calling directly from the script, but there may be other changes that need to be made. I admittedly don't have a ton of experience with custom context menu items 🤣

**Comment by jurialmunkey** [comment]
> 
> 
> I looked a bit at the code, and realized it may be a bit more substantial change, but my proposed solution would be to remove the context menu definitions from `addon.xml`, and simply add context menu items to your `ListItem`s whenever your menus populate. This way, you can control visibility easier (add the item or don't) based on various conditions, like Trakt being authorized 😉
> 
> It would essentially just need the endpoints defined, so you can add them by path, rather than calling directly from the script, but there may be other changes that need to be made. I admittedly don't have a ton of experience with custom context menu items 🤣

I initially did have the context menus this way (i.e. attached to the ListItem itself). However, for some reason Kodi will only show context addon entries on widgets (both home screen and info dialog), and not the ListItem context menu entries - which is a real pain as I most frequently want to add items to my watchlist from widgets, especially since in the addon browser section you don't even need the context menu (you can just do it from the detailed item list).

**Comment by drinfernoo** [comment]
Good call, I forgot that they didn't show on widgets then... Is that because of something in Skin Shortcuts, I assume?

**Comment by jurialmunkey** [comment]
> 
> 
> Good call, I forgot that they didn't show on widgets then... Is that because of something in Skin Shortcuts, I assume?

Nah, it doesn't work even if the widget is hardcoded. It's something in Kodi core.

**Comment by SerpentDrago** [comment]
could you get it so it doesn't' show up on non tmdb helper items at least ? 



        <visible>!String.IsEmpty(ListItem.Property(tmdb_id)) + [String.IsEqual(ListItem.dbtype,episode) | String.IsEqual(ListItem.dbtype,movie) | String.IsEqual(ListItem.dbtype,tvshow)]</visible>

change to 

 <visible>String.StartsWith(ListItem.path,plugin://plugin.video.themoviedb.helper/) + !String.IsEmpty(ListItem.Property(tmdb_id)) + [String.IsEqual(ListItem.dbtype,episode) | String.IsEqual(ListItem.dbtype,movie) | String.IsEqual(ListItem.dbtype,tvshow)]</visible>

or something like that , sorry bit rough and prob did that wrong ?

**Comment by SerpentDrago** [comment]
Also i'd like to add , Jurial , you have been Amazing at adding features and fixing bugs . This addon is shapeing up to be a true replacement for lots of the other addons that are now outdated / have old code / etc . 

And i'd just like to say thank you for doing all this ! 

Have a great new year !

**Comment by SerpentDrago** [comment]
#39 

Thanks @drinfernoo

**Comment by jurialmunkey** [comment]
> 
> 
> could you get it so it doesn't' show up on non tmdb helper items at least ?
> change to
> ` <visible>String.StartsWith(ListItem.path,plugin://plugin.video.themoviedb.helper/) + !String.IsEmpty(ListItem.Property(tmdb_id)) + [String.IsEqual(ListItem.dbtype,episode) | String.IsEqual(ListItem.dbtype,movie) | String.IsEqual(ListItem.dbtype,tvshow)]</visible>`

Works well but see my suggestion here: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/pull/39#issuecomment-569451648

Not sure if my suggestion will work for widgets or not. If it doesn't, then I'll go with your approach.  


>
> 
> OR , split off the context menu to its own addon , thats much more universal with support for most any id type etc etc .
> 

I've been thinking of splitting the plugin up into modules to give a bit more fine grained control i.e. plugin browser / service monitor / context menu 

>
>
>Also i'd like to add , Jurial , you have been Amazing at adding features and fixing bugs . This addon is shapeing up to be a true replacement for lots of the other addons that are now outdated / have old code / etc
>

Thanks! 😁

**Comment by SerpentDrago** [comment]
Looks good ! thanks . This can prob be closed now

**Comment by jurialmunkey** [comment]
> 
> 
> Looks good ! thanks . This can prob be closed now

I've still got the original issue of hiding the options when Trakt hasn't been authorised though... 😉

**Comment by SerpentDrago** [comment]
can you make a viability condition where if x settings in the xml is blank or empty it doesn't show ? after all if your not authorized to trakt , you won't have some settings in the settings.xml filled out ?

**Comment by drinfernoo** [comment]
Unfortunately, there doesn't appear to be a way to check  add-on settings within `addon.xml`, where the visibility conditions are for the context items 🙃

**Comment by jurialmunkey** [comment]
> 
> 
> Unfortunately, there doesn't appear to be a way to check add-on settings within `addon.xml`, where the visibility conditions are for the context items 🙃

Actually, you've both given me an idea 💡 

Maybe I can set something like `Window(Home).Property(TMDbHelper.Trakt.IsAuth)` on startup and/or when auth occurs, and then check against that.

**Comment by jurialmunkey** [comment]
@SerpentDrago @drinfernoo - Can you test my latest commit?

The context menu items should only show if you've authorised Trakt - plugin sets window property `Window(Home).Property(TMDbHelper.TraktIsAuth)` once authorised. 

The property persists until you restart Kodi, so if you somehow deauthorise Trakt after it has been authorised then the context menu items will stay until restart. I don't think it is worth the extra cycles to check for deauthorisation - better to check for authorisation just once on startup or when the user specifically authorises Trakt.
