### ISSUE TITLE
[Question] Players not working...(my paths problem)

### ISSUE THREAD

**Issue by minixb4286** [jurialmunkey/plugin.video.themoviedb.helper#150]
Dear. jurialmunkey
Thanks to your help, I use search_movie and search_episode very well.
But another question arose.
You said that the path of the add-on I was using last time cannot use play_movie. You told me why, but I feel difficult and I don't understand what I mean.

[#147](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/147) 
Use `search_movie` instead of `play_movie` if the endpoint produces a list of results.

So I've read numerous issues and looked closely.
You said "You can re-arrange that so that the search query is at the end and it will still work"
AZ2 [#36](https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/36)

`plugin://plugin.video.twitch/?content=streams&mode=search_results&query=SEARCHTERM&index=0`
`plugin://plugin.video.twitch/?content=streams&mode=search_results&index=0&query=SEARCHTERM`

Is there any way to change the path I'm using like Twitch's example?
Should I ask the producer of the watcham add-on for this problem?
`plugin://plugin.video.watcham/?api_path=-?mode=SEARCH&stype=-&page=1&search_key={title}"`

**Comment by jurialmunkey** [comment]
For play movie to work you need to add steps to find a match in the list of results.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#additional-steps
