### ISSUE TITLE
Trakt colection limit option

### ISSUE THREAD

**Issue by dancaer69** [jurialmunkey/plugin.video.themoviedb.helper#151]
I just found this addon and I wanted to use it but I have a large trakt collection and the 20 per page limit was annoying for me and I didn't use it. But today I tried to find a way to bypass this because I liked it and wanted to use it. To achive this I removed the page and add a limit=300 to params_get item in container.py. 
So, I suggest to have an option to control the limit of items per page there and also the option to remove the limit completely.

**Comment by Demonseeed** [comment]
@jurialmunkey has previously commented on his decision on why the Trakt lists are limited the way they are. 

You can view his reply here:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/34#issuecomment-568242085

Not sure if he will do something different for the Collection, but in case he doesn’t I am linking this so you can understand why.

**Comment by jurialmunkey** [comment]
Yeah sorry see the linked thread above. Overriding the limit like this is a quick way to get my api keys disabled and ruin things for everyone. Please don't do that.
