### ISSUE TITLE
[Bug] UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4'

### ISSUE THREAD

**Issue by Andihawke** [jurialmunkey/plugin.video.themoviedb.helper#152]
hey, on TVShows with special characters in title (e.g. ä, ü, ö...) kodi throws an error. 
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/4456726/kodi.log)

version 2.3.3

**Comment by jurialmunkey** [comment]
Can you test latest version (2.3.4)? It should be fixed now.

**Comment by Andihawke** [comment]
hey jeaaa great!!! can confirm. it works now.
