### ISSUE TITLE
Wrong set information for  custom sets

### ISSUE THREAD

**Issue by DimitarCC** [jurialmunkey/plugin.video.themoviedb.helper#154]
Current the sets information including items count and years range are scrapped only online.
That means it returns count of items that are less or more that really present in the library.
Especially when you have custom set or you have manually added items in the existing set.
For example Star Wars Collection contains 9 movies however lets say i added 2 more to the set (Rouge One and Solo). Now the set contains 11 movies but the info is still 9 movies.
Another example is Indiana Jones Collection TMDB info shows 5 movies, however the last movie is not released yet so i dont have it the collection but it still shows 5 movies when they are actually 4.
I think that is wrong :(

**Comment by jurialmunkey** [comment]
The info displayed is correct. We've already had this discussion. The plugin only displays online info. You need to let this go.
