### ISSUE TITLE
URL not encoded when using {title_url}

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#157]
Hi jurialmunkey.
I run into an issue when using {title_url}. The plugin is expecting the url to be encoded but I'm only getting whitespaces replaced with +.
This is a url created by the addon when used directly (the relevant part is in bold) :

{server}/emby/Users/{userid}/Items?**searchTerm=all%2Bmight**&IncludePeople=false&IncludeMedia=true&IncludeGenres=false&IncludeStudios=false&IncludeArtists=false&IncludeItemTypes=episode&Limit=16&Fields={field_filters}&Recursive=true&EnableTotalRecordCount=false&ImageTypeLimit=1

And this is the url I get when using calling the addon through themoviedb helper:

%7Bserver%7D%2Femby%2FUsers%2F%7Buserid%7D%2FItems%3FIncludeItemTypes%3Depisode%26filters%3DIsNotFolder%26fields%3DMediaStreams%26Recursive%3Dtrue%26ImageTypeLimit%3D1%26Limit%3D16%26**searchTerm%3DAll+Might**

And this is the step I'm using in the player:

"plugin://plugin.video.embycon/?content_type=video&mode=GET_CONTENT&media_type=episodes&url=%7Bserver%7D%2Femby%2FUsers%2F%7Buserid%7D%2FItems%3FIncludeItemTypes%3Depisode%26IncludeMedia%3Dtrue%26filters%3DIsNotFolder%26fields%3DMediaStreams%26Recursive%3Dtrue%26ImageTypeLimit%3D1%26Limit%3D16%26**searchTerm%3D{title_url}"**,

As far as I understand it, there are two things here:

1. Replacing whitespaces with + which is what {title_url} seems to be doing now. From the documentation, I understand it should be {title_+} to get this result.
2. Encoding the url after replacing whitespaces.

Is there anyway to get whitespaces replaced by + and the result encoded?

Thanks.

**Comment by jurialmunkey** [comment]
`{*_url}` uses `quote_plus` encoding which is standard HTML percent encoding for urls
https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote_plus

The `%2B` encoding is NOT space, it is `+`. The encoded value for a space is `%20`. Even if I used the plain `quote` encoding module you wouldn't get `%2B`, you'd get `%20`. 

Basically you are asking for the strings to be double encoded: one pass with `quote_plus` then a second pass with just `quote` - that should never be necessary. The point of encoding is to replace special characters with standard characters - you do that either by encoding or replacing, not both.

Can you try with the latest version. 
`{KEY_url}` will now use quote encoding (`%20` spaces)
`{KEY_url+}` will now use quote_plus encoding (`+` spaces)

If this standard percent encoding of `%20` doesn't work with Emby, then the problem is the Emby addon. The author needs to choose an encoding approach and stick to it.

**Comment by juanma-cvega** [comment]
I'm not sure if it's an issue with the EmbyCon addon, the Emby server or something I don't get from the encoding url standard but the problem I see from testing directly through the Emby UI that calls the Emby server is that it uses + to trigger a strict search. So for instance:
- If I search for "All Might" through the Emby UI (not Kodi), I get 12 results. So basically anything that contains either "All" or "Might"
- If I search for "All+Might" through the Emby UI, I get 2 results, both containing "All Might" within the name.
So for that reason I was asking to get + as the encoded value (%2B). Apparently, just having + in the string doesn't work. It has to be its encoded value (All%2BMight and not All+Might).

**Comment by jurialmunkey** [comment]
Ah okay, that makes much more sense then - it's not because emby addon needs url to have spaces encoded as plus- it's that replacing with plus provides AND keyword searching (whereas space is OR keyword search).

I'll have a look at what I can do.

**Comment by jurialmunkey** [comment]
@juanma-cvega - Okay I've added `{KEY_url_escaped+}`
That will replace spaces with `+` and then percent encode the string. So `{title_url_escaped+}` should work for your purposes.

**Comment by juanma-cvega** [comment]
Hi, I tested the new feature and it works... but apparently the problem came from Embycon in this case. The URL is being decoded in the addon and it ends up sending "+" instead of "%2B" no matter what I send. I ended up adding some code myself to the Embycon addon. I created a pull request hoping for the author to accept it if he sees no problems with it  as he closed the repository and now no one seems to be able to create issues.

**Comment by juanma-cvega** [comment]
The author of Embycon replied to my pull request suggesting the problem comes from the searchTerm needing to be encoded twice. He gave me an example of what it should look like.

%7Bserver%7D/emby/Users/%7Buserid%7D/Items%3F**searchTerm%3DAll%252BMight**%26IncludeItemTypes%3Depisode%26IncludeMedia%3Dtrue%26filters%3DIsNotFolder%26fields%3DMediaStreams%26Recursive%3Dtrue%26ImageTypeLimit%3D1%26Limit%3D16

This is the code that produces that

```
import urllib

search_txt = "All+Might"
search_txt = urllib.quote(search_txt)
print search_txt + "\r\n"

url = "{server}/emby/Users/{userid}/Items?searchTerm=" + search_txt + "&IncludeItemTypes=episode&IncludeMedia=true&filters=IsNotFolder&fields=MediaStreams&Recursive=true&ImageTypeLimit=1&Limit=16"

final_url = urllib.quote(url)
print final_url + "\r\n"

unquoted = urllib.unquote(final_url)
print unquoted + "\r\n"
```

Do you think that's feasible?

**Comment by juanma-cvega** [comment]
I just encountered another similar one. There is an episode called "Boy meets...". The Emby server is expecting "Boy%2BMeets%E2%80%A6" but without the double encoding, the addon ends up sending "Boy+Meets…".

**Comment by jurialmunkey** [comment]
URLs shouldn't need to be double encoded. Sounds like bad encoding/decoding handling on the EmbyCon side of things to me.

**Comment by juanma-cvega** [comment]
I guess the logic is that the addon expects the url parameter encoded for itself but then the search string requires to also be encoded for the Emby server. Which, as you said, seems weird to me as the Embycon addon could extract the search string and rencoded itself if that's what the server is expecting. But I don't know if I'm going to be able to convince the developer to merge anything on his side. I'll try to encode the whole search string myself instead of just the '+' and push again to see what he says. From your side you don't see any meaning on doing it, right?

**Comment by juanma-cvega** [comment]
Thinking about it, it could make sense actually. His plugin is creating a url that contains a search value that needs to be passed encoded, so it creates it that way. But then the plugin is called from an external addon so it's expecting some arguments and then a url to invoke. The url is sent encoded and then decoded by the addon to call the Emby server as if it was generated by the addon itself. But the part that needs to be sent to the Emby server gets decoded as well as part of the process so, in order for it to remain encoded, it needs to be encoded twice. Does it make sense?

**Comment by jurialmunkey** [comment]
I suspect that is what is happening in the EmbyCon addon but it's still poor encoding/decoding handling. 

> Which, as you said, seems weird to me as the Embycon addon could extract the search string and rencoded itself if that's what the server is expecting.

This is exactly my point. The whole message should only be encoded once. Then EmbyCon decodes it, does whatever additional actions are needed, then encodes the resulting message into the format that Emby expects.

> But I don't know if I'm going to be able to convince the developer to merge anything on his side. 

I suspect this much as well. As much as I think it is the wrong way to do things, it's not a hill worth dying on - so I'll just implement double encoded strings on my side. 

And anyway, really TMDbHelper players are just hacks attempting to wrangle various addons into doing what we want. To do things "properly" would require a standardized language for interfacing between addons, and I don't really see that happening.

Okay, so now:

| Key | Meaning |
| :--- |  :--- |
| `{KEY_escaped}` | quote(quote(KEY)) - i.e. `%2520` spaces |
| `{KEY_escaped+}` | quote(quote_plus(KEY)) - i.e. `%252B` spaces |
| `{KEY_url}` | quote(KEY) - i.e. `%20` spaces |
| `{KEY_url+}` | quote_plus(KEY) - i.e. `%2B` spaces |

I removed `{KEY_url_escaped+}` 
The new version of `{KEY_escaped+}` should serve that purpose now.

I also changed how `{KEY_escaped}` and `{KEY_escaped+}` function. Originally these followed what OpenMeta does - i.e. replace spaces with double escaped characters. However, after this whole discussion, I'm now thinking that `_escaped`/`_escaped+` were added to support addons like EmbyCon and the OpenMeta author didn't know how to encode strings properly.

**Comment by juanma-cvega** [comment]
Ok, thanks for adding it! I'll give it a try once I get the time.
