### ISSUE TITLE
Disable (or reduce priority) of local library player

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/plugin.video.themoviedb.helper#158]
I have Netflix set as my default player and I want that to take priority over everything else (even local library content).

Currently even with it set as default it still prioritises local library content if it finds it (including other addons that use library integration).

Is there any easy way for me to set it so that Netflix truly is the default player even at the expense of the local library content? (and it only moves onto local library if not found on netflix)

(I have tried messing around with priorities in player files but cannae get them to prioritise over local library as of yet)

**Comment by jurialmunkey** [comment]
In latest version I've added an option:
`TMDbHelper Settings > Players > Prioritise local files (disable)`

Disabling that option will stop the default players from playing local files.
