### ISSUE TITLE
[Request] better folder browser for library location setting

### ISSUE THREAD

**Issue by shivaism** [jurialmunkey/plugin.video.themoviedb.helper#159]
I'd like to host my TMDB Helper library folders on external storage (USB or NAS), but the file browser limits me to local storage and the SMB/NFS browsers that don't work

Any chance we can use the same file browser/folder picker as Kodi's media library settings (or File Manager)? Those let me, for instance, type out the network address manually

**Comment by drinfernoo** [comment]
I had initially thought this was using `xbmcgui.Dialog().browse(...)` to do this, but it appears it's being done as a `folder` setting. However, it doesn't seem that I'm able to see anything besides my local drives and SMB/NFS using any of the values [listed for](https://kodi.wiki/view/Add-on_settings#type.3D.22folder.22) `source`... Not even sources added through the file manager, local or otherwise.

**Comment by jurialmunkey** [comment]
Yeah sounds like a Kodi bug. Not much I can do about it - that's the only method available to browse a folder inside addon settings.

**Comment by drinfernoo** [comment]
@jurialmunkey We *could* make it call out to an action and browse from Python 😉 May be more trouble, though.

**Comment by jurialmunkey** [comment]
@drinfernoo - But why would xbmcgui.Dialog().browse() be any different? Pretty sure the settings uses the same method. The options for the settings dialog all correlate with the args for that method:
https://codedocs.xyz/AlwinEsch/kodi/group__python___dialog.html#ga3a3b4ef3f55a926aea5e81d7620a6174

Unless you're suggesting we create our own scripted gui file browser? No really a path I think I want to go down...

**Comment by jurialmunkey** [comment]
@drinfernoo - Also, when you tested the `source=""` tag, did you try `source="files"`? That should give file manager sources?

**Comment by jurialmunkey** [comment]
Actually... I think I've found a fix.

@drinfernoo @shivaism - Can you test latest. It should now show all your video sources. So if you go into videos and create the source first, then you should be able to go into tmdbhelper settings and now select that source.

**Comment by drinfernoo** [comment]
I did try `source="files"`, and if I I'm remembering correctly, it didn't work either. I have used it before in Python, however, and it seems to work fine there.

**Comment by jurialmunkey** [comment]
> 
> 
> I did try `source="files"`, and if I I'm remembering correctly, it didn't work either. I have used it before in Python, however, and it seems to work fine there.

Yeah I just tried it - seems to only show local sources which is odd. Maybe it isn't setting it correctly.

Anyway I think pointing at Video sources should work, as long as you create the actual source first and then select it in TMDbHelper.

**Comment by shivaism** [comment]
Thanks for this, I'll test it out when I get a chance. Pointing at video
sources is a good solution because one of the key benefits of TMDb Helper
for me is being the "single source of truth" for my video content (local as
well as online)
