### ISSUE TITLE
[Request] Proper Icons in Sections

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#16]
In the section for a movie or TV show, it would be really nice if the various options had a simple icon of their own, rather than using the exact same artwork from the selected item on every line.

The current solution, in any view besides List, is just a bunch of the same artwork over and over again, which is a bit monotonous.

**Comment by jurialmunkey** [comment]
Haha I actually had this exact same thought yesterday! I started working on some icons in a local branch yesterday and hopefully will have something ready in the next few days.

**Comment by jurialmunkey** [comment]
Finally got around to adding icons! https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/2b1497767ea8375691c9bf5933a0520b03a0dbdb
