### ISSUE TITLE
xStream Player Integration

### ISSUE THREAD

**Issue by SaLii05** [jurialmunkey/plugin.video.themoviedb.helper#160]
Hello friends, I have a question.  I'm trying to integrate the German player xStream into the add-on TheMoviedb.  I also put the xStream.json in the player folder.  Unfortunately, he does not find the player.

This is what my json file looks like:

{
"name"         : "Abspielen mit xStream",
"repository"   : "repository.xstream",
"plugin"       : "plugin.video.xstream",
"priority"     : 500,
"id"           : "search.xstream",
"filters"      : {},
"postprocess"  : "",
"movies"       : [
  [
   {
    "link"      : "plugin://plugin.video.xstream/?function=globalSearch&params=0&site=globalSearch&title=Global%20Suche&searchterm={title}",
    "steps"     : 
	[".*"],
    "action"    : "PLAY"
   }
  ]
 ],
"tvshows"      : [
  [
   {
    "link"      : "plugin://plugin.video.xstream/?function=globalSearch&params=0&site=globalSearch&title=Global%20Suche&searchterm={showname}",
   "steps"     : [
    "{showname}.*"
    ],
    "action"    : "PLAY"
   }
  ]
 ],
"musicvideos"  : [],

"music"        : [],

"live"         : []

}

Maybe someone will find the mistake or what I'm doing wrong.  It works in other addons like OpenMeta.

**Comment by jurialmunkey** [comment]
This addon is not OpenMeta. The player file needs to be configured differently.

Read the wiki:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

**Comment by SaLii05** [comment]
Thank You very much ☺️

is that maybe right ? 


{
    "name"              : "Abspielen mit xStream",
    "plugin"            : "plugin.video.xstream",
    "play_movie"        : [
                            "plugin://plugin.video.xstream/?function=globalSearch&params=0&site=globalSearch&title=Global%20Suche&searchterm={title}",
                          ],
    "play_episode"      : [
                            "plugin://plugin.video.xstream/?function=globalSearch&params=0&site=globalSearch&title=Global%20Suche&searchterm={showname}",          
                          ],
    "search_movie"      : "plugin://plugin.video.xstream/?function=globalSearch&params=0&site=globalSearch&title=Global%20Suche&searchterm={title}",
    "search_episode"    : "plugin://plugin.video.xstream/?function=globalSearch&params=0&site=globalSearch&title=Global%20Suche&searchterm={showname}"
}


I'm a little inexperienced with this and I really want to use your addon. can that work?  so am i on the right way?

**Comment by jurialmunkey** [comment]
Yeah that's looking correct. I would expect that search_movie search_episode methods will work correctly. 

Main issue I can see is the play_movie and play_episode you need an additional step within the square brackets to try to find the matching item. See the info here:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#additional-steps

Best thing to do is put it in the players folder and test it out then tweak it as needed.

**Comment by SaLii05** [comment]
Since the last update, he has not played the films when I have the addon as a widget.

**Comment by drinfernoo** [comment]
@SaLii05 Then that means something is wrong with your player file.

**Comment by SaLii05** [comment]
Yeah. But before the update, it works.

**Comment by SaLii05** [comment]
That’s my player file. 
Tv shows are working. 


{
    "name"              : "xStream",
    "plugin"            : "plugin.video.xstream",
    "search_movie"      : "plugin://plugin.video.xstream/?function=globalSearch&params=0&site=globalSearch&title=Global%20Suche&searchterm={title}",
    "search_episode"    : "plugin://plugin.video.xstream/?function=globalSearch&params=0&site=globalSearch&title=Global%20Suche&searchterm={showname}"
}

Maybe you can see what’s wrong with them

**Comment by SaLii05** [comment]
So. I have installed a older version (2.0.18) and with them I can play movie directly from widget. 
With version 2.4.4. it doesn’t work

**Comment by jurialmunkey** [comment]
Debug log?

**Comment by SaLii05** [comment]
Sorry. But. Where can I find the log ? 
I have activate it in the settings. Where is the log file ?

**Comment by jurialmunkey** [comment]
https://kodi.wiki/view/Log_file/Easy#Copy_and_Paste

**Comment by jurialmunkey** [comment]
@SaLii05 - Actually I was able to reproduce and I think I've fixed the bug. Seems the busy dialog was blocking Kodi from opening the search path for some strange reason. 

Can you test latest version (2.4.12) and confirm that it is now working?

**Comment by SaLii05** [comment]
I tested it with the v2.4.13 and it works perfekt. Thank your very much. 

And that jurialmunkey repo alpha. Where themoviedb helper 2.4.4 available is. Is that your actually repo ?

**Comment by jurialmunkey** [comment]
Yes, that's my Kodi repo -- @drinfernoo maintains and updates it from my github repos.

**Comment by SaLii05** [comment]
@jurialmunkey are you from Germany ?

**Comment by jurialmunkey** [comment]
No. I'm an Aussie.
