### ISSUE TITLE
Popular Lists not sorted by Movie or TV

### ISSUE THREAD

**Issue by JohnatStile** [jurialmunkey/plugin.video.themoviedb.helper#162]
Hi,

I have noticed that the Popular Lists in the addon is not sorted by movie or tv. For example if I go into movies and click Popular Lists both Movie and TV lists appear, visa versa for TV.

Is it possible to have this sorted correctly?

Thanks.

**Comment by jurialmunkey** [comment]
What do you mean "sorted" correctly? Trakt lists don't have a content type - there's no way to differentiate whether they contain movies, tvshows, or both.

**Comment by JohnatStile** [comment]
Hi thanks for the reply. No worries, I mistakenly assumed there was content type for trakt lists.
