### ISSUE TITLE
[Request] Pass information from one step to other as variables

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#164]
The API of the Emby server accepts a "ParentId" parameter as part of a search request. The problem is that this id is Emby's so there is no provider to fetch the information from. 
When searching by episode name, if the only thing available is the name, there is the risk of finding different shows with the same or partially the same name (Pilot episode comes to mind). TV shows are easier to match by name or TMDB id in contrast with episodes so the idea would be to first make a request to find this Emby id to then use it later. The steps would be like:
1. Navigate to the episode in TheMovieDB Helper addon.
2. Use a search player.
3. The player would first have a step that makes a request. 
4. The response is put into a variable that can be accessed later.
5. The player would execute the next of the player that would access this variable to fill the required information. 

Do you think this would be feasible or would it be too much work?

**Comment by jurialmunkey** [comment]
This sounds like an overly complicated approach.

Why can't you search by tvshow name and then use a step which combines season and episode numbers to match the correct episode?

**Comment by juanma-cvega** [comment]
Yes, I know it seems quite complicated. To be honest, this is for specific cases, specially anime. 
The reason why I would like to try fetching information from a previous step is because I trigger the search player when the play one, that's using a provider ID, didn't find anything. In anime, the main reason why this happens is because the Emby server uses TVDB information and the addon hasn't been able to find it based on the TMDB one. And this is mostly because seasons are handled differently in both providers for some tv shows. So using steps here wouldn't work. In this situations I'm forced to search by episode name but it may find episodes from other series containing the search string I passed. I've already been able to improve it by passing the year in the query as the Emby API supports it. By providing the tv show Emby ID I'd be able to narrow down the search further. But as you mention is quite a development to do for specific cases.

**Comment by jurialmunkey** [comment]
Okay that makes sense about episode numbers not syncing. 

Although, couldn't you just check the episode against showtitle as well as the episode name to make sure that you're getting the correct tvshow?

e.g. in the step where you check for episodes:
`{"showtitle": "{showname}", "title": "{title}"}`

Another option is to check `"firstaired"` or `"premiered"` against `"{released}"` or `"{premiered}"`

I really need to add what fields exist to check against to the wiki - for reference, these fields can be checked against: "title", "year", "originaltitle", "premiered", "firstaired", "season", "episode", "showtitle", "file"

**Comment by juanma-cvega** [comment]
I already tried passing showname but it doesn't work. It doesn't match with the TV show in the name. Either you search by episode or by TV show but both together finds nothing. 

> Another option is to check "premiered": "{premiered}" or "firstaired": "{released}"

I just tested with `premiered` and it seems to work! At least the ones I tested it was able to find the right episode. How accurate is the premiered date when compared between providers? The Emby API accepts `MaxPremiereDate` and `MinPremiereDate` and I currently use the same value for both but I don't know if it makes sense to add a buffer there.

**Comment by jurialmunkey** [comment]
It's strange that matching showtitle in the second step of the player wouldn't work. I find it odd that emby would return a list of episodes with the tvshow title being empty.

BTW I'm not saying to use showname and episode name together in the search query - I'm saying to use it in the second step of the action that looks for a matching item.

**Comment by juanma-cvega** [comment]
Sorry, I think I misunderstood you. So basically you are saying that, once I get the list of results, I use a second step to refine the search by filtering by TV show name. I'm not sure I know what to match the showname against, I guess that depends on what Embycon exposes and with what schema, but I'll take a look

**Comment by jurialmunkey** [comment]
It doesn't matter what Embycon exposes - the info labels are standardised by Kodi's JSON-RPC method.

You would do this:
```
"search_movie"        : [
                        "plugin://plugin.video.embycon/?however-you-search-query={showname}",
                        {"showtitle": "{showname}", "title": "{title}"}
                      ],
```

In the above, obviously you need to replace the plugin:// path with whatever the embycon search path is.

Basically what is happening in the above:
1. TMDbHelper calls that plugin directory and it retrieves a virtual list of results just like if you had passed that path directly to "search_episode"
2. In the second step, TMDbHelper looks for an item in that list that has a showtitle which matches the `{showname}` key AND has a title that matches the `{title}` key. If it finds a match it will play it.

Basically in the second step what happens is Kodi's JSON-RPC retrieves a series of properties about each item in the list (e.g. title, season, episode, showtitle, premiered, file). Then TMDbHelper tries to match with whatever the string is after the colon `:`

Just to give an example of how it works, we could also hardcode something if we wanted - e.g. `{"title": "The Terminator"}`

We can also use regex 
e.g. `{"title": "The Terminator|Terminator 2|.*Dark Fate"}`
Will match any of the following titles: "The Terminator", "Terminator 2: Judgement Day" and "Terminator: Dark Fate". (Pipe `|` is OR in regex and  `.*` is wildcard).

With that in mind, we can do some interesting things.
e.g. we can match title to the title or the showname: `{"title": "{title}|{showname}"}`

Or say we get a list where titles are sometimes in the format `001. Showname - S01E01 - Title`
`{"title": ".*{showname}.*S.*{season}E.*{episode}.*{title}"}`

**Comment by jurialmunkey** [comment]
TMDbHelper is not doing anything tricky with these things - it is basically the exact same thing as if you had manually opened the search up in kodi yourself and then clicked on items. Each step is a click through an item - the step just tells TMDbHelper which item to click on. We're just telling it "When you open the folder, look for the item that has a title that looks like this or a season number that matches this one" etc.

**Comment by juanma-cvega** [comment]
Ok, I get what you mean. I could use that to filter but I have another problem now that I would like to get your opinion about. The mismatch TVDB to TMDB is a pain, specially for anime. You would expect names to be the same but that's not the case. I've been testing the TV show "Bleach" and there are plenty of episodes where the name has the same meaning but using different words. I don't know if this is because of them using different translations from Japanese or what. Anyway, my problem now is that, even though your solution will probably work, it depends on the name being the same. I've tested the Emby API using `{premiere}` without a name to find a match and it works but only when I give it the ParentId so it's able to find the right episode from the list from a specific TV show (it returns information about every single episode for the specific ParentId which is quite a lot of information). I've been trying to find another solution without luck. Any ideas?

**Comment by jurialmunkey** [comment]
What about checking against episode firstaired in the second step instead?
e.g. a step like:
`{"showtitle": "{showname}", "firstaired": "{firstaired}"}`

There's still the same issue if the info diverges between TMDb and TVDb - but at least firstaired isn't up to interpretation - there is only one "correct" answer. Checking Dragon Ball and Bleach on both services, it looks like firstaired episode dates match despite season/episode/title diverging.

**Comment by juanma-cvega** [comment]
What's the difference between `firstaired` and `premiered`? The Emby API lets you use `premiered` and so far the tests I've done with it where correct even for TV shows like bleach with different names. Using `premiered` I can leave it in one step and safe some bandwidth as the Emby server only sends the right one. 
For the problem of TV shows, I'll try to convince the author of the EmbyCon addon to add the option to do first a search for the TV show to get the ParentalID and then the search for the episode. I cannot come up with a better solution to overcome the naming problem. If he doesn't like the idea I may fork it and modify it for my use case as I would like Emby to be the main source of TV shows for me.

**Comment by jurialmunkey** [comment]
There's no difference between `{premiered}` and `{firstaired}` keys - they're both the date the episode aired as specified by TMDb.

There is, however, sometimes a difference between "premiered" and "firstaired" info when retrieving a list of episodes from an addon/library. In some addons the values are the same - but for others premiered will be the date the *tvshow* started; whereas firstaired will be the date the episode aired.

**Comment by juanma-cvega** [comment]
Well, Emby seems to use `years` for the year the TV show started and `premiered` for airing date so I'll leave the player as is. I think this can be closed as the main reason the issue was created for won't be added.
