### ISSUE TITLE
[Bug] Cannot edit submenu with disabled item in it

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/plugin.video.themoviedb.helper#165]
At some point the settings layout changed from 2 column to 3 column style.

Now have a problem where for one of my submenus the first item was disabled.

I now cant edit that menu, I'm trapped top left and cannot move the cursor anywhere....

![041320221420](https://user-images.githubusercontent.com/25871666/79162181-bca9ba00-7dd4-11ea-9554-8ce3504bba0a.png)

It only happens if you disable the first item in the menu (that I can tell)

(Workaround: I switched to Artic Zephyr 2, which has traditionally two column settings and was able to enable that item, switch back to AH afterwards - am i alone in hating the three column settings setup?)

On a related note. Also noticed, if you disable a widget, then all widgets below it in the list break.

**Comment by jurialmunkey** [comment]
This is not related to tmdbhelper at all. Also it has already been fixed.

**Comment by dm2912** [comment]
Oh my bad.. doing too many things at once, didnt check what  git i was in lol
