### ISSUE TITLE
TV Show "Add to Kodi Library" Crashes Kodi

### ISSUE THREAD

**Issue by brentonv** [jurialmunkey/plugin.video.themoviedb.helper#166]
Hi there. I just noticed adding TV shows to Kodi Library from TMDBhelper and widgets is crashing Kodi but it works fine on movies. After crash the TV shows folder contains the .nfo file but is missing the .strm file. I'm on Kodi 18.6 (Xbox) and will also test shortly on Android and post back. Logfile for crash is at https://paste.kodi.tv/paqukebezu .Thanks

**Comment by jurialmunkey** [comment]
I can't recreate this issue.

What widget are you using, what tvshow are you trying to add, and what language do you have set in TMDbHelper?

**Comment by brentonv** [comment]
It's any TV show in both the add-on directly or from widget. By the way I'm using your fabulous AZ2 skin. The widgets were Trakt list garycrawfordgc new-shows and also trakt_history tv. Don't think it matters what widget it seems to be any TV show. I've turned on both debug logs. Here's the latest https://paste.kodi.tv/zulixacamo

**Comment by brentonv** [comment]
I'll try turning off flatten seasons and also let it sit idle for a while before triggering crash so there's no startup activity mixed into the log.

**Comment by brentonv** [comment]
I tried on Android and same thing. But just tested Xbox with flatten seasons turned off and it worked fine? I'll turn it back on again and confirm crash.

**Comment by brentonv** [comment]
Yeah so crash confirmed on both Xbox and Android when TV show "Add to Kodi Library" is used when "Flatten Seasons" is enabled.

I let the system idle for a while before reproducing crash but then log was too big for Kodi paste so here it is on my Google drive. Thanks for looking into it mate.

https://drive.google.com/file/d/1eLuiOZnzZEIuKMLtzjAg-ZV4OdpR_Sc1/view?usp=drivesdk

**Comment by jurialmunkey** [comment]
I still can't reproduce the crash but the flatseasons thing is a good clue. Can you test latest version? Hopefully the cause is what I think it is.

**Comment by brentonv** [comment]
I'm away for the system I'll get back to you tomorrow. Thankyou

**Comment by brentonv** [comment]
Hi @jurialmunkey I updated from 2.4.13 to 2.4.14 and no more crash. Thanks mate!

**Comment by brentonv** [comment]
By the way where do you post change logs for both TMDBhelper and Arctic Zephyr 2 so I can keep up with your changes. Thanks

**Comment by jurialmunkey** [comment]
You can see the changes in the release page for Zephyr
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases

Though I haven't made many updates in a while since I've been largely working on TMDbHelper and Arctic Horizon.
