### ISSUE TITLE
[bug] player is strange

### ISSUE THREAD

**Issue by minixb4286** [jurialmunkey/plugin.video.themoviedb.helper#167]
Dear, jurialmunkey
Tested with the last updated version.
There is a problem with the player function.
I am using the same path, it works fine in global search, but the player returns a different value.
No matter what keyword you use, the returned value will be the same.
I checked it by setting it as below to test this correctly.
I have set and tested TMDB movies to be searched in the global search widget. Search results are normal. I searched for "deadpool" movies and "Chernobyl" TV shows and tried play watcham one after the other. However, the results returned were entirely different TV shows. Watcham has "deadpool, chernobyl" content and it works fine when searching by global search.
I don't remember what version it was, but it worked fine before the update.

{
  "name"         : "watcha",	
  "plugin"        : "plugin.video.watcham",					  
  "play_movie": [
                          "plugin://plugin.video.watcham/?api_path=-&mode=SEARCH&stype=-&page=1&search_key={title}",
                           {"dialog": "True"}
                         ],
"play_episode": [
                           "plugin://plugin.video.watcham/?api_path=-&mode=SEARCH&stype=-&page=1&search_key={showname}",
                            {"dialog": "True"}
                          ]
}

[kodi.log.save.txt]

(https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/4475981/kodi.log.save.txt)

**Comment by jurialmunkey** [comment]
Please try latest version. Hopefully that will fix the issue.

**Comment by minixb4286** [comment]
Solved.
Thank you.

**Comment by jurialmunkey** [comment]
Thanks for the bug report and confirming the fix works! 😁
