### ISSUE TITLE
[Bug] Player Fallback not working

### ISSUE THREAD

**Issue by prateek33** [jurialmunkey/plugin.video.themoviedb.helper#171]
I tried the exact same line as mentioned in wiki:
"fallback": {"play_movie": "youtube.json search_movie"}

Added it to the netflix.json and then chose a movie which I know is not present in netflix. I saw the error notification - couldn't find movie as expected and then instead of opening youtube search, it just popped the select player window.

**Comment by jurialmunkey** [comment]
Can you post the full player file. Plus a debug log with debug logging enabled in TMDbHelper and Kodi, and post to a paste site like pastebin/hastebin.

**Comment by prateek33** [comment]
Kodi Log - https://pastebin.com/hDEdKQfs
Netlix Player File - https://pastebin.com/WjjsXxVY
Youtube Player File - https://pastebin.com/NiD5XihC

**Comment by prateek33** [comment]
I tried with different players like fallback to seren in netflix and fallback to netflix in seren. None of them worked for me

**Comment by jurialmunkey** [comment]
That Netflix player file is working correctly for me with the fallback. I choose "Play with Netflix" on a movie not in Netflix and I get list of Youtube search results.

Can you download the latest version (v2.4.29) and get me a fresh log with logging turned on in TMDbHelper (no need for kodi logging - just TMDbHelper). I've added some additional logging to try to see what the issue might be.

**Comment by prateek33** [comment]
figured out what was wrong after you added the logs. I had to turn off use bundled Netflix and Youtube player. Now it works as expected. Thanks a ton for your help @jurialmunkey :)
