### ISSUE TITLE
[Question] Provider IDs not matching TMDB ones

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#174]
I'm trying to make work the TV show saint seiya the hades chapter through its TVDB id. TMDB doesn't have the TVDB ids so I added them to one of the seasons to see if that way I could then fetch it and use it through a player. But then I saw in the logs the ID of the episode used is different from the one I set so I was wondering where this ID came from. 
For more information, in TVDB the TV show is Saint seiya, season 4, episode 1. But in TMBD the show is Saint Seiya the hades chapter, season 1, episode 1 so I don't know if this mix of show names and seasons may be the cause of the issue. At least on TheMovieDB Helper I can see the episode information and thumb so based on that, I guess it shouldn't have any problem finding the right external providers ids for the episode as it has its TMDB ID. 

This is the url of the episode I tested. The ID I set is 96050 and the TV show ID is 67199.
https://www.themoviedb.org/tv/67199-saint-seiya-saga-de-hades/season/1/episode/1/edit?active_nav_item=external_ids&language=en-US

And here are the logs from TheMovieDB Helper and Embycon with the IDs the player passes on. For the episode, the TVDB ID it uses is 7107700 instead. I tried verifying whether at least the TMDB ID for the episode is right but I haven't been able to find it on the page of the episode so I don't know if I need to use the API to get it. The TMDB ID it uses is 1209377.

2020-04-18 10:31:48.619 T:123145502625792  NOTICE: [plugin.video.themoviedb.helper] Container -- Attempting to Play Item...: {u'info': u'play', u'episode': u'1', u'tmdb_id': u'67199', u'season': u'1', u'type': u'episode', u'nextpage': u'True'}
                                            
2020-04-18 10:31:50.038 T:123145502625792  NOTICE: EmbyCon.resources.lib.downloadutils|DEBUG|After: https://emby2.supedup.ga:443/emby/Users/c45eb99a569f4b599c3bddbf548d465c/Items?IncludeItemTypes=episode&filters=IsNotFolder&fields=MediaStreams&Recursive=true&ImageTypeLimit=1&Limit=16&Years=2002&AnyProviderIdEquals=**tvdb.7107700**,imdb.None,tmdb.1209377,trakt.3449717

**Comment by jurialmunkey** [comment]
Trakt provides all the episode IDs. Looks like it is wrong in Trakt.

This is what Trakt is returning - it's getting the right episode as evidenced by the Title, just the IDs are wrong:

```python
{
    u'number_abs': None,
    u'rating': 7.0,
    u'votes': 1,
    u'available_translations': [
        u'en',
        u'es',
        u'fr',
        u'it',
        u'ja',
        u'pt',
        u'zh',
        ],
    u'title': u'The Start of a New Holy War',
    u'updated_at': u'2020-04-16T21:47:16.000Z',
    u'season': 1,
    u'first_aired': u'2002-11-08T15:00:00.000Z',
    u'ids': {
        u'tvdb': 7107700,
        u'tmdb': 1209377,
        u'imdb': None,
        u'tvrage': 0,
        u'trakt': 3449717,
        },
    u'number': 1,
    u'comment_count': 0,
    u'overview': u'''In the Five Peaks, Dohko has a vision in which Athena is beheaded by Hades. At that moment he realizes that the day has finally come when Hades and his 108 Specters will return to Earth.\r
\r
In the Sanctuary, M\u016b finds that several Knights have revived by the power of Hades in exchange for bringing the head of Athena. Among them, Death Mask of Cancer and Aphrodite of Pisces are the first to fight, along with a mysterious third Knight that is capable of destroying the incredible defense of M\u016b.''',
    u'runtime': 25,
    }
```

**Comment by jurialmunkey** [comment]
Yep looks like the TVDB ID is wrong on the Trakt page (button on left side down the bottom)
https://trakt.tv/shows/saint-seiya-the-hades-chapter-2002/seasons/1/episodes/1

I'm not sure where they're getting that ID from though as it isn't on TMDb or TVDb.

**Comment by jurialmunkey** [comment]
I just changed things in the player to preference the data already available on TMDb over the Trakt data - it will only use Trakt to fill in any empty info (before I was relying on Trakt for all Episode IDs). Probably better this way anyway as TMDb is easier to edit and the Trakt data is just a combo of TMDb and TVDb data.

Can you test latest and make sure it is working now?

**Comment by juanma-cvega** [comment]
Ok, thanks for that! That means the fun I had yesterday adding TVDB ids to one of the seasons may have some use in the end 😄 . I'm trying to update the addon but I'm getting this error every time.
2020-04-18 14:04:19.801 T:123145444585472   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'plugin.video.themoviedb.helper'.
                                            Traceback (most recent call last):
                                              File "/Users/juan/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/plugin.py", line 11, in <module>
                                                Container().router()
                                              File "/Users/juan/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/container.py", line 23, in __init__
                                                super(Container, self).__init__()
                                              File "/Users/juan/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/plugin.py", line 36, in __init__
                                                append_to_response=APPEND_TO_RESPONSE, mpaa_prefix=mpaa_prefix)
                                              File "/Users/juan/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/tmdb.py", line 17, in __init__
                                                req_api_key='api_key=a07324c669cac4d96789197134ce272b')
                                              File "/Users/juan/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/requestapi.py", line 24, in __init__
                                                self.addon = xbmcaddon.Addon(self.addon_name)
                                            RuntimeError: Unknown addon id 'plugin.video.themoviedb.helper'.

**Comment by juanma-cvega** [comment]
Nevermind the last comment, I finally was able to install. But I'm still seing the wrong IDs.

`2020-04-18 14:10:53.103 T:123145462882304  NOTICE: EmbyCon.resources.lib.downloadutils|DEBUG|Before: {server}/emby/Users/{userid}/Items?IncludeItemTypes=episode&filters=IsNotFolder&fields=MediaStreams&Recursive=true&ImageTypeLimit=1&Limit=16&Years=2002&AnyProviderIdEquals=tvdb.7107700,imdb.None,tmdb.1209377,trakt.3449717`

**Comment by jurialmunkey** [comment]
@juanma-cvega Are you sure you updated properly. I'm not getting those IDs for that episode.

These are the details I'm getting in the player keys:
```python
{
    'epimdb': None,
    'tmdb': '67199',
    'imdb': u'tt0805448',
    'eptmdb': 1209377,
    'year': u'2002',
    'id': 350828,
    'showname': u'Saint Seiya: The Hades Chapter',
    'title': u'The Start of a New Holy War',
    'fanart': u'https://image.tmdb.org/t/p/original/v7v89HBEx80JWFRdsWhj9Iukp4T.jpg',
    'clearname': u'Saint Seiya: The Hades Chapter',
    'trakt': 145848,
    'season': '1',
    'epid': 96050,
    'thumbnail': u'https://image.tmdb.org/t/p/original/dkRONeqEpjIcPyXdKQDG72aNyl6.jpg',
    'tmdb_id': '67199',
    'poster': u'https://image.tmdb.org/t/p/w500/3wuWmvpk9MnqnpiyC9Oc0thDLKx.jpg',
    'tvshowtitle': u'Saint Seiya: The Hades Chapter',
    'tvdb_id': 350828,
    'imdb_id': u'tt0805448',
    'released': u'2002-11-09',
    'now': '20200418222559615000',
    'slug': u'saint-seiya-the-hades-chapter-2002',
    'episode': '1',
    'name': u'Saint Seiya: The Hades Chapter S01E01',
    'premiered': u'2002-11-09',
    'originaltitle': u'None',
    'tvdb': 350828,
    'firstaired': u'2002-11-09',
    'eptrakt': 3449717,
    }
```

**Comment by juanma-cvega** [comment]
Weird, I'm still seeing them. The version I'm using is 2.4.25 and the player is this one. 
```
  "play_episode" : [
                      "plugin://plugin.video.embycon/?content_type=video&mode=GET_CONTENT&media_type=episodes&url=%7Bserver%7D%2Femby%2FUsers%2F%7Buserid%7D%2FItems%3FIncludeItemTypes%3Depisode%26filters%3DIsNotFolder%26fields%3DMediaStreams%26Recursive%3Dtrue%26ImageTypeLimit%3D1%26Limit%3D16%26Years%3D{year}%26AnyProviderIdEquals%3Dtvdb.{epid},imdb.{epimdb},tmdb.{eptmdb},trakt.{eptrakt}",
                      {"dialog":"auto"}
                    ],
```
I tried several episodes I changed the TMDB ID for and it's the same for all.

**Comment by jurialmunkey** [comment]
Ah yeah it's the cache.

In the details list for the item you can refresh the item cache -- set TMDbHelper default action to "Browse" and then click the episode to open the details section. The Refresh option is down the bottom.

**Comment by juanma-cvega** [comment]
Hmm, I cannot find the option. I have set up the addon to play the item, not browse it. And I cannot find any button in the context menu to pull that list up.

**Comment by angelitto2005** [comment]
@juanma-cvega, you can see that option only if you set the addon to ”Browse”, not to ”Open/Play”.

**Comment by juanma-cvega** [comment]
@angelitto2005 Yes, I just did it to be able to refresh it. Thanks. It would a good button to add to the context menu I think.
And yes, now it works! It uses the TMDB id I set yesterday instead of the Trakt one.

**Comment by jurialmunkey** [comment]
I've been meaning to add refresh to context menu - I just haven't got around to it yet.
