### ISSUE TITLE
[Feature Request]Please include TMDb-My List section

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/plugin.video.themoviedb.helper#175]
Hi Jurial @jurialmunkey hope all well at your end.
First things first, many thanks for the superb TheMovieDv Helper add-on 👌
I got a small request. In TheMovieDb Helper Video add-on, when I enter the 'TheMovieDb' section can you please make my personal TMDb lists appear there?
I am using Trakt but TMDb is listing some obscure contents like my regional webseries which are absent in Trakt, hence this request.

**Comment by jurialmunkey** [comment]
Do you know of any addons that provide access to these lists? I cannot see a way for a user to authenticate without a web browser on the same machine as kodi (which is a problem for libreelec etc.).

**Comment by onlytanmoy** [comment]
Sorry not aware of any add-on that does that at the moment 😐 As I gather from you now that the authentication process is not straight forward, I think you can ignore my request mate.

**Comment by jurialmunkey** [comment]
No worries. Yeah it's annoying because I would like to add the tmdb user features since they are quote good bu I just can't see a way to authenticate without a Web browser on the machine.

**Comment by onlytanmoy** [comment]
@jurialmunkey How about IMDb watchlist/list mate? Is that doable? Let me know pls.

**Comment by jurialmunkey** [comment]
IMDb doesn't have a public API unfortunately.

**Comment by onlytanmoy** [comment]
Ohh ok, I see.
