### ISSUE TITLE
[Bug] progress mark for tv and movies are not saved

### ISSUE THREAD

**Issue by prateek33** [jurialmunkey/plugin.video.themoviedb.helper#178]
I use themoviedb.helper for managing all my content. Once I start a movie or an episode and chose the player like seren or crew or netflix, it works. Then I stop the video and quit. Now I see the movie/episode in my in-progress and now when I try to resume, the video starts from the beginning and not where i left it.

Now when I play a new video from seren directly and quit midway and then resume, seren gives me an option to resume or start over.

**Comment by jurialmunkey** [comment]
In Kodi v18 Leia, it is currently not possible to retrieve resume points from other plugins. It requires a fix which is merged for Kodi v19 Matrix
https://github.com/xbmc/xbmc/pull/17202

**Comment by prateek33** [comment]
aha..something weird though.. when I select the crew as my player, i am able to resume from where i left off. Seren has some weird problem. It only resumes when I play video directly from the addon and not if I select it as player from themoviedbhelper.. so weird

**Comment by jurialmunkey** [comment]
It depends on how the addon handles resume. My point is that TMDbHelper is unable to retrieve the resume point to send to Kodi's player function, so it is entirely dependent on the addon being called to manage resume.

**Comment by Bulletbling** [comment]
Couldn't tmdbhelper retrieve the resume point from the built in trakt functionality? Add-ons such as seren and venom sync the resume point to trakt for all content. Wouldn't just pulling the resume point from trakt that the other addon saved allow tmdbhelper to resume from that point?

**Comment by jurialmunkey** [comment]
> Couldn't tmdbhelper retrieve the resume point from the built in trakt functionality? Add-ons such as seren and venom sync the resume point to trakt for all content. Wouldn't just pulling the resume point from trakt that the other addon saved allow tmdbhelper to resume from that point?

TMDbHelper _could_ retrieve it from Trakt but it wouldn't do anything anyway because these addons you listed don't use setResolvedURL for playback -- Because these addons don't follow the correct way to start playback in Kodi there is no way for TMDbHelper to pass the resume point to them.

**Comment by Bulletbling** [comment]
Ahh makes sense. However, I do have setresolvedurl enabled for venom in tmdb helper and it works fine (it was enabled by default for some reason).
