### ISSUE TITLE
Clear art redownloaded for every episode in a TV show

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#179]
I open the issue here this time instead on in the horizon repo. Clear art is redownloaded for each episode, which causes the image to show up and disappear continuously while browsing episodes in a TV show folder. Is this something that can be fixed?

**Comment by jurialmunkey** [comment]
It's not redownloaded. It's that each episode is a different item and so new properties get set

**Comment by jurialmunkey** [comment]
@juanma-cvega - Can you test latest version. 

This commit https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/fb55ed228b6938e04e71c5ad76e61fd672bf8718 introduces some better handling of artwork setting/clearing and, at least on my end, appears to be working well.

**Comment by juanma-cvega** [comment]
Yes, it works very well now! Thanks! A question though, is it just for artwork or does it include better handling of scores as well?

**Comment by jurialmunkey** [comment]
> 
> 
> Yes, it works very well now! Thanks! A question though, is it just for artwork or does it include better handling of scores as well?

Ratings need to be updated for each item because each episode can have different ratings whereas Artwork between episodes largely stays the same other than the thumb (which is usually attached to the item anyway and so doesn't need service monitor).
