### ISSUE TITLE
[Request] Turn off default player

### ISSUE THREAD

**Issue by notoco** [jurialmunkey/plugin.video.themoviedb.helper#18]
Maybe it's worth considering turning off the default players? Although Netflix is OK for me, I don't use YouTube at all. I have my own other plugins that I use and it's getting too confusing.

**Comment by jurialmunkey** [comment]
I haven't forgotten this issue! I'm just still thinking about the best way to do it.

**Comment by jurialmunkey** [comment]
I was thinking about having a dialog where users could enable/disable various options but I ultimately decided that it was simplest just to have a toggle to disable the bundle ones and then users can manage whatever is in addon_data folder themselves.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/767e46120f145db7c8352dc76cb89f6faa5959c0

**Comment by drinfernoo** [comment]
Would you be interested in a PR to add something to granularly enable/disable certain players? I could look at adding that.
