### ISSUE TITLE
TheMovieDB doesn't recognize Trakt Collection

### ISSUE THREAD

**Issue by Nazim1981** [jurialmunkey/plugin.video.themoviedb.helper#180]
I have enabled Trakt account in TMDB now I want to sync Trakt Files (Collection)  to my Library (Movies+TV Shows Folder) I have set the path of TMDB to these Library created folders and enabled sync both library and Trakt , but nothing happened , then I saw in setting I have to add the something directly from Trakt but when I open it , it doesn't show my collection but one random created folder of my Trakt (only) with None , Collection folder should be there , if it is not there how can I add it?

**Comment by jurialmunkey** [comment]
You cannot add it. Stop misusing Trakt's Collection feature. Collection should NOT be synced to library. Collection is meant to be for items that you either have on physical media or as a file on a harddrive.

You need to create a separate subscription list of items that you have access to via subscription services and sync that.

**Comment by Nazim1981** [comment]
May be you are right , but I have 2 addon names who are actively doing this
with remarkably ease , and I love for that.nevertheless thanks, closed and
left.
