### ISSUE TITLE
[Feature] AZ2

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#181]
Hi,
Not urgent, would it be possible to add this feature to AZ2 🙂
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/142#issue-590037202
Thanks

**Comment by drinfernoo** [comment]
@Blurayx That's a feature of TMDbHelper... not skin specific?

**Comment by Blurayx** [comment]
> @Blurayx That's a feature of TMDbHelper... not skin specific?

This is TMDbHelper thread

**Comment by drinfernoo** [comment]
@Blurayx Exactly. There should be no need to add anything to AZ2, as the feature you're referring to should be skin-agnostic, being that it's a feature *of* TMDbHelper.

Is it not working in AZ2?

**Comment by Blurayx** [comment]
> @Blurayx Exactly. There should be no need to add anything to AZ2, as the feature you're referring to should be skin-agnostic, being that it's a feature _of_ TMDbHelper.
> 
> Is it not working in AZ2?
The home widgets posters are different from my library widgets.

**Comment by jurialmunkey** [comment]
@Blurayx - AZ2 prefers season posters - TMDbHelper only uses library artwork for tvshow posters. Can you open this issue in AZ2 github? -- though at the moment I don't have much time to work on that skin.

**Comment by Blurayx** [comment]
Sorry, No worries I'll open an issue in AZ2 github. I know you are very busy, that's why I said it's not urgent 🙂
