### ISSUE TITLE
Feature request movie sets

### ISSUE THREAD

**Issue by BP-onthemove** [jurialmunkey/plugin.video.themoviedb.helper#183]
Hi, thanks for this great addon! 🙂🙏
I know that the moviedb also has moviesets information. It would be great to have a view to browse through all movie box sets.🎬📽️

**Comment by jurialmunkey** [comment]
As of this commit https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/34ed66fc47c41ceca37590c17e1850c7d3da48f5 you should now be able to get collections
`TMDbHelper > TheMovieDb > All Collections`

**Comment by BP-onthemove** [comment]
Thanks so much! 🙂👍👍👍
