### ISSUE TITLE
Widgets fail to populate leaving a blank home screen

### ISSUE THREAD

**Issue by djnield** [jurialmunkey/plugin.video.themoviedb.helper#186]
Odroid N2 CoreElec
Arctic Horizon
TheMovieDb Helper 
Seren

I have an issue where widgets won't always appear at boot up and left with a blank home page. It happens about 50% of the time. A reload skin sometimes rectifies it but that fails about 30% of the time too. Further reboots will eventually have it back to normal. 

Widgets are pointed through the Helper to trakt lists and next up. Also to a playlist of library shows populated by the helpers trakt list subscription function.

Currently on v2.4.39 but the issue has been going on for many versions before this.

**Comment by jurialmunkey** [comment]
Full debug log please.

This doesn't happen for me.

**Comment by drinfernoo** [comment]
The only time I've seen something like this when there are service outages, and it's pretty rare for that part of the API to be down.

**Comment by jurialmunkey** [comment]
> The only time I've seen something like this when there are service outages, and it's pretty rare for that part of the API to be down.

Yep that's the only time I get anything like that - either the api is down or my actual internet connection is.

**Comment by djnield** [comment]
Will try the debug log but the Internet suggestion is interesting. For example the weather temp icon next to the clock won't always initially display. The widgets always fail at this same time too.

I have the Internet of course. But could kodi / coreelec not be utilising it immediately on boot up?

**Comment by jurialmunkey** [comment]
> 
> 
> Will try the debug log but the Internet suggestion is interesting. For example the weather temp icon next to the clock won't always initially display. The widgets always fail at this same time too.
> 
> I have the Internet of course. But could kodi / coreelec not be utilising it immediately on boot up?

I do occasionally experience a bug on LibreElec where no addons will load at all on startup -- if weather also isn't loading for you, then that's probably a pretty good indication of the same issue.

However, that isn't limited to just TMDbHelper widgets -- it will be absolutely every addon, even those that don't use Internet. If you go into Video Addons, you won't be able to open anything (it will just sit on busy spinner for ever). Even plugins that only use library data won't work (e.g. library service widgets addon).

It only happens very occasionally for me, so it is hard to replicate with a debug log. Afaict, it happens even with TMDbHelper uninstalled - so it appears that TMDbHelper is just a "victim" of a bug somewhere else so to speak. 

As far as I can tell from my logs, Kodi's texture loader gets hung up on loading some skin texture and so doesn't progress to loading other addons. However, that is just the last log message when it happens - not necessarily the cause.

**Comment by djnield** [comment]
Interesting.
Will check video addons then next time it happens.

**Comment by drinfernoo** [comment]
@jurialmunkey Now that you describe it that way... I think I've had this happen to me on my Shield, but I never noticed it until I started using AH 🤔

It'll seem like widgets are taking a long time to load, so I'll just hit my search shortcut (search lists from TMDbHelper), and... nothing ever loads.

I'll have to sometimes reboot my *Shield* just to get it to work again.

**Comment by jurialmunkey** [comment]
@drinfernoo - You just have to kill kodi and relaunch it. Shouldn't need to reboot. If it happens on LibreElec, I'll ssh into the machine and run `killall -9 kodi.bin`, which will fix it (unless I get really unlucky and it happens twice in a row - but that very very rarely happens).

I'm not sure if there is an equivalent for Android though.

**Comment by djnield** [comment]
I never thought a skin issue would be at play. Am going to try AZ2 then.

**Comment by jurialmunkey** [comment]
> 
> 
> I never thought a skin issue would be at play. Am going to try AZ2 then.

I don't think its a skin issue. It's happened to me before in AZ2.

**Comment by henryjfry** [comment]
> > I never thought a skin issue would be at play. Am going to try AZ2 then.
> 
> I don't think its a skin issue. It's happened to me before in AZ2.

I saw this issue and I thought it might be worth mentioning that on my system I think I've narrowed down the problem of no add-ons loading on boot to one specific add-on, up next (that provides general up next episode functionality).

Disabling this add-on seemed to prevent all issues where weather would not start (nor any other add-on)

And as upnext hasn't worked in quite a while it's no loss having it disabled.

**Comment by djnield** [comment]
@henryjfry that's interesting too.
You referring to up next that comes from installing seren? 

I'm going to play and see if it works for me. 
Btw I'm still using and enjoying your Next Playlist addon 👍

**Comment by henryjfry** [comment]
> @henryjfry that's interesting too.
> You referring to up next that comes from installing seren?
> 
> I'm going to play and see if it works for me.
> Btw I'm still using and enjoying your Next Playlist addon 👍

Seren has its own next episode methodology so i don't think thats where it came from on my system, I have a number of different skins installed so I had thought it came from one of the ones I dont use. Or Gaia possibly?

But yeah its the one which has a white overlay, it would occasionally pop up over serens next episode window which was when i started investigating what was going on with it.
And disabling it seemed to fix a number of issues.

Glad you like the addon, its a very simple but useful functionality.
Ive added a bunch of stuff to my own version of the addon actually, like my own next episode window (which i stole from seren) but its all very hacky and a lot of its kind of specific to my system so ive never felt like releasing it (parts of it rely on changes ive made to tmdbhelper amongst other things not really suitable for public consumptionn).

**Comment by djnield** [comment]
Ah might not be the same for me then. I've not got any other next up but from nixgates. No other skins nor video addons other than seren.

Saying that the issue hasn't arisen since I made this post. Isn't that typical! It was so frequent before and nothing for a couple of days now 🤔

I envy you can do this stuff. I can't, so will stick with what you've already offered in the past 👍

**Comment by jurialmunkey** [comment]
> Saying that the issue hasn't arisen since I made this post. Isn't that typical! It was so frequent before and nothing for a couple of days now 🤔

Hahaha yeah it hasn't occurred for me since you opened this thread either! 

In a way, I was hoping that it *would* occur on my LibreELEC machine so I could do some further digging now that I know it happens to other people and its not just some quirk in my system caused by my constant skin reloading during feature/bug testing.

**Comment by henryjfry** [comment]
> > Saying that the issue hasn't arisen since I made this post. Isn't that typical! It was so frequent before and nothing for a couple of days now 🤔
> 
> Hahaha yeah it hasn't occurred for me since you opened this thread either!
> 
> In a way, I was hoping that it _would_ occur on my LibreELEC machine so I could do some further digging now that I know it happens to other people and its not just some quirk in my system caused by my constant skin reloading during feature/bug testing.



> Ah might not be the same for me then. I've not got any other next up but from nixgates. No other skins nor video addons other than seren.
> 
> Saying that the issue hasn't arisen since I made this post. Isn't that typical! It was so frequent before and nothing for a couple of days now 🤔
> 
> I envy you can do this stuff. I can't, so will stick with what you've already offered in the past 👍

The one i am referring to is called:
~/.kodi/addons/service.upnext

<addon id="service.upnext" name="Up Next" version="1.1.0" provider-name="im85288">

**Comment by henryjfry** [comment]
> > Saying that the issue hasn't arisen since I made this post. Isn't that typical! It was so frequent before and nothing for a couple of days now thinking
> 
> Hahaha yeah it hasn't occurred for me since you opened this thread either!
> 
> In a way, I was hoping that it _would_ occur on my LibreELEC machine so I could do some further digging now that I know it happens to other people and its not just some quirk in my system caused by my constant skin reloading during feature/bug testing.

I saw something in the Kodi forums about add-ons failing to load.
(I re enabled artwork beef and it happened again)

A short delay in autoexec.py may be a potential fix, without having to figure out if it's one specific add-on causing it?

**Comment by djnield** [comment]
> > > Saying that the issue hasn't arisen since I made this post. Isn't that typical! It was so frequent before and nothing for a couple of days now thinking
> > 
> > 
> > Hahaha yeah it hasn't occurred for me since you opened this thread either!
> > In a way, I was hoping that it _would_ occur on my LibreELEC machine so I could do some further digging now that I know it happens to other people and its not just some quirk in my system caused by my constant skin reloading during feature/bug testing.
> 
> I saw something in the Kodi forums about add-ons failing to load.
> (I re enabled artwork beef and it happened again)
> 
> A short delay in autoexec.py may be a potential fix, without having to figure out if it's one specific add-on causing it?

I don't know what that entails. 
But just to say, after days of behaving correctly, the issue returned tonight 😉

And so far no amount of reboots is rectifying it. 

I can't work it out 😏

**Comment by jurialmunkey** [comment]
@djnield - do you have a debug log with the issue? I managed to get it to occur yesterday, so I want to compare against the log that I saved.

**Comment by djnield** [comment]
Not this time but will try next one.
Actually yesterday's issue was my own fault. Hadn't realised the mesh system had failed 🤦‍♂️

**Comment by jurialmunkey** [comment]
I've stumbled across something interesting today regarding python's datetime module.

It appears that I can replicate this plugin hang bug consistently by calling `datetime.datetime.strptime(time_str)` on Kodi startup. If I add a delay before calling datetime then everything is fine.

My guess is that some of these addons call datetime module to determine whether to do an update and occasionally it happens to be called at startup causing the hang.

**Comment by djnield** [comment]
> I've stumbled across something interesting today regarding python's datetime module.
> 
> It appears that I can replicate this plugin hang bug consistently by calling `datetime.datetime.strptime(time_str)` on Kodi startup. If I add a delay before calling datetime then everything is fine.
> 
> My guess is that some of these addons call datetime module to determine whether to do an update and occasionally it happens to be called at startup causing the hang.
> 
> Not sure what the underlying reason for the issue is but I can very consistently replicate it now.

Well done for finding that out! 
Does that mean the individual addon devs need to alter their addons assuming they're inclined to?

**Comment by jurialmunkey** [comment]
> Well done for finding that out!
> Does that mean the individual addon devs need to alter their addons assuming they're inclined to?

It's not really something that they should need to fix as the python module should work properly without needing workarounds. If this is indeed the culprit, then it is more of a bug that needs to be fixed in Kodi core -- and with the switch to python 3 in Matrix, it is very possible that it already has been fixed (I haven't tested on Matrix yet) - python 2, which is used in Leia, has reached end of life and is no longer developed.
