### ISSUE TITLE
[enhancement] extend the 'Hide watched items on widgets' to include playlist widgets

### ISSUE THREAD

**Issue by djnield** [jurialmunkey/plugin.video.themoviedb.helper#192]
Would that be possible to include a larger range of widgets like playlists for example?

**Comment by jurialmunkey** [comment]
Do you mean kodi smart playlists? Just edit the playlist and add a rule to only show items with play count 0

**Comment by djnield** [comment]
Actually not smart playlist, I don't know how to make them.

For example the playlist the Helper makes automatically from the Trakt subscription. And another is an addon (next playlist) I use that makes a playlist of next up library items.

Both these seem to display watched items in widgets.

**Comment by jurialmunkey** [comment]
Those are both smart playlists. The addon makes a smart playlist. Once it is made, the addon has no control over what is displayed inside it.

Making a smart playlist based on another smart playlist is simple:
Go to `Videos > Playlists > New smart playlist`

![Honeyview_screenshot764](https://user-images.githubusercontent.com/4618719/80897371-303b4900-8d3b-11ea-9681-a761d807a60b.jpg)

![Honeyview_screenshot765](https://user-images.githubusercontent.com/4618719/80897373-32050c80-8d3b-11ea-822d-b557b0a0cebf.jpg)


Add a rule `Playlist is name-of-playlist`
You can get the name of the playlist by clicking on the folder search icon in the rule creation dialog.
![Honeyview_screenshot762](https://user-images.githubusercontent.com/4618719/80897316-9378ab80-8d3a-11ea-883d-b1032266d9aa.jpg)

Then add another rule `Play count is 0`

![Honeyview_screenshot763](https://user-images.githubusercontent.com/4618719/80897335-b4d99780-8d3a-11ea-9a21-1e640679dc59.jpg)


Hit OK and give your playlist a name. That smart playlist will now show the contents of the original playlist but with only unwatched items.

**Comment by djnield** [comment]
This worked perfectly thanks 👍

Tried to make a smart playlist last night but couldn't get my head around it. So this tip is great thanks.

**Comment by jurialmunkey** [comment]
No problem! 😃
