### ISSUE TITLE
Search keyword

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#198]
I'm trying to create widgets with anime TV shows and movies but I'm not sure how/if is possible to do it through the addon. There is a section in the addon within the option `TheMovieDB` called `All keywords` but there there are tons of pages, each one with keywords for the whole alphabet so after some pages I gave up trying to find anime. 
Through google by searching tmdb and anime I was able to reach the following page.
https://www.themoviedb.org/keyword/210024-anime/tv?language=en-US
which gives me something to work with. It'd be nice if there was the option to search by keyword and filter by trending ones as with regular TV shows/movies but the website only gives you the option sort by airing date. 
There is no anime within genre, only animation which includes everything so, is there any way to reach to the same result as within the website within the addon?

**Comment by jurialmunkey** [comment]
Use the discover section to search by keyword.

**Comment by juanma-cvega** [comment]
Ok, I actually never realised that option was there. I just tried it out and that's what I was looking for but I have some problems adding results to a widget. For instance, I tried creating one with genres animation and family, pressing the button to discover results and then adding the result as a widget but when the widget loads up, a dialog to add another rule pops up.

**Comment by jurialmunkey** [comment]
How did you add it as a widget? If you add through the normal skinshortcuts dialog in skin settings, it shouldn't prompt for rule addition.

**Comment by juanma-cvega** [comment]
I added by doing `Skin settings -> Customise home menu -> Widgets (on menu item) -> Choose Widget -> Add-on -> Video Add-on -> TheMovieDB Helper -> Discover -> Discover Movies -> Add rule -> With Genres -> Animation, Family -> Discover Movies w/ Below Settings -> Use as widget`

**Comment by jurialmunkey** [comment]
That's very strange. I just added that exact widget using those exact steps just before and it works fine for me.

What does the widget path say in the choose widget button? (Highlight it to let it scroll).

**Comment by juanma-cvega** [comment]
`ActivateWindow(Videos, "plugin://plugin.video.themoviedb.helper/?info=discover&with_genres=16%2F+10751&widget=True&type=movie&with_id=True",return)`
With the configuration, the first it does after starting Kodi and loading widgets is popping up the dialog.
I'm using Mac for testing by the way, just in case it may be the cause of the issue.
<img width="1440" alt="Screenshot 2020-05-05 at 15 18 58" src="https://user-images.githubusercontent.com/6765894/81070650-d45ff400-8ee3-11ea-8920-62dc6b1a4a56.png">

**Comment by jurialmunkey** [comment]
Hmm, that's very odd - that's the exact same path I have and it is working with no problems. I can't even see what would cause that dialog to popup. That dialog is not used for the `info=discover` entry point. It is only opened if `info=user_discover&method=sort_by`

Are you sure you haven't inadvertently set another widget elsewhere that is pointing to `info=user_discover` instead?

**Comment by juanma-cvega** [comment]
Oh my... You were right, I had one in another menu item I must have created while testing that I completely forgot about. Sorry for making you lose your time.

**Comment by juanma-cvega** [comment]
Before closing the subject, is there any way to save these settings somewhere? I was thinking maybe the TMDB site offered some kind of lists like Trakt does. I would like to keep them so I can replicate them in other Kodi systems I have as it's quite some work to keep creating these all the time.

**Comment by jurialmunkey** [comment]
Tmdb does have lists. Unfortunately the authentication process only works if you have a Web browser on the machine - so not really suitable for kodi.

You can backup skinshortcuts userdata/addon_data folder to transfer the settings to another machine.
