### ISSUE TITLE
Auto update is annoying

### ISSUE THREAD

**Issue by G-streamer** [jurialmunkey/plugin.video.themoviedb.helper#200]
Latest update has my Library auto updating about every hour. I had the old setting set for every 6 hours so it wouldn't disrupt what I was watching. I had to completely disable auto update.

**Comment by jurialmunkey** [comment]
Debug log please. That shouldn't be happening. It should only update once a day at the specified time.

**Comment by jurialmunkey** [comment]
Actually, scrap that - I think I realised the issue. Can you test latest version? Hopefully should be fixed now.

**Comment by angelitto2005** [comment]
Last night i had the same auto-update glitch, every 30 min (2.4.52)
Lets test it now with 2.4.56 😎

**Comment by angelitto2005** [comment]
All it's fine with 2.4.56. Last night, only one time i saw the auto-update. I set it to 01.00, but i started Kodi at 1.10 and i saw the auto-update notice after 15-20 min. After that was quiet 👍

**Comment by G-streamer** [comment]
Yes, seems to be okay now. Sorry I didn't get back sooner I was working on a new build and didn't have it running long enough to test. BTW Awesome add-on. Would love to see you redo the Extended Info Mod like OpenInfo linked to TMDB Helper. That would officially make you a Kodi God. lol

**Comment by jurialmunkey** [comment]
I already have an extended info replacement in both AZ2 and Arctic Horizon.
