### ISSUE TITLE
[Bug] Library  Calendar  Fanart

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#201]
When I select a fanart, the library calendar doesn’t mirror the fanart I have chosen. posters work fine.

<a href="https://imgur.com/60SzpI3"><img src="https://i.imgur.com/60SzpI3.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/29SqqEK"><img src="https://i.imgur.com/29SqqEK.png" title="source: imgur.com" /></a>

Thanks

**Comment by jurialmunkey** [comment]
Do you have landscape art turned on? 
`Skin settings > Library > Landscape art`

Because if that option is enabled and there's landscape art on fanart tv, then it will use that instead of fanart.

**Comment by Blurayx** [comment]
I disabled the landscape art. still not showing the fanart I selected.

**Comment by jurialmunkey** [comment]
Ah, it's a skin issue. 
Should be fixed in v0.2.41 of Arctic Horizon - at least seems to be working for me correctly now.

**Comment by Blurayx** [comment]
Working now. Thanks!!!
I made a donation a few hours ago 😉
when this lockdowns over have a drink on me 😀

**Comment by Blurayx** [comment]
How do I manually refresh  Library Calendar/TMDBHelper?

**Comment by jurialmunkey** [comment]
> Working now. Thanks!!!
> I made a donation a few hours ago 😉
> when this lockdowns over have a drink on me 😀

Thanks so much! You're too generous! 😁 

Now that's a crazy idea to be able to go down to the local and have a pint and a pub meal! It almost feels like a distant memory... Such a simple thing that I used to take for granted!

**Comment by jurialmunkey** [comment]
> 
> 
> Is there an option to manually refresh Library Calendar/TMDbHelper?
> similar to Next Aired(6.0.18)

If you do a ReloadSkin then it will refresh.

It will also refresh automatically if you open the Calendar and more than an hour has passed since it was last refreshed.

**Comment by Blurayx** [comment]
> > Working now. Thanks!!!
> > I made a donation a few hours ago 😉
> > when this lockdowns over have a drink on me 😀
> 
> Thanks so much! You're too generous! 😁
> 
> Now that's a crazy idea to be able to go down to the local and have a pint and a pub meal! It almost feels like a distant memory... Such a simple thing that I used to take for granted!

You're welcome, you deserve it!!!
You have worked so hard over the past weeks and always willing to listen to ideas and help others. sometimes when you don't hear from me I still follow what's going on, it doesn't go unnoticed 😉
Yes, The world has changed. those days are gone for now.

**Comment by Blurayx** [comment]
I can honestly say I love using TMDbHelper/Next Aired. it's so quick

**Comment by Blurayx** [comment]
YES!!!!! 😀
it's working thank you so much.

I have a question. I can't access the library from the home screen. When I was using Next Aired(6.0.18), It was possible. 
<a href="https://imgur.com/pnsDBHe"><img src="https://i.imgur.com/pnsDBHe.png" title="source: imgur.com" /></a>
