### ISSUE TITLE
[Feature request]  Direct access to library 

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#202]
When browsing Next Aired(6.0.18) I was able to go directly into my Library. 
<a href="https://imgur.com/KMkQItA"><img src="https://i.imgur.com/KMkQItA.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/NXxVSKU"><img src="https://i.imgur.com/NXxVSKU.png" title="source: imgur.com" /></a>

Thanks

**Comment by jurialmunkey** [comment]
Okay should be working now. You'll need latest version of both TMDbHelper and Arctic Horizon.

**Comment by Blurayx** [comment]
Working perfectly. I can't believe I didn't know about this. TMDbHelper has so many tricks up its sleeve. I now prefer to use TMDbHelper/Next Aired. Thank you so much for creating TMDbHelper/Next Aired.
What gave you the idea?

**Comment by jurialmunkey** [comment]
> 
> 
> Working perfectly. I can't believe I didn't know about this. TMDbHelper has so many tricks up its sleeve. I now prefer to use TMDbHelper/Next Aired. Thank you so much for creating TMDbHelper/Next Aired.
> What gave you the idea?

Well I already had these lists for each day available to be used as widgets, so the Next Aired window in Arctic Horizon is essentially just a separate page of widgets with one widget for each day of the week stacked on top of each other and few little skin tricks to help with reloading and onclick actions.
