### ISSUE TITLE
[Request] Without company rule

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#203]
Maybe the reason why it doesn't exist is because the rule doesn't exist. If it's available, could `without company` be added to the list of rules? For some reason someone decided that Disney Animation movies should be tagged as anime so I would like to filter by company as well so I can remove movies like Cars or Frozen from the list of popular anime movies.

**Comment by jurialmunkey** [comment]
Hahahaha. Oh dear... 

Unfortunately not possible. It's not exposed by the discover endpoint in the api. 

If youre using multiple keywords, make sure that the MATCH setting is set to ALL and not ANY. 

The plugin does provide basic exclusion and inclusion filters based upon a field, but they have to be added manually currently (normally used by skins in the info dialog to exclude the base movie from the list of studio movies, or to filter movies by a crew member by the job they had eg only only movies where the person was director not producer). Ill look at possibly adding these options through the UI.

**Comment by juanma-cvega** [comment]
I just created a post in the TMDB forum asking for this feature. Let's see if someone answers it. 
As far as I understand, what you propose would be filtering the results from the API at the UI level. The problem with that is that the number of elements displayed would be much lower than the max limit imposed by the API, right? So you could end up with a widget with 8 elements instead of 20 for example.

**Comment by jurialmunkey** [comment]
> As far as I understand, what you propose would be filtering the results from the API at the UI level. 

Yep that's correct.

> The problem with that is that the number of elements displayed would be much lower than the max limit imposed by the API, right?

Good point. Pagination throws a spanner in the works. I didn't even really think about that - definitely defeats the purpose and is probably why I never really exposed it in the first place. Realistically it is only useful for hiding one or two very specific items rather than a whole category of items.

> I just created a post in the TMDB forum asking for this feature. Let's see if someone answers it.

Excellent! Here's hoping.

I have a feeling that maybe they might say that it will be too expensive - but still I can't see why without_keywords would be fine but without_companies wouldn't be. In both scenarios it should just be a check of the ID against a database field.

**Comment by jurialmunkey** [comment]
Looks promising from Travis' comments on your post about without_companies. I'll add it once they do!

**Comment by juanma-cvega** [comment]
Yeah, hopefully they will do it but, given it is under consideration and that they probably have quite a backlog of items to do, I think it's going to take some time. At least they acknowledged there are items with wrong keywords added and they have removed some. I just deleted Snow white from the list.
