### ISSUE TITLE
Smart playlist from Trakt liked list only adds movies already in the library

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#206]
I just realised a Trakt list I liked that contains all the movies in the MCU that I added to the library, the playlist created from it only contains a handful of films. After checking I saw that only the movies I already had in the library were added to the playlist instead of all of them.

**Comment by jurialmunkey** [comment]
Did all the movies get added to the library successfully? 
If you open the smart playlist in a text editor, does it have all the entries added?

**Comment by juanma-cvega** [comment]
Hi, sorry for the late reply. For some reason I didn't get the notification of reply or I just missed it. 
I just realised what was the problem. I forgot to add the movies folder as media on Kodi, I only had TV shows added.
