### ISSUE TITLE
Extended Info for Estuary Skin

### ISSUE THREAD

**Issue by angelitto2005** [jurialmunkey/plugin.video.themoviedb.helper#207]
> 
> 
> I already have an extended info replacement in both AZ2 and Arctic Horizon.

Is there any way to use/implement your extended info with Estuary Skin? 
I use now, OpenInfo, but it seems that the developer has abandoned the project.

**Comment by drinfernoo** [comment]
Team Kodi would have to update the skin to use TheMovieDb Helper instead of ExtendedInfo Script.

**Comment by jurialmunkey** [comment]
It doesn't work like that - it's not a scripted window, it uses a native implementation of the video info dialog so it requires skin changes to work.
