### ISSUE TITLE
selecting dutch as language downloads Russian clearart

### ISSUE THREAD

**Issue by edd--** [jurialmunkey/plugin.video.themoviedb.helper#208]
As the title say: selecting dutch as language downloads Russian clearart. 

For now I have changed the language to English. But I can't manage to clear the clearart (removing the Russian versions). I tried removing the Textures DB but that didn't seem to do the trick ? Any ideas ?

**Comment by jurialmunkey** [comment]
TMDbHelper first looks for artwork matching the language and uses that if found. If it can't find a match according to your language settings, then it will ignore language and look for the best rated artwork -- usually the best rated artwork is in English but occasionally no English artwork exists. 

If you're getting Russian artwork then it probably is the only artwork available for that item. Either that or the artwork is miscategorised on fanart tv.

The artwork is cached for 14 days - you can force a cache refresh by deleting 
```
kodi/userdata/addon_data/script.module.simplecache/simplecache.db
```
Note that this is the nuclear option and will delete the entire cache (ratings, details, everything) used by TMDbHelper, so you should only delete it as a last resort.


I need to add a few extra options to control how the artwork is dealt with -- I think maybe it should only fallback to English artwork, with the option to disable the fallback entirely.

**Comment by jurialmunkey** [comment]
Okay it should be fixed now - you should only get english fallbacks if artwork for the main language is not found.

**Comment by edd--** [comment]
Thanks a lot ! Is there any way to batch cache all data ? (like cache all info / images) ?

**Comment by jurialmunkey** [comment]
Nope, not possible.
