### ISSUE TITLE
The dependency on xbmc.python version 3.0.0 could n.. 

### ISSUE THREAD

**Issue by djnield** [jurialmunkey/plugin.video.themoviedb.helper#209]
I'm showing an update to v2.4.58 but get the above error flash on screen before the update fails. Also the same error trying to update to Horizon v0.2.45

My current Helper is v2.4.56

**Comment by drinfernoo** [comment]
You'll need to get the latest version from the `matrix` branch, and install it from zip. The repo is currently not serving Matrix-compatible packages.

**Comment by djnield** [comment]
> You'll need to get the latest version from the `matrix` branch, and install it from zip. The repo is currently not serving Matrix-compatible packages.

I don't know about matrix? 
Has something happened since yesterday that stops me updating horizon and Helper only all previous updates have worked fine. 

Am using coreelec 9.2.2

**Comment by drinfernoo** [comment]
Fixed. In testing the future setup for the Matrix repo, I accidentally pushed a Matrix version to the normal repo. My apologies 😅

**Comment by djnield** [comment]
I thought I broke my kodi 😂
Good to know thanks.
