### ISSUE TITLE
Folder Creation Bug - (Specific Series)

### ISSUE THREAD

**Issue by ZefXyde** [jurialmunkey/plugin.video.themoviedb.helper#210]
Version Info
---
**TMDb Helper:** 2.4.58
**OS:** Windows 10
**Kodi:** 18.6

Issue
---
Adding "Marvel's Agents of S.H.I.E.L.D." to the library creates a corrupted file. Could this be due to the acronym?

Screenshot of Error
---
![TMDb Helper Error](https://user-images.githubusercontent.com/23259307/81460582-e227aa80-916b-11ea-9c22-7d4c8e09616f.png)

Debug Log
---
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/4602513/kodi.log)

Steps Taken to Resolve
---
- Adding series from all menu options in TMDb Helper
- All combinations of the following:
  - Clean reinstall of TMDb Helper
  - Clean reinstall of Kodi
  - Clean setup of new folders

To Remove the Folder
---
Remove the series from the library via Kodi and allow Kodi to delete the folder.

**Comment by ZefXyde** [comment]
I eventually gave up and just manually added the folder and info.

**Comment by jurialmunkey** [comment]
Hmm, yeah I can confirm this issue. Very strange.

Having a `.` in the folder name shouldn't matter. I wonder if it is because there's one on the end.
