### ISSUE TITLE
Not sure if it's an issue but maybe someone can enlighten me if it is or not

### ISSUE THREAD

**Issue by spursgalea** [jurialmunkey/plugin.video.themoviedb.helper#211]
Firstly I think this is a great add on. When I first installed it from the alpha repo it was all working fine but all the sudden my library update isn't updating when kodi starts up. I had to downgrade from the alpha repo to the version that's in the kodi repo to get the auto update on startup to work again. I don't understand what's happened in the new version.

**Comment by jurialmunkey** [comment]
The auto-update now happens at a scheduled time instead (default is midnight). If the scheduled time has already passed at startup, then the addon will check when the last update occurred and will do an update if there hasn't already been one that day.

Note that the update is delayed 15 mins after startup. The delay is to avoid bogging down lower spec systems considering how many other things are happening immediately on start.

You can force a manual update from the settings OR by running the command:
```
RunScript(plugin.video.themoviedb.helper,library_autoupdate)
```

**Comment by spursgalea** [comment]
Thanks for your reply
