### ISSUE TITLE
Inconsistent behaviour with TMDB Helper and Auramod Video Information

### ISSUE THREAD

**Issue by basKT-case** [jurialmunkey/plugin.video.themoviedb.helper#218]
_Excuse my cross-post from Reddit, as I now realise my issue posted there might be best addressed directly here with the dev._

I'm getting accustomed to my new Auramod + Seren + TMDB helper build. So far I'm loving the vast improvements over the stock Estruary skin that I have been using.

1) However I've noticed some inconsistent behaviour regarding Auramod's Netflix-style Video Information screen and TMDB helper. My homescreen widgets mainly consist of Seren content with a couple of TMDB helper widgets for extra content. When I browse for a title through Seren (addon or widget) the Video Information screen shows these buttons as expected:

https://imgur.com/a/vMEbt8S

This is great because I like the ability to access the Trakt Manager in the Information page to add a title to my Trakt Collection. I also find the Cast & More button useful to find similar content etc. But then here comes the issue. Say I find a similar show through this menu, and then it opens up a new Information page for that new title (I'm fairly certain it's searched through TMDB helper and not Seren). However, the Trakt Manager is no longer listed. This isn't so great for efficiency since now I have no easy way to add this title to my library straight from the Info page. I've also tried comparing the Info page for the same title through both Seren and TMDB helper, and I can confirm that the issue still persists.

Is this something others have encountered with TMDB helper? If it's indeed the current state of things, hopefully it's a feature that can be added as it will improve efficiency of managing new titles.

2) One other oddity I have encountered involves titles that exist in my local Kodi library. When I find that same title through TMDB helper and open the Video Information, the Play Button is gone.

https://imgur.com/a/zoyqXjB

I can still play the title from the addon by directly pressing the title listing itself, but just not from the Info page. Viewing that same title's Information from my local library acts like normal however with all the right buttons. I can confirm that this issues only happens within TMDB helper for titles already in my local library.

This issue isn't so much of a big deal to me, but I hope that I can bring it to the right people's attention.

Thanks for your assistance. Much appreciated!

**Comment by jurialmunkey** [comment]
These are both skin issues. You would need to ask the author of AuraMod - @skyfsza

There were some recent changes in the plugin that fixed ListItem.FileNameAndPath in the info dialog for all TMDbHelper items - both local and non-local. Previously this did not work properly for local files and so skins applied a workaround -- now that's no longer needed.

For skins that use TMDbHelper to replace extended info, all that is needed for the play button now is:
```
<onclick condition="!ListItem.IsFolder + !String.IsEmpty(ListItem.FileNameAndPath)">RunScript(plugin.video.themoviedb.helper,close_dialog=1190,playmedia='$ESCINFO[ListItem.FileNameAndPath]')</onclick>
```

For skins that don't use TMDbHelper to replace extended info. The default play button (ID=8) will work correctly for all items now.

**Comment by skyfsza** [comment]
Thanks Jurial.

I had made the previously suggested change to fix the FileNameAndPath bug, will revert back to the above.

**Comment by basKT-case** [comment]
Thanks for responding to my issue @jurialmunkey. Hopefully now that @skyfsza has entered the conversation, they are able to implement a solution for both issues.
Looking forward to seeing how it goes. Thanks to you both!
