### ISSUE TITLE
[Question] Randomise 'Based on...' options with filters

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#220]
I'm not sure if the `Based on...` options in the randomise section come from the TMDB API or if there is something else you are doing in the addon so I haven't been able to verify this myself. Would it be possible to use a filter (genre or keyword for example) within these sections? The idea is to be able to have different sections on Kodi (like anime, kids, tv shows...) and get recommendations on each one. Right now, I have the `Based on recently watch` as a widget on the movies and TV shows section but this keeps changing depending on whether I was watching anime or my kid was watching something himself.

**Comment by jurialmunkey** [comment]
The plugin provides several "related" lists for skinners to use in the info dialog to provide recommendations and similar items.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Lists-Related

All the `Based on...` list does is retrieve your five most recently watched movies/tvshows from Trakt and then pick one at random to use to create a Recommendations list.

You can make your own recommendations list based upon any item you like - you just pass the name of the item as a query:

e.g. Get Recommendations based on the Movie Robocop:
`plugin://plugin.video.themoviedb.helper?info=recommendations&amp;type=movie&amp;query=Robocop`

e.g. Get Similar TV shows to Seinfeld:
`plugin://plugin.video.themoviedb.helper?info=similar&amp;type=tv&amp;query=Seinfeld`

**Comment by jurialmunkey** [comment]
If you use the auto widget addon by @drinfernoo you should be able to create recommendation widgets based on a certain item pretty easily.

Just switch TMDbHelper default action to "Browse", then open a Movie/Show and you should be able to browse the Recommendations / Similar etc. lists. Then you can use the Autowidget context menu to add the path as a widget.

**Comment by juanma-cvega** [comment]
Hmm, I'm not sure I get it. If I understand correctly, your solution would only let me create a recommendation system from a static film selected the moment the widget is created instead of based on the latest movie/tv show watched that gets updated as I keep watching things. 
With the current implementation, the default 'Based on...' option just checks the latest 5 elements on Trakt but without filtering by type (I guess Trakt doesn't even have the option to filter that list itself) so on either case there is no way to create a widget based on latest watched element filtered by its genre/keyword. 
It's not a big deal, it's just that it would look great on my current setup having 'Based on...' widgets per type but that's not the end of the world.

**Comment by jurialmunkey** [comment]
Trakt only returns very sparse details for watched items -- there's really not much to filter on at all.
```json
{
    "plays": 4,
    "last_watched_at": "2014-10-11T17:00:54.000Z",
    "last_updated_at": "2014-10-11T17:00:54.000Z",
    "movie": {
      "title": "Batman Begins",
      "year": 2005,
      "ids": {
        "trakt": 6,
        "slug": "batman-begins-2005",
        "imdb": "tt0372784",
        "tmdb": 272
      }
    }
```

> Trakt but without filtering by type (I guess Trakt doesn't even have the option to filter that list itself) so on either case there is no way to create a widget based on latest watched element filtered by its genre/keyword.

Not really no. It would have to pull up the TMDb details individually for each item until it hit upon something with the matching keyword/genre -- could be very expensive and long process.

> Hmm, I'm not sure I get it. If I understand correctly, your solution would only let me create a recommendation system from a static film selected the moment the widget is created instead of based on the latest movie/tv show watched that gets updated as I keep watching things.

Yeah they'd be static but you could create multiple different recommendations lists from different movies with a particular keyword and have autowidget select from them at random and then use that as the widget -- the way you get changing recommendations but centred around a specific group of movies based on the keyword.

e.g. Say I want Recommendations for 80s/90s action movies. I could create a series of widgets:
Recommendations based on Robocop
Recommendations based on Aliens
Recommendations based on Predator
Recommendations based on Die Hard
Recommendations based on First Blood

Then I have autowidget select from those five different recommendation lists to create my widget.

It's probably about as close as you're going to get to a recommendations widget based on a type of movie that isn't just the same recommendations.

**Comment by drinfernoo** [comment]
I'd like to throw in and say that is a wonderful usage of AutoWidget. Really good thinking.
