### ISSUE TITLE
Plex player not playing episodes

### ISSUE THREAD

**Issue by daveftw84** [jurialmunkey/plugin.video.themoviedb.helper#224]
It plays movies but not shows. When I hit search Plex. It brings up show as if it is searching for the show by name.

**Comment by jurialmunkey** [comment]
What plex player? The one for Composite that @anxdpanic submitted? Or some other one?

I don't make any players other than Netflix and Youtube -- you'd need to speak to whoever made the player.

There's information about how to make players in the wiki
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

**Comment by daveftw84** [comment]
The one you did and asked how it runs
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/50#issuecomment-581176831

**Comment by jurialmunkey** [comment]
Oh that was just an example to use as a base for someone else to create a plex player. I don't use plex so I have no idea if it works or not and can't test -- the file was simply created from taking the one that was in that thread from openmeta and adapting it to the existing Netflix player. It was never intended as an end product.

**Comment by daveftw84** [comment]
any chance you can help a noob how to write a player? hehe
i saw your comments eariler about taking pictures of how things line up in the addon after search.  
i see that embycon doesnt display the season and episode number in the season folder, so i figured i have to change it to look for the epsiodes title instead. i read your wiki and trying to figure this out. 
https://xxz.pw/4.png
https://xxz.pw/1.png
https://xxz.pw/2.png
https://xxz.pw/3.png
