### ISSUE TITLE
TMDB Scan the whole Tv Shows library every time 

### ISSUE THREAD

**Issue by Nazim1981** [jurialmunkey/plugin.video.themoviedb.helper#227]
I have added and synced Trakt list ( TV Shows ) to my Library and it took 15 hours for 1800 TV shows to add and sync at last its done . now i have added few more TV shows on Trakt list , now when i scan the library TMDB start the whole process from start and i can see TMDB try to add and Skip (some time) those TV shows who already added , it should SKIP all other and detect the new one only but it wont happen any suggestion ?

**Comment by drinfernoo** [comment]
Maybe don't add 1800 shows? 😅

**Comment by Nazim1981** [comment]
I think its a bug if TMDB doesn't recognize the files are already in Library and yet it try to read it thoroughly and wont skip the whole process to find new one , but strangely in the case of Movies section TMDB skips old and add new one instantly .

**Comment by Nazim1981** [comment]
and and more terrible thing TMDB scan TV shows in random order not in Ascending order due to this we cannot found easily what have added or what are pending while scanning .

**Comment by jurialmunkey** [comment]
It has to check each tvshow in order to add new episodes.

Don't add 1800 tvshows for Auto update. That's absurd. You're never ever going to be able to watch that many shows. Stupid shit like this is why I was hesitant to add the auto update feature.

**Comment by JayDee696969** [comment]
Or just use the Trakt sections in the addon instead of scanning anything to Kodi library.
