### ISSUE TITLE
[Request] Add entry to library when added to a Trakt list

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#228]
Would it be possible to automatically add an entry added to a Trakt list to the library when that list is been watched? Ideally that would apply to every list added to library and not just the ones added to the configuration to be refreshed on a timely basis. And if that could trigger a clean up of the library once added so they are immediately scanned would be a plus.

**Comment by drinfernoo** [comment]
Use the official Trakt add-on to sync watched statuses to and from the library.

**Comment by juanma-cvega** [comment]
Sorry, I think I didn't expressed myself properly. I'm not talking about the watched history, I'm talking about the 'Add to library' feature. Currently, any new TV show/movie added through the addon to a Trakt list is not added to the Kodi library. For lists that have already been added to the library, I'd be nice if any new element could be added automatically as well. For Trakt lists that are part of those automatically synced on schedule you would need to wait for the job to trigger. For the ones that are not part of those watched, the entry would never be added automatically. 
In the end, you could just add them yourself through the context menu so it's not a big deal actually. I was just suggesting the option so the addon feels more integrated with the library but I understand that could get complicated if those Trakt lists added to the library through the context are not kept somewhere so the addon is able to know which entries would need to be added and which not.

**Comment by jurialmunkey** [comment]
I don't understand how this would be possible. I would essentially need to be running a command to check the list for changes constantly. It's not like trakt sends out a signal to say the list is changed - Id need to be constantly redownloading the lists and checking for changes. 

Just add the library auto update command to your power menu or main menu and run that when you make changes. 

If you want, I can add a manual command to only check a specific list (essentially same as add list to library context command) - that way you can just check the one list without doing the full scale update.

Checking automatically is not really going to be possible - the frequency of checks would be too high.

**Comment by juanma-cvega** [comment]
There is something I don't get here. Isn't the TMDBHelper options context menu something the addon controls? 

> It's not like trakt sends out a signal to say the list is changed - Id need to be constantly redownloading the lists and checking for changes.

What I mean is not verifying Trakt API itself. Unless they implemented a way for clients to subscribe to changes on their side that'd be a continuously polling that wouldn't make sense. I'm talking about changes done from your addon (or like in this case, the context menu). So any new item added to a Trakt list from within the context menu would automatically add the item to the library as well. But only when that list has been added to the library previously.
I'm pretty much handling my already created Trakt lists from within your addon so, as I said earlier, that would be just a convenience to avoid having to do `TMDBHelper Options -> Add to Trakt list` plus `TMDBHelper Options -> Add to Kodi library` as doing the first part would add the element automatically. By adding stuff only from your addon that eliminates the need to synchronise lists continuously and I could just leave that to liked lists I don't have control over (and that are mostly films which are synchronised much faster).

**Comment by jurialmunkey** [comment]
> I'm talking about changes done from your addon (or like in this case, the context menu). So any new item added to a Trakt list from within the context menu would automatically add the item to the library as well. But only when that list has been added to the library previously.

Ah okay, that makes waaaay more sense than what I was thinking you meant -- that's definitely possible. It would have to be listed as one of the auto-update lists because I don't keep track of other lists that have been added - but should be relatively easily to implement otherwise (just check if it is also a monitored list and also add the item to the library if it is).

**Comment by juanma-cvega** [comment]
> It would have to be listed as one of the auto-update lists because I don't keep track of other lists that have been added

That's what I feared. In my case that wouldn't help much given the limit of 2 lists there is currently as I have lists for movies/tv shows/anime/ovas/kids movies/kids tv shows. But in any case, I can continue doing it manually by adding to library after adding to Trakt list using the context menu. 
In any case, would it be possible to trigger an `Update library` command after adding to Kodi library, so new entries are automatically available? I think Kodi only gives the option to update the library on startup. . And maybe a widgets update as well as an option?

**Comment by jurialmunkey** [comment]
Update library command is triggered after adding.

It updates library properly for me on Windows and LibreELEC after adding an item.

**Comment by juanma-cvega** [comment]
Hmm, ok. Maybe there is something wrong on my end or I didn't see the updated element. In any case, if it works for you, that means it's me who has the problem.

**Comment by jurialmunkey** [comment]
> Hmm, ok. Maybe there is something wrong on my end or I didn't see the updated element. In any case, if it works for you, that means it's me who has the problem.

It's only when you "Add to *Library*" not when you add to a list.

However, I've just added a feature which will allow you to add as many of your own lists to be monitored as you like. It should also now prompt you to update the library from a monitored list when adding an item to it from inside the plugin.

**Comment by juanma-cvega** [comment]
Ah cool! Thanks!
And just to be cleared, this only works with your own lists, liked lists won't work, right?

**Comment by juanma-cvega** [comment]
> as many of your own lists to be monitored as you like

Sorry, I should read more carefully, that answers the question.

**Comment by juanma-cvega** [comment]
Question about this new feature. So now, if I add my lists to the list of monitored ones, the library is going to be updated automatically any time I add a new element to one of those lists from the addon. Given TV shows are automatically updated when new episodes air regardless of whether they are part of a monitored list or not, I shouldn't need the scheduled auto update feature as all elements should already be in the library. Am I right?

**Comment by jurialmunkey** [comment]
Yeah pretty much. As long as you only add things from inside kodi.

**Comment by juanma-cvega** [comment]
Sorry to still use this issue but there is something I think is missing. Would it be possible to have the option to not update the monitored Trakt lists on a scheduled then? Based on my previous comment, I am forced to add my Trakt lists to the list of monitored ones in order to use the new feature. But in my case, I only need them to be monitored to add new entries to the library but not refreshed on a schedule as elements are always going to be there as I'm only using the addon.
