### ISSUE TITLE
[Feature Request] Allow multiple player files per plugin

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#23]
There are a number of third party add-ons that allow for setting various runtime parameters in their URI, aside from media metadata... and in the past, other add-ons that supported this "player file" integration could have multiple player files defined, which would all show up to select from where applicable.

Would that be possible here?

**Comment by drinfernoo** [comment]
An  added bonus of me including the player file shown in #24, is that it shows the `id` and `priority` tags, which could easily be used for identification and sorting of various player files, including per-plugin multiples 😁

**Comment by jurialmunkey** [comment]
You already can have multiple player files. Just create a new `player.json` file with a different name e.g. `netflix2.json`

Some sort of "priority" sort tag is definitely planned. I don't really see the value of the "id" tag though as the file name and/or plugin name already act as unique identifiers.

**Comment by drinfernoo** [comment]
Hmm, from my (limited) testing while working on #22, it seemed that since paths were saved using the plugin as a key, they would overwrite each other when multiple files had the same plugin value. This was especially annoying when one player defined a `play_movie` path, for example, but a different player for the same plugin did not. The key would be created with the first player, but overwritten with a blank value on processing of the next player. This made it so that the player showed up in the list, but with no associated action.

I can look at solving this in a future PR, if you'd like.

**Comment by jurialmunkey** [comment]
Ah, yes you're right. I only quickly tested if it showed up in the list, not whether the action worked. I can see where the issue is - fix incoming shortly.

**Comment by jurialmunkey** [comment]
This commit should hopefully fix the issue https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/079846aaeeb2cd1693a1f422e917734d11aedf72
