### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by ananias47** [jurialmunkey/plugin.video.themoviedb.helper#231]
Hi my friend
First of all thanks for your great work 
I want to ask you if it is possible to  show on trakt-your next episodes not only the name of the episode but also the name of the series and the number of the season and episode e.g. Walking dead s5e01 no Sanctuary instead of only no sanctuary 
Second when you browse on a season of a series to show before the name of the episode the number eg 1.No Sanctuary, 2....
And one last thing when you search a movie or series to show after the name the year they aired 
Eg Joker(2019)
Ps again thanks for great work so far keep up

**Comment by jurialmunkey** [comment]
Unfortunately not possible. Kodi overwrites the episode label depending on the sort method. The episode number is only shown by Kodi if sort method is set to "Episode" -- I've added this sort method in the most recent version.

Adding year to movie title is a bad idea because it means that skins can no longer access the title without the year.

**Comment by ananias47** [comment]
ok my friend thank you for your time

I asked you about the next episodes of trakt because i saw it  on other addons so i thought it may be possible
this is from themoviedb helper
![2](https://user-images.githubusercontent.com/6560173/82202111-19375200-990a-11ea-8144-fc30bb458450.jpg)
and those are from other addons

![1](https://user-images.githubusercontent.com/6560173/82202043-f86efc80-9909-11ea-89a5-4278666cf14b.jpg)

![3](https://user-images.githubusercontent.com/6560173/82202217-46840000-990a-11ea-8638-2c1903c2241d.jpg)

**Comment by jurialmunkey** [comment]
This is only because those addons alter the title field, not the label field. Title field should only be episode name. These addons are abusing the title field to achieve this.
