### ISSUE TITLE
update to feature request

### ISSUE THREAD

**Issue by ananias47** [jurialmunkey/plugin.video.themoviedb.helper#232]
ok my friend thank you for your time
sorry but i dont know how to re-open the old issue so i make new one
I asked you about the next episodes of trakt because i saw it  on other addons so i thought it may be possible
this is from themoviedb helper trakt-progress
![2](https://user-images.githubusercontent.com/6560173/82202111-19375200-990a-11ea-8144-fc30bb458450.jpg)
and those are from other addons trakt progress

![1](https://user-images.githubusercontent.com/6560173/82202043-f86efc80-9909-11ea-89a5-4278666cf14b.jpg)

![3](https://user-images.githubusercontent.com/6560173/82202217-46840000-990a-11ea-8638-2c1903c2241d.jpg)

**Comment by jurialmunkey** [comment]
These addons override the title field which means that skins are never able to get the plain title of the episode. That's a bad approach. Just because it can be done doesn't mean that its the right way to do things.
