### ISSUE TITLE
Add to Library issue

### ISSUE THREAD

**Issue by G-streamer** [jurialmunkey/plugin.video.themoviedb.helper#233]
When I add something to my Kodi Library it doesn't display right away. I have the option "Update after adding item" switched on but it doesn't do it. I can't see what I added until I do a manual Library update. On a side note it would be nice to have "Add to Library" in the main context menu instead of a sub menu of TMDB Options context menu. (Yes, I'm being a picky pain in the ass now. lol)
BTW, I don't use Trakt, I keep my Library within Kodi.

**Comment by jurialmunkey** [comment]
It works properly for me.

The code is there to update the library:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/context.py#L309
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/context.py#L320
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/context.py#L327
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/context.py#L343

Would need a full debug log with debugging turned on to understand why it isn't updating for you.

> On a side note it would be nice to have "Add to Library" in the main context menu instead of a sub menu of TMDB Options context menu. (Yes, I'm being a picky pain in the ass now. lol)

Can't please everyone! 
Other users were complaining about it adding too much clutter to the main context menu, which is why it was added to a subfolder.

**Comment by SirRickie** [comment]
It's not automatically updating for me neither. Only if I do a manual update. I can soon send you a full debug log. There are installed several thirdparty addons. Is this a problem ? Tnx.

**Comment by jurialmunkey** [comment]
> 
> 
> It's not automatically updating for me neither. Only if I do a manual update. I can soon send you a full debug log. There are installed several thirdparty addons. Is this a problem ? Tnx.

I don't really care what you have installed. Would be interested in a log to see why it's not working.

Are all you guys where it's not updating on Android? I wonder if it is a platform specific thing where updating a specific library path isn't working on Android but works on Windows/LibreELEC...

**Comment by jurialmunkey** [comment]
@G-streamer @SirRickie - Can you test latest version and see if it works for you now? Only thing I can think is that Android platforms don't like having the path to the source being passed to them, so maybe I need to do a more generic update rather than only update the specific source.

**Comment by SirRickie** [comment]
Hey, it's working now ! Great job. 
Btw : I'm on Windows 10 (not android).

**Comment by jurialmunkey** [comment]
@SirRickie - Hmm, so strange. It worked perfectly fine for me on Win 10 before. 

Are you using TMDbHelper's default library path or did you add a custom location in the settings? I was using a custom location - I wonder if maybe the `special://` file protocol doesn't get translated properly in the `updatelibrary(video, path)` command.

**Comment by G-streamer** [comment]
Awesome, working for me as well. Thank you.
BTW, I am using Windows 7 for testing Kodi and an Android box for watching Kodi.

**Comment by SirRickie** [comment]
> @SirRickie - Hmm, so strange. It worked perfectly fine for me on Win 10 both before and after these changes.
> 
> Are you using TMDbHelper's default library path or did you add a custom location in the settings? I was using a custom location - I wonder if maybe the `special://` file protocol used in the default path doesn't get translated properly in the `updatelibrary(video, path)` command.
> 
> Oh well. As long as it's working now.

I am using the default library path.
