### ISSUE TITLE
Problem playing show after adding to library

### ISSUE THREAD

**Issue by Wayoff1** [jurialmunkey/plugin.video.themoviedb.helper#236]
I add show to library from tmdb helper. Then when I try to watch a episode, it says can't find next item to play.
I can add and play a movie with no issues.

If I install and use helper from the Kodi repo, it works without this issue.

[Log](https://paste.kodi.tv/abedegiqub)

**Comment by horacio2012** [comment]
Seeing this as well. Weirdly all tv shows i've added are doing this, however the movies are fine. 

"Playlist, can't find a next item to play"

**Comment by SirRickie** [comment]
Same here. I'm on Windows 10.

**Comment by jurialmunkey** [comment]
Oops! Little typo causes big problems...

Should be fixed now. You'll need to remove the .strm files, clean the library, then re-add them.

You should be able to just delete the season folders but leave the base show folders with the .nfo -- if you then clean the library and do an auto-update, it should re-fill the shows correctly.

**Comment by protwloski** [comment]
Has the update been pushed to your Kodi repo? The last version I'm seeing is 2.4.73.

**Comment by jurialmunkey** [comment]
You'll have to wait for @drinfernoo to update the repo. 

Otherwise just install from github using the zip it generates:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/master.zip

**Comment by Wayoff1** [comment]
Thanks for the fix. Worked great 👍
