### ISSUE TITLE
Issue addons crashes on some episodes

### ISSUE THREAD

**Issue by ananias47** [jurialmunkey/plugin.video.themoviedb.helper#238]
Hi when i am trying to see e.g. Arrow s8e8, s8e9, s3e8, flash 3x08 the addons crashes either before showing the generated links or when you trying to play a link
This is happening on every addon i have tried e.g.sh@dow $eren.
Maybe the problem is the special characters ( ) : & on the titles??

**Comment by jurialmunkey** [comment]
Debug log?

**Comment by ananias47** [comment]
https://paste.ubuntu.com/p/WfgHyRfCKz/
![Screenshot_20200527-142529_Kodi](https://user-images.githubusercontent.com/6560173/83013821-509eb080-a026-11ea-9f0b-a4d62f398809.jpg)
![Screenshot_20200527-142027_Kodi](https://user-images.githubusercontent.com/6560173/83013831-5399a100-a026-11ea-822c-2cc7937bd277.jpg)
![Screenshot_20200527-142020_Kodi](https://user-images.githubusercontent.com/6560173/83013837-55636480-a026-11ea-89da-ea0e506b8c20.jpg)

**Comment by jurialmunkey** [comment]
These aren't TMDbHelper errors. These are errors in the addons that you are using. You probably need to fix your player files.
