### ISSUE TITLE
Feature - Add .strm of entire folder/category to library

### ISSUE THREAD

**Issue by rodolfofanti** [jurialmunkey/plugin.video.themoviedb.helper#239]
Hi there,
would it be possible to add the .strm files of an entire folder/category of whatever addon browsed from context menu?

**Comment by jurialmunkey** [comment]
I don't understand what you are suggesting. What do you mean by "entire folder/category"? And what do you mean by "whatever addon browsed from context menu"

**Comment by rodolfofanti** [comment]
For example I would browse to a "Most Popular" category of an addon, press C for context menu and add the whole folder to library rather then the single titles (which is the current status).

This would make what another plugin (Library Integration Tool) does and what make yours one of the most complete I reckon?

**Comment by rodolfofanti** [comment]
Not sure if this makes sense but the bottom line is you basically integrate to library whatever you want.

**Comment by jurialmunkey** [comment]
Very bad idea. Most of these folders are just all items sorted in a particular way. Popular is all movies sorted by popularity. You would be adding 1000s of items and it would take days to complete. 

That type of excessive scraping of data is very disrespectful to the services that provide this data for free and is quick way to get my api key banned. You are essentially asking to download the entire tmdb database. 

That library integration addon is very irresponsible and clearly doesn't care about the possible ramifications to other plugins.
