### ISSUE TITLE
Trailers missing 

### ISSUE THREAD

**Issue by giadokimes** [jurialmunkey/plugin.video.themoviedb.helper#241]
Choosing a movie and pressing "info" displays plot and ratings, but not trailers for most of them.
Tried many different skins and happens in all cases, so not a skin issue. 
All API keys entered properly on the addon itself, plus "Metadata and Artwork module".

**Comment by jurialmunkey** [comment]
To reduce loading time, additional details are only retrieved if the item has been cached. The service monitor provides trailer information, so skins can use that to supply trailers for items that haven't yet been cached (eg I do this in Arctic Horizon)
