### ISSUE TITLE
Authorizing Trakt from settings gives error, opening addon gives another one

### ISSUE THREAD

**Issue by cgcgcgcgcg** [jurialmunkey/plugin.video.themoviedb.helper#244]
I managed to authorize Trakt by opening addon and navigating to Trakt / TV Shows Collection, but it gives this error when trying to use the addon (see pic).
Is that because OpenInfo is installed on my linux laptop?
![ksnip_20200603-175641](https://user-images.githubusercontent.com/38960370/83652831-bc06f600-a5c3-11ea-9ef6-5ef270f6ed97.png)

**Comment by drinfernoo** [comment]
Those errors are not related to TMDbHelper at all.

**Comment by jurialmunkey** [comment]
Yeah clearly that log refers to extendedinfo (ie openinfo). Nothing at all todo with Tmdbhelper.

**Comment by cgcgcgcgcg** [comment]
You both are right about above error, so I completely removed OpenInfo and tried TMDBhelper again and got this error -see pic.
This might be a linux specific error, since a friend using windows and a shield doesn't have an issue with same version of Tmdbhelper.
![ksnip_20200605-063508](https://user-images.githubusercontent.com/38960370/83834493-19e82a80-a6f7-11ea-9fc4-6401c2642dde.png)

**Comment by cgcgcgcgcg** [comment]
Just updated to version 2.4.82 and got same error:
![ksnip_20200605-064037](https://user-images.githubusercontent.com/38960370/83834679-8cf1a100-a6f7-11ea-8386-12e3c66bcc3a.png)

**Comment by drinfernoo** [comment]
That appears to be an issue with the Android version of PIL, right @jurialmunkey?

**Comment by cgcgcgcgcg** [comment]
Thank you @drinfernoo, I installed Tmdbhelper on an empty Kodi and it worked fine so that PIL android version might be the issue, still have no clue about getting the linux version (if there is one) but I'll look it up.

**Comment by drinfernoo** [comment]
@cgcgcgcgcg Are you on Android? And what version of Kodi?

**Comment by cgcgcgcgcg** [comment]
> @cgcgcgcgcg Are you on Android? And what version of Kodi?

I'm using Kodi v18.6 and v18.7 (on the empty Kodi, using flatpak) on latest Manjaro Linux.
I found a PIL version in System / Manage Dependencies that might be android only and cause this.
No other version to choose from though.

**Comment by cgcgcgcgcg** [comment]
I found script.module.pil and will replace and test current one soon.

**Comment by drinfernoo** [comment]
@cgcgcgcgcg There should be no reason to have an Android-only module on a Linux install... How would it have gotten there? Are you using builds?

**Comment by jurialmunkey** [comment]
It's a problem specific to Manjaro Linux using a version of numpy module that is different to the one included with Kodi's built-in python interpreter

**Comment by jurialmunkey** [comment]
According to this comment https://github.com/sualfred/script.embuary.helper/issues/28#issuecomment-554781105 - downgrading numpy module to version 1.15.4 will resolve the issue.

**Comment by cgcgcgcgcg** [comment]
> According to this comment [sualfred/script.embuary.helper#28 (comment)](https://github.com/sualfred/script.embuary.helper/issues/28#issuecomment-554781105) - downgrading numpy module to version 1.15.4 will resolve the issue.

Thank you, that was all I needed.
In case another Linux user has this issue -since Linux uses both 3.8 and 2.7 Python, it's a bit tricky-, here are the necessary commands:
sudo python2.7 -m ensurepip --default-pip
sudo python2.7 -m pip install numpy==1.15.4
![ksnip_20200605-221544](https://user-images.githubusercontent.com/38960370/83914835-b7387280-a77a-11ea-9d6e-51dbdf53d4b1.png)
