### ISSUE TITLE
Empty SmartPlayList On selecting the Create Library from Trakt List option

### ISSUE THREAD

**Issue by sathish804** [jurialmunkey/plugin.video.themoviedb.helper#248]
Hi Developer,

I am on latest version of the TMDB Helper Addon.
I authorized trakt and selected create library from Trakt List option from Library section in settings.
Its created a Smart Play List under play lists but the play list is empty.
Screen recording of the issue can be find here.
https://imgur.com/a/LHfNHza

Regards,
Sathish.

**Comment by drinfernoo** [comment]
You haven't added the items your library via a media source. You need to add the "movies" and "tvshows" folders from `addon_data/plugin.video.themoviedb.helper` as media sources, and scan them into your library.

All you've done so far is add the files.

**Comment by sathish804** [comment]
Thank You!!
