### ISSUE TITLE
Context menu does not have TMDBHelper Options

### ISSUE THREAD

**Issue by patel-jeel92** [jurialmunkey/plugin.video.themoviedb.helper#250]
TMDbHelper > Trakt > Your Lists

Then open the context menu on the list to add to the library
Context Menu > TMDbHelper Options > Add to Library

You can also add any lists from other users that you've liked in the "Liked List" section. You can like a list by opening it on the Trakt website and pressing the thumbs up button
e.g. You could add this IMDb Top 250 list by opening this link, clicking the thumbs up, and then navigating to Liked Lists in TMDbHelper and Adding to Library via context menu
https://trakt.tv/users/nielsz/lists/active-imdb-top-250

You can also add any list from trending/popular lists.

You can also auto sync from lists in 
`TMDbHelper Settings > Library > Auto-update library from Trakt list(s)`

_Originally posted by @jurialmunkey in https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/242#issuecomment-636409414_

Was looking through this issue and tried adding Trending Movies list from trakt into my kodi library. However, I cant add them since the option to add to library in context menu does not exist. I am on version 2.4.83

**Comment by drinfernoo** [comment]
You can only sync your own personal and/or liked lists, not each add-on section.

**Comment by patel-jeel92** [comment]
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/242#issuecomment-636409715

In this it is mentioned that it can be done for trending or popular lists

**Comment by patel-jeel92** [comment]
Sorry, I just figured it out. Thank you for your help!

**Comment by drinfernoo** [comment]
Ah, those are those are the "Trending *Lists*" and "Popular *Lists*" sections. Those ones can do it as well. Basically anything that is a Trakt *list*, as can be managed on the website.
