### ISSUE TITLE
Netflix Player not working

### ISSUE THREAD

**Issue by abbaskip** [jurialmunkey/plugin.video.themoviedb.helper#251]
I use TMDB Helper as my primary driver and generally set the Netflix player up as my default - but I've noticed recently (around a month ago) that Community stopped playing from Netflix when using TMDB.

Now it seems the Last Dance is doing the same.

Strangely if I context - play using, then choose search in Netflix it shows it first; but if I choose play in Netflix it works anymore.

**Comment by drinfernoo** [comment]
I've actually made a pull request (which has been merged) to the Netflix add-on to restore the functionality. He hasn't released a new version yet, but you can download the zip from GitHub for the time being, and it will include the fix.

**Comment by abbaskip** [comment]
> I've actually made a [pull request](https://github.com/CastagnaIT/plugin.video.netflix/pull/681) (which has been merged) to the Netflix add-on to restore the functionality. He hasn't released a new version yet, but you can download the zip from GitHub for the time being, and it will include the fix.


Thanks. Working now - but it now makes me select a Netflix profile each time. Is this a new 'feature' of the Netflix add-on?

**Comment by drinfernoo** [comment]
@abbaskip Yes, I believe it is. If you set the add-on to auto-login, it should skip it, if I'm not mistaken.
