### ISSUE TITLE
Rating of movies in Trakt

### ISSUE THREAD

**Issue by SirRickie** [jurialmunkey/plugin.video.themoviedb.helper#252]
Added TV show in Kodi library via TMDB Helper. When finishing an episode, as usual, a small Trakt screen shows up where I can rate the episode (which is great). Now when finishing a movie (which is also added in library via TMDB), this screen does not show up. So each time, I have to go to Trakt website to add my rating (btw, with OpenMeta this works fine). Can this be fixed. Tnx.

**Comment by jurialmunkey** [comment]
Nothing to do with tmdbhelper. That's the trakt addon which adds ratings.
