### ISSUE TITLE
movie length (screen time) and MPAA ratings arent scrapped

### ISSUE THREAD

**Issue by daking1512** [jurialmunkey/plugin.video.themoviedb.helper#253]
im having issues with both TMDB and Trakt lists in the Tmdb helper addon, non of the movies/shows have MPAA ratings, and the movies dont have movie length scrapped

fresh installation, using Titan Bingie skin

**Comment by jurialmunkey** [comment]
Additional details are only shown if they've been cached previously by either the service monitor or by accessing the detailed item of the item (ie click on it with default action in addon settings as browse not play).
