### ISSUE TITLE
[Request] Add ListItem.Property(widget) as a Service Monitor Property

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#256]
Would this be possible? That way it could be grabbed without knowing the container ID? 

EDIT: Also, might I suggest a more descriptive name, like possibly `TMDBHelper.WidgetContent`?

**Comment by jurialmunkey** [comment]
@drinfernoo - What would this be used for though? Because you can't use it as the widget label because it will change depending on what widget is focused.

**Comment by drinfernoo** [comment]
@jurialmunkey Ah, you're right! I hadn't thought of that...

I actually wanted to use it as a workaround for my ListItem property dilemma, but I think we're [closing in on a solution](https://forum.kodi.tv/showthread.php?tid=355209&pid=2959827#pid2959827) 😁

**Comment by jurialmunkey** [comment]
Ah that looks promising! Amazing if we can get properties via JSON-RPC!
