### ISSUE TITLE
special character  (french title)

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/plugin.video.themoviedb.helper#258]
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/4822552/kodi.log)

Hi Jurialmunkey, hope you are doing well  :)

I came across an issue when trying to search a movie who is not in my kodi library AND having a special character in title... 
ex, when I search for "La guerre des étoiles", Themoviedb helper show me a error and I can not see the movie informations.. But, If I search for a movie having special character who is present in my kodi library, there is no problem.

I attach my log if it can help.
Thanks for the great addon :)

**Comment by jurialmunkey** [comment]
@alKODIque - What is your player file? The issue is with your default player, not with TMDbHelper.

**Comment by jurialmunkey** [comment]
@alKODIque - Latest commit will fix the exception but really your player file should be using `{*_url}` type keys.

**Comment by alKODIque** [comment]
Ok, i'm not completely sure of what you meam by this.... but i have only 1 player in my "players" folder and i think it's related to this...

Many thanks Jurialmunkey , i do my best to learn and you are one of my best "learning tool" haha
