### ISSUE TITLE
[Feature Request] Movie Genre Icons

### ISSUE THREAD

**Issue by Satris404** [jurialmunkey/plugin.video.themoviedb.helper#260]
Hi,

I want to specify that I am not a skinner. I like to use theMovieDBhelper to create widget on my Kodi main menu and to display trending movies, popular shows, etc. I would like to create a "Genre" widget on my menu so I can select a genre and navigate through the movies shows of that genre. However, the icons that are shown are the TMDB green images. Is there anyway that the icons displayed are those of the "Movie genre icons" add-on instead?
Also, a "Year" section that would classify content by year would be very nice. 

Let me know if the way I use the add-on is not the intended one, as my request wouldn't be relevant. If that's the case, kindly suggest me an alternative way to achieve what I'm looking to do. 

Thank you

**Comment by jurialmunkey** [comment]
You can use the "Discover" section to view movies/tvshows by Year. Just add a rule for "primary release year" with the year that you want to view then click "Discover Movies w/ Below Settings" to view the movies from that year. You can use the context menu to favourite it, if you want to use that setup elsewhere.

Genre icons support is up to skins to implement. For instance, in my skin "Arctic Horizon", TMDbHelper Genre Widget looks like this:

![Honeyview_screenshot038](https://user-images.githubusercontent.com/4618719/86009386-812a9d80-ba5d-11ea-886f-a6f781a1f261.jpg)

**Comment by Satris404** [comment]
Hi jurialmunkey,

Thanks for the info. I'm using Arctic Zephyr 2, I though that feature would have been implemented in that theme. Is there a particular settings I have to configure to make this work? Or should I make a feature request on Arctic Zephyr 2 Github? haha

![Genre icons](https://user-images.githubusercontent.com/29675522/86020728-47727c00-b9f6-11ea-9b28-6744ff72a4c9.png)

**Comment by jurialmunkey** [comment]
It's not supported in AZ2 as far as I recall.
