### ISSUE TITLE
[Documentation] Library Integration

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#263]
It would be *sweet* if there was one page in the wiki with (at least) most of the information about library integration with TMDbHelper 😉

**Comment by jurialmunkey** [comment]
I'm not really sure what there is to write about it? Isn't it pretty self explanatory and basic? Add to library and then scan source then click item in library... 

The wiki is mostly there to document the technical aspects for skin implementation and player creation -  I get the benefit of having some tutorial pages, but I personally don't really have the time to write a user manual that's a step-by-step hand holding of basic features available in the plugin.

If anyone wants to submit a frequently asked questions write up, I'm happy to include it in a user FAQ section.
