### ISSUE TITLE
[Bug/Feature Request] Include movies with no date info to the "Hide unaired movies" option.

### ISSUE THREAD

**Issue by tjamieg** [jurialmunkey/plugin.video.themoviedb.helper#264]
Can you please include movies with no date info to the "Hide unaired movies" option?

I recently added a pile of unreleased movies to my Trakt watchlist for the future, and because some of them are so new, the release dates are not populated, and so they are still showing up although I have the "Hide unaired movies" option checked.

**Comment by jurialmunkey** [comment]
Ah, I didn't think about empty dates. I wonder if there's any shows/movies from the past without release dates? Hopefully there aren't that many -- I'd expect pretty much most to have dates of some kind.
