### ISSUE TITLE
Trakt - NextUp and Resume time

### ISSUE THREAD

**Issue by sathish804** [jurialmunkey/plugin.video.themoviedb.helper#265]
Dear Developer,

Thank You for wonderful add-on. I see 2 issues with the add-on

1) Trakt NextUp  List, in TMDB helper addon under trakt the NextUp episodes are not being shown when the Your Next Episodes is selected. Its showing some other list rather than the Integrated Trakt Account  next up list.
2) Trakt Resume, Wheb a video is played on any supported add-on using players option like Seren, and if the video is stopped in middle the resume point is stored in Trakt. But when the same video played on the same add-on then its starting from first rather than the resume point stored in the Trakt

**Comment by drinfernoo** [comment]
Regarding #2, resuming is handled entirely by the add-on that handles playback, not by TMDbHelper.

**Comment by sathish804** [comment]
I agree on the point that addon handles the resume of a video. This is working if I an playing the video from Seren trakt collection. Via tmdb helper if we can pass the resume point for the addon being called might solve this for trakt collection and watch list titles. 
![Screenshot_20200703-230539](https://user-images.githubusercontent.com/14090242/86497575-771cdd80-bd82-11ea-8a26-261758e257b5.jpg)
![Screenshot_20200703-230500](https://user-images.githubusercontent.com/14090242/86497576-77b57400-bd82-11ea-86d0-aa04807ac58b.jpg)

**Comment by drinfernoo** [comment]
@sathish804 Resume time parameters are not something that is handled by TMDbHelper, and are typically not handled via a URL call at all, which is how TMDbHelper players *work*.

Either way, this isn't really a TMDbHelper issue at all.

**Comment by jurialmunkey** [comment]
1. Yes it does. "Your Next Episodes" displays the Next Episode to Watch *according to your Trakt account* for each of your recently watched shows. Depending on your TMDbHelper settings, the episodes are either in order of airdate (newest episodes at the front) or recently watched (most recently watched shows at the front). There is no such thing as an "Integrated Trakt Account next up list" on the Trakt website, so I have no idea what you're comparing this to but I can say with certainty that it shows the next episode for each show according to your Trakt account.

2. Already answered by drinfernoo above.
