### ISSUE TITLE
Missing TMDB Artwork for show in library with full local artwork

### ISSUE THREAD

**Issue by henryjfry** [jurialmunkey/plugin.video.themoviedb.helper#270]
I've got a show in my library (Better Off Ted - TMDB 7777) which was returning the default fanart "plugin.video.themoviedb.helper/fanart.jpg" because TMDB doesn't have any backdrops for this show.

However this show exists in my library and has a full complement of artwork attached from TVDB/Fanarttv. Would you be able to implement a Library lookup for artwork and only default to online lookups where no art exists?
This would presumably be better generally as it would be faster and prevent tmdbhelper users from downloading the same artwork which they have already populated to their library and overtaxing the various API's

If added my own lookup to container.py 

`	    import urllib, json
            kodi_params = ('{"jsonrpc": "2.0", "params": {"sort": {"order": "ascending", "method": "title"}, "filter": {"operator": "is", "field": "title", "value": "'+tvshowtitle+'"}, "properties": []}, "method": "VideoLibrary.GetTVShows", "id": 1}')
            json_result = xbmc.executeJSONRPC(kodi_params)
	    json_object = json.loads(json_result)

	    try:
	            tvshow_id = json_object['result']['tvshows'][0]['tvshowid']
	    except:
		    tvshow_id = None
	    if tvshow_id <> None:
		    kodi_params = ('{"jsonrpc":"2.0","method":"VideoLibrary.GetTVShowDetails","params": {"tvshowid": '+str(tvshow_id)+', "properties": ["art"]},"id":1}')
	            json_result = xbmc.executeJSONRPC(str(kodi_params))
		    json_object = json.loads(json_result)
		    lib_fanart = 'http://USER:PASSWORD@127.0.0.1:8081/image/'+ urllib.quote_plus(json_object['result']['tvshowdetails']['art']['fanart'][:-1])
		    lib_poster = 'http://USER:PASSWORD@127.0.0.1:8081/image/'+ urllib.quote_plus(json_object['result']['tvshowdetails']['art']['poster'][:-1])
		    lib_clearlogo = 'http://USER:PASSWORD@127.0.0.1:8081/image/'+ urllib.quote_plus(json_object['result']['tvshowdetails']['art']['clearlogo'][:-1])
		    lib_clearart = 'http://USER:PASSWORD@127.0.0.1:8081/image/'+ urllib.quote_plus(json_object['result']['tvshowdetails']['art']['clearart'][:-1])
		    lib_banner = 'http://USER:PASSWORD@127.0.0.1:8081/image/'+ urllib.quote_plus(json_object['result']['tvshowdetails']['art']['banner'][:-1])
		    lib_landscape = 'http://USER:PASSWORD@127.0.0.1:8081/image/'+ urllib.quote_plus(json_object['result']['tvshowdetails']['art']['landscape'][:-1])

	    if i.poster == None and tvshow_id <> None:
		i.poster = lib_poster
	    if (i.fanart == None or 'plugin.video.themoviedb.helper/fanart.jpg' in i.fanart) and tvshow_id <> None:
		i.fanart = lib_fanart
	    if i.tvshow_clearart  == None and tvshow_id <> None:
		i.tvshow_clearart  = lib_clearart
	    if i.tvshow_clearlogo  == None and tvshow_id <> None:
		i.tvshow_clearlogo  = lib_clearlogo
	    if i.landscape   == None and tvshow_id <> None:
		i.tvshow_landscape  = lib_landscape
	    if i.tvshow_fanart == None and tvshow_id <> None:
		i.tvshow_fanart = lib_fanart
	    if i.tvshow_landscape   == None and tvshow_id <> None:
		i.tvshow_landscape  = lib_landscape
	    if i.tvshow_banner == None and tvshow_id <> None:
		i.tvshow_banner = lib_banner
	    if i.tvshow_poster == None and tvshow_id <> None:
		i.tvshow_poster = lib_poster
`
Which does work however i've had to convert the kodi "image://" to a valid url with the authentication as I have a username setup on my kodi install.
So would you have a better method for retrieving artwork from the library and using local art rather than always using tmdb art?

Even if its been cached its still going to keep looking up art you already have.

**Comment by jurialmunkey** [comment]
![Honeyview_screenshot071](https://user-images.githubusercontent.com/4618719/87214265-6d8d0a00-c36e-11ea-9b6a-85cb23fc12e1.jpg)

That's what this option does. Is it not working for you?

Also, artwork is provided by TMDb in the base API call, so there isn't any additional lookup (unless you specifically enable fanart tv lookups). Images are cached according to URL and are directory agnostic, so Kodi will use the locally cached image if it is from the same URL regardless of where it appears (e.g. if TMDbHelper uses an image from the same URL as an item in the library, then Kodi will use the cached image for the library item rather than re-downloading the image)

**Comment by jurialmunkey** [comment]
I just tested with "Better Off Ted" with that option enabled and fanart was working for me. Nonetheless, the commit referenced above should provide some better fallbacks for artwork.

Let me know if it is working for you.

**Comment by henryjfry** [comment]
I was fairly certain I had that library information setting enabled, hence me puzzling over why the artwork was missing, but i just checked and I must not have re-enabled after the last time i wiped my settings.
So i enabled it and commented out the bits that I had added and the expected artwork is now showing up.

So thanks for looking into this.
