### ISSUE TITLE
[Feature Request]Saved Discover Rules- rename, delete etc.

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/plugin.video.themoviedb.helper#274]
For the newly introduced Saved Discover Rules please include context menu options to delete, rename and edit individual entries.
I know you are planning to do that anyways, thought of having a tracking ticket :)

**Comment by jurialmunkey** [comment]
You should now be able to rename and delete from the context menu.

Edit rules is going to be slightly more challenging.
