### ISSUE TITLE
Auto update library items added from a list on start up

### ISSUE THREAD

**Issue by patel-jeel92** [jurialmunkey/plugin.video.themoviedb.helper#279]
I have added my Trakt list to my Kodi library using the context menu. However, I am not sure if this is implemented yet or i need to submit a feature request for it. I would like to know if the library items added from the list auto update if you add new movies or TV Shows to your custom list in Trakt.

**Comment by jurialmunkey** [comment]
Add the Trakt list to your auto-update lists in the TMDbHelper settings:

![Honeyview_screenshot075](https://user-images.githubusercontent.com/4618719/88752103-6b171680-d19c-11ea-8b6f-c34c9bddcd80.jpg)

**Comment by patel-jeel92** [comment]
Ah perfect! Thank you!
