### ISSUE TITLE
[Feature request] Default to Show info & videoinfo integration

### ISSUE THREAD

**Issue by dairefagan** [jurialmunkey/plugin.video.themoviedb.helper#283]
Can you please consider adding an option so that the default select action can be set to show information for different media? This would allow users of videoinfo in AuraMod to see it when not just using TMDBH widgets on their homescreen, but also when they go into lists or browse lists in the mod.

The above is only worthwhile if there is proper functionality in videoinfo. If getting this to work requires something on TMDBH's side, could you please also integrate videoinfo's features Quickplay and More episodes. Right now Quickplay will always play s01e01, and selecting more episodes returns the original screen.

**Comment by drinfernoo** [comment]
You can press `I` on your keyboard, or open the context menu and choose "Information" in order to pull the information window on any item.

"Quick Play" and "More Episodes" are a skin implementation that the AuraMOD developer has done, and likely hasn't updated in quite a while.

**Comment by jurialmunkey** [comment]
What drinfernoo said.

In addition, there's also an option already in Kodi settings to set default select action to show information.
`Settings > Media Settings > Videos > Default select action (Show information)`

If you want that setting to open info directly from a TMDbHelper list (i.e. skip the detailed item landing page), then you will want to also change the default select action in TMDbH settings from "Browse" to "Play / Open".
`TMDbH Settings > Navigation > Default select action in addon (Play / Open)`

**Comment by dairefagan** [comment]
> You can press `I` on your keyboard, or open the context menu and choose "Information" in order to pull the information window on any item.

Thanks but I am hoping it may be possible to automate this as it works for shows in TMDBH widgets.

> "Quick Play" and "More Episodes" are a skin implementation that the AuraMOD developer has done, and likely hasn't updated in quite a while.

I have provided Serpentdrago with a log and he is reviewing this.

> In addition, there's also an option already in Kodi settings to set default select action to show information.
> `Settings > Media Settings > Videos > Default select action (Show information)`

Thanks for the input. Although I had already enabled `Settings > Skin Settings > Default Select Action - Show Information` for movies, shows, and episodes, I had missed that Videos option.
 
> If you want that setting to open info directly from a TMDbH list, then you will want to also change the default select action in the addon settings from "Browse" to "Play / Open".
> `TMDbH Settings > Navigation > Default select action in addon (Play / Open)`

What you have mentioned, which sounds like what I am after, AuraMod's VideoInfo opening for shows and movies by default in TMDBH lists just like it does for TMDBH widgets on the homescreen.
 
> This setting skips the detailed item page that opens by default when you click on a movie/show/person in TMDbH - i.e. it will skip the page that allows you to open other related lists like cast or recommended.

With that settings now also enabled, it does skip the detailed item page but it just displays season 1 and season 2 rather than VideoInfo which your previous comment seemed to suggest was possible?
