### ISSUE TITLE
Trending, Popular, Liked lists error

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#29]
Getting an error on the latest version when trying to enter Trending, Popular and Liked list folders. kodi log with error message:

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/3982206/kodi.log)

**Comment by jurialmunkey** [comment]
Whoops! Stupid error on my part. Should be fixed now.

**Comment by jurialmunkey** [comment]
@drinfernoo - if you can pull in this 2.0.11 version to the repo when you get a chance, that would be great. The 2.0.10 version is broken for these trakt lists as reported by skyfsza here and 2.0.11 fixes the issue.

**Comment by skyfsza** [comment]
Can confirm it's working now, thanks!
