### ISSUE TITLE
Players not working

### ISSUE THREAD

**Issue by Desperados85** [jurialmunkey/plugin.video.themoviedb.helper#293]
So I finally made the switch from OpenMeta to TMDB Helper.. 
Created custom Trakt lists and added them to my library. Everything seemed fine, artwork scraped and everything. 
So I was testing a few movies and tv shows but everytime I try to play a video I get an error message.. Restarting Kodi didn't help.. 
So I enabled the debug log in TMDB Helper settings, restarted Kodi, tried 2 titles, V for Vendetta and Mr. Robot.. Hope the log is ok, this is the first log I ever made.. If you need more info, let me know! 

https://paste.kodi.tv/tinexopuqu

**Comment by drinfernoo** [comment]
To me it looks like you're using malformed players... Double check that the JSON is correct here: https://jsoneditoronline.org/

**Comment by Desperados85** [comment]
I only activated the players from this link; http://bit.ly/tmdbplayers
Have the players changed?
