### ISSUE TITLE
Install players from url slight issue

### ISSUE THREAD

**Issue by SerpentDrago** [jurialmunkey/plugin.video.themoviedb.helper#30]
When installing players from url . 

You must enter url , then click ok in settings . Then go back to be able to "install players from url" 

instead of expected behavior of just being able to enter the url and it installing directly

**Comment by drinfernoo** [comment]
I didn't have this behavior when I was testing, but I'll look into it.

**Comment by SerpentDrago** [comment]
If players url had already been entered in , it will work , this is tested from a blank / fresh install

**Comment by drinfernoo** [comment]
That may just be "the way it is"... since it reads the URL directly from the setting, so if the setting hasn't been "set" yet, it doesn't have anything to read.

**Comment by jurialmunkey** [comment]
@drinfernoo - I'm thinking of maybe combining the two into one setting. What do you think?  Can you foresee any issues?

i.e.
1. User clicks setting "Download Players From Url"
2. Keyboard pops-up for user to enter url. If they previously had entered a url it is autofilled.
3. Downloader function runs (maybe need another Yes/No confirm dialog before this stage?)

**Comment by jurialmunkey** [comment]
See latest commit https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/92700b4d16710883a04c25ed830a8cdef7918d96

**Comment by drinfernoo** [comment]
Yep, I like this. That seems like a good way to do it.
