### ISSUE TITLE
TMDB Error after the last update

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/plugin.video.themoviedb.helper#300]
![3DAE3145-2D0D-40D2-8224-0367ECCAD362](https://user-images.githubusercontent.com/49699869/93137725-efb9e780-f6ab-11ea-9344-70a162344784.jpeg)
Really appreciate any feedback or help on what could be triggering this error, And when this error pops up it affects all my track widgets coming from TMDB helper

**Comment by jurialmunkey** [comment]
Full debug log please.

**Comment by xyzfre** [comment]
Turns out to be it was a Trakt issue on their end everything seems to be working fine now really appreciate your response and all your hard work TMDB Helper is an amazing addon
