### ISSUE TITLE
TMDBH library not restoring with OpenWizard

### ISSUE THREAD

**Issue by dairefagan** [jurialmunkey/plugin.video.themoviedb.helper#302]
I mentioned this in another ticket but there was no debugging logs provided, and strictly that ticket is for a different issue. I now provide a log for this issue, with Kodi debugging and TMDBH debugging both turned on promptly after the OpenWizard restore - [kodi-postrestore.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5252156/kodi-postrestore.log)

The issue is that although in _Kodi Settings >> Media >> Library >> Videos >> TV Shows_ I can see a combination of TV Shows from my local NAS and those that were created by TMDBH with .strm files for each episode, when I select TV Shows from the homescreen of Kodi I see only the 54 shows from my NAS, despite attempts to rectify this.

The steps I followed after a clean install of Kodi on Ubuntu 20.04:

1. Installed OpenWizard and at the prompt enable only delete cache on startup, disable any other options enabled by default, and leave all other options disabled. Restore backup taken from good working build of Kodi with TMDBH on a Nvidia Shield Android TV, accepting the prompt to force quit.

2. As restoring from Android to Ubuntu, and as the NAS Samba share is running on a deprecated version of DD-WRT, before setting the file read only, I changed _~/.kodi/.smb/smb.conf_ to:

 [global]
	lock directory = /home/daire/.kodi/.smb/
	client min protocol = NT1
	client max protocol = SMB3
	name resolve order = bcast host
	include = /home/daire/.kodi/.smb/user.conf

3. Reopened Kodi and quickly enabled debug logging in the main settings and the settings of TMDBH before closing Kodi and reopening it and leaving it idle.

4. Monitored tail of kodi.log from terminal, and after TMDBH started updating, finished updating, and triggered a library scan, I cleaned the library, and selected _Scan for new content_ on _Kodi Settings >> Media >> Library >> Videos >> TV Shows_ , and cleaned the library again.

I attach a screenshot of the shared TV Show library source, and where the entry for my TMDBH Trakt playlist points:

![TV Shows library source](https://user-images.githubusercontent.com/12515718/93717378-4c664800-fb6d-11ea-9d5a-a16c6db49fca.png)

Still when I open TV Shows from the Kodi homescreen it only displays my local NAS shows. 

I have selected update library from the lefthand side of the Kodi media settings which seems to now be adding the TV Shows, but 
should my TV Show library not have been backed up and restored by OpenWizard or is there something else I need to do to help that happen? If the issue is due to the platform change, is there a workaround considering both my local NAS library and TMDBH library are relatively in the same place?

**Comment by drinfernoo** [comment]
Sounds like your backup contains a `sources.xml`, which is being restored, but doesn't contain the entries for TMDbHelper's source folders.

**Comment by dairefagan** [comment]
> Sounds like your backup contains a `sources.xml`, which is being restored, but doesn't contain the entries for TMDbHelper's source folders.

I had thought that would be it, perhaps I enabled or forgot to enable something, but I just used meld to compare a freshly extracted from backup sources.xml file, with that of the one from the current install, which started re-adding the shows into the library on update library, and they are identical. Perhaps there is some other issue with the file: [sources.xml](https://paste.ubuntu.com/p/MqYZQ9KPwy/) or there is something in the logs?

From where VideoInfoScanner starts scanning on line 24687, there are many lines similar to:

`2020-09-20 17:27:39.363 T:140690624763648 WARNING: Process directory '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/tvshows/30 Rock/' does not exist - skipping scan.`

I wonder if the issue is that TMDBH or Kodi uses absolute references somewhere rather than the special relative references, and if this is something that the 'convert to special option' in OpenWizard before backup would resolve?

**Comment by dairefagan** [comment]
If it helps here is the OpenWizard log: 
[wizard.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5252898/wizard.log)

**Comment by drinfernoo** [comment]
Ah, are you not including addon data for TMDbHelper when you do your backup?

**Comment by dairefagan** [comment]
> Ah, are you not including addon data for TMDbHelper when you do your backup?

From the Back up/Restore menu of OpenWizard I select _[Back Up] Build_, and then when I am prompted I select _Include data_. I thought that this backed everything up in such a way that I could restore everything on the same system or another, is this not the case?

Maybe I need to also separately select _[Back Up] Addon_data_ and when restoring first restore build, and then afterwards separately addon_data?

While I am asking you about this, is there a general usage guide for OpenWizard?

**Comment by dairefagan** [comment]
@drinfernoo Can you please let me know if I should be doing something differently than I describe, or if there is anything I could try? I want to get right so I have it to come back to before I move on with the build!

**Comment by dairefagan** [comment]
On my desktop I made a backup and restored it to a clean install of the desktop, as far as I know exactly as I did previously although the source that time was the Shield, otherwise I am not sure what the difference was. After I can test on a new build on the Shield I will post here on whether I experience the same issue.

**Comment by s0ulslack** [comment]
Post on openwizards GH?

**Comment by jurialmunkey** [comment]
Closing this as it doesn't appear to relate to any issue in TMDbHelper itself.
