### ISSUE TITLE
[Request]Manually mark as watched from the context menu

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/plugin.video.themoviedb.helper#303]
Title of the thread basically :)
Pls refer below reddit post for details
https://www.reddit.com/r/Addons4Kodi/comments/ivxsz8/unable_to_mark_episodes_as_watched_in_tmdbhelper/

**Comment by jurialmunkey** [comment]
You already can. under the tmdbhelper options in context menu there's an option to add to trakt history

I can't control what Kodi's built in "mark as watched" does.

**Comment by SerpentDrago** [comment]
This is my bad , I did not see "trakt history" every addon and other convention has always called this "mark or unmark as watched" 

Thanks Jurial :) you can close this

**Comment by onlytanmoy** [comment]
Thanks guys 😊 closing this ticket.

**Comment by jurialmunkey** [comment]
> 
> 
> This is my bad , I did not see "trakt history" every addon and other convention has always called this "mark or unmark as watched"
> 
> Thanks Jurial :) you can close this

Yeah it might make more sense for it to be called Mark Watched/Unwatched even though technically it does more than that - i.e. it doesn't _just_ mark as watched but actually adds a timestamp to the item and syncs it back into the history.
