### ISSUE TITLE
[Request] Auto try next Addon when video failed to play or no sources found.

### ISSUE THREAD

**Issue by mathu204** [jurialmunkey/plugin.video.themoviedb.helper#305]
Not sure if this feature request has already been made or if its possible or not.
Basically the idea is that lets say I have 3 addons in my TMDB Helpers list: Netflix, Disney Plus and Amazon Prime

I click a movie such as Avengers Infinity War. My default player is Amazon Prime. It doesn’t have that movie so no source is found and when TMDB Helper sees that no video is playing it would automatically try the next addon until a video has started to play. You would or would not be able to set a sequential preferred order of addons to try.

**Comment by drinfernoo** [comment]
You would have to leverage fallback players.

**Comment by s0ulslack** [comment]
Good job associating questionable activity, come ppl damn

**Comment by mathu204** [comment]
> Good job associating questionable activity, come ppl damn

Hey man no need to be a dick about it

**Comment by jurialmunkey** [comment]
Answered by drinfernoo above.

**Comment by mathu204** [comment]
> Answered by drinfernoo above.
Hi, not sure if this will open this back up I dont want to, I just need some help with using the Fallback players. 
I downloaded a player with a fallback player integrated (Disney+ with secondary addon as fallback [Addon 2]) from dr.infernoos repo

when I play a movie: (i tried Avengers:Endgame bc I knew it would be named differently in D+) it says item not found and then brings me back to the Choose Action dialog with players rather than playing with Addon 2. At this point the D+/Addon 2 player is gone. 
_The fallback movie action from D+ to Addon 2 doesn't work when player fails to find playable item._

I tried to play the movie Avatar (blue ppl) with the same player and it found the movie and played it.
_The player can correctly play a movie if found in D+ first like intended._

I tried to then play an episode of Avatar The Last Airbender (S01E01) knowing D+ doesnt have it. It would say item not found like last time but this time it would automatically go to Addon 2 and play the episode correctly.

here is the code from the player can you tell me what is wrong?

 ],
    "fallback": {
        "play_movie": "addon2.json play_movie",
        "play_episode": "addon2.json play_episode"
    }
}

**Comment by mathu204** [comment]
Hi im using a player i downloaded from drinferno it is a Disney+ player with a fallback player (Addon 2) written into it.

when I play a movie: (i tried Avengers:Endgame bc I knew it would be named differently in D+) it says item not found and then brings me back to the Choose Action dialog with players rather than playing with Addon 2. At this point the D+/Addon 2 player is gone.
_The fallback movie action from D+ to Addon 2 doesn't work when player fails to find playable item._

I tried to play the movie Avatar (blue ppl) with the same player and it found the movie and played it.
_The player can correctly play a movie if found in D+ first like intended._

I tried to then play an episode of Avatar The Last Airbender (S01E01) knowing D+ doesnt have it. It would say item not found like last time but this time it would automatically go to Addon 2 and play the episode correctly.
_The fallback player works correctly by playing with Addon 2 after D+ could not find it_

here is the code from the player can you tell me what is wrong?

```
{
    "name": "[COLOR royalblue]Disney+[/COLOR] -> [COLOR blue]Addon 2[/COLOR]",
    "plugin": [
        "slyguy.disney.plus",
        "plugin.video.addon2"
    ],
    "priority": 350,
    "play_movie": [
        "plugin://slyguy.disney.plus/?_=search",
        {"keyboard": "{title}"},
        {"title": "{title}", "year": "{year}"}
    ],
    "play_episode": [
        "plugin://slyguy.disney.plus/?_=search",
        {"keyboard": "{showname}"},
        {"title": "{showname}"},
        {"position": "{season}"},
        {"position": "{episode}"}
    ],
    "fallback": {
        "play_movie": "addon2.json play_movie",
        "play_episode": "addon2.json play_episode"
    }
}
```

**Comment by mathu204** [comment]
So I’m using a Disney+ player with a fallback player (Addon 2) written into it.

when I play a movie: (i tried Avengers:Endgame bc I knew it would be named differently in D+) it says item not found and then brings me back to the Choose Action dialog with players rather than playing with Addon 2. At this point the D+/Addon 2 player is gone.
The fallback movie action from D+ to Addon 2 doesn't work when player fails to find playable item.

I tried to play the movie Avatar (blue ppl) with the same player and it found the movie and played it.
The player can correctly play a movie if found in D+ first like intended.

I tried to then play an episode of Avatar The Last Airbender (S01E01) knowing D+ doesnt have it. It would say item not found like last time but this time it would automatically go to Addon 2 and play the episode correctly.
The fallback player works correctly by playing with Addon 2 after D+ could not find it

here is the code from the player can you tell me what is wrong?

{
    "name": "[COLOR royalblue]Disney+[/COLOR] -> [COLOR blue]Addon 2[/COLOR]",
    "plugin": [
        "slyguy.disney.plus",
        "plugin.video.addon2"
    ],
    "priority": 350,
    "play_movie": [
        "plugin://slyguy.disney.plus/?_=search",
        {"keyboard": "{title}"},
        {"title": "{title}", "year": "{year}"}
    ],
    "play_episode": [
        "plugin://slyguy.disney.plus/?_=search",
        {"keyboard": "{showname}"},
        {"title": "{showname}"},
        {"position": "{season}"},
        {"position": "{episode}"}
    ],
    "fallback": {
        "play_movie": "addon2.json play_movie",
        "play_episode": "addon2.json play_episode"
    }
}
