### ISSUE TITLE
[REQUEST] My Accounts

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#306]
Maybe you would consider implementing the My Accounts addon into TMDBH? The more addons that implement this, the easier it is to consolidate Trakt Logins. https://github.com/a4k-openproject/repository.myaccounts

**Comment by jurialmunkey** [comment]
It has to be an addon that is available on the official repo, otherwise the dependency will fail.

**Comment by JayDee696969** [comment]
> It has to be an addon that is available on the official repo, otherwise the dependency will fail.

Cant you add it to your repo?

**Comment by jurialmunkey** [comment]
Doesn't matter. Intent of the plugin is to be on the official Kodi repo, so any dependencies also need to be on the official repo.
