### ISSUE TITLE
[Request] Player file for Disney Plus addon?

### ISSUE THREAD

**Issue by mathu204** [jurialmunkey/plugin.video.themoviedb.helper#307]
I don't know if you've made all the players yourself but Id really like to be able to use TMDB Helper to play with Disney Plus when available

**Comment by drinfernoo** [comment]
It's been awhile since I tested it, and even then it had some issues, particularly with shows where the title didn't match ("The Mandalorian" on TMDb vs. "Disney's The Mandalorian" on D+), but you can try this one: https://github.com/drinfernoo/netflix.disney.seren/blob/master/disney.json

If we can get it working well, I'd love for it to be included as a default player.

**Comment by mathu204** [comment]
> It's been awhile since I tested it, and even then it had some issues, particularly with shows where the title didn't match ("The Mandalorian" on TMDb vs. "Disney's The Mandalorian" on D+), but you can try this one: https://github.com/drinfernoo/netflix.disney.seren/blob/master/disney.json
> 
> If we can get it working well, I'd love for it to be included as a default player.

Not saying for you to do it bc i feel it might be tedious, but just curious on if something like this could be done and if so how itd work. Is it possible to write exceptions into the code for example the Mandalorian?

Command something like: (TMDb) "The Mandalorian" = "Disney's The Mandalorian" (D+)

So like when u use play with TMDB Helper for an episode of "The Mandalorian" from inside the TMDB Helper, or any other addon; when you click the Disney Plus player, it would see The Mandalorian and then seeing the code/command you wrote; it would look for "Disney's The Mandalorian" in D+, while keeping "The Mandalorian" if you had used any other player.

This would ideally work vice versa, example: Disney Plus is down or hella laggy one day, u click "Disney's The Mandalorian" S01E03 with Play with TMDB Helper, use any player such as Netflix (not sure if it even has it but w.e); It would change "Disney's The Mandalorian S01E03" to "Mandalorian S01E03"

**Comment by drinfernoo** [comment]
I *think* you could pull something off with regex, but I haven't taken the time to figure it out.

**Comment by jurialmunkey** [comment]
Yeah something like `.*{title}.*` would regex match it.

Or you could do an OR group if you wanted to match both with and without "Disney's" prefix.
`(Disney's |){title}`

**Comment by jurialmunkey** [comment]
> This would ideally work vice versa, example: Disney Plus is down or hella laggy one day, u click "Disney's The Mandalorian" S01E03 with Play with TMDB Helper, use any player such as Netflix (not sure if it even has it but w.e); It would change "Disney's The Mandalorian S01E03" to "Mandalorian S01E03"

Each player is separate so the rules they use are also separate.

**Comment by mathu204** [comment]
> > This would ideally work vice versa, example: Disney Plus is down or hella laggy one day, u click "Disney's The Mandalorian" S01E03 with Play with TMDB Helper, use any player such as Netflix (not sure if it even has it but w.e); It would change "Disney's The Mandalorian S01E03" to "Mandalorian S01E03"
> 
> It already works like this. Each player is separate so the rules they use are also separate. If you define a rule in one player it won't affect any other players.



> Yeah something like `.*{title}.*` would regex match it.
> 
> Or you could do an OR group if you wanted to match both with and without "Disney's" prefix.
> `(Disney\'s |){title}`

I see so it is possible to get the Disney Plus Player working as intended then. How could one go about learning to add these regex rules, im somewhat nooby but id like to help get this working somehow if i can.
