### ISSUE TITLE
[Request] Trakt list support for person type

### ISSUE THREAD

**Issue by ohfuchs** [jurialmunkey/plugin.video.themoviedb.helper#308]
Maybe you could consider adding support for person type in trakt lists. 

I looked for a way to display a widget with my favorite actors in arctic zephyr skin, so I could quickly navigate to movies/shows with those actors. I thought trakt lists would be a great way to solve it :)

**Comment by jurialmunkey** [comment]
Ah that's a great idea that I just simply never thought of before. I always assumed person lists wouldn't be much use so never bothered to implement them.

I'm currently working on a rewrite of the plugin, so I'll definitely keep this feature in mind for the upcoming release!

**Comment by ohfuchs** [comment]
that's great news!

**Comment by jurialmunkey** [comment]
Added in the v4 refactor.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/tree/refactor
