### ISSUE TITLE
Auto Repeat Video

### ISSUE THREAD

**Issue by Wafflestyx** [jurialmunkey/plugin.video.themoviedb.helper#309]
v3.3.21 Libreelec Pi3

I'm using library integration and when I select a video to watch after it's over it trys to play again.

If I stop the video before it reaches the end, it doesn't do this.

Using Yatse shows what I'm watching is in a playlist.
Playlist repeat is set to off.

When I look at the playlist in Kodi it has a music note icon (using Aura skin).

Thought maybe it thinks it's audio I check settings > player settings > music > play next song automatically and that is uncheck.

I have tired reinstalling tmdb and it's still happens.

**Comment by jurialmunkey** [comment]
Please try v4 in the "refactor" branch and see if that fixes the issue. Keep in mind that this is a pre-release version.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/tree/refactor

Also debug logs are useful.

**Comment by Wafflestyx** [comment]
This fixed this issue. 

I noticed when I installed this version and played something, it wouldn't use the default player that was set from before. It would bring up the select what you want to use dialogue window.
I had to go into settings and reselect the one I wanted.

**Comment by jurialmunkey** [comment]
Excellent!

> I noticed when I installed this version and played something, it wouldn't use the default player that was set from before. It would bring up the select what you want to use dialogue window. I had to go into settings and reselect the one I wanted.

Yeah I've tried to keep things as backwards compatible as possible, but it is a very large rewrite of the code base so there are some spots where it wasn't possible and settings will need to be set again to work properly.

**Comment by Wafflestyx** [comment]
Been using the refactor version, saw there have been a few updates since. 
Updated to 4.0.21, somewhere along the way this issue returned.
