### ISSUE TITLE
ListItem.Studio issue

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#31]
Currently ListItem.Studio is being filled with a list of all studios separated by / 
eg:  Showtime / Bonanza Productions / John Wells Productions / Warner Bros. Television / Showtime Networks

With the current method,  resource.images.studios is unable to provide studio images as ListItem.Studio does not match any file names.

Direct texture file loading failed for resource://resource.images.studios.coloured/Showtime / Bonanza Productions / John Wells Productions / Warner Bros. Television / Showtime Networks.png

Would it be possible to change this to only fill the first studio in the list, eg "Showtime".

**Comment by jurialmunkey** [comment]
You can get the name of the first studio with `$INFO[ListItem.Property(Studio.1.Name)]`

See wiki for full list of available properties:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Detailed-Item

**Comment by skyfsza** [comment]
Thanks, I will add a variables for tmdbhelper.

Just did a quick test and I seem to be getting studio no.2 as Studio.1.Name for TV Shows

TV:
ListItem.Property(Studio.1.Name): Sean Daniel Company
ListItem.Studio: Netflix / Sean Daniel Company / Platige Image / Pioneer Stilking Films
Movie:
ListItem.Property(Studio.1.Name) 20th Century Fox
ListItem.Studio 20th Century Fox / Chernin Entertainment

**Comment by jurialmunkey** [comment]
Ah, only production companies are getting added, not networks.

Latest commit should fix this issue. You will need to refresh the cache for that item to see updated info.

**Comment by skyfsza** [comment]
Thanks, can confirm it's working now.
