### ISSUE TITLE
Kodi crashing when selecting TMDBH strm before player selection

### ISSUE THREAD

**Issue by KyzanHartwig** [jurialmunkey/plugin.video.themoviedb.helper#313]
For TMDB Helper 4.0.10.

I have created a smart playlist of TV series episodes within Kodi that should select a random episode from my library, which contains many strm files created by TMDB Helper.

Whenever I try to play this smart playlist, the screen shows the TMDB Helper logo in the background and then Kodi crashes, before I am able to select a player.

The log states at the end XBMC is not playing any media file.

Is there an easy fix for this?

**Comment by jurialmunkey** [comment]
Matrix or Leia version? I'll see if I can recreate it.

**Comment by jurialmunkey** [comment]
@KyzanHartwig - Can you test latest version (4.0.11) from refactor branch? Fixes the issue for me.

**Comment by KyzanHartwig** [comment]
Yep, seems to be working now. Thank you.
