### ISSUE TITLE
4.0.14

### ISSUE THREAD

**Issue by hindsight2021** [jurialmunkey/plugin.video.themoviedb.helper#315]
Hi there,

When updating the plug-in to 4.0.14 it pulls it from video addons and places it in program addons on Kodi 18.8 (Librelec), where it is failing to run properly in my widgets in aura-mod etc. and when opened - when downgrading to earlier releases, it’s resolved, any ideas?

**Comment by hindsight2021** [comment]
Snippet;

25 17:49:53.800 T:1987044208   ERROR: Window Translator: Can't find window infodialog
2020-10-25 17:50:03.115 T:2043102064  NOTICE: [plugin.video.themoviedb.helper]
                                            Attempting to play:
                                             {u'info': u'play', 'tmdb_type': 'tv', u'episode': u'9', u'islocal': u'True', u'tmdb_id': u'50042', u'season': u'4'}
2020-10-25 17:50:04.402 T:1987044208   ERROR: Window Translator: Can't find window infodialog
2020-10-25 17:50:11.247 T:3011417424  NOTICE: VideoPlayer::OpenFile: videodb://tvshows/titles/440/4/12417?season=4&tvshowid=440&xsp=%7b%22order%22%3a%7b%22direction%22%3a%22ascending%22%2c%22ignorefolders%22%3a0%2c%22method%22%3a%22sorttitle%22%7d%2c%22type%22%3a%22tvshows%22%7d

**Comment by jurialmunkey** [comment]
No snippets. Full log please.

Shows fine for me in Leia in video addons. Tmdbhelper has always also shown in Programs because it is also a script and service in addition to being a plugin.

**Comment by hindsight2021** [comment]
Full; https://pastebin.com/iLGkYspP

4.0.16 made no real changes.

“Your next episode” appears broken, missing most of my shows, both in and external to app, and this update removes it from video addon, and places it as a program addon now, may be root cause.

Interactions with Auramod are not good, when downgrading to 2.4.xxx, my lists appear normally again.

**Comment by jurialmunkey** [comment]
What is the exact issue? The snippet you linked above is not in the log. As I explained the addon has always shown in Programs because it is also a script in addition to a plugin. It shows correctly under "Videos > Video Addons" for me.

![Honeyview_screenshot275](https://user-images.githubusercontent.com/4618719/97168074-f58f0680-17db-11eb-9980-27371c3fb3a6.jpg)

**Comment by jurialmunkey** [comment]
> Interactions with Auramod are not good, when downgrading to 2.4.xxx, my lists appear normally again. Re-Auth with trakt, made no changes.

What lists don't display properly? What is the exact issue?

In your log the only list I can see failing to load is a genre list which uses a very outdated method of `info=genre` which has long been replaced with `info=discover`

**Comment by hindsight2021** [comment]
I posted the full log in my previous post.

When I update to 4.0.14/16 it yanks the addon out of video addons and places it in program addons. From there, my widgets on Auramod, such as your next episode from within the addon and for the widget are missing 80% of my shows, and errors out trying to view 2nd page, etc. 404 errors in fanart api, etc, disabled that. See log.

Primary issue;

When updating, it places it in program addons and ceases to function.

Tried clearing cache, rebooting, etc, but the issue remains, also re-authed in trakt, no changes. Downgraded to 2.4.x.x and it works like normal minus recent changes.

**Comment by hindsight2021** [comment]
Screenshots showing the before, in video addons.

With list of shows from your next episode trakt list.

Updated via zip from GitHub to 4.0.16, addon moves to program addons. Re-auth Trakt, shows still missing. Widgets in Auramod also missing content.

Link; [https://imgur.com/a/1wBasFA](url)

**Comment by jurialmunkey** [comment]
I keep telling you. It doesn't matter what category it shows under in the Addon Browser. You can still open it via Video Addons by going to Videos > Video Addons.

**Comment by hindsight2021** [comment]
I hear you - but I’m trying to explain to you that is not the case.

When udating it to 4.0.16 is is no longer found in my video addons, at all, in any capacity, it can now only be found in “program” addons. I don’t know why, but that is the issue I’m raising here. Screenshots appended in my last post that show this in real time. What else do you need from me? Happy to supply anything else needed. This is handicapping my setup, so eager for any help.

**Comment by jurialmunkey** [comment]
Create a shortcut on your home menu pointing to "Video Library > Video Addons". Open that. Does it show there?

**Comment by hindsight2021** [comment]
I should also note, 4.0.16 largely functions fine when updated - I just can’t see why it’s messing up my trakt functions for “your next episode”. 80% of my shows are suddenly not showing as they were before, screenshot highlights the differences

**Comment by hindsight2021** [comment]
Checking...

**Comment by jurialmunkey** [comment]
>  I just can’t see why it’s messing up my trakt functions for “your next episode”. 80% of my shows are suddenly not showing as they were before, screenshot highlights the differences

Are you sure they aren't just on the next page? The default sorting method for "Your next episodes" has changed to be based on release date of the episode so that newer released episodes now show at the front. You can toggle the sort method in the addon settings under "Accounts > Next Episodes Sort Method"

**Comment by hindsight2021** [comment]
Yes, it can still be found in video addon > TMDB helper, so thank you for that. I added a new widget for “your next episode” on 4.0.16 to see if it will make any difference in Auramod.

Sadly, it’s still missing 80% of my shows that were in this widget from before the update. Same as opening the addon directly, so it doesn’t seem to be AM causing it.

**Comment by hindsight2021** [comment]
It’s the default sorting, it threw me off, thank you!!!

That said, I also noticed the widget now only displays 10 shows, I think it used to have the option to display 20+ - is that gone?

**Comment by jurialmunkey** [comment]
Also in addition to the sorting method changes, also note that the plugin now correctly hides any shows from calendars/progress that you've hidden on Trakt. You can see what you've hidden on Trakt here:
https://trakt.tv/settings/hidden

**Comment by jurialmunkey** [comment]
> 
> 
> It’s the default sorting, it threw me off, thank you!!!
> 
> That said, I also noticed the widget now only displays 10 shows, I think it used to have the option to display 20+ - is that gone?

Only for your next episodes and in-progress - all the other Trakt lists show 20 items by default now. It's only limited for these two lists because they involve a lot more look-ups than other lists. The trade-off is that now these lists are properly paginated so you can see every item now (e.g. if you have 50 next episodes you can see them all, they are just split across 5 pages whereas before you could see 20 items at once but you couldn't see further than that).

**Comment by hindsight2021** [comment]
Thanks, I think this can close it out.

Only suggestion, would be to allow for more than 10 if desired, as I don’t like changing pages where possible, but understood and can go the library route now. Thanks again for this,
