### ISSUE TITLE
Integration with Seren broken

### ISSUE THREAD

**Issue by naudski** [jurialmunkey/plugin.video.themoviedb.helper#316]
Hi there,

Somehow with this latest update (4.0.14) the integration with Seren seems broken. Seren is setup as my default player for episodes and movies in the tmdb helper addon. When I start an episode from my tmdb helper widget in Auramod it now asks me to select a player and when I choose Seren, kodi crashes.

Any ideas?

**Comment by drinfernoo** [comment]
That has nothing to do with TMDbHelper.

**Comment by jurialmunkey** [comment]
Default players need to be set again with v4.

Hard to tell what the source of the crash is without a full debug log with debug logging turned on. Could be TMDbHelper or could be the addon you're calling as a player or could be the skin or could just be a coincidence.

**Comment by LN13uLL** [comment]
I’m having this issue too.  I even tried to set the default player again. But it crashes kodi when I try to select seren as the player. It works okay for Fen. I didn’t have this issue before this latest update.

**Comment by LN13uLL** [comment]
I tried “search with seren” and that works. But kodi crashes when “play with seren” or “play with seren (source select)” is selected.

**Comment by jurialmunkey** [comment]
Debug log please!

**Comment by LN13uLL** [comment]
Sorry this is the first time trying to do a debug log. How do I create or locate the debug log?

**Comment by jurialmunkey** [comment]
Usually in the basedir of the Kodi application data folder and is named `kodi.log`

On windows it is
`%APPDATA%\Kodi\kodi.log`

**Comment by jurialmunkey** [comment]
App data folder basedir is the parent folder of userdata. Can find the paths here for other OS here:
https://kodi.wiki/view/Userdata

**Comment by LN13uLL** [comment]
I hope this helps
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5437232/kodi.log)

**Comment by LN13uLL** [comment]
also just wanted to highlight that when i change the option, it displays like this now.  should it display the code or should it display the text like, example, "Play with Seren".
![20201026_024907](https://user-images.githubusercontent.com/67085646/97141890-ff5e2e80-1735-11eb-82b0-2cfd62d78adb.jpg)

**Comment by jurialmunkey** [comment]
The displayed name is correct - I decided it was better to show the file name and method so that it is easier to find the correct file to edit if needed.

**Comment by jurialmunkey** [comment]
Judging from the log it looks like TMDbHelper finishes. 

How far along does the player get before the crash? e.g. does Kodi crash immediately after selecting the player, or does the other addon open up?

**Comment by LN13uLL** [comment]
Okay. I think I found out what is “not working and what is “working”. 

There’s a new player option I noticed called plainly “play with seren”. That definitely works the same way as “play with seren (select source)”.

The options called “play with seren (source select)” and play with seren (smart play w/ source select)” crashes kodi. 

Is there a difference between those three?

Play with seren
Vs
Play with seren (source select)
Play with seren (smart play w/ source select)

**Comment by LN13uLL** [comment]
> The displayed name is correct - I decided it was better to show the file name and method so that it is easier to find the correct file to edit if needed.

Gotcha! That’s good to know.

**Comment by jurialmunkey** [comment]
> 
> 
> Okay. I think I found out what is “not working and what is “working”.
> 
> There’s a new player option I noticed called plainly “play with seren”. That definitely works the same way as “play with seren (select source)”.
> 
> The options called “play with seren (source select)” and play with seren (smart play w/ source select)” crashes kodi.
> 
> Is there a difference between those three?
> 
> Play with seren
> Vs
> Play with seren (source select)
> Play with seren (smart play w/ source select)

Those player files are all 3rd party so I'm really not sure what the differences are.

**Comment by LN13uLL** [comment]
Okay some more additional information.

1.  i've set the tmdbplayer as "Play with Seren" for movies and episodes.
2.  from the tmdb helper widget, i select the movie or episode.  once i click it, that's when it crashes.
3.  if i go into the context menu for the movie or episode from the tmdb helper widget, then select "select players" option from the context menu then i click "play with seren". it works find.  

It seems like for some reason clicking the movie or episode with the default tmdbplayer option will crash but when i go into "select player", then it won't crash.

**Comment by LN13uLL** [comment]
I also now just tested changing the default tmdbplayer to "play with fen".  same thing happens.  kodi crashes, when i click on the movie/episode, but if i go to the movie/episode, and select "select player" from the context menu.  it won't crash after selecting a player.

**Comment by LN13uLL** [comment]
also not sure if it helps, but i'm also running the newly released Kodi 18.9.

**Comment by jurialmunkey** [comment]
Hmmm so strange. Playing using a default player is work fine for me. How exactly are you playing the file? Is it from the play button in the info dialog? A widget? In the plugin? A strm file in the library?

**Comment by LN13uLL** [comment]
I'm clicking it from widgets in official Aura skin.

I did test it directly from within the TMDB Helper addon and it works fine.

I've tested it on the "Your Next Episodes" widget and Trending movies widget.  it crashes on those.  But doing it from within the TMDB helper addon works okay.

**Comment by naudski** [comment]
I'm having the exact same issues. I always use the Play button in the info dialog which normally starts Seren, but now it asks me to select a player and then when I select a player, kodi crashes. No matter which player I choose by the way.
I will try to reselect my default players as well.

Thanks a lot for your support!!!

**Comment by jurialmunkey** [comment]
> 
> 
> I'm clicking it from widgets in official Aura skin.
> 
> I did test it directly from within the TMDB Helper addon and it works fine.
> 
> I've tested it on the "Your Next Episodes" widget and Trending movies widget. it crashes on those. But doing it from within the TMDB helper addon works okay.

Okay we're getting close! I was able to recreate the crash using that widget in Aura.

It might be some weird skin specific issue because it was working fine for me using the same widget in Arctic Horizon. I'll have a dig in the code for Aura (wow, I haven't looked at that code for a _long_ time!) and see if I can get some idea

**Comment by jurialmunkey** [comment]
@naudski - Are you also using Aura? Or some other skin?

**Comment by naudski** [comment]
I'm using Auramod.

**Comment by LN13uLL** [comment]
> > I'm clicking it from widgets in official Aura skin.
> > I did test it directly from within the TMDB Helper addon and it works fine.
> > I've tested it on the "Your Next Episodes" widget and Trending movies widget. it crashes on those. But doing it from within the TMDB helper addon works okay.
> 
> Okay we're getting close! I was able to recreate the crash using that widget in Aura.
> 
> It might be some weird skin specific issue because it was working fine for me using the same widget in Arctic Horizon. I'll have a dig in the code for Aura (wow, I haven't looked at that code for a _long_ time!) and see if I can get some idea

Thanks!!!  Hopefully it won't be too difficult once you dig into the code.  

I also love your Arctic Horizon skin.  I just wish i'm able to do a pinned category shortcuts similar to Aura.  That's the only reason why i'm still like Aura over Horizon. :)

**Comment by jurialmunkey** [comment]
> I also love your Arctic Horizon skin. I just wish i'm able to do a pinned category shortcuts similar to Aura. That's the only reason why i'm still like Aura over Horizon. :)

Not to get too off-topic but FYI you can - it's called a submenu widget in AH. Very similar to the default categories widget in Aura (though you can't do the smaller square icon only one that's in Aura - only the larger style one).
https://github.com/jurialmunkey/skin.arctic.horizon/wiki/Submenus#submenu-widget

**Comment by jurialmunkey** [comment]
@naudski @LN13uLL - Can you both try latest version from master (v4.0.16)? Hopefully I've fixed the issue 🤞 - Not crashing for me any more using stock Aura skin from repo.

**Comment by LN13uLL** [comment]
Caught me at a good time. I was about to head to bed. But excited you are so quick at fixing it so I just tested build 16. It works!!!!! You rock!! :-)

I can sleep happy :). Thank you soooo much!

**Comment by jurialmunkey** [comment]
Excellent! We got there in the end! Thanks so much for testing - it was really helpful in narrowing down the issue.

**Comment by LN13uLL** [comment]
You’re very welcome :). Glad I was able to help! Have a good day or night.

**Comment by naudski** [comment]
Thank you very much!!!
