### ISSUE TITLE
4.0.14 Update Messes Up Watchlist sorting

### ISSUE THREAD

**Issue by LN13uLL** [jurialmunkey/plugin.video.themoviedb.helper#317]
Hi there, TMDB Helper updated to 4.0.14 and messes up sorting for the Watchlist for movies and tv shows.  I'm not able to get my sorting back to what it was before.  It worked on the previous version.

**Comment by jurialmunkey** [comment]
You can sort the watchlist via "Context Menu > Browse sorted list"

From their you have the option to Sort By: Rank, Added, Title, Year, Random.

**Comment by jurialmunkey** [comment]
Rank = Default list order
Added = Date item was added to watchlist
Title = Alphabetical order
Year = Release date order
Random = Random order

**Comment by LN13uLL** [comment]
Thanks. 

It works now for movies Watchlist via widget. But I’m not able to sort it by added date for tv shows Watchlist. I’m not able to see the sorting options like for movies watchlist.

**Comment by LN13uLL** [comment]
I found it when I go from tmdbhelper/tv shows/Watchlist. 

But it doesn’t show up when I go to tmdbhelper/trakt/tv shows Watchlist.

**Comment by jurialmunkey** [comment]
Try going "TMDbHelper > TvShows > Watchlist"

For some reason they aren't showing when you go "TMDbHelper > Trakt > Tvshows Watchlist"

**Comment by jurialmunkey** [comment]
> 
> 
> I found it when I go from tmdbhelper/tv shows/Watchlist.
> 
> But it doesn’t show up when I go to tmdbhelper/trakt/tv shows Watchlist.

Haha discovered at the same time. I'll look into why it isn't showing up there.

**Comment by LN13uLL** [comment]
Hahaha yep!! We crossed paths haha. Thanks for looking through h it with me :). 

For now, I will go through ur explanation.

**Comment by jurialmunkey** [comment]
Found the issue. Should be fixed now. Thanks for the bug report! 😁

**Comment by LN13uLL** [comment]
Sweeeet! You’re welcome!

Thanks so much for the quick reply and fix :-). 🤘🏼
