### ISSUE TITLE
4.0.14 No Longer Allows "TMDB Helper (Play With)" Option?

### ISSUE THREAD

**Issue by LN13uLL** [jurialmunkey/plugin.video.themoviedb.helper#318]
Hi, I also noticed that when in Seren, for example, Up Next, I used to be able to see the "TMDB Helper (Play With)" option in the context menu.  It's no longer there.  Has this feature been removed?  Sometimes I use a widget or shortcut to an addon, but want to use tmdb helper to select a different player rather than going through the other addon.

**Comment by jurialmunkey** [comment]
It's still available inside TMDbHelper as "Select player". I can look into adding it outside of TMDbHelper.

**Comment by LN13uLL** [comment]
That would be extremely helpful if you could add it to outside of TMDB Helper.  Thanks so much for answering so much of my posts tonight.  Seems like a lot of changes were done for this update.  Hopefully, I haven't been too annoying lol.

**Comment by jurialmunkey** [comment]
> 
> 
> That would be extremely helpful if you could add it to outside of TMDB Helper. Thanks so much for answering so much of my posts tonight. Seems like a lot of changes were done for this update. Hopefully, I haven't been too annoying lol.

Much of the plugin has been rewritten from the ground up, so I'm expecting some hurdles on the way!

These reports are all great. I've tried to make things as backwards-compatible as possible but obviously there will be some corner cases where things break or I simply forgot that a feature existed etc. etc. So these reports from other users are really helpful! There's only so much testing I can do myself to catch everything - there's a point where it's just easier to push it out and break a few things (hopefully not too many things though!)

**Comment by LN13uLL** [comment]
Hahaha yea I really appreciate the changes you have made though. Really cool updates. I’m glad I have been helpful with the feedbacks :).

**Comment by jurialmunkey** [comment]
Okay I've created a separate context menu addon here:
https://github.com/jurialmunkey/context.themoviedb.helper

This addon will contain any context menu actions for items that are *not* from TMDbHelper. 

So basically context menu items for TMDbHelper items will ship by default, but if you want to use TMDbHelper actions on non-TMDbHelper items then you also install the context menu addon. That way it's kept optional and doesn't clutter up context menus for users that don't want them on other items.

Currently is only the "Play using TMDbHelper" entry but I'll be expanding it to include other actions such as "Browse lists" etc. Eventually will also include some Service Monitor options such as refreshing ratings / details / artwork.

**Comment by smallieollie** [comment]
Just want to comment on this as I am not sure I am understanding.  I was having issues today so I went to reddit and could see Dr.inferno suggested installing this directly  https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/master.zip.  I did so and the initial problem of not loading from my library was solved.  I then like this user was looking for the play with option from TMDB helper and it was not available from the library.  I then installed this fix and I now see TMDB helper options.  When I click that I get select player as my only option and then it just starts to try and play from the defaults that I have set.  I do not get an option to play with another addon.  (like in the past)  I used this function many many times a day.  Currently says I am using version 4.0.17.  Am I doing something wrong?

**Comment by jurialmunkey** [comment]
> Am I doing something wrong?

Nope, I just forgot to add the ignore default param to the context menu item. Can you test with latest version of both the plugin itself and the context menu addon? Should be fixed now.

Some teething problems are expected with such a large rewrite of the code base!

**Comment by smallieollie** [comment]
Yes I can.  Did the update get pushed via Repo, or do you want me to download and install again via github?  No worries on the changes.  I love your work and can always test if need be =)

**Comment by LN13uLL** [comment]
> Okay I've created a separate context menu addon here:
> https://github.com/jurialmunkey/context.themoviedb.helper
> 
> This addon will contain any context menu actions for items that are _not_ from TMDbHelper.
> 
> So basically context menu items for TMDbHelper items will ship by default, but if you want to use TMDbHelper actions on non-TMDbHelper items then you also install the context menu addon. That way it's kept optional and doesn't clutter up context menus for users that don't want them on other items.
> 
> Currently is only the "Select player" entry (all options are under "TMDbHelper Options" sub context menu). However, I'll be expanding it to include other actions such as "Browse lists" etc. Eventually will also include some Service Monitor options such as refreshing ratings / details / artwork.
> 
> (@drinfernoo - Heads-up you might want to include this context menu addon next time you do a repo update)

Thanks so much!!!! I just tested it and it works great!!!!

**Comment by LN13uLL** [comment]
> Yes I can. Did the update get pushed via Repo, or do you want me to download and install again via github? No worries on the changes. I love your work and can always test if need be =)

For now, download the zip from his gibhub for that context menu addon.  Then install it from zip from kodi.

**Comment by drinfernoo** [comment]
It's been added to the repo now as well.

**Comment by LN13uLL** [comment]
> It's been added to the repo now as well.

Thanks! What’s the repo link? I thought I had it unless I’m losing it lol.
