### ISSUE TITLE
New "Show More" page error

### ISSUE THREAD

**Issue by joobert** [jurialmunkey/plugin.video.themoviedb.helper#319]
Hey,

Whenever widgets are loading now, instead of seeing loading symbols I see the new "show more" button, which is fine. The problem is that once the widgets are done loading, the widgets are shot all the way to the last item of the row, instead of showing and focusing on the first item in each respective row like normal. This is more of just a pet peeve than anything but figured I'd bring it to your attention.

**Comment by jurialmunkey** [comment]
This sounds like a skin issue. Can you report this issue on the relevant skin git page instead.

If this is for Arctic Horizon, the "Show More" item can be disabled in 
`Skin Settings > Home > Display the "Show More..." widget item`

(I know it's not a "fix" per se but might be useful to know in the interim until I do have a fix for it).
