### ISSUE TITLE
[Bug] with Play when default action is show info

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#32]
Small bug when you set default action to show information.

If you click on a movie, it will trigger DialogVideoInfo correctly. but If you then try use the play button, tmdbhelper triggers DialogVideoInfo again.

To get around it I added a custom button for tmdbhelper, but might be something you want to look at addon side. 
`PlayMedia($ESCINFO[ListItem.FileNameAndPath,,&amp;widget=True])`

**Comment by jurialmunkey** [comment]
Ah, I didn't think about this scenario at all. Fixed in latest. There is now a separate `?info=info` param.

**Comment by jurialmunkey** [comment]
Actually, I've just realised the whole Action(Info) option messes with Kodi's inbuilt default select action and so I've had to remove it as it wouldn't be accepted into official repo.

If you need to have default select action be info then you should set the Kodi setting:
`Settings > Media > Videos > Default Select Action > Show Information`

And in the addon set default action to Play/Open.

Sorry! I just know that overriding the default select action will be a deal breaker for Kodi repo.

**Comment by drinfernoo** [comment]
@jurialmunkey This doesn't affect the situation where we want the default action to be "Play/Open", though?

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey This doesn't affect the situation where we want the default action to be "Play/Open", though?

No, there's still the option to select between Play and Browse as that still respects Kodi's default play action setting (i.e. if it is set to show information, the information will show).

The difference between Play and Browse is:

- Browse sets the listitems to be folders which open the detailed item folder. The first item of the detailed item folder is set to be playable (or open seasons folder in the case of tvshow).
- Play sets the listitems to be playable (or open seasons folder in the case of tvshow) and thus skips the detailed item folder.

**Comment by skyfsza** [comment]
> Actually, I've just realised the whole Action(Info) option messes with Kodi's inbuilt default select action and so I've had to remove it as it wouldn't be accepted into official repo.
> 
> If you need to have default select action be info then you should set the Kodi setting:
> `Settings > Media > Videos > Default Select Action > Show Information`
> 
> And in the addon set default action to Play/Open.
> 
> Sorry! I just know that overriding the default select action will be a deal breaker for Kodi repo.

No problem, makes sense if it's breaking builtin kodi features.

I dont suppose you know of a way skin side I could achieve a custom onclick inside MyVideoNav?  I tried adding an onclick, tried a button in focusedlayout, nothing seems to work.

Kodi's default select action --> Show Information "breaks" non Video addons so I prefer to have skin side "show info".

**Comment by rijs43** [comment]
If you click on a movie, it will trigger DialogVideoInfo correctly. but If you then try use the play button, tmdbhelper triggers DialogVideoInfo again.

Still have this issue with latest moviedb helper, using arctic horizon skin but tried also in other skins.

When hitting Play from info screen for a movie in my library it will bring me back to the widget (home screen)

**Comment by jurialmunkey** [comment]
@rijs43 - I think what you're describing is a separate issue as the issue in this thread relates to a feature that is no longer available in TMDbHelper.

Can you open a new issue with a clear description of exact steps to reproduce.
