### ISSUE TITLE
Watchlist sorting issue is back

### ISSUE THREAD

**Issue by naudski** [jurialmunkey/plugin.video.themoviedb.helper#321]
Hi!

It looks like the watchlist sorting issue (issue #118) is back. I now have version 4.0.17 installed.
Sorry to bother you again :-(
I think your addon is amazing! Thanks for all your work 👍

**Comment by jurialmunkey** [comment]
Already answered here: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/317

You can change watchlist sorting via "Context menu > Browse sorted list".
When adding the widget you get the option of what sort method to use. You just need to re-add your widget with the sorting method you want (see thread I linked above).

Sorting has been standardised across the addon for all sortable lists. You can now choose between: rank, added, year, title, random for any liked list, popular/trending list, collection, watchlist, or in-progress movies in the same way.

**Comment by naudski** [comment]
I found it. Thanks!!
