### ISSUE TITLE
Trakt options- No option to remove from Watchlist

### ISSUE THREAD

**Issue by BlackChee** [jurialmunkey/plugin.video.themoviedb.helper#322]
In Helper Widgets, In the Context menu/Trakt Options, There is a option to Add to watchlist. But, it does not give a option to remove from watchlist.. (Trying it on something that is in my watchlist)

If it matters, I am using the latest Artic Horizon and latest helper.

![IMG_20201026_200600](https://user-images.githubusercontent.com/73506987/97244499-dcc82600-17c6-11eb-909f-04ba41786201.jpg)

**Comment by jurialmunkey** [comment]
Are you trying to remove it from the watchlist itself?

**Comment by BlackChee** [comment]
Yes, bringing up the context menu on something in my watchlist.

**Comment by jurialmunkey** [comment]
Ah I think I see the issue. Silly typo!

Can you test latest and confirm it is working for you now?

**Comment by BlackChee** [comment]
> Ah I think I see the issue. Silly typo!
> 
> Can you test latest and confirm it is working for you now?

Thank! I'll test it this evening when I get home 👍

**Comment by BlackChee** [comment]
> Ah I think I see the issue. Silly typo!
> 
> Can you test latest and confirm it is working for you now?

Worked great. Thanks again for all the work you put into this.

**Comment by jurialmunkey** [comment]
Excellent! Thanks for testing and the bug report! 😁
