### ISSUE TITLE
Navigation tab

### ISSUE THREAD

**Issue by Gamboa4** [jurialmunkey/plugin.video.themoviedb.helper#323]
Under navigation tab is missing "select Action".
(I always chose browse )

**Comment by jurialmunkey** [comment]
No longer necessary. You can now browse all the related lists via context menu options.

**Comment by Gamboa4** [comment]
It's not the same. It is realy important.
Love your work, but unfortonaly have to downgrade to the kodi repo version.
If you change your mind...

Best regards



A terça, 27/10/2020, 07:31, jurialmunkey <notifications@github.com>
escreveu:

**Comment by jurialmunkey** [comment]
v4.0.26 Adds option for browse which will cause onclick action to open the related lists menu.

**Comment by Gamboa4** [comment]
Fantastic.
Thank you. It really makes a diference.

A sábado, 31/10/2020, 07:24, jurialmunkey <notifications@github.com>
escreveu:
