### ISSUE TITLE
v 3.3.21  General Issues with unaired episodes not remaining hidden

### ISSUE THREAD

**Issue by Mahava** [jurialmunkey/plugin.video.themoviedb.helper#326]
I'm kinda confused about the versions, but this one didn't work on Kodi 18.9, so I reverted to 3.3.21.

Some general issues with the program:
1. Shows don't remain hidden until a few days before first episode airs.
      I think this is a replacement for openinfo and openmeta and next aired?
      In openmeta, shows with a future release date only appear in video sources and not in 
      library Title views - that is, not until a few days before the first episode airs.
      Even when I set TMDB Helper to hide unaired episodes, after the scrape, it displays "Foundation" show title
      with the first episode that is due to air on Dec 31.

2.   The context menu 'TMDB options' disappeared.  It is in the version I've reverted to: 3.3.21
        Nevertheless, could you make 'Add to Kodi Library' more accessible?  If this is intended to
        replace openmeta/openinfo, those programs make it easy to add to library with one click.

Thanks.

**Comment by drinfernoo** [comment]
3.3.21 is a very old version, and this add-on isn't related to OpenInfo *or* OpenMeta.

You need to update to the latest version.

**Comment by jurialmunkey** [comment]
Copying my response from the forum here:

The add to library context issue has already been fixed. V4 is a major rewrite so some bumps along the way are expected - ive tried to test things as much as possible myself but obviously there are small thing here and there that I've forgotten about. I'm relying on users to report the missing features or that things aren't working as expected and I'm fixing as needed. 

I'm not sure what you want me to do about an air date bug in an older version of the plugin... Unless you are saying the air date bug is happening in the new version (V4) but not the old version (v3) ?

**Comment by Mahava** [comment]
I would have been happy to test the 4.** version that was pushed if I could find the "add to kodi library" button.
***
version 4.0.18 manual install from repo: "add to kodi library" NOT seen on right-click context menu.  No way for me to test air date if I can't add something to the library, I'm afraid.

..reverting to the newest old version I have archived, 3.3.*

**Comment by drinfernoo** [comment]
it's fixed now: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/324

Somebody else opened an issue pertaining to the correct version of the plugin 😅

**Comment by jurialmunkey** [comment]
Was
