### ISSUE TITLE
TMDB Helper Context Menu Options

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/plugin.video.themoviedb.helper#329]
Hi jurialmunkey,
I noticed that you separated TMDB helper and it's context menu items in 2 different addons in the latest update.
Previously, I could add my local library movies from their widgets/list to my Trakt user lists using the TMDB helper context menu.
However, now that option is gone and the only option that remains is "Choose player".
Could you kindly add back the option to add my local library movies from their widgets/list to my Trakt user lists using the TMDB helper context menu?
I will be really grateful if you can do so.
I really liked that feature as it's not available in any other addon.
Thanks in advance!

P.S.: Also I noticed that you removed various other options from this addon. I couldn't understand why you did so. I actually liked this addon as a whole, instead of being 2 separate addons, i.e. TMDB helper and context menu. The TMDB Helper version 3.3.21 was almost perfect. I reverted back to that version currently. All features except few things like "Upcoming movies" are working fine in that one.

**Comment by jurialmunkey** [comment]
V4 is an almost complete rewrite of the plugin because there were a lot of underlying code issues with v3. This has been about 2 months worth of work for me. I didn't intentionally remove any features and I've tried to keep things as backwards compatible as possible - with such a complex plugin I just can't possibly test everything or on every system setup so I needed to release it at some stage.

The context addon is just for external items as many people complain about having too many context options so this makes it optional. Items inside tmdbhelper have all options by default - I plan to add all the options to the addon I just simply don't have more than 24hrs in a day so there's only so much I can do at once! The options will be added soon.

**Comment by jurialmunkey** [comment]
Please try v1.0.2 of context menu addon with v4.0.28 of TMDbHelper (latest git master of both). Should now have Trakt options for external movies/tv.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
First I want to say thank you for the amazing work that you're doing!
I can understand the pain in rewriting code from scratch.

Now coming to the addons, I installed v1.0.2 of context menu addon with v4.0.28 of TMDbHelper (latest git master of both).
I now have Trakt options for external movies/tv.
However, I noticed some issues:
1) Though I can add movies/tv to Trakt list. The option for removing them from the list is no longer there.
2) I cannot play any movies from TMDB helper, both from widgets video info page as well as from inside the addon. For local files on clicking play, simply nothing is happening. For web files, I chose "Seren (Source Select)" player and it's opening the context menu on clicking Play. After that if I click on Play again it's simply crashing Kodi. I tried changing resolve_url settings for the player as well but the issue is still happening.
3) Cast info in widget video info screen is no longer showing up for majority of the movies/tv shows.
4) I use Fanart.tv api. Earlier for local content posters and artworks used to remain my local library ones. However, now for everything (both local and web content) posters and artworks are being fetched from fanart.tv.
5) I have 3 Kodi setups and I noticed that the movie/tv lists are not syncing equally in all of them. Some are having updated info and some are having old info. e.g. In one setup I'm seeing info for "Trending Movies Today" from yesterday and for another setup I'm seeing updated info for today.

Could you kindly advise regarding the above issues?
I'll let you know if I notice anymore issues with these addons.

Thanks again for the wonderful work!

**Comment by jurialmunkey** [comment]
1. The option to add to watchlist switches to remove if the item is found in your watchlist. For instance, I have the movie "Joker" in my library and I just added it to my watchlist and now it displays remove from watchlist.

![Honeyview_screenshot278](https://user-images.githubusercontent.com/4618719/97801336-2665b480-1c90-11eb-8cd9-728a63d19a2d.jpg)

If you don't have this option then you probably had some Trakt sync issue. Hard to say without a debug log.


Could you please open separate issue threads for the other points not directly related to the context menu. It makes it much easier to resolve bugs and follow the discussion if each issue only relates to one bug. It also helps me keep track of what I need to fix, what I've already attempted, and ultimately how I resolved the issue.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
Actually I'm not talking about the default Trakt Watchlist, what I'm talking about are the Trakt Custom User Lists. I'm able to add items to my Trakt User lists via the Context Menu but the option to remove them is missing. Please advise.

I'll create separate issue threads now for the other points I mentioned above.
Thanks!

**Comment by jurialmunkey** [comment]
> Actually I'm not talking about the default Trakt Watchlist, what I'm talking about are the Trakt Custom User Lists. I'm able to add items to my Trakt User lists via the Context Menu but the option to remove them is missing. Please advise.

Ah yep you're right - the remove option isn't working there. I'll see if I can get it fixed.

> I'll create separate issue threads now for the other points I mentioned above.

Thanks! That will make it much easier to keep track of things.

**Comment by ShibajiCh** [comment]
> > Actually I'm not talking about the default Trakt Watchlist, what I'm talking about are the Trakt Custom User Lists. I'm able to add items to my Trakt User lists via the Context Menu but the option to remove them is missing. Please advise.
> 
> Ah yep you're right - the remove option isn't working there. I'll see if I can get it fixed.
> 
> > I'll create separate issue threads now for the other points I mentioned above.
> 
> Thanks! That will make it much easier to keep track of things.

Thanks a lot! Hope to see the issues get fixed soon.

**Comment by megavectra** [comment]
Same issue here. Really miss the "remove from user list" option. I use trakt as a "Favorites" of sorts that can be viewed on any Kodi box in the house.

**Comment by jurialmunkey** [comment]
> Same issue here. Really miss the "remove from user list" option. I use Trakt/TMDB Helper as a "Favorites" of sorts that can be viewed on any Kodi box in the house.

Ah! Thanks for the bump on this issue. I thought I had already fixed it but your comment made me realise I hadn't merged the changes!

**Comment by jurialmunkey** [comment]
Okay I believe all the missing context options are now added to the latest version of context menu addon (need latest version of TMDbHelper and Context Addon to work).

Context addon should now provide:
- Select player
- Browse lists
- Trakt options
- Refresh details
- Manage artwork

The Refresh details and Manage artwork options won't do anything for non-TMDbHelper items directly. However, they can be useful for updating the Service Monitor in skins which use that (e.g. If you need to change which the clearart/clearlogo that the service monitor is grabbing you can do it via this menu)

**Comment by jurialmunkey** [comment]
Additionally, there should be new Trakt options for custom lists:

Inside custom lists that you own, you should now be able to delete items. You should also be able to now delete and rename any custom lists that you control. When adding items to a custom list, you can now create a new list (previously was broken but now works correctly).

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
I've updated the TMDB Helper Context Menu add-on to version 1.0.3.
However, I'm unable to see any option to remove Movies/TV Shows under Trakt custom (your) lists in the TMDB Helper addon or widgets. Only the Add option is available like before. Could you please re-open this ticket and kindly look into the issue? Thanks!

**Comment by jurialmunkey** [comment]
It's working fine for me:

`TMDbHelper > Trakt > Your Lists > *Any List* > *Focus Item in List* > Context Menu > Trakt Options > Remove from user list`

![Honeyview_screenshot296](https://user-images.githubusercontent.com/4618719/100223260-5b071c00-2f6f-11eb-8591-b6b0c182a319.jpg)


Also FYI it won't work from a widget. You need to open the list inside TMDbHelper. I can't do it for a widget because I need to read a container property to tell whether the list is owned by the user and container properties currently don't work correctly in Kodi for widgets (same reason a lot of default Kodi context menu items and other things are missing from widgets).

**Comment by drinfernoo** [comment]
@jurialmunkey Those container properties *should* be working in Matrix ;) I hope, anyways 😅

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
For me the below "Remove" option is not appearing in custom Trakt lists:
TMDbHelper > Trakt > Your Lists > *Any List* > *Focus Item in List* > Context Menu > Trakt Options > Remove from user list

See screenshot here:
![Capture](https://user-images.githubusercontent.com/65297828/100251258-905a3c80-2f64-11eb-8567-0364109f06a7.JPG)

I opened the list inside TMDBHelper, but still the same issue.
I tried both for Movies and TV Shows.
Please advise. Thanks!

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
Any advise regarding the above?

**Comment by jurialmunkey** [comment]
>  I've updated the TMDB Helper Context Menu add-on to version 1.0.3.

@ShibajiCh - Did you update TMDbHelper itself? What version of TMDbHelper are you running?

**Comment by ShibajiCh** [comment]
> > I've updated the TMDB Helper Context Menu add-on to version 1.0.3.
> 
> @ShibajiCh - Did you update TMDbHelper itself? What version of TMDbHelper are you running?

Hi jurialmunkey,
Yes, I've already updated the TMDBHelper addon as well. I'm running version 4.0.71 at present.
Still I'm facing the same issue.
Please advise. Thanks!

**Comment by jurialmunkey** [comment]
Can you try latest. Might be container properties acting up. Otherwise if this doesn't work then will need a debug log.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
The latest version of TMDBHelper (version 4.0.72) is working perfectly.
Thanks for resolving the issue!
You're awesome! :)

**Comment by megavectra** [comment]
Thank you!
