### ISSUE TITLE
Problem with special characters (french language)

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/plugin.video.themoviedb.helper#331]
Hi @jurialmunkey 

Is it possible that since the latest developments of TheMovieDb Helper, the addon no longer supports accented characters in the French language? 

I have that kind of error:
  `Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe8' in position 169: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/plugin.py", line 9, in <module>
                                                Container().router()`

Here is my log file attached if it can help

Thank you for all good work :)
Kodi 18.9
Nvidia Shield
TheMovieDb Helper 4.0.26 
Skin Arctic Horizon 0.5.50

**EDIT:** I updated to the v4.0.28 of TheMovieDv Helper since I wrote this issue but unfortunately, it's the same

[kodi.log.txt](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5470587/kodi.log.txt)

**Comment by jurialmunkey** [comment]
I was wondering when some of these errors with accented characters would crop up! 

Can you test latest git version? I've fixed the ones I could find but I'm not sure if there's others I've missed.

**Comment by alKODIque** [comment]
Hi again, thanks for the fix and the quick reply !


It seems that the biggest problems are with trakt. 
And I can no longer use my player on widget of home screen when movie title have special characters too...

Here is my new log :)
[kodi (1).log.txt](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5470807/kodi.1.log.txt)

**Comment by jurialmunkey** [comment]
Thanks for the log, it was very useful!

Can you try with v4.0.30 (latest)? I've fixed the MPAA issue. I wasn't able to recreate the playback error though - hopefully I've fixed it.

**Comment by alKODIque** [comment]
It's seems to be all good for me now :)
I can use player functions with all movies with accented characters, open Trackt section ans tmdb lists

Thanks a lot!!!
I will let you know if I see something I missed

**Comment by jurialmunkey** [comment]
Excellent! Thanks so much for testing.

Yes, please let me know if any other errors crop up - hopefully I've got them all but I wouldn't be surprised if there's still a few lurking around!
