### ISSUE TITLE
Fanart.tv api posters and artworks issue

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/plugin.video.themoviedb.helper#334]
Hi jurialmunkey,

I use Fanart.tv api. Earlier for local content posters and artworks used to remain my local library ones. However, now for everything (both local and web content) posters and artworks are being fetched from fanart.tv.

Please advise. Thanks!

**Comment by jurialmunkey** [comment]
Do you have the "Get additional details from the local Kodi library database" option turned on in TMDbHelper settings?

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
Yes, the "Get additional details from the local Kodi library database" option is turned on in my TMDbHelper settings. Still I'm getting the above issue. This never used to happen in the version 3.x series of TMDB helper.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,

I further tested and found out that the above posters and artworks issue is not happening in widgets created from the default Trakt Watchlist.

**Comment by jurialmunkey** [comment]
@ShibajiCh - Are you still experiencing this problem or can I close this issue? It is working correctly for me as far as I can tell.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
Yes, you can close this issue. It's working fine for me too.
