### ISSUE TITLE
Cast info and other extra info in widget video info screen is no longer showing up for non-local videos

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/plugin.video.themoviedb.helper#335]
Hi jurialmunkey,

Cast info and other extra info in widget video info screen is no longer showing up for majority of the movies/tv shows which are non-local, in the latest updated version of TMDB Helper.

Please advise. Thanks!

**Comment by jurialmunkey** [comment]
If you use `Context Menu > Refresh Details` do you then get Cast in info dialog?
Also, can you view the cast by going `Context Menu > Browse lists > Cast`

Note that for most lists TMDb API does not provide cast details for items. A separate call needs to be done to pull down the detailed information (including cast) about the item. I only call this detailed info in the service monitor, and it's only added to listitems if it is previously cached because otherwise all the lists would take a significantly longer time to load. 

It's the reason why lists from Trakt take much longer to load - because I'm forced to lookup the details for each individual item since Trakt doesn't provide any artwork via their api. So I only do this where absolutely necessary and instead provide skinners tools to provide cast and details lookups on the fly.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
Yes, If I use "Context Menu > Refresh Details" then I'm getting Cast in info dialog.
Also, I can view the cast info by going "Context Menu > Browse lists > Cast".

However, in version 3.x series of TMDB helper the cast info and other extra info used to populate automatically as soon as I entered the Video Info page.

**Comment by jurialmunkey** [comment]
> However, in version 3.x series of TMDB helper the cast info and other extra info used to populate automatically as soon as I entered the Video Info page.

The way it works now is the same as it worked in v3. You probably just had those items cached already hence why they had details - but in the new version because the cache number has been bumped you won't have the same items cached and so they will need to be recached first.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,

Actually, I never has to use "Context Menu > Refresh Details" option earlier.
So does this mean that in the new version I have to use the "Context Menu > Refresh Details" option every time to display the extra info or will it get automatically cached slowly over time once I open the Video Info screen for an item?

**Comment by jurialmunkey** [comment]
The Refresh Details is a new addition to force the details to be downloaded. 

If the skin you are using has the TMDbHelper service monitor turned on then details will be retrieved automatically by hovering over the item (or opening info dialog).

The details will then be added to the item the next time the list is opened. Unfortunately Kodi doesn't provide anyway to modify listitems in real time without refreshing the entire directory (and I very much doubt users would want the directory to be constantly reloading while they are trying to scroll through it!)

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
Is there any way to turn on service monitor for tmdb helper on arctic zephyr 2? If so how? I really like the arctic zephyr 2 Skin. Also it's comparatively light weight for my Fire tv stick 4k compared to arctic horizon. Moreover the Seren theme for arctic horizon by drinfernoo is currently not working properly. He said he will fix the issues when seren v2.0 releases. So I might start using arctic horizon in future.

**Comment by jurialmunkey** [comment]
Is this issue still happening with the most recent version of the plugin. I have a feeling it might've been related to the empty tvshowtitle field which has now been fixed. Can you confirm if you are still having this issue?

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
The cast info is not appearing the first time when I enter the Movie/TV info page. However, if I refresh the widgets and re-enter the same Movie/TV info page again, the cast is appearing the second time. Is this supposed to work like this? If so, then it is working fine. Please advise. Thanks!

**Comment by jurialmunkey** [comment]
Yes cast is only available from a detailed request so I believe that this is functioning correctly. The plugin provides methods for skinners to retrieve the list on-the-fly and the refresh details command exists for skins that don't support the online lookup methods.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
Okay. Fine. Thanks!
