### ISSUE TITLE
Trakt Ratings not showing up on widgets using AuraMod 

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/plugin.video.themoviedb.helper#336]
Using AuraMod Skin with the latest version the track ratings don’t show up on widgets I reverted back to 4.0.26 and the track ratings showed up right away is this something that was removed with the latest update,, appreciate any feedback and thank you for all your hard work this is a truly amazing addon

**Comment by xyzfre** [comment]
![0F0A9DAE-239B-4027-9B38-403B478C242C](https://user-images.githubusercontent.com/49699869/97805037-9db02f80-1c21-11eb-9823-b57db8acb4c5.jpeg)
With the latest update only the red star shows up but not Trakt ratings like in this picture which looks amazing to me on the widgets

**Comment by jurialmunkey** [comment]
Ah yep you're right it's missing. Made a small mistake in a recent update. Should be fixed now. 😃

**Comment by xyzfre** [comment]
Now the Trakt  ratings show up only for seasons but not for episodes tested it by reverting back to 4.0.26 and the Trakt  ratings show up for episodes as well Sorry for the trouble just love seeing my ratings LOL

**Comment by xyzfre** [comment]
And also just noticed on episodes also the TMDB ratings were missing
