### ISSUE TITLE
[Bug] Not Grabbing Extra Artwork

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#337]
It doesn't appear that TMDbHelper items are getting multiple fanarts attached, even with a Fanart.tv key... This makes it so the background slideshow doesn't work for those items 🥴

**Comment by jurialmunkey** [comment]
Ah forgot that I didn't get around to adding extrafanart back in. This is a good reminder!

**Comment by daviddia5** [comment]
Will it be fixed in future versions? I loved this feature. Thanks for your excellent work!

**Comment by jurialmunkey** [comment]
> Will it be fixed in future versions? I loved this feature. Thanks for your excellent work!

Yes, soon! I have it half done sitting on a branch on my laptop - just haven't got to finishing it yet.

**Comment by jurialmunkey** [comment]
Actually, just realised a super simple way to do this. Not sure why I didn't think to do it this way before. 

Appears to be working well. Can you test and confirm?

**Comment by daviddia5** [comment]
> Actually, just realised a super simple way to do this. Not sure why I didn't think to do it this way before.
> 
> Appears to be working well. Can you test and confirm?

Solved! That is speed! Thank you! :)

**Comment by daviddia5** [comment]
Edit: It works but not in all (for example "This is us" only shows a fanart). I don't know if it will depend on the minimum rating of the fanart for them to appear. Thanks again!

**Comment by jurialmunkey** [comment]
> 
> 
> Edit: It works but not in all (for example "This is us" only shows one fanart). I don't know if it will depend on the minimum rating of the fanart for them to appear. Thanks again!

That's because it only has one background available on fanart tv:
https://fanart.tv/series/311714/this-is-us/
