### ISSUE TITLE
Trakt and TMDB ratings missing from episodes ,AuraMod Skin

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/plugin.video.themoviedb.helper#338]
Now the Trakt ratings show up only for seasons but not for episodes tested it by reverting back to 4.0.26 and the Trakt ratings show up for both episodes and seasons

**Comment by xyzfre** [comment]
And just noticed with the latest update on episodes also the TMDB ratings were missing reverted back to 4.0.26 and both show up TMDB ratings and Trakt

**Comment by jurialmunkey** [comment]
Okay, _now_ it should be fixed 🤞

**Comment by xyzfre** [comment]
Yup all working again thank you for all your hard work TMDB is amazing ,,love the new context menu👍🏼👍🏼 GREAT work

**Comment by xyzfre** [comment]
Sorry for rambling away but also just noticed when you point a widget it gives you the option of ranking ,date added etc.. Great for watchlist I always preferred date added,, love this feature TMDB gets better and better 🙌🏼👍🏼
