### ISSUE TITLE
Rating icons freeze when selecting movie set

### ISSUE THREAD

**Issue by DimitarCC** [jurialmunkey/plugin.video.themoviedb.helper#341]
When browsing movies library and have movies and sets when selecting movie then rating icons shows up normally if after that movie i select a movieset the rating icons from before selection are not cleared. Well sometimes cleared if i scroll very fast.
The problem is in  convert_media_type function

![image](https://user-images.githubusercontent.com/1904901/97968600-8b6ff600-1dc7-11eb-93c1-a3238a1b948e.png)

You are stripping the s at the end but then you search for 'sets'.
changing 'sets' to 'set' fixes the issue

**Comment by jurialmunkey** [comment]
Thanks! Fixed.
