### ISSUE TITLE
Bug[Next Aired]

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#342]
When I updated The movie plugin helper two days ago I noticed Next Aired tv shows a duplicated. 

![Next Aired](https://user-images.githubusercontent.com/2873112/98087666-5bccf680-1e78-11eb-9679-c57ad6650f51.jpg)

Thanks

**Comment by jurialmunkey** [comment]
Hmm that's unusual. I can't see any reason why that would happen. Can you try with latest (v4.0.34) and see if it is still happening?

**Comment by Blurayx** [comment]
it corrected it self after 4 hours before the v4.0.34 update. installed the latest version, working so far. I will monitor the Next Aired over the next few days.

![new](https://user-images.githubusercontent.com/2873112/98160229-c8c2a980-1ed5-11eb-9c47-050c53d61034.jpg)

Thanks
