### ISSUE TITLE
"Your Next Episodes", Watchlists, Collections Not Loading

### ISSUE THREAD

**Issue by LN13uLL** [jurialmunkey/plugin.video.themoviedb.helper#343]
Looks like "Your Next Episodes", watchlist and collection for both movies and shows are not loading.  Is there something that broke?

I'm using the official Aura skin on Kodi 18.9.

**Comment by jurialmunkey** [comment]
Working fine for me.

Got a debug log? Sounds like a Trakt connection issue

**Comment by elec2105** [comment]
link http://pastie.org/p/1KJ4MZ0M9lxL9210Dq9ELX

tmdb doesn't work after an update has been released

**Comment by KoRnEr007** [comment]
I have the same issue. I cannot retrieve my list on trakt.

**Comment by LN13uLL** [comment]
Somehow the trakt token got revoked. So I reauth trakt. It’s all good now. Sorry for the false alarm.
