### ISSUE TITLE
Strange error in log

### ISSUE THREAD

**Issue by Sajklops** [jurialmunkey/plugin.video.themoviedb.helper#344]
I've been trying to solve this for the last 2days and multiple instalations on multiple devices.
Whenever I try to play something from the newest version of tmdbhelper I get this error: https://pastebin.com/EKibkz1p

I've tried with clean installs of both Kodi 18.9 and 18.8, on 2 Nvidia Shields with android OS and a Win 10 PC.

Any idea as to what is going on?

**Comment by jurialmunkey** [comment]
It's because one of your player files contains a name with non-standard characters. Latest version of plugin from master has a fix to deal with these.
