### ISSUE TITLE
Cannot play some movies (Umlauts?)

### ISSUE THREAD

**Issue by khezuu** [jurialmunkey/plugin.video.themoviedb.helper#346]
Movie helper fails to play some movies. If I play them directly without the helper they work fine.

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5501732/kodi.log)

I have the suspicion that it has to do with "ä ö ü" being in the filename, but I know for a fact that it worked before.

**Comment by jurialmunkey** [comment]
Should be fixed now in 4.0.35
