### ISSUE TITLE
[Bug] Unable to play non-local videos from video info screen

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/plugin.video.themoviedb.helper#348]
Hi jurialmunkey,
I'm currently using version 4.0.36 of TMDB Helper with Arctic Zephyr 2 skin on Kodi version 18.9. I noticed that I'm unable to play any non-local videos from the video info screen. My player is currently set to default for Seren (Source Select) player. Once I click "Play" on the video info screen, Seren scrapes the sources properly but then fails to play the video once I click on any source. However, if I click on the context menu and then click on "Select Player" and try to play the video via the same Seren (Source Select) player then everything plays fine. Also, I have already set resolved_url as "True" for the player. As far as I can remember this issue was not there in TMDB Helper version 4.0.33 and started happening since the last two version updates. I checked on multiple devices. Could you please check what's the cause of this issue? Thanks!

P.S. Other people on Reddit also wrote about this issue. See here: https://www.reddit.com/r/Addons4Kodi/comments/jp8qwg/tmdbhelper_seren_not_playing_video_after_scrape/?utm_medium=android_app&utm_source=share

**Comment by ShibajiCh** [comment]
Update: I found a solution for this issue. What I did was that I changed the is_resolvable setting for the Seren (Source Select) player to "Play Media" instead of "Resolve URL". Then selected the default players and set them to Seren (Source Select) again. This solved the issue. The "Resolve URL" setting was the causing the issue.

**Comment by jurialmunkey** [comment]
Any addon that shells out to script to scrape sources, plays torrents, or does other complex scripted things will need to use "Play Media" as these addons don't resolve directly to a url.

Any addon that plays directly (e.g. Youtube) or uses inputstream adaptive (e.g Netflix, BiNGE, Disney+, HBO, Prime etc.) will almost certainly be able to use setResolvedURL.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,

Thanks for the above information!
