### ISSUE TITLE
Service Monitor on widgets

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#35]
Does tmdbhelper have something like SkinHelper.WidgetContainer so the service monitor can be used on widgets / dynamic lists?

**Comment by jurialmunkey** [comment]
Yes. I must've forgotten to add it to the Wiki:
```
SetProperty(TMDbHelper.WidgetContainer,WIDGET_ID,Home)
```

Note that you don't need to specify a container for the service monitor to work in dialogvideoinfo. You only need to specify the container ID if you need info on the actual home page itself.

**Comment by skyfsza** [comment]
Perfect, thanks!
