### ISSUE TITLE
Running on Matrix: The MovieDB Helper Error

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/plugin.video.themoviedb.helper#352]
Running with Kodi Matrix Alpha 3 on AH 0.5.51, I'm regularly get the message "The MovieDB Helper Error: See log for more information". Investigating the log I find that the relevant messages are:
2020-11-09 07:58:37.261 T:5604     INFO <general>: [plugin.video.themoviedb.helper]
                                                   lib.monitor.listitem.process_artwork
                                                   Error Type: TypeError
                                                   Error Contents: ("'>' not supported between instances of 'str' and 'int'",)

No further info seems to be available to help debug, but from my limited knowledge may be a Python 2-3 error

**Comment by berkhornet** [comment]
Hi. I've investigated a bit further and think the error may originate from lines 133 and 134 in the file \Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\monitor\listitem.py":

 if ADDON.getSettingBool('service_fanarttv_lookup'):
            details = self.get_fanarttv_artwork(details, tmdb_type)

Hope this helps

**Comment by jurialmunkey** [comment]
Sorry for the delay in getting to this one. My portable Matrix install got messed up and I had to get around to reinstalling it to test Matrix since I normally run Leia.

Above commit should fix this error (added to latest version on Matrix branch). Could you test and confirm?

**Comment by berkhornet** [comment]
Yep, that has fixed it. Many thanks for your help.
