### ISSUE TITLE
Context menu players doesn't show Play with EmbyCon

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#355]
I don't know why exactly but the Play with EmbyCon player doesn't show in the list of players available when using the context menu. I tried this from the library as I have currently set up Venom as the default one but there are some things I watch with EmbyCon.

**Comment by jurialmunkey** [comment]
Does it show if you play normally (without a default player enabled)?

**Comment by juanma-cvega** [comment]
Yes it does. But I just realised something weird. It only happens with one TV show (from the ones I've tested) in the library. If I try the same TV show from the addon or any other one from the library it shows up. So not really sure of what's happening there.

**Comment by jurialmunkey** [comment]
> If I try the same TV show from the addon or any other one from the library it shows up. So not really sure of what's happening there.

Possibly the assert value in the player file? It is asserting epid, so possible it doesn't have an epid (which is tvdb episode id) for that episode on Trakt.

Also note that if you are using the context menu addon to select a player from inside the library that TMDbHelper has to do some guess work based off the available infolabels to try to grab the correct episode ID from TMDb first before calling the player function - whereas from an actual TMDbHelper item the info is already there in the correct format.

**Comment by juanma-cvega** [comment]
I just verified that the TV show doesn't have the TVDB ID on TheMoviedb so that's probably it. But if that's the case why is it showing it when doing it from inside the addon? Based on what you just said, shouldn't it follow the same behaviour given there is no TVDB id?

**Comment by jurialmunkey** [comment]
Because inside TMDbHelper we already have TMDb ID so the player code then use that info to do a further look-up on Trakt for any missing IDs. However, in your library the context menu first needs to be able to find the item on TMDb. If you use TVDb as your library scraper then the info for the item in the library is going to be different from what's on TMDb so it makes it more difficult to find.

**Comment by juanma-cvega** [comment]
Ok, makes sense. In any case, I'm closing the issue as it looks like the expected behaviour.
