### ISSUE TITLE
View Season No longer in context

### ISSUE THREAD

**Issue by abbaskip** [jurialmunkey/plugin.video.themoviedb.helper#359]
Since the big code rewrite the handy "View Seasons" or whatever the option was called has disappeared from the context menu of an episode.

This was for episode views/widgets, and would take you to the TV shows season list so you could select episodes.

About a week or two ago I tagged @jurialmunkey in the old Closed case where it was originally added, but may have been missed.

**Comment by jurialmunkey** [comment]
`Context > Browse lists > Seasons`
