### ISSUE TITLE
Missing/Invalid OMDb API Key

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#36]
After kodi startup, if you have service monitor enabled, the first time the monitor does a look up it triggers the Missing/Invalid OMDb API Key dialog.

It doesnt effect the actual lookup and only happens once after startup.

**Comment by jurialmunkey** [comment]
Works fine for me. 

Check that your OMDb API key is correct. If you don't have an OMDb API key, then make sure the field is completely empty (including any spaces).

The Invalid/Missing API Key dialog only displays if the API returns a "401 Unauthorised" error. You only ever get a 401 if the API rejects your credentials.

**Comment by skyfsza** [comment]
I think OMDb might have been having an issue yesterday (at least for me), strange part is I was getting OMDb results despite the dialog. 

Not getting the Missing/Invalid key error today.

**Comment by jurialmunkey** [comment]
> 
> 
> I think OMDb might have been having an issue yesterday (at least for me), strange part is I was getting OMDb results despite the dialog.

The plugin caches results for 14 days (or longer if you change the setting). If a cached result exists, the plugin will use that instead of doing a request, so cached results will work even if the api is down etc.

Still it shouldn't be returning 401 unless API key is wrong.

**Comment by RaajeshwarTetgure** [comment]
![image](https://user-images.githubusercontent.com/106911654/216384765-98bbc4f8-ffb2-49c9-b1dd-7589a3c8144c.png)
is this api code is correct?
