### ISSUE TITLE
[Bug] Extended Info in TV Shows

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/plugin.video.themoviedb.helper#366]
The addon cannot find the TV Shows in Extended Info (Open Info). With movies there is no problem.

**Comment by matke-84** [comment]
I confirm too.

**Comment by drinfernoo** [comment]
This addon has nothing to do with either ExtendedInfo Script *or* OpenInfo.

**Comment by matke-84** [comment]
So where does that information come from? And how does extended info work with movies and not with tv shows?

**Comment by jurialmunkey** [comment]
I don't even understand what this issue is trying to say. Tmdbhelper isn't extended info...

**Comment by matke-84** [comment]
A lot of skins have support for extended info. When I select the extended info option for movies I get additional information but the TV shows don’t show anything, everything is empty. Some other similar addons do not have this problem.

**Comment by jurialmunkey** [comment]
Which skin... be specific about how to recreate the issue. What are the exact steps? I can't fix the issue if I don't even know how to make it occur in the first place.

Also keep in mind that ExtendedInfo is a depreciated addon that hasn't been worked in three years and won't be included in Matrix.

**Comment by matke-84** [comment]
I'm talking about titan bingie mode. When you enter movies or TV shows there is a more info button. Movies look like this
![movies](https://user-images.githubusercontent.com/74268331/99599431-ad8a8a80-29fb-11eb-974b-52a6927ed05c.png)
TV Shows
![tvshows](https://user-images.githubusercontent.com/74268331/99599499-c8f59580-29fb-11eb-8c14-ac4243a1585a.png)

**Comment by daviddia5** [comment]
In my case I use AuraMod and there is also a specific button for ExtendedInfo as well as a context menu. In previous versions it has always worked for both, movies and TV Shows. Now only works with movies.

**Comment by drinfernoo** [comment]
Titan BINGIE does not use TMDbHelper, as far as I'm aware... AuraMOD does, but only in certain sections, and the skin itself hasn't been updated in ages.

This doesn't sound like a TMDbHelper issue to me at all.

**Comment by matke-84** [comment]
@drinfernoo The man says it worked in previous versions of tmdb helper and now it doesn't.

**Comment by daviddia5** [comment]
Exactly, it had always worked in older versions.
From my ignorance I think it will be something simple because in Movies it works correctly.
I use the Openinfo version which is very fast and gives a lot of information.
This is the error message:
![IMG_20201119_143112](https://user-images.githubusercontent.com/74454397/99674944-f29fd280-2a76-11eb-80ad-82ec352738f3.jpg)

Thank you very much for all the work!

**Comment by jurialmunkey** [comment]
I just installed Titan Bingie skin and extended info doesn't even work from the tvshow library. 

If it doesn't even work in the library then it is a skin or Extended Info issue and nothing to do with TMDbHelper.
