### ISSUE TITLE
showyear and showpremiered player keys are None

### ISSUE THREAD

**Issue by L2501** [jurialmunkey/plugin.video.themoviedb.helper#367]
I beleve these worked previously in 3.3 but in 4.0.51 both are None

**Comment by jurialmunkey** [comment]
Ah yep you're right. Can you test latest git master? Should fix the issue.

You might need to refresh the details of the item first (Context Menu > Refresh Details) if the old details are still cached.

**Comment by L2501** [comment]
yes, all good now :+1:

**Comment by teletcl** [comment]
The problem back again.
