### ISSUE TITLE
Stream Doesn't Play After Clicking Link Using "Select Player" with "Play with Fen"

### ISSUE THREAD

**Issue by LN13uLL** [jurialmunkey/plugin.video.themoviedb.helper#368]
I can't steam to play a stream after a link is clicked on from Fen results.  I've tried using select player and then "Play with Fen"  from Aura Skin widgets from TMDB Helper widget and Seren Up Next widget.  I've set tmdbplayer with "PlayMedia" option.  After clicking the link, nothing happens.  If i got into the Fen add on and go to the shortcuts, it works fine.

I've attached the log
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5562217/kodi.log)

Let me know if you need any other details.

**Comment by jurialmunkey** [comment]
Looks like a misconfigured player file rather than a TMDbHelper issue:


TMDbHelper correctly executes the player function:

```python
2020-11-18 14:06:01.323 T:24235  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.script.router - attempting to play
                                            {'tmdb_type': u'tv', u'episode': u'6', 'tmdb_id': 1562, u'season': u'16', u'ignore_default': u'true', u'query': u'The Bachelorette'}
```

TMDbHelper then correctly builds the player plugin URL and sends to routing:
```python
2020-11-18 14:06:04.159 T:24235  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.player - finished executing action
                                            RunScript(plugin.video.themoviedb.helper,run_plugin=plugin://plugin.video.fen/?mode=play_media&vid_type=episode&library=True&query=The Bachelorette&year=2020&season=16&episode=6&ep_name=Week 6&tmdb_id=1562&premiered=2020-11-17)

```

TMDbHelper routing successfully completes and it calls the plugin in question:
```python
2020-11-18 14:06:04.427 T:24237   DEBUG: [plugin.video.themoviedb.helper]
                                            lib.script.router.Script - route_taken	run_plugin
2020-11-18 14:06:04.427 T:24237  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.script.router - attempting to play
                                            plugin://plugin.video.fen/?mode=play_media&vid_type=episode&library=True&query=The Bachelorette&year=2020&season=16&episode=6&ep_name=Week 6&tmdb_id=1562&premiered=2020-11-17
```

Plugin then runs:
``` python
2020-11-18 14:06:04.443 T:16622   DEBUG: RunScriptWithParams - calling plugin Fen('plugin://plugin.video.fen/','-1','?mode=play_media&vid_type=episode&library=True&query=The Bachelorette&year=2020&season=16&episode=6&ep_name=Week 6&tmdb_id=1562&premiered=2020-11-17','resume:false')
```

**Comment by LN13uLL** [comment]
Is that something that needs to be fixed your end or is there something I need to do on my end? 

If it’s something on my end, what do I need to look at and change?

**Comment by jurialmunkey** [comment]
I don't make third party players and I don't use that addon so I can't say what url it is expecting.

All I can say is that judging from the log, TMDbHelper is functioning how it is expected to based upon the player file that it has been given.

**Comment by LN13uLL** [comment]
Understood. Gotcha thanks. Basically if I’m able to figure out the url, I can update the player file?

**Comment by jurialmunkey** [comment]
@LN13uLL - Actually can you test latest version - it might fix your issue. I think some plugins maybe don't like being called with RunPlugin (ironic I know!) and will only work specifically with PlayMedia.

This "fix" reverts another fix so its going to cause issues elsewhere but I think I have another idea about how to deal with those.

**Comment by LN13uLL** [comment]
Yay thank you this fixes it!! That’s awesome!!

In my email notification, you mentioned the fix reverts a different issue. Just curious, what issue is that?

**Comment by jurialmunkey** [comment]
> 
> 
> Yay thank you. this fixes it!! That’s awesome!!
> 
> In my email notification, you mentioned the fix reverts a different issue. Just curious, what issue is that?

It was an issue with if you played from the info dialog and had default select action as browse (so pressing play in the info dialog would open the browse context menu and then selecting play from there would crash Kodi because it didn't like doing playmedia from playmedia). I've already got an alternate fix in though hence my edited comment.

See here for reference:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/332#issuecomment-720227378
