### ISSUE TITLE
[Bug] Home Widget(Next Aired Library)

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#371]
When I create a Next Aired Library widget on the home screen. After restarting Kodi it disappears.
it also happens when I restore skin settings from the backup. 

Setup: 
macOS
Nvidia Shield TV

![screenshot002](https://user-images.githubusercontent.com/2873112/99602364-3c49d800-29f9-11eb-9346-f51c218c4514.png)

![screenshot003](https://user-images.githubusercontent.com/2873112/99602379-410e8c00-29f9-11eb-86a6-1ab39c512b02.png)

![screenshot001](https://user-images.githubusercontent.com/2873112/99602400-4cfa4e00-29f9-11eb-8eda-34f1fe7ed756.png)

![screenshot004](https://user-images.githubusercontent.com/2873112/99602416-55eb1f80-29f9-11eb-8ce3-66cca087d02b.png)

After restaring Kodi
![screenshot000](https://user-images.githubusercontent.com/2873112/99602448-64d1d200-29f9-11eb-807e-217a4ff6d5c8.png)

Thanks

**Comment by jurialmunkey** [comment]
Ah I remember there was a similar issue in the old version. I'll see if I can find the issue which contained the fix.

**Comment by jurialmunkey** [comment]
Found the old issue here: https://github.com/jurialmunkey/skin.arctic.horizon/issues/119

But maybe it isn't the same because I've already got the fix in the code for v4
I'll do some digging and see what I can figure out.

**Comment by jurialmunkey** [comment]
Can you get me a debug log of this happening. I don't appear to be able to recreate the issue.

**Comment by Blurayx** [comment]
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5569024/kodi.log)

[kodi.old.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5569026/kodi.old.log)

**Comment by jurialmunkey** [comment]
Okay trying something out. Hopefully it works.

Can you install latest master version then restart Kodi and see if my latest changes help?

**Comment by Blurayx** [comment]
Hi, jurialmunkey

Unfortunately, Next Aired Home-Widget still not working. Creating Airing Today Home-Widget works without issues

After restarting Kodi. As you can see no issues with Airing Today. I hope this helps.
![screenshot001](https://user-images.githubusercontent.com/2873112/99721944-d5372c80-2aa7-11eb-9641-82d279a86b03.png)

**Comment by jurialmunkey** [comment]
Damn. It was a bit of a long shot though.

Are you still getting these errors in the log?

```php
2020-11-19 18:46:57.280 T:8375  NOTICE: [plugin.video.themoviedb.helper]
                                            Failed to import _strptime because the import lockis held by another thread.
2020-11-19 18:46:57.280 T:8375  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.timedate - date_in_range
                                            Error Type: AttributeError
                                            Error Contents: ("'NoneType' object has no attribute 'date'",)
```

Just wondering if it is related or coincidental.

**Comment by jurialmunkey** [comment]
Also, could you download this testing version from the test_log branch and then get me a log using that:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/test_log.zip

I added a few extra logging things to see what is happening.

**Comment by Blurayx** [comment]
Here is the log as requested🙂

[kodi.log.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5569858/kodi.log.zip)

Thanks

**Comment by jurialmunkey** [comment]
> 
> 
> Here is the log as requested🙂
> 
> [kodi.log.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5569858/kodi.log.zip)
> 
> Thanks

Thanks, that definitely confirmed the issue for me - the only issue is how to fix it (or rather how to work around what is a well known bug python's inbuilt datetime module).

Can you try latest master version that I just pushed now? According to a few python bug report threads this should fix the issue (though I'm skeptical but its worth trying - just wish I was able to recreate the issue so I could test myself).

**Comment by Blurayx** [comment]
Success. After instaling the latest master, Reloaded skin. Next Aired Library widgets appeared on the home screen. working perfectly now. Thank you for fixing it so quickly 😀

<img width="957" alt="Screenshot 2020-11-19 at 21 59 56" src="https://user-images.githubusercontent.com/2873112/99730003-aaeb6c00-2ab3-11eb-803b-7a16340a8af0.png">

After reloading the skin
![screenshot002](https://user-images.githubusercontent.com/2873112/99730332-2b11d180-2ab4-11eb-98f2-75670cf6b709.png)

**Comment by jurialmunkey** [comment]
Oh wow! I'm surprised it worked. Let me know if it pops up again but hopefully this is the solution!

**Comment by jurialmunkey** [comment]
Oh wait maybe try restarting Kodi and make sure that it doesn't happen after a restart not just a reload? I think this error is only likely to happen on start-up.

**Comment by Blurayx** [comment]
> Oh wait maybe try restarting Kodi and make sure that it doesn't happen after a restart not just a reload? I think this error is only likely to happen on start-up.

I tested restarting Kodi before I posted my results😀

**Comment by jurialmunkey** [comment]
> I tested restarting Kodi on the Nvidia Shield TV & macOS before I posted my results 😀

Oh excellent! Thanks so much for testing!
