### ISSUE TITLE
No Clearlogos or ratings on TV shows.

### ISSUE THREAD

**Issue by mathu204** [jurialmunkey/plugin.video.themoviedb.helper#373]
No clearlogos show up or ratings on Titan Bingie Mod in widgets or in the addon view. 
I can get clearlogo to show up by browsing into the show where the clearlogo then updates, and then ratings show up too but when i back out 7/10 times the clearlogo is saved but the ratings do not show up.

**Comment by drinfernoo** [comment]
Titan Bingie doesn't use TMDbHelper for artwork or metadata lookups.

**Comment by mathu204** [comment]
> Titan Bingie doesn't use TMDbHelper for artwork or metadata lookups.

I know I just set paths from it for widgets but does that mean it still won’t work?

**Comment by jurialmunkey** [comment]
Last update for bingie was 2 years ago which is before tmdbhelper even existed. Can't expect feature that require skin support to work in a skin that doesn't support them...

**Comment by drinfernoo** [comment]
To be fair, it is still being developed in a different branch: https://github.com/cartmandos/skin.titan.bingie

**Comment by jurialmunkey** [comment]
> 
> 
> To be fair, it is still being developed in a different branch: https://github.com/cartmandos/skin.titan.bingie

Last commit by Cartman.Dos is on Aug 11 2019

Though I just spotted on the forums that there is a mod version by some other users which is continuing to be updated:
https://forum.kodi.tv/showthread.php?tid=355993

Still, either way, there's no way to magic in skin support for features that require skin support if the skin doesn't support them! 😉
