### ISSUE TITLE
Next Aired - Loading Widgets

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#374]
Hi, jurialmunkey
Sorry to be a pain. Sometimes the Home Widgets don't load after restarting Kodi. Can you please look at my logs?

![screenshot001](https://user-images.githubusercontent.com/2873112/99874300-a40d4800-2bde-11eb-8515-2756713a0cad.png)

[kodi.log.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5577346/kodi.log.zip)
[kodi.old.log.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5577347/kodi.old.log.zip)

Thanks

**Comment by jurialmunkey** [comment]
I can't see anything specifically in the log but I have a feeling it might just be a Trakt issue. I've been having connection issues with the calendar end-point of the Trakt API all day

**Comment by Blurayx** [comment]
> I can't see anything specifically in the log but I have a feeling it might just be a Trakt issue. I've been having connection issues with the calendar end-point of the Trakt API all day

No worries, Thanks for taking a look 🙂

**Comment by jurialmunkey** [comment]
Let me know if it keeps happening over the next few days but today definitely it has been intermittent at best -- sometimes it will load and other times it will timeout or not return results.

**Comment by Blurayx** [comment]
Btw, when will you be releasing the Matrix version😀

**Comment by Blurayx** [comment]
> Let me know if it keeps happening over the next few days but today definitely it has been intermittent at best -- sometimes it will load and other times it will timeout or not return results.

Yes, That's the issue I'm having. I'll keep you updated.

Thanks

**Comment by drinfernoo** [comment]
@Blurayx There's a Matrix version of the repo that is kept up-to-date with the Leia repo... It's been on Matrix for months 😅

**Comment by Blurayx** [comment]
> @Blurayx There's a Matrix version of the repo that is kept up-to-date with the Leia repo... It's been on Matrix for months 😅

You're kidding me!!!!🤣
I'm going to give it a test drive, Now Matrix has gone into beta😀

**Comment by Blurayx** [comment]
> @Blurayx There's a Matrix version of the repo that is kept up-to-date with the Leia repo... It's been on Matrix for months 😅
to make sure we are on the same page. there is a matrix version of AH2?

**Comment by drinfernoo** [comment]
@Blurayx Ah, no. There's a Matrix version of TMDbHelper, which is where this issue is open. Probably my fault for causing confusion 😅

**Comment by Blurayx** [comment]
> @Blurayx Ah, no. There's a Matrix version of TMDbHelper, which is where this issue is open. Probably my fault for causing confusion 😅

No worries 😀

**Comment by jurialmunkey** [comment]
I'll be getting a Matrix version of Arctic Horizon ready really soon though! Hopefully in time for Christmas 😉 

My plan is first to get TMDbHelper stable enough to go for a 4.1.0 release on both Leia and Matrix official repo, then I'll work on the Matrix updates for Arctic Horizon. Really want to get everything up on the official repo by the end of the year if I can manage it.

**Comment by drinfernoo** [comment]
@jurialmunkey Do you intend to get AZ2 into the official and/or Matrix repo(s) as well?

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey Do you intend to get AZ2 into the official and/or Matrix repo(s) as well?

I don't really have the time to maintain it, let alone actually fix up all the various issues it currently has that would block repo inclusion. Plus, since I don't actually use it myself, I really lack the motivation to work on it. I'd rather spend time getting a proper light theme running for AH.

I can't really see myself returning to AZ2. Whilst there's lots I like about it, there's just too many aspects of it that I find completely frustrating but I can't be bothered to fix and then have to listen to complaints about things being removed etc. I'm sure sometime in the future I'll end up working on a Zephyr type skin but it is highly unlikely to be AZ2.
