### ISSUE TITLE
creating a player

### ISSUE THREAD

**Issue by mrXoo** [jurialmunkey/plugin.video.themoviedb.helper#378]
Hi there,

Im trying to create a player based on one of my addons.
What im trying to do is convert an existing openmeta player to your format. 
Having a real hard time.Basically i want to open the addon, then open the directory "movies" then open "Movies by Category" then open "2020movies"

also want to open a keyboard, type in the name of the movie and search for it. 
Is this possible?

Regards

**Comment by jurialmunkey** [comment]
Please read the wiki for details about how to create player files
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

**Comment by mrXoo** [comment]
I have but cant get it to work. How about i paste it here, maybe you can help me?

**Comment by mrXoo** [comment]
I have figured it out thank you.
