### ISSUE TITLE
Trakt

### ISSUE THREAD

**Issue by mrXoo** [jurialmunkey/plugin.video.themoviedb.helper#379]
Hi there,

Im really liking this addon with what ive done so far.

I have some of my Trakt lists set up as widgets and am Wondering if its possible to cache the lists so that they load quicker.

Also wondering if its possible to show all movies in my collection, rather than the first 20?

thanks again

**Comment by jurialmunkey** [comment]
> I have some of my Trakt lists set up as widgets and am Wondering if its possible to cache the lists so that they load quicker.

Lists are already cached. Basic lists are cached for 1 day (e.g. Popular/Trending Movies etc.). Lists that involve syncing (e.g. Recently Watched, Next-Up etc.) are updated based upon Trakt activity - i.e. if you watch something these will update.

Details for items are cached for 2 weeks.

> Also wondering if its possible to show all movies in my collection, rather than the first 20?

There is a next page button. Use that. Pulling details for more than 20 items at a time will take too long to load.
