### ISSUE TITLE
Trakt lists aren't loadind

### ISSUE THREAD

**Issue by jaum20** [jurialmunkey/plugin.video.themoviedb.helper#381]
`Error getting plugin://plugin.video.themoviedb.helper/?info=trakt_sortby&widget=true&tmdb_type=movie&parent_info=trakt_watchlist`

complete log here: https://anonymousfiles.io/AAd5jhgK/

**Comment by jurialmunkey** [comment]
Can you test latest master version. Should fix the issue.

**Comment by jurialmunkey** [comment]
@jaum20 - I was wondering if you've had a chance to test the fix yet?

**Comment by DreevCi** [comment]
I also have the same problem. I tested yesterday with the latest update available version in the repository, I don't know if that one contains the fix.

**Comment by juanma-cvega** [comment]
I also have the same problem. I tested yesterday with the latest update available version in the repository, I don't know if that one contains the fix.

**Comment by jurialmunkey** [comment]
> 
> 
> I also have the same problem. I tested yesterday with the latest update available version in the repository, I don't know if that one contains the fix.

What version? Fix was 4.0.73 and I can no longer recreate this error.

If you have a version higher than 4.0.73 installed and this error is still happening can you get me a debug log?

**Comment by juanma-cvega** [comment]
Ok, I was able to fix it but I had to reauthorise trakt in order for it to work. It's good for me so happy for you to close the ticket if no one says otherwise.
