### ISSUE TITLE
intergrate with extendedinfo

### ISSUE THREAD

**Issue by mrXoo** [jurialmunkey/plugin.video.themoviedb.helper#382]
Hi there again,

I was wondering if you would be able to incorporate the look of extendedinfo mod into TMDb helper addon.

Perhaps you wanted a simpler addon, that I understand.

Thanks

**Comment by drinfernoo** [comment]
TMDbHelper leaves that responsibility up to the skin developer.

**Comment by JayDee696969** [comment]
+1 Would also love to have a built in GUI for TMDBH like Openinfo
![Screenshot_2](https://user-images.githubusercontent.com/45118866/101128463-ba97a400-35cd-11eb-937a-e20838b5e3bb.jpg)
