### ISSUE TITLE
Wrong plot for sets

### ISSUE THREAD

**Issue by DimitarCC** [jurialmunkey/plugin.video.themoviedb.helper#383]
I am encountering an issue with the sets. Once i select a set item it shows correct the number of items inside, the name of the set. However on some sets it totally mistake the description.
For example if i select first Batman (original series) Set it correctly shows the description of the set. Then i select Star Wars set and instead of showing the description for the Start wars set it shows Batman description.
Its very weird since that happening on the random sets.
Also for sets it shows Trailer button from the previous selection.

**Comment by jurialmunkey** [comment]
Could you try with latest master (make sure to restart kodi after installing to ensure service monitor restarts)? Hopefully should fix the issue of some properties not clearing correctly.

**Comment by DimitarCC** [comment]
I tried it. Same situation. 
Select Batman Dark Knight set -> Description loaded correctly
Select Deadpool set -> description loaded correctly
Select Indiana jones set -> description loaded correctly
**Select Star Wars set -> load the descrription of Batman Dark knight set**
**Select The Mummy set -> Load the description of Terminator set**
**Select Mission Impossible set -> loads the description of Batman Dark knight set**
Also what i noted is when i open info page for the set (the one that loads wrong description) it tries to load the all movies contained in the set and it load the same movies that loaded description is for (ex. Start wars -> load movies for Dark knight set).
So i suppose is not something related to the not clearing properties but something related to wrong tmdb ID got or missing one.
I am running Kodi 18.9 on Coreelec if that matters.

**Comment by jurialmunkey** [comment]
I can't recreate this plot issue. I was able to recreate the trailer issue but that appears to be fixed with my previous commit.

Where are you viewing these sets from? A widget? Mixed in with other movies in the library? Or in the specific sets section of the library (i.e. the part that only shows sets and nothing else)?

Occasionally the service monitor gets stuck on a previous item and doesn't register the switch to the new item properly but it is very strange to have it happen consistently.

**Comment by jurialmunkey** [comment]
Also can you try latest master.  Might be something preventing retrieving type so previous details are still active.

**Comment by DimitarCC** [comment]
I tried the latest master. No change in situation.
I am showing the sets together with the movies (mixed view sets and single movies)
My Kodi language is English, however i am scraping my movies in Bulgarian.
Language setting in TMDbHelper is also Bulgaria(Bulgarian).
The set description is shown in Bulgarian to some sets and on others in english since there is no bulgarian translation in TMDb.
I agree is very strange. However i am not sure how i can help you to determine the problem.
What i think for most strange is that on Set info page even the items in the set are shown wrong(are they rendered by using TMDbHelper?).

**Comment by DimitarCC** [comment]
I investigated a bit and i think parsing of tmdb_id for the collection goes wrong for some collections and search return wrong id

**Comment by DimitarCC** [comment]
Well i have a new info.....
Disabling the cache for get_tmdb_id function (in file plugin.video.themoviedb.helper\resources\lib\tmdb\api.py) fixes the issue and now all is loaded correctly.
Maybe there is an issue with the cache. Can you check that out?
Basically i think for get of tmdb id should be no cache. Correct me if i am wrong... ;)

**Comment by jurialmunkey** [comment]
No it definitely should be cached because items only have one ID and cache entry is saved on the basis of the lookup params. It is a waste of bandwidth to make the same request for the ID multiple times when the result should be the same everytime since IDs don't change.

Something weird has happened where somehow the wrong result has been cached. I'll double check the naming of the cache because probably some naming errors on a none type

**Comment by DimitarCC** [comment]
OK i am not really sure how the cache is saved. But probably you are right....it is retrieved or saved wrong cache item. Maybe the name is not formed correctly since sets could not have ID or something like that. Yes please check the names that are saved especially with the sets. Thanks.

**Comment by jurialmunkey** [comment]
I can't really see any issues with the naming but I added some extra precautions just to be safe.

**Comment by jurialmunkey** [comment]
Anyway, marking this resolved for the time being as I have a feeling the wrong cached item might've just been from an earlier version of the plugin when there was an issue with sets and I simply forgot to bump the cache version to force a refresh.

Let me know if it pops up again.

**Comment by DimitarCC** [comment]
Well the problem is still there but i found what caused it.
If the name of the set is not in English or contains non-ASCII character cache got messed up and it not works anymore.
Since my set names are in Bulgarian (Cyrillic) the cache not works anymore and always returns wrong tmdb id.
Once i change to English scrapping it works just fine.
However in that case it is not usable for any other language than English :(

**Comment by jurialmunkey** [comment]
Can you test latest version? Should be working now.

**Comment by DimitarCC** [comment]
The latest version appears to work. Thanks.
