### ISSUE TITLE
Player code

### ISSUE THREAD

**Issue by mrXoo** [jurialmunkey/plugin.video.themoviedb.helper#385]
Hi there, 
Im trying to get your player to come up in script.extendedinfo addon. I have got movies working all good.

Im trying to get tv working now and having issues.

Here is the code im using:
`RunPlugin(plugin://plugin.video.themoviedb.helper?info=play&amp;tmdb_id=$INFO[ListItem.Property(tvshow.tmdb_id)]&amp;type=episode&amp;season=$INFO[ListItem.Season]&amp;episode=$INFO[ListItem.Episode])`

Here is what I came up with but it brings up the players but the keyboard says "none"
`				url = 'plugin://plugin.video.themoviedb.helper/?info=play&tmdb_id=%s&type=episode&season=%s&episode=%s' % ((Utils.fetch(TheMovieDB.get_tvshow_ids(self.tvshow_id), 'tvdb_id')), (self.info['season']), (self.info['episode']))	
			xbmc.executebuiltin('RunPlugin(%s)' % url)`
where am I going wrong?

**Comment by mrXoo** [comment]
this was the original code`		def play_episode(self):
			if self.dbid and int(self.dbid) > 0:
				dbid = self.dbid
				url = ''
				PLAYER.play_from_button(url, listitem=None, window=self, type='episodeid', dbid=dbid)
			else:
				url = 'plugin://plugin.video.openmeta/tv/play/%s/%s/%s' % (Utils.fetch(TheMovieDB.get_tvshow_ids(self.tvshow_id), 'tvdb_id'), self.info['season'], self.info['episode'])
				xbmc.executebuiltin('RunPlugin(%s)' % url)`

**Comment by mrXoo** [comment]
okay im pretty sure its to do with the id's being mixed up.
Here's what I have to play Queens Gambit
`				url = 'plugin://plugin.video.themoviedb.helper/?info=play&amp;season=%s&amp;tmdb_type=tv&amp;episode=%s&amp;tmdb_id=87739' % (self.info['season'], self.info['episode'])
`

**Comment by mrXoo** [comment]
https://www.themoviedb.org/tv/87739-the-queen-s-gambit


https://thetvdb.com/series/the-queens-gambit
TheTVDB.com Series ID 387115

**Comment by jurialmunkey** [comment]
TMDb IDs are not TVDb IDs. You need to pass TVDb ID to `tvdb_id=%s`
