### ISSUE TITLE
Playback with PlayMedia broken since 4.0.65

### ISSUE THREAD

**Issue by bidyboop** [jurialmunkey/plugin.video.themoviedb.helper#388]
When trying to play any movie, I select a plugin (in this case Seren), then on the next dialog I choose No (PlayMedia). This used to work until now. 
Since 4.0.65 the spinner shows, then Kodi freezes and quits.

I am running Kodi 18.9.0 on Android.

I pinpointed the issue to 4.0.65, playback still worked in 4.0.51 for me.

Just a wild guess, but maybe the changes in https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/142afaf923c9539226c1b8871a55075264b160e2 have something to do with the bug.

**Comment by jurialmunkey** [comment]
Debug Log?

Also what skin? I've found different skins react differently to certain scenarios.

**Comment by bidyboop** [comment]
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5647727/kodi.log)

Skin is the Kodi default (Estuary).
Kodi exits on Android when I try to launch from a .strm file in my library, and also when trying to launch from TMDbHelper menu.
Default action for TMDbHelper is 'Play', I have not changed that. I'm basically running default settings with default settings, logged in to Trakt, set up library sync, and configured some players with an URL.

I do think this change is suspect:
 https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/142afaf923c9539226c1b8871a55075264b160e2#diff-fba8cecd6bc784aeaa0474206bd212f91fd818bf780662864019b2ba2edd3c5dR478

 given that that's the last thing that can be seen in the logs befor Kodi closes.

I am using Android TV, but will try and reproduce from an Android phone as well.

**Comment by jurialmunkey** [comment]
Can you try with latest version from master.

I've added two extra options under "Expert" settings in TMDbHelper Settings.

First can you try changing `Delay before playing after dummy resolves` setting to be 1 second or higher. Try 1 first and then if still crashing, try higher values.

If that doesn't work, set it back to 0 and try disabling `Reroute PlayMedia to call xbmc.Player() directly`

Can you let me know if either of those work (or some combination of both)?

I think some Android systems don't like having the player called twice in quick succession. It works fine on all my Windows and Linux system but unfortunately I don't have an Android device that I can test on, so I'm essentially going in blind when it comes to platform specific issues.

**Comment by xxlren** [comment]
I made an account just to say that the player crashing kodi was fixed by setting the delay to over 1 second. Thanks for the help.

**Comment by bidyboop** [comment]
Setting the delay to 1 helped. Setting it back to anything below 1 seems to consistently crash the kodi app.

**Comment by jurialmunkey** [comment]
Thanks both! That is really useful information. It is as I suspected - Kodi doesn't like having two items playing in quick succession on Android.

I'll look to see if I can find a better way of handling this problem but at least for now you can use the work around of setting the delay in expert settings.
