### ISSUE TITLE
Error with Fen only with Episodes 

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/plugin.video.themoviedb.helper#389]
When trying to play next episode with TMDB Helper using Fen as a player I get a error pop-up it use to work before,,,with Movies it works fine ,I tried to configure the players I always had it set to setResolvedURL and it always worked fine in the past just can’t remember which version of TMDB ,but just to make sure I did try switching it to PlayMedia and User Choice and still got the error ,,on version 4.0.77 Using AuraMOD, K18.9 ,Nvidia Shield ,, and I also use Venom,Seren with player settings set to setResolvedURL And both played episodes with no problem,, thank you for all the hard work that goes into TMDB Helper✊🏼

**Comment by xyzfre** [comment]
![B1C8C19D-804D-4BE1-9D71-CC481567FC0D](https://user-images.githubusercontent.com/49699869/101258967-06446d80-36f4-11eb-81ce-303876eaf031.jpeg)
I’m not sure if this is helpful I will try to get a log

**Comment by drinfernoo** [comment]
This means the player needs to be updated.

**Comment by xyzfre** [comment]
Noob question but the json.openplayers or something in Fen

**Comment by drinfernoo** [comment]
Neither FEN (as far as I'm aware) nor this project are affiliated with the player files themselves.

**Comment by jurialmunkey** [comment]
Yeah this isn't a tmdbhelper error. Error with end plugin - I imagine that plugin has been updated and now expects a different path in the player file.
