### ISSUE TITLE
Library folder creation errors

### ISSUE THREAD

**Issue by ricinga666** [jurialmunkey/plugin.video.themoviedb.helper#390]
Hi I've just set library integration up for the first time and I keep getting folder creation errors.

I am adding two trakt lists.

I get the error message about free creation on every show in the list.
After running the update I have the folder  but only a couple of the folders have seasons inside.

I've rebooted my firestick and even cleared Kodi cache.  But I keep getting the error.

Is there something more I needed to do.

Regards Richard

**Comment by SJ50** [comment]
Settings > Library > Ignore folder creation checks

**Comment by ricinga666** [comment]
I turned that off. 

it looks like it has a default option for not adding duplicate content.  
I removed my previous folder subscription from Fen and then all the shows added ok.

**Comment by jurialmunkey** [comment]
> it looks like it has a default option for not adding duplicate content.

Yep, if the item is already in your library TMDbHelper will skip it to avoid double ups.
