### ISSUE TITLE
Clicking Show Title takes me to seasons of different show

### ISSUE THREAD

**Issue by abbaskip** [jurialmunkey/plugin.video.themoviedb.helper#392]
Thinking this bug may be due to a hash tag in a TV show title, but when searching for, or navigating to via lists, the show:
Dating #NoFilter 
it shows the show over view, but if I click it to open seasons it takes me to:
Dating Around

Figured this was a big with hashtags so worth raising.

**Comment by jurialmunkey** [comment]
@abbaskip How are you searching for this show? When I go to `TMDbHelper > TV Shows > Search` and put this show in I can't find any results for it.

I don't think it even exists on TMDb...
