### ISSUE TITLE
[Request/Suggestion] Add Year to Shows being added to Library, or add NFOs

### ISSUE THREAD

**Issue by mathu204** [jurialmunkey/plugin.video.themoviedb.helper#397]
I don't think it used to be like this for Movies but after updating to the latest Master to be able to add my watchlist, I noticed upon adding Movies to my library the Year is now added after the Movie title in (XXXX), as well as NFO's being added inside the folder which is great. The year alone is a great addition bc it lets the movies be scanned into my library correctly.

Now with shows being added to my library there were a few that were not added correctly or a different show was scanned in due to the year not being added correctly; EX: Drifters, Utopia, etc.
Do you think you could make it so the year is added in (XXXX) after show title when added to the library so the show can be scanned in correctly instantly without having to manually put the year on the folder after its added? Granted its not a super difficult task for me to do this but just thought it would be a nice suggestion and add more automation to the process of adding to library, then scanning in.

**Comment by jurialmunkey** [comment]
Tvshows have nfo added also. Use default tmdb scraper (not tvdb which will soon require a paid subscription anyway) and it should work automatically.

**Comment by mathu204** [comment]
> Tvshows have nfo added also. Use default tmdb scraper (not tvdb which will soon require a paid subscription anyway) and it should work automatically.

I don’t get any nfos added does using the tmdb scraper make them appear or something?

**Comment by jurialmunkey** [comment]
Nfo being added is by tmdbhelper not the scraper. Tmdbhelper should be adding nfo files to base tvshow folder

**Comment by mathu204** [comment]
> Nfo being added is by tmdbhelper not the scraper. Tmdbhelper should be adding nfo files to base tvshow folder

Oh okay, alright thank you. Do u think u can still add years to the tv show folder names though?

**Comment by jurialmunkey** [comment]
> Oh okay, alright thank you. Do u think u can still add years to the tv show folder names though?

It's not really possible because the ship has already sailed on that since people will already have their libraries setup.

It would basically mean that every single user would need to delete their entire TMDbHelper library on disk, then clean the Kodi library, then re-add everything and then re-scan. Not something that I'd want to force on everyone for a very small handful of shows no scraping correctly on a scraper that isn't the default.

**Comment by mathu204** [comment]
> > Oh okay, alright thank you. Do u think u can still add years to the tv show folder names though?
> 
> It's not really possible because the ship has already sailed on that since people will already have their libraries setup.
> 
> It would basically mean that every single user would need to delete their entire TMDbHelper library on disk, then clean the Kodi library, then re-add everything and then re-scan. Not something that I'd want to force on everyone for a very small handful of shows no scraping correctly on a scraper that isn't the default.

Alright I understand, IF it’s not too difficult to do, and not trouble to you; would u mind telling me how I could edit it in myself? If it’s a difficult thing to explain or just a lot for you to type or something it’s fine, but I would not mind trying to give it a go with some kind of reference.

**Comment by jurialmunkey** [comment]
It's complicated.

I did think about this more and I could add an optional setting to switch to including year - that way backwards compatibility is retained but the option is still there.

**Comment by mathu204** [comment]
> It's complicated.
> 
> I did think about this more and I could add an optional setting to switch to including year - that way backwards compatibility is retained but the option is still there.

That is dope If you do, the main reason I use tvdb is bc I use a skin and I like to have tvdb ratings for it to show up as well as tmdb and IMDb. 

Also when scraping tv shows with tmdb do u use just the main tmdb, or tmdb tv shows? Is there a difference?

**Comment by mathu204** [comment]
> It's complicated.
> 
> I did think about this more and I could add an optional setting to switch to including year - that way backwards compatibility is retained but the option is still there.

Hey so Im facing an issue where I have two shows: Drifters (2016), and Shameless US (2011). I have them in my library but when scanning them it shows the wrong shows. Switching from TVDB to TMDB and vice versa did not help. However renaming the folder with the correct year did. But by doing this, every time i run a tmdb update to add new episodes for my other shows, it ends up creating a Drifters and Shameless folder again without the years so I have to go and delete them every time. Any thoughts?

**Comment by jurialmunkey** [comment]
> > It's complicated.
> > I did think about this more and I could add an optional setting to switch to including year - that way backwards compatibility is retained but the option is still there.
> 
> Hey so Im facing an issue where I have two shows: Drifters (2016), and Shameless US (2011). I have them in my library but when scanning them it shows the wrong shows. Switching from TVDB to TMDB and vice versa did not help. However renaming the folder with the correct year did. But by doing this, every time i run a tmdb update to add new episodes for my other shows, it ends up creating a Drifters and Shameless folder again without the years so I have to go and delete them every time. Any thoughts?

Just leave it as named by tmdbhelper and then go into library pressing info on show choose refresh and then select the right show - scraper will now treat it as the show you selected.

**Comment by mathu204** [comment]
> > > It's complicated.
> > > I did think about this more and I could add an optional setting to switch to including year - that way backwards compatibility is retained but the option is still there.
> > 
> > 
> > Hey so Im facing an issue where I have two shows: Drifters (2016), and Shameless US (2011). I have them in my library but when scanning them it shows the wrong shows. Switching from TVDB to TMDB and vice versa did not help. However renaming the folder with the correct year did. But by doing this, every time i run a tmdb update to add new episodes for my other shows, it ends up creating a Drifters and Shameless folder again without the years so I have to go and delete them every time. Any thoughts?
> 
> Just leave it as named by tmdbhelper and then go into library pressing info on show choose refresh and then select the right show - scraper will now treat it as the show you selected.

Thanks that fixed it

**Comment by mathu204** [comment]
> It's complicated.
> 
> I did think about this more and I could add an optional setting to switch to including year - that way backwards compatibility is retained but the option is still there.

Bump on the added year optional setting, would make managing my shows with TinyMediaManager much much faster and less manual matching of shows !

**Comment by jurialmunkey** [comment]
@mathu204 - I can do you one better. Can you test latest version on master? All new shows will now have year appended and on first run it will do a run through of the folder and automatically rename any legacy folder names to include the year. 

The automated rename will only touch folders with a valid .nfo inside. Also, it won't do anything if there is a folder already exists with the name (i.e. it won't try to copy/move files into an existing folder, it only renames the folder).

After it runs it will do a once off library clean so that it removes any old entries. It will only ever run the one time -- basically the first time you try to add/update the library after the change it will run, and then it sets a flag to know that it has completed and won't do it again since there's no reason to.

**Comment by mathu204** [comment]
> @mathu204 - I can do you one better. Can you test latest version on master? All new shows will now have year appended and on first run it will do a run through of the folder and automatically rename any legacy folder names to include the year.
> 
> The automated rename will only touch folders with a valid .nfo inside. Also, it won't do anything if there is a folder already exists with the name (i.e. it won't try to copy/move files into an existing folder, it only renames the folder).
> 
> After it runs it will do a once off library clean so that it removes any old entries. It will only ever run the one time -- basically the first time you try to add/update the library after the change it will run, and then it sets a flag to know that it has completed and won't do it again since there's no reason to.

THANK YOU :D !, im currently running the update ive already seen many folders get renamed with the years added. Ill update when the process finishes hopefully with no errors
