### ISSUE TITLE
One click URL to update players

### ISSUE THREAD

**Issue by mrXoo** [jurialmunkey/plugin.video.themoviedb.helper#398]
Hi there,
I was wondering if you could let me know if there is a URL to update the players. 
really wanting to update my players automatically without having to answer all the prompts before they download. 
I did it with another meta addon, but it doesn’t look as simple as that.

**Comment by jurialmunkey** [comment]
I don't manage third party players. You can enter a url in the settings and download via that. You'll have to find the url yourself. I believe that there is a subreddit where you can find third party player files for kodi addons.

**Comment by mrXoo** [comment]
Sorry you misunderstood me. What I meant was the code  needed to automatically update the players.

**Comment by drinfernoo** [comment]
`RunScript(plugin.video.themoviedb.helper, update_players)`

**Comment by mrXoo** [comment]
I got that but it only takes me to next step which is  “Enter url to download players”
I was hoping to get everything extracted in 1 step.

**Comment by drinfernoo** [comment]
Have you already set an URL in the settings, prior to making that call? I'd think it should use the URL already defined in the settings.

**Comment by mrXoo** [comment]
Got it figured out. Had to change a bit of code in the router.py and the downloader.py
