### ISSUE TITLE
[Feature Request] Mixed Movies and Shows

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#399]
So I really like the randomized section and am looking to clone the Netflix style of widgets that mix for example Popular Movies and shows together in one widget, and would like to mix some of my TMDBH Movie and Show Trakt lists.  So im asking if possible to add some randomized sections that mix the two. Like Mixed Popular Movies and shows, or Trending movies and shows together? Or even possibly adding an option to the Discover section that would give the ability to make a custom mix and save it and use that as the widget? I do know about autowidgets and its abilities, however the issue with that is If I add TMDBH items to autowidgets all Trakt functionality is gone for the widget items. I use Auramod with it set to open Info screen by default that has the Trakt options, but theres no Trakt options there or in context menu when coming from autowidgets.

**Comment by matke-84** [comment]
Great idea. +1

**Comment by drinfernoo** [comment]
For what it's worth, the missing context menu items on AutoWidgets should be present in Matrix.

**Comment by JayDee696969** [comment]
> For what it's worth, the missing context menu items on AutoWidgets should be present in Matrix.

That will be my GOTO as soon as that 2.0 is released😉

**Comment by jurialmunkey** [comment]
@JayDee696969 
Please try latest. Should now have options for "Random {List} Combined" in the Randomised section. Possibilities are for Popular, Trending, Anticipated, and Most Played.

The other list types don't really support mixing. Keywords *only* works for Movies and the "Based on" lists can only be one type (TMDb only recommends items of the same type as the list is based on).

Trakt's custom lists already support mixing types, so nothing to do for those. It is just dependent on whether the list itself mixes types - e.g. "The Best Sci-Fi Movies" is obviously only going to have movies, but a list like "Netflix" is going to mix tvshows and movies.

> Or even possibly adding an option to the Discover section that would give the ability to make a custom mix and save it and use that as the widget?

This would be amazing but unfortunately the Discover endpoint on the TMDb API doesn't support mixing types.

**Comment by matke-84** [comment]
It works. Thanks a lot @jurialmunkey

**Comment by JayDee696969** [comment]
> @JayDee696969
> Please try latest. Should now have options for "Random {List} Combined" in the Randomised section. Possibilities are for Popular, Trending, Anticipated, and Most Played.
> 
> The other list types don't really support mixing. Keywords _only_ works for Movies and the "Based on" lists can only be one type (TMDb only recommends items of the same type as the list is based on).
> 
> Trakt's custom lists already support mixing types, so nothing to do for those. It is just dependent on whether the list itself mixes types - e.g. "The Best Sci-Fi Movies" is obviously only going to have movies, but a list like "Netflix" is going to mix tvshows and movies.
> 
> > Or even possibly adding an option to the Discover section that would give the ability to make a custom mix and save it and use that as the widget?
> 
> This would be amazing but unfortunately the Discover endpoint on the TMDb API doesn't support mixing types.

Your fast!!! Thanks so much!! This is great. Quick question, maybe I didnt notice before, was there never a Next Page option in the random sections before?

**Comment by matke-84** [comment]
@JayDee696969 Ohhh you're right. I didn't notice that only showed 20 movies and tv shows.

**Comment by JayDee696969** [comment]
> @JayDee696969 Ohhh you're right. I didn't notice that only showed 20 movies and tv shows.

Yea, TMDH only shows 20 items, but usually theres a next page option.

**Comment by matke-84** [comment]
@JayDee696969 Yes, yes I know. That’s why I said it only shows 20 movies and tv shows. For popular and trending lists combined, there is a next page.

**Comment by JayDee696969** [comment]
> @JayDee696969 Yes, yes I know. That’s why I said it only shows 20 movies and tv shows. For popular and trending lists combined, there is a next page.

Weird, Im not seeing a next page for the combined sections.

**Comment by matke-84** [comment]
You didn't understand me. I'm talking about the lists that existed before this update. Where there are netflix lists, imdb 250 lists, marvel lists...

**Comment by JayDee696969** [comment]
> You didn't understand me. I'm talking about the lists that existed before this update. Where there are netflix lists, imdb 250 lists, marvel lists...

Yea, it seems like its kinda mixed, some sections have a next page, some dont.

**Comment by jurialmunkey** [comment]
These aren't lists so there is no "next" page. These are just 20 items are taken at random from a pool like lottery number. There's no such thing as a "next" number until it is drawn - there is no order and thus no index to the items remaining in the pool. 

The reason the other sections have a "next" page is because for those it is the *list* itself which is drawn at random, not the items. The actual items in the list have a sort order applied, hence there is a "next" page of items to retrieve because each item has an index.

For instance, Random Popular Combined combines the lists of the top 50 movies and top 50 tvshows from Trakt and then 20 random items are drawn out of the pool to display - there's no "next" page, just a pool of items all jumbled together. By contrast, Random Popular List takes draws one *list* from a list of the most popular lists but the actual items inside are shown in normal order - there is a "next" page because the list has an order so we are able to ask for the next X items.

**Comment by JayDee696969** [comment]
Understandable, not an issue for me, was just curious, its random anyways and refreshes with different content anyways, so Im happy, Thank you!

**Comment by JayDee696969** [comment]
How about Random Recommended combined?
