### ISSUE TITLE
Integration with Seren Broken

### ISSUE THREAD

**Issue by Bulletbling** [jurialmunkey/plugin.video.themoviedb.helper#406]
Trying to play any content via seren does nothing. I did try with other addons and it works fine. I saw there was another issue (#316 I think) regarding this with Auramod skin users and I do indeed use Auramod skin. The fix was issued in 4.0.16. I believe I am on the latest (per the official jurialmonkey repo I’m using), which is version 4.0.77 and am still having this issue. I even tried manually downloading the “master” zip (whatever that means), which says it is version 4.1.4, and it’s still broken with Seren.

Btw, where in github does it show the current version or version history of tmdb helper? I can’t find it. The “jurialmunkey alpha repository” only shows 4.0.77.

—UPDATE—
After 5 attempts to play a very popular movie that should be available everywhere (Shawshank Redemption), I got Seren to work with TMDB Helper for just this movie. I have tried other shows and movies since this and cannot get Tmdb helper to do anything after choosing seren as the player. So it’s possible to work, but it is normally not working if this helps. Doubt this has anything to do with functionality, but Trakt is down/undergoing speed issues and maintenance at the moment.

**Comment by jurialmunkey** [comment]
1. I don't write third party players and I don't provide support for them.
2. Can't tell anything without a log
3. Have you tried playing from inside the addon you are attempting to play with? If you can't play inside the addon itself then clearly it is a problem with that addon and not TMDbHelper.
4. Trakt being down is almost certainly the issue. Many addons rely on Trakt IDs. Trakt down = no Trakt ID.

**Comment by Bulletbling** [comment]
> * Can't tell anything without a log
> * Have you tried playing from inside the addon you are attempting to play with? If you can't play inside the addon itself then clearly it is a problem with that addon and not TMDbHelper.
> * Trakt being down is almost certainly the issue. Many addons rely on Trakt IDs. Trakt down = no Trakt ID.

I was going to provide more info contingent upon seren 2.0 still having it broken for me, but 2.0 has resolved the issue.
