### ISSUE TITLE
[Bug] TMDBHelper keeps re-adding shows named "{showname} (TMDB {tmdbid})" or vice versa

### ISSUE THREAD

**Issue by mathu204** [jurialmunkey/plugin.video.themoviedb.helper#408]
So some information going into this, I was having an issue where the runtime was 0 for all my episodes in kodi making it so trakt was not syncing my episode playback progress correctly. I recreated all the show nfos and added episode nfos to my shows with TinyMediaManager and then wiped and readded my library in Kodi. By doing this though now a handful of my shows (ex:Big Mouth, Mandalorian, the Flight attendant) all get re added to my library folder in TMDBHelper with the name followed by (TMDB id in brackets). 

Ex, I have American Dad folder with the new show nfo and episode nfos from TinyMediaManager, on a TMDB Library update it creates another (empty or with just a tvshow.nfo) folder called American Dad (TMDB 1433). If i move all the files from American Dad to American Dad (TMDB 1433) and delete American Dad, on another TMDB update, it will instead make an empty folder called American Dad. 

Now there are some shows that I want this to happen on like shows with the same name, ex I have Top Boy (original series) and Top Boy from netflix 2019 in which the 2019 one is Top Boy (TMDB xx), this is fine. But the other shows I dont want this to happen and im not completly sure what caused this, i assume something went wrong when I redid all my NFOs through TinyMediaManager, I would not like to re-add all my shows and movies again though so hopefully I can figure out the problem.

I've enabled TMDBHelper debug logging and debug within Kodi settings as well. In this log I triggered a manual update and Drifters and Deadman Wonderland were both re-added. Some of these shows already get added with a tvshow.nfo (EDIT: as im writing this a lot more shows are now being re-added) although im not sure if the tvshow.nfo is the result of the library scanning them in as tmdb is updating bc if I remember correctly you said TMDBHelper doesnt create any nfos. Regardless here is an nfo from the empty folder, and an NFO from the one i made with TinyMediaManager as well as the log.

Debug Log
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5759699/kodi.log)

NFOs
https://www.dropbox.com/sh/nhd0nqu7kw0eiol/AACreRUve4p2EV0rwdCoWNfga?dl=0

EDIT: Actually when I first added all the NFOS, i made a complete copy of my .strm library called Library - Copy, (Og folder is just Library) I did all the nfo creations in Library - Copy and kept the original Library before anything just in case something got messed up. After adding all the nfos and stuff, I moved Library to a backup folder, and renamed the copy to jsut Library the exact same name so Kodi could just pick it up. It did work without me doing anything but after that I ended up changing content and setting it back so I did a full Library re-scan regardless. But maybe this could be important info

**Comment by jurialmunkey** [comment]
This isn't a bug - the problem is that you've edited TMDbHelper's .nfo files. You shouldn't edit _anything_ in the TMDbHelper library folder. TMDbHelper should be the _only_ thing editing anything in that folder. If you want to edit content manually, then you should separate that content into its own source folder.

The logic that TMDbH follows when adding/updating a show:

1. If there isn't a folder matching the showname then it will simply create one, add the .nfo + .strm files to it and then move onto the next show.
2. If there _is_ already a folder, then it compares the .nfo in the folder against the one it was planning to write. Matching .nfo files indicates that TMDbH created that folder for that specific show and thus it is safe to write the new .strm files to.
3. If the .nfo doesn't match, then that indicates to TMDbH that it isn't safe to write to that folder. Either it is a different show with the same name, or someone else created/modified the folder. So to make sure that things aren't written somewhere they shouldn't be, TMDbH will create a _new_ folder with the TMDb ID added to the end.

**Comment by mathu204** [comment]
> This isn't a bug - the problem is that you've edited TMDbHelper's .nfo files. You shouldn't edit _anything_ in the TMDbHelper library source folder. TMDbHelper should be the _only_ thing editing that folder. If you want to edit manually, then you should separate that content into its own library source folder.
> 
> The logic that TMDbH follows when adding/updating a show:
> 
> 1. If there isn't a folder matching the showname then it will simply create one, add the .nfo + .strm files to it and then move onto the next show.
> 2. If there _is_ already a folder, then it compares the .nfo in the folder against the one it was planning to write. Matching .nfo files indicates that TMDbH created that folder for that specific show and thus it is safe to write the new .strm files there.
> 3. If the .nfo doesn't match, then that indicates that either it is a different show with the same name, or someone/something else created/modified the folder. So to play it safe and make sure it isn't writing somewhere it shouldn't be, TMDbH will create a _new_ folder with the TMDb ID added to the end.

I see, the issue im having though is that I **had** to edit the nfos because the tmdbhelper nfos do not include runtime in it, or for whatever reason the TMDB pages it redirects to does not give episode runtimes, due to this episode runtimes are marked as 0, and when I run a trakt sync in my library to sync progress bc the number of 0 whenever it applys any percent of 0 it just wipes any progress I had. Adding the runtime was the only thing that fixed this, so if I am unable to edit the nfos without messing somehting up is there anythign that can be done on TMDBHelpers end to resolve this runtime issue? The related issue is over here if it is of any help

https://github.com/trakt/script.trakt/issues/518

The only way I could get around this without creating/editing nfos in the tmdbhelper library is by editing the .db file in Databases in Kodi/userdata. But id have to do it manually for each episode which would be extremely tedious.

**Comment by mathu204** [comment]
Do you think adding episode nfos with the runtime, and leaving alone the tvshow.nfo enable to me to fix my problem, without messing up things for TMDBH?

**Comment by jurialmunkey** [comment]
> Adding the runtime was the only thing that fixed this, so if I am unable to edit the nfos without messing somehting up is there anythign that can be done on TMDBHelpers end to resolve this runtime issue?

You can edit .nfo files, just not in the TMDbHelper source folder. You should create a new source folder in Kodi and move the folders that you want to edit there.

The more important question is why are you editing the .nfo for the tvshow? Only the episode .nfo contains runtime info, not the base tvshow.

**Comment by mathu204** [comment]
> > Adding the runtime was the only thing that fixed this, so if I am unable to edit the nfos without messing somehting up is there anythign that can be done on TMDBHelpers end to resolve this runtime issue?
> 
> You can edit .nfo files, just not in the TMDbHelper source folder. You should create a new source folder in Kodi and move the folders that you want to edit there.
> 
> The more important question is why are you editing the .nfo for the tvshow? Only the episode .nfo contains runtime info, not the base tvshow.

I would like to keep the source folder tho so that TMDBH can keep adding new episodes when they come out though, but then going to the other question then, would only adding the episode NFOs to add a runtime to episodes, while leaving the tvshow.nfo alone, enable me to Keep the source folder so new episodes get added, wont create new folders, and solve my trakt issue all in one?

**Comment by jurialmunkey** [comment]
> I would like to keep the source folder tho so that TMDBH can keep adding new episodes when they come out though,

Kodi allows you to have more than one source folder. You still keep the TMDbH one but also move the modified folders to a new source folder.

> Would only adding the episode NFOs to add a runtime to episodes, while leaving the tvshow.nfo alone, enable me to Keep the source folder so new episodes get added, wont create new folders, and solve my trakt issue all in one?

Yes, that would work. The only physical things that TMDbH checks is the .nfo for the base tvshow and the folder name. It doesn't look at anything else on disk.

**Comment by mathu204** [comment]
> > I would like to keep the source folder tho so that TMDBH can keep adding new episodes when they come out though,
> 
> Kodi allows you to have more than one source folder. You still keep the TMDbH one but move the modified folders out of there and into a new source folder.

Yea that is fine, Ive done that with other folders, but then the problem becomes whenever TMDBHelper drops a new episode it will drop it into the TMDB Source folder and not the new one where ive made all my edits, id then have to go to each show and find the new episodes then transfer them to my new folder which defeats the point for me Id rather just be able to fix the runtime problem and use TMDBH as i have been.

but regarding the second point, if i can just leave the show.nfo alone then Im good should be all fine. Thank you for educating me :D

**Comment by mathu204** [comment]
I redid my library with TMM leaving the show.nfos untouched but for some weird reason some of them were deleted, I ran a tmdb update hoping it would either add the missing .nfos back or just make the folder with (tmdb) next to it where I could just cut and paste the nfos back, delete the folders and be back to how it should be. Upon an update tho I got 2 errors don’t know if they did anything tho cause my library seemed fine but the only show that got the .nfo added was Seinfeld, out of like 10-15 shows that had show nfos missing.

https://paste.ubuntu.com/p/xz6RptgM7F/

ik this might not exactly be the same issue but I figure it’s better than making a new issue and clogging things up to u and this is about the same or similar enough topic

**Comment by jurialmunkey** [comment]
The errors are a separate issue. It'd be some weird non-ascii character in the showname. Thought I had already dealt with all those but looks like I've missed converting the text encoding somewhere.

If you're getting that exception it probably caused the update script to terminate early and not get through all the shows.

You can see if it completed by checking the update specific logs in the file (timestamp is replaced with actual time)
`kodi/userdata/addon_data/plugin.video.themoviedb.helper/log_library/YYYY-MM-DD-HHMMSS.json` 

If there isn't a log for when you ran it, then it didn't get to the end. If there is a log, that's a better place to look rather than using the Kodi log because it will tell you exactly what was added / skipped etc. and the reason why.

**Comment by jurialmunkey** [comment]
In the list where you have "72 Dangerous Animals Latin America", do you know what the next show after that is? Because that'd be the one that is causing the issue.

**Comment by mathu204** [comment]
> In the list where you have "72 Dangerous Animals Latin America", do you know what the next show after that is? Because that'd be the one that is causing the issue.

If I sort the library my name the next one is 90 day fiancé

**Comment by mathu204** [comment]
> The errors are a separate issue. It'd be some weird non-ascii character in the showname. Thought I had already dealt with all those but looks like I've missed converting the text encoding somewhere.
> 
> If you're getting that exception it probably caused the update script to terminate early and not get through all the shows.
> 
> You can see if it completed by checking the update specific logs in the file (timestamp is replaced with actual time)
> `kodi/userdata/addon_data/plugin.video.themoviedb.helper/log_library/YYYY-MM-DD-HHMMSS.json`
> 
> If there isn't a log for when you ran it, then it didn't get to the end. If there is a log, that's a better place to look rather than using the Kodi log because it will tell you exactly what was added / skipped etc. and the reason why.

By date modified Seinfeld is the last one updated in my library folder but is the log I check in tmdb supposed to go past that or stop at Seinfeld or before that for me to get anything? I also don’t think it did finish fully cause the shows I know don’t have nfos we’re not added and I can assume this is only cause the update didn’t finish.

**Comment by jurialmunkey** [comment]
> By date modified Seinfeld is the last one updated in my library folder but is the log I check in tmdb supposed to go past that or stop at Seinfeld or before that for me to get anything?

FYI date modified of the folder is when the folder was last modified, not its contents - so that won't tell you much at all.

The log is written at the end, so either it finishes and creates one successfully or it doesn't and there's no log.

I just went and checked the code and the part it is erroring on is when it reads the folder to update all shows, so whatever show you have alphabetically after "72 Dangerous Animals Latin America" is the one causing the issue. Can you grab me the name of the show and also its .nfo file so I can test?

**Comment by mathu204** [comment]
https://www.dropbox.com/sh/nhd0nqu7kw0eiol/AACreRUve4p2EV0rwdCoWNfga?dl=0

90 Day Fiancé , I think maybe the é has a part to play in it?

**Comment by mathu204** [comment]
yea there isnt a log btw the latest one is 2020-12-31

**Comment by jurialmunkey** [comment]
> 90 Day Fiancé , I think maybe the é has a part to play in it?

Yeah definitely is that. Managed to recreate myself by creating a fake folder using a string of non-standard characters `çßØÅ`
I know exactly what the issue is. Fix in a second.

**Comment by jurialmunkey** [comment]
Can you try latest and re-run the update. That should fix it.

**Comment by mathu204** [comment]
> Can you try latest and re-run the update. That should fix it.

Alright testing now, my library takes a bit to update tho since theres so much so might take me a bit to update

**Comment by mathu204** [comment]
The update finished, and the log was created let me check if the .nfos were added to all the shows that were missing them

**Comment by mathu204** [comment]
So all the shows here still have not had the .show nfos added to them, only exception being Seinfeld which was added before in the previous update before it cut off halfway. If it adds any info, **all** these shows are at the bottom of my folder when sorted by date modified, meaning these shows were the longest to have gone without any update I think.

I think maybe bc the update cut off halfway when i did it again maybe it just kinda picked up where it thoguht it left off leaving a lot of stuff in between? Ill try running another update and see if that fixes it this time.

Log:

![Capture](https://user-images.githubusercontent.com/52363082/103457882-e7c09a80-4cd0-11eb-97e3-e81177c711f4.PNG)

**Comment by mathu204** [comment]
Yea even after doing it again these shows dont get the show.nfos added it is only slightly annoying bc in the image above, without a show.nfo it gets marked as an X for incomplete nfos. I would make the nfos with the program but again that may break it bc the only show.nfo should be TMDBs

![Screenshot 2021-01-02 090425 PNG](https://user-images.githubusercontent.com/52363082/103459008-0e370380-4cda-11eb-94fb-a65cc30845c3.jpg)
![Screenshot 2021-01-02 090510](https://user-images.githubusercontent.com/52363082/103459010-0e370380-4cda-11eb-9311-0c5d4a320160.jpg)


Log: Shows like Sonic X, Atlanta, etc are not able to found in the log by ctrl-f
https://www.dropbox.com/s/ojeldn5cecuviqf/2021-01-02-090303.json?dl=0

**Comment by jurialmunkey** [comment]
@mathu204 - Are you sure that these items are in one of the Trakt lists that you are scanning? They'll only get added if they are in a list - TMDbH won't pick them up simply because there's a folder, it has to either have the .nfo (to be picked up by the library update script) or in a monitored list (to be picked up by the list adding script).

At worst you can always create the .nfo manually -- just take an .nfo from another show and replace the number inside the url it contains with the TMDb ID for that particular show. 

However, I'm very interested to know what is going on. Could you also grab me the actual debug log, as that might have some hints. If these shows are definitely in a monitored list, then something weird is happening. They still should show up in the .json even if they are skipped entirely -- not being in that file suggests that they were missed entirely for some reason.

**Comment by mathu204** [comment]
> @mathu204 - Are you sure that these items are in one of the Trakt lists that you are scanning? They'll only get added if they are in a list - TMDbH won't pick them up simply because there's a folder, it has to either have the .nfo (to be picked up by the library update script) or in a monitored list (to be picked up by the list adding script).
> 
> At worst you can always create the .nfo manually -- just take an .nfo from another show and replace the number inside the url it contains with the TMDb ID for that particular show.
> 
> However, I'm very interested to know what is going on. Could you also grab me the actual debug log, as that might have some hints. If these shows are definitely in a monitored list, then something weird is happening. They still should show up in the .json even if they are skipped from being added -- not being in that file suggests that they were missed entirely.

Oh okay, it is the first, these shows were not in a list when added i can just make the custom .nfos, so does that mean that library update will only update add new episodes to shows in my synced lists? For example I only have my watchlists, and 2 personal lists for library synced. But if i use the context menu to add a list called top 100 shows u must watch, its not synced i just added the list to my library, will that list not get updated or will it?

**Comment by mathu204** [comment]
So for these shows, after the Year update. Before the update i used ur idea of just making the nfos myself with the tmdb url. But these shows in the above pic are getting their folders remade with the show.nfo inside alone, rather than renaming the current folder. Not that big a deal cause its just a small handful of shows i have to fix and i think from there im good but just letting u know.
I compared the nfos and they are also the exact same
![Screenshot 2021-01-03 055306](https://user-images.githubusercontent.com/52363082/103476970-2cf3d380-4d88-11eb-99a5-6caf7a1b377a.jpg)

**Comment by mathu204** [comment]
So for those shows they were remade, i just deleted them and renamed the ones with the seasons and nfo in them correctly with the years. Hopefully after a library update next time it wont be re added under "Show name (year) (TMDB ID)" or something. I may just run another one tonight to make sure it works, but so far everything seems to have worked. 

I did face 1-2 small issues though a show called Failon Ngayon was added to my library, when i searched it in the log_library log from tmdb helper it didnt show up. So not sure what happened i just deleted it hopefully it wont be added again, i couldnt even find it on trakt so no way it could be in any of my lists either. It was an empty folder with just a tvshow.nfo that correctly led me to the show on TMDB, but the show doesnt even have any metadata, or episodes.

Also upon the library clean, my Kodi froze at around 4% and gave the not responding thing until it crashed. Normally it would hang and not respond around 4 and if i left it it would finish but this time it would not budge. I know this is probably not TMDBHelper related but if you find anything related to why it may have happened while looking at "Failed Ngayon" i would appreciate it a lot if u could point it out. 

Or even point me in the direction of where I should post to get help on that part, I would on the Kodi forum but there are probably some addons in my log so i wouldnt be able to get much help there.

https://www.dropbox.com/sh/nhd0nqu7kw0eiol/AACreRUve4p2EV0rwdCoWNfga?dl=0 

Here are the 2 TMDB logs cause tmdb did the library update twice, and then the kodi log.

**Comment by jurialmunkey** [comment]
> so does that mean that library update will only update add new episodes to shows in my synced lists? 

No. It will also update any shows in the source folder that have an .nfo that was made by TMDbH.

The update runs in two parts:

1. It updates/adds all the movies/shows in the monitored lists.
2. It scans the library source for tvshows and looks inside each folder for an .nfo file. If it was a .nfo made by TMDbH then it will update the show (assuming it wasn't already updated in step 1, otherwise it will be skipped due to being in the update log).

> But if i use the context menu to add a list called top 100 shows u must watch, its not synced i just added the list to my library, will that list not get updated or will it?

Yes, that will get updated in Step 2 because it will have a tvshow.nfo in its folder. 

> So for a handful of shows (the same ones from theTinyMediaManager picture with the "x's" above) the folders are being recreated rather than renaming with the year. 

That'd most likely be due to the url in the .nfo not being in the exact format that TMDbH expects (it is pretty picky about it because it expects it to be exactly the same as if it created it itself).

> So for those shows they were remade, i just deleted them and renamed the ones with the seasons and nfo in them correctly with the years. Hopefully after a library update next time it wont be re added under "Show name (year) (TMDB ID)" or something. I may just run another one tonight to make sure it works, but so far everything seems to have worked.

You probably will need to copy over the .nfo TMDbH created as the .nfo not being correct would be the reason it made a new folder.

> Also upon the library clean, my Kodi froze at around 4% and gave the not responding thing until it crashed. Normally it would hang and not respond around 4 and if i left it it would finish but this time it would not budge. I know this is probably not TMDBHelper related but if you find anything related to why it may have happened while looking at "Failed Ngayon" i would appreciate it a lot if u could point it out.

I'm not much of an expert on the db but I've found this tool useful in the past when I've had issues with corrupted entries: 
https://github.com/the-black-eagle/script.database.cleaner
https://forum.kodi.tv/showthread.php?tid=272112

**Comment by mathu204** [comment]
> > so does that mean that library update will only update add new episodes to shows in my synced lists?
> 
> No. It will also update any shows in the source folder that have an .nfo that was made by TMDbH.
> 
> The update runs in two parts:
> 
> 1. It updates/adds all the movies/shows in the monitored lists.
> 2. It scans the library source for tvshows and looks inside each folder for an .nfo file. If it was a .nfo made by TMDbH then it will update the show (assuming it wasn't already updated in step 1, otherwise it will be skipped due to being in the update log).
> 
> > But if i use the context menu to add a list called top 100 shows u must watch, its not synced i just added the list to my library, will that list not get updated or will it?
> 
> Yes, that will get updated in Step 2 because it will have a tvshow.nfo in its folder.
> 
> > So for a handful of shows (the same ones from theTinyMediaManager picture with the "x's" above) the folders are being recreated rather than renaming with the year.
> 
> That'd most likely be due to the url in the .nfo not being in the exact format that TMDbH expects (it is pretty picky about it because it expects it to be exactly the same as if it created it itself).
> 
> > So for those shows they were remade, i just deleted them and renamed the ones with the seasons and nfo in them correctly with the years. Hopefully after a library update next time it wont be re added under "Show name (year) (TMDB ID)" or something. I may just run another one tonight to make sure it works, but so far everything seems to have worked.
> 
> You probably will need to copy over the .nfo TMDbH created as the .nfo not being correct would be the reason it made a new folder.
> 
> > Also upon the library clean, my Kodi froze at around 4% and gave the not responding thing until it crashed. Normally it would hang and not respond around 4 and if i left it it would finish but this time it would not budge. I know this is probably not TMDBHelper related but if you find anything related to why it may have happened while looking at "Failed Ngayon" i would appreciate it a lot if u could point it out.
> 
> I'm not much of an expert on the db but I've found this tool useful in the past when I've had issues with corrupted entries:
> https://github.com/the-black-eagle/script.database.cleaner
> https://forum.kodi.tv/showthread.php?tid=272112

I compared the nfos and it was exactly the same just the basic tmdb url with the numbers at the end

**Comment by mathu204** [comment]
> > > so does that mean that library update will only update add new episodes to shows in my synced lists?
> > 
> > 
> > No. It will also update any shows in the source folder that have an .nfo that was made by TMDbH.
> > The update runs in two parts:
> > 
> > 1. It updates/adds all the movies/shows in the monitored lists.
> > 2. It scans the library source for tvshows and looks inside each folder for an .nfo file. If it was a .nfo made by TMDbH then it will update the show (assuming it wasn't already updated in step 1, otherwise it will be skipped due to being in the update log).
> > 
> > > But if i use the context menu to add a list called top 100 shows u must watch, its not synced i just added the list to my library, will that list not get updated or will it?
> > 
> > 
> > Yes, that will get updated in Step 2 because it will have a tvshow.nfo in its folder.
> > > So for a handful of shows (the same ones from theTinyMediaManager picture with the "x's" above) the folders are being recreated rather than renaming with the year.
> > 
> > 
> > That'd most likely be due to the url in the .nfo not being in the exact format that TMDbH expects (it is pretty picky about it because it expects it to be exactly the same as if it created it itself).
> > > So for those shows they were remade, i just deleted them and renamed the ones with the seasons and nfo in them correctly with the years. Hopefully after a library update next time it wont be re added under "Show name (year) (TMDB ID)" or something. I may just run another one tonight to make sure it works, but so far everything seems to have worked.
> > 
> > 
> > You probably will need to copy over the .nfo TMDbH created as the .nfo not being correct would be the reason it made a new folder.
> > > Also upon the library clean, my Kodi froze at around 4% and gave the not responding thing until it crashed. Normally it would hang and not respond around 4 and if i left it it would finish but this time it would not budge. I know this is probably not TMDBHelper related but if you find anything related to why it may have happened while looking at "Failed Ngayon" i would appreciate it a lot if u could point it out.
> > 
> > 
> > I'm not much of an expert on the db but I've found this tool useful in the past when I've had issues with corrupted entries:
> > https://github.com/the-black-eagle/script.database.cleaner
> > https://forum.kodi.tv/showthread.php?tid=272112
> 
> I compared the nfos and it was exactly the same just the basic tmdb url with the numbers at the end

Alright thank you for the db stuff I’ll try working on it
