### ISSUE TITLE
Clear Logo

### ISSUE THREAD

**Issue by SoulTV** [jurialmunkey/plugin.video.themoviedb.helper#41]
Would it be possible to use TMDB for all of the artwork and have TMDB Helper default to Fanart for items that TMDB doesn't provide like clear logo? Instead of like the all or nothing approach

**Comment by jurialmunkey** [comment]
That's the current approach. I always preference TMDb artwork over FanartTV as seen in the code:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/listitem.py#L83-L88

**Comment by SoulTV** [comment]
Ah, ok. Thxx
