### ISSUE TITLE
Update to be compatible with Seren 2.0 Context Menu (Trakt Manager)

### ISSUE THREAD

**Issue by iscriptu** [jurialmunkey/plugin.video.themoviedb.helper#411]
Hi,

When I tried to access Trakt Manager on a MDBHelper widget, I got an error and was told by the seren dev that this addon needs to be updated to be compatible with 2.0 so I hope you will do so.

Thank you

**Comment by SerpentDrago** [comment]
What do you mean by trakt manager .  Seren's Trakt manager ? that would not be a thing you could do from a non seren item / widget anyways . 

you need to explain yourself much better . this also doesn't appear to be a issue with TMDB helper by any means anyways . 

Seren's Context menu item "trakt manager" only works on SEREN items . it won't and will never work on other addons items such as tmdb helper . Tmdb helper has its own menu items for trakt actions

**Comment by jurialmunkey** [comment]
@iscriptu - I'm assuming this comment is what you are referring to: https://github.com/nixgates/plugin.video.seren/issues/282#issuecomment-753755837

As nixgates said, Seren's Trakt management options only work with Seren.

As SerpentDrago points out above, TMDbHelper has its own Trakt management options in the context menu for its items. Also, if you install the TMDbHelper [context menu addon](https://github.com/jurialmunkey/context.themoviedb.helper), these management options will also work with the library and potentially other addons (it does a query search of the item's title to try to find the correct ID).

Either way, definitely not a bug with either addon. If anything it sounds like an issue with the Auramod skin but I'm pretty sure that's not being developed anymore.

**Comment by SerpentDrago** [comment]
for the record Jurial not that you care / need to care .  Auramod's Trakt manager button on its INFO screen only shows / displays on  seren items . and it works fine . 

I have no idea what this guy was talking about . It designed as a purely seren feature . Obviously its not going to work on TMDB helper items as it uses specific seren paths .  but when the skin was developed we knew this and made it only appear on seren items . 

have a great day Jurial . and new year . thanks for all you do .

**Comment by iscriptu** [comment]
Wrong. The "Trakt Manager" button shows up on my "Recommendations" TMDBHelper widget and works. I know this because I use it to add shows/movies from my "Recommendations" to my watchlist. This didn't work in Seren 2.0 though.

The only thing that changed was the Seren update so I assumed that's the problem but then Nix said TMDBHelper needs to be updated to work with Seren 2.0 so that's why I posted here.

So, @SerpentDrago, I actually do know what I'm talking and unless I was fed wrong information, I'm right.
