### ISSUE TITLE
[Bug] Episodes with airdates beyond current date still being added to library (through context menu and force update)

### ISSUE THREAD

**Issue by unkn0wn234** [jurialmunkey/plugin.video.themoviedb.helper#412]
Hey jurial, got 2 requests for you based on some of our earlier conversations on Github.

Request 1: A GUI or just an option in the context menu or something to disable this show from being updated when TMDB does a update, or force library update in the settings. 

Context: I renamed an anime in my TMDBLibrary to absolute ordering and after running a force update it re added all the episodes beyond Season 1. An option to disable this show and others id like to rename from being updated until selected otherwise would be nice.

Alternatively I could just move this anime to another folder, which Id love to do and have all my anime in one folder but it would bug me if I had only some anime in that folder and the others remaining in TMDB (the ones that are still currently airing and need new episodes to be added to the folders, then library weekly or whenever). You also explained how having extra folders in TMDBHelper would just overcomplicate things and make things much more error-prone so that "solution" cant really be done of having an Anime folder for TMDB to add to and scan to seperately.

-- I just had a thought while writing this though i know its likely to get shut down (understandably) in which case i wouldnt mind. But is it possible to add a secondary (only 1 extra so it doesnt get too complicated) Show (or movie too) folder to the TMDBH settings, in which you can't add to it or mess with it using tmdbhelper, other than just adding it as a source to check. and TMDBH whenever updating will just scan this folder for the shows too and add episodes when available? that way (in my noob head correct me if im wrong) theres much less room for error. Itd be just one other folder for TMDB to scan when updating. 

Request 2: Don't add complete show (like dont add episodes beyond current release date) when adding through context menu "Add to Library". Or ask upon adding.

This isn't me asking to not add episodes without release dates as youve already explained how many episodes that are already released dont have release dates on TMDB and thus wouldnt be added. This is for when you add a show through the context menu (for me it was Re Zero), and it adds the whole show including the episodes that DO have release dates on TMDB and they are all beyond the current date. Normally as u said during a Library UPDATE, TMDB wont add episodes with release dates beyond the current date so can this be passed on to when you add through the context menu as well? It may have just been a glitch and added the other episodes let me know if that might be the case as well. 

I did notice that with Re Zero, it added the episodes beyond current release date, but after deleting those episodes and running a manual forced update in the settings which force re checkes everything. The Re Zero episodes in question were not re-added so the update libary side of this works as intended.

Here is a tmdb log as well as my kodi log if it helps.

https://www.dropbox.com/s/bi8a2kf9zhmc1ch/2021-01-09-175026.json?dl=0

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5791954/kodi.log)

**Comment by jurialmunkey** [comment]
Remove the tvshow from any monitored lists and delete the tvshow nfo and it won't update anymore. You don't need the nfo after it has scraped and you don't need to scrape it again since you aren't updating it with new episodes.

For the 2nd it sounds like a bug because it should respect the hide unaired setting when adding via context menu. I'll look into it - probably just missed something in the conditions.

**Comment by mathu204** [comment]
> Remove the tvshow from any monitored lists and delete the tvshow nfo and it won't update anymore. You don't need the nfo after it has scraped and you don't need to scrape it again since you aren't updating it with new episodes.
> 
> For the 2nd it sounds like a bug because it should respect the hide unaired setting when adding via context menu. I'll look into it - probably just missed something in the conditions.

Oh yea for the first that was such an easy fix I forgot about that completely. Thank you that will do the trick!

**Comment by jurialmunkey** [comment]
Re Zero doesn't have release dates for episodes past S02E15 so it is functioning properly there:

https://www.themoviedb.org/tv/65942-re/season/2/episode/16


Here's snippet of relevant data returned:
```
{
"name": "The Sounds That Make You Want to Cry", 
"air_date": "2020-09-30", "season_number": 2, "episode_number": 13}, 
{
"name": "Straight Bet", 
"air_date": "2021-01-06", "season_number": 2, "episode_number": 14}, 
{
"name": "Episode 15", 
"air_date": "2021-01-13", "season_number": 2, "episode_number": 15}, 
{
"name": "Episode 16", 
"air_date": "", "season_number": 2, "episode_number": 16}, 
{
"name": "Episode 17", 
"air_date": "", "season_number": 2, "episode_number": 17}, 
```

I just added via context menu E13/14 added because they have air dates in the past, E15 was skipped due to airing tomorrow, and E16/17 (and so on) were added due to not having air dates. So it is working correctly, at least in this instance.

**Comment by mathu204** [comment]
> Re Zero doesn't have release dates for episodes past S02E15 so it is functioning properly there:
> 
> https://www.themoviedb.org/tv/65942-re/season/2/episode/16
> 
> Here's snippet of relevant data returned:
> 
> ```
> {
> "name": "The Sounds That Make You Want to Cry", 
> "air_date": "2020-09-30", "season_number": 2, "episode_number": 13}, 
> {
> "name": "Straight Bet", 
> "air_date": "2021-01-06", "season_number": 2, "episode_number": 14}, 
> {
> "name": "Episode 15", 
> "air_date": "2021-01-13", "season_number": 2, "episode_number": 15}, 
> {
> "name": "Episode 16", 
> "air_date": "", "season_number": 2, "episode_number": 16}, 
> {
> "name": "Episode 17", 
> "air_date": "", "season_number": 2, "episode_number": 17}, 
> ```
> 
> I just added via context menu E13/14 added because they have air dates in the past, E15 was skipped due to airing tomorrow, and E16/17 (and so on) were added due to not having air dates. So it is working correctly, at least in this instance.

That is wierd when I first added and saw those episodes I made sure to check on tmdb before posting maybe it got removed or I just checked the wrong season? Well thanks anyways for helping with both cases :D

**Comment by unkn0wn234** [comment]
> Remove the tvshow from any monitored lists and delete the tvshow nfo and it won't update anymore. You don't need the nfo after it has scraped and you don't need to scrape it again since you aren't updating it with new episodes.
> 
> For the 2nd it sounds like a bug because it should respect the hide unaired setting when adding via context menu. I'll look into it - probably just missed something in the conditions.

hey jurial i think i maybe misread something, when u say respect the hide unaired setting do you mean the hide unaired setting in TMDBH? I was under the impression this was not good bc like u once told me many episodes that are already aired have no release dates and thus they would get skipped. Or is it that, hide unaired makes it so episodes WITH release dates beyond current date are added, but episodes that have no dates at all are still added no matter what

**Comment by jurialmunkey** [comment]
> Or is it that, hide unaired makes it so episodes WITH release dates beyond current date are added, but episodes that have no dates at all are still added no matter what

This.

The original version of Hide Unaired:
SKIP items that have an airdate AND that airdate is in the future.
INCLUDE items without an airdate OR with an airdate in the past.

With the new option "Hide items without airdates":
SKIP items without an airdate OR with an airdate in the future
INCLUDE items that have and airdate AND that airdate is in the past.

**Comment by unkn0wn234** [comment]
> > Or is it that, hide unaired makes it so episodes WITH release dates beyond current date are added, but episodes that have no dates at all are still added no matter what
> 
> This.
> 
> The original version of Hide Unaired:
> SKIP items that have an airdate AND that airdate is in the future.
> INCLUDE items without an airdate OR with an airdate in the past.
> 
> With the new option "Hide items without airdates":
> SKIP items without an airdate OR with an airdate in the future
> INCLUDE items that have and airdate AND that airdate is in the past.

Alright thanks. So earlier I had an issue with adding through context menu where it added episodes that were beyond the current date in airdate, and i thought it was a mistake cause it didnt happen for you but I just tested on a fresh install (pre Hide items without airdates TMDBH build) I was trying to test the differences. I used Riverdale 

https://www.themoviedb.org/tv/69050-riverdale/season/5

![Screenshot 2021-01-30 145635](https://user-images.githubusercontent.com/52363082/106366696-b6f17680-630b-11eb-941d-00ba108c2dd2.jpg)

https://www.dropbox.com/s/vk93jzmsn2f7f67/2021-01-30-145426.json?dl=0

As you can see it added episodes 3 through 7, 3, and 5-7 have airdates beyond today so they should not have been added. 

During this test I was expecting only episode 4 to be added alongside episode 1 and 2 because episode 3s airdate is Feb 3 (beyond today), while episode 4 has no airdate so it should have been added regardless. I was going to do this, then test with the new version and was expecting episode 1-2 only to be added with 4 being treated as unaired, however when checking my folder it added all the episodes. Ive attached the TMDB update log too if you could kindly take a look.

**Comment by unkn0wn234** [comment]
https://www.dropbox.com/s/3ynfqzel5s92aim/2021-01-30-150437.json?dl=0

Running a force update through TMDBH settings adds these episodes back too

**Comment by unkn0wn234** [comment]
Trying with the new version of TMDBH, with neither Hide unaired, or treat no airdates as unaired, doesnt add episode 4 to the library which I believe it should with all those disabled due to the hide unaired and airdates option both being disabled

**Comment by unkn0wn234** [comment]
> Trying with the new version of TMDBH, with neither Hide unaired, or treat no airdates as unaired, doesnt add episode 4 to the library which I believe it should with all those disabled due to the hide unaired and airdates option both being disabled

Nvm force closing and clearing cache through TMDBHelper fixed the problem in above, and now the settings correclty work even for Riverdale, but still not sure why it initally didnt work, even after the context add through a manual update it wasnt respecting it. But now it does, it seems to work as intended!

**Comment by jurialmunkey** [comment]
> Nvm force closing and clearing cache through TMDBHelper fixed the problem in above, and now the settings correclty work even for Riverdale

Ah that's interesting. I think maybe what happened was that your TMDbH settings file was corrupted or file system locked and Kodi wasn't able to read/write to it properly. 

That would also explain your Trakt authentication issue because the settings file is where the auth token is stored.

Other possible (though unlikely) causes I can think of:

- Corrupted entry in cache (doubtful since it still had enough data to add the episodes)
- TMDb API server error leaving airdates blank (also highly doubtful)
- Incorrect time set in System and/or Kodi (possible but unusual since clock is normally synced online - I'd maybe suggest a timezone issue if we were only out by a day but very unusual to have a completely incorrect date that is in the future)
- Regional specific air dates that are incorrect on TMDb (Im fairly certain that TMDb doesn't have regional specific dates but if they do this is a possibility)
