### ISSUE TITLE
Can't add an entire Trakt collection (or list) to TheMoviedbHelper library.

### ISSUE THREAD

**Issue by azdonw** [jurialmunkey/plugin.video.themoviedb.helper#413]
When in TheMovieDbHelper/Trakt, I can select my collection and see all of the shows, and I believe I could long press on an individual show and add it to the library (because I see "add to library" when longpressing). But when I try long pressing on my collection, all I see is "add to favourites"--no add to library. I'm using a NexBox A95x with Android 6.0.1 and Kodi 18.9.

**Comment by drinfernoo** [comment]
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/405#issuecomment-752872402

**Comment by mathu204** [comment]
> When in TheMovieDbHelper/Trakt, I can select my collection and see all of the shows, and I believe I could long press on an individual show and add it to the library (because I see "add to library" when longpressing). But when I try long pressing on my collection, all I see is "add to favourites"--no add to library. I'm using a NexBox A95x with Android 6.0.1 and Kodi 18.9.

If you want to add Collection to library, u cant with TMDBH as the linked comment above, but u can use Library Integration Tool its outdated but works perfectly still on TMDBHelper

**Comment by azdonw** [comment]
Thanks, that's helpful. With Library Integration Tool, can I add the Collection to the TMDBH folder?

**Comment by azdonw** [comment]
I did try something similar. I was using Venom for Trakt library integration. Then I copied all the folders/strm files from the Venom TVShows folder over to the TMDBH TVShows folder. Didn't turn out well. I ended up with duplicates of shows in some folders and some shows with no associated file.

**Comment by mathu204** [comment]
> I did try something similar. I was using Venom for Trakt library integration. Then I copied all the folders/strm files from the Venom TVShows folder over to the TMDBH TVShows folder. Didn't turn out well. I ended up with duplicates of shows in some folders and some shows with no associated file.

Don’t mix other folders into the tmdb source folder it will create duplicates as in your case bc everything follows a specific order and nfo type when tmdb detects it’s not there it will recreate it. If u want to use venom put it in its own folder and then add that as another source in your Kodi library so they are seperate  sources but will all show together in your library. And yes u can add tmdb collection to library with the tool just again put them in a. Seperare folder the tool will automatically make them I think anyway

**Comment by drinfernoo** [comment]
This is a mess 😅 The Library Integration tool may "work" but it's defunct, buggy as hell, and unsupported as far as I'm aware.

The point of there not being an easy way to do what you want, is that it's a feature you're using incorrectly.

If you haven't **collected** an item, don't put it in your **collection**.

**Comment by azdonw** [comment]
Thanks Mathu. Another question. I expected TMDBH to behave like OpenMeta and allow me to select which player to use by long pressing a show in the library and selecting the player. When I try this, I do see "TMDB Helper Options" at the bottom of the context menu, but the only option is "Add to Trakt List".  Is something wrong?

**Comment by azdonw** [comment]
> This is a mess 😅 The Library Integration tool may "work" but it's defunct, buggy as hell, and unsupported as far as I'm aware.
> 
> The point of there not being an easy way to do what you want, is that it's a feature you're using incorrectly.
> 
> If you haven't **collected** an item, don't put it in your **collection**.

I have collected many TV series in my Trakt collection. Now I want that collection to be in the library so that I can play shows from the library. I was expecting TMDBH to act somewhat like OpenMeta, and allow one to select which Addon to play an episode with by long pressing the episode inside the library and selecting the player to use. Having shows in the library is handy because you can readily see which ones you've watched (because of the checkmark next to the episode). OpenMeta worked great but is no longer supported.

**Comment by mathu204** [comment]
> > This is a mess 😅 The Library Integration tool may "work" but it's defunct, buggy as hell, and unsupported as far as I'm aware.
> > The point of there not being an easy way to do what you want, is that it's a feature you're using incorrectly.
> > If you haven't **collected** an item, don't put it in your **collection**.
> 
> I have collected many TV series in my Trakt collection. Now I want that collection to be in the library so that I can play shows from the library. I was expecting TMDBH to act somewhat like OpenMeta, and allow one to select which Addon to play an episode with by long pressing the episode inside the library and selecting the player to use. Having shows in the library is handy because you can readily see which ones you've watched (because of the checkmark next to the episode). OpenMeta worked great but is no longer supported.

The point is that your collection in Trakt is supposed to be a list of physical media you own and youre telling Trakt this is the stuff I actually own. Hence the name collection, its not meant to be just any shows uve watched or liked. Say I have the complete series of Dragon Ball Z on DVD, I would mark DBZ in my collection on Trakt to keep track of media that I own. Just do what I did and make two new lists called Movie Library and TV Library and add all the shows from your Trakt collection to those lists and then sync/add them to TMDBHelper. Then clear the trakt collection and either dont use it cause u dont need to anymore or just use it properly to keep track of media you own. Im the first one cause I dont really own much media now anyway. TMDBH is supposed to work like OpenMeta it sounds like u havent installed any players for it, when u use TMDBH to add to library as well you dont even need to long click it will instantly either bring up the play with menu or use the default players you set which is how i have it. Also for the checkmarks next to episode, you dont need library for that just use Trakt authorization in your favourite addons and you should be fine.

**Comment by azdonw** [comment]
I do have players installed. If I search for a show and find it, then click down to episodes. If I long press on an episode, I get a context menu that has "TMDB Options". Click on that, and I can select which player will be used to play the episode. It does not work this way in library--even if I added the show from within TMDBH. The point of wanting to do that is so that I can have a default player that is set to "auto-play", but if the episode does not play well, then I have the option to play the episode from another player via the context menu. Sure I could set TMDBH for "selector" and always have to select the player with witch to play, but auto-play is more seamless.

**Comment by drinfernoo** [comment]
@azdonw Sounds like that may be a separate issue.

**Comment by mathu204** [comment]
> I do have players installed. If I search for a show and find it, then click down to episodes. If I long press on an episode, I get a context menu that has "TMDB Options". Click on that, and I can select which player will be used to play the episode. It does not work this way in library--even if I added the show from within TMDBH. The point of wanting to do that is so that I can have a default player that is set to "auto-play", but if the episode does not play well, then I have the option to play the episode from another player via the context menu. Sure I could set TMDBH for "selector" and always have to select the player with witch to play, but auto-play is more seamless.

So you’re saying auto play and select player works? But u have autoplay in the library, but want to also be able to choose the player in certain cases with the long press? If I understand correct then what you are missing is the tmdb helper context menu it is an additional download in the repo

**Comment by azdonw** [comment]
> @azdonw Sounds like that may be a separate issue.

Yep, two issues. 1. Want to add the entire Trakt Collection to the library. 2. Want a  TMDBH context menu for the library to select which player to use.

**Comment by azdonw** [comment]
> > I do have players installed. If I search for a show and find it, then click down to episodes. If I long press on an episode, I get a context menu that has "TMDB Options". Click on that, and I can select which player will be used to play the episode. It does not work this way in library--even if I added the show from within TMDBH. The point of wanting to do that is so that I can have a default player that is set to "auto-play", but if the episode does not play well, then I have the option to play the episode from another player via the context menu. Sure I could set TMDBH for "selector" and always have to select the player with witch to play, but auto-play is more seamless.
> 
> So you’re saying auto play and select player works? But u have autoplay in the library, but want to also be able to choose the player in certain cases with the long press? If I understand correct then what you are missing is the tmdb helper context menu it is an additional download in the repo

Thanks, I will have to look for that context menu download.

**Comment by mathu204** [comment]
> > @azdonw Sounds like that may be a separate issue.
> 
> Yep, two issues. 1. Want to add the entire Trakt Collection to the library. 2. Want a TMDBH context menu for the library to select which player to use.

1. Is not an issue won’t be fixed. Make a new collection trakt list and add ur stuff to it if u want TMDBHelper to add it

2. Install tmdb helper context menu

**Comment by azdonw** [comment]
> > > @azdonw Sounds like that may be a separate issue.
> > 
> > 
> > Yep, two issues. 1. Want to add the entire Trakt Collection to the library. 2. Want a TMDBH context menu for the library to select which player to use.
> 
> 1. Is not an issue won’t be fixed. Make a new collection trakt list and add ur stuff to it if u want TMDBHelper to add it
> 2. Install tmdb helper context menu

Agreed.

**Comment by azdonw** [comment]
> > > @azdonw Sounds like that may be a separate issue.
> > 
> > 
> > Yep, two issues. 1. Want to add the entire Trakt Collection to the library. 2. Want a TMDBH context menu for the library to select which player to use.
> 
> 1. Is not an issue won’t be fixed. Make a new collection trakt list and add ur stuff to it if u want TMDBHelper to add it
> 2. Install tmdb helper context menu

Can you find that context menu on the Kodi repo/context menus? (not able to access my kodi right now)

**Comment by mathu204** [comment]
It’s in the same repo as tmdbhelper

**Comment by mathu204** [comment]
> > > > @azdonw Sounds like that may be a separate issue.
> > > 
> > > 
> > > Yep, two issues. 1. Want to add the entire Trakt Collection to the library. 2. Want a TMDBH context menu for the library to select which player to use.
> > 
> > 
> > 
> > 1. Is not an issue won’t be fixed. Make a new collection trakt list and add ur stuff to it if u want TMDBHelper to add it
> > 2. Install tmdb helper context menu
> 
> Can you find that context menu on the Kodi repo/context menus? (not able to access my kodi right now)

Jurialmunkey repo, context menus, tmdb helper additional context menus

**Comment by azdonw** [comment]
> > > > > @azdonw Sounds like that may be a separate issue.
> > > > 
> > > > 
> > > > Yep, two issues. 1. Want to add the entire Trakt Collection to the library. 2. Want a TMDBH context menu for the library to select which player to use.
> > > 
> > > 
> > > 
> > > 1. Is not an issue won’t be fixed. Make a new collection trakt list and add ur stuff to it if u want TMDBHelper to add it
> > > 2. Install tmdb helper context menu
> > 
> > 
> > Can you find that context menu on the Kodi repo/context menus? (not able to access my kodi right now)
> 
> Jurialmunkey repo, context menus, tmdb helper additional context menus

Thanks!
