### ISSUE TITLE
One show multiple listings.

### ISSUE THREAD

**Issue by Wafflestyx** [jurialmunkey/plugin.video.themoviedb.helper#414]
There are some discrepancies with how shows are listiwd on trakt vs TMDB.

Example: Whose line is it anyways
Ran from 1998-2007 then had a revival in 2013
Trakt groups this as one show.
https://trakt.tv/shows/whose-line-is-it-anyway-1998

TMDB lists it as two
Original https://www.themoviedb.org/tv/61018-whose-line-is-it-anyway
Revival https://www.themoviedb.org/tv/64978-whose-line-is-it-anyway

Is there a way to combine the two?
Does tvshow.nfo allow one to add two listings?

**Comment by jurialmunkey** [comment]
If you are talking about library integration, then that's a matter for whatever scraper you use. If you are talking about inside tmdbhelper, then no because obviously the data is dependent on how it is on tmdb
