### ISSUE TITLE
Tmdb Context Menu doesnt showing in Matrix for Library

### ISSUE THREAD

**Issue by Nazim1981** [jurialmunkey/plugin.video.themoviedb.helper#417]
I have installed TMDBH 4.2.10 in Matrix , I could not find context menu option anywhere for using in Library contents even I long press in one addon widgets it doesn't  show tmdb helper option in context menu even in library contents.

https://i.postimg.cc/tgFQzGjf/image.png

but strangely tmdbh version 2.4.36 does show context menu in addon widgets but not in Library contents 

https://i.postimg.cc/HLLr7jm3/image.png

kindly help out.

**Comment by drinfernoo** [comment]
That only shows up on TMDbHelper items.

**Comment by Nazim1981** [comment]
It should work with library contents , that is a basic thing.

**Comment by mathu204** [comment]
> That only shows up on TMDbHelper items.

To be fair, unless it was never meant to work like this and I just happened to reap the benefit of it till now, in Kodi 18 the TMDB Context menu option (TMDBH Options) does appear on content outside of TMDBHelper, I kinda assume thats the point, in case youre in an addon thats not TMDBH, it doesnt work, and u want to switch players/addons.

**Comment by jurialmunkey** [comment]
Install the context menu addon
https://github.com/jurialmunkey/context.themoviedb.helper
