### ISSUE TITLE
Cant play TV Shows from widgets using Seren players.

### ISSUE THREAD

**Issue by patel-jeel92** [jurialmunkey/plugin.video.themoviedb.helper#419]
With the new update to Seren, all my widgets for TV Shows are unplayable and always result in an error. For context, I am using TMDBHelperv 4.2.10 and Seren 2.0.16.

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5877741/kodi.log)

**Comment by jurialmunkey** [comment]
You need to set the resolve method for the player to be PlayMedia.

You can do this from the player configuration dialog in TMDbH settings.

**Comment by drinfernoo** [comment]
For what it's worth, and as far as I'm aware, the latest version of the player file he would be using does actually set the `is_resolvable` flag...

Since @patel-jeel92 wasn't very specific on his error, it appears to me from the log that the only *obvious* error is one from TMDbHelper; a `UnicodeDecodeError`.

**Comment by patel-jeel92** [comment]
So more info, I have seren.smartplay.json play_episode for episodes and seren.json play_movie for movies. And I just set `isResolveable`flag to PlayMedia for both and was still unsuccessful in playing movies and tv shows directly from widgets.

**Comment by jurialmunkey** [comment]
@drinfernoo - Whereabouts are you seeing the UnicodeDecodeError in the log?

All I see is this section where the log message `lib.player - finished resolving path to url` indicates that TMDbH is using setResolvedURL. It will say `lib.player - playing path with [xbmc.Player() | PlayMedia]` if it is using that method.
```
2021-01-26 22:27:06.936 T:8032  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.container.router - Attempting to play item
                                            {u'info': u'play', u'tmdb_type': u'tv', u'episode': u'2', u'islocal': u'True', u'tmdb_id': u'60573', u'season': u'6'}
2021-01-26 22:27:16.454 T:8032  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.player - finished resolving path to url
                                            plugin://plugin.video.seren/?action=smartPlay&forceresumecheck=true&actionArgs=%7B%22episode%22%3A%202%2C%20%22item_type%22%3A%20%22episode%22%2C%20%22season%22%3A%206%2C%20%22trakt_id%22%3A%2060157%7D
2021-01-26 22:27:21.410 T:26671   ERROR: Playlist Player: skipping unplayable item: 0, path [/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/tvshows/Silicon Valley (2014)/Season 6/S06E02 - Blood Money.strm]
```

**Comment by drinfernoo** [comment]
Ah, crud... maybe *I* read the error wrong on mobile 😅

I'm not really sure then 🤔 @patel-jeel92, the most recent update to the player file I'm thinking of was on 1/16/21.

**Comment by patel-jeel92** [comment]
Okay. Where can i potentially update them from? same bit.ly/tmdbplayers site? I am not sure what else i can provide other than the log.

**Comment by drinfernoo** [comment]
Yes, please try updating your players.

**Comment by jurialmunkey** [comment]
@patel-jeel92 - Yes another log after updating would be good if the error persists. Also I noticed in your log that you are playing from a .strm file - can you also try playing the same item from inside TMDbH itself and see if you have the same issue or not.

**Comment by patel-jeel92** [comment]
Okay I will try it out again. I did install the players again using the link I mentioned earlier.  And I will try to play from the add on as well. Will update this soon

**Comment by patel-jeel92** [comment]
Playing within the TMDBh addon didnt work either. I am attaching the log here:
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5896713/kodi.log)

**Comment by jurialmunkey** [comment]
Honestly looks like TMDbH is working fine.

In TMDbH addon settings under `Expert` you could try using PlayMedia instead of xbmc.Player by disabling
`Reroute PlayMedia to call xbmc.Player() directly (disable)`

But honestly it looks to be working fine and I suspect it is not a TMDbH issue.

**Comment by drinfernoo** [comment]
@patel-jeel92 Can you open your issue at https://www.github.com/a4k-openproject/json.openplayers/issues/ instead?

Maybe the player just needs to be fixed.

**Comment by patel-jeel92** [comment]
https://github.com/a4k-openproject/json.openplayers/issues/48

**Comment by Nazim1981** [comment]
Tmdbh unable to install URL players in Matrix , so I added players manually in Kodi folder and it reflects when I click tmdbh in context menu BUT BUT it doesn't recognizes DEFAULT player which I set to SEREN , so each time It took 3 steps first Long press and click tmdbh second ''Select Player'' Menu, third it took 5 Second to load and select Addon

**Comment by dplim87** [comment]
FWIW, I believe this issue resides in Seren. I've had the same issue, which I tracked down to be a silent failure on a SQL SELECT on the traktSync.db. For episodes, the player is called and this path silently fails: seren.py => g.init_request =>

**Comment by dplim87** [comment]
FWIW, I believe you can close this issue. I've had the same issue with Seren which tracked down to be a SQL query on traktSync.db in Seren that silently fails.

For episodes, the player is called and fails down this path: seren.py => g.init_globals = self.init_request => self.legacy_action_args_converter => shows.TraktSyncDatabase().get_episode_action_args => (shows.TraktSyncDatabase).filter_trakt_items_that_needs_updating

If the Trakt database isn't properly synced and the episode is missing from the show in the DB then it silently falls through. I think Seren 2.0 just has some hiccups to work through. Going into Seren's settings  to Shortcuts => Rebuild Database should fix the issue in the meantime.

As an aside, I think collaboration between add-on developers to create a separate Trakt add-on (or maybe an update to the offical Trakt addon) with it's own database to import as a dependency would be beneficial. It would stop the duplication of API requests for every add-on that queries Trakt and consistency in the data seen between add-ons. ¯\\_(ツ)_/¯

**Comment by Nazim1981** [comment]
Little confused , which folder we place players manually ? Path please

**Comment by dplim87** [comment]
> Little confused , which folder we place players manually ? Path please

@Nazim1981
It is documented in the wiki: [TheMovieDB Helper Wiki - Player Function](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function)
- Put user created player files in userdata/addon_data/plugin.video.themoviedb.helper/players/
- Player files configured within the addon have a copy stored in userdata/addon_data/plugin.video.themoviedb.helper/reconfigured_players/

Although the plugin works on Matrix (including downloading and installing players), keep in mind that Kodi v19.x "Matrix" is **not** a finalized release. If you're having issues with running the plugin on Matrix, you might want to stick with Kodi v18.9 "Leia" for the time being.
