### ISSUE TITLE
[Bug] "Manage Artwork" for NextUp widget - MenuItem Manage Artwork not showing and changes not applied

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/plugin.video.themoviedb.helper#420]
I have a widget Next Up episodes.  The widget is showing in PosterView, there are default Posters for the series visible.  I want to change the artwork. On longpress there is no menu for Manage Artwork [Bug]. 

In widget "Your recently Watched Tv Shows" I do have that menu Manage Artwork. Here I can change the artwork for Poster for a serie to something else.

Isn't the widget "Next Up" supposed to have Manage Artwork. If you put it on Landscape, for some series a scene-snapshot is visible.  Or Landscape art.  But in Posterview you should be able to change the generic poster for that show to another one no ?

Look at the screenshot on the left both art for Vikings.  Bottom one (Watched TV Shows) has menu "Manage Artwork" and has been changed. Top one (Next Up episodes) doesn't have that menu (as shown) and doesn't display the changed art.

![screenshot008](https://user-images.githubusercontent.com/10348988/106135051-adc7a480-6167-11eb-95a7-0823c59245af.png)

**Comment by jurialmunkey** [comment]
Manage artwork only works for tvshows/movies - it isn't available for seasons/episodes/people.

**Comment by DaisyF8** [comment]
Ah okay thanks

【Solved】
