### ISSUE TITLE
[Request] Retrieve playback progress(%) from local Kodi library data

### ISSUE THREAD

**Issue by unkn0wn234** [jurialmunkey/plugin.video.themoviedb.helper#426]
In the option in general "Get additional details from local Kodi library data" would it be possible to retrieve and display the playback progress of an episode or movie inside TMDBHelper as well? 

I know TMDBH doesn't even play anything and its addon dependent to resume, so not much reason or incentive for you to put it in it's really just a visual thing. 

But my use case is to test out using the widget from TMDBH instead of my local library one for Next episodes so metadata would just automatically update through TMDBH instead of me manually updating.

**Comment by jurialmunkey** [comment]
Not currently possible in Leia.

There's an update to Kodi core in Matrix which will make it possible - See here: https://github.com/xbmc/xbmc/pull/17202

However, for the time being I'm focusing on maintaining cross compatibility with Leia. I will eventually discontinue Leia support once Matrix is more established but that's a ways down the line yet. Once that happens I will start adding these types of Matrix only features.

**Comment by unkn0wn234** [comment]
Dope! I’ll look forward to it

**Comment by unkn0wn234** [comment]
> Not currently possible in Leia.
> 
> There's an update to Kodi core in Matrix which will make it possible - See here: [xbmc/xbmc#17202](https://github.com/xbmc/xbmc/pull/17202)
> 
> However, for the time being I'm focusing on maintaining cross compatibility with Leia. I will eventually discontinue Leia support once Matrix is more established but that's a ways down the line yet. Once that happens I will start adding these types of Matrix only features.

Hey Jurial I have a question about this, so when reading it it says "Video plugins should be able to synchronize their users' viewing activity between Kodi and corresponding API's of online streaming services (like Netflix or VRT NU)." Does this mean it will be possible to actually get playback progress from even the Trakt.tv website? Because if so that would be amazing!

**Comment by jurialmunkey** [comment]
> Does this mean it will be possible to actually get playback progress from even the Trakt.tv website? Because if so that would be amazing!

Yep, that's one of the most exciting parts of that feature. 

Not only will it mean that addons can share progress with each other via Trakt but it will also mean that you can continue watching on a completely separate Kodi device that uses the same Trakt account -- e.g. Start watching in Loungeroom on Device A using Addon X, then stop halfway through and continue watching in the Study on Device B using Addon Y.

**Comment by unkn0wn234** [comment]
> 

Just wondering if this is planned anytime soon for 2022 and Matrix where it's currently at?

**Comment by jurialmunkey** [comment]
> > 
> 
> Just wondering if this is planned anytime soon for 2022 and Matrix where it's currently at?

You can already enable progress from Trakt under accounts settings. To get progress from library just need to setup Kodi's trakt addon to sync it.
