### ISSUE TITLE
[Question] Your in-progress tv shows

### ISSUE THREAD

**Issue by 5ilv3r5urf3r** [jurialmunkey/plugin.video.themoviedb.helper#427]
Hi, I think I’m just missing a setting. But I can only see unwatched episodes listed here. Is there a way to see all episodes in the “your in progress tv shows”. I am able to see all episodes by going to the browse lists and seasons option.

**Comment by jurialmunkey** [comment]
In progress is for showing episodes you haven't watched yet. It makes no sense to show all episodes. Use recently watched if you want to access all episodes of recently watched shows.

If you need to go back and rewatch an already watched episode from in progress then use the season list from the context menu like you have been doing.
