### ISSUE TITLE
Trakt library automatic marked as watched doesn't work in Shadow addon

### ISSUE THREAD

**Issue by cgcgcgcgcg** [jurialmunkey/plugin.video.themoviedb.helper#428]
It works in Shadow if I open the TV Collection section.
I even tried to install the Trakt addon, but of course that changed nothing.
Auto marked as watched after watching an episode using TMDb Helper works fine with Seren, Venom and Fen though. Manually marking as watched works fine too.
Thanks for an amazing addon.

**Comment by cgcgcgcgcg** [comment]
> It works in Shadow if I open the TV Collection section.
> I even tried to install the Trakt addon, but of course that changed nothing.
> Auto marked as watched after watching an episode using TMDb Helper works fine with Seren, Venom and Fen though. Manually marking as watched works fine too.
> Thanks for an amazing addon.

I installed TMDbH v4.2.11 today and Seren auto marks as watched, Shadow still doesn't, so I edited the issue above.

**Comment by unkn0wn234** [comment]
> > It works in Shadow if I open the TV Collection section.
> > I even tried to install the Trakt addon, but of course that changed nothing.
> > Auto marked as watched after watching an episode using TMDb Helper works fine with Seren, Venom and Fen though. Manually marking as watched works fine too.
> > Thanks for an amazing addon.
> 
> I installed TMDbH v4.2.11 today and Seren auto marks as watched, Shadow still doesn't, so I edited the issue above.

might be addon dependent but idk

**Comment by drinfernoo** [comment]
This would be an issue with either Shadow or the player file. TMDbHelper doesn't mark as watched, as it leaves that up to the add-on used for playback.
