### ISSUE TITLE
[Request] Genres

### ISSUE THREAD

**Issue by Demonseeed** [jurialmunkey/plugin.video.themoviedb.helper#43]
Hello jurialmonkey!

I just wanted to throw another request your way that I think would be beneficial. 

The ability to select multiple genres at once. Possibly a button above Action & Adventure that says Multi Select (or something similar) that pops up a window dialog slowing you select multiple genres. From there, loading movies/shows that meet the genre requirements of all selected. 

Thank you!

Edit: Changed title because I had another request related to the theme. A genre for Anime, and then possibly splitting Anime from the Animation genre. 

After looking at TheMovieDb’s website, it seems Anime is all lumped together with Animation. Possibly Anime could pull genre (Animation) + Country of Origin/Original Language (Japan/Japanese). Animation possibly do the opposite (Genre - Country/Language)?

**Comment by jurialmunkey** [comment]
For complex calls, use the [Discover](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Lists-Discover) method. Discover allows you to combine several rules together.

Discover will translate genre names into TMDb IDs but it is better to use the actual ID if you know it.  
Here are the genre IDs for [Movies](https://api.themoviedb.org/3/genre/movie/list?api_key=a07324c669cac4d96789197134ce272b&language=en-US) and [Tv](https://api.themoviedb.org/3/genre/tv/list?api_key=a07324c669cac4d96789197134ce272b&language=en-US)

### Examples
**Movies that are Action (28) or Comedy (35)**
`plugin://plugin.video.themoviedb.helper?info=discover&amp;type=movie&amp;with_id=True&amp;with_separator=OR&amp;with_genres=28 / 35`

**Movies that are Action (28) *and* Comedy (35)**
`plugin://plugin.video.themoviedb.helper?info=discover&amp;type=movie&amp;with_id=True&amp;with_separator=AND&amp;with_genres=28 / 35`

**Movies that are Action but are NOT Comedy**
`plugin://plugin.video.themoviedb.helper?info=discover&amp;type=movie&amp;with_id=True&amp;with_separator=AND&amp;with_genres=28&amp;without_genres=35`

**Comedy Movies by Arnold Schwarzenegger**
`plugin://plugin.video.themoviedb.helper?info=discover&amp;type=movie&amp;with_separator=AND&amp;with_genres=Comedy&amp;with_cast=Arnold Schwarzenegger`

**Horror Movies by David Cronenberg**
`plugin://plugin.video.themoviedb.helper?info=discover&amp;type=movie&amp;with_separator=AND&amp;with_genres=Horror&amp;with_crew=David Cronenberg`

**Movies that have the Anime (210024) keyword**
`plugin://plugin.video.themoviedb.helper?info=discover&amp;type=movie&amp;with_id=True&amp;with_keywords=210024`

**Tv Shows that have the Anime (210024) keyword**
`plugin://plugin.video.themoviedb.helper?info=discover&amp;type=tv&amp;with_id=True&amp;with_keywords=210024`

To get the keyword ID I just googled *anime keyword tmdb* and and then took the ID from the number in the url: https://www.themoviedb.org/keyword/210024-anime/tv?language=en-US

**Comment by drinfernoo** [comment]
Wow, that is awesome. I love how powerful this add-on is becoming!

**Comment by jurialmunkey** [comment]
> 
> 
> Wow, that is awesome. I love how powerful this add-on is becoming!

Discover has been there almost from the start. It's just not exposed by the UI so I think most people don't know about it.

**Comment by jurialmunkey** [comment]
It's super powerful though! I'm thinking of maybe having a folder of pre-built discover lists to showcase it a bit more.

**Comment by drinfernoo** [comment]
@jurialmunkey Makes sense... I do feel like it's tough to use these paths for normal users, though, as it seems they're more designed with skinners in mind.

**Comment by jurialmunkey** [comment]
Yeah definitely meant for skinners and so it's not that accessible by normal users. Maybe it might be possible to have a dialog that exposes the parameters a bit like how the filter dialog works in a normal library view - I think I would need to have a custom skinned dialog though, which is something I'm hoping to avoid.

**Comment by drinfernoo** [comment]
You're the king of skins! I'm sure you could handle a dialog 😁

Maybe something in your Skin Shortcuts dialog like "Add Parameter", or similar, that would let the user type, and then append it to the end of the shortcut?

**Comment by jurialmunkey** [comment]
> 
> 
> You're the king of skins! I'm sure you could handle a dialog 😁
> 
> Maybe something in your Skin Shortcuts dialog like "Add Parameter", or similar, that would let the user type, and then append it to the end of the shortcut?

It's more that I don't want to add additional dialogs that other skinners need to deal with in their own skins. One of the big pain points of addons like extended info, global search, next aired, and up next is that they all add multiple additional dialogs that need to be skinned.

I want to keep implementation as simple as possible. That's why I spent a lot of time figuring out a way to provide an extended info type experience using the inbuilt video info dialog.

It provides consistency whilst simultaneously giving a lot more freedom over layout etc.

**Comment by Demonseeed** [comment]
Thank you for the information. 🙏 I saw the Discover List, I just wasn’t 100% sure how I’d implement it yet, this is a good example. 

As for the exclusion parameter `&amp;exclude_key=KEY&amp;exclude_value=VALUE` what are the keys? Are these things like people, crew, cast, etc?

For example: if I wanted to exclude movies by Ryan Gosling, I would do:
`&amp;exclude_key=crew&amp;exclude_value=Ryan Gosling`?

**Comment by jurialmunkey** [comment]
Exclusions/filters will work for any TMDb list. They are the key/value pairs that are returned by the API end point.

If you look at the Responses Schema for an end-point, you can see what key/value pairs are returned. For instance, here is the discover end-point: https://developers.themoviedb.org/3/discover/movie-discover

Discover is pretty limited in info it returns: `poster_path` `adult` `overview` `release_date` `genre_ids` `id` `original_title` `original_language` `title` `backdrop_path` `popularity` `vote_count` `video` `vote_average` -- So there isn't a lot to filter/exclude against other than title or original language.

Other end points support Append to Response which gives a lot of extra data. Or the person end-points like "credits", have things like character, job, and role which you can filter against.

**Comment by Demonseeed** [comment]
Good to know, thanks again!

**Comment by jurialmunkey** [comment]
@Demonseeed @drinfernoo - Please test latest version (2.2.5). I've added a new "Discover" folder in the addon which will allow you to customise the discover call.

It should work fine with skinshortcuts / as a widget, also. It translates whatever parameters you set into a discover url, so you should be able to create multiple discover widgets with different settings.

Let me know your thoughts and if you encounter any bugs.

**Comment by Demonseeed** [comment]
Just checked it out. I don’t have the time atm to fully delve into it, but so far this is super cool. It reminds me of the left side bar from Extended Info. 

Haven’t ran into any problems with the bit of testing I did, though I will admit it took me longer than it should have to realize the first letter of the genre has to be capitalized 😂

**Comment by jurialmunkey** [comment]
Yep, it's essentially the same principle as the extended info side bar -- which I'm pretty sure also uses discover endpoint.

Any names that you enter (genres, cast, companies etc.) must match TMDb exactly, including case.

**Comment by Demonseeed** [comment]
Yeah that’s what I figured once I realized the genre had to be capitalized. This is badass, jurialmonkey!

**Comment by jurialmunkey** [comment]
@Demonseeed - Please test latest version. I've now added search / select dialogs to the discover method, which means that now you don't need to know IDs or have exact actor names etc. Instead, you can type part of a name and you will get a select dialog to choose the correct item. After selecting an item, you will get the option to add more.

**Comment by drinfernoo** [comment]
@jurialmunkey That would be great! I quickly tested the previous changes this morning, but found it hard to figure out what I was supposed to be putting 😅

**Comment by Demonseeed** [comment]
That sounds amazing! I will test it out tomorrow and let you know my thoughts. 👌

**Comment by Demonseeed** [comment]
I just tested it out, and I gotta say this is pretty cool. 

It works completely while doing it within the addon, however, it didn’t work for me as a widget. I am using the current version from github. 

When I add it as a widget, it tried to load for a few moments, then pops up the dialog to choose the rules I want to to filter it by. Once I do this again on the home screen, the widget loads. 

Here’s what I did to create this:
1. Go through the skin and start creating a shortcut to Discover > Discover Movies. 
2. Added some parameters. In this example I added a “With Genres” > Animation and  “Primary Release Year” > 2018. 
3. Hit “Discover Movies w/ Below Settings” and then “Use as widget”
4. Backed out and let the Skin reload, updating Skin Shortcuts. As the widget reloads, I get this screenshot. As you can see this is your dialog on my home screen instead of in the application. 
![ABE19A18-2DC0-4575-9A37-16D6CD6CAD0B](https://user-images.githubusercontent.com/29167580/71869461-62130a80-30cf-11ea-8faf-3f8623fcd7bc.jpeg)

**Comment by jurialmunkey** [comment]
Ah yep, you're right. Something gone wrong between updates and it no longer works as a widget. I'm pretty sure I know the issue and will have a fix shortly.

Nice idea on the library node editor type rules. I think it should be possible to implement. I'll have a look.

**Comment by jurialmunkey** [comment]
Okay that was surprisingly easy to implement.

@Demonseeed - Can you test latest? Add Rule is now in effect and also the widget issue should be fixed. 

I'll add some additional functionality to modify/delete rules soon - but the basic functionality is now there.

**Comment by Demonseeed** [comment]
Wow, that was fast!

Yeah I’d love to test it, will do when I get home from work. 👍

**Comment by Demonseeed** [comment]
Tested it out, works great! No more weird pop ups from the widget either!

Awesome job, @jurialmunkey!

**Comment by Demonseeed** [comment]
Hello @jurialmunkey 

Still loving this feature, but I was wondering if you could add something to it. 

The ability to filter for Networks. Something like `&amp;with_network` would be useful. The reason for this would be the ability to essentially recreate those custom Trakt lists like “Netflix Movies” or “Hulu Movies” without having to rely on another party to have to update - this would update as TheMovieDb updates their database naturally. 

I checked through TheMovieDb Helper’s website for Netflix movies, and for some reason if you search for the Company Netflix, it only brings in like 5-6 hits, but if the network is Netflix it brings in everything. Same with Hulu and Disney+. 

Thanks again!

**Comment by jurialmunkey** [comment]
@Demonseeed - with_networks is not available as a query string param in the movie's discover endpoint:
https://developers.themoviedb.org/3/discover/movie-discover

It is only available for tvshows. Also, there is no Networks Search endpoint available in the API, so network IDs need to be inputted manually (the network IDs are different to company IDs).

**Comment by Demonseeed** [comment]
Ah, darn that TMDb! Thank you for that link, I’ll make sure to double-check that next time I recommend something like this. 

As for inputting the Network ID, is that something that I could do? I have no clue how. 

Would it be `&amp;with_id=True`?

**Comment by jurialmunkey** [comment]
You can only use Networks for TvShows Discover.

There is a rule to add networks in the tvshows section. Just enter the ID into the keyboard that comes up.

**Comment by Demonseeed** [comment]
Ahhh, I gotcha, thanks for that clarification!
