### ISSUE TITLE
[Request] Respect hidden movies, shows and seasons in Trakt

### ISSUE THREAD

**Issue by unkn0wn234** [jurialmunkey/plugin.video.themoviedb.helper#434]
Can it be made so in TMDBH, watched statuses will still be taken from a show when it's hidden in Trakt so when u go search for 
a show manually itll show what youve watched up till. 
But also make it so these shows movies and seasons wont not show up in currently watching tv shows/next up/in progress movies if they are marked hidden in Trakt?

EX: TV Show 1 is 2 seasons completed in progress and normally shows up in "In progress shows" and "next up" but if I hide it in trakt it will disappear from that section in TMDBH. However if i search for the show manually it will still show the watched statuses

**Comment by jurialmunkey** [comment]
I don't quite understand what you're asking.

If you hide something on Trakt it will be hidden from calendar type views only (eg calendar, in progress, next episodes, up next). It will still show up in other lists and search.

That's how hiding items is intended to work on Trakt (you only hide items from specific sections such as progress) and that's how it also works in TMDbH (at least it should)

**Comment by unkn0wn234** [comment]
> I don't quite understand what you're asking.
> 
> If you hide something on Trakt it will be hidden from calendar type views only (eg calendar, in progress, next episodes, up next). It will still show up in other lists and search.
> 
> That's how hiding items is intended to work on Trakt (you only hide items from specific sections such as progress) and that's how it also works in TMDbH (at least it should)

Yea I’m just asking for it to be hidden from progress, but in another addon it does this but also keeps the watched states so if I searched for that show it would still show which episodes are watched but just hide the show from the next up/progress section

**Comment by drinfernoo** [comment]
@unkn0wn234 He's saying it already does that.

**Comment by drinfernoo** [comment]
@unkn0wn234 He's saying it already does that.

**Comment by jurialmunkey** [comment]
Yeah exactly it should already do that. 

Watched status is entirely separate from hidden status

**Comment by unkn0wn234** [comment]
Ah okay i guess i just had a bug I reinstalled TMDBHelper and the shows I hid on Trakt are now gone from Next Up
