### ISSUE TITLE
[REQUEST] Change picture from episode cover to series cover

### ISSUE THREAD

**Issue by mrXoo** [jurialmunkey/plugin.video.themoviedb.helper#442]
I have a bunch of different shows I’m watching now and I have added my trakt “Your Next Episodes” as a widget on my homepage. 
Currently with the picture of the episode rather than the Series I have a hard time seeing exactly what’s about to play unless I play it. It it possible to change this cover art on the widget?
![BCAC8859-BC65-432B-B2EE-2F6E3E218AEA](https://user-images.githubusercontent.com/50938643/108663538-0dc31980-748e-11eb-9d73-629b022a903b.jpeg)
As you can see Seal Team is perfect. Yellowstone is not.

**Comment by jurialmunkey** [comment]
This is a skinning question. TMDbH already supplies all the artwork e.g. `ListItem.Art(tvshow.poster)` `ListItem.Art(fanart)` -- it is up to the skin to decide which artwork to display. In this instance the skin you are using is prioritising episode thumb.
