### ISSUE TITLE
TMDBH Default player Load time 25 Sec?

### ISSUE THREAD

**Issue by Nazim1981** [jurialmunkey/plugin.video.themoviedb.helper#443]
I have matrix . players manually installed , library populated with tmdbh integration , default player set to Seren , tmdbh latest matrix version , xbmc transfer checked in player setting , now when I click to play from library or from direct addon it took 25 to 30 second to load player to show on display , I am not talking about scrapping result time . how to get shorter time like instant load of tmdbh Player?

http://paste.kodi.tv/egapayazuf

**Comment by jurialmunkey** [comment]
Can you get me a clean log with Kodi's debug logging turned on (system settings). Without debugging enabled there isn't much useful info (I can see it taking time to start but no info about what is happening inbetween). 

Turn in debugging, restart then try to play just one item once everything has started up.

**Comment by Nazim1981** [comment]
> Can you get me a clean log with Kodi's debug logging turned on (system settings). Without debugging enabled there isn't much useful info (I can see it taking time to start but no info about what is happening inbetween).
> 
> Turn in debugging, restart then try to play just one item once everything has started up.

Here is  a log with debugging 

http://paste.kodi.tv/mawihalexi

**Comment by jurialmunkey** [comment]
For a start you are using the wrong resolve method for that addon -- any addon that scrapes sources should have is_resolvable set to false (i.e. set it to PlayMedia NOT setResolvedUrl). You need to reconfigure that in the player configuration dialog.

Possibly also you have a corrupted TMDbH cache. You can clear the cache by exiting Kodi and then deleting the `TMDb.db` and `TraktAPI.db` files in the database folder:
`.kodi/userdata/addon_data/plugin.video.themoviedb.helper/database/`

**Comment by Nazim1981** [comment]
> For a start you are using the wrong resolve method for that addon -- any addon that scrapes sources should have is_resolvable set to false (i.e. set it to PlayMedia NOT setResolvedUrl). You need to reconfigure that in the player configuration dialog.
> 
> Possibly also you have a corrupted TMDbH cache. You can clear the cache by exiting Kodi and then deleting the `TMDb.db` and `TraktAPI.db` files in the database folder:
> `.kodi/userdata/addon_data/plugin.video.themoviedb.helper/database/`



Did what you said , still taking 30 second to load default player ,

New log

http://paste.kodi.tv/ayagoladek

**Comment by Nazim1981** [comment]
@jurialmunkey   I have checked on other system ,Same issue there ,  it took 25 to 30 second by default to load default player .

**Comment by Nazim1981** [comment]
Its really hysteria to wait default player to load that much time . my whole tmdb created library is useless if I am using Seren widgets to load on home & Hubs whereas  I am not using my 15000 movies (.strm) library due to this waiting , it should work instant .

**Comment by jurialmunkey** [comment]
Why do you have 15000 strms in your library? You can't possibly watch that many movies and indicates that you bypassed the limits set in the plugin.

**Comment by Nazim1981** [comment]
> Why do you have 15000 strms in your library? You can't possibly watch that many movies and indicates that you bypassed the limits set in the plugin.

Owning media worked super fast and instant load , whereas online widgets  artwork (clear logos , clear art ,fanart, Ratings ) are hassle to load  , so using local media & artwork worked better then Netflix,Hulu,Prime,HBOMax,Disney+ combined.
Yes I cant watch all but the catalogue is there , I can choose whatever to play from waste catalogue , everything is there you name it . All three Debrid(PM,RD,AD) working well with library items . So think about  25 to 30 Sec wait to load players before even scrapping is really something you need to look at. i did not by passed limits , But 2500x6 Movies Lists & 500x10 TV Shows which you are forcing to do whereas Fen.Venom,Crew dont have any limit and Fen can pull Collections as well , which you said once No .

**Comment by jurialmunkey** [comment]
I dont care what piracy addons do.
