### ISSUE TITLE
[Meta] Submit to Official Repo?

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#447]
It seems there have been some inconsistencies with availability, since Matrix changes the way dependencies are served from third-party repositories...

The official repository has version 2.4.36, while this repository is currently at 4.2.19.

**Comment by jurialmunkey** [comment]
FYI - PR pending:
https://github.com/xbmc/repo-plugins/pull/3451

**Comment by SerpentDrago** [comment]
https://github.com/xbmc/repo-plugins/commit/b4bb8598ddba338d01951a17270fc0122fe15c97

Merged
