### ISSUE TITLE
Unable to activate Trakt and update player list

### ISSUE THREAD

**Issue by kodiuser-xiii** [jurialmunkey/plugin.video.themoviedb.helper#448]
Hi,

I have recently installed Kodi 19 on my windows 10 and tried to set up TMDB helper Trakt Activation and players installation. However I keep getting an error and to check the log file for details.
I am not a developer so I am unsure what I am looking at so below is the log info.
[TMDBHelper log.txt](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6046853/TMDBHelper.log.txt)
Please advise if there is a fix around this. 

Kind regards

**Comment by jurialmunkey** [comment]
Full log please

**Comment by kodiuser-xiii** [comment]
Here you go.
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6047493/kodi.log)

**Comment by jurialmunkey** [comment]
You are using a very old version (v2.4.36) from the Kodi repo. The most recent version on github is v4.2.19

Please install latest version either from [github matrix branch](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/tree/matrix) or install from my personal [repo](https://jurialmunkey.github.io/repository.jurialmunkey/).

**Comment by kodiuser-xiii** [comment]
Thanks, I installed the version that is on the default Kodi Addon Repository, was not aware this was not up to date version. 

I installed the latest version using the personal repo you provided and was able to activate the trakt account and update players. However, I am having difficulty with the library integration. I have activated autoupdate and library integration but there is no library created for TV shows and Movies. Please advise what I am doing wrong. I have attached new log and settings.xml (in txt format) copies
for your reference.
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6055490/kodi.log)
  
[settings.txt](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6055485/settings.txt)

**Comment by jurialmunkey** [comment]
You haven't added any Trakt lists to monitor so there's nothing to integrate.

**Comment by kodiuser-xiii** [comment]
Thanks, is there a link which gives step up step process for Trakt List Library Integration? and will the list get updated in the library automatically or need to be manually updated?

**Comment by jurialmunkey** [comment]
No there isn't a setup process but it is really simple. You add the list in the settings right where the library integration stuff is and then TMDbH will add those items in the list at the next update time. Every day at the time specified it will check the list and add any new items.
