### ISSUE TITLE
In progress trakt tv shows error

### ISSUE THREAD

**Issue by paallday** [jurialmunkey/plugin.video.themoviedb.helper#449]
Running latest version of tmdb helper in Matrix with signed in Trakt account. Getting errors when trying to access „your in progress tv shows” and “your next episodes“.

Here’s a log:
https://paste.kodi.tv/ulemidoyeg

Thanks

**Comment by jurialmunkey** [comment]
Can you try latest matrix github version and see if that fixes the issue?

**Comment by paallday** [comment]
> Can you try latest matrix github version and see if that fixes the issue?

Thanks so much for the quick fix! Latest update worked perfectly!
