### ISSUE TITLE
[Request] Add to Library button

### ISSUE THREAD

**Issue by doccy-doc** [jurialmunkey/plugin.video.themoviedb.helper#458]
I was hoping you could implement the option to include an "Add to/Remove from Library" button in the Information section? I believe this was implemented in OpenInfo and was extremely useful for me.
![git-req](https://user-images.githubusercontent.com/4121848/111022597-b7f7e680-8427-11eb-855a-1c1142266431.png)

**Comment by jurialmunkey** [comment]
This is a skin question. Please put skin requests on Arctic Horizon github:
https://github.com/jurialmunkey/skin.arctic.horizon

**Comment by jurialmunkey** [comment]
Also, why don't you just use the "Add to Library" context menu option on the item itself (in default keymap long press Select opens context menu).

![Honeyview_screenshot00002](https://user-images.githubusercontent.com/4618719/111023832-53d92080-842f-11eb-8274-e5298b4972c5.jpg)

**Comment by doccy-doc** [comment]
I know about that option, and it works fine. I just find it much more intuitive to also have a button there, particularly for the less Kodi-savvy family members. 

I have reposted the request to the skin's github. Thanks.
