### ISSUE TITLE
Player option in Global context, list for Start watching TV shows and Personal lists.

### ISSUE THREAD

**Issue by kodiuser-xiii** [jurialmunkey/plugin.video.themoviedb.helper#459]
Hi,

I am just getting my head around the TMDB Helper addon and was wondering whether the following is possible:
1) _Ability to select player options available at the global context level_: This way I can use the multiple player feature option across any addons. This was a feature I enjoyed in Openmeta.
2) _Start Watching TV Shows:_ This is something opposite to 'In Progress Shows' where the shows are added to the list/collection but not started watching.
3) If 2) is not available then can I create one on my own by using the rule options under the Discover TV shows. 

Many thanks.

**Comment by jurialmunkey** [comment]
1. Install the context menu addon for TMDBh - its available in my repo. That'll give a tmdb helper options submenu in context which should allow for playing from anywhere.
2. That's what the Trakt watchlist is for. Add item you want to start watching and once you've watched an episode Trakt will automatically remove it from your watch list (and it should now instead show in in progress instead). 
3. Unfortunately discover doesn't have any way to interact with your personal Trakt account - it only works on info available in their public api.

**Comment by kodiuser-xiii** [comment]
Thanks. I have installed TMDBh context addon and it is what I was after. 
What happens in the case when the watchlist is synced to the library. Will the synced TV Show drop out of the library too after watching the first episode since its dropped out of the Trakt Watchlist?
I am trying to figure a way for it to continue sync any unwatched/new future episodes to the library. 

Also can the number of items displayed in a page be altered?

**Comment by jurialmunkey** [comment]
No. Once you add something to the library it stays there. TMDBh never deletes anything from your library, it only adds things. Also once the show is added it will update with new episodes if you have auto updates enabled.

One thing to note is that if you watch the show _before_ it gets added to the library then it will never get added because it will be taken out of the watchlist and so won't be listed when the update happens. But that's a pretty corner scenario and you can always manually add a missed show from in progress on the rare occurrence that that happens.

**Comment by kodiuser-xiii** [comment]
Thanks and is there a way to adjust the number of items displayed on a page? I am trying to increase the number of episodes displayed under 'Your Next Episode' list, is this possible?

**Comment by jurialmunkey** [comment]
No. Limits are there for a reason to prevent excessive API calls.

Covered multiple times before:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/213
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/34#issuecomment-568247204
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/65
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/91
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/56

**Comment by kodiuser-xiii** [comment]
Thanks, then is there a way to restrict which episodes get added to the library?

I have added an entire TV show to the library and it has included episodes which are yet to be aired or aired date is not provided.

I noticed in the settings>navigation there is an option exclude unaired episodes, but I don't think this will apply to the library also?

**Comment by jurialmunkey** [comment]
> I noticed in the settings>navigation there is an option exclude unaired episodes, but I don't think this will apply to the library also?

Yes it applies to library updates too. You will also probably want to hide items without airdates.

**Comment by kodiuser-xiii** [comment]
Hi, thanks for clarifying this and for all the help so far.

**Comment by kodiuser-xiii** [comment]
Hi @jurialmunkey , 

Instead of raising a new issue thought I ask the question here regarding the options available under TMDB context addon.
Is 'add to library' function not included in the context addon?

I was trying to add a series from via another addon but could not find 'add to library' option under the TMDBHelper options n the context menu.
Please advise.
