### ISSUE TITLE
[Bug] Add to Trakt Watchlist

### ISSUE THREAD

**Issue by webmaher** [jurialmunkey/plugin.video.themoviedb.helper#46]
When i want add serie to Trakt watchlist I got this error:

Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument of type 'NoneType' is not iterable
                                            Traceback (most recent call last):
                                              File "C:\Users\Jan\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\context-watchlist.py", line 8, in <module>
                                                context.action('watchlist')
                                              File "C:\Users\Jan\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\context.py", line 27, in action
                                                boolean = 'remove' if int(tmdb_id) in trakt_ids else 'add'
                                            TypeError: argument of type 'NoneType' is not iterable

**Comment by jurialmunkey** [comment]
Works fine for me. 

Please post full log using https://paste.kodi.tv/ or https://pastebin.com/

I need more details:
What Kodi version?
What TV show are you attempting to add?
Where are you adding the show from? Widget? Info Dialog? Add-on?
What exact steps do you take to add the show?
Have you authorized Trakt?

**Comment by webmaher** [comment]
i start MDB helper go to TV Shows-Popular
 and try to add The Mandalorian to Trakt watchlist...
 https://pastebin.com/vRgwgeYx
 
 
Kodi 18.5 (on w10) with your skin Arctic Zephyr 2 and today version MDB helper 
And of course before i made log file I also authorize Trakt...


More important for me is possible to create function "ADD to LIBRARY?
If answer is yes then you can also create function which player is play movies and series from Library
and then this MDB Helper is almost perfect ...

Now I use OpenMeta to browsing movies and series. When i found what i want i just add to library and then default Open players
start to play... my default player is plexkodiconnect... if they dont found  choosen movie or serie then from context menu start another one....

**Comment by jurialmunkey** [comment]
Trakt isn't authorised in TMDbHelper or you have something deleting the token / preventing it being set.
```
2020-01-14 11:31:28.708 T:10468   DEBUG: CSettingsManager: requested setting (trakt_token) was not found.
```

**Comment by webmaher** [comment]
I remove complete Kodi and install again and only your skin and TMDB helper... and same story no matter which movies or series i want to add... I also check settings.xml file and see Trakt token there... I really no idea why this not work.. Do I need VIP Trakt acc?

**Comment by jurialmunkey** [comment]
No, you don't need a VIP trakt account. A normal account is fine.

Can you try with latest version? It might be an issue with having an empty trakt watchlist. You shouldn't get the error anymore, so you will need to check if the item has actually been added to your watchlist to make sure it is working.

However, I'm pretty sure trakt is not being authorised because Kodi can't read the trakt_token from the settings file for some reason. If it still isn't working, try deleting `userdata/addon_data/plugin.video.themoviedb.helper` folder and then reauthorise trakt.

**Comment by webmaher** [comment]
Thanks, thanks, thanks...fantastic.... you are pure genius... Can you now also add function "ADD to Library"... then you made the best Kodi addon ever :-)
