### ISSUE TITLE
Change in tmdb helper I think broke it saving  history when using Skins search feature 

### ISSUE THREAD

**Issue by SerpentDrago** [jurialmunkey/plugin.video.themoviedb.helper#464]
First let me say Thank you for all your hard work with tmdbhelper . 

This issue was found when working on  [Auramod](https://github.com/SerpentDrago/skin.auramod)  , i've been trying to patch it up to get working in matrix  (see matrix branch) . and slowly getting there . (its mostly good besides some bugs ) Really wish sky was still around :( 

I will try to explain the issue i found as best i can . but first let me explain in what context i'm using it , just in case my logic was wrong . 

I'm trying to get its search history working again . The way it worked was kinda hacky but was great in function. The user would click a shortcut/menu for search and it would pop up the on screen keyboard , and if they didn't type anything yet then at the bottom of that keyboard  would list previous searches they had done . Once they started typing it would then switch to showing autocomplete results .   This worked by having TMDB helper movies and shows added to the search lists . And the skin would simply put the tmdb helper search history at the bottom of the on screen keyboard . 

That way everytime a user would search anything no matter what search lists were configured  (as long as tmdb movies an shows were one of them ) a search would be made in tmdb helper and thus it would have a history to pull from . 

Example screenshot of how it looks (note i've been testing things so its ugly lol ) 
![image](https://user-images.githubusercontent.com/21133858/112179858-6b539e80-8bd1-11eb-8ad5-30e773a70bea.png)

The issue seems to be that the search list path , that both Auramod AND your own skin Arctic Horizon uses , Causes TMDB helper to not save the search to its own history , Even though the search path is valid and lists results .  If i search WITHIN TMDB helper , Tmdb helper shows a record of the search , but if i use the search list one (such as using auramods  search feature )  it doesn't . It used to work , but i do not know at what time it stoped working . 

This is the plugin path auramod uses for its built in tmdb helper movie search lists which doesn't save history  > 

https://github.com/SerpentDrago/skin.auramod/blob/9528f8e0acbf81eea3c5345bf1de2e4a355bed33/shortcuts/template.xml#L180

And i've even tried using Arctic Horizons 

https://github.com/jurialmunkey/skin.arctic.horizon/blob/ee18b8280673affafaa5fbf2cf92e1ac2fda5b4f/shortcuts/template.xml#L1389

With no luck

To replicate , simply use one of your skins Search Paths , and notice you get results but if you go into tmdb helper there is no history for that search . If you search using tmdb helpers menus items to search (tmdb helper > movies > search , or tmdb helper > search > movies ) it will then show a history of that search 

Thank you for your time .

**Comment by SerpentDrago** [comment]
Note , I have not actually tested directly using arctic horizon , just tried using AH's  exact default tmdb helper movie search list , inside auramod's search , and then searching directly with tmdb helper though its menus, I very well could have missed some logic , and its simply a Auramod bug , if so I apologize for your time

**Comment by jurialmunkey** [comment]
Ah, yep - looks like with the v4 rewrite I forgot to include the `history=true` param in the search logic. Should be fixed now.

**Comment by SerpentDrago** [comment]
Ill test it out tomorrow. Thanks man!

**Comment by SerpentDrago** [comment]
Confirmed its working now ! @jurialmunkey Thank you so much . 

Just FYI , i know your a super super busy guy . But if you ever get bored , i have mounting bugs in auramod i'm slowly going though (references your fixs to AH and others fix's to matrix versions of aura )   If you see any quick fix's or just simply POINT me in the right direction . 

Currently biggest issue right is prob the fact widgets are not respecting the Widget type (poster / landscape / etc) and they are defaulting to landscape. Only happens on Search hub and other hubs / mylists  . Who knows but i'm getting it done  . 

Its all good , I know you have your own work . just figured i'd drop that in  . 

At the very least , do you have any issues with me hitting you up if i hit a roadblock , I'll off course try to do my best . Just learning atm .  I dont' even currently use kodi that much . but i didn't want to see all the hard work sky had put into auramod be lost in time . Trying to get it up to spec first . 


Again thanks for the TMDB helper fix !!! i have history again !

**Comment by SerpentDrago** [comment]
Final note , you may want to add history=true to your [search lists in AH](https://github.com/jurialmunkey/skin.arctic.horizon/blob/ee18b8280673affafaa5fbf2cf92e1ac2fda5b4f/shortcuts/template.xml#L1389) , i'd make the pr , but i dont' know if you wanted to make this optional or not .
