### ISSUE TITLE
Next up trakt

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/plugin.video.themoviedb.helper#466]
Is there a possibility to show episode count on the "your next episodes'widget if I connect trakt through tmd helper? Thanks

**Comment by jurialmunkey** [comment]
What do you mean by "episode count"? The Your Next Episodes list displays individual episodes not tvshows.

**Comment by derrgoo** [comment]
This is first time writing in but really have enjoyed your skins over the years. When using Horizon, I pull widgets for tv shows and the small number on the fanart shows how many episodes. 

I was wondering if you can add for your next up or in process tv shows pulling a widget the same way to show how many episodes that are left to watch. I hope this makes sense?

Thank you!

**Comment by jurialmunkey** [comment]
It already does for In-Progress. Enable "Get watched indicators from Trakt" in TMDbH settings.

![Honeyview_screenshot00027](https://user-images.githubusercontent.com/4618719/112268666-6e32ba00-8ccb-11eb-9f9d-b1d18aed6ee8.jpg)

And like I said, Next Episodes displays individual episodes NOT tvshows. Individual episodes cannot have unwatched counts - only tvshows can.

**Comment by derrgoo** [comment]
Thank you. Sorry, I mixed it up when I first asked you but yes episodes. Working perfectly.

**Comment by derrgoo** [comment]
Can you point me to where I can ask a question on horizon matrix? I get no error but when I open it always crashes. Takes 2-3 turns to get it to stay open. It seems to crash loading widget. Thank you!
