### ISSUE TITLE
Language change not working

### ISSUE THREAD

**Issue by Thomiehawk** [jurialmunkey/plugin.video.themoviedb.helper#468]
I tried changing the language to english instead of dutch because a lot of anime don't have synopsises or titles display incorrectly.

When making a widget for recently watched tv-shows and in-progress movies from trakt however it is still shown in dutch.

On my second device with kodi I set it to english initially and everything is displayed in english.

Is there some sort of cache I can clear?

Thanks for reading this

**Comment by jurialmunkey** [comment]
Yes cache is stored in `kodi/userdata/addon_data/plugin.video.themoviedb.helper/database`

Deleting the TMDb one should be enough (close kodi whilst doing so). You shouldn't need to delete any of the others. 

Also you can refresh individual items via the context menu by choosing refresh details
