### ISSUE TITLE
TMdB player.py throws error on Matrix version but not Kodi 18

### ISSUE THREAD

**Issue by Ebonlore** [jurialmunkey/plugin.video.themoviedb.helper#469]
Exact same code/config works on Kodi 18 TMdB 4.3.1 and not on Kodi 19.  See Kodi.zip for log of error

[kodi.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6215441/kodi.zip)

[direct.shadow.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6215437/direct.shadow.zip)

[plugin.video.shadow.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6215443/plugin.video.shadow.zip)

**Comment by jurialmunkey** [comment]
Your player file is misconfigured. It references a key - `{rating}` - that does not exist.

Valid keys are listed in the wik, of which `{rating}` is not one:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#available-keys

You need to remove invalid keys from your player file. There's other ones in there too like `{genres_+}` which are not provided. This is a python 3 change where string formatting is now stricter and it will no longer let you get away with having invalid undefined keys.
