### ISSUE TITLE
[Request] Browse Trakt Collection

### ISSUE THREAD

**Issue by umonkey13** [jurialmunkey/plugin.video.themoviedb.helper#47]
I can't seem to find a menu entry for Movie and TV Show collections from trakt is it possible to add these? 

Thanks

**Comment by jurialmunkey** [comment]
It shouldn't be too difficult. I'll have a look and see.

**Comment by jurialmunkey** [comment]
@umonkey13 - Please test latest version (v2.2.24). I've added the option to browse trakt collections. Either enter through `Movies/TvShows > Collection` or `Trakt > Movies/TvShows Collection`

**Comment by jurialmunkey** [comment]
Marking this issue as resolved as I'm pretty sure it is working correctly.
