### ISSUE TITLE
[Request] Auto-pick player

### ISSUE THREAD

**Issue by keving119** [jurialmunkey/plugin.video.themoviedb.helper#470]
Hi,

If I understand correctly, this addon already uses the `get watch providers` function from TMDB.
I was wondering if it might be possible to link your own configured players to these watch providers, such that, whenever I want to play an item that is, for example, available only on Netflix, it does not show the pop-up of `Choose Action` (where I can select a player) anymore.
Ideally, I would also want to filter on it. So to see only popular movies from providers which I have linked to existing players. 
Is this possible?
Thanks in advance!

**Comment by jurialmunkey** [comment]
I've actually been planning to do this for a while now - I just haven't got to it yet because it is part of a series of changes that I want to make to player handling. See here for discussion: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/401#issuecomment-751311739

**Comment by jurialmunkey** [comment]
Closing this to keep discussion in the one thread.
