### ISSUE TITLE
Tmdbplayers not working after update...

### ISSUE THREAD

**Issue by Converted007** [jurialmunkey/plugin.video.themoviedb.helper#473]
The [log](https://paste.kodi.tv/olocurimez)

I got this on all my systems (kodi 18.9 and 19) after i updated the playerslist i got an error and now i cant configure them nor use tmdb helper.

Can you solve the issue?

Thanks

**Comment by jurialmunkey** [comment]
You've got a lot of disk errors. Sounds like a corrupted addon_data folder.

Close kodi and delete:
`.kodi/userdata/addon_data/plugin.video.themoviedb.helper`

Then restart Kodi. You will need to setup TMDbH again as this will delete all its settings, cache and players.

**Comment by JC253** [comment]
I've also got this same problem after updating TMDbH players. Unable to open the addon as well. Tried manually updating the addon with no luck either. Error continues. I'll try clearing user data tonight after work and report back.

**Comment by Converted007** [comment]
> You've got a lot of disk errors. Sounds like a corrupted addon_data folder.
> 
> Close kodi and delete:
> `.kodi/userdata/addon_data/plugin.video.themoviedb.helper`
> 
> Then restart Kodi. You will need to setup TMDbH again as this will delete all its settings, cache and players.

Yep worked! Thanks:-)
Weird thing is I had it on all my machines...
