### ISSUE TITLE
[Bug] Episodes won't play when using seren as a player

### ISSUE THREAD

**Issue by rizreflects** [jurialmunkey/plugin.video.themoviedb.helper#475]
Quite often, when i select a TV show using TMDB helper, seren comes back with an error message. This usually happens with true crime documentaries and nature shows. I know the episodes are present using seren as I can manually search and get it to play (using seren directly). But when using a TMDBhelper widget, seren crashes when i click play. 

It is worth noting that this error occurs on my windows PC, running Kodi 19.. As well as my Beelink GT King Pro, which runs kodi 18 on coreelec. I have no idea why this problem occurs so I was hoping you could help.

Log File: https://paste.kodi.tv/uquronisoy

**Comment by jurialmunkey** [comment]
TMDbHelper is working properly. Issue is with your player file and/or the addon that you are calling. 

I don't maintain third party players.
