### ISSUE TITLE
[Feature Request] Trakt Infolines calls for skins?

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#476]
Hey just wondering if this is possible? See Kodi thread...https://forum.kodi.tv/showthread.php?tid=342130&pid=3028167#pid3028167

**Comment by drinfernoo** [comment]
What type of stats are you looking for? If it's something that the TMDb API doesn't already return on its own, I'd imagine this would require extra cakes to Trakt, which would have a negative impact on speed.

**Comment by jurialmunkey** [comment]
Yeah it really depends on what kinda stats you're looking for.

If youre looking for something like number of movies/episodes watched in total on your trakt account then I could probably retrieve those with a single call on startup and that wouldn't be too bad performance wise (and could then update those stats every hour or so).

I need to know what stats you're trying to get to know if it is going to be feasible though.
