### ISSUE TITLE
[BUG] Missing Movies from Trakt Liked List

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/plugin.video.themoviedb.helper#478]
Hi @jurialmunkey,
I'm using Kodi v18.9 with the latest versions of Arctic Horizon Skin and TMDB Helper addons, in my Nvidia Shield TV Pro.

I liked the following list in Trakt:
https://trakt.tv/users/justin/lists/imdb-top-rated-movies?sort=rank,asc

When I'm going inside this list through the Liked Lists option in Trakt Menu of the TMDB Helper addon, many movies are missing from this list, e.g. the movies - The Godfather, 12 Angry Men, Schindler's List, which should be at the numbers 2, 5 and 6, respectively as per the list are missing. See below screenshot for reference:

![IMG20210407173219](https://user-images.githubusercontent.com/65297828/113864476-8f65d100-97c8-11eb-8c90-4f868415d113.jpg)

When I'm looking into the same list through the Fen addon, all movies are appearing perfectly.

Could you please look into the issue and kindly try to resolve it? Thanks in advance!

**Comment by drinfernoo** [comment]
Have you watched them? Do you have "Hide Watched" on?

**Comment by jurialmunkey** [comment]
Working perfectly fine for me using that list:

![Honeyview_screenshot00037](https://user-images.githubusercontent.com/4618719/113869544-301db600-97f4-11eb-89aa-afac64733639.jpg)

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,
Thank you! I found the issue. I had hidden unaired movies and TV shows in my TMDB Helper addon. I had to unhide those options. Now all movies are appearing fine. I don't know why this happened as all the movies in the above mentioned list are old ones and hence already aired. Could you please suggest why this happened?

**Comment by jurialmunkey** [comment]
Hard to say without a debug log. I have those options enabled and still works fine for me. 

Possibly corrupted details cache or might be some type of connection error.

**Comment by AakashC2020** [comment]
> Hard to say without a debug log. I have those options enabled and still works fine for me.
> 
> Possibly corrupted details cache or might be some type of connection error.

Hi @jurialmunkey,
Yes, you're correct. I checked in another Kodi device (Windows PC) and the movie list is working perfectly even with those options enabled. On further investigation I found that the details of the movies which are getting hidden are not showing up in TMDB Helper on my Nvidia Shield TV Pro Kodi setup. So I guess that the issue might be due to a corrupted details cache, as you suggested. Could you please let me know how I can fix this issue, i.e. how can I fix my details cache, if that's the issue?

Here is my Kodi log:

https://paste.kodi.tv/ruguyimeji.kodi

Thanks in advance!

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,
Thanks for pointing me towards the corrupt details cache! I've now resolved the issue by deleting the TMDB.db file which was located under kodi>>userdata>>tmdb Helper addon>>database folder. After deleting it the TMDB.db file was recreated once I restarted Kodi and all the movie and TV show details got refreshed. Now everything works fine again. Thanks a lot for helping me! Keep up the good work! You may close the ticket.
