### ISSUE TITLE
Certain widgets fail to send info to tmdbhelper/players

### ISSUE THREAD

**Issue by Logs22** [jurialmunkey/plugin.video.themoviedb.helper#480]
Hello, I'm not exactly sure how to describe this problem, but I will try my best. When using certain widgets through Skin helper Service Widgets (the Similar Movies and Unwatched Movies widgets are the ones im having the issues with) I get this error 

2021-04-09 21:48:17.778 T:10147   ERROR <general>: Open - error probing input format, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/movies/Deadpool (2016)/Deadpool (2016).strm

https://paste.kodi.tv/loziqirubo

There is a full log, Using Titan Bingie Mod on Kodi 19. If you need more info please let me know.

**Comment by jurialmunkey** [comment]
Unless you are having issues, you can ignore that error. All it means is that SkinHelper/Kodi tried to probe the strm file for codec info as if it was a video, but obviously a strm file is not a video and thus does not have codec info.

**Comment by jurialmunkey** [comment]
Also if you are having issues, then that's a problem with SkinHelper not supporting .strm files in the library properly. Nothing to do with TMDbH other than the fact that it was the source which created the strm file.

**Comment by Logs22** [comment]
gotcha, thanks for the response! It's weird, though i've narrowed it down to being potentially a skin problem as opposed to a tmdbh/skin helper problem. The problem only happens on bingie, but the same widget works and plays fine on Arctic horizon. Might be because of the Bingie helper info addon. anyways im rambling to myself, thanks for the response!
