### ISSUE TITLE
[Feature Request]  put "Add to Library" button on context menu when click on any media poser, thumbnail etc..

### ISSUE THREAD

**Issue by Mahava** [jurialmunkey/plugin.video.themoviedb.helper#482]
There is the "TMDB helper options" button on the context menu, maybe it could go in there.

**Comment by SerpentDrago** [comment]
your going to need to better explain your request . There is already "add to library" on any context menu on a tmdb helper item . 

It even works inside other skins info pages , such as auramod's cast & more > similar  , as it uses tmdb helper items to populate its sections

**Comment by Mahava** [comment]
Yes, it's fairly easy to 'add to library' on a TMDBH item from within TMDBH.

I want to add ANY item to TMDBH library from any other addon from anywhere in Kodi.

I want to right-click on any artwork to bring up the context menu, click on 'TMDBH options' and click 'add to library' to add it to the library, but that option isn't there.  There's a small handful of other options, but not 'add to library'.

Kinda' like 'OpenInfo'.  I select that on the context menu and it takes me to the extended info window where I can add to library, or it gives an error notification saying it can't be found at Movie Database.

Hope that is clear.

Cheers.

**Comment by jurialmunkey** [comment]
Added in most recent version of context menu addon: https://github.com/jurialmunkey/context.themoviedb.helper
TMDbHelper Options > Add to Kodi library

Needs v4.7.7 of TMDbHelper and v1.1.0 of TMDbH context menu add-on
