### ISSUE TITLE
[QUESTION] Go to the relevant streaming website in an internal (preference!) or external web browser

### ISSUE THREAD

**Issue by BobbyBabes** [jurialmunkey/plugin.video.themoviedb.helper#485]
Kodi 18.9 Leia on Arch Linux " | Windows 8.1 | Mac Big Sur.

Is it possible to click on a TV episode and be taken directly to the specific TV show's related streaming website ?
The website Just Watch seems to do that.

For example when I click on episode 4, of season 3, of Dark (2017) I want to be taken to the the TV show's homepage on the Netflix website. In an internal (preference!) or external web browser. Doesn't have  to be the exact season and episode, but the exact TV show's homepage.
Or clicking episode 2, of season 3, of Sneaky Pete (2015) I want to be taken to the the TV show's homepage on the Amazon website. Ditto. Ditto.

I do not want to use an external service (like Just Watch) as my starting point. I want to use Kodi and add TV shows to a list on Trakt (or where ever) then these will be shown in Kodi by TheMovieDb Helper, and then clicked to go to the relevant streaming website in an internal or external web browser.

P.S. You could even make these affiliate links. I don't care.

**Comment by jurialmunkey** [comment]
I'm not sure if it is possible to open a web browser directly from Kodi. Do you know of any other video addons that directly open a link in an external web browser?

Getting the link itself isn't that difficult because TheMovieDb API already provides JustWatch data (and TMDbHelper already retrieves this data -- you can see that in the info dialog for my Arctic Horizon skin which will show logos for streaming services where the item is available). It's just the actual function of opening a web browser that I'm not sure about.

**Comment by drinfernoo** [comment]
I don't believe you can on most platforms. On Android, you can use the `StartAndroidActivity` built-in to open the user's browser, but there'd be some digging to do to figure out the right call.

**Comment by BobbyBabes** [comment]
I'm sorry and do apologise. I forgot to add my source for this request. I assumed that this had been implemented already in to Kodi. Because of the following response by a Team Kodi member in 2015 (about an other Team Kodi member's efforts) on the Official Kodi forum. He states that is is already possible :  [Need advice on Embedded Chrome add-on](https://forum.kodi.tv/showthread.php?tid=231545&pid=2047504#pid2047504)
Please follow the link in that post, as it links further to a GitHub repo with recent updates by the Kodi dev.
First this site : [http://esmasol.de/open-source/kodi-add-on-s/chromium-web-browser/](http://esmasol.de/open-source/kodi-add-on-s/chromium-web-browser/)
And from there to this Embedded Chromium Kodi Add-on repo with recent updates : [https://github.com/AlwinEsch/web.browser.chromium](https://github.com/AlwinEsch/web.browser.chromium)

**Comment by jurialmunkey** [comment]
That addon is not currently stable.

Regardless, the issue isn't whether a browser exists or not in Kodi. The issue is that I need a method to send the link to the browser and as far as I'm aware there isn't a way to call the browser and pass it a link. That's why I need an example of another addon which passes a link to a browser, so I can copy the method.

**Comment by BobbyBabes** [comment]
>The issue is that I need a method to send the link to the browser .....

I know of:
[URL Launcher](https://github.com/marcalv/script.url.launcher) on GitHub.
Then there is :
[Browser Launcher](https://www.tvaddons.co/kodi-addons/show/plugin.program.browser.launcher/) and [Chrome Launcher](https://www.tvaddons.co/kodi-addons/show/plugin.program.chrome.launcher/) addons. But they are both on the TVAddons site apparently. So I'm not touching them.
[Brave Browser Launcher](https://github.com/marcelmah/bravelauncherkodi) here on GitHub.
[Google Chrome Launcher for Kodi](https://github.com/marcelmah/googlechromelauncherkodi) also on GitHub and here [Chrome Launcher Add-on: How to Browse The Web From Kodi](https://www.addictivetips.com/media-streaming/kodi/browse-web-kodi-chrome-launcher/).
[Chrome Launcher (another)](https://github.com/rwperkinsjr/plugin.program.chrome.launcher) also on GitHub.
[Chrome Launcher (another, quite old though)](https://github.com/rasjani/plugin.program.chrome.launcher) also on Github.
[Chrome Launcher (another, really old though)](https://github.com/AddonScriptorDE/plugin.program.chrome.launcher) also on Github.

**_EDIT:_** I prefer Firefox though.

**Comment by BobbyBabes** [comment]
It’s gone awfully quiet. Have I said something wrong?

Anyway, I just realised that Browser Launcher is also here on GitHub and is from the developer of [Amazon Instant Video Addon for Kodi Media Center ](https://github.com/Sandmann79/xbmc). This addon uses Browser Lancher to launch the Prime Video website in fullscreen/kiosk mode apparently.

**Comment by jurialmunkey** [comment]
I have been extremely busy at work doing 50hr+ weeks for the past two months, so I've barely had anytime for kodi dev stuff. When work calms down in a couple of weeks, I'll get back to dev stuff

**Comment by BobbyBabes** [comment]
Oh man. I should have realised. Apologies! I was blaming myself and rereading the last comment. Your bread and butter always goes first.
