### ISSUE TITLE
Ratings not showing

### ISSUE THREAD

**Issue by Thomiehawk** [jurialmunkey/plugin.video.themoviedb.helper#486]
I have set both my omdb api key and my fanart.tv api key, yet in the widgets there are no ratings shown. I deleted simplecache.db  and now it's not making a new one either

**Comment by drinfernoo** [comment]
TMDbHelper does not use simplecache.

**Comment by Thomiehawk** [comment]
How do I get the ratings to show up then?

**Comment by drinfernoo** [comment]
@Thomiehawk It likely depends on the skin you're using, as each skin usually has different settings that pertain to ratings.

**Comment by Thomiehawk** [comment]
Using titan bingie mod 2.0 and the meta data and utils addon for it has the omdb api key filled in

**Comment by drinfernoo** [comment]
Then there is an issue with either script.module.metadatautils or Titan Bingie Mod, neither of which are related to or interact with this add-on.

**Comment by Thomiehawk** [comment]
Yet Seren does show proper ratings and tmdb helper does not...
