### ISSUE TITLE
Valid Error: XBMCVFS reports unable to create path (on FTP server)

### ISSUE THREAD

**Issue by jmh2002** [jurialmunkey/plugin.video.themoviedb.helper#488]
I'm trying to write library stream files to an FTP server on a networked android device but I get this error in TMDBH:

XBMCVFS reports unable to create path

(it's a valid error, the folders and stream files are not created)

and this error in the Kodi log:

2021-04-27 22:24:33.673 T:13100  NOTICE: [plugin.video.themoviedb.helper]
                                            UPDATING TV SHOWS LIBRARY

2021-04-27 22:24:42.261 T:13100   ERROR: CCurlFile::Exists - Failed: Access denied to remote resource(9) for ftp://USERNAME:PASSWORD@192.168.1.102:2121/TVShowsTMDBH/TV Show Name (2019)/

2021-04-27 22:24:42.262 T:13100   ERROR: CUtil::CreateDirectoryExW called with an unsupported path: ftp://FTPKODI:mypassword@192.168.1.102:2121/TVShowsTMDBH/TV Show Name (2019)/

2021-04-27 22:24:42.535 T:13100   ERROR: CCurlFile::Exists - Failed: Access denied to remote resource(9) for ftp://USERNAME:PASSWORD@192.168.1.102:2121/TVShowsTMDBH/TV Show Name (2019)/Season 1/

The error only seems to be with regard to creating the TV Show folder.

If I create the TV Show folder manually TMDBH is then able to write the stream files to this folder.

Is this a bug, or do I not have something configured correctly?

THANKS :)

**Comment by jurialmunkey** [comment]
It's an issue with Kodi's xbmcvfs module which provides access to the filesystem. 

Do you have movies setup with a similar ftp path? Can you test adding a movie and see if you get the same error?

Basically, I'm wondering if it is specifically multi-folder creation that's that issue (i.e. tvshows also need to create a subfolder for seasons, whereas movies are a single folder). If it works for movies then it should mean I'll be able to use a different method to create the folders incrementally instead - but if it doesn't work for movies then there might not be a solution for ftp.

**Comment by jurialmunkey** [comment]
No response from user. Closing.

**Comment by jmh2002** [comment]
Sorry for the delay with my reply, real life got in the way.

I tested adding a movie and I see the same error, so no it doesn't seem to be a specific multi-folder related issue unfortunately.

Given that Kodi supports FTP, it would make sense for Kodi to be able to write to FTP too. That seems odd.

I'm thinking of a few work arounds though:

- the 'ftp server' is actually an android device, so it could run Kodi too
- so I can write the stream files locally to avoid the XBMCVFS error with TMDBH
- but I still need to provide network access to those stream files for my other devices

- maybe I can use path substitution on the other devices, so that the library path is technically the same but that these other devices look for the files on the FTP server instead? 
ie: 
from: special://profile/addon_data/plugin.video.themoviedb.helper/tvshows
to: ftp://Username:password@IPADDRESS:PORT/userdata/addon_data/plugin.video.themoviedb.helper/tvshows/

I don't know if that works, I'll need to test it I suppose.

Worst case is that I also own a Tasker type android app (MacroDroid) which I believe is capable of automatically moving the files to the FTP server location after creating them within Kodi, but that might be an unnecessarily complicated way to solve this problem.

**Comment by jmh2002** [comment]
> 
> I'm thinking of a few work arounds though:
> ...
> I don't know if that works, I'll need to test it I suppose.
> 

I can confirm that the above solution using Kodi's Path Substitution functionality does work for FTP.

So this doesn't fix the problem with Kodi's xbmcvfs module, but it is a work around.

- NB: the path doesn't seem to be being subsituted on my LibreElec device, but I guess that's an LE issue and I'll look into it later. It functions on my Windows device so the theory works (UPDATE: a couple of restarts seems to have fixed this now).

Here are some notes for other users who may have a similar problem:

- https://kodi.wiki/view/Path_substitution
- The FTP Server is set to share the Kodi folder (or just the TMDBH userdata folder if that's all you need)
- Leave TMDBH > Settings > Library > TV (or Movie) path set to the default on all devices: 
special://profile/addon_data/plugin.video.themoviedb.helper/tvshows 
- Run Kodi & TMDBH helper on the FTP server device and write the Library stream files to the local path above

Here is the path substitution I used in advancedsettings.xml:

```
<pathsubstitution>
<substitute>
<from>special://profile/addon_data/plugin.video.themoviedb.helper/tvshows/</from>
<to>ftp://User:Password@IPAddress:Port/userdata/addon_data/plugin.video.themoviedb.helper/tvshows/</to>
</substitute>
</pathsubstitution>
```
