### ISSUE TITLE
[BUG] Crash on play

### ISSUE THREAD

**Issue by rehannali** [jurialmunkey/plugin.video.themoviedb.helper#489]
Hi, this plugin is crashing as soon as i press play button. I already configured players but still having issue with it.

if anything i'm doing wrong, kindly tell me how to play via available sources?

**Comment by jurialmunkey** [comment]
Debug log?

**Comment by rehannali** [comment]
@jurialmunkey How to get debug logs from kodi?

**Comment by BobbyBabes** [comment]
How-To for v18 : [https://kodi.wiki/view/Log_file](https://kodi.wiki/view/Log_file)

**Comment by SerpentDrago** [comment]
> @jurialmunkey How to get debug logs from kodi?

there is a kodi log file uploader addon in the official kodi  repo

**Comment by jurialmunkey** [comment]
No response from user. Closing.
