### ISSUE TITLE
Can tmdb helper serivce be used for looking up Clearlogos

### ISSUE THREAD

**Issue by SerpentDrago** [jurialmunkey/plugin.video.themoviedb.helper#491]
Before in auramod  (kodi 18) We used Skin helper service to lookup Ratings from OMDB and Clear logos from Fanart .  or  (Skin setting ) TMDB helper Service  to lookup Ratings from OMDB . If the addon didn't provide that info itself . 

In auramod (kodi 19 ) i've been able to completely Drop lookups to Skin helper service  and instead ONLY use and only offer ability to use TMDB helper service , its much faster and modern and you have done amazing work replicating lots of the things skin helper service used to provide . 

The ultimate goal is to completely drop skin helper service lookups from the skin . Yet still provide ability to Pull in ratings and clearlogos when that info is not already provided by the addon. 

But unless i'm missing something , at this time TMDB helper service can not be used to provide / lookup Clear logos from Fanart . Could this function be implemented ? or did i miss something . I do not see info to be able to do this in the wiki  OR i missed it . 

Thanks for all you do !

**Comment by jurialmunkey** [comment]
TMDbH service monitor already does artwork lookups. The user needs to enable Fanart TV in TMDbH settings first though, otherwise it will only grab artwork from TMDb.

I think I forgot to add these to the wiki, but the following work

```
Window(Home).Property(TMDbHelper.ListItem.icon)
Window(Home).Property(TMDbHelper.ListItem.poster)
Window(Home).Property(TMDbHelper.ListItem.thumb)
Window(Home).Property(TMDbHelper.ListItem.fanart)
Window(Home).Property(TMDbHelper.ListItem.discart)
Window(Home).Property(TMDbHelper.ListItem.clearart)
Window(Home).Property(TMDbHelper.ListItem.clearlogo)
Window(Home).Property(TMDbHelper.ListItem.landscape)
Window(Home).Property(TMDbHelper.ListItem.banner)
```

**Comment by SerpentDrago** [comment]
Thank you so much !
