### ISSUE TITLE
TMDBHelper closing DialogVideoInfo.xml in add_path/del_path loop

### ISSUE THREAD

**Issue by inb4after** [jurialmunkey/plugin.video.themoviedb.helper#492]
I would like to ask for your help in understanding [this issue](https://github.com/SerpentDrago/skin.auramod/issues/16) with TMDBHelper in AuraMOD skin.

Since TMDBHelper 4.0, `del_path` and `prevent_del` script functions no longer exist. This breaks a loop within AuraMOD skin which depends on `TMDbHelper.Path.Current`.

Here is the order of operations:

1. `add_path` (with `prevent_del` parameter) for `Widget_TMDB` which is used for similar/recommended items.
> [skin.auramod/1080i/Includes_Object.xml#L6846](https://github.com/SerpentDrago/skin.auramod/blob/e430501d60eb0e59858ef2f2804e8da5dbe754d8/1080i/Includes_Object.xml#L6846)
>> [skin.auramod/1080i/DialogVideoInfo-Includes.xml#L1932](https://github.com/SerpentDrago/skin.auramod/blob/e430501d60eb0e59858ef2f2804e8da5dbe754d8/1080i/DialogVideoInfo-Includes.xml#L1932)

2. This function also calls window `1137`, which then replaces itself with window `1134`
> [skin.auramod/1080i/Custom_1137_TMDB_Info_Reload.xml#L7](https://github.com/SerpentDrago/skin.auramod/blob/e430501d60eb0e59858ef2f2804e8da5dbe754d8/1080i/Custom_1137_TMDB_Info_Reload.xml#L7)

3. This begins a loop in window `1134` (control `9999`) which does `Action(Info)` when `TMDbHelper.Path.Current` is filled.
> [skin.auramod/1080i/Custom_1134_TMDB_Info.xml#L25](https://github.com/SerpentDrago/skin.auramod/blob/e430501d60eb0e59858ef2f2804e8da5dbe754d8/1080i/Custom_1134_TMDB_Info.xml#L25)

4. This opens `DialogVideoInfo.xml` for the current item, but after some 30 seconds, TMDBHelper closes `DialogVideoInfo.xml` and wipes `TMDbHelper.Path.Current`, leaving window `1134` stuck in busy dialog with control `9999` focused.
> [plugin.themoviedb.helper/resources/lib/window/manager.py#L128](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/abc6e8bb6284571a90d95cb2e228bec2a106b5cd/resources/lib/window/manager.py#L128)

5. The unloading of `DialogVideoInfo.xml` does `del_path` and then calls `1137` to reload `1134`, but only if `TMDbHelper.Path.Current` is filled.
> [skin.auramod/1080i/DialogVideoInfo.xml#L11](https://github.com/SerpentDrago/skin.auramod/blob/e430501d60eb0e59858ef2f2804e8da5dbe754d8/1080i/DialogVideoInfo.xml#L11)

6. Another symptom is if the user presses back before the above bug happens, `DialogVideoInfo.xml` exits and then reloads with the same item information.
> [plugin.themoviedb.helper/resources/lib/window/manager.py#L53](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/abc6e8bb6284571a90d95cb2e228bec2a106b5cd/resources/lib/window/manager.py#L53)

These symptoms are quite similar to what skyfsza (AuraMOD creator) experienced when first developing this loop: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/27

Thanks in advance for any advice, it would be much appreciated.

**Comment by jurialmunkey** [comment]
There's info in the wiki about setting up the extended info replacement

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Replacing-Extended-Info

**Comment by inb4after** [comment]
Thanks for the help jurial, had to move some of the custom overlay but overall it now works as it used to!
