### ISSUE TITLE
[FEATURE REQUEST] Add default select action in addon

### ISSUE THREAD

**Issue by tekhop** [jurialmunkey/plugin.video.themoviedb.helper#493]
I've setup a widget with my trakt watchlist, and if I chose Explore in Settings/Navigation/Default select action in addon, when I click on a movie it opens a context menu for all the movie info.
The only other option is to play the movie.
Is it possible to add a "Show infopage" option?

**Comment by jurialmunkey** [comment]
You can change default select action to show information in standard Kodi settings

https://kodi.wiki/view/Settings/Media/Videos#Default_select_action
