### ISSUE TITLE
Certification for German

### ISSUE THREAD

**Issue by Reichi00** [jurialmunkey/plugin.video.themoviedb.helper#496]
Hello, I have put the add-on in German and can also read everything in German. Everything is great, but the certification is not displayed in German, but for the USA.  Can you help me there?

**Comment by SerpentDrago** [comment]
Certifications come from OMDB  if i'm not mistaken , and as such only contain the American  (MPAA Certification)  Jurial would have to add another meta provider to pull german certifications . Which i dont' see happening .. unless tmdb itself can provide these though API calls . 

I could be wrong though

**Comment by jurialmunkey** [comment]
> Certifications come from OMDB.

Nope, only thing from OMDb is RT/Metacritic/Awards (OMDb does give certs but I don't use that info from there).

Certification ratings come from TMDb and depend on TMDbH language/region setting. These work perfectly fine for me. 

~If you previously had region set to USA then you likely have old details cached about the item. The details cache is valid for 2 weeks after which it will refresh itself with new details. If you want to force an item to refresh manually, you can do that from the context menu ("Refresh Details"). Alternatively, you can use the nuclear option by deleting the entire cache (make sure Kodi is closed first) from .kodi/userdata/addon_data/plugin.video.themoviedb.helper/Database/TMDb.db~

EDIT: Just pushed a fix that makes that separates details cache according to language/region settings. So as of v4.3.6 you shouldn't need to refresh details any more when changing language - it will just update accordingly.

![Honeyview_screenshot00040](https://user-images.githubusercontent.com/4618719/118738549-ad742600-b88a-11eb-88ea-02cc460195ec.jpg)

![Honeyview_screenshot00039](https://user-images.githubusercontent.com/4618719/118738565-b36a0700-b88a-11eb-98ea-e5fc8270e951.jpg)

**Comment by Reichi00** [comment]
I think there was a small bug in your last update.  Under settings "General" under "MPAA rating prefix" you entered "Rated".  Unfortunately there is a teacher sign at the end and therefore I cannot display the symbols for the certifications in my skin view.  That's why I wanted to ask if you could remove this space.

**Comment by jurialmunkey** [comment]
I don't know what you mean by "teacher sign"

You can change the prefix text to be whatever you like

Also I didn't change anything in the code - I just split the details cache by language so that you don't have to refresh it when changing language
