### ISSUE TITLE
Valid Error: XBMCVFS reports unable to create path (on FTP server)

### ISSUE THREAD

**Issue by jmh2002** [jurialmunkey/plugin.video.themoviedb.helper#497]
Sorry @jurialmunkey, I couldn't reopen my previous issue so had to create a duplicate with the link of my reply and findings to your question:

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/488#issuecomment-844721179

**Comment by jurialmunkey** [comment]
I'll reopen the other one and close this one.
