### ISSUE TITLE
Error on LibreElec when trying to call Player via TMDBH

### ISSUE THREAD

**Issue by jmh2002** [jurialmunkey/plugin.video.themoviedb.helper#498]
I would be pleased for some help with this problem, but I'm not sure if the problem is with TMDBH, third party player (The Oath), LibreElec Kodi Matrix v19, or some other error on my part. But I'll start here with TMDBH and go from there.

- I try to play a TV episode via TMDBH
- TMDBH starts 'Building Player Dialog...'
- The Oath displays 'Preparing Sources dialog as normal, but then it fails and disappears
- and Kodi just shows 'working'
- Kodi isn't frozen, pressing Back stops 'working'

I have the same Kodi setup across multiple devices, LibreElec, Windows, and Android, but this error only occurs on the LibreElec device. Additionally for information the same setup worked on LibreElec with Kodi Leia 18.9 but I appreciate that there have been many changes with Matrix.

Here is the debug log: https://paste.kodi.tv/diqisexaki.kodi

THANKS :)

**Comment by jurialmunkey** [comment]
TMDbH is working properly. Player issue.

Player probably needs to have is_resolvable set to false in configure players dialog (in TMDbH settings).
