### ISSUE TITLE
[Bug] Phyton Exceptions with chars like äüö

### ISSUE THREAD

**Issue by PhunkMaZ** [jurialmunkey/plugin.video.themoviedb.helper#5]
Hi, i get lots of exceptions with movies and tv-shows having special characters like the german äöü in its title. Same goes for some actors with french characters in the name.

Most of the errors are
- UnicodeDecodeError: 'ascii'
- UnicodeDecodeError: 'utf8'

I can upload a log if needed.

Greetings

**Comment by jurialmunkey** [comment]
Platform? Kodi Version? Exact Steps to Reproduce?

**Comment by jurialmunkey** [comment]
I think I've managed to fix this bug. If you could test latest git version and confirm, that would be greatly appreciated.

**Comment by PhunkMaZ** [comment]
Hi

Systems are:
Intel NUC: Win 7, Kodi 18.4 Stable
PC: Win 10, Kodi 18.4 Stable and 18.5 Nightly

The bug appeared in movies like Star Trek: Zur**ü**ck in die Gegenwart or tv-shows like Akte X: Die unheimlichen F**ä**lle des FBI.

Anyways, it's working now with your latest github version. No exceptions in log. 

Thanks for all your work!

**Comment by jurialmunkey** [comment]
Thanks for testing and confirming. Much appreciated! 
I've submitted a pull-request for the fix, so it should be up on the official repo soon.
