### ISSUE TITLE
[QUESTION] TMDBHelper lookups as widget content

### ISSUE THREAD

**Issue by inb4after** [jurialmunkey/plugin.video.themoviedb.helper#501]
In AuraMOD we have a spotlight widget on the homescreen that loads actor info using:
`<content limit="6" target="video">plugin://plugin.video.themoviedb.helper/?info=cast&amp;$VAR[Info_Param_Type_1506]&amp;$VAR[Info_Param_IMDB_or_QUERY_1506]</content>` ([link](https://github.com/SerpentDrago/skin.auramod/blob/9b3a30f43dfcd23a62aa096b4f96f5bcfc866d14/1080i/Includes_Object.xml#L715))

Here are the variables:

https://github.com/SerpentDrago/skin.auramod/blob/9b3a30f43dfcd23a62aa096b4f96f5bcfc866d14/1080i/Includes_Defs.xml#L229

https://github.com/SerpentDrago/skin.auramod/blob/9b3a30f43dfcd23a62aa096b4f96f5bcfc866d14/1080i/Includes_Defs.xml#L238

When Kodi is restarted or skin is reloaded, we get a TMDBHelper error about a failed lookup `ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=cast&&query=`

This is most likely because the skin runs the lookup before Container(1506) has any info. If we wait a few more seconds after this error, the actor info does appear as intended.

How would we delay this content lookup, or is there a better workaround?

**Comment by jurialmunkey** [comment]
Have you tried hiding the actor widget container while the 1506 container is empty/updating?
`<visible>!Integer.IsEqual(Container(1506).NumItems,0) + !Container(1506).IsUpdating</visible>`

I can't remember if that works by itself but if it doesn't you can use it in tandem with a variable for content
`<content limit="6" target="video">$VAR[ActorWidgetContent]</content>`

```
<variable name="ActorWidgetContent">
<value condition="!Integer.IsEqual(Container(1506).NumItems,0) + !Container(1506).IsUpdating">plugin://plugin.video.themoviedb.helper/?info=cast&amp;$VAR[Info_Param_Type_1506]&amp;$VAR[Info_Param_IMDB_or_QUERY_1506]</value>
<value>plugin://plugin.video.themoviedb.helper/</value>
</variable>
```

**Comment by inb4after** [comment]
@jurialmunkey Thanks again, it works as intended using only the variable method!

Added adjustments for power menu and removed the fallback line:

```xml
<variable name="ActorWidgetContent">
        <value condition="!Integer.IsEqual(Container(1506).NumItems,0) + !Container(1506).IsUpdating + !Window.IsVisible(DialogButtonMenu.xml)">plugin://plugin.video.themoviedb.helper/?info=cast&amp;$VAR[Info_Param_Type_1506]&amp;$VAR[Info_Param_IMDB_or_QUERY_1506]</value>
</variable>
```

I did try something similar, but must have done something wrong as I was still getting an error. It was probably for using `Container(1506).IsUpdating` instead of the inverse. 👍
