### ISSUE TITLE
add {showyear} to wiki Available Keys

### ISSUE THREAD

**Issue by 123Venom** [jurialmunkey/plugin.video.themoviedb.helper#504]
@jurialmunkey petty of me to ask but you once added this `{showyear}` key for me when we discussed this awhile back.  When you get around to it could you add it to the wiki list of Available Keys?

**Comment by jurialmunkey** [comment]
Thanks for the reminder! I completely forgot to add those to the wiki (there's `{showpremiered}` too). Added now.
