### ISSUE TITLE
[Feature Request] Split Hide specials / Up Next option

### ISSUE THREAD

**Issue by Edd75** [jurialmunkey/plugin.video.themoviedb.helper#507]
Hello,
My suggestion is if it were possible, within the settings options -> Navigation, to be able to divide this option into two different ones, so that it can show the Specials but not the Up Next folder.
Thank you very much for considering it.

**Comment by jurialmunkey** [comment]
Can you test latest github version. Should now be able to select which special folders are hidden.

**Comment by Edd75** [comment]
Checked. I have reviewed it in 4.3.12.
The options are really wide to customize the views.
Thank you!
