### ISSUE TITLE
[Feature Request] Could we get Last_Aired.Year

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#508]
We currently have the following properties for tv shows:-

Last_Aired, Last_Aired.Day and Last_Aired.Long

Could we also get Last_Aired.Year, I would like to be able to display the years a tv show ran for using something like:-

<label>Ran from $INFO[Window(Home).Property(TMDbHelper.ListItem.Year)] to $INFO[Window(Home).Property(TMDbHelper.ListItem.Last_Aired.Year)]</label>

to get an output like:-

Ran from 2005 to 2011

Thanks

**Comment by jurialmunkey** [comment]
Easy! Added in v4.3.12 matrix

**Comment by roidy** [comment]
Thanks 👍
