### ISSUE TITLE
[BUG] Crash after select player

### ISSUE THREAD

**Issue by rehannali** [jurialmunkey/plugin.video.themoviedb.helper#511]
Hi, I'm using kodi 19 and everything working fine suddenly it starts crashing.

After i press any player to start Video, it shows splash screen TMDB and then crashes.

I'm using is on Macbook Pro `11.4`.

Debug logs are [here](https://pastebin.com/NB9VSSze).

**Comment by jurialmunkey** [comment]
The resolvable flag for that player should be set to false in the player config dialog.

**Comment by jurialmunkey** [comment]
Looks like TMDbH is working properly and it's the player plugin that's crashing.

You could try adjusting the splash times in TMDbH expert settings to be longer (sometimes if Kodi tries to play too quickly after it will crash on some systems). There's also an option to disable the splash completely (you will lose some resume features for some players but the trade-off can be worth it if you find the splash is causing a crash).

**Comment by audiosistem** [comment]
Hi, I use the addon in Leia and Matrix. In Leia there are no problems (regardless of version-4.3.0 or last 4.3.17, or android, win or linux platform) keep track of tv and play (looking in my addons, the Oath , the Crew, Alvin, Revolution). In Matrix the same addon useful on win and android, but in the version for LibreELEC (9.95.5) no stream. In individual addons everything is ok. I changed, 20-30-40-50, times for the provider, I restricted and activated dummy ... do you know what else I could do, to be functional in raspberry 4?
There may, to a large extent, be no solution on your part and strictly adhere to the LibreELEC team. With thanks and appreciation, for what you do!

**Comment by jurialmunkey** [comment]
@audiosistem - There's no such thing a specific "LibreELEC version" - TMDbHelper uses exactly the same code on all platforms running matrix. Impossible to tell what your issue is without a debug log. You also need to provide proper description of the issue, and the exact steps needed to reproduce the problem.

**Comment by audiosistem** [comment]
Hi, I'm not contradicting anything, from what you say (as long as I don't have problems in windows and android 32/64).Thanks, I'll dig in, see where I'm wrong.

**Comment by BinaryAssault** [comment]
I have this issue too. Seems to happen more when selecting a movie vs selecting a tv show. I'll grab a log next time it happens. It does happen often though. 

I'm running kodi 19 with titan bingie mod 

I noticed that it gets to building players, then crashes shortly after. I'll attempt to adjust the splash as you mention above. I actually never see the splash screen and don't recall ever changing it.

**Comment by audiosistem** [comment]
> I have this issue too. Seems to happen more when selecting a movie vs selecting a tv show. I'll grab a log next time it happens. It does happen often though.
> 
> I'm running kodi 19 with titan bingie mod on windows
> 
> I noticed that it gets to building players, then crashes shortly after. I'll attempt to adjust the splash as you mention above. I actually never see the splash screen and don't recall ever changing it.
> 
> Edit- changing the splash time to max fixed an issue for me where I was 100% crashing every time. I'll do some more testing tomorrow. This is great

It works for me.
[plugin.video.themoviedb.helper-4.3.40(change).zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/7149021/plugin.video.themoviedb.helper-4.3.40.change.zip)

**Comment by jurialmunkey** [comment]
@audiosistem - I've removed the zip from your comment because it contains 3rd party players.

You can find zipped versions of TMDbH in my repo:
https://github.com/jurialmunkey/repository.jurialmunkey/tree/master/matrix/zips/plugin.video.themoviedb.helper

Here's the latest version:
https://github.com/jurialmunkey/repository.jurialmunkey/raw/master/matrix/zips/plugin.video.themoviedb.helper/plugin.video.themoviedb.helper-4.3.40.zip

**Comment by audiosistem** [comment]
> I've removed the zip from your comment because it contains 3rd party players.

Sorry, I'm a user, not a saint.

**Comment by BinaryAssault** [comment]
This is an issue again. I'm using 4.4.1. can grab a log if desired. 

I noticed it always happens after "building players". Gets to 66%, waits some amount of time then crashes.

**Comment by jurialmunkey** [comment]
@BinaryAssault - Yes, log would be good.

However, if it is crashing _before_ you select a player then that's an entirely different issue. Most likely you have added players for plugins that you've installed but then disabled.

TMDbH looks at all the players and then asks Kodi for the details for each one. If one is installed but disabled then Kodi crashes due to a bug in the Python addon module.

**Comment by BinaryAssault** [comment]
> @BinaryAssault - Yes, log would be good.
> 
> However, if it is crashing _before_ you select a player then that's an entirely different issue. Most likely you have added players for plugins that you've installed but then disabled.
> 
> TMDbH looks at all the players and then asks Kodi for the plugin each player uses. If a plugin is installed but you have disabled it in Kodi (instead of uninstalling it) then Kodi crashes due to a bug in the Python addon module.

I will get a log next time it happens. Unfortunately, it seems that if I enable debug logging in Kodi via the gui, it always works. So it's hard to get a debug log.

Regarding your comment about players. I'm aware of that actually as I stumbled across it before. I only have 2 add-ons and both are enabled. Not to get off topic, but I was thinking about that though, is it possible to check if an addon is disabled via Kodi API? If so, couldn't you pull defined players and check them against disabled plugins and skip the disabled one? Seems like a potentially simple solution for a pesky feature. I'm not familiar with Kodi back end enough to know the implementation details on something like that. Just an idea.

**Comment by Arthur1967** [comment]
If you install the open Wizard it will tell you which add-ons are enabled
or disabled  it has lots of valuable maintenance tools

**Comment by drinfernoo** [comment]
@jurialmunkey Is this what the change in 4.4.2 addresses? I was under the impression the API considered disabled add-ons as "not installed"... Or at least it used to work that way, if I recall correctly.

**Comment by Arthur1967** [comment]
I use Seren and Venom with it and it works fine not sure what he’s using

**Comment by jurialmunkey** [comment]
> @jurialmunkey Is this what the change in 4.4.2 addresses? I was under the impression the API considered disabled add-ons as "not installed"... Or at least it used to work that way, if I recall correctly.

Yep. System.AddonIsEnabled() was only added in Matrix so previously wasn't possible when I was still trying to keep back compatibility with Leia. 

The old System.HasAddon() command returns true if the addon is installed even if disabled, so previously there wasn't a quick way to check.

**Comment by BinaryAssault** [comment]
Fwiw, I increased the dummy settings to max and it seems to be pretty stable again
