### ISSUE TITLE
plugin.video.themoviedb.helper/resources/lib/script/router.py uses xbmc.translatePath

### ISSUE THREAD

**Issue by jojobrogess** [jurialmunkey/plugin.video.themoviedb.helper#515]
xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/44a065100f8ac900942c7792e7f143be5fa723ba/resources/lib/script/router.py#L286

I was searching through my addons looking for the culprit. 
This is the only file that doesn't have an   xbmc.translatePath = xbmcvfs.translatePath in it. 
I don't know how to code, so I could be wrong.

**Comment by jurialmunkey** [comment]
Thanks, must've missed that one. I've updated it to xbmcvfs. Nonetheless, that's almost certainly _not_ your issue as that specific code block is _never_ run in normal usage. That code block is a hidden debug function used to output API calls and the only way to access it is manually inputting an API request via the expert section of TMDbH settings dialog - there's absolutely no reason for a normal user to ever use that function.
