### ISSUE TITLE
update not working.

### ISSUE THREAD

**Issue by delluser** [jurialmunkey/plugin.video.themoviedb.helper#520]
I updated my build to a newer version and the MDBhelper does not update the library any longer.  I've waited fifteen to twenty minutes and it just does not update. I'm using the lastest version from the kodi repo. your version 4.3.14.  Any ideas

**Comment by jurialmunkey** [comment]
Nothing has changed on the library update side of things. Got a debug log? 

Also check the latest update log in `.kodi\userdata\addon_data\plugin.video.themoviedb.helper\log_library` as you will be able to see all the updates that occurred and exactly what happened. It's possible an update occurred but there wasn't much to check so it happened quickly (TMDbH will skip anything that isn't currently airing and is already in your library).

Also, check that your settings correct in TMDbH Setting > Library and that your Trakt account is authenticated.

**Comment by delluser** [comment]
I'll get back to you on Wednesday evening. I have a program that has a new episode on Wednesday.  Then I'll know for sure. I did re-authenicated my Trakt TMDbH account. I also checked the library settings and they were right. Maybe it was just the Trakt acct that was messed up. I'll let you know. Thank you for your time.

**Comment by delluser** [comment]
All is well the updates occur as they are supposed to. There were new episodes to update today and it worked properly. I would prefer to be able to set the update timer myself. I have high end devices and they update and settle down within 2 to 3 minutes and to have to wait 10 minutes for the TMDbH to update seems to take forever. nut thank you for your help and your time. Please consider a setting that would allow the user to set the update time depending on their devices and circumstances. Thank you

**Comment by jurialmunkey** [comment]
You already can set the time the update occurs in the settings. The 10 minutes after startup is only if you missed the last update time.

**Comment by delluser** [comment]
I realize that but i would prefer to be able to have the update occur at 'X' time after startup. I might not be watching at 2pm or what ever time and if the update time is missed now i have to wait 10 minutes instead of 'X' time after start up. Just a thought to make it more efficient.
