### ISSUE TITLE
[Request] Support for episodes in trakt lists

### ISSUE THREAD

**Issue by KavGoat** [jurialmunkey/plugin.video.themoviedb.helper#521]
I have liked this list on trakt.
https://trakt.tv/users/munch54/lists/one-chicago-viewing-order?sort=rank,asc

When I try to open this in TMDB helper, nothing happens. Everything works fine if the list is just movies or shows but episodes don't work.

Is there anything I can do about this?

Thanks

**Comment by jurialmunkey** [comment]
Trakt episode lists aren't supported currently
