### ISSUE TITLE
[Feature Request] Add a route to the search movies and search tv dialogs

### ISSUE THREAD

**Issue by mjanus** [jurialmunkey/plugin.video.themoviedb.helper#523]
I created a small plugin to do but it acts kinda funky some times. It would be awesome if you could incorporate it into the plugin itself. The following is what I had managed to sorta get working:

```
@plugin.route('/')
def index():
    addDirectoryItem(plugin.handle, plugin.url_for(searchtv), ListItem("Search TV Shows"), True)
    addDirectoryItem(plugin.handle, plugin.url_for(searchmovies), ListItem("Search Movies"), True)
    endOfDirectory(plugin.handle)


@plugin.route('/searchtv')
def searchtv():
    term = Dialog().input(heading='Enter the show name', type=INPUT_ALPHANUM)
    if term != '' and term != ' ':
        executebuiltin('Dialog.close(all,true)')
        executebuiltin('ActivateWindow(Videos, "plugin://plugin.video.themoviedb.helper/?info=search&type=tv&query={}", return)'.format(term))

    endOfDirectory(plugin.handle)

@plugin.route('/searchmovies')
def searchmovies():
    term = Dialog().input(heading='Enter the movie name', type=INPUT_ALPHANUM)
    if term != '' and term != ' ':
        executebuiltin('Dialog.close(all,true)')
        executebuiltin('ActivateWindow(Videos, "plugin://plugin.video.themoviedb.helper/?info=search&type=movie&query={}", return)'.format(term))

    endOfDirectory(plugin.handle)

def run():
    plugin.run()
```

**Comment by jurialmunkey** [comment]
You already can search from inside the plugin. Open tmdbhelper and choose the search menu

**Comment by mjanus** [comment]
On my build, i have a "submenu/ categories widget" that i added to execute a search from the main menu's "tv shows" section.

![image](https://user-images.githubusercontent.com/13682900/124133170-8dba4b00-da4f-11eb-9626-f43922e89c8a.png)

If i set the search button to point directly to the tmdbhelper's tv search, it will continue the least search session instead of creating anew one. That's why i needed to build my addon. I don't wan't to search the shows in my library, i want to search for shows on tmdb.

My movie section has the same thing where it shortcuts directly to the movie search. It also has the same issue

**Comment by ntzb** [comment]
Hi @jurialmunkey,
I'm also interested in this, and just in case the request was not clear - the point is having a "Search TV" and "Search Movie" buttons in the skin (e.g. Arctic Horizon 2) home submenu, that directly opens the input dialog, and then searches accordingly.
just like the Movies->Search->Search Movies menu item, which opens up the input dialog and searches.

maybe it's already possible, and we just need the right plugin url, to enter as a shortcut in the skin?

@mjanus thanks for that piece of code. why do you say it's funky? do you have a different solution by now?

**Comment by jurialmunkey** [comment]
`ActivateWindow(Videos,"plugin://plugin.video.themoviedb.helper/?info=search&tmdb_type=movie",return)`

Works perfectly fine for me. 

You don't even need to type it in-- you can just add it as a link
`Video Add-ons > TMDbHelper > Search > Search Movies > Blank keyboard OK > Create menu item here`

**Comment by jurialmunkey** [comment]
If you need to force Kodi to refresh the directory because it is caching the last opened directory then you can add a reload param to the end of the path.
`plugin://plugin.video.themoviedb.helper/?info=search&tmdb_type=movie&reload=$INFO[System.Time(hh:mm:ss)]`

As long as you don't reopen it within the same exact second that will make it appear to Kodi as a new path and so retrigger the search.

**Comment by nitzan-blink** [comment]
adding `&reload=$INFO[System.Time(hh:mm:ss)]` to the end of the path does refresh the directory and is exactly what we wanted.
as usual thanks for the super quick reply and solution.
the referenced commit and version now also adds it by default, when added as a link like you suggested above, so thanks for that too.

**Comment by ntzb** [comment]
adding `&reload=$INFO[System.Time(hh:mm:ss)]` to the end of the path does refresh the directory and is exactly what we wanted.
as usual thanks for the super quick reply and solution.
the referenced commit and version now also adds it by default, when added as a link like you suggested above, so thanks for that too.

**Comment by daveftw84** [comment]
> `ActivateWindow(Videos,"plugin://plugin.video.themoviedb.helper/?info=search&tmdb_type=movie",return)`
> 
> Works perfectly fine for me.
> 
> You don't even need to type it in-- you can just add it as a link `Video Add-ons > TMDbHelper > Search > Search Movies > Blank keyboard OK > Create menu item here`

this keeps poping up a enter search query after searching
 for me
