### ISSUE TITLE
Error prompted when clicking the Similar - Arctic Horizon skin button and selecting any further action with TV Shows

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/plugin.video.themoviedb.helper#524]
As the title says, when using Arctic Horizon skin and you're viewing TV Show lists, episodes, etc. if you click on the **Similar** button which is connected with the TMDb Helper Add-on no matter from which add-on you might be using and you select either the **Similar**, **Recommended**, **From Director**, etc. You get prompted with an tmdb helper error. Hence, the task will still be performed and it will show you a list of whatever option you clicked despite the error. However, I wanted to share this issue as it gets a bit annoying triggering so many errors. Again, this is only happening with TV Shows, there's no Errors being presented when you use the **Similar** button with Movies.

### Here are three screenshots, 1 from an add-on outside of TMDb Helper triggering the error, 2nd from inside the TMDb Helper add-on itself, and 3rd is the Error log itself.

![2763DED9-09A0-47E5-AFE6-AFC0206BDF24_1_201_a](https://user-images.githubusercontent.com/76958541/124196264-0ba34400-da9a-11eb-975a-02ae6e184f61.jpeg)
![FA49BB49-44B7-4EBD-A470-6F5FB7C9E780_1_201_a](https://user-images.githubusercontent.com/76958541/124196305-207fd780-da9a-11eb-8fef-92e3138ac170.jpeg)
![BD17B0AC-DB18-4DB4-B0F7-9D24C7243609_1_201_a](https://user-images.githubusercontent.com/76958541/124196335-31304d80-da9a-11eb-91be-54b4bc41fd9c.jpeg)

**Comment by drinfernoo** [comment]
This seems like probably a skin issue, where the skin is calling the wrong path.

**Comment by Nuklear92** [comment]
> This seems like probably a skin issue, where the skin is calling the wrong path.

Maybe, I decided to share the issue here because the dev usually works on both projects and since theoretically both the skin and addon work in conjunction I don't think it won't matter much if I did it in A.H skin GitHub or here. 🤔🙂

**Comment by jurialmunkey** [comment]
TMDbHelper issue caused by one of the ListItem fields being blank when it tries to split. ^^^ Above commit should fix it.

**Comment by Nuklear92** [comment]
@jurialmunkey thanks that did fixed the issue! 😃
