### ISSUE TITLE
Tmdb doesn't find posters and fanarts

### ISSUE THREAD

**Issue by Greenylie** [jurialmunkey/plugin.video.themoviedb.helper#525]
So I've been following the situation since the problem has been reported by others (see [this discussion](https://www.themoviedb.org/talk/60de0392a128560074955f5d))

Despite Olympia should have fixed the issue with metadata.common.themoviedb.org v3.2.15, I can't manage to receive posters and fanart with your plugin.video.themoviedb.helper which I use integrated with Auramod for Kodi matrix.

Obviously, the API keys are there in the settings, so this shouldn't be the problem.

If everything it's ok in the code and APIs I'll probably need help fixing it on my end.

**Comment by jurialmunkey** [comment]
Posters and fanart work perfectly fine for me.  

What are the exact steps to reproduce the issue? Got a screenshot?

Also what API keys are you talking about and where? This plugin doesn't use metadata.common.themoviedb.org and you don't need to input any API keys for artwork from TMDb.

Are you sure you aren't confusing this plugin with the library scraper?

**Comment by Greenylie** [comment]
> Posters and fanart work perfectly fine for me.
> 
> What are the exact steps to reproduce the issue? Got a screenshot?
> 
> Also what API keys are you talking about and where? This plugin doesn't use metadata.common.themoviedb.org and you don't need to input any API keys for artwork from TMDb.
> 
> Are you sure you aren't confusing this plugin with the library scraper?

So I use an addon called Kodi On Demand (which is Italian) that offers the possibility to add the content to Kodi's library.
Just a couple of things:
Kodi version: 19.1
Skin: Auramod for Matrix (With tmdb service monitor setting on)
APIs: I entered omdb and fanart.tv keys

For the anime "To your eternity" it can't find any fanart (even tho on the [tmdb site](https://www.themoviedb.org/tv/97525/images/backdrops?language=it-IT) there's at least one without language)
![image](https://user-images.githubusercontent.com/41172833/124389397-21f20f80-dce7-11eb-9252-aea1be0d1d7b.png)
Also it doesn't find the image I uploaded on [fanart.tv ](https://fanart.tv/series/375271/to-your-eternity/)

For the anime "The way of the househusband" there's no media at all. (Even tho on [tmdb](https://www.themoviedb.org/tv/112160/images/backdrops) there's something)
![image](https://user-images.githubusercontent.com/41172833/124389807-215a7880-dce9-11eb-8db8-7edcb4067d65.png)

This happens even with series that precedently had media scraped (es. Naruto Shippuden)

For the last question I'm not really sure, I mean i thought the artwork selection integrated in auramod was strictly connected with your plugin, since it was in the installation wiki, am i wrong?

**Comment by jurialmunkey** [comment]
Posters and fanart for library items has nothing to do with this plugin. Artwork and other metadata of library items is the job of the scraper that you use.

You are probably confusing the scraper with this plugin because TMDbHelper has a service monitor function which can provide additional artwork, ratings and other metadata "on the fly" - but that's a thing the skin handles and is only for the currently focused item, it doesn't add the info to the item itself.

The screenshots you are showing have nothing to do with the service monitor - anything in the "Choose Artwork" menu is about attaching artwork to the item, and would be provided by the library scraper that you use.
