### ISSUE TITLE
[Bug] Add to library ignores unaired episodes setting

### ISSUE THREAD

**Issue by newf276** [jurialmunkey/plugin.video.themoviedb.helper#53]
While I have the setting checked to hide unaired movies and episodes in the Addon, for some reason unaired episodes are still being added to the Kodi library.  When I look at my trakt tv show collection via the Addon under trakt menu, they are not visible. Not sure if this setting is to only hide unaired episodes/movies in the Addon? I assume it is. 

I would recommend that when a show is added to the Kodi library it remains hidden, or like many other addons it is displayed as a red colour. Not sure if it is possible to add code to the add to library function so it does not add the unaired items, or to have it display in a different colour. Maybe it is a Kodi issue? Not sure? Thoughts?

**Comment by jurialmunkey** [comment]
Since the scraper populates library info, I can't control the colour of the label.

However, it definitely should be respecting the setting to hide unaired and not adding those to the library IMO. I think I know what the cause might be - I'll have a look later when I'm back home from work.

**Comment by newf276** [comment]
Understood, thanks.

**Comment by jurialmunkey** [comment]
@newf276 - I can't recreate this issue. I just added the show "Picard" which has a lot of upcoming episodes listed and only the first episode was added when I had the setting enabled (and with the setting disabled I got the whole season of upcoming episodes).

Are you sure you have the setting enabled? (A common mistake is people don't click OK to save their addon settings and just press back instead).

What are the exact steps that you are taking to add the show to library?

**Comment by jurialmunkey** [comment]
Also can you test with latest version as it may have been related to this bug https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/54 which is now fixed.

**Comment by newf276** [comment]
> @newf276 - I can't recreate this issue. I just added the show "Picard" which has a lot of upcoming episodes listed and only the first episode was added when I had the setting enabled (and with the setting disabled I got the whole season of upcoming episodes).
> 
> Are you sure you have the setting enabled? (A common mistake is people don't click OK to save their addon settings and just press back instead).
> 
> What are the exact steps that you are taking to add the show to library?

Yes 100% certain it is and has always been enabled.  That being said, I deleted the library today after discussing this issues with some folks on Reddit yesterday. apparently Trakt had bene causing many errors yesterday to almost every video Addon, so I suspect it was a trakt issue, as it is no longer occurring after redoing a test library.  Sorry for creating work for you when it was not required my friend. So I do not think it is a bug, and we can remove the issue.

**Comment by jurialmunkey** [comment]
Not a problem! Thanks for testing.
