### ISSUE TITLE
[Feature Request] ListItem.Property(Top250)

### ISSUE THREAD

**Issue by inb4after** [jurialmunkey/plugin.video.themoviedb.helper#530]
This works well with service monitor, it would be beneficial to have for containers and focused item as well.

https://i.imgur.com/z6ODlEE.png

**Comment by jurialmunkey** [comment]
As I said in the other issue. TMDbHelper does not fill ratings/votes etc. for ListItem.Properties
The cost of making all these extra requests is not worth it for the minimal benefit it gives. It's an extra 2 trakt requests and 1 omdb request _per_ item for something that rarely ever needs to be referenced on unfocused items -- and for focused items you can already use the service monitor.

Think about how long it takes for the service monitor to fill new details for the focused item if it hasn't previously been cached - now multiple that by 20 and that's the extra overhead it would add to a list.
