### ISSUE TITLE
[BUG] Custom Network/Studio properties inconsistencies

### ISSUE THREAD

**Issue by inb4after** [jurialmunkey/plugin.video.themoviedb.helper#531]
Studio and Network custom properties have inconsistencies if using an addon other than TMDBHelper:

TMDBHelper item: https://i.imgur.com/XNktw9a.png

Other addon item: https://i.imgur.com/WEzFe7s.png

1\. `ListItem.Property(Network)` and the positional `ListItem.Property(Network.X.Name)` is not being set for Other addon items; they are both already correct here for TMDBHelper items

2\. The custom property `ListItem.Property(Studio)` for both TMDBHelper and Other addon items is not being set; the positional `ListItem.Property(Studio.X.Name)` is already correct here for TMDBHelper items but not for Other addon items

Note that `Window(Home).Property(TMDBHelper.ListItem.[property])` is always correct

**Comment by jurialmunkey** [comment]
Can't control what other plugins do. It is not possible to change the properties of another plugins' listitems.

Anything that is attached to a listitem is set by the plugin that created it. The properties of a listitem can only be set _before_ it is created -- once it is created and is visible on screen, they cannot be changed

If that was possible, I wouldn't bother with window properties at all and would just write directly to the listitem properties... That's the whole point of the service monitor - to get additional info not provided by the listitem itself.

**Comment by inb4after** [comment]
I always thought service monitor did the lookups and the rating was cached in the corresponding `ListItem.Property([property])` so it doesn't need to be looked up again. I think ListItem.X is definitely impossible (as those are left to the addon itself) but most custom properties are already working for every addon including TMDBHelper:

This is how it works for all other ratings currently: https://i.imgur.com/SzH8X71.png so it should definitely be possible, and would allow for studio/network logos on spotlight to not change on focus of normal widgets (as we are stuck using service monitor for now).

Notice the cached value is slightly lower than the lookup value. The spotlight item in focus is from another addon.

**Comment by jurialmunkey** [comment]
You can't change the properties or info of a listitem after a plugin creates it - it's just not how it works. There's no shared cache between plugins - whatever plugin you are using for that list is filling those properties itself by doing its own lookup.

**Comment by inb4after** [comment]
I don't think it is being looked up by the non-TMDBHelper addon, it seems to be stored in database locally after service monitor does the lookup:

1\. Award_Wins is 100% only given by TMDBHelper, and when I focus a non-TMDBHelper item, both the ListItem.Property and service monitor property are filled: https://i.imgur.com/gAFtpOR.png

2\. If I test with a non-TMDBHelper item, where Award_Wins was looked up before TMDBHelper updated and fixed the broken regex, I still see the bugged (old) value, since I haven't cleaned the database yet: https://i.imgur.com/dbFx4BM.png

This proves that TMDBHelper is already caching lookups into Listitem.Property even for other addons, which it does for many properties including ratings from TMDBHelper.

So the method of the above is already working, it's just that some properties aren't being stored such as Top250 and Studio/Network and their positional.

These (1) are also items I've never visited before either in the non-TMDBHelper addon or in TMDBHelper because if I have visited them previously, they will have bugged regex (2), and these items are also not part of my Kodi library either.

**Comment by inb4after** [comment]
Found the issue which is totally my mistake, the addon was in fact providing the very same properties as TMDBHelper was and I assumed both were working together.

The only solution seems to be a service monitor for `Window(id).Property(property)` or `Container(id).Property(property)`, where the `id` could just be the container id.

Could this be implemented by TMDBHelper or is this another Kodi limitation?

**Comment by jurialmunkey** [comment]
> The only solution seems to be a service monitor for Window(id).Property(property) or Container(id).Property(property), where the id could just be the container id.

That's the point of `SetProperty(TMDbHelper.WidgetContainer,WIDGET_ID,Home)` - it changes which ID the service monitor looks at.

If you need to lookup two separate container IDs _at the same time_ then you can use a hidden list details lookup. I recommend only using this sparingly where you absolutely need to get two lookups at once 

```xml
<variable name="DetailsContent">
    <value condition="String.IsEqual(Container(1505).ListItem.DBType,movie) + !String.IsEmpty(Container(1505).ListItem.IMDbNumber)">plugin://plugin.video.themoviedb.helper/?info=details&amp;tmdb_type=movie&amp;imdb_id=$INFO[Container(ID).ListItem.IMDbNumber]</value>
    <value condition="String.IsEqual(Container(1505).ListItem.DBType,movie) + String.IsEmpty(Container(1505).ListItem.IMDbNumber)">plugin://plugin.video.themoviedb.helper/?info=details&amp;tmdb_type=movie&amp;query=$INFO[Container(1505).ListItem.Title]&amp;year=$INFO[Container(1505).ListItem.Year]</value>
    <value condition="String.IsEqual(Container(1505).ListItem.DBType,tvshow) + !String.IsEmpty(Container(1505).ListItem.IMDbNumber)">plugin://plugin.video.themoviedb.helper/?info=details&amp;tmdb_type=tv&amp;imdb_id=$INFO[Container(ID).ListItem.IMDbNumber]</value>
    <value condition="String.IsEqual(Container(1505).ListItem.DBType,tvshow) + String.IsEmpty(Container(1505).ListItem.IMDbNumber)">plugin://plugin.video.themoviedb.helper/?info=details&amp;tmdb_type=tv&amp;query=$INFO[Container(1505).ListItem.TvShowTitle]&amp;year=$INFO[Container(1505).ListItem.Year]</value>
    <value condition="String.IsEqual(Container(1505).ListItem.DBType,season)">plugin://plugin.video.themoviedb.helper/?info=details&amp;tmdb_type=tv&amp;query=$INFO[Container(1505).ListItem.TvShowTitle]&amp;year=$INFO[Container(1505).ListItem.Year]&amp;season=$INFO[Container(1505).ListItem.Season]</value>
    <value condition="String.IsEqual(Container(1505).ListItem.DBType,episode)">plugin://plugin.video.themoviedb.helper/?info=details&amp;tmdb_type=tv&amp;query=$INFO[Container(1505).ListItem.TvShowTitle]&amp;year=$INFO[Container(1505).ListItem.Year]&amp;season=$INFO[Container(1505).ListItem.Season]&amp;episode=$INFO[Container(1505).ListItem.Episode]</value>
</variable>


<control type="list" id="90001">
    <itemlayout />
    <focusedlayout />
    <content>$VAR[DetailsContent]</content>
    <visible>!Integer.IsEqual(Container(1505).NumItems,0) + !Container(1505).IsUpdating</visible>
</control>

<label>$INFO[Container(90001).ListItemAbsolute(0).Studio]</label>
<label>$INFO[Container(90001).ListItemAbsolute(0).Property(Studio.1.Name)]</label>
<label>$INFO[Container(90001).ListItemAbsolute(0).Property(Studio)]</label>
<label>$INFO[Container(90001).ListItemAbsolute(0).Property(Network)]</label>

```


Also with latest commit you'll be able to get OMDb ratings using the above too (I've still got to add Trakt ratings in but everything else should be available).

**Comment by drinfernoo** [comment]
@jurialmunkey While testing this, I noticed that OMDb metadata does not appear to be fulfilled on the the `ListItem.Property` fields of items *inside* TMDbHelper... Is that by design, to save on calls, or an oversight?

**Comment by jurialmunkey** [comment]
@drinfernoo - intentional for performance reasons. The only content list I grab omdb data for is the `info=details` one. There's only ever one real item in that list (the one it is the details for) - all the other folders it displays are just duplicates of that detailed item but pointing to different places for navigation (eg cast, crew, similar, recommended etc). So the lookup cost is cheap (also you'd expect the details list to have, well, _all the details_...)

**Comment by drinfernoo** [comment]
I had a feeling, just wanted to check 😉
