### ISSUE TITLE
[Request] Add an automatic refresh to Your Next Episodes list

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/plugin.video.themoviedb.helper#533]
As the title says, when you finish watching any episode directly from within the Trakt - Your Next Episodes list. The episode you just watched regardless of being marked as watched from Trakt still shows when you stop the player and return to the list. It doesn't automatically refresh and show you the Next Episode from that Show until you back out from the list and enter again manually.

**Comment by jurialmunkey** [comment]
Refreshing containers is controlled by kodi. Kodi already does refresh all containers after you finish watching something. 

Likely what happened is that the plugin you played with didn't update trakt status quick enough for it to be marked watched before the list refreshes - that or the trakt server is too slow in updating status so when the new request happens it is still giving the old info.

You can always long press on the show to open context and manually mark as watched via the trakt management options (which will also refresh the list). Alternatively, you can go to context and browse lists, then go to seasons.

Ideally it would sync immediately but it doesn't always work like that. This is why i generally prefer the in progress list over next episodes

**Comment by Nuklear92** [comment]
Thanks, I'll try that option and I appreciate the extra detailed info. 😀
