### ISSUE TITLE
[Request]Trakt on Deck access

### ISSUE THREAD

**Issue by Debiggs** [jurialmunkey/plugin.video.themoviedb.helper#536]
Would it be possible to add “Trakt on Deck” to the “Trakt” section? This maybe the same question as #424 Lastly, Great work BTW. Thanks.

**Comment by jurialmunkey** [comment]
What does "On Deck" mean exactly? The Trakt website and API don't have anything called "On Deck".

**Comment by Debiggs** [comment]
“On Deck” is the playback progress of episodes or movies that the Trakt scrobbler uses when episodes or movies are stopped during playback but not finished.  I know there’s “In Progress TV” in Trakt but that list also includes episodes not watched.

**Comment by Ebonlore** [comment]
The Crew has it under My Shows

**Comment by Debiggs** [comment]
I know there are other addons that have it, but i prefer to use TMDB Helper due to it’s integration and reliability across devices.
