### ISSUE TITLE
[BUG] DialogVideoInfo from a widget only shows info the first time.

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#537]
When using the service monitor and getting information in DialogVideoInfo for a widget item the info only shows the first time you press info on the widget item, after that the info is blank.

1. Press info on widget item "A" - dialogvideoinfo shows the info fine
2. Back out and press info on item "A" again - dialogvideoinfo shows no info
3. Back out and press info on a different item - dialogvideoinfo shows the info fine
4. Back out and press info on item "A" again - dialogvideoinfo shows the info fine again
5. Go back to 2 and repeat forever :D

For library item the info works fine every time.

This is driving me crazy trying to figure out what is wrong :(

**Comment by jurialmunkey** [comment]
It works fine for me in Arctic Horizon. Is this for your own skin?

Check that you're setting `SetProperty(TMDbHelper.WidgetContainer,WIDGET_ID,Home)` to the correct ID and that your widget container ID isn't duplicated somewhere (e.g. two home widgets with same ID or container in the videoinfo dialog with the same ID).

~The info lookup in the videoinfo dialog _should_ work without widgetcontainer being set. However if you've got an ID conflict somewhere, then it could be the source of the issue.~ EDIT: Was just able to replicate this issue by _clearing_ the widgetcontainer property -- solution is to set it to your ID for the widget.

**Comment by jurialmunkey** [comment]
Okay latest commit should fix the issue when WidgetContainer property is empty.

**Comment by roidy** [comment]
Fix works perfect, thank you 👍
