### ISSUE TITLE
Library Integration doesnt work after the latest update

### ISSUE THREAD

**Issue by patel-jeel92** [jurialmunkey/plugin.video.themoviedb.helper#540]
I am trying to add a few lists to my library, however on some lists I get a prompt saying that adding items are limited to 500 TV Shows and 2500 movies. When was this limit added

The reason I had to wipe my library clean is because of the latest conversation we had regarding nfo files creation mentioned in [https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/538](url). Now I have a lot less tv show items in my source folder due to the limitations. 

Also the selected lists don't stay in settings. They get deselected and I have to select them again. No matter if the list is tiny and only has a few movies/tv shows.

**Comment by patel-jeel92** [comment]
Is there a way that you can let users add lists with more items? I use TMM to scrape my movies and tv shows with my own api keys. I would like have the tv shows added locally so I can scrape them by myself. Maybe turn off scraping if list contains more than the limit set right now? Currently the way it is, my list that I have built up over the years won't be added locally because of the limit

**Comment by jurialmunkey** [comment]
The limit has been there for a long time. 500 shows is a _lot_ of shows... It would take years to watch 500 shows.

**Comment by jurialmunkey** [comment]
The limit is there for a reason. Every time you do an update, TMDbH has to do individual look-ups of all the shows in that list that are currently airing and pull the episode list to check for new episodes. 

From my API stats, TMDbHelper currently has almost half a million unique users, with an average of 80k daily users and a total of more than 3.6 million requests _per day_. If I lifted the limits my API key would likely get banned or rate limited.

**Comment by patel-jeel92** [comment]
I understand but I would still like to add them to my local library. Can you allow us to add the items but exclude that list from updates? Or better yet, just update the recent 500 items from that list? Like I said I use TMM with my own apis to scrape information

**Comment by jurialmunkey** [comment]
Scraper is entirely irrelevant because TMDbHelper isn't the library scraper anyway - the scraper used has absolutely no impact on the number of requests generated by TMDbHelper.

The main purpose of the limit is to prevent people from indiscriminately adding massive auto-generated lists created by other users without really considering what is in them. So the limit is only per list, not total - which means that if these are your lists, then you can simply remove some items from one list to get it under the limit and then start a new list with the removed items and add both of them.

**Comment by patel-jeel92** [comment]
https://trakt.tv/users/a925sw/lists/popular-mini-series-2010s?sort=rank,asc

This is one of the lists I really like because I like mini series so how do I go about adding these. It's not my list so I can't really edit it.

**Comment by patel-jeel92** [comment]
Okay I understand that nothing can be done. I will split up my lists in trakt. Thanks
