### ISSUE TITLE
[Bug] Service Monitor looking up "Next" items

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#541]
We have had a bug reported for our add-on, where the next page item in our lists (called "Next", in our case), is getting metadata looked up and attached by the TMDbHelper service monitor, most often resulting in either "Jumanji: The Next Level" or "Baruto: Naruto Next Generations".

Is it possible to skip these such items for lookup?

**Comment by jurialmunkey** [comment]
It's difficult because there's no real way to differentiate the Next Page item from some other item in the list. How would the service monitor know to skip it?

**Comment by drinfernoo** [comment]
@jurialmunkey I'm not sure what criteria are used to do the lookup, but I don't believe I've ever seen it happen with items labeled "Next Page" in either TMDbHelper itself or AutoWidget (as it also adds items labeled "Next Page").

We considered simply changing our label to use the Kodi-provided "Next Page" localization (33078), but have reservations over whether or not we would end up with some other random title match, of that's the method used...

We do set `{"specialsort": "bottom"}` as a ListItem property on those items, and we considered proposing to you skipping items with that property set, but it seems that calling `xbmc.getProperty("ListItem.Property(specialsort)")` does not return a value, even if it has been set... So maybe Kodi "swallows" that value or something?

Also, looking at the service monitor, it seems those checks are skipped entirely for parent folder items (by checking if the label is `..`), so would it be possible to maybe check against the "Next Page" label? I do this in AutoWidget via a carefully crafted regex that covers most permutations of "Next", "Next Page", and even items which provide a page count (as found in some add-ons).

**Comment by jurialmunkey** [comment]
> {"specialsort": "bottom"}

I considered this too but unfortunately as you've found there doesn't appear to be a way to retrieve it.

> We considered simply changing our label to use the Kodi-provided "Next Page" localization (33078)

That's all I do in TMDbHelper - I don't do anything special, I just use that next page label - there's no shows called Next Page on TMDb so service monitor stays empty because no match (whereas just "Next" is pretty generic).

I do want to find a better solution in general to skip matching non-media items but so far haven't found anything consistently usable (not a fan of the regex approach because it gets a bit sketchy when localisation and variations come into play)

**Comment by drinfernoo** [comment]
Sounds good. Changing our label was my first thought to be honest (and have made that change already), but wanted to see if you had any ideas on how to completely skip it.

If you're interested in how my regex works: https://github.com/drinfernoo/plugin.program.autowidget/blob/master/plugin.program.autowidget/resources/lib/menu.py#L728

I've recently done some fixes to it that also handle translations (using my own `.po` definitions though) and different formatting, including Kodi string formatting tags and non-word characters (like `Next Page >>>`, for example).

All up to you if you want to implement something similar, obviously, but I'll close this for now 👍
