### ISSUE TITLE
Netflix or Seren Players not working

### ISSUE THREAD

**Issue by kodiuser-xiii** [jurialmunkey/plugin.video.themoviedb.helper#542]
Hi,

In my Kodi set up I have noticed that Seren or Netflix player does not function as intended. 

The Seren player is very erratic. I use the 'Play with Seren (Source Select)' player as that is the only player I found works(when it works!). Most times this player displays the 'Please wait' refresh screen and then does nothing after. The times that it provides the list of links (which is rare) it displays it after very long time. Seren is an amazing player and I like using it for all the non Netflix shows however, have difficulties using it via the TMDB helper player option.

As for Netflix player, I have never had any luck playing any Netflix shows through it. When this player is selected it does go and search for the show but then after it provides a list of all the fall back players to choose from. 

I have attached my [kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6873239/kodi.log) . Hope fully this helps you to find the cause of this. 

Many thanks.

**Comment by jurialmunkey** [comment]
I don't maintain 3rd party players. What I can tell you is that the Netflix player that comes bundled *with* TMDbHelper works perfectly fine - I use it all the time and am currently watching something tonight via it so it definitely works.

Likely you've downloaded a 3rd party version of the Netflix player which is broken. Make sure you are using the one that comes with TMDbHelper.

**Comment by kodiuser-xiii** [comment]
Apologies!! I was not aware that you did not look after the players. Who would I need to raise this with?

I installed the players in TMDB helper from http://bit.ly/tmdbplayers, is this not the correct link to get the players from?

How can I check and make sure that the Netflix player I am using is not a third party version. I have checked under TMDB Helper settings>Players>Use bundled players option and this is selected. So I am guessing that the app is using bundled players.

It would be really helpful if you can share some info on how did you set up your Netflix player.

**Comment by drinfernoo** [comment]
@kodiuser-xiii That package does not even include a Netflix player... To be safe, it may be worth installing it again and ensuring that you choose to "clear installed players" when prompted. You may have an old one hanging around.

**Comment by kodiuser-xiii** [comment]
Hi @drinfernoo,
You are right abobout link not including the Netflix player however it does show up player list comes up. I think its picking the Netflix player info from netflix.json file under my _.Kodi\addons\plugin.video.themoviedb.helper\resources\players_ folder. While the other players are saved under my userdata folder. 

Instead of what you suggested of just reinstalling the players I actually took it to the next level and reinsalled the entire TMDB helper addon again and below is summary of activity

- Uninstalled TMDB helper completely
- Cleared Kodi Cache using Openwizard addon
- Cleared Seren cache.
- Exited Kodi
- Relaunched Kodi
- Installed TMDB helper v4.3.27
- Activated Trakt
- Installed players from the bit.ly link above
- Tried playing a netflix show from the local library > failed
- Tried playing a non netflix show via Seren (play with Seren (Smartplay) player) > Kodi crahed
- Relaunched and tried using Seren again
- Tried playing a show via Seren (play with Seren (Smartplay) player) > 'Please wait' screen for few seconds
- Kodi crashed
- Relaunched and tried using Seren again
- Played a show via Seren (play with Seren (Smartplay w/ Source)) > - 'Please wait' screen for over a minute and no sources list displayed
- Played a show via Seren (play with Seren) > 'Please wait' screen for over a minute and nothing happens
- Played a  show via Seren (play with Seren Source Select) > 'Please wait' screen for few seconds and then nothing

So I am not sure what is wrong Seren use to work very well before its latest update to v2.1.3

I would appreciate any help or guidance you can offer here.

Here is my latest log if that helps.

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6881944/kodi.log)

**Comment by drinfernoo** [comment]
Well, only the Netflix player is relevant here, as it's already been explained that third-party players are maintained separately. Also, you really didn't need to do any of the steps you did do... The player file is all that matters here, considering the Netflix add-on works fine all by itself.

You'll need to raise that issue elsewhere, but it most likely just means that the player you're trying to use needs to be updated.

**Comment by kodiuser-xiii** [comment]
ok so how do I update the Netflix player? coz as explained that is not working for me. I can play a Netflix show through the NF addon without a problem.

**Comment by drinfernoo** [comment]
It is packaged with TMDbHelper, as you mentioned... And @jurialmunkey says it works. I haven't tested it in quite some time, but the Netflix add-on also works for me.

**Comment by kodiuser-xiii** [comment]
ok...but is there a way for you or @jurialmunkey to help me find out why Netflix player its not working for me? or I just live with the fact that I fall under few other users facing this issue.

**Comment by jurialmunkey** [comment]
@kodiuser-xiii 

First thing to check is that you can play the item you are trying to play via the Netflix plugin itself. Also check that you can create a new search in the Netflix plugin.

Assuming your Netflix plugin is searching and playing correctly, can you try the following:

- Exit Kodi
- Delete the folders `.kodi/userdata/addon_data/plugin.video.themoviedb.helper/players` and also `reconfigured_players` if it exists (this will ensure that you are definitely using the built-in Netflix player).
- Reopen Kodi and attempt to play the item via the Netflix player.

If that fails, please tell me what you are trying to play. If you're playing from the library, please provide me the `.strm` file that you are using (you can just open it in a text editor and copy the contents here as text rather than uploading the file itself).

Also please tell me your TMDbHelper settings for the following and I'll see if I can recreate the issue

- General > Language and country
- Players > Automatically play local files
- Players > Use bundled players
- Expert > All four Dummy ResolvedURL settings (duration / delay / reroute / restrict).

**Comment by kodiuser-xiii** [comment]
@jurialmunkey 

Thank you for providing the steps to diagnose the issue.

I followed your instructions and still have had no luck :(. I can confirm that I can search and play the episodes below of two shows in Netflix add-on.

- _plugin://plugin.video.themoviedb.helper/?info=play&tmdb_type=tv&islocal=True&tmdb_id=93454&season=1&episode=3_
- _plugin://plugin.video.themoviedb.helper/?info=play&tmdb_type=tv&islocal=True&tmdb_id=119988&season=1&episode=2_

My TMDB helper setting info is:
- General > Language and country => _English (New Zealand)_
- Players > Automatically play local files => _Selected_
- Players > Use bundled players ==> _Selected_
- Expert > All four Dummy ResolvedURL settings  
           duration / delay => _1.0 Sec_
           reroute => _Selected_
           restrict=> _Unselected_

Not sure if this info helps but I have noticed that the player searches for the show in Netflix addon coz I have seen the show name under the search history. For some reason it fails to pick the episode to play.

**Comment by jurialmunkey** [comment]
@kodiuser-xiii - Can you try something with a second season? These two shows both look like miniseries and I've noticed an issue with the Netflix plugin recently where it sometimes doesn't fill the season number or flattens the series when it's a miniseries/single-season show (so player fails because it is trying to open season 1 folder). The other show (The Innocent) might be failing due to Spanish language title - but I think it might be the same miniseries issue.

**Comment by jurialmunkey** [comment]
Okay for these two shows ("The Serpent" and "The Innocent") it is definitely the flattened miniseries issue. The above commit will fix the issue by adding the ability for players to have early exit steps by specifying `"return": "true"` -- 

Basically, the Netflix player now has an additional early exit step which first checks for a matching episode before attempting to open a season folder just in case it's a single series miniseries that opens directly into episodes.

**Comment by kodiuser-xiii** [comment]
> @kodiuser-xiii - Can you try something with a second season? These two shows both look like miniseries and I've noticed an issue with the Netflix plugin recently where it sometimes doesn't fill the season number or flattens the series when it's a miniseries/single-season show (so player fails because it is trying to open season 1 folder). The other show (The Innocent) might be failing due to Spanish language title - but I think it might be the same miniseries issue.

@jurialmunkey  I tried other shows which had more than one season and they worked :). The shows I tried were Cobra Kai S3E10, The Crown S4E10 and Virgin River S2E9.
The ones which did not work for me were Money Heist and Lupin. The only reason I could guess was to do with the season numbering being different in MDB vs Netflix. So these ones unfortunately will be watched through the addon directly. 




> Okay for these two shows ("The Serpent" and "The Innocent") it is definitely the flattened miniseries issue - I can reproduce the problem. The above commit will fix the issue by allowing players to specify early return steps with `"return": "true"`
> 
> Basically, the Netflix player now has an additional early exit step which first checks for a matching episode before attempting to open a season folder just in case it's a single season miniseries that opens directly into episodes.

Thanks for adding an early step. Do I need to do anything my end to get these changes or they will come through automatically in the next update?

**Comment by drinfernoo** [comment]
@kodiuser-xiii The new player should already be available in 4.3.28 from the repo.

**Comment by jurialmunkey** [comment]
>  The ones which did not work for me were Money Heist and Lupin. The only reason I could guess was to do with the season numbering being different in MDB vs Netflix. So these ones unfortunately will be watched through the addon directly.

Yeah *Money Heist* is a difficult one. When Netflix did the English dub, they re-cut the original 15 episodes of *La Casa de Pape* Season 1 into 22 shorter episodes split into Part 1 and Part 2 (and Season 2 became Part 3 and Part 4). TMDb has original Antenna 3 TV episode air order, not the new Netflix order. 

No real solution for that other than go into Netflix plugin unfortunately

**Comment by kodiuser-xiii** [comment]
> @kodiuser-xiii The new player should already be available in 4.3.28 from the repo.

@drinfernoo  The update has come through. The shows with single season works perfectly. Thanks heaps for getting this resolved. Now I can use Netflix player with confidence. Just a suggestion (probably a future enhancement) if the Netflix.json player could include a script to check for resume point would be great. This will then align with the way Netflix addon works providing the option to play from a resume point or from beginning for partially watched episodes/movies.  

Now I will on to see why Seren player is not working (I know you have nothing to do with it), was hoping to have Seren player as a fall back to Netflix player. Hopefully I find something on the internet. I may have figured that it's probably the Aura Mod skin that could be the cause.

Anyways thanks for your help.

**Comment by jurialmunkey** [comment]
> Just a suggestion (probably a future enhancement) if the Netflix.json player could include a script to check for resume point would be great. 

Resume point for Netflix works perfectly fine when playing from TMDbHelper plugin as it uses setResolvedURL -- the only caveat is that Kodi will only save the resume point from the last time you played it with TMDbHelper. There's no way to retrieve the resume point from the Netflix plugin itself as the resume point needs to be created before you click the item to play it.

If resume point doesn't work from library then that's a Kodi issue. It definitely works perfectly fine from inside TMDbHelper because I use it all the time.
