### ISSUE TITLE
[Request] Season specific artwork

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#544]
Hi @jurialmunkey. I have two small requests. The first relates to information about number of seasons in tv shows. We have metadata for the number of episodes within a season but there is no number of seasons within an entire tv show.
Other request relate to artwork. We don’t have fanarts for tv shows seasons. For seasons, it shows a picture of the whole tv show. But pay attention to one thing, and that is that when there is no picture of the season, then use the picture of the whole tv show.
I think this is not so difficult for you to implement in tmdb helper considering that some other addons already have this. Thanks in advance. 😉

**Comment by jurialmunkey** [comment]
^^^ That commit will fix the missing season count (added to `ListItem.Season`). I didn't even realise it was missing - I mistakenly thought I'd already added it but I think I must've only added episode counts to seasons, not season counts to tvshows.

Season specific artwork is a bit more complicated. It's definitely possible as fanart.tv does supply it - I will just need to think about best way to approach it.

**Comment by matke-84** [comment]
@jurialmunkey Half job is done with this. 🙂 You should also insert a property for TotalSeasons and TotalEpisodes.
About season artwork, look at this as done in the elementum. Maybe it will help you a little.
https://github.com/elgatito/elementum/commit/bb5662f35d4da0dffe00454cf133047bd32b9634

**Comment by matke-84** [comment]
@jurialmunkey Hi jurial. Can you please just insert the property for totalseasons and totalepisodes.  You don't have to rush for fanarts. Thanks. 😉

**Comment by jurialmunkey** [comment]
> Can you please just insert the property for totalseasons and totalepisodes. 

You already can get these:

`$INFO[ListItem.Season]` will give you the the total number of seasons the tvshow has

`$INFO[ListItem.Episode]` or `$INFO[ListItem.Property(totalepisodes)]` will give you the total number of episodes the tvshow has (it will also work for individual seasons to show how many episodes the season has).

**Comment by jurialmunkey** [comment]
And ^^^ that commit will also assign listitem.season to listitem.property(totalseasons) in case you have a skin that specifically uses the property instead.

**Comment by matke-84** [comment]
@jurialmunkey That's it my friend. Thank you very much. When you find some free time , try to solve the fanarts as well.  ;-)

**Comment by matke-84** [comment]
@jurialmunkey
I hope you haven't forgotten about this. 🙂 The only problem here is that the landscape images is not displayed seasons. Instead of showing the season as with a poster, it displays a landscape image of the entire tv shows. So if I use some landscape view in skin then all the images are the same. But don't forget that if there is no landscape image for a season, then it shows a fallback image for the whole season. I hope I wasn’t too confused. 🙂

**Comment by jurialmunkey** [comment]
Nope haven't forgotten about this request. It was actually next on my list since I've been working on the fanarttv stuff lately

**Comment by jurialmunkey** [comment]
Added in v4.5.20

**Comment by matke-84** [comment]
@jurialmunkey
Thank you very much my friend. 😉

**Comment by matke-84** [comment]
@jurialmunkey
There is a small bug though. For example, if you enter in episodes group in Game of thrones, you will see that it shows all the posters from season eight instead of a different poster for each season.

**Comment by jurialmunkey** [comment]
> @jurialmunkey There is a small bug though. For example, if you enter in episodes group in Game of thrones, you will see that it shows all the posters from season eight instead of a different poster for each season.

Ah yep. It's because episode groups don't have season numbers -- even if there's a number in the group name like with game of thrones there isn't actually a season number field because they aren't "real" seasons. So the season is getting filled with the season count from the parent tvshow details.

Latest version will stop the count transfering across so you'll just get base tvshow artwork instead for episode groups. No way to get specific artwork for the groupings though because they technically aren't seasons so there's no season number to lookup and there's no consistency in the naming to pull it from the label.

**Comment by matke-84** [comment]
@jurialmunkey
OK. Only now is it giving the wrong information about the number of episodes per season in episodes group. Each states that there are 73 episodes in the case of Game of thrones.

**Comment by jurialmunkey** [comment]
> @jurialmunkey OK. Only now is it giving the wrong information about the number of episodes per season in episodes group. Each states that there are 73 episodes in the case of Game of thrones.

I don't think this was ever correct. TMDb doesn't give counts and the lack of a corresponding Trakt entry for groupings means it isn't possible to lookup

**Comment by jurialmunkey** [comment]
Okay latest should fix the count issue by preventing the Trakt watched data lookup for episode groups. No point doing the lookup anyway as it will be wrong for groupings since we don't have season numbers.

I added a manual count of number of items in the episode group's list since TMDb actually gives all the groupings in the one request. So for episode groups you should get `ListItem.Property(TotalEpisodes)` but you won't get `UnwatchedEpisodes` or `WatchedEpisodes` properties since Trakt doesn't keep grouping data.

**Comment by matke-84** [comment]
@jurialmunkey
But now I have no information about unwatche episodes anywhere. Not just in groups.

**Comment by jurialmunkey** [comment]
> @jurialmunkey But now I have no information about unwatche episodes anywhere. Not just in groups.

Really? It is working correctly for me.

**Comment by matke-84** [comment]
@jurialmunkey 
Really. Tried on few skins.

**Comment by jurialmunkey** [comment]
^ Try that. If you haven't watched an episode then Trakt doesn't keep any data. That will fake a 0 count to differentiate between `None` and `0`

**Comment by matke-84** [comment]
@jurialmunkey Nope. It still doesn't work. Tried version 23 it works.

**Comment by jurialmunkey** [comment]
> @jurialmunkey Nope. It still doesn't work. Tried version 23 it works.

Do you have trakt watched indicators enabled in TMDbH settings?

**Comment by matke-84** [comment]
@jurialmunkey
I turn on that too, but I didn't need that in the versions until the last two. This is about not getting more info about unwatched episodes. Most often in skins it is in the corner of the poster.

**Comment by jurialmunkey** [comment]
> @jurialmunkey I turn on that too, but I didn't need that in the versions until the last two. This is about not getting more info about unwatched episodes. Most often in skins it is in the corner of the poster.

It was incorrect before.

TMDb provides `ListItem.Property(totalepisodes)`
Trakt provides `ListItem.Property(watchedepisodes)`

`ListItem.Property(unwatchedepisodes)` should be `totalepisodes - watchedepisodes`

Without the Trakt data, `watchedepisodes` was incorrectly being given `0` rather than `None`. That meant that `unwatchedepisodes` incorrectly ended up with the total episode count since `total - 0 = total`.

**Comment by matke-84** [comment]
@jurialmunkey
I'm not sure we understand each other. This option exists in all addons, to count the total number of all episodes and then subtract the number when viewed. I'm just using your artic horizon. The number at the bottom of the poster in the circle no longer exists. I don't understand what was wrong when it worked?

**Comment by matke-84** [comment]
@jurialmunkey
![IMG_20220205_032112](https://user-images.githubusercontent.com/74268331/152625260-2658d9d8-27fe-48fd-803a-befe5e49ae27.jpg)
![IMG_20220205_032008](https://user-images.githubusercontent.com/74268331/152625263-d03a55f1-0425-4bbf-b680-9650ad24fd81.jpg)

**Comment by alKODIque** [comment]
@matke-84  It looks like a screen resolution issue... not artwork, I think

**Comment by jurialmunkey** [comment]
> @jurialmunkey I'm not sure we understand each other. This option exists in all addons, to count the total number of all episodes and then subtract the number when viewed. I'm just using your artic horizon. The number at the bottom of the poster in the circle no longer exists. I don't understand what was wrong when it worked?

The number in the circle shows `unwatchedepisodes` not `totalepisodes`.

If there's no data about which episodes you've watched (even if that's 0) then there's no information about how many unwatchedepisodes. The only data is the totalepisodes which is not the correct data to show in that circle.

The only way to get data about how many episodes that you've watched is from Trakt since TMDbHelper doesn't play files itself.

**Comment by matke-84** [comment]
@jurialmunkey
I know this is information about unwatched episodes. If I understand you correctly, all this time it was wrong in tmdb helper and all other addons. Just one more thing I didn't understand. How can I get information on how many episodes I have left to watch? When do I watch the first episode and sync with the trakt?

**Comment by alKODIque** [comment]
Hi!
If it can help,  I get all informations from my trakt account in settings of this screen in TMDbH:

![Screenshot_20220204-214934](https://user-images.githubusercontent.com/49578130/152626200-ff71bcc2-02c4-412a-95cf-929cb6a8444c.png)

I have a local library and everythings work well... But I know that if you are using addons for watching your media, it's possible that scrobbling don't work properly if this addon has not a correct way to obtain TRAKT API informations. For exemple, I've been using a french addon who was not able to scrobble movies informations from my trakt account. Only tv show... It was an addon issue, not TMDbH issue (even with widgets from TMDbH)

**Comment by jurialmunkey** [comment]
> @jurialmunkey I know this is information about unwatched episodes. If I understand you correctly, all this time it was wrong in tmdb helper and all other addons. Just one more thing I didn't understand. How can I get information on how many episodes I have left to watch? When do I watch the first episode and sync with the trakt?

It depends on the addon - e.g. Netflix keeps track of what you've watched locally and even syncs that data back with Netflix - but yes I'd say the majority are incorrectly dumping totalepisodes in there instead.

For TMDbHelper specifically, it doesn't play files itself, so it relies on the end add-on reporting watched status. The main issue is that many video add-ons use player hacks which have the side-effect of preventing Kodi from tracking progress locally so there's no way for TMDbHelper to get that data back other than relying on an external service like Trakt to monitor for changes.

As alKODIque points out, the official Trakt addon from Kodi repo is pretty good at automatically tracking most scenarios, especially for Kodi library files. However, for some video add-ons you will also need to put your Trakt credentials into that specific add-on's settings to get it to track items it plays.

**Comment by matke-84** [comment]
@jurialmunkey 
Ok. I must apologize. I was tired yesterday so I didn't quite understand everything. When I connected to the trakt I got a number of unwatched episodes in seasons. Can we get the number of unwatched episodes of complete tv show not only on seasons?
Also when I turn on the option "get watched indicators from trakt" I lose information about the number of seasons of the whole tv show. My skin uses listitem.property(totalseasons)/(totalepisodes).

**Comment by matke-84** [comment]
@jurialmunkey 
I made a pull request for this ^^^ problem.

**Comment by matke-84** [comment]
@jurialmunkey 
The only thing I noticed is that in the seasons it doesn't count unaired episodes and in the whole tv show it counts.

**Comment by jurialmunkey** [comment]
> Can we get the number of unwatched episodes of complete tv show not only on seasons?

Unwatched count only displays on shows that you've started watching because otherwise there's no way to differentiate between a show in progress and a show that you've never watched.

**Comment by jurialmunkey** [comment]
^^^ FYI that fixes the total episode counts (at least everything I tested was working correctly as far as I could tell)

**Comment by matke-84** [comment]
> Unwatched count only displays on shows that you've started watching because otherwise there's no way to differentiate between a show in progress and a show that you've never watched.

Ok. This makes sense even though I’m used to seeing that information on all tv shows. But then maybe this should be done with season as well. Info about unwatched episodes should appear only if I start watch episode in season or at least in all seasons but only of tv show I start watch. Now if you get into any tv show, seasons show a number of unwatched episodes, and I haven’t started watching any of them. I don't know if this is even possible, I haven't tried but it makes sense to me.

**Comment by jurialmunkey** [comment]
> 

 It is definitely a bit inconsistent but I don't mind so much the counts being all seasons because generally you start from season 1 and go up in order so it's easy to tell where you're up to.

I agree that they probably should be hidden if you haven't started the show at all though. I'll need to track down why that's happening because it uses the same code as for tvshows so it should have the same behaviour.

**Comment by matke-84** [comment]
@jurialmunkey I was tried some things. I manage to hide for tv shows that have not started to be watched but for tv shows that I have started I get an incorrect result. But I have no doubt that you will be able to find a solution.

**Comment by matke-84** [comment]
@jurialmunkey
It seems to me it's work perfectly. Well done my friend. 👌
