### ISSUE TITLE
How do I configureeach  Player properly  what is the proper configuration and how do I get the setveiw stay on the one I like thank you

### ISSUE THREAD

**Issue by Arthur1967** [jurialmunkey/plugin.video.themoviedb.helper#546]

**Comment by jurialmunkey** [comment]
The players that come with Tmdbhelper are already configured correctly. If you are talking about 3rd party players then you'll need to speak to whoever made them as I didn't.

Forced view ids has been request and is currently not supported.

**Comment by Arthur1967** [comment]
Thank you
