### ISSUE TITLE
[Request] Increase widgets number to 100+ or provide a setting.

### ISSUE THREAD

**Issue by cg00001** [jurialmunkey/plugin.video.themoviedb.helper#552]
It makes little sense to use TMDbH for widgets if it only shows a handful. This is worse if you hide watched in widgets.
A setting that could change the number of widgets would solve the problem -even a hard-wired one set to 100+.

**Comment by drinfernoo** [comment]
#213 #151 #240

**Comment by cg00001** [comment]
> #213 #151 #240

OK, sorry I missed those.
