### ISSUE TITLE
Trakt collection Movies/ TV Show as list

### ISSUE THREAD

**Issue by rijsab** [jurialmunkey/plugin.video.themoviedb.helper#554]
Hi,

In library update settings I see all of my Trakt lists. Is it possible to have Trakt Collection Movies and TV Shows showing up as a list? I want to integrate into Kodi library so tmdbhelper can identify better files if I have them in my library or not. 

Thanks.

**Comment by drinfernoo** [comment]
@rijsab You can view your Collections in the add-on, but not sync them to the library.

**Comment by rijsab** [comment]
Yes aware of this option however the reason why I am asking for is that the local library indicator does not work if I have a widget pulled from Trakt list and only works for imdb widgets. So let's say a Trakt list called 4k Movies.. not possible to see if I have these in my library or not. 

Edit. I have made a test.. when I integrate Trakt list 4K movies,  all of these 4K Movies are showing a local library icon as it believes I own these which is not. However with Trakt Collection I know for sure I own these files and local library icon will indicate to me which ones and which not and regardless if this is a widget from Trakt tmdbhelper or IMDB tmdbhelper

**Comment by jurialmunkey** [comment]
Why aren't the files that you already own already in your library?

**Comment by rijsab** [comment]
Hi,
Yes they are but as said the local library indicator on posters of widgets does not work for trakt lists unless I import these lists as such that I own these files. However I do not own all files in a trakt list, except the files in my Trakt Collection. I can show you an example?

**Comment by jurialmunkey** [comment]
Sounds like an XY problem https://en.wikipedia.org/wiki/XY_problem

So the real issue here is not that you want to add your collection to the library, but that items in Trakt lists are not correctly getting the DBID from the item in the library added to them (and thus are not showing a library indicator).

EDIT: Just did a test and can confirm a bug with Trakt lists not getting the DBID. This has nothing to do with needing to add your collection to the library.

**Comment by jurialmunkey** [comment]
@rijsab - Please test latest github version. That should fix the missing DBID issue on Trakt user lists for items already in the library.

Make sure you have the TMDbH setting "Get additional details from the local Kodi library database" enabled.

![Honeyview_screenshot00049](https://user-images.githubusercontent.com/4618719/131245089-212863a5-79c0-4679-a2e2-ad3583722c84.jpg)

**Comment by rijsab** [comment]
Hi,

Thanks for the quick update. I have tested this and seems to work for movies lists. However for TV shows the indicators (showing amount of episodes) is showing for all files of the widget, even if not in my local library and therefor not able to play these files of course. So I can only find out when playing the file and the context menu shows up from where to play. 

Cheers. 

Edit: with the new update my Kodi crashes quiet often now and no any other changes have been made since.

**Comment by jurialmunkey** [comment]
Episode counter shows you total number of unwatched episodes the exist for the show/season. It doesn't count how many shows you've got in your library.

**Comment by jurialmunkey** [comment]
Disable "Accounts > Get watched indicators from trakt" and you will be able to see which episodes in a season are in your library.

**Comment by rijsab** [comment]
Hi,

Thanks - I am using Trakt lists to search my library what to watch and therefor want to see if I have this in my library. So basically similar how movies are working. Fully understand I can use smart playlist but I find it much easier to use Trakt for my set up and hope you will consider this.

Edit: I had disable watched indicators and still all unwatched indicators are showing in my widget and therefor difficult to see which TV Show I own.

**Comment by rijsab** [comment]
Hi,

Can this be reopened please? I really would appreciate if the local library indicator is showing for TV Shows of Trakt lists as well and not only on episode level. Thanks!!

**Comment by jurialmunkey** [comment]
No. The total episode count is the number of episodes in the season folder. The unwatched count subtracts number of watched episodes from total episode count. Unwatched + Watched has to equal Total.

**Comment by rijsab** [comment]
Unfortunately pal, your decision but I still believe to have the collection list as an option as well because than the local library indicators for TV Shows are working instead of on episode level. 

For example.. I have a list in Trakt for 90ths TV Shows organized per rating however I do not own all files. So if I download this list Kodi will think I own all of these and is showing the library indicator. So for me there is no purpose to download this list. If I make this list as a widget the indicators are also not working. However if I download my collection.. make the list again as a widget the indicators are working correctly for the files I own and leaves the other ones without indicator. Hope this gives you a better idea on what I am trying to achieve.
