### ISSUE TITLE
[REQUEST] add lists from other users on Trakt

### ISSUE THREAD

**Issue by dreulavelle** [jurialmunkey/plugin.video.themoviedb.helper#556]
Would like to distribute builds with my Trakt lists, but don't want to be signed in. A setting in the menu to specify a user-id or list-id would be great!

**Comment by dreulavelle** [comment]
Actually figured out how to do this with what you have already.. You can search lists and search for a random list.. from there you can favorite any of them... and in your favorites.xml file it'll generate what its supposed to look like for an ActivateWindow function.. from there you can just change the values in that url for your list-slug/list_name and user-slug. After tweaking that, I can create my own links to my own personal lists.. Perfect!

**Comment by jurialmunkey** [comment]
FYI, the user and list slug can be pulled directly from the web url. For example for this list `https://trakt.tv/users/canconfirm/lists/shut-up-and-watch` the user slug is `canconfirm` and the list slug is `shut-up-and-watch`

Also, if it is someone else list, you can like the list on trakt.tv (open the list and click the heart icon). Then it will show in your liked lists folder in TMDbH and you can get the folderpath that way.
