### ISSUE TITLE
People search in Arctic horizon not working. 

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/plugin.video.themoviedb.helper#557]
I have the DefaultSearch-TMDBPeople set in AH search list and when I search an actor it pulls up a list of actors like it is supposed to but when I click on the actor, I get the popup with "Cast in movies, Cast in TV shows, Crew in movies, Crew in TV shows, Images" but when I select one of the options, nothing happens. When I go in TMDBhelper and search it works properly. Am I doing something wrong? Is there a fix for this?

**Comment by drinfernoo** [comment]
https://github.com/jurialmunkey/skin.arctic.horizon/issues/434

**Comment by jabir15** [comment]
Similar issue. Though it works if you go through the context menu (C) --> "Browse lists" --> "Cast in movies...". So, not a huge issue for me, but hopefully it gets fixed.

I have checked the log file. The error seems to be this
```
DEBUG <general>: Activating window ID: 10025
INFO <general>: Activate of window '10025' refused because there are active modal dialogs
```

Debug Log file: [kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/7139965/kodi.log)

**Comment by jurialmunkey** [comment]
Ah weird, Kodi doesn't like opening another window if the busy dialog is active. Easy fix.

**Comment by derrone015** [comment]
how to add a general search artic horizon skin? I tried the global search but didn't work
