### ISSUE TITLE
Having trouble with my player

### ISSUE THREAD

**Issue by mrXoo** [jurialmunkey/plugin.video.themoviedb.helper#559]
Hi there,

Im having an issue with my player. There is probably a very easy fix.

Im trying to put brackets instead of the URL encoding

Basically so far I have

"{clearname|replace(%28,x)|replace(%29,x)}", that prints showname x2018x

so I need showname (2018)

**Comment by mrXoo** [comment]
sorry im writing this for a meta player so the format will be different.
Maybe @drinfernoo  can help??

**Comment by drinfernoo** [comment]
I don't think that I would be able to, no. 

If you're referring to OpenMeta, the format does not give any type of "advanced formatting" options like TMDbHelper does, nor is the addon supported or maintained any longer.

Check here for information on making TMDbHelper players: https://www.github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

**Comment by jurialmunkey** [comment]
@mrXoo - Are you trying to write a player for OpenMeta or TMDbH?

If you're writing a player for TMDbH, getting `Showname (Year)` it is as simple as `"{showname} ({showyear})"`
If you're trying to get `Showname xYEARx` instead you'd use `"{showname} x{showyear}x"`

If you're writing a player for OpenMeta, you're in the wrong place.
