### ISSUE TITLE
[ISSUE MATRIX]  trakt manage functions not workin in kodi matrix

### ISSUE THREAD

**Issue by marduklev** [jurialmunkey/plugin.video.themoviedb.helper#563]
the action usage descrpided here 

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Trakt-Management-Functions

is workin flawless in kodi leia , but does nothing in matrix version.

found nothing meaningfull in the logs, helper debug setting was enabled.
it just do nothing.

EDIT: shipped context fuction working like it should

**Comment by jurialmunkey** [comment]
These changed quite a long time ago (v4) - I just forgot to update the wiki. If it is still working for you on Leia, then I imagine that you're using an old version (Matrix version on official repo is up to date but Leia version is very old and out of date -- if you're still using Leia, you should use the version on my repo)

All the Trakt sync options have been combined into a single RunScript:

Movies
```
RunScript(plugin.video.themoviedb.helper,sync_trakt,type=movie,tmdb_id=ID)
```

Tvshow / Episode
```
RunScript(plugin.video.themoviedb.helper,sync_trakt,type=tv,tmdb_id=ID)
RunScript(plugin.video.themoviedb.helper,sync_trakt,type=tv,tmdb_id=ID,season=SEASON,episode=EPISODE)
```

TYPE must be either `movie` or `tv` (specify season/episode numbers for specific episode).

If you don't have tmdb_id you can specify IMDB ID or a Title query params to do a lookup (if episode use ListItem.TvShowTitle for query not Title)
`query=$INFO[ListItem.Title],imdb_id=$INFO[ListItem.IMDBNumber]`

**Comment by marduklev** [comment]
Ak, great .
Thanks for fast response.
Tested on now works like a charm ;-)

I sticked with the Versions provided by Kodi repo,means 
Leia version="2.4.36" ( still working without issues )
Matrix version="4.3.0" 

Thanks and have a nice day ;-)
