### ISSUE TITLE
Movies from Trakt watchlist not marked as watched on Trakt

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#564]
Hi,

I have recently started using the watchlist list for movies from Trakt as a widget and I realised, watched movies are not marked as watched on Trakt after watching them/marking them as watched. Currently you have to mark them as watched manually by going to Trakt options. Is this the normal behaviour? Could it be player related?

Thanks.

**Comment by drinfernoo** [comment]
It is definitely player-related. The add-on that gets used to play is what is ultimately responsible for dealing with Trakt.

**Comment by juanma-cvega** [comment]
Ok, so I guess the problem comes from the player only marking things as watched when they are in the Kodi library and from there it's the Trakt addon that does the rest. 
But even when using the Arctic Horizon skin, when I mark a movie as watched from a TMDBHelper widget that pulls the list from Trakt watchlist, it still doesn't mark the movie on Trakt. Is this still the expected behaviour? Because in that case, marking anything outside of the Kodi library wouldn't be reflected on Trakt (unless using the Trakt options which is a bit slower)

**Comment by drinfernoo** [comment]
If you are using the standard "Mark as Watched" context menu item, that only affects the Kodi library. You'll need to use the "TMDBHelper Trakt Menu -> Mark as watched" option to mark it on Trakt.

**Comment by juanma-cvega** [comment]
Ok, I was hoping a more integrated could be possible but I guess I'll just keep using the Trakt options. I'm closing the issue now that this is clear.
