### ISSUE TITLE
Widget Playlist issue

### ISSUE THREAD

**Issue by cgtjr1** [jurialmunkey/plugin.video.themoviedb.helper#565]
Sorry I posted in wrong thread. 

I am having an issue with a new setup. After I install TMDB Helper and sync my trakt lists, it creates the playlists of my trakt lists. they work properly and are all there, but when I go to set up my widgets and go into the playlists thru the skin settings it only shows 5 of the 12 playlists. I have wiped and done a complete fresh install and it is still happening. It work fine on my main setup, this is a secondary setup (for my dad). We have everything the same except for one. Our local (external HDD) files are different. I have a Movies folder containing all files and a TV one the same way. He has a Movie folder with subfolders by genre and those contain the files. I don't know if this contributes or not but it's the only difference. It has all the files in the playlists it creates...I just can't see them when doing the widget set up. We both are running Matrix on the same model of Nvidia Shield.

**Comment by drinfernoo** [comment]
What skin are you using?

**Comment by drinfernoo** [comment]
Actually, it probably doesn't matter... locally stored movies should be organized as laid out here: https://kodi.wiki/view/Naming_video_files/Movies

Most likely that's why they're not working out.

**Comment by cgtjr1** [comment]
Sorry I should have said that. I'm using Arctic Zephyr Reloaded, which is why I came to jurial munkey.. I also installed Titan Bingie Mod and had the same issue.

I fear that the folders may be the issue, but it works fine in every other way. I plays the correct file from any list and/or playlist in the skin. So that would seem like it has the correct pathways....but when im in Widget set up it only shows a few of the playlists available....the ones it does work fine. If it was a issue with the local files than none of it would work, correct?

**Comment by cgtjr1** [comment]
I under stand Reloaded is a mod and not yall, but it happened on AZ2 also. And since it's moded on your framework I came here.

**Comment by drinfernoo** [comment]
The items added by TMDbHelper's library integration function are not added into the same folders as your normal local files, so I don't believe that those other folders will behave the same as ones created by TMDbHelper.

**Comment by jurialmunkey** [comment]
I assume you're talking about using SkinShortcuts to customise home menus/widgets. Are you going to `Videos > Playlist >` to try to add the playlists? Because all mine show there.

**Comment by cgtjr1** [comment]
Yes that's ccorrect.it works fine on one of my setups...but on this new setup it only shows 4 of the 12 playlists. So weird. Both setups are exact same hardware and build. 

It would make sense if the playlists weren't being generated by tmdbhelper...but they are and function properly. I've wiped it and did a fresh install with the same results. 

The only difference in my two setups is the one I'm having problems with, the hard drive has moviefolder >genre folder>files...my one that works is movie folder>files. But koid scraped everything fine and so did tmdbhelper. All the folders are labeled correctly...I guess somehow it's the issue but it doesn't make sense why. Since tmdbhelper playlists are correct and play the files when I select them.

**Comment by jurialmunkey** [comment]
Do you use Kodi profiles? Playlists are saved to the currently active profile's folder - so it's possible that some of the playlists were saved elsewhere

Default playlist folder is
`.kodi/userdata/playlists/videos`

But if you use profiles it will be something like:
`.kodi/userdata/profiles/{profile-name}/playlists/videos`

You could check the playlist folders on your harddrive and see whether they are all in the same folder. That's the only thing I can think of -- that SkinShortcuts is only looking at one of the playlist folders (i.e. only master or only profile) whereas when you go via normal Kodi playlist section it is combining both.

The only other thing I can think of is some sort of strange character in the playlist (either the name or one of the items in it) causing an issue - still, that would be odd considering both setups are the same hardware and OS.
