### ISSUE TITLE
Widget Artwork Issue

### ISSUE THREAD

**Issue by JC253** [jurialmunkey/plugin.video.themoviedb.helper#566]
Hello Jurialmunkey,
Sorry about posting that issue on your repo, didn't even realize I wasn't on TMDb Helper page. 
Anyhow, the settings I showed you on that post are the settings I've used for quite some time now, with 2 different skins and they've always worked fine, even the widget artwork and using the settings I use. I did however go into TMDb Helper settings after seeing your comment, and turned the widget setting on, cleaned out all old thumbnails and cleaned everything out, opened back up, and same issue. I took some fresh screenshots just now to show you again the behavior I'm experiencing with this. Also, I should point out, I've been using those settings with this same setup for over 6 months now without issue. The widget artwork issue just started a few days ago. Appreciate any help or insight you may have. Thanks.

I've attached a few screenshots to show the behavior of the widgets in different sections. Again, this has been working fine up until a few days ago (the 25th to be exact.) Thanks again.

![Screenshot (219)](https://user-images.githubusercontent.com/79684237/135394862-879baa64-69cd-4fb3-b478-335cea082d1f.png)

![Screenshot (217)](https://user-images.githubusercontent.com/79684237/135394915-99effec0-348f-4fc4-81d4-1368e8b20935.png)

![Screenshot (223)](https://user-images.githubusercontent.com/79684237/135395005-c60c5e3d-9b56-4f6c-8e6f-033fbdbcde65.png)

![Screenshot (224)](https://user-images.githubusercontent.com/79684237/135395029-6190821e-3d65-4964-a323-32f155894e33.png)

![Screenshot (225)](https://user-images.githubusercontent.com/79684237/135395069-60da4819-282d-4871-9acf-cb43331813f2.png)

**Comment by JC253** [comment]
Also, the artwork does eventually load, but it takes a few minutes. So once they're cached it's ok, but when someone installs my setup they are gonna see the widget artwork missing. Also have a teammate who was experiencing the same issue on the 25th when mine started, with his setup that uses a different skin but he's in Greece, and his widget artwork was working the next day, and he doesn't use any of the fanart settings.

**Comment by jurialmunkey** [comment]
Wait so you're saying the artwork does load? That's just a connection problem then - once the plugin content loads (ie once you see items on screen) TMDbH is no longer active. All it does is provide the url to the image as an artwork property of the listitem. Then when kodi tries to display the image for that artwork property, kodi will download it from the url and cache it. 

It taking time to download has absolutely nothing to do with TMDbH - that's entirely to do with the website server,  your connection speed and kodi.

If there was no image url being attached to the item to load, that's a different story. But if the images do eventually load then TMDbH is working correctly.

**Comment by JC253** [comment]
Yes, they do eventually load, after a few minutes. I just thought it had to do with TMDBH since my teammate was also having the problem and doesn't use fanart settings. So your saying this is on fanart.tv's end, correct?

**Comment by jurialmunkey** [comment]
> Yes, they do eventually load, after a few minutes. I just thought it had to do with TMDBH since my teammate was also having the problem and doesn't use fanart settings. So your saying this is on fanart.tv's end, correct?

If the images load eventually but just take time then that's an issue on the server's end (or a Kodi issue). Images come from both fanart.tv and themoviedb.org so it could be either website - the only way to know is to inspect the listitem artwork properties.

TMDbH is just putting a URL like https://fanart.tv/fanart/tv/121361/showbackground/game-of-thrones-4fd5fa841ac32.jpg into `$INFO[ListItem.Art(Fanart)]` -- It's just the same as how when you see this comment you haven't downloaded the image. The image only gets downloaded after you click the link.

Basically it works like this:
- TMDbH requests info from the API and the API returns json formatted text. [Here's an example response from the fanarttv API.](https://gist.github.com/jurialmunkey/5fb96fb6732405be18b6aa71b4e47624)
- TMDbH adds that text data to the relevant properties on the listitem. Once it has all items in the list, it gives the list to Kodi
- Kodi displays the list according to how it is defined in the Skin. For example, a Skin will put `$INFO[ListItem.Art(Fanart)]` as the texture for an image control to tell Kodi to draw an image on screen using the url stored in each listitem's Art(fanart) property.
- When the image control is onscreen, Kodi will download the image to display it (once it's downloaded once it will cache the image locally for quicker future access)

**Comment by JC253** [comment]
Sorry for the late reply. I appreciate all the info. Still pretty new to this so I'll see what I can do in terms of figuring out where the issue is coming from and go from there. Thanks again!
