### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by WernerAUT** [jurialmunkey/plugin.video.themoviedb.helper#567]
i made a german translation, but i can't add to github, so could someone add the translation please.

https://www.file-upload.net/download-14709044/resource.language.de_de.zip.html

​​​​​​​Werner

**Comment by jurialmunkey** [comment]
Awesome, thanks! I've added the translation.

**Comment by WernerAUT** [comment]
Haha that was fast, thanks for adding it
