### ISSUE TITLE
API_URL Issue

### ISSUE THREAD

**Issue by zhiyu-fly** [jurialmunkey/plugin.video.themoviedb.helper#569]
Hi @jurialmunkey.
Is there any way to chang API_URL in Kodi\addons\plugin.video.themoviedb.helper\resources\lib\tmdb\api.py?
I want to use 'https://api.tmdb.org/3' instead of https://api.themoviedb.org/3'.
But just change this file, the skin goes wrong.
Thanks in advance. 😀

**Comment by jurialmunkey** [comment]
Why are you trying to change the api url?

**Comment by zhiyu-fly** [comment]
https://api.themoviedb.org/ can't connect，but https://api.tmdb.org/ runs well

**Comment by jurialmunkey** [comment]
> 
> 
> https://api.themoviedb.org/ can't connect，but https://api.tmdb.org/ runs well

Whatever is put in API_URL is the base url used for the api. It doesn't do anything special it is just joins `API_URL` to the `request`.  If you changed API_URL to api.tmdb.org and it didn't work, then it doesn't work.

api.tmdb.org just redirects to api.themoviedb.org anyway. This sounds like you have either a DNS, VPN or proxy issue and is nothing to do with TMDbHelper.
