### ISSUE TITLE
A little help with IMDB Trailers

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#571]
So I had an IMDB Trailers player working with TMDBH. Its a really useful player. It stopped working in the last couple days. The IMDB Trailers addon still works and so does the search. Maybe somebody can help get this player working again. Thanks, heres the player code: `{
    "name": "Watch Trailer Now",
    "plugin": "plugin.video.imdb.trailers",
    "priority": 1,
    "play_movie": [
        "plugin://plugin.video.imdb.trailers/?action=search",
        {
            "keyboard": "{title}"
        },
        {
            "title": "{title}"
        }
    ],
    "is_resolvable": "false"
}`

**Comment by drinfernoo** [comment]
Have you tried the one that is bundled with the add-on? The only difference I see immediately is that the `is_resolvable` flag isn't set in the bundled one.

**Comment by JayDee696969** [comment]
> Have you tried the one that is bundled with the add-on? The only difference I see immediately is that the `is_resolvable` flag isn't set in the bundled one.

Hey bud, thanks for responding. Yea, I tried without the resolve flag and it still isnt working. Im guessing an addon change to IMDB trailers broke it? Have you tried it? Is it working for you?

**Comment by drinfernoo** [comment]
I haven't tried it. Just a quick glance and thought I'd see if that helped. If I get a chance, I'll debug it soon.

**Comment by JayDee696969** [comment]
Yea, I tried it on a stock Kodi 19.2 install, and a fresh install of TMDBH and using bundled players. Same issue. It just blinks the keyboard search and goes back to the players menu.. *Edit* full Log attached below..

**Comment by JayDee696969** [comment]
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/7361214/kodi.log)

**Comment by drinfernoo** [comment]
I'm seeing the same (or similar, at least) behavior, using the bundled player, which does appear to still be the accurate path...

Choosing the "IMDb Trailers" player does pop up the keyboard, and the correct title is entered, but the player dialog does indeed pop back up after that. Curiously, if I back out of that dialog, the folder from IMDb Trailers does open for the results, but is immediately "canceled out of", and I land back in TMDb Helper again.

I looked a bit and came up with this player (which I think works interestingly :wink:), but still has the issue of the player dialog popping back up again:
```json
{
    "name": "IMDb Trailers",
    "plugin": "plugin.video.imdb.trailers",
    "priority": 500,
    "play_movie": [
        "plugin://plugin.video.imdb.trailers/?action=search_word&keyword={title}",
        {"dialog": "True"}
    ],
    "is_resolvable": "true"
}
```
Maybe @jurialmunkey has an idea why the dialog keeps popping back up afterwards 🤔

**Comment by JayDee696969** [comment]
Thanks Drinfernoo, At least it works for now. It just doesnt auto play the first Trailer on the list, but at least it works.

**Comment by JayDee696969** [comment]
Drinfernoo, think I figured it out! I did this and now it works as expected, try it out.  

`{
    "name": "Watch Trailer Now",
    "plugin": "plugin.video.imdb.trailers",
    "priority": 1,
    "play_movie": [
        "plugin://plugin.video.imdb.trailers/?action=search_word&keyword={title}",
        { "keyboard": "{title}" }, { "title": "{title}" } ],
    "is_resolvable": "True"
}`

**Comment by jurialmunkey** [comment]
Ah yep, looks like the IMDb trailers addon got updated a couple of days ago. 

Player updated to work with the new version.
