### ISSUE TITLE
Specific show wrong Trakt ID returned

### ISSUE THREAD

**Issue by henryjfry** [jurialmunkey/plugin.video.themoviedb.helper#573]
When attempting to play new episodes of the CW show "4400" (ie the reboot of "The 4400"), TMDB helper is passing the wrong trakt ID to Seren:
```
2021-10-28 19:09:02.340 T:5658     INFO <general>: [plugin.video.themoviedb.helper]
                                                   lib.container.router - Attempting to play item
                                                   {'info': 'play', 'tmdb_id': '127581', 'season': '1', 'episode': '2', 'tmdb_type': 'tv'}
2021-10-28 19:09:02.343 T:5658     INFO <general>: [plugin.video.themoviedb.helper]
                                                   TMDbHelper - 00 Constructing Players...
2021-10-28 19:09:02.554 T:5658     INFO <general>: [plugin.video.themoviedb.helper]
                                                   TMDbHelper - 33 Retrieving Item Details...
2021-10-28 19:09:02.614 T:5658     INFO <general>: [plugin.video.themoviedb.helper]
                                                   TMDbHelper - 66 Building Player Dialog...
2021-10-28 19:09:03.253 T:5658     INFO <general>: [plugin.video.themoviedb.helper]
                                                   TMDbHelper - Done!
2021-10-28 19:09:03.304 T:2602     INFO <general>: Loading skin file: DialogSelect.xml, load type: KEEP_IN_MEMORY
2021-10-28 19:09:08.079 T:5704     INFO <general>: initializing python engine.
2021-10-28 19:09:08.302 T:5658     INFO <general>: [plugin.video.themoviedb.helper]
                                                   lib.player - playing path with xbmc.Player()
                                                   plugin://plugin.video.seren/?action=getSources&smartPlay=true&source_select=false&forceresumecheck=true&actionArgs=%7B%22episode%22%3A%202%2C%20%22item_type%22%3A%20%22episode%22%2C%20%22season%22%3A%201%2C%20%22trakt_id%22%3A%204400%7D
2021-10-28 19:09:08.303 T:5658     INFO <general>: CPythonInvoker(93, /home/osmc/.kodi/addons/plugin.video.themoviedb.helper/plugin.py): script successfully run
2021-10-28 19:09:09.942 T:5658     INFO <general>: Python interpreter stopped
2021-10-28 19:09:14.114 T:5704     INFO <general>: SEREN (24): Inserting Shows into sync database: 1
2021-10-28 19:09:14.891 T:5704     INFO <general>: SEREN (24): Inserting seasons into sync database: 3
2021-10-28 19:09:15.107 T:5704     INFO <general>: SEREN (24): Inserting episodes into sync database: 52
2021-10-28 19:09:17.077 T:5704     INFO <general>: SEREN (24): Seren, Running Path - {'action': 'getSources', 'smartPlay': 'true', 'source_select': 'false', 'forceresumecheck': 'true', 'action_args': {'episode': 2, 'season': 1, 'trakt_id': 316855, 'trakt_show_id': 4400, 'mediatype': 'episode'}}
```
The plugin url passed to seren:
plugin://plugin.video.seren/?action=getSources&smartPlay=true&source_select=false&forceresumecheck=true&actionArgs=%7B%22episode%22%3A%202%2C%20%22item_type%22%3A%20%22episode%22%2C%20%22season%22%3A%201%2C%20%22trakt_id%22%3A%204400%7D

Has used the show name (slug?) instead of the valid trakt ID as you can see from the seren output:

{'action': 'getSources', 'smartPlay': 'true', 'source_select': 'false', 'forceresumecheck': 'true', 'action_args': {'episode': 2, 'season': 1, 'trakt_id': 316855, 'trakt_show_id': 4400, 'mediatype': 'episode'}}

With the trakt ID "4400" belonging to some 80's show I've never heard of.

It is passed to tmdbhelper correctly and can accurately return the correct information about the episode to the select dialog (so it shows the correct show name, episode number and episode name in the select dialog).
But when it produces the plugin url it is some how not using the actual trakt id for the show.

So above i've attempted to play S01E02 (which I know is not available) but the same thing happened with S01E01 which I watched last night, once i made a change to the player file to pass the tmdb id and then made a change to seren to lookup its trakt DB and return the trakt id from the tmdb id passed to it from tmdb helper.

So im pretty sure its something to do with the fact that the show has a numerical name/slug:

{'plays': 1, 'last_watched_at': '2021-10-27T21:27:47.000Z', 'last_updated_at': '2021-10-27T21:27:47.000Z', 'reset_at': None, 'show': {'title': '4400', 'year': 2021, 'ids': {'trakt': 173509, 'slug': '4400', 'tvdb': 396564, 'imdb': 'tt9319770', 'tmdb': 127581, 'tvrage': None}}, 'seasons': [{'number': 1, 'episodes': [{'number': 1, 'plays': 1, 'last_watched_at': '2021-10-27T21:27:47.000Z'}]}]}

However why tmdbhelper doesnt just return response['ids']['trakt'] and instead parses a numerical slug as the actual trakt ID, I have no idea.

**Comment by drinfernoo** [comment]
That sounds more like an issue with the player.

**Comment by henryjfry** [comment]
Its not, its a tmdbhelper issue.  The problem is here:
~/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/player/details.py

Line 27:
trakt_slug = trakt_api.get_id(id_type='tmdb', unique_id=unique_id, trakt_type=trakt_type, output_type='slug')

Changing this line to:
trakt_slug = trakt_api.get_id(id_type='tmdb', unique_id=unique_id, trakt_type=trakt_type, output_type='trakt')

It returns the actual trakt ID, which is then used to do the lookup and returns the correct details when it then does the details lookup:

details = trakt_api.get_details(trakt_type, trakt_slug, extended=None)

The way its currently setup becasue the slug for this show is a number I think it determines that the supplied slug is actually the trakt ID and looks that up, becasue there isnt anything specified in the trakt api lookup function to say it definetly is a slug and not an ID number which has been provided.

Although I couldnt exactly figure out after "get_id" in the trakt "api.py" where it then decides whether or not to do a slug lookup or an ID lookup as I didnt particularly fancy trying to trace through the cache where the actual lookup occurs.

**Comment by henryjfry** [comment]
I mean did you not see this line in my log:

2021-10-28 19:09:08.302 T:5658     INFO <general>: [plugin.video.themoviedb.helper]
                                                   lib.player - playing path with xbmc.Player()
                                                   plugin://plugin.video.seren/?action=getSources&smartPlay=true&source_select=false&forceresumecheck=true&actionArgs=%7B%22episode%22%3A%202%2C%20%22item_type%22%3A%20%22episode%22%2C%20%22season%22%3A%201%2C%20%22trakt_id%22%3A%204400%7D
2021-10-28 19:09:08.303 T:5658     INFO <general>: CPythonInvoker(93, /home/osmc/.kodi/addons/plugin.video.themoviedb.helper/plugin.py): script successfully run

This is what is passed by tmdbhelper "trakt_id%22%3A%204400%7D"
What are the chances that a show "4400" also has a trakt ID "4400"?

If tmdbhelper passes the wrong trakt ID to seren, its a tmdbhelper problem.

**Comment by drinfernoo** [comment]
After looking into it more, it does appear to be an issue not with player, but technically with Trakt... And I can replicate it with other shows as well.

The issue is that the *slug* for the show is just numbers, whereas the Trakt API (if passed a strictly numerical value) expects the value to be an ID, not a slug.

I can replicate this by trying to play any episode of "24", as the slug is `24`, but that ID corresponds to "Presidio Med".

It does seem like a better approach would be to pass the ID, rather than the slug, as you mentioned, but that would likely need some further testing just to be safe in the end.

**Comment by jurialmunkey** [comment]
Thanks guys. drinfernoo is on the money - it's a Trakt API issue. The [API docs](https://trakt.docs.apiary.io/#reference/movies/summary/get-a-movie ) specify that the id param in the call will accept a string containing "Trakt ID, Trakt slug, or IMDB ID" -- however, there's no param to specify the type of ID being passed and the docs don't specify what happens if there's an overlap between IDs and slugs.

What's worse is the example they provide in the docs (`Example: tron-legacy-2010`) is a Trakt slug so the expectation is that slugs are preferred (when based upon what we're seeing here, it actually looks like it prefers IDs first and only checks against slugs as a fallback).

**Comment by henryjfry** [comment]
Yeah I had a look at the API docs as I thought that there was an individual slug lookup method but I think thats just for lists and such, not for individual items.

So I think either just looking up the trakt ID, or passing the slug and ID as separate variables and defaulting to the ID in the trakt API call if the slug is numeric?

**Comment by jurialmunkey** [comment]
> So I think either just looking up the trakt ID, or passing the slug and ID as separate variables and defaulting to the ID in the trakt API call if the slug is numeric?

Looking up the Trakt ID instead of the slug should be enough (which is what drinfernoo's PR does). I'd expect everything that has a slug will also have an ID. Plus it's the same API call to get either (just different keys in the returned json).

Only reason I used slugs originally was because that's what the examples in the API docs used. Makes no difference from the TMDbH side of things which one is used.

**Comment by henryjfry** [comment]
Yeah fair enough.
