### ISSUE TITLE
Trying to add Hulu

### ISSUE THREAD

**Issue by MultiversalTraveler** [jurialmunkey/plugin.video.themoviedb.helper#575]
Hello, I would like to add slyguy's Hulu addon to the list of players, but I don't know what I'm doing wrong.  I created the file direct.hulu.json in the players folder, and formatted it like the Netflix addon, like this:

{
    "name"              : "Hulu",
    "plugin"            : "slyguy.hulu",
    "priority"          : 100,
    "is_resolvable"     : "true",
    "assert"            : {
                            "play_movie":       ["title", "year"],
                            "play_episode":     ["showname", "season", "episode"],
                            "search_movie":     ["title"],
                            "search_episode":   ["showname"]
                          },
    "play_movie"        : [
                            "plugin://slyguy.hulu/directory/search/search/add/",
                            {"keyboard": "Select"},
                            {"keyboard": "{title}"},
                            {"title": "(?i).*{title}.*", "year": "{year}"}
                          ],
    "play_episode"      : [
                            "plugin://slyguy.hulu/directory/search/search/add/",
                            {"keyboard": "Select"},
                            {"keyboard": "{showname}"},
                            {"title": "(?i).*{showname}.*"},
                            {"return": "true", "season": "{season}", "episode": "{episode}"},
                            {"season": "{season}"},
                            {"season": "{season}", "episode": "{episode}"}
                          ],
    "search_movie"      : [
                            "plugin://slyguy.hulu/directory/search/search/add/",
                            {"keyboard": "Select"},
                            {"keyboard": "{title}"}
                          ],
    "search_episode"    : [
                            "plugin://slyguy.hulu/directory/search/search/add/",
                            {"keyboard": "Select"},
                            {"keyboard": "{showname}"}
                          ]
}

It shows up in the players menu with the version number and everything, but It won't play episodes that I know are on Hulu (just defaults to the Elementum file for the show I've added to the library).  The "Search Hulu" actually opens the main menu of the Hulu addon, but does nothing else.  I know I'm dumb for missing something obvious, but any help would be appreciated.  Thanks.

**Comment by jurialmunkey** [comment]
Your search path will be wrong. You need to go into the addon and inspect the `$INFO[ListItem.FolderPath]` for the search command to find out what the path is (or call the search and then look at `$INFO[Container.FolderPath]`).

I don't use Hulu as I'm not located in the US but I suspect the plugin will likely have a similar layout to SlyGuy's other InputStream based plugins. The BiNGe player (it's basically FOX/HBO in Australia) would be a good base to use as that's another SlyGuy plugin

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/matrix/resources/players/binge.json

**Comment by MultiversalTraveler** [comment]
Thanks!
