### ISSUE TITLE
Error Contents: name 'trakt_slug' is not defined

### ISSUE THREAD

**Issue by hindsight2021** [jurialmunkey/plugin.video.themoviedb.helper#577]
Error:

When selecting any installed player or attempting to load list of players in any active widget.
Same event(s) when selecting context menu >> select player.

Brand now Kodi 19.3 install, Nvidia Shield 2019 Pro.

Trakt authed, players installed, updated.

Debug Log https://pastebin.com/RVia3Dcp

Example error, line 1030 - repeated a lot in the log (TMDBH debugging is enabled).

Error Type: <class 'NameError'>
Error Contents: name 'trakt_slug' is not defined

----------------

Have tried: Remove/reinstall, ZIP install from latest release, no change(s).
Videos playback from their respective addons without issue.

Thank you.

**Comment by drinfernoo** [comment]
Ohh, that's my bad! I recently made a PR to fix a different player issue, and caused this one in the process 😅 I've opened a new one to fix this as well.

**Comment by hindsight2021** [comment]
> Ohh, that's my bad! I recently made a PR to fix a different player issue, and caused this one in the process 😅 I've opened a new one to fix this as well.

Awesome! Thx
