### ISSUE TITLE
[Bug?] Missing Artwork

### ISSUE THREAD

**Issue by henryjfry** [jurialmunkey/plugin.video.themoviedb.helper#58]
I have had issues with missing artwork in widgets and general sections in the addon. I had thought it might have been a problem with the best cached version of art being "none" for certain items.
However after reinstalling the addon on the latest update it was definitely using the wrong banners/thumbs within the addon and not loading clearlogos within widgets for art which was already cached.

So i've got a fairly long and rambling post with an overview of my problem here:
https://www.reddit.com/r/Addons4Kodi/comments/etugvk/tmdb_helper_fanarttv_got_a_solution_but_i_have/

But to fix this i have made changes to "def get_sortedlist(self, items):" within container.py as per the following github gist:

https://gist.github.com/henryjfry/6b8beca3b5872991b31642d063e770b8

With the "poster" item type having been added to:
listitem.py
https://gist.github.com/henryjfry/4856bc5e7768974092130bd6f9ef179d

plugin.py
https://gist.github.com/henryjfry/5b999b1629d66e1b0b10315a4ff7f7cd

fanarttv.py
https://gist.github.com/henryjfry/1ce04314bd9a7d7718ac052bd6ef86ab

The may be some extraneous changes in those gists which are unnecessary, i can upload more concise changes if anything isn't clear enough.

I've also made some changes to player.py to serve more artwork to links i play externally to tmdbhelper from a context menu item:
https://gist.github.com/henryjfry/b898a9580bb032c38a48a1059492babc

Let me know if you have any queries.
Cheers.

**Comment by jurialmunkey** [comment]
> ... it was definitely using the wrong banners/thumbs within the addon and not loading clearlogos within widgets for art which was already cached.

What do you mean by "wrong" banners / thumbs? I haven't had any issues with incorrect artwork being retrieved.

If your cache gets messed up, you can always delete simplecache.db from the simplecache folder of addons_data.

>Now i have had my fanarttv api keys setup since I installed the addon. However i had got messages about the api key not being setup and then I added my personal api key again in the advanced settings. When that didnt stop it i disabled the messages.
> 
> Noticing the issues with art i thought that it might be the api key, so i generated a project api key and put that in the advanced settings.

Please don't do this. A project api key is completely unnecessary and negates the whole point of project key in the first place. 

You can add a personal fanart tv api to "Fanart.tv client key" in the "Accounts / API Keys" section of the settings but it will also work fine without one.

DONT add API keys to the EXPERT section - that is only there for debugging / future proofing (e.g. if my project keys get disabled for some reason). 

I'll have a proper look at your suggested changes tomorrow. However, I've not had any issues with artwork, so I'm not quite clear on what you are trying to fix here exactly. Your comments about needing to disable the message indicate that you are putting the wrong api key in the wrong section.

**Comment by jurialmunkey** [comment]
I did a few tests with home screen widgets and all artwork types are being found correctly for me. Make sure you have the setting enabled to use fanart tv for widgets.

Here are `clearlogo` `banner` `discart` `clearart` `landscape`

![Honeyview_screenshot462](https://user-images.githubusercontent.com/4618719/73135727-bb9ca280-4099-11ea-878e-74d8d63f4ce1.jpg)
![Honeyview_screenshot461](https://user-images.githubusercontent.com/4618719/73135728-bb9ca280-4099-11ea-9532-148872e2bd64.jpg)
![Honeyview_screenshot463](https://user-images.githubusercontent.com/4618719/73135729-bc353900-4099-11ea-81ba-8197b8b1adbd.jpg)

**Comment by henryjfry** [comment]
Ok, ill take out my project API key and ill try deleting simplecache.db (but FYI i hadnt had the message since i setup two different api keys).

Yep i definetly do have fanarttv enabled for widgets, its only a TV widget which im using. Someone else on reddit reported no clearlogos on episodes widgets.

By "wrong" banners/thumbs i mean in the addon when i change my view setting so thumbs were visible a number of shows had missing thumbs or the poster was being used as the thumb and was all stretched to the wrong width. And missing banners it was just showing me grey boxes where the banner wasnt being loaded at all.

When i reinstalled the addon it was still showing me the same stretched posters as thumbs and/or missing banners for the same shows, which were working with my changes prior to the update so its not like it was retrieving the wrong items from the cache.
As soon as i readded the changes the correct artwork was back.

**Comment by jurialmunkey** [comment]
>And missing banners it was just showing me grey boxes where the banner wasnt being loaded at all.

This is a Kodi texture cache issue. It happens when a lot of new textures get loaded. Note that I don't download the images myself - I just point to the url and Kodi will then download them.

> Yep i definetly do have fanarttv enabled for widgets, its only a TV widget which im using. Someone else on reddit reported no clearlogos on episodes widgets.

I'll have a look at episode widgets as I didn't test them just now.

**Comment by jurialmunkey** [comment]
TvShows/Seasons are getting artwork fine for me both in widgets and inside the plugin. Episodes are currently not getting any artwork - I'll look at a fix for that tomorrow.

![Honeyview_screenshot466](https://user-images.githubusercontent.com/4618719/73135901-ef78c780-409b-11ea-9ea8-cd4aeeced4c7.jpg)
![Honeyview_screenshot464](https://user-images.githubusercontent.com/4618719/73135902-ef78c780-409b-11ea-9a65-b8621641694a.jpg)

**Comment by drinfernoo** [comment]
@jurialmunkey FWIW, a "widget" of artwork like those would be neat in AZ2's info dialog 👌

**Comment by jurialmunkey** [comment]
Okay, In latest episodes should now get additional fanarttv artwork types.
These are put in `$INFO[ListItem.Art(tvshow.foobar)]` e.g. `$INFO[ListItem.Art(tvshow.clearart)]`

Note that fanarttv api is currently having connection error issues (err code 500), so only cached items will be working until the API comes back up. (I've also added some checking for these errors because previously it would result in long loading times - now if it fails on a 500 I suppress retries for 1 minute because that means API is down and there isn't any point constantly trying to hit it)

**Comment by drinfernoo** [comment]
@jurialmunkey I just realized, what window *is* that in your screenshots? I'm intrigued by the icons in the top left, and also the "peeking" posters on the left and right margins...

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey I just realized, what window _is_ that in your screenshots? I'm intrigued by the icons in the top left, and also the "peeking" posters on the left and right margins...

Hahaha shhhhh... It's a secret 😉 
Something new maybe coming soon...

**Comment by drinfernoo** [comment]
@jurialmunkey Ooh, that's exactly what I was hoping you'd say! 😅 I'll hold for new developments 👍

**Comment by henryjfry** [comment]
Ok so ive had a chance to install the new version and I can confirm that it can now play successfully from episodes widgets again, but it is still underserving me artwork.

So ive attached some images two are from the recently watched tv shows in trakt and two are from my next up episodes widget (not sure which is which)

So in the recently watched tv show addon folder it is missing a thumb for the madalorian which just shows as a grey box and the witcher is missing the thumb (and is using the poster in place of the thumb) and it also is missing the clear logo.  So this is basically exactly the same as was happening prior to all my additions to do with fanart.
But this artwork was cached and available prior to updating the addon and rebooting kodi.

The two from my next up episodes show you that the widget has no clear logos showing up for every single show.

![IMG_20200127_192143](https://user-images.githubusercontent.com/44173765/73206514-f1459800-413a-11ea-8da1-20f33c061a4e.jpg)
![IMG_20200127_192128](https://user-images.githubusercontent.com/44173765/73206515-f1de2e80-413a-11ea-9a68-fd1df47c86ba.jpg)
![IMG_20200127_191948](https://user-images.githubusercontent.com/44173765/73206517-f1de2e80-413a-11ea-9e28-6f3f639ad3ec.jpg)
![IMG_20200127_191932](https://user-images.githubusercontent.com/44173765/73206520-f1de2e80-413a-11ea-87e7-980408f45253.jpg)

**Comment by henryjfry** [comment]
Ok I think i might have an idea why its not working even with your changes, in listitem.py:

`        if self.infolabels.get('mediatype') == 'tvshow' and (self.tvdb_id or tmdb):
            self.tvdb_id = self.tvdb_id or tmdb.get_item_externalid('tv', self.tmdb_id, 'tvdb_id')
            artwork = fanarttv.get_tvshow_allart_lc(self.tvdb_id)`

All this does will get art for tvshows? Hence episodes wont get populated?

Also in container.py in get_sortedlist

`        if self.item_tmdbtype in ['season', 'episode'] and self.params.get('tmdb_id'):`

Would this possibly be false by default for episode widgets (maybe self.params.get('tmdb_id') isnt true??)
Just a thought.

Making a couple of changes there seems to get widget artwork working. Although i think fanarttv is having issues at the moment.

Also i should point out that there are a couple of places where you are referencing artwork but you dont have a poster reference, which for some tvshows will be a problem if tmdb doesnt have a poster.

**Comment by jurialmunkey** [comment]
Witcher and Mandalorian both getting full art for me in Trending TV Shows:

![Honeyview_screenshot467](https://user-images.githubusercontent.com/4618719/73217136-736da500-41ab-11ea-9925-f2685ad6d4a2.jpg)

If only some items in a list are getting artwork and others aren't, then that indicates an issue with fanarttv or the cache. I'll double check my artwork caching code to make sure blanks from error codes are not being cached as results.

The stretching issue in your screenshot (The Witcher) is a skin issue. Whatever skin you are using should fallback to Art(fanart) if Art(landscape) is not available. Skin decides what artwork fallbacks to use. I don't fill Art(landscape) with poster - that's a skin variable doing that.

The blank artwork for Mandalorian is a Kodi caching issue. It happens sometimes when Kodi is downloading new artwork. I'm not sure why.

**Comment by jurialmunkey** [comment]
> 
> 
> Ok I think i might have an idea why its not working even with your changes, in listitem.py:
> `if self.infolabels.get('mediatype') == 'tvshow' and (self.tvdb_id or tmdb):
> 
> ```
>         self.tvdb_id = self.tvdb_id or tmdb.get_item_externalid('tv', self.tmdb_id, 'tvdb_id')
> 
>         artwork = fanarttv.get_tvshow_allart_lc(self.tvdb_id)`
> ```
> 
> All this does will get art for tvshows? Hence episodes wont get populated?

Fanart tv only supplies artwork for TVShows. It requires a **tvshow** id to do the lookup. The listitem for an episode/season will have the episode/season ID, not the tvshow id so no point doing a lookup there as you will get the wrong items and your cache will become a mess.

For this reason, I deal with episodes/seasons elsewhere in container.py where I get the details for the tvshow and merge with the episode/season details:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/container.py#L148-L159
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/container.py#L187-L199


> Also in container.py in get_sortedlist
> 
> ` if self.item_tmdbtype in ['season', 'episode'] and self.params.get('tmdb_id'):`
> 
> Would this possibly be false by default for episode widgets (maybe self.params.get('tmdb_id') isnt true??)
> Just a thought.
> 
> Making a couple of changes there seems to get widget artwork working. Although i think fanarttv is having issues at the moment.
> 
> Also i should point out that there are a couple of places where you are referencing artwork but you dont have a poster reference, which for some tvshows will be a problem if tmdb doesnt have a poster.

**Comment by jurialmunkey** [comment]
@henryjfry - Okay, please test latest version. Fanart tv artwork is now working for episode widgets. Please note that the skin must reference these like `Art(tvshow.clearlogo)` not `Art(clearlogo)` as the artwork is for the tvshow not the episode (this approach is consistent with artwork in the Kodi library db). `Art(poster)` will be the season poster and `Art(tvshow.poster)` will be the standard poster.

![Honeyview_screenshot468](https://user-images.githubusercontent.com/4618719/73249698-7bf4c880-4209-11ea-8d26-8373519c704c.jpg)

**Comment by henryjfry** [comment]
Ok i can confirm that the current version in the repo (2.2.46) is now delivering all the artwork it should be, thanks for all your hard work.

**Comment by drinfernoo** [comment]
@jurialmunkey Whatever happened to the window shown here?
