### ISSUE TITLE
[Bug} themoviedb.helper error

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#580]
info: themoviedb.helper error v4.4.16. I was also getting the same  error with 4.4.15

<img width="1627" alt="Screenshot 2021-11-01 at 01 29 30" src="https://user-images.githubusercontent.com/2873112/139610080-8001aa4d-90f5-4e63-8399-ab6c5cbc419f.png">

<img width="1627" alt="Screenshot 2021-11-01 at 01 40 26" src="https://user-images.githubusercontent.com/2873112/139610102-3c657b81-0e17-4547-a95d-86c09fa37f14.png">

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/7450234/kodi.log)
[kodi.old.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/7450235/kodi.old.log)

Thanks

**Comment by jurialmunkey** [comment]
Oops! Missed an import - not sure why my linter didn't pick that up but it's an easy fix -- should work properly now in 4.4.17

**Comment by xyzfre** [comment]
Thank you for the fix definitely working now with no errors and thank you for all the hard work that goes into TMDB Helper ✊🏼￼￼￼
