### ISSUE TITLE
Context Menu and Auramod Problem 

### ISSUE THREAD

**Issue by paallday** [jurialmunkey/plugin.video.themoviedb.helper#583]
All of the sudden, the context menu keeps popping up when I try to go into a Season or Episode from widgets. I select the show, and in Auramod I can choose Episodes…then the context menu pops up instead of going into the season list from the original source addon (Seren). Running latest version of tmdb helper

**Comment by drinfernoo** [comment]
Sounds like an AuraMOD issue 🤔

**Comment by paallday** [comment]
Hmmm. I did just switch back over to Auramod from Titan Bingie. Only started since then actually. Liking Auramod better though, always have 😉

**Comment by paallday** [comment]
> Sounds like an AuraMOD issue 🤔

Funny thing is…when I uninstall both and reinstall, the problem goes away. Not sure what makes it happen??

**Comment by jurialmunkey** [comment]
Yeah this sounds like a skin issue.

Tmdbhelper doesn't activate the context menu. Unless you're talking about the browse lists menu which is used when default action in addon settings is set to browse not play - then it gives the option of where you want to go. But still a skin issue if it is popping up unintended.
