### ISSUE TITLE
Players not showing in settings

### ISSUE THREAD

**Issue by ry0240** [jurialmunkey/plugin.video.themoviedb.helper#584]
I'm having this problem in windows x64 and x86 on 19.3. When I go to settings there's no option to update the players. 
![2021_11_21 11_05 PM Office Lens](https://user-images.githubusercontent.com/59429310/142802656-90df82a1-19e2-4cdd-8819-12737d677728.jpg)
There's no error when installing. I've tried both from your repo and official Kodi repo.

**Comment by alKODIque** [comment]
@ry0240 
Just go down in tabs settings. You'll find more option after the last see on your screenshot (after "Account" tab)

![Screenshot_20211122-013345](https://user-images.githubusercontent.com/49578130/142814124-39cd7488-de40-4090-90ae-c0460ed61370.png)

**Comment by ry0240** [comment]
> @ry0240 Just go down in tabs settings. You'll find more option after the last see on your screenshot (after "Account" tab)
> 
> ![Screenshot_20211122-013345](https://user-images.githubusercontent.com/49578130/142814124-39cd7488-de40-4090-90ae-c0460ed61370.png)

Ok thank you.
