### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by mrXoo** [jurialmunkey/plugin.video.themoviedb.helper#585]
Hi there,

I was wondering if you were ever thinking of implementing a GUI like the script.extendedinfo used to have, where you can see more info about the movie or show etc?

Just a though

**Comment by drinfernoo** [comment]
Use a skin that implements TMDbHelper 😉

**Comment by jurialmunkey** [comment]
This is up to skinners to implement. Instructions for skinners are provided in the wiki: 
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Replacing-Extended-Info

**Comment by mrXoo** [comment]
@drinfernoo  in your opinion whats the best skin out there for that? currently using xonfluence skin

**Comment by drinfernoo** [comment]
Arctic Horizon probably has the most fleshed-out and user-friendly integration with TMDbHelper, but also Arctic Horizon 2 and AuraMOD make pretty extensive use of it too.

I'm not sure what other skins do, but I think Eminence v2 does as well.
