### ISSUE TITLE
24hr delay on TV shows

### ISSUE THREAD

**Issue by thefrench1** [jurialmunkey/plugin.video.themoviedb.helper#587]
Hi I'm new to this add-on so not sure if it has been requested before or not. Is it possible to have a 24hr delay set so that my trakt library does not show the episode on the widget till it actually airs. I know lots of repos have this option within in there settings.  Again sorry if this has been asked before.

**Comment by jurialmunkey** [comment]
You can already set the time the library updates in the settings.

Air dates are UTC adjusted based upon your System region settings. Make sure that your region and time/date settings are correct in `Kodi Settings > Interface > Regional`

Also make sure that the "Hide unaired" settings are enabled in `TMDbHelper Settings > Navigation`

I've never had an issue with a tvshow episode showing up before it airs.
