### ISSUE TITLE
Request : add Addon shortcut as last item in a widget/every widget.

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/plugin.video.themoviedb.helper#588]
So if I have let's say a Seren Widget, the last item would be a shortcut to opening Seren's main menu. To be clear: it wouldn't open that widget-list in Seren, that wouldn't add functionality I think.  But linking to the addon top menu would.

Or (more complex) a user-defined shortcut to an item in the Seren addon.

You @jurialmunkey allready have "Show next page item on widgets", so that made me think this could be possible.  Last item would also be easy to reach if you go left if your position is the first item of a widget in horizontal view.

**Comment by jurialmunkey** [comment]
I don't understand the point of this. Why would a TMDbHelper list have an item which opens a different addon?

You can already use the "Search" version of a player to open a search query for an item in another addon (assuming the player file has implemented it - I do this for Netflix).

**Comment by DaisyF8** [comment]
I'm reading what I wrote and I must have been out of my mind, no joke. I was thinking about my kaito-widget (anime) and convinced myself it was by tmdb-helper. And then some other stuff and I also don't know why I wrote Seren.

I derped big time. Let's close this thing. Sorry to waste your time.

**Comment by jurialmunkey** [comment]
Hahaha no worries!
