### ISSUE TITLE
WARNING: Invalid media type ""

### ISSUE THREAD

**Issue by henryjfry** [jurialmunkey/plugin.video.themoviedb.helper#59]
Getting this message in the logs on the newest version.  Can be fixed by making a change to the 'Next Page' item in listitem.py

```
        if self.label == 'Next Page':
#           self.infolabels['mediatype'] = ''
           self.infolabels['mediatype'] = 'videos'
```

**Comment by jurialmunkey** [comment]
Fixed in latest.

It needs to be blank because it's not a video. 
Solved by doing `self.infolabels.pop('mediatype', None)` instead.
