### ISSUE TITLE
Abort fallback option when cancelling in a dialog window

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#591]
I'm opening this ticket because of something I noticed yesterday but I'm not really sure what the best option would be to handle it. 
I'm using the Embycon player that is configured with the search option as a fallback to the play one. When there is more than one result, a dialog is opened to select the right file. The problem is that, if you want to cancel the whole selection and go back to the previous screen, you are forced to go over the list of fallbacks, cancelling all of them (in my case I have yet another player after the search with Embycon). 
On one hand, this is the right behaviour if the first player didn't find what you were looking for and you want the fallback functionality try other players. On the other hand, if you just want to cancel it, you are force to go over the whole list. 
I think it's a minor thing given this is not something that happens often but I was wondering if there was something that could be done from the addon side like adding an extra button to the select dialog to cancel. I think the answer is no given the one with the control at that point is the player addon but wanted to see your opinion on this.

**Comment by jurialmunkey** [comment]
Okay I was just about to write something about how you can't add a button to the select dialog and without an extra button there's no way to know whether the user is intending to cancel or just didn't find a source. 

However, I just had an idea, what about an extra item to cancel in the _list_ of the select dialog itself? Or would that be too confusing if it was at the end of the list? 

That's the only way I can think of getting an additional option in the dialog. Any other solution just adds an extra step which defeats the purpose of the fallback (if we're adding an extra step then may as well just disable the fallback altogether and go back to the player selection dialog).

**Comment by juanma-cvega** [comment]
I'd say that'd be difficult to understand for anyone not knowing this feature exists. If it's not too much work I guess it could be implemented but otherwise I'd say don't bother adding it so feel free to close the issue if you don't feel like doing it.
