### ISSUE TITLE
Fallback when the first player is not available

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#593]
I have configured a fallback for the Embycon play episode player that falls back to the search episode one if it doesn't find anything. But this doesn't work when the play player cannot be executed at all by the addon. This happens when the player uses data that is not available, in the case of this player it uses the `epid` variable that in some cases is not there. 
Would it be possible to configure it so it does fallback to the next player even though it didn't even execute?

**Comment by jurialmunkey** [comment]
I'm confused. How are you even selecting the player in that case? Or have you set it as the default player?

**Comment by juanma-cvega** [comment]
Sorry, I forgot to mention that. Yes, I'm using the Embycon play player as my default player.

**Comment by jurialmunkey** [comment]
> Sorry, I forgot to mention that. Yes, I'm using the Embycon play player as my default player.

Oh okay, this is definitely unintended behaviour / a bug then. 

I probably forgot to account for asserted values when I wrote the code. I'll look into fixing it.

**Comment by jurialmunkey** [comment]
@juanma-cvega - Can you test latest version (v4.4.40) and see if that fixes the issue for you?

My test case was a three player fallback (i.e. Player1 -> Player2; Player2 -> Player3) where Player1 asserted values that didn't exist, and Player2 didn't have the item. When I set Player1 as default player, my test item correctly played automatically with Player3 without a dialog prompt, so it looks like the fallbacks are cascading properly now.

**Comment by juanma-cvega** [comment]
Yes, it seems to work fine for me as well. Thanks for the work done!
