### ISSUE TITLE
Episode thumbs list returns plug-in root

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#598]
Is the documentation for the Episode Thumbs list correct:-

`plugin://plugin.video.themoviedb.helper?info=episode_thumbs&amp;type=tv&amp;query=$INFO[ListItem.TvShowTitle]&amp;season=2&amp;episode=1`

This just returns the root of the plugin.

**Comment by jurialmunkey** [comment]
Ah this is a feature that was in v2 that I meant to port to v4 and forgot about on my todo list. Latest commit (v4.4.38) should make it work (and also give the thumbs option in the Browse lists section of the context menu).

**Comment by roidy** [comment]
Works perfect, thanks for the quick fix 👍
