### ISSUE TITLE
Auto play next episode

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#599]
Is there a way the addon could implement auto play of episodes? This may not be possible as I understand once the player invokes the addon, it stops there but maybe there is a workaround?

**Comment by drinfernoo** [comment]
#148

**Comment by juanma-cvega** [comment]
ok, I didn't see that one

**Comment by hbashton** [comment]
on this topic, it might be important to note that in my testing, even with a proper queue set up (using the in progress TV shows list for example), and playing with the Venom auto-play player (which does support Up Next, and has been confirmed to work when playing through Venom's own one-click auto-play), up next still doesn't function in TMDB helper.

**Comment by jurialmunkey** [comment]
> on this topic, it might be important to note that in my testing, even with a proper queue set up (using the in progress TV shows list for example), and playing with the Venom auto-play player (which does support Up Next, and has been confirmed to work when playing through Venom's own one-click auto-play), up next still doesn't function in TMDB helper.

Unlikely to be a TMDbH issue.  Many video plugins have multiple methods of playing files. The most likely reason for a difference in behaviour is that the player file you are using is configured to use a different method than the one being used inside the plugin to auto-play a playlist. 

All listitems have a call-back uri which is passed to the plugin when you click on the item in Kodi. That uri is how the plugin determines what code to run. TMDbH doesn't do anything special - it just follows the rules setup in the player file to retrieve the call-back uri from the listitem and then passes it to Kodi. As long as the player is configured correctly to retrieve the same uri as inside the plugin then the end behaviour should be identical.
