### ISSUE TITLE
Group movies by set in widgets

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#600]
I currently I show movies from my lists as widgets but I would like to group them by set instead of showing individual ones. For example, grouping all the Harry Potter movies or the MCU ones. Is there any way this could be implemented?

**Comment by jurialmunkey** [comment]
Trakt lists don't give metadata about which set a movie belongs to, so there's no simple way to do it since sorting and pagination happens before the tmdb details lookup. Every way to do it is going to involve a lot of doubling handling and I don't think the performance trade-off will be worth it.

**Comment by juanma-cvega** [comment]
Ok, fair enough. I'm closing the issue then.
