### ISSUE TITLE
Missing Documentation?

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#601]
I can't seem to find documentation for getting videos for an item, i.e. trailers, teasers, clips etc...

I know it should be possible because it's one of the lists available from the context menu.

**Comment by jurialmunkey** [comment]
Ah yep, you're correct. Not sure how I missed that one.

It's `info=videos` and takes same params (query, imdb_id, year etc.) as the other related lists. I'll add it to the docs now.

**Comment by roidy** [comment]
Perfect, thanks.
