### ISSUE TITLE
[Feature] Option to Include day / date in next aired lists

### ISSUE THREAD

**Issue by trexx** [jurialmunkey/plugin.video.themoviedb.helper#603]
I currently have a next aired widget for the week on my home screen, and it'll really be useful if I could also have the day the show airs included in the episode title somehow.
For example,

Before: The Expanse - 6x03. Force Projection
After: Monday | The Expanse - 6x03. Force Projection

I understand with your horizon skin you have a next aired view with each day as a widget / row but I don't watch that many shows to justify a full view and it'll be nice to mix in the weeks viewing with a next up widget or alike.

I understand changes would have to be made here?
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/matrix/resources/lib/container/listitem.py#L358

Do you think this is functionality worth including in the plugin?

**Comment by jurialmunkey** [comment]
I think this is a matter for skinners to implement rather than to force it in the plugin by overwriting the label. 

TMDbHelper already fills properties of the listitem with various day/date/time metadata for next aired items which skinners can then use to display how they wish: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Lists-Next-Aired-Calendar#special-listiteminfolabels-for-calendar-episodes

**Comment by trexx** [comment]
FWIW, a little workaround that doesn't require any changes to either skin or plugin is to include
$INFO[Container(x).ListItem.Property(air_date)] or other ListItem property in the widget label when customising the main menu. Which is pretty handy and enough for my needs. At least it avoids having to mod the skin.

![image](https://user-images.githubusercontent.com/874158/147341529-759b2cd6-d8fa-47d5-99db-838864d63d25.png)

**Comment by jurialmunkey** [comment]
> FWIW, a little workaround that doesn't require any changes to either skin or plugin is to include $INFO[Container(x).ListItem.Property(air_date)] or other ListItem property in the widget label when customising the main menu. Which is pretty handy and enough for my needs. At least it avoids having to mod the skin.
> 

I was almost going to suggest exactly this approach. It's just one of those things that's a little difficult to explain how to figure out the ID so I ended up not mentioning it, especially since it differs skin to skin.

I'm glad you figured out something that works for you!
