### ISSUE TITLE
Add to Library not working

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#605]
I'm unable to get the context menu function "Add to Library" to work.

I press "Add to Library" on a TV Show from anywhere in the plugin and all the folders and strm files are correctly created, and Kodi performs a library update but the TV Shows are never add to my library.

Any ideas what I'm doing wrong, or does the "Add to Library" function not do what I think it does?

![Cap](https://user-images.githubusercontent.com/4118048/147507980-51aa935d-0bf1-4b30-ba18-ba04f50be9f3.jpg)

**Comment by jurialmunkey** [comment]
Have you added the location to your Kodi sources as a tvshow library source?

**Comment by roidy** [comment]
D'oh! Completely forgot to add the source.... Thanks
