### ISSUE TITLE
translate problem

### ISSUE THREAD

**Issue by shahaf1122** [jurialmunkey/plugin.video.themoviedb.helper#606]
when I was using kodi 18.9 when the translate didn't work it send a +
but now in 19.3 it return error and I cant play the show....
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/7786398/kodi.log)
.

**Comment by jurialmunkey** [comment]
Could you post your player .json file so that I can test?

**Comment by shahaf1122** [comment]
it is not a public addon so i dont know if you can test it....

**Comment by jurialmunkey** [comment]
> it is not a public addon so i dont know if you can test it....

The actual addon doesn't matter, I can use a dummy addon - I just need the actual player configuration so that I'm able to reproduce the issue correctly.

**Comment by shahaf1122** [comment]
o.k. I got it.
Thanks for the quick response.
and series that have a Hebrew translation it works but series that do not just return ERROR.
I tried to watch the series "The North Water"
[direct.boom.txt](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/7788911/direct.boom.txt)

**Comment by jurialmunkey** [comment]
@shahaf1122 - Can you test latest git version (v4.4.43)? It should fix the issue. Kodi 19.3 updated Python version from 3.6 to 3.7 and there was a change in how string formatting is handled, so this patch should fix it. 

Whilst fixing the issue, I also realised that returning `+` for non-existent keys potentially causes a recursive regex issue, so now blanks will return an underscore `_` instead to prevent that.

**Comment by shahaf1122** [comment]
I tested it and it is works now
Thank you for the fast response and the fast repair!
