### ISSUE TITLE
[Request] Option to include 0% progress in "In-Progress" list

### ISSUE THREAD

**Issue by mattokar** [jurialmunkey/plugin.video.themoviedb.helper#608]
Hi @jurialmunkey

In trakt settings there is an option to "Include Watchlisted" in WATCHED PROGRESS section. I have enabled this in trakt and got used to it. Is it possible to get this behaviour in addon? Didn't noticed it in wiki.

Thank you

**Comment by jurialmunkey** [comment]
Currently not available but it's a great idea! Definitely will look into adding it as it makes a lot of sense to combine the two lists.

**Comment by mattokar** [comment]
Thank you. Would be nice to have option to order by "Recently watched" also.  But just being able to merge this two lists would be awesome.

**Comment by jurialmunkey** [comment]
> Would be nice to have option to order by "Recently watched" also.

In-Progress Shows should already be sorted by Recently Watched by default.

**Comment by jurialmunkey** [comment]
@matthew6870 - Can you test latest git version (v4.4.66)?

Adds "TV Shows Still to Watch" and "Movies Still to Watch" lists under Trakt which mix in-progress list with watchlist.

The sorting is by last activity of the item -- i.e. it compares date an item was last watched (in progress) with the date the item was listed at (watch list). So basically your most recently watched/added items will be listed at the front. 

It actually seems to work quite well. If you start watching a show or add an item to the watchlist then it goes to the front. If you start watching something else, that comes to the front. Once you finish a show, it is removed from the list so the rest of the items move up.

**Comment by mattokar** [comment]
Hi. That was fast! :)  I didn't have time today and I am busy tomorrow also. I will try to test it on Thursday.

**Comment by mattokar** [comment]
@jurialmunkey Sorry for a little late reply. Tested and seems to work as intended. Thank you

**Comment by jurialmunkey** [comment]
Excellent! Seems to be working properly for me too after a few days testing - so I'll close this issue now. Let me know if you encounter any bugs with it.
