### ISSUE TITLE
[Request] Flatten shows with multiple episodes in calendar.

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#611]
For TV shows that release multiple episodes on the same day would it be possible to flatten all the episodes into one TV Show entry in the calendar lists, to save space. Possibly also adding an item property with the number of episodes released.

Thanks

**Comment by jurialmunkey** [comment]
I swear there was already an issue open for this exact request but I can't find it now! Anyway, yes, definitely on the cards as this has been bugging me quite a bit recently with Netflix shows like The Witcher and Cobra Kai.

The only thing I'm a bit stumped on is how to indicate a stacked episode and what the behaviour should be when you click on it. The action issue could be solved with a DialogSelect pop-up to choose from the stacked episodes but I still need a way to indicate it's stacked that doesn't need skin support.

**Comment by jurialmunkey** [comment]
Can you test latest version (4.4.46)? Adds a flatten option for the calendar (enabled by default).

Currently I'm just dropping the user in the season if it's stacked. The episode label will display the first and last episode numbers in the stack and say how many episodes there are: e.g. `1x01-1x03. Airing 3 Episodes` if 1x01/02/03 all air together.

You'll get these `ListItem.Property(properties)`
| Property | Description |
| :--- |  :--- |
| stacked_count | Number of episodes in the stack |
| stacked_labels | Comma separated list of episode labels e.g. `1x01 - Ep1Title, 1x02 - Ep2Title, 1x03 - Ep3Title` |
| stacked_titles |  Comma separated list of episode titles e.g. `Ep1Title, Ep2Title, Ep3Title` |
| stacked_episodes | Comma separated lists of episode numbers e.g. `1x01, 1x02, 1x03` |
| stacked_first | First episode number in the stack |
| stacked_last | Last episode number in the stack |

**Comment by roidy** [comment]
>Can you test latest version (4.4.46)? Adds a flatten option for the calendar (enabled by default).

Wow, that's great. It works exactly how I would want it to work and the extra properties cover every possibility I can think of 👍 

One very very minor thing but if the episodes are in the past then the label should be:-
`1x01-1x03. Aired 3 Episodes`
instead of
`1x01-1x03. Airing 3 Episodes`

Thanks for adding this, it really makes the calendar look much nicer

**Comment by roidy** [comment]
Another small request :)

For the properties stacked_first and stacked_last could we just get the episode number without the 1x01 formatting. I'm finding it hard to do custom formatting. In my skin my season/episode labels are formatted like so:-

`S2: E5 Episode Title`

so for multiple aired episodes the following label is impossible to create:-
`S2: E1-E5 Aired 5 episodes`

Thanks

**Comment by jurialmunkey** [comment]
Okay should have `stacked_(first|last)_(season|episode)` properties now which will give raw number e.g. `$INFO[ListItem.Property(stacked_first_episode)]`

I've also modified the standard label to remove the "Airing" part so that it works both ways
e.g. `1x01-1x05. 5 Episodes`

**Comment by roidy** [comment]
Perfect, thank you 👍
