### ISSUE TITLE
Reg. Posters and Fanarts

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/plugin.video.themoviedb.helper#615]
Hi @jurialmunkey,

I'm using the TMDB Helper add-on in combination with the Arctic Horizon skin in Kodi. I'd like to know if there's any way to show the Posters from TMDB website and the extra Fanarts from Fanart.tv website? This is because I like the TMDB Posters more and also want to get the various extra Fanarts from Fanart.tv for the Arctic Horizon skin. Kindly advise.

Thanks,
ShibajiCh.

**Comment by jurialmunkey** [comment]
No way currently. If you enable fanarttv and the item has artwork from fanarttv then it will override tmdb artwork. 

It's a bit complicated to mix the two together and I haven't thought of a way to do it yet that doesn't involve a big rewrite or will negatively impact performance by repeating requests, so for the time being there is an ovevrwrite heirarchy where Library > FanartTV > TMDb.

However, you can manually select which artwork is used from fanarttv via the context menu addon for TMDbHelper.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Thank you! I guessed the same too. Thanks for letting me know!

Regards,
ShibajiCh.
