### ISSUE TITLE
Reconfigured players issue

### ISSUE THREAD

**Issue by cg00001** [jurialmunkey/plugin.video.themoviedb.helper#616]
If someone needs to change the priority numbers of players it's very easy via TMDbH settings.
The issue comes later, when you update the players.
The reconfigured players are saved in /userdata/addon_data/plugin.video.themoviedb.helper/reconfigured_players and when you update your players the ones that will be used are not the updated ones (the ones in normal players folder), but the reconfigured ones.
That could mean you will have a non working player.
A fast and semi-elegant solution would be the reconfigured folder to be automatically deleted when players are updated, and a popup saying "Your reconfigured players are deleted, please customize them again." could be shown.

**Comment by jurialmunkey** [comment]
You can reset the players in the configuration dialog. That will delete the configured file and revert to using the installed/downloaded version.
