### ISSUE TITLE
Addons that otherwise scrape link for the correct show returns links for the wrong show.

### ISSUE THREAD

**Issue by TheGuyWhoo** [jurialmunkey/plugin.video.themoviedb.helper#619]
When I try to scrape links for the show 'blood & treasure' using a4kstreaming TMDB player it returns links for 'Dexter new blood'. When I search for 'blood & treasure' in tmdb helper, the first result is 'Dexter new blood'. When I search for links within the addon a4kstreaming, it returns links for 'blood & treasure' and not dexter. So it appears to be a TMDB issue.

Same thing happens with the show 'Babarians', I get links for 'Barbarians Rising' instead and sure enough when I search 'Barbarians' in TMDB helper, the first result is 'Barbarians Rising'.

**Comment by jurialmunkey** [comment]
Sounds like your player file is misconfigured and not pointing to the correct path and/or using the correct properties. I don't make 3rd party players. Speak to whoever made the player file and ask them to fix it.

**Comment by jurialmunkey** [comment]
I had a look at this player. I assume that you're using the one available on via this page: https://github.com/a4k-openproject/a4kStreaming at http://bit.ly/a4kStreaming-tmdb

That player uses {imdb} and {epimdb} keys. I just tested playing S01E04 of Blood & Treasure from inside TMDbHelper and got the correct imdb values of `tt7712598` for the show and `tt8686648` for the episode, so TMDbHelper is functioning correctly.

Either you're using a different player file which is incorrectly configured or you're not playing the item from inside TMDbHelper. The only thing I can think is that you're attempting to use some weird context menu based call from outside TMDbHelper where you don't have full item details so the query look-up can't find a proper match.

Without more details about how you attempt to play the file I can't really help.

**Comment by TheGuyWhoo** [comment]
Yes, I was using the context menu from the official repository. That appears to have been the issue, when I cleared my default players and then tried again I got the correct results.

**Comment by jurialmunkey** [comment]
> Yes, I was using the context menu from the official repository. That appears to have been the issue, when I cleared my default players and then tried again I got the correct results.

Ah yep via the context menu addon you might get the wrong result with episodes because it has to try to guess what show you mean just based off the tvshowtitle. 

I've added an episode year lookup in v1.0.5 of the context menu addon which should improve results. I tested with your examples and am now able to get the correct results - whereas with only the tvshowtitle available it would be incorrect.

You can download a zip here:
https://github.com/jurialmunkey/context.themoviedb.helper/archive/refs/tags/v1.0.6.zip

**Comment by TheGuyWhoo** [comment]
Thank you, that's much appreciated!
