### ISSUE TITLE
[Bug] TV show exists in TMDb, but can't be found in Helper

### ISSUE THREAD

**Issue by tjamieg** [jurialmunkey/plugin.video.themoviedb.helper#62]
There's one stubborn TV show (and its episodes) that never populates in my widgets, although it does exist in TMDb.

![Homescreen Widget](https://user-images.githubusercontent.com/48328397/73147959-dc70f200-40b1-11ea-813a-c7b4e5368fd4.jpg)
![TV Show](https://user-images.githubusercontent.com/48328397/73147960-dd098880-40b1-11ea-8bd3-70b11e1d3489.jpg)

Don't get me wrong I can live without it, but it sounds like a bug all the same, and if this ones not showing properly for me then other people might have the same problem with others.

The show is called "Hanger 1: UFO Files" (TMDb ID: [64900](https://www.themoviedb.org/tv/64900)).
At first I thought the colon in the title might have caused some issue, but then I noticed others with colons in their titles that populated just fine.

Here's the debug log from whenever it's next episode is called:
```
2020-01-27 02:17:38.821 T:15316   DEBUG: [plugin.video.themoviedb.helper]
                                            In-Progress -- Searching Next Episode For:
                                            (u'hangar-1-the-ufo-files', None, u'Hangar 1: The UFO Files')
2020-01-27 02:17:39.849 T:15316   DEBUG: [plugin.video.themoviedb.helper]
                                            In-Progress -- Found Next Episode:
                                            {u'season': 2, u'ids': {u'tvdb': 5250696, u'tmdb': None, u'imdb': u'tt4535112', u'tvrage': None, u'trakt': 1898906}, u'number': 12, u'title': u'UFO Superpowers'}
2020-01-27 02:17:39.850 T:15316   DEBUG: [plugin.video.themoviedb.helper]
                                            In-Progress -- Got Next Episode Details:
                                            {'tmdb_id': None}
```

**Comment by jurialmunkey** [comment]
What list is this?

Looks like Trakt is not returning a TMDb ID which is why the lookup is failing.

**Comment by ZefXyde** [comment]
Ticket submitted with Trakt. TMDb ID should be added and duplicate show listing should be removed. Should be fixed within 24hrs.

**Comment by jurialmunkey** [comment]
> 
> 
> Ticket submitted with Trakt to add TMDb ID and remove duplicate show listing. Should be fixed within 24hrs.
> 
> Edit: Reworded

Thanks! 😁

**Comment by tjamieg** [comment]
> EDIT: Yep, Trakt is missing TMDb ID for this show. Not quite sure how to update missing info in Trakt.

@jurialmunkey Sorry, I did try checking for ID's myself before posting the issue here - I saw that the show actually did have TMDb and Trakt ID's but didn't realise the TMDb ID had to be pulled from Trakt.

> Ticket submitted with Trakt to add TMDb ID and remove duplicate show listing. Should be fixed within 24hrs.

@ZefXyde Thank you!

**Comment by ZefXyde** [comment]
@jurialmunkey @tjamieg You're welcome. Ironically, I had literally just done this for 2 other shows prior to this one. 🤣
