### ISSUE TITLE
In-Progress Movies widget taking too long to refresh

### ISSUE THREAD

**Issue by alscaldas** [jurialmunkey/plugin.video.themoviedb.helper#621]
Hello,

I'm using LibreELEC 10.1 (Kodi 19.3 Matrix),  Arctic Zephyr 2 Resurrection v0.7.5 skin and TMDB Helper 4.4.56. All of my content comes from a remote Emby share that I watch using tmdb helper's EmbyCon player. I added a couple of widgets to my home, among them "In-Progress Movies" , "In Progress tv shows", etc. 

What I noticed is that the In-Progress Movies widget doesn't seem to be working as supposed. If I begin watching a new movie and let it unfinished to resume later it takes a long time until the movie shows up sorted as the first one from the list of the widget (as it's sorted based on date added).

By the way, I made a test and added the equivalent widget from Seren ("Finish watching", which also use Trakt as a source). Well, before watching a new movie both widgets (TMDB Helper and Seren) show the same content. If I start watching something and stop it before finishing Seren's widget refreshes after one, maybe two minutes and the new unfinished movie shows up. But that doesn't happen in the tmdb widget, no matter which player I use (EmbyCon or Seren).

Is it maybe caused by any misconfiguration I did? Maybe any sort of delay on the communication between tmdb helper and trakt?

I appreciate any help.

**Comment by jurialmunkey** [comment]
Ah yep you're right - I was checking the wrong activity data for this list. Was checking the activity for `watched_at` when I should've been checking activity for `paused_at`. So the list would've only been refreshing after finishing watching something, not just partially watching something.

Latest commit (v4.4.61) should fix the issue. Could you test and confirm? Looks to be working correctly for me now (note that sometimes the Trakt data might not manage to update before Kodi refreshes the container, so you may need to refresh the container a second time to see the updated list).

**Comment by alscaldas** [comment]
Hey, it seems to be working now! 

I tested a couple of different situations (watching a not previously started movie, resuming an already started movie) and everything works perfectly now. And I notice it usually takes just a couple of seconds to refresh and the movie shows up as expected. 

Thank you very much for taking the time to look into this issue.

**Comment by jurialmunkey** [comment]
Excellent! Thanks for reporting the bug and testing.

**Comment by ghost** [comment]
Excellent! Is a movie supposed to be removed from this list when watched? If so, that’s not happening for me (24hrs later). Also, if I use ‘remove playback progress’ in Seren’s trakt options, an in-progress movie is removed from its ‘Finish Watching’ widget, but remains in tmdb helper’s in-progress movies.

**Comment by alscaldas** [comment]
> Excellent! Is a movie supposed to be removed from this list when watched? If so, that’s not happening for me (24hrs later). Also, if I use ‘remove playback progress’ in Seren’s trakt options, an in-progress movie is removed from its ‘Finish Watching’ widget, but remains in tmdb helper’s in-progress movies.

Hey @Tee77, it's supposed to be removed indeed. I'm not the developer but which version of the addon you're using? Since this issue has already been fixed by @jurialmunkey I believe you're using v4.4.56 or older. If that's the case I believe that updating it will fix it to you too as it did to me.

**Comment by ghost** [comment]
Thanks for the info. I’m actually on 4.5.0. If I use the hide watched option, that works, but wonder if this should be necessary.

**Comment by alscaldas** [comment]
That's the version available on the Kodi repository, I guess. Maybe you should try to add jurialmunkey's repository, which has the newest features and fixes.

As for the this specific list, I believe that hide watched only works with the movies you watched completely, isn't it? If that's the case I may be wrong but I don't think it'll hide partially watched movies.

**Comment by ghost** [comment]
Already have jurialmunkey’s repo installed. Pretty sure 4.5.0 is the latest version - downloaded from GitHub as latest version in Jurialmunkey’s kodi repo is 4.4.67. 

No, I don’t want to hide partially watched movies. I just want watched movies to automatically disappear- this isn’t working for me so the only way to remove them is to hide them. Thanks anyway.

**Comment by jurialmunkey** [comment]
Yep 4.5.0 is most recent version. I bump the minor version number (the middle number) when I submit to the repo and I increase the point number (the right number) for inbetween fixes only released on github and my personal repo.

Anyway, I'll comment in the other thread you've opened: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/626
