### ISSUE TITLE
Sizes for IMAGEPATH_ORIGINAL and IMAGEPATH_POSTER

### ISSUE THREAD

**Issue by Sourcedine** [jurialmunkey/plugin.video.themoviedb.helper#623]
Hi!

Would it be possible to add an option to configure the image sizes for IMAGEPATH_ORIGINAL (for backdrop) and IMAGEPATH_POSTER?

I don't think it's necessary for every configuration to load the backdrop image in the original format or event the poster at w500.

Do you think it can give a 'noticeable' improvement in loading? :)

Thank you for your work! 😊

**Comment by jurialmunkey** [comment]
> Do you think it can give a 'noticeable' improvement in loading? :)

It wont change loading time at all. Kodi downloads artwork _after_ the plugin directory is created and the items are already visible on screen. 

Any images Kodi downloads are rescaled to an optimised image format and added to the local texture cache. Once they've been added to the texture cache, they aren't downloaded again. The artwork sizes have specifically been chosen to be as close as possible to Kodi's default texture rescale settings for posters and fanart.

The only possible area it would benefit is if you see lots of "blank" posters for new items. A smaller size source image will mean that Kodi is slightly quicker in downloading the image to add to the texture cache - but you will really only see an advantage on a system with a very slow internet connection.


More information about Kodi's artwork cache is available here: https://kodi.wiki/view/Artwork/Cache

**Comment by Sourcedine** [comment]
I understand better how it works, thank you for your answer!
