### ISSUE TITLE
{key} won't get replaced

### ISSUE THREAD

**Issue by webepg** [jurialmunkey/plugin.video.themoviedb.helper#628]
Hi,

I'm trying to get my player for the ardundzdf addon to work. What I got so far is to search for an explicit episode.

When using this term

`plugin://plugin.video.ardundzdf/?action=dirList&dirID=ZDF_Search%26fparams%3d%7b%27query%27%3a%20%27heute%252Bshow%252B10%252Bdezember%252B2021%27%2c%20%27title%27%3a%20%27ZDF%253A%25201%2520Video%2528s%2529%2520%2520%257C%2520heute%2520show%252010%2520dezember%25202021%27%2c%20%27pagenr%27%3a%20%271%27%7d`

I do get the search result for: "heute show 10 dezember 2021" which works

But when I try to use this

`plugin://plugin.video.ardundzdf/?action=dirList&dirID=ZDF_Search%26fparams%3d%7b%27query%27%3a%20%27{showname_escaped}%27%2c%20%27title%27%3a%20%27ZDF%253A%25201%2520Video%2528s%2529%2520%2520%257C%2520{showname_escaped}%27%2c%20%27pagenr%27%3a%20%271%27%7d`

the searchterm is {showname_escaped}  which leads to no result What am I doing wrong?

**Comment by jurialmunkey** [comment]
Could you provide me the player .json file and I'll see if I can reproduce the issue. Also `kodi.log` file of attempting to play and it failing.

**Comment by jurialmunkey** [comment]
Also what language/country settings do you have in TMDbHelper? When I try this path via a dummy player it works correctly for me on this show/episode -- it outputs:

`plugin://plugin.video.ardundzdf/?action=dirList&dirID=ZDF_Search%26fparams%3d%7b%27query%27%3a%20%27heute-show%27%2c%20%27title%27%3a%20%27ZDF%253A%25201%2520Video%2528s%2529%2520%2520%257C%2520heute-show%27%2c%20%27pagenr%27%3a%20%271%27%7d`

**Comment by webepg** [comment]
```
{
    "name"              : "ARDundZDF",
    "plugin"            : "plugin.video.ardundzdf",
    "priority"          : 100,
    "is_resolvable"     : "true",
    "assert"            : {
                            "search_movie":     ["title"],
                            "search_episode":   ["showname"]
                          },
    "search_movie"      : [
                            "plugin://plugin.video.ardundzdf/?action=dirList&dirID=ZDF_Search%26fparams%3d%7b%27query%27%3a%20%27heute%252Bshow%252B10%252Bdezember%252B2021%27%2c%20%27title%27%3a%20%27ZDF%253A%25201%2520Video%2528s%2529%2520%2520%257C%2520heute%2520show%252010%2520dezember%25202021%27%2c%20%27pagenr%27%3a%20%271%27%7d",
                            {"keyboard": "{title}"}
                          ],
    "search_episode"    : [
                            "plugin://plugin.video.ardundzdf/?action=dirList&dirID=ZDF_Search%26fparams%3d%7b%27query%27%3a%20%27{showname_escaped}%27%2c%20%27title%27%3a%20%27ZDF%253A%25201%2520Video%2528s%2529%2520%2520%257C%2520{showname_escaped}%27%2c%20%27pagenr%27%3a%20%271%27%7d",
                            {"keyboard": "{showname_escaped}"}
                          ]
}
```

sorry for the bad format. The configured language is german (Germany). The search_movie part is not configured yet.

I also changed the language but it doesn't matter

Here is the kodi.log:

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/7933802/kodi.log)

**Comment by jurialmunkey** [comment]
Is there any specific reason that you're using the `{"keyboard": "{showname_escaped}"}` step? Keyboard steps are only used to input text into the pop-up keyboard if the plugin doesn't allow passing search terms directly in the URI path. 

It looks like that search path should be fine on it's own without requiring keyboard input.

i.e. don't use any steps at all and just try a direct path:
```
"search_episode"      :  "plugin://plugin.video.ardundzdf/?action=dirList&dirID=ZDF_Search%26fparams%3d%7b%27query%27%3a%20%27{showname_escaped}%27%2c%20%27title%27%3a%20%27ZDF%253A%25201%2520Video%2528s%2529%2520%2520%257C%2520{showname_escaped}%27%2c%20%27pagenr%27%3a%20%271%27%7d",
```


---

> sorry for the bad format.

FYI - Use three backticks to create a code block - e.g.
\`\`\`
code
\`\`\`

**Comment by webepg** [comment]
Not really, I don't know why I'm using it but I think it's just from the file I used as a template. Never the less it doesn't make any difference. The {showname_escaped} key doesn't get substituted. I also tried some other keys, same thing they don't get replaced. Do I need to escape the braces or anythink like that for TMDBHelper to recognize them?

**Comment by webepg** [comment]
Ok, it had to be some charset problem or something like that. After copying your URL it just worked.

Thank you very much for your help and for developing this great addon!

**Comment by jurialmunkey** [comment]
It's a bit of a quirk but it's due to how the steps evaluate. With a list of steps, the initial path formatting doesn't happen until the second step evaluates. So if you only put one step inside the `[ ]` list then you end up with the unformatted string.

The reason it doesn't work even with the keyboard step in there is because the keyboard is a special case which only counts as a step once the keyboard inputter resolves -- if the plugin doesn't popup a keyboard then the step never resolves.

The difference between what I had and what you had is that you would've had `search_episode: ["path"]` whereas I had `search_episode: "path"` -- without the `[ ]` list of steps TMDbHelper knows that it's a single step and so evaluates it immediately.
