### ISSUE TITLE
[Feature Request] Make request timeouts customizable

### ISSUE THREAD

**Issue by drse** [jurialmunkey/plugin.video.themoviedb.helper#630]
It would be helpful if request timeouts could be externalized to a config file, rather than hardcoded to a value.

The reason for this request is to suppress constant "Connection Error: TMDb" and similar errors when device is offline.

Some options to overcome this behavior might be:

- if offline, implement a backoff on retries
- don't make requests if offline
- option to disable notifications entirely
- option to modify timeout (such as setting it to an arbitrarily large value, effectively disabling timeout)

**Comment by jurialmunkey** [comment]
Could you test latest git version (4.5.5) and see if that helps for you.

Behaviour when internet disconnected should now be:

- First connection failure in Kodi session:
  - GUI notification popup 
  `ConnectError: {api_name}`
  `Not connected. Check Network Settings`
  - Error logged in kodi.log
- Subsequent connection failures:
  - GUI notification popup and error logged _only if_ a connection error hasn't occurred at all in last 15 minutes.

That way you'll still get notification initially when your internet goes down but you won't get continually spammed with notifications. The actual connection attempts are still only suppressed for 30 seconds like normal, so if your internet does come back up TMDbHelper will start working normally again.

**Comment by drse** [comment]
Seems to be working well, thank you very much!

Minor issue: I wasn't able to find the error log lines in `kodi.log`

**Comment by jurialmunkey** [comment]
> Minor issue: I wasn't able to find the error log lines in `kodi.log`


It will be something like the below. Details will differ depending on the actual request but you should be able to find them by searching for `ConnectionError: Not connected. Check network settings.` in the log.
```
INFO <general>: [plugin.video.themoviedb.helper]
   ConnectionError: Not connected. Check network settings.
   HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: //shows/tt0944947/seasons/1/episodes/1/ratings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D28354BF40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
   Suppressing retries.
```
