### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#635]
Hi Jurialmunkey,
I assume these regular updates are for the anticipated new skin? 😀

**Comment by jurialmunkey** [comment]
Some are just bug fixes and improvements - but, yes, there's been a few where I've specifically needed to add a feature for AH2.

It's moving along nicely. Will probably release some screenshots sometime in the next week and getting pretty close to having a (very alpha) release soon. 

There's still heaps to do but it's almost at the stage of at least being usable even if some features are missing.

**Comment by Blurayx** [comment]
Thanks for the update. Looking forward to the screenshots 😀

**Comment by Blurayx** [comment]
Any closer to revealing the name of the skin & screenshots? 😀

**Comment by jurialmunkey** [comment]
https://forum.kodi.tv/showthread.php?tid=367352 
😉
