### ISSUE TITLE
Next page arrow (>) missing on widgets

### ISSUE THREAD

**Issue by brentonv** [jurialmunkey/plugin.video.themoviedb.helper#64]
In AZ2 skin if I create a TMDBhelper widget it returns 20 items without the next page arrow. I'm not sure about other skins. If I open TMDBhelper as an add-on the lists are displayed correctly. Thankyou

**Comment by jurialmunkey** [comment]
It's intentional.

However, see latest version (v2.2.45) - There is now an option in settings to enable nextpage item on widgets.
