### ISSUE TITLE
Episode groups option dissapeared

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#641]
While browsing some of my anime shows I realised the episode groups option is no longer available. Is there an option to enable now?

**Comment by jurialmunkey** [comment]
What version are you using? There's something weird occurring in the 4.5.40+ versions that I can't quite track down.

**Comment by juanma-cvega** [comment]
I think it's the .43 (my son is watching the PAW patrol right now), the
latest one available through the repo, but I've been noticing this for
quite some time now,  even before version .40.

**Comment by jurialmunkey** [comment]
Episode groups folder was being hidden if hide no airdates was enabled. But there's also some another issue with groupings themselves - looking for a solution now.

**Comment by jurialmunkey** [comment]
Okay I think that should fix things (hopefully!)

**Comment by juanma-cvega** [comment]
yes, it works now. thanks!
