### ISSUE TITLE
Trakt Next Up Episode Issue

### ISSUE THREAD

**Issue by jluftman** [jurialmunkey/plugin.video.themoviedb.helper#642]
One of my shows is displaying wrong episode in my TMDB Helper - Trakt Next Episodes
Show: Snowpiercer Should be Season 3 Episode 1 (The Tortoise and the Hare) but showing Season 3 Episode 3 (The First Blow).
Trakt support says it's an addon issue (of course!)
Uninstalled and reinstalled TMDB Helper (tried both 4.4.0 and 4.4.70). Reauthorized Trakt.  No change.
Log file seems to indicate info is pulling correctly. Any ideas?

    {
      "progress": 0.133477,
      "paused_at": "2022-02-07T18:32:12.000Z",
      "id": 826187867,
      "type": "episode",
      "episode": {
        "season": 3,
        "number": 1,
        "title": "The Tortoise and the Hare",
        "ids": {
          "trakt": 5673927,
          "tvdb": 8817975,
          "imdb": "tt13877192",
          "tmdb": 3320980,
          "tvrage": null
        }
      },
      "show": {
        "title": "Snowpiercer",
        "year": 2020,
        "ids": {
          "trakt": 136863,
          "slug": "snowpiercer",
          "tvdb": 364928,
          "imdb": "tt6156584",
          "tmdb": 79680,
          "tvrage": null
        }
      }
    },

**Comment by jurialmunkey** [comment]
4.4.70 is quite out of date. Please test with latest git version which is 4.5.49

**Comment by jurialmunkey** [comment]
>  Log file seems to indicate info is pulling correctly. Any ideas?

This looks like the output of watched history which isn't the endpoint used to find the next episode.

Please go to `TMDbHelper Settings > Expert > Log output of Trakt request` (you might need to scroll down to see the option) and then enter the following into the onscreen keyboard 
`shows/snowpiercer/progress/watched`

Then get me the `trakt_showssnowpiercerprogresswatched.json` file it generates which will be in 
`kodi/userdata/addon_data/plugin.video.themoviedb.helper/log_request/`

**Comment by jluftman** [comment]
Updated TMDBH to 4.5.43.  Log File attached (as txt since git won't paste json)
I see that the log shows episodes 1 & 2 complete="true" but Trakt dashboard shows correctly as unwatched.
Thanks for looking at this.  Really minor issue but would love to know if it's Trakt, TMDB or the addon.

[trakt_showssnowpiercerprogresswatched.json.TXT](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/8054743/trakt_showssnowpiercerprogresswatched.json.TXT)

**Comment by jurialmunkey** [comment]
> Updated TMDBH to 4.5.43

FYI There's a significant (unrelated) bug with playing files in version 4.5.42 to v.4.5.47 -- you should use the latest git version 4.5.49 installed from zip -- https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/refs/heads/matrix.zip

> Really minor issue but would love to know if it's Trakt, TMDB or the addon.

That's the raw data returned from Trakt, so it is a Trakt issue if you haven't watched the first two episodes. Specifically, I use the info that Trakt puts in the `next_episode` field which indicates that Your Next Episode to watch is Episode 3 as you can see below:

```
"next_episode": {
      "season": 3,
      "number": 3,
      "title": "The First Blow",
      "ids": {
        "trakt": 5789883,
        "tvdb": 8827265,
        "imdb": "tt15215394",
        "tmdb": 3409459,
        "tvrage": null
      }
```

**Comment by jluftman** [comment]
Thanks for looking!

**Comment by jluftman** [comment]
FYI... I sent log file to Trakt and they said their API is sending correct info and sent me the log.  I went back into TMDB and found the option to Delete Cache- Delete Trakt cache, ignored the warning, cleared and restarted Kodi and all is now right in the world!
