### ISSUE TITLE
[Request] Limit people list to 20 per page

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#644]
As the title says, this list should be limited to 20 per page, of course if possible. Some actors have over 100 movies in their careers and opening a list like this takes a very long time.

**Comment by jurialmunkey** [comment]
Do you mean the "Cast in Movies" etc. lists you get when clicking on an actor?

**Comment by matke-84** [comment]
> Do you mean the "Cast in Movies" etc. lists you get when clicking on an actor?

Yes, cast in movies, cast in tv shows....
