### ISSUE TITLE
api_language key not make difference

### ISSUE THREAD

**Issue by kolekan** [jurialmunkey/plugin.video.themoviedb.helper#645]
Hi jurialmunkey. Since version 4.5.32 the api_language key in players json file doesn't work as it should. No matter if i use or not api_language key in json, the search terms is translated to addon's settings api language and not use the json player api_language key.

**Comment by jurialmunkey** [comment]
Can you try 4.5.70? That should fix it.

**Comment by kolekan** [comment]
I just tried it and the problem has been fixed. Thank you very much for your work on this.
