### ISSUE TITLE
Change the image resolution

### ISSUE THREAD

**Issue by lebigboss** [jurialmunkey/plugin.video.themoviedb.helper#648]
Changing the image resolution

Hi, is it possible to add an option to change the resolution of the images because the addon consumes a lot of RAM on NVIDIA Shield.

Thanks a lot for this great addon

**Comment by jurialmunkey** [comment]
It already exists. Make sure you are using latest git version.

`TMDbHelper Settings > General > TMDb artwork quality`

**Comment by lebigboss** [comment]
Ok @jurialmunkey  thank you so much.
I was with the 4.5.7.
I don't know why but I don't have the update
Sorry for my question and have a nice d'ay.
