### ISSUE TITLE
(Request) Option to change number of items per page

### ISSUE THREAD

**Issue by brentonv** [jurialmunkey/plugin.video.themoviedb.helper#65]
Could you please consider adding an option to change the number of items per page. Default appears set to 20 items. Thankyou

**Comment by drinfernoo** [comment]
Read this issue, where he explains why he *didn't* do it that way: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/56

**Comment by brentonv** [comment]
Roger that
