### ISSUE TITLE
Ratings not showing

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#650]
I just realised ratings stopped showing in the addon but I'm not sure with which version this started happening.

**Comment by jurialmunkey** [comment]
Do you mean the service monitor ones (e.g. rotten tomatoes / metacritic etc. that come from OMDb?) - because those are working for me.

**Comment by juanma-cvega** [comment]
No, all of them. Right now I only see the number of stars (I'm not sure which one is that) on Horizon. I'm on version 76.

**Comment by jurialmunkey** [comment]
![Honeyview_screenshot00002](https://user-images.githubusercontent.com/4618719/154803339-5f0fa31b-ab6a-4102-a23c-93e7a10d4ec3.jpg)

Working fine for me on 4.6.1 (but should also be fine on 4.5.76 as it was mostly only a version bump for the repo). I deleted my OMDb cache to be certain it was working.

**Comment by juanma-cvega** [comment]
My bad, for whatever reason some of my skin settings were reset and the
ratings option was disabled.I'm closing the issue.
