### ISSUE TITLE
Thumbnails and Fanarts 

### ISSUE THREAD

**Issue by lebigboss** [jurialmunkey/plugin.video.themoviedb.helper#655]
Hello, is it possible to display the thumbnail instead of the fanart?
I'm on Auramod and TMDBHELPER 4.6.6
![Screenshot_20220221-103014](https://user-images.githubusercontent.com/12912677/154928397-15adbdc5-7516-4560-bbe8-d1242f5c0374.png)

**Comment by matke-84** [comment]
@lebigboss 
This needs to be changed in the skin, not in the tmdb helper.
Also try to turn on fanart.tv for artworks in tmdb helper if you haven't already.

**Comment by jurialmunkey** [comment]
@lebigboss - Yep, this is a question for the skinner. 

@matke-84 - FYI - Fanart.tv doesn't provide thumbs for episodes (it doesn't provide any episode specific artwork at all - only season/shows). All episode thumbs come from TMDb.

**Comment by matke-84** [comment]
@jurialmunkey 
I know, I just didn't notice that they were episodes, I thought they were tv shows.
