### ISSUE TITLE
Season 

### ISSUE THREAD

**Issue by Flyboy1035** [jurialmunkey/plugin.video.themoviedb.helper#658]
It is not adding all season to library when adding my list of tv shows

**Comment by jurialmunkey** [comment]
I'll need more information than that. Exact details of shows and which episodes. How do I recreate your issue?

Importantly I also need the library update logs from 
`kodi/userdata/addon_data/plugin.video.themoviedb.helper/log_library/`

Grab the most recent few and put in a zip file to upload here.

Also kodi.log of the update not working.
