### ISSUE TITLE
[Request] Add season and episode number to Your Next Episodes titles

### ISSUE THREAD

**Issue by 7E1EVEN** [jurialmunkey/plugin.video.themoviedb.helper#66]
Hey jurialmunkey,

I have a small request and these aren’t deal breakers so take all the time you need but,

Could you add the season and episode number in Your next episodes?
ex: “Show Title - **S01E01** - Episode Title”

Edit:
With the clear logos working it could also be “**S01E01** - Episode Title”.  

Also maybe, separate the option to hide unaired movies and tv episodes. 

It’s nice to see what this addon is becoming. Especially in combination with AZ2 (which I highly recommend for anyone who is on the fence.)
I can easily see this becoming one of the biggest things in the Kodi community. 

Once again thanks for your hard work.

**Comment by jurialmunkey** [comment]
Hmmm. I'm on the fence about this one. Not sure if it should be done in the addon or the skin. Though it's not possible to zero pad numbers in the skin, so maybe doing it in the addon is better.

**Comment by drinfernoo** [comment]
@jurialmunkey You could make it as a setting 😉

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey You could make it as a setting 😉

I think that's worse because then Skinners don't know what to expect from the label and lose control over how things are presented. It needs to be consistent

**Comment by 7E1EVEN** [comment]
> Hmmm. I'm on the fence about this one. Not sure if it should be done in the addon or the skin. Though it's not possible to zero pad numbers in the skin, so maybe doing it in the addon is better.

Alright, thanks for the reply.
I look forward to see what you come up with. 

How about the separation of the unaired movies and episodes?

**Comment by jurialmunkey** [comment]
@7E1EVEN - Please open separate issue threads for separate requests. I've created one here for separating movies/episodes https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/70

**Comment by jurialmunkey** [comment]
@7E1EVEN - Please test latest version. I've added season and episode numbers for episodes.

The format is `1x01. Title` for lists that mix seasons (e.g. calendar, up next, your next) and `01. Title` for a season list. This format is consistent with the Kodi library.

**Comment by 7E1EVEN** [comment]
> @7E1EVEN - Please open separate issue threads for separate requests. I've created one here for separating movies/episodes #70

Oh sorry, I’ll keep that in mind. 

I can see the season and episode number now. 

Thank you.
