### ISSUE TITLE
Showmax player (South Africa)

### ISSUE THREAD

**Issue by nroets1** [jurialmunkey/plugin.video.themoviedb.helper#660]
**Showmax** is a subscription based streaming service in South Africa. Here is a player for this:

```
{
    "name"              : "Showmax",
    "plugin"            : "plugin.video.showmax",
    "priority"          : 3,
    "is_resolvable"     : "true",
    "assert"            : {
                            "play_movie":       ["title", "year"],
                            "play_episode":     ["showname", "season", "episode"],
                            "search_movie":     ["title"],
                            "search_episode":   ["showname"]
                          },
    "play_movie"        : [
                            "plugin://plugin.video.showmax/?_=search&query={title}",
                            {"label": "(?i).*{title}.*"}
                          ],
    "play_episode"      : [
                            "plugin://plugin.video.showmax/?_=search&query={showname}",
                            {"label": "(?i).*{showname}.*"},
                            {"season": "{season}.*"},
                            {"season": "{season}", "episode": "{episode}"}
                          ],
    "search_movie"      : [
                            "plugin://plugin.video.showmax/?_=search&query={title}",
                            {"label": "(?i).*{title}.*"}
                          ],
    "search_episode"    : [
                            "plugin://plugin.video.showmax/?_=search&query={showname}",
                            {"label": "(?i).*{showname}.*"},
                            {"season": "{season}.*"}
                          ]
}
```

**Comment by jurialmunkey** [comment]
Hey thanks for this player. I was thinking about adding it to the defaults, I'm just wondering why you have a `.*` regex on season? `{"season": "{season}.*"}` -- Wouldn't this make season `1` also match `11` ?

Also for the `plugin://` parts you should probably use url encoded keys e.g. 
`"plugin://plugin.video.showmax/?_=search&query={title_url}",`

**Comment by nroets1** [comment]
Thank you. Yes, you are right. You may add it with that changes.

On 26 Feb 2022, 10:10, at 10:10, jurialmunkey ***@***.***> wrote:
>Hey thanks for this player. I was thinking about adding it to the
>defaults, I'm just wondering why you have a `.*` regex on season?
>`{"season": "{season}.*"}` -- Wouldn't this make season `1` also match
>`11` ?
>
>Also for the `plugin://` parts you should probably use url encoded keys
>e.g. 
>`"plugin://plugin.video.showmax/?_=search&query={title_url}",`
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/660#issuecomment-1051802937
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>
