### ISSUE TITLE
Issue with titles for the widgets

### ISSUE THREAD

**Issue by Guillaume5464** [jurialmunkey/plugin.video.themoviedb.helper#661]
Hi, 
I've got another issue but its about the title's label, when i change it, it takes my changes but keep the one written in the tmdb, for exemple the title of my widget is : "films à voir (my changes) films liste de suivi (tmdb)"
I don't know why. I noticed that with a previous version, I dont remember which one but then it was ok, with the 4.4.37 and came back from the 4.6.6.
So, Is it about the skin? Or from TMDB?
Thanks
![Inked155142926-262c9cae-a273-4bcb-be55-cd965a2aa0e5_LI](https://user-images.githubusercontent.com/85249544/155283912-9ef99b5a-93a5-4945-9ec7-39c5e3042e63.jpg)

**Comment by jurialmunkey** [comment]
Skin issue / skinshortcuts issue
