### ISSUE TITLE
number of widgets per page

### ISSUE THREAD

**Issue by shkope** [jurialmunkey/plugin.video.themoviedb.helper#662]
Hi, is it possible to increase the number of widgets per page limited here to 19?

**Comment by jurialmunkey** [comment]
TMDbHelper doesn't control how many widgets a skin can display.

If you are talking about the number of items each page of a list displays, no it is not possible to change the 20 item limit. The item limit is set by the TMDb api.

If you want to expand the limit for Trakt sync lists like collection, watchlist, in-progress and history, you can do that in the Trakt settings section.
