### ISSUE TITLE
poster key in players json issue

### ISSUE THREAD

**Issue by kolekan** [jurialmunkey/plugin.video.themoviedb.helper#663]
It seems that in the latest versions, poster key in players json has broken and nothing displayed as video thumb in video osd of my skin.

**Comment by jurialmunkey** [comment]
Can you try v4.6.11? I think that should fix the issue.

**Comment by kolekan** [comment]
Yes it works!! Have a good day!!

**Comment by matke-84** [comment]
@jurialmunkey 
I thought the artworks in osd depended on player being used. When I use elementum as a player, poster comes from elementum, not from tmdb helper.

**Comment by jurialmunkey** [comment]
@matke-84 - Most add-ons will supply their own artwork. However, it is possible to provide a `{poster_url}` or `{fanart_url}` key via the player json file for those add-ons which pass metadata directly through the `plugin://` uri

**Comment by matke-84** [comment]
@jurialmunkey 
Can a little help? :-)
`{
    "name" : "[COLOR FFFF6B00]Elementum[/COLOR]",
    "plugin" : "plugin.video.elementum",
    "priority" : 400,
    "play_movie" : "plugin://plugin.video.elementum/library/play/movie/{tmdb}",
    "play_episode" : "plugin://plugin.video.elementum/library/play/show/{tmdb}/season/{season}/episode/{episode}"
}`

**Comment by jurialmunkey** [comment]
> @jurialmunkey Can a little help? :-) `{ "name" : "[COLOR FFFF6B00]Elementum[/COLOR]", "plugin" : "plugin.video.elementum", "priority" : 400, "play_movie" : "plugin://plugin.video.elementum/library/play/movie/{tmdb}", "play_episode" : "plugin://plugin.video.elementum/library/play/show/{tmdb}/season/{season}/episode/{episode}" }`

It won't work for that add-on. It only works if the add-on has a `meta=` tag or similar.

You can see the type of addon that it works with here: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/652#issuecomment-1047073450

**Comment by matke-84** [comment]
@jurialmunkey 
Ok. Thanks.
