### ISSUE TITLE
More clearly label project/dev keys in expert

### ISSUE THREAD

**Issue by SerpentDrago** [jurialmunkey/plugin.video.themoviedb.helper#67]
Had a few ... users .. enter personal keys into  expert > tmdb / fanart  api key locations . 

I know users will always be kinda dumb . but mybee it can be more clearly labeled that those blanks are only for dev / project keys and NOT personal keys . 

I get it already says "only use if default api key is deactivate. " 

but mybee the error message that is then displayed "invalid key" could be more descriptive ? 

idk , if you think this is to much , you can't completely dumb  proof everything  . just close this issue . Just a thought

**Comment by jurialmunkey** [comment]
Yeah im tempted to just remove that section altogether... Children can't help but get their sticky hands all over it even though they've been told not to touch it.

**Comment by SerpentDrago** [comment]
I'm not opposed to that at all lol

**Comment by jurialmunkey** [comment]
Done!

**Comment by SerpentDrago** [comment]
8083d3c0416f058712ce3958c103a6afd5582a6d
