### ISSUE TITLE
Question. Discover by original_language(s)

### ISSUE THREAD

**Issue by jollyhiggler** [jurialmunkey/plugin.video.themoviedb.helper#670]
I've recently been using the Discover function to create a selection of movie nodes according to original_language.

In certain cases I would like to be able to group certain languages into the same search string: for example one "Nordic Cinema" node, rather than individual nodes for each language.

While the addon currently permits the selection of a single original_language as a rule of discovery, it seems the API may be able to cater for what I am trying to do: https://www.themoviedb.org/talk/59b1bbd2c3a3682c48083f32?language=en-GB 

I've tried various manual adjustments to the original search string but haven't managed to pull results for anything other than the first language in the list (in this case Danish):  

`plugin://plugin.video.themoviedb.helper/?info=discover&primary_release_date.gte=2011-01-01&sort_by=primary_release_date.desc&tmdb_type=movie&vote_average.gte=7&vote_count.gte=50&with_id=True&with_original_language=da|no|nb|nn|sv|fi|is&with_separator=OR&widget=True`

I'd be really grateful for any guidance on glaring errors in the above string as well as thoughts on the feasibility of enabling search by more than one original_language at a time within the addon's Discovery rules.

Cheers

**Comment by jurialmunkey** [comment]
You need to urlencode the pipe `|` as it is a special character. URL percent encoding for a pipe is `%7C`
e.g. `with_original_language=da%7Cno%7Cnb%7Cnn%7Csv%7Cfi%7Cis`

**Comment by jurialmunkey** [comment]
And ^^^ that commit should allow you to select multiple languages from the GUI.

I've made it so that original language setting is forced to always be OR and will ignore the Match: ALL setting. I figure that a movie generally only has one original language and this way you get more flexibility with the other rules.

**Comment by jurialmunkey** [comment]
@jollyhiggler - Just wondering if you had a chance to test that out yet? Once you confirm that it's working I'll close this issue.

**Comment by jollyhiggler** [comment]
> @jollyhiggler - Just wondering if you had a chance to test that out yet? Once you confirm that it's working I'll close this issue.

Yes - exactly what I was after. Many Thanks
