### ISSUE TITLE
Episodes keep disappearing multi installs.

### ISSUE THREAD

**Issue by Kylar514** [jurialmunkey/plugin.video.themoviedb.helper#671]
Running Nvidia Shield 2017 (updated to the latest android update, I just installed the hotfix released on 3/2/2022 a few moments ago)-Kodi 19.3 - AuraMod - TMDB - Trakt - Venom - Kaito

So just like the title says.  The episodes in the lists just completely disappear.  I made this build a couple of days ago, and within a few hours the episodes disappeared.  So I deleted Kodi, started all over again, and this time it worked for 24 hours, and then just now recently they all went poof again.  Tried to force updates, nothing.  Cleared caches of Kodi, and every cache I could find in side the app, and inside Android.  Not really sure where to go from here.  I found another use who ran into the exact same issue.  He reverted to Kodi 4.4.0 version of TMDB it worked for a few days and just now all his episodes disappeared again as well...

Side note.  I saw another user mention slow speeds on his android stick.  I also saw you mentioned latency from TBMD, especially from fanart.  So I am getting like anywhere from 20 seconds wait time to 3-7 seconds load time between each menu.  This includes when it isnt loading any artwork or details, just the menus like popular/trending/most played after selecting movie/tv shows.  Even when the artwork and details are in the cache it seems to take anywhere from 3-7 seconds to load up the menu and movies within submenus.  Is that still just the slow response time from TMDB's servers?   ISP is 500/500 on hardwire throughput network of 1gbps.

edit: about speed.  I am running it with post display, so it shows info and such.  But that doesnt seem to be making a differnce, no matter the way I list them, its all pretty much the same result...  I don't think the Shield is that underpowered... is it?  I was guessing it was the shield, but I can't say for sure.

**Comment by jurialmunkey** [comment]
What do you mean by episodes disappeared? In a specific list? In a normal tvshow? Is this in a widget? or inside TMDbHelper? Does this happen in Estuary?

A debug log would be useful here. Ideally with timer reports turned on.

**Comment by Kylar514** [comment]
> What do you mean by episodes disappeared?

Every episode for every tv show listed within TMDB addon, has 0 tv shows listed.  Pending the sub menu I access it will either load no seasons, or various seasons (1,2,3 etc), but each season has no episodes listed when selecting them. This same happens when I scroll down to Trakt submenu, and pull from Trakt sources within the TMDB addon.  Now if I pull from a different addon, not TMDB, that uses Trakt or IMDB, I can see every season and episode as intended.

> In a specific list? In a normal tvshow? Is this in a widget? or inside TMDbHelper?

Every list, for every tv show, within TMDB Helper addon.  I do use AutoWidget with Auramod skin, although my autowidget path locations are not going through TMDB, but rather specific other addons.  When using other path locations it does seem to work fine in the widget.  But if I set up a widget to use a TMDB Helper path location through TMDB addon itself, it will do the same thing.

>Does this happen in Estuary?

Yes.  

>A debug log would be useful here. Ideally with timer reports turned on.

Not sure if this is possible, unless you know something I dont.  Latest Android updates restrict access to Android/data folder location, read and write.  I don't know if Kodi is able to write there, but regardless, I cant see in side that folder, across multiple file explorers and attempting to access over the network, I also don't see a way to change the log location in Kodi. I did however link this thread to the other user who is having the same symptoms as me, I suspect its the same issue.  He uses the "cosmic" skin.  Hopefully he will have better luck getting the log files.

In the meantime I am going to try and set up my exact build on my PC.  perhaps I can generate the same issue if I follow the same steps and then generate a log to help us determine the issue, its the only other way I see to move forward here.

edit: I did install jurialmunkey alpha repo through [SerpentDrago's repo for AuraMod](https://github.com/SerpentDrago/skin.auramod/tree/Matrix), which included your repo.  its all updated to the latest TMDB.  Dunno if that would make a difference

**Comment by Kylar514** [comment]
[SerpentDrago's repo for AuraMod](url)

**Comment by matke-84** [comment]
@Kylar514
I don't know which version of android you have. I have android tv 9 and i use it X-plore file manager and I have access to kodi log without root. Also as far as I know there are some log viewers (addons) for kodi.

**Comment by Kylar514** [comment]
@matke-84 
Android 11, it seems to be a common issue.  Might be Nvidia Shield specific, not sure.
Log Viewer addon worked, was able to get it to export to my desktop, ALTHOUGH, seems the problem fixed itself?  Wasn't working, so I went to the store, ate lunch, came back, boom working flawlessly... so no clue lol.  Only things that have changed was me starting my VPN on the shield, and installing that log viewer addon.

**Comment by jurialmunkey** [comment]
https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader
Use that addon to upload a log of you attempting to open episodes from a few different types of lists. 

Without a log I can't help as I've never seen this issue and have no way to recreate it. I play all my content on kodi via tmdbhelper (both library and addons) and primarily watch tvshows so it's something I would notice if it happened to me since I use it everyday. It has to be something system related and I'd need a log to diagnose that.

Also what settings do you have for hide unaired and trakt indicators do you have?

**Comment by matke-84** [comment]
@Kylar514
Android 11 has a lot of problems.
As for the speed of opening lists in tmdb helper, I agree that it needs a little more acceleration on android, but it is also much improved compared to previous versions. That's why our friend @jurialmunkey needs time report logs in order to try to improve that part of our beloved addon if possible. Maybe you should switch here for that issue https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/617

**Comment by Kylar514** [comment]
@jurialmunkey So like said for what ever reason its working now, I dont think its anything I did..  This is my first time playing with Kodi, so im learning as i go, and I am trying to set up widgets and the UI in a way that suits my wife and I.

Since its happened to me 2x in the past 2 days, I am fairly confident it'll happen again, and once it does, i'll get a log to you.

In TMDB settings, NAvigation>Content both 'hide unaired movies' & 'hide unaired episodes' are not checked, so all unaired stuff should populate if there is metadata.

As for Trakt data in TMDB under accounts, I have all checked except scrobble local files, as I have no local files that go through Kodi.

**Comment by jurialmunkey** [comment]
@Kylar514 - Apologies, I think you must've commented after I'd already opened up the issue and I didn't notice that you'd made a further comment!

Yes please a debug log if/when you get it to happen again. 

FYI - The progress indicator option is a new feature in Kodi and I've noticed that the implementation in Matrix is still a bit buggy (not in TMDbH but in Kodi itself). Watched indicators are fine (e.g. checkmarks and episode counts) it's just the percentage progress that's new and a bit buggy.

Occasionally the progress indicator being set will cause the metadata for the item to disappear and the item will be completely blank. I've never seen it cause the items themselves to disappear though, so it's a bit of a longshot guess but possible it has different side effects on other systems.
