### ISSUE TITLE
Errors in kodi matrix 19.4

### ISSUE THREAD

**Issue by baltzis** [jurialmunkey/plugin.video.themoviedb.helper#677]
In the new version of Kodi Matrix (19.4) the plugin produces errors when trying to invoke some addons, for e.g. FEN. When running the addon, no errors are produced.

Here is the log for the error:
2022-03-09 15:23:55.353 T:5740    ERROR <general>: EXCEPTION Thrown (PythonToCppException) :
-->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'KeyError'>
Error Contents: 'media_type'
Traceback (most recent call last):
File "D:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\fen.py", line 4, in <module>
routing(argv[2])
File "D:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\modules\router.py", line 60, in routing
Sources().playback_prep(params)
File "D:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\modules\sources.py", line 48, in playback_prep
self.media_type = self.params['media_type']
KeyError: 'media_type'
-->End of Python script error report<--

**Comment by drinfernoo** [comment]
This is an issue with the player, not with TMDbHelper or Fen.

**Comment by trowieuk** [comment]
> This is an issue with the player, not with TMDbHelper or Fen.

I haven't updated my kodi and I get the same issue, haven't changed anything from when it last worked. If it was a player issue wouldn't it be because of an kodi update?

**Comment by jurialmunkey** [comment]
> > This is an issue with the player, not with TMDbHelper or Fen.
> 
> I haven't updated my kodi and I get the same issue, haven't changed anything from when it last worked. If it was a player issue wouldn't it be because of an kodi update?

Looks like the Fen addon has been updated and now expects a `media_type` key in the URI. You'd need to change the player to match the new format fen expects
