### ISSUE TITLE
Not an issue.... more of a query.....

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/plugin.video.themoviedb.helper#678]
Hey,
I'm using an FireCube with an external USB connected. To try and save space, now I have added a path sub for my thumbs to go there, but if I also add the follow below, will that screw anything up? Just the database_v4 had about 600mb of data in it.

Cheers in advance. 

      <pathsubstitution>
         <substitute>
           <from>special://profile/addon_data/plugin.video.themoviedb.helper/database_v4/</from>
           <to>/storage/5808-12EC/Android/data/org.xbmc.kodi/plugin.video.themoviedb.helper/database_v4</to>
         </substitute>
      </pathsubstitution>  
    </advancedsettings>

**Comment by jurialmunkey** [comment]
I _think_ it should be fine. The cache uses Kodi's builtin virtual file system module - xbmcvfs - to translate the path location, so it should work but I've never tried something like that before.

It definitely won't hurt to try! Just delete the database folder and then start kodi/tmdbhelper and see if the database files get created in the new location without errors (and not in the old one).

If there's an issue just let me know and I can add a setting inside tmdbhelper to change cache location instead.

**Comment by adamosborne83** [comment]
> I _think_ it should be fine. The cache uses Kodi's builtin virtual file system module - xbmcvfs - to translate the path location, so it should work but I've never tried something like that before.
> 
> It definitely won't hurt to try! Just delete the database folder and then start kodi/tmdbhelper and see if the database files get created in the new location without errors (and not in the old one).
> 
> If there's an issue just let me know and I can add a setting inside tmdbhelper to change cache location instead.

Thank you for your reply, I am afraid that the database_v4 folder keeps coming up and that the pathsubstitution folder did not have anything in.

If you'd be so kind as to be able tonadd the feature to move the cache, then you'd be amazing.

**Comment by jurialmunkey** [comment]
^^ Latest should give you an option under Expert Settings to change the cache database location. It won't transfer your existing database, so you'll need to delete the old files manually. Whatever folder you choose, it will make a "database_v4" sub-folder inside it (just in case you want to transfer your database files to the new location rather than delete and make new ones).

I tested using the local drive and it appears to work fine. It should be fine on a usb drive but you'll need to make sure that the usb location is persistent. 

Depending on the USB version supported by the drive, performance might be slightly reduced. All disk cache operations are also written to memory though, so it should only impact performance on initial read from cache (e.g. if something was cached last time you had Kodi open, then that lookup might be slightly slower - but anything that subsequently was cached/looked up in the current session will also go to memory which is fast).

**Comment by adamosborne83** [comment]
Works a bloody treat, thank you. No noticeable loading increase either.

**Comment by jurialmunkey** [comment]
> Works a bloody treat, thank you. No noticeable loading increase either.

Great! Let me know if there are any issues but it should be fine as long as the usb stays connected in the same location.

**Comment by adamosborne83** [comment]
> > Works a bloody treat, thank you. No noticeable loading increase either.
> 
> Great! Let me know if there are any issues but it should be fine as long as the usb stays connected in the same location.

Good evening,

Now this might be a total coincidence, but since I have moved the info to my static usb, I get a lot of kodi crashes about 3 seconds into a movie, now I've spoken to Doc and Venom and they're both at a loss, but some RD related but thus happens on all movies, I've added a couple of logs below.

If you can help......

https://paste.kodi.tv/agatipuhuv
https://paste.kodi.tv/morohugihe
https://paste.kodi.tv/tecirexabu
https://paste.kodi.tv/pakuqigayo

**Comment by jurialmunkey** [comment]
I think it might be a coinincedence. Can't see anything much TMDbH related at all. I can see it does a cache clean up which completes successfully, so if anything that indicates that it isn't having any problems and can access the usb storage completely fine. If there was going to be any errors that's where it'd be as sqlite vacuum is fairly disk io intensive but it's completing without issue well before the crash. 

Venom is generating a lot of invalid handle messages and I also noticed metadatautils errors too (I'm guessing that's the module venom uses to get metadata on playback). Invalid handle error is usually not an issue but strikes me as odd the sheer volume being generated (handle is what kodi uses to tell two different plugin folders of items apart - basically a widget id)
