### ISSUE TITLE
Error not letting me authenticate Trakt

### ISSUE THREAD

**Issue by GodsLikelyMe** [jurialmunkey/plugin.video.themoviedb.helper#679]
After doing a completely fresh install due to some unrelated issues, TMDB helper is not letting me authenticate trakt. It just pops up the same error. 

Log
https://paste.kodi.tv/igezixijaf.kodi

Kodi - 19.4
TMDB helper - 4.6.32

**Comment by jurialmunkey** [comment]
Oops! Accidentally deleted the module import - ^ 4.6.33 should fix it.

**Comment by GodsLikelyMe** [comment]
Lol. Thanks
