### ISSUE TITLE
[Request] Play local files from lists other than My TV Shows and My Movies

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#68]
Hi,
Is there anyway to default to try to play a local file when navigating through a list (for instance the Popular TV Shows list)? 
In my case, my library comes from video files stored in Plex but made available through PlexKodiConnect. I think files are treated as local files when imported anyway but may be linked to #50 . 
Thanks.

**Comment by juanma-cvega** [comment]
Well, apparently it does do it. It seems a problem with OpenInfo and TV shows though. The Netflix view (that's the only one I tested on) doesn't recognize local files when searching through season's episodes. But it works with films. So nothing to do with your addon.

**Comment by juanma-cvega** [comment]
I reopened it because I found out it kind of works but I realised, after checking 5 TV seasons, that it doesn't find all episodes. Sometimes it finds the 10 episodes, some times 9 or like with Grey's anatomy it was able to find the first season but after half the second, the rest it falls back to Seren as if there were any more episodes in the library.
Could it be related to the size of the library? The Plex server I connect to has like 200000 episodes. I'm using a Amazon Fire TV Cube 2nd generation.

**Comment by jurialmunkey** [comment]
Hard to say without a debug log. Also please turn on debug logging in the TMDbHelper expert settings.

You can also try turning on fuzzy matches in the Player settings. Sometimes the Year in the library doesn't match the Year retrieved from TMDb. Although that would be unusual if some episodes are playing and not others.

It won't have anything to do with library size.

**Comment by juanma-cvega** [comment]
Sorry, I was busy yesterday and I couldn't reply back. I'll try to get the logs this weekend. 
I don't think it has nothing to do with the year actually. Files found are always consecutive and the last one found could be in the middle of a season.

**Comment by juanma-cvega** [comment]
I going to close the issue. I'm still not sure what happened but I think it's a mix between the skin not showing data for every episode and the PlexKodiConnect disconnecting. I tested this weekend and the episodes that didn't work the other day now work.
