### ISSUE TITLE
Multiple Networks

### ISSUE THREAD

**Issue by Fabrice19730526** [jurialmunkey/plugin.video.themoviedb.helper#682]
Kodi 19.4 TheMovieDB Helper 4.6.4.1

In Discover Search : Multiple Networks selected will give as a result all networks content.

Same issue if added in the URL by using */*.

**Comment by jurialmunkey** [comment]
The API doesn't provide any way to search for network ids. So for networks you need to look up the ids on TMDb manually and input the ID directly.

Note networks are different to companies/studios. To make it more complicated some networks also have studios eg Netflix or Apple tv+ and the studio will have a different id to the network so you need to make sure to use the right one.

**Comment by Fabrice19730526** [comment]
Some misunderstanding here...

Please go to Discover Menu/Discover TV Shows/Add Rule/With Networks.
e.g.
Then Type 4 for the BBC then "/" followed by 213 for Netflix will provide all networks content rather than these 2 providers.

I've tried to edit the URL &with_networks=4/213 without success or using the pipe as a separator but no luck either.

One network ID search is fine but not multiple ones. 

Hope that makes more sense :)

**Comment by jurialmunkey** [comment]
> One network ID search is fine but not multiple ones.

Ah, I see. Should be fixed now in v4.6.43
Note that the `/` needs to have spaces e.g. `4 / 213` not `4/213`

I've set `with_networks` to always use OR matching since tvshows typically only have one network and it'd be fairly uncommon to want to use AND there. That way it's possible to choose multiple networks but still use "Match ALL rules"

**Comment by Fabrice19730526** [comment]
Perfect. Thank you so much!
