### ISSUE TITLE
[suggestion] reduce size of some trakt lists

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#683]
My opinion is that there is a lot of scrolling, I think that the trakt popular and trending lists have over 200 lists inside. Maybe it should be reduced to 50-100.
![popular](https://user-images.githubusercontent.com/74268331/159493028-6bda65f7-ef45-4c7e-82a1-a5f24cf84b8e.png)

**Comment by ambulancePilot** [comment]
I disagree. There isn't any difference between 100 items or 200 items in terms of scrolling, and in this case I would prefer to have more to choose from.

**Comment by matke-84** [comment]
@ambulancePilot
I didn't mean to exclude lists from the list selection, but to reduce the number of lists per page. It's easier to scroll on a computer, but on some other devices like a TV or TV box with a remote, it's a much more tedious job.

**Comment by jurialmunkey** [comment]
Doesn't the skin you're using have a scrollbar?

My primary setup is loungeroom tv with a remote and I have no issue scrolling using the scrollbar.

Also I'm not sure I understand how having fewer items makes scrolling easier. if the lists were sorted alphabetically it'd make sense to help find a specific letter but the lists are sorted by popularity so you can really only browse - in which case I would've thought larger page size would be better.

**Comment by matke-84** [comment]
@jurialmunkey
I don't know, it's much clearer to me that there is less content on the page. It’s similar with websites, I don’t like sites that scroll infinity. But it's all a matter of taste. I just suggested. It's not big deal.
