### ISSUE TITLE
Sorting trakt list

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#685]
I'm using the following trakt list:-

`plugin://plugin.video.themoviedb.helper/?info=trakt_anticipated&amp;tmdb_type=tv&amp;widget=true`

![trakt](https://user-images.githubusercontent.com/4118048/160393097-090aa7a0-b4c0-4e7a-8176-ddde76139c92.jpg)

The items have a ListItem.Premiered entry but Kodi is unable to sort list content using this method, could we please get the ListItem.Premiered copied into the ListItem.Date entry so that sorting is possible. Also for any items without a ListItem.Premiered value could we get a fake value way off in the future so they get sorted to the end of the list.

Thanks

**Comment by jurialmunkey** [comment]
Have you tried `sortby="year"` in your `<content>` tags as that should sort by premiered date (date is filesystem creation date not air date of the item).

**Comment by roidy** [comment]
>Have you tried sortby="year" in your <content> tags as that should sort by premiered date

Thanks, that worked.... Which is strange because if I output ListItem.Year I only get the year not the full date, so how does that sorting method work?

Also one more quick question. When filling a widget with:-

`plugin://plugin.video.themoviedb.helper/?info=trakt_anticipated&amp;tmdb_type=tv&amp;widget=true`

From the ListItem's info labels or properties is there a way to return the plugin path or just the `info=trakt_anticipated` portion so I can detect it and layout the list items differently?

**Comment by jurialmunkey** [comment]
> Thanks, that worked.... Which is strange because if I output ListItem.Year I only get the year not the full date, so how does that sorting method work?

It's defined in core here: https://github.com/xbmc/xbmc/blob/7e5881c26e4ad69dedec603d3ef6e951f7f3ce5a/xbmc/utils/SortUtils.cpp#L726-L730

Basically it sorts year > airdate > album > tracknumber > origdate


> From the ListItem's info labels or properties is there a way to return the plugin path or just the info=trakt_anticipated portion so I can detect it and layout the list items differently?

`ListItem.Property(Param.Info)` from the listitem. 
`Container.Property(Param.Info)` from the container -- container property only works for main container in MyNav windows, it doesn't allow specifying an ID for a widget. However, you can use `Container(ID).ListItem.Property(param.info)` instead.

Also this should work for any params (there are a couple of special ones that aren't passed through but most are).

**Comment by roidy** [comment]
>ListItem.Property(Param.Info) from the listitem.

Perfect, exactly what I needed, thanks👍

Is that in the wiki? I looked but couldn't seem to find any mention of it.
