### ISSUE TITLE
Back navigation issue

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#686]
If I open a plugin path using ActivateWindow from a custom window like so:-

ActivateWindow(Videos,plugin://plugin.video.themoviedb.helper?info=trakt_calendar&amp;startdate=-1&amp;days=14)

When I press back I end up at the root of plugin.video.themoviedb.helper and not back at the location I called the activate window function from.

Any help please.

**Comment by jurialmunkey** [comment]
Specify "return" parameter in ActivateWindow sets the path as root. Works for everything, not just tmdbhelper. 

`Activatewindow(videos, videodb://movies/titles, return)`
https://kodi.wiki/view/List_of_built-in_functions#GUI_built-in.27s

**Comment by roidy** [comment]
~~D'Oh! I can't believe I missed the return.... That's what happens when you stare at the same block of code for too long. Thanks 👍~~

No, actually I have return in the activatewindow function.  It's from a skinshortcuts submenu, this is the item from the include:-

```
<item id="2">
	<property name="id">$NUMBER[2]</property>
	<property name="mainmenuid">8</property>
	<label>Next 14 Days</label>
	<label2 />
	<icon>DefaultShortcut.png</icon>
	<thumb />
	<property name="labelID">next10days</property>
	<property name="defaultID">next10days</property>
	<onclick>ActivateWindow(Videos,plugin://plugin.video.themoviedb.helper?info=trakt_calendar&amp;startdate=-1&amp;days=14,return)</onclick>
	<property name="path">ActivateWindow(Videos,plugin://plugin.video.themoviedb.helper?info=trakt_calendar&amp;startdate=-1&amp;days=14,return)</property>
	<property name="list">plugin://plugin.video.themoviedb.helper?info=trakt_calendar&amp;startdate=-1&amp;days=14</property>
	<visible>String.IsEqual(System.ProfileName,Master user)</visible>
	<property name="group">tvshowsubmenu</property>
	<property name="isSubmenu">True</property>
</item>
```
This video demos the issue I'm having:-  https://streamable.com/oow11g

1. Starting in my TV Show hub I press "Next 10 Days" which then takes me to the correct  plugin location.
2. I then press back which just reloads the current plugin path.
3. I then press back again which takes me to the root of the plugin
4. One last press of back then takes me back to the correct start location.

**Comment by roidy** [comment]
Ok, finally figured it out, I was missing a forward slash at the end of the plugin name.

This fails, missing the / before ?info
`plugin://plugin.video.themoviedb.helper?info=trakt_calendar&amp;startdate=-1&amp;days=14`

This works
`plugin://plugin.video.themoviedb.helper/?info=trakt_calendar&amp;startdate=-1&amp;days=14`

Sorry, my fault :D
