### ISSUE TITLE
Short day and date for last and next aired

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#688]
In the trakt calendar we get both

ListItem.Property(air_day_short)
ListItem.Property(air_date_short)

Wed 06 Apr

Could we also get this format for item detail last_aired and next_aired and the window property versions please

**Comment by jurialmunkey** [comment]
Those should already be in kodi system short format by default.

**Comment by jurialmunkey** [comment]
Sorry, I see what you're saying now - you want `%d %b` formatting not system shortdate which is usually `dd/mm/yyyy` or similar.

Added in latest `next_aired.short` (and same for last_aired) - you'll need to refresh item details for already cached items to see changes.

**Comment by roidy** [comment]
Sorry to be a nuisance but I also need the short version of the day name.

In the trakt calendar 
ListItem.Property(air_day) - gives 'Monday'
ListItem.Property(air_day_short) - gives 'Mon'

I need the same for item details
ListItem.Properety(next_aired.day) - gives 'Monday'
ListItem.Property(next_aired.day.short) - There is no short version :(

Also could we get the day number without the leading zero %-d
It's easy to add the leading zero using a variable if you want it, but impossible to remove it.

Thanks
