### ISSUE TITLE
[Request] Option to flatten seasons

### ISSUE THREAD

**Issue by brentonv** [jurialmunkey/plugin.video.themoviedb.helper#69]
Could I please request an option to flatten seasons. Alll add-ons in my setup have this option except TMDB helper. Thankyou

**Comment by jurialmunkey** [comment]
Shouldn't be too difficult to achieve. I'll have a look and let you know once it's implemented.

**Comment by brentonv** [comment]
Thankyou very much. Could you please also try option to disable tv show specials? This would consistent with other add-ons. The main reason is that most of them don't play anyway and usually show on list before season 01 pilot episode. Thankyou

**Comment by jurialmunkey** [comment]
@brentonv - Please try latest version. There is now an option in settings to flatten seasons.

**Comment by brentonv** [comment]
Thanks mate will check it out when home

**Comment by brentonv** [comment]
Sorry for the delay I was waiting for update but installed from source and it's working great. I also appreciate the option to hide unaired. Coukd you also hide specials? Is that possible. Thanks heaps mate!

**Comment by jurialmunkey** [comment]
> 
> 
>  Coukd you also hide specials?

Specials should already be hidden if you have flatten seasons on.

**Comment by brentonv** [comment]
Thanks again
