### ISSUE TITLE
Can't get any YouTube video to play

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#691]
From the following list, which gives videos like trailers etc:-

plugin://plugin.video.themoviedb.helper?info=videos&amp;type=movie&amp;imdb_id=$INFO[ListItem.IMDBNumber]

I can't get any video to play, just keep getting a notification saying "Youtube, this video is unavailable". However the exact same video plays perfectly fine from script.embuary.info

Any idea what's wrong?

**Comment by roidy** [comment]
After some more digging:-

Scrapped library trailer from Kodi, that plays perfectly fine:-
`plugin://plugin.video.youtube/?action=play_video&videoid=Lg69veY4kNA`

Same trailer from themoviedb.helper, that doesn't play:-
`plugin://plugin.video.youtube/play/?video_id=Lg69veY4kNA&tmdb_type=video&tmdb_id=103992`

Not sure why your YouTube plugin path is formatted differently from the Kodi one.

**Comment by roidy** [comment]
So after taking apart Embuary Info it seems is uses the following to play YouTube video

`xbmc.Player().play('plugin://plugin.video.youtube/play/?video_id=%s' % xbmc.getInfoLabel('Container(%s).ListItem.Property(ytid)' % controlId))`

The only difference is your plugin path contains tmdb_type and tmdb_id at the end, why would the YouTube addon need that information?

So adding a button to my skin that runs:-

`RunPlugin(plugin://plugin.video.youtube/play/?video_id=Lg69veY4kNA&tmdb_type=video&tmdb_id=103992)`

The video plays fine, so the extra information at the end isn't the problem.

----------------------------------------------------------

So from your videos list I get the following info labels

ListItem.FolderPath =`plugin://plugin.video.youtube/play/?video_id=Lg69veY4kNA&tmdb_type=video&tmdb_id=103992`

Which I assumed was the path that gets played when the item is clicked....

But I also get:-

ListItem.Path = `plugin://plugin.video.youtube/play/`

Which has no video id information. I'm at a loss, I just can't figure out why none of the YouTube video from this addon will play :(

**Comment by jurialmunkey** [comment]
Ah I forgot to set `-1` flag for videos to ignore adding parent item params when constructing the path url. Must've left it out accidentally when I rewrote the container class recently.

v4.6.50 should fix it. Can you test?

PS - ListItem.Path is correct. FileNameAndPath is full path whereas Path is everything before the `?` for plugins

**Comment by roidy** [comment]
Thanks, so the videos do play now, however I'm getting an error notification, and this in the log:-

```
2022-04-12 05:22:13.025 T:360     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: get_items() missing 1 required positional argument: 'tmdb_type'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/plugin.py", line 8, in <module>
                                                       Router().run()
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/items/router.py", line 49, in run
                                                       self.get_directory()
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/addon/modimp.py", line 22, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/items/router.py", line 42, in get_directory
                                                       container.get_directory()
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/items/container.py", line 218, in get_directory
                                                       items = self.get_items(**self.params)
                                                   TypeError: get_items() missing 1 required positional argument: 'tmdb_type'
                                                   -->End of Python script error report<--
```

Also from DialogVideoInfo.xml the video starts in the background and you have to press back before you can see it. How do you get the video to play on top, or how do you close DialogVideoInfo.xml when the video starts?

-------------------------------------------------------------------
Ok, so after some playing around I can get the media to play on top by first closing the Dialog and then playing the video using either:-

```
<onclick>Dialog.Close(all,true)</onclick>
<onclick>RunPlugin($INFO[ListItem.FileNameAndPath])</onclick>
```

or 

```
<onclick>Dialog.Close(all,true)</onclick>
<onclick>PlayMedia($INFO[ListItem.FileNameAndPath])</onclick>
```

Which is the best method, RunPlugin or PlayMedia or is there a better solution?

**Comment by jurialmunkey** [comment]
That error means that the `&tmdb_type=` param is missing or blank in your `info=videos` widget container path. `&type=` is also fine to use instead (it's an alias for tmdb_type for legacy compatibility with Leia version of TMDbH). However, I will eventually depreciate `&type=` in favour of `&tmdb_type=` so may as well use tmdb_type since it is standard in TMDbH for Matrix.

Careful if you're using nested variables (i.e. variable inside variable) to set tmdb_type= or type=. Nested variables will be blank when other dialogs have focus due to a Kodi bug with $VAR[] - so that could be the reason for your type being blank.

In terms of play method, it isn't possible to play fullscreen without closing the dialog - Even if you play and toggle fullscreen after, the video info dialog still gets closed by Kodi.

PlayMedia is probably slightly better but it shouldn't really matter if you use RunPlugin instead. Also, you can specify 12003 for the videoinfo dialog window ID to avoid closing other dialogs unnecessarily.
```
<onclick>Dialog.Close(12003,true)</onclick>
<onclick>PlayMedia($INFO[ListItem.FileNameAndPath])</onclick>
```

**Comment by roidy** [comment]
Yep, it appears to be a nested $VAR issue, if I hard code the type then there is no error. Closing the dialog also seems to fix the error as I'm guessing the plugin content no longer reloads. This doesn't solve the error for any widget that doesn't close the dialog.... I may need to un-nest my vars and write them all out long hand :(

It's a shame from a usability point of view that DialogVideoInfo is a dialog and not a window and thus has to close and can't be returned to after the video plays.
