### ISSUE TITLE
Default players menu not opening

### ISSUE THREAD

**Issue by thefrench1** [jurialmunkey/plugin.video.themoviedb.helper#693]
Hi just been updating my players to use another add-on but the default players option in the settings is not working as it gives an error when you click to open them

**Comment by jurialmunkey** [comment]
Debug log?

**Comment by thefrench1** [comment]
> Debug log?

Sorry how would one get a debug log please never had to send one before. Even tried a fresh install on my android phone and took a few attempts at installing and gave an error just after the install.

**Comment by jurialmunkey** [comment]
Use Kodi log file uploader
https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

Alternatively you can get the log file directly
https://kodi.wiki/view/Log_file#Log_file_location

Upload to https://paste.kodi.tv/

**Comment by jurialmunkey** [comment]
Please try latest git version of TMDbHelper `v4.6.59`. Likely an attribute error so should be fixed now.

**Comment by thefrench1** [comment]
> Please try latest git version of TMDbHelper `v4.6.59`. Likely an attribute error so should be fixed now.

Hi sorry for the late reply. Rebooted my router and did. A fresh install on one device and it's all good now. My other device worked fine after I rebooted the router. As always thanks for the. Quick replys and all the time you spend on creating this amazing add-on.
