### ISSUE TITLE
[Request] Separate unaired movies / episodes option

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/plugin.video.themoviedb.helper#70]
As requested by @7E1EVEN here https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/66#issuecomment-580375621

> 
> How about the separation of the unaired movies and episodes?

**Comment by jurialmunkey** [comment]
@7E1EVEN - I've now separated the options. Please test latest and confirm that it is working correctly.

**Comment by 7E1EVEN** [comment]
I can confirm, it’s working. 

Thanks, JM, you’re the best!
