### ISSUE TITLE
Add author of Trakt liked lists

### ISSUE THREAD

**Issue by SirRickie** [jurialmunkey/plugin.video.themoviedb.helper#700]
Going into the addon 4.7.11, going to Trakt, there is "liked lists". Is it possible to add, next to a list, the author of the list ? Tnx.

**Comment by jurialmunkey** [comment]
Please try v4.7.15
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.7.15

List author is now added as `ListItem.Studio` and Label2 mask is set to `%U` so will also display studio in `ListItem.Label2` for skins which display label2 in list (test with Arctic Horizon and it works in list view there).

**Comment by SirRickie** [comment]
I'm running 4.7.20, list author is not showing up. The skin I'm using is Estuary Mod latest version, list view (3.4.0 + matrix 12). Could this skin be the reason that the author is not showing up ? Tnx.
