### ISSUE TITLE
[Feature] Add Most Watched This Week Lists for Movies and TV Shows

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/plugin.video.themoviedb.helper#701]
Hi @jurialmunkey,

First of all thanks a lot for this amazing addon!

A small request. Could you please add "Most Watched This Week" Lists from Trakt/TMDB for both Movies and TV Shows? I'd like to use these lists for displaying the Top 10 Movies/TV Shows of the week as widgets?

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
`Trakt > Most Played`
`TMDb > Trending this Week`

Trakt Most Played is already based on weekly stats. 

TMDb doesn't collect watch data but trending will show you what items have had the most activity.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

I'm already using the TMDB Trending Movies and TV Shows lists as separate widgets and they are always up-to-date.

However, Trakt Most Played and Most Watched this week are not the same. Most played means the videos which were played the highest number of times and Most Watched means the videos which were watched by most number of people. Therefore, my request is if you could add the Trakt Most Watched Movies/TV Shows lists along with the Most Played ones that already exist? This will be really helpful for me.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
I don't see how there would be much of a difference between these two. Most people are only going to watch something once so 1 play = 1 person for the most part.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Actually there's a lot of difference between Most Watched and Most Played, especially in case of TV Shows. See below screenshots from another addon which has both these lists and they are very different:

Most Watched:

![IMG20220424142932](https://user-images.githubusercontent.com/65297828/164968859-556ac1b9-f1a1-47b5-b746-73382c59f598.jpg)

Most Played:

![IMG20220424143036](https://user-images.githubusercontent.com/65297828/164968869-81901016-1830-4e1a-b52a-9d44b9911c36.jpg)

As you can see from the above screenshots, Most Watched has more latest TV Shows compared to Most Played and therefore is more accurate. What do you think? Kindly advise.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Movies is practically exactly the same. But yes there is a difference for TvShows. Most Watched is basically Trending though. Easy enough to add either way.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Thank you so much for adding "Most Watched" lists for both Movies and TV Shows so swiftly! 🙂

Thanks and Regards,
ShibajiCh.
