### ISSUE TITLE
[Feature] Add Multiselect Genres option

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/plugin.video.themoviedb.helper#702]
Hi @jurialmunkey,

Hope you're doing well.

Could you please add an option for "Multiselect Genres" under Genres so that we can combine and select multiple genres together?

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
You can do this in Discover already
`TMDbHelper > Discover > Discover Movies/TVShows`

- Choose `Add Rule > with_genres`
- Select your genres and press OK. 
- Choose `Match` to toggle whether to match ALL or ANY of the selected genres.
- Then select "Discover Movies w/ Below Settings" to see the results.

You can also save your settings as a preset for future use (e.g. to use as a widget).

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Thanks for the info! That's very helpful and sorted my another requirement.
However, actually what I wanted was something like the below screenshot:

![IMG20220424134342](https://user-images.githubusercontent.com/65297828/164966998-be785e67-a792-4963-aa15-d8edfd5cd588.jpg)

As you can see from the screenshot, I wanted the Multiselect Genres option to be available along with the Genres widget, so the user can choose from the same widget whether to select a particular genre or Multiselect multiple genres. Is this possible in TMDB Helper? Kindly advise.

Thanks and Regards
ShibajiCh.
