### ISSUE TITLE
[BUG] info=fanart doesn't set Param.Info 

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#703]
plugin://plugin.video.themoviedb.helper/?info=fanart

Doesn't set ListItem.Property(Param.Info)

**Comment by jurialmunkey** [comment]
Hmm weird, for pictures library type I had an early exit before properties were set but I can't remember what the reason for doing that was. It must've been some workaround for Leia because it appears to work fine in Matrix without the early exit.
