### ISSUE TITLE
[BUG] wonderfulsubs askes to install every search but wonderful subs is not kodi 19 supported 

### ISSUE THREAD

**Issue by daveftw84** [jurialmunkey/plugin.video.themoviedb.helper#704]
wonderfulsubs askes to install every search but wonderful subs is not supported with kodi 19. can we remove it from searching the addon?

**Comment by jurialmunkey** [comment]
TMDbHelper has nothing to do with wonderfulsubs...

**Comment by daveftw84** [comment]
sorry, i forgot i was using aura's search feature
