### ISSUE TITLE
[BUG] Trakt "your Next Episodes" crashes kodi on Shield TV

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/plugin.video.themoviedb.helper#705]
**Describe the bug**
Trakt "your Next Episodes" crashes kodi on Shield TV.
Steps to reproduce:
1. Open TMDBH
2. Scroll down to "Trakt" and select
3. Scroll down to "Your Next Episodes" and select
4. wait for things to load then it crashes kodi to the shield main screen.

**Debug log**
https://paste.kodi.tv/wibapazoji.kodi

**Screenshots**
N/A

**Additional context**
Works fine on my mac.
Both devices are running kodi 19.4 and TMDBH 4.7.11

**Checklist**
- [x] I have described the bug and included steps to reproduce the issue
- [x] I have included a full kodi debug log of the error

**Comment by jurialmunkey** [comment]
Reduce max threads from unlimited.
`TMDbHelper Settings > Expert > Max concurrent threads`

Try start at 30 and if you still get the crash try reducing further. Usually somewhere in the 20 to 30 range is the sweet spot between performance and stability on Android.

**Comment by Liquidrag** [comment]
30 worked thanks!
