### ISSUE TITLE
[Feature] Context menu item for "browse show" and "browse season"

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/plugin.video.themoviedb.helper#706]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It would be really convenient for me as an end-user to have "browse show" and "browse season" options in the main contest menu. This way I don't need to load all the seasons and then select the season I'm wanting. Currently, there is browse lists then seasons then the desired season. My solution would be to click "browse season" so it only has the desired list to load instead of having to load multiple lists to get to the desired one. 

**Describe alternatives you've considered**
N/A

**Additional context**
Seren has this in its Context menu and I think TMDBH can benefit from it too. 
<img width="2560" alt="Screen Shot 2022-04-25 at 7 12 54 AM" src="https://user-images.githubusercontent.com/43726430/165092872-f2dbc08e-9d95-4a7a-8002-3ec1d8c97ee9.png">

**Comment by AakashC2020** [comment]
Hi @Liquidrag,

I'd like to see this implemented in TMDB Helper too. It's very useful.

@jurialmunkey: Is this possible? Thanks a lot in advance!

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Yes it's possible and I think definitely useful! should be fairly easy to implement, I just haven't had a chance to yet.

FYI "browse show" is already available via
"Context >browse lists > seasons"

I'd just be adding an extra option to jump directly to the specific season of the episode.

**Comment by AakashC2020** [comment]
Thank you @jurialmunkey !

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Added in v4.7.22 - https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.7.22

`Context Menu > Browse Lists > Episodes`

**Comment by Liquidrag** [comment]
Works perfectly. Thank you @jurialmunkey
