### ISSUE TITLE
[Feature] Movie & TV Show title fallback to english option

### ISSUE THREAD

**Issue by kolekan** [jurialmunkey/plugin.video.themoviedb.helper#707]
I'm seeing that when there is no title of selected api language for a movie or tvshow title it returns original title of movie/tvshow in lists. I'm thinking that it is useful having the option to choose between original title or english title as a fallback title label.

**Comment by jurialmunkey** [comment]
Unfortunately TMDB api does not have the the option to specify a fallback language. So this request won't be possible because otherwise it would double the item details lookup time.
