### ISSUE TITLE
[BUG] Mark as Unwatched in Trakt

### ISSUE THREAD

**Issue by jake93evans** [jurialmunkey/plugin.video.themoviedb.helper#708]
**Describe the bug**
The past couple of days I've been unable to 'mark as unwatched' (Trakt) via the context menu.
This has been for multiple addons, not just TMDbHelper, maybe they've changed something their end?

- Mark as watched works fine.
- Manually able to remove play via Trakt website.
- Auto-marks as watched after playback.
- Fresh Kodi, skin, and addon install.

**Debug log**
No errors in log, just "Mark as unwatched failed for movie - TMDB ID #####" dialog after it hangs for around 10 seconds.

Thanks in advance

**Comment by jurialmunkey** [comment]
No changes as far as I'm aware. 

I've noticed Trakt has had some server issues with some sync requests being dropped and timing out in the past few days, so I get the impression it's probably related to some issue or maintenance they're having server side rather than an api change.

**Comment by jurialmunkey** [comment]
Looks like they had an issue about a week ago and are still looking into the problem so probably related to that
https://mobile.twitter.com/traktapi/status/1514682311337394178?cxt=HHwWhICqra_inYUqAAAA

**Comment by jake93evans** [comment]
Thanks for getting back to me so quickly.

I'll wait patiently then :)

Many thanks.

**Comment by jurialmunkey** [comment]
I've been able to mark as unwatched today, so it appears to be working on Trakt's end now

**Comment by jake93evans** [comment]
Brilliant thanks.
I'll close this.
