### ISSUE TITLE
I'm running 4.7.20, list author is not showing up. The skin I'm using is Estuary Mod latest version, list view (3.4.0 + matrix 12). Could this skin be the reason that the author is not showing up ? Tnx.

### ISSUE THREAD

**Issue by SirRickie** [jurialmunkey/plugin.video.themoviedb.helper#711]
I'm running 4.7.20, list author is not showing up. The skin I'm using is Estuary Mod latest version, list view (3.4.0 + matrix 12). Could this skin be the reason that the author is not showing up ? Tnx.

_Originally posted by @SirRickie in https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/700#issuecomment-1108324969_

**Comment by jurialmunkey** [comment]
Yes, it's the skin. If the skin doesn't display either ListItem.Label2 or ListItem.Studio then you won't be able to see the author.
