### ISSUE TITLE
[Feature] Custom date formatting

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#712]
There is a skin setting to set a custom date format:- Skin.SetString(TMDbHelper.Date.Format,%d %b %Y)
However it only seems to be used for Premiered_Custom

I propose that every date  property should be able to use the custom set TMDBHelper.Date.Format ie.

Last_Aired.Custom
Next_Aired.Custom

Thanks

**Comment by jurialmunkey** [comment]
Hmm, still trying to think about what the best approach would be for this.

Do you need the custom formatting in the ListItem or is a Window Property for focused item good enough?

**Comment by roidy** [comment]
Window Property for focused item would be perfectly fine.

**Comment by jurialmunkey** [comment]
Window property is much easier to manage. Working in v4.7.29

**Comment by roidy** [comment]
Works perfectly, thanks 👍
