### ISSUE TITLE
[BUG] "Your next episodes" causing error at start up

### ISSUE THREAD

**Issue by 43v3rLoCo** [jurialmunkey/plugin.video.themoviedb.helper#714]
**Describe the bug**
When I start up kodi, tmdb helper throws an error which causes my widgets to not load. It's fixed by reloading my skin. Been happening since the last 2 updates I believe. 

Kodi 19.4
TMDB Helper 4.7.20
Fire TV

**Debug log**
https://paste.kodi.tv/afusugecev.kodi

**Comment by jurialmunkey** [comment]
Please try v4.7.23 and let me know if that fixes the issue:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.7.23

**Comment by 43v3rLoCo** [comment]
That did it! Thanks, you're awesome! :)
