### ISSUE TITLE
players functionality

### ISSUE THREAD

**Issue by kolekan** [jurialmunkey/plugin.video.themoviedb.helper#715]
I'm thinking that is a good idea the ability of a search tmdb helper player prompts for user's selection from a dialog when more than one listitems match the criteria of player's step instead to proceed with the first matching listitem. Or if no item matches step's criteria, prompts for user's selection from a list dialog with the rest of provided listitems before returns the players selection dialog.

**Comment by jurialmunkey** [comment]
What is the use-case of the first idea? It sounds like an [XY problem](https://en.wikipedia.org/wiki/XY_problem) that would be better solved with better match rules.

The second idea you can already do with an early return step. For example the following will pop-up a select dialog if the matching episode isn't found.
```
{"return": "true", "season": "{season}", "episode": "{episode}"},
{"dialog": "true"}
```

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#steps-actions

**Comment by kolekan** [comment]
Here is the case. Movie Title is "Rumble". When i'm using the search function in video addon that i'm trying to make the player, it returns a list with the following items
-Rumble
-Rumble
-Rumble Fish
-Rumble Strip
First item in list is https://www.themoviedb.org/movie/598331-rumble?language=en-US
Second item in list is https://www.themoviedb.org/movie/286339-rumble?language=en-US
There is no year in item name or other item infolabel to match the second in list item instead of the first.

But even if there was year info in listitem name (i made some changes for this in addon), the second item's release year is 2016 in tmbd but 2017 in imdb, so it cant't be matched if the year infolabel comes from imdb.
I tried return step as follow.
```
{"keyboard": "{clearname}"},
{"return": "true", "label": "(?i){clearname} {year}"},
{"dialog": "true"}
```
but it returns the search input keyboard dialog.
And one more thing i want to ask. Is there a tool for viewing listitems infolabels in screen like debug info? I think somewhere there is a skin xml for this job.

**Comment by kolekan** [comment]
*Update*
with this
```
{"keyboard": "{clearname}"},
{"return": "true", "label": "(?i){clearname} {year}"},
{"keyboard": "{clearname}"},
{"dialog": "true"}
```
it works but makes an extra request in search link

**Comment by drinfernoo** [comment]
https://github.com/rmrector/webinterface.devhelper

**Comment by jurialmunkey** [comment]
@kolekan - Ah I see, yeah that's a tricky scenario when there's not much data to match on. I'll see what I can come up with.

BTW - In v4.7.33+ there is additional player debug logging using `TMDbHelper settings > Expert > Debug logging` which you can use to see exactly on which step your player is failing in the kodi log.

The return step shouldn't pop-up the keyboard. Anyway, I forgot that you can combine "dialog" steps with other rules:
`{"dialog": "true", "label": "(?i){clearname} {year}"}`

^  That will auto play an item if a match is found otherwise it provides a dialog for the user to select from the folder.

**Comment by jurialmunkey** [comment]
@kolekan - In v4.7.34 I've added a `"strict": "true"` flag for steps which forces the step to check that only one item matches. You can combine this with a dialog step to allow a user to select from the options

For example:
`{"dialog": "true", "label": "(?i){clearname}", "strict": "true"}`

- Looks for matches where label contains `{clearname}`
- Only one match = Auto play
- Multiple matches = Dialog with matches
- No matches = Dialog with folder contents
- No items in folder = Player fails

**Comment by kolekan** [comment]
@jurialmunkey 
I just tried it. I have no words. You just gave me the tools to make fault-proof players. It's better than I thought it would be.
