### ISSUE TITLE
[BUG] Saved discover filters cannot be edited

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#716]
Hi, I currently have a couple of saved discover filters, one for movies, one for anime OVAs. When I try to edit the name of one, the one getting edited is the other. When I try to change their settings, I always get the same filters to modify, no matter which one I choose. So it seems there is something funny with the saved discover configurations. I'm on version 4.7.20.

**Comment by jurialmunkey** [comment]
Yep, can reproduce. Something odd is going on. Looks like the cache itself is fine because newly created rule sets are being saved correctly and can be opened. It's just when editing the index is not matching up or a property isn't being cleared properly.

**Comment by jurialmunkey** [comment]
Yep index for rename was reversed due to how I was reversing the history to put newest at top. And Edit issue was just the previously set properties not clearing properly. Should be fixed now in v.4.7.24
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.7.24
