### ISSUE TITLE
[BUG] NextAired.date fails to update

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#719]
NextAired dates are failing to update after the last episode has aired. For example the series The Flash after it's last episode aired on Wednesday the 4th of May the NextAired info property should now point to the next episode on the 11th of May but as of Today(Saturday the 7th of May) it still returns Wednesday the 4th of May's episodes date.

Not sure if this is an overly aggressive cache issue or a bug, either way it makes the NextAired property inaccurate .

**Comment by jurialmunkey** [comment]
Do you just mean for `ListItem.Property()` or is it also happening in the Window Property?

ListItem is due to the item details being cached for 14 days but the window property version should update daily.

**Comment by roidy** [comment]
Nope, I'm defiantly using the window property version:-

`$INFO[Window(home).Property(TMDBHelper.ListItem.next_aired.day_short),, ]$INFO[Window(home).Property(TMDBHelper.ListItem.next_aired.short)]`

**Comment by jurialmunkey** [comment]
You know what, you're totally correct - it wasn't being updated. I was getting the data and cache was set correctly to one day refresh but it wasn't updating the details dictionary properly so it was falling back to the 14 day cached version anyway.

Pretty sure it should be fixed now.

**Comment by roidy** [comment]
Perfect, after updating and restarting all my nextaired dates have populated correctly.... Big thanks 👍

**Comment by roidy** [comment]
Just noticed one small problem, I've got shows which aired there last episodes on Thursday 5th of May and have no next episode however:-

`Window(home).Property(TMDBHelper.ListItem.last_aired)` returns the correct date of Thursday 5th May as it's now the last episode but

`Window(home).Property(TMDBHelper.ListItem.next_aired)` still returns 5th May regardless of the fact there is no next episode and it should return nothing.

The shows are Star Trek Picard and Outer Range.

**Comment by jurialmunkey** [comment]
I *think* v4.7.27 should fix it.

**Comment by roidy** [comment]
Yep, that fixed it, thanks 👍
