### ISSUE TITLE
[Request] Library Update

### ISSUE THREAD

**Issue by newf276** [jurialmunkey/plugin.video.themoviedb.helper#72]
Not so much an issue perhaps, but maybe a request, depending on your intent of the library update.

If a user wishes to use this without activating TRAKT, how does one go about updating the library to include new episodes for each TV Show that they have added to the library. I realize that if you select the update library setting after adding show, it will add the show with the current aired series. However, there is no option to update the library on startup like OpenMeta does. Meaning that when you start Kodi it searches for new episodes and adds them to the library.  Right now it does not update and add new episodes. Even if I enable the update library on startup under Kodi Media settings. How do we go about having the library update automatically without having to add each new episode manually? Without using the trakt script?

Thanks for your continuous work, I am really enjoying how fast this Addon is, the only thing that would prevent me from replacing OpenMeta and using this plugin solely is an auto library update function.  Thanks again

**Comment by jurialmunkey** [comment]
Currently you need to update manually. I'll have a look at adding an auto-update option for shows.

**Comment by newf276** [comment]
> Currently you need to update manually. I'll have a look at adding an auto-update option for shows.

Appreciate the recommendation for now, and look forward to extra option when you have time.

**Comment by jurialmunkey** [comment]
> 
> 
> > Currently you need to update manually. I'll have a look at adding an auto-update option for shows.
> 
> Appreciate the recommendation for now, and look forward to extra option when you have time.

By "update manually" I mean you need to add the new episodes to the library manually by going into TMDbHelper and re-adding the show to the library.

**Comment by newf276** [comment]
> > > Currently you need to update manually. I'll have a look at adding an auto-update option for shows.
> > 
> > 
> > Appreciate the recommendation for now, and look forward to extra option when you have time.
> 
> By "update manually" I mean you need to add the new episodes to the library manually by going into TMDbHelper and re-adding the show to the library.

Ack, thanks.

**Comment by jurialmunkey** [comment]
@newf276 - Can you test latest version? There is now a setting to auto-update tvshows on startup under the library section of the addon's settings.

**Comment by newf276** [comment]
> @newf276 - Can you test latest version? There is now a setting to auto-update tvshows on startup under the library section of the addon's settings.

Works perfect, thank you sooooooooooooooooooooo.....much.  This is now fantastic, everyone will love this for sure..

**Comment by drinfernoo** [comment]
I've been a bit behind I've the last few days, but I can get some updates pushed to the repo tomorrow @jurialmunkey 🎉

**Comment by jurialmunkey** [comment]
> 
> 
> > @newf276 - Can you test latest version? There is now a setting to auto-update tvshows on startup under the library section of the addon's settings.
> 
> Works perfect, thank you sooooooooooooooooooooo.....much. This is now fantastic, everyone will love this for sure..

Excellent! Let me know if you encounter any issues but I can't see any reason for any problems. I'm just walking the library tv path, grabbing the tmdb_id from the nfo files, and then readding the show.

**Comment by jurialmunkey** [comment]
> 
> 
> I've been a bit behind I've the last few days, but I can get some updates pushed to the repo tomorrow @jurialmunkey 🎉

Cheers! Whenever, you get the chance - no rush!
