### ISSUE TITLE
[Feature] Premieres lists

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#720]
Is there a way to get or could you add the:-

Calendar->My->Premieres
Calendar->All->Premieres

Lists?

**Comment by jurialmunkey** [comment]
Yeah I think I should be able to get all these. Looks like there's specific API endpoints and the output data format is the same as the standard calendar so should be relatively simple to extend the calendar to include

![image](https://user-images.githubusercontent.com/4618719/167250582-4b5f3fb0-8769-496e-8c8c-53c17d5b06f7.png)

**Comment by roidy** [comment]
Thanks, on the website the lists look like this, it would be nice, but not super important if we could get a property to return weather it's a series or season premier.

![Screenshot 2022-05-07 124328](https://user-images.githubusercontent.com/4118048/167252774-4cc98dea-cf87-4642-b68b-7ef9b6759988.png)

**Comment by jurialmunkey** [comment]
Okay should now have premieres and new shows for calendar. Also will have "All" version. I'll add Movies/DVDs soon (just need to expand calendar functionality as currently it is only setup to work with episodes).

You can access these through normal Trakt menus in the Addon. For the plugin path there are a couple of extra params to expand the `info=trakt_calendar` path:

`&user=false` switches from "My" to "All"
`&endpoint=premieres` gets season premieres
`&endpoint=new` gets new tvshow premieres

You should already be able to determine season/series premiere using normal skinning:
`Integer.IsEqual(ListItem.Season,1) + Integer.IsEqual(ListItem.Episode,1)`
`Integer.IsGreater(ListItem.Season,1) + Integer.IsEqual(ListItem.Episode,1)`

**Comment by roidy** [comment]
Oh wow... that was fast. Works great 👍 

>You should already be able to determine season/series premiere using normal skinning:

D'Oh.... I should of realised that, thanks.

One quick question, if I leave the `endpoint` off will it return both season and new show premiers combined?

**Comment by roidy** [comment]
Also is it possible to filter the calendar to only return English language shows? I've tried:-

`&amp;filter_key=language&amp;filter_value=english`

With no luck.

**Comment by jurialmunkey** [comment]
> One quick question, if I leave the `endpoint` off will it return both season and new show premiers combined?

No endpoint is just standard calendar (all episodes)

`endpoint=premieres` is already both series+season because it displays S*E1 episodes
`endpoint=new` displays S1E1 episodes only.

>Also is it possible to filter the calendar to only return English language shows? I've tried:-

`&amp;filter_key=language.1.iso&amp;filter_value=en`

It's not perfect but language 1 should be the main language of the show. Some dubbed English shows still display but it should filter out most of the foreign language shows.

**Comment by roidy** [comment]
> No endpoint is just standard calendar (all episodes)

Of course, sorry I realise that now 😊

> `&amp;filter_key=language.1.iso&amp;filter_value=en`
> 
> It's not perfect but language 1 should be the main language of the show. Some dubbed English shows still display but it should filter out most of the foreign language shows.

Yep, some still creep through but the list is much more manageable, thanks
