### ISSUE TITLE
[Question] Search list

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#723]
Hi Jurial. One question and little help. I want to use tmdb helper search list in my skin (titan bingie mod). I placed it in search hub so that I could search the lists of movies and tv shows from tmdb helper. But I have one small problem. As you can see I use movie and tv show search list. When I enter in search hub, virtual keyboard first appears and then disappears. They probably appeared with a movie list and then disappeared with a TV show list. I have other lists in search hub (e.g. youtube), but not one of them not forced keyboard to show up. Is there a way around this? Thanks in advance.
```
`<!-- TMDB Helper Movies Results -->
            <include content="SearchResultWidget" condition="Skin.HasSetting(EnableBingieSearchTMDBHelper)">
                <param name="id" value="660" />
                <param name="layout">PosterPanelBingie</param>
                <param name="layoutwidth">search_widget_thumb_width</param>
                <param name="allow_showinfo_onclick" value="true" />
                <param name="visibility" value="!String.IsEmpty(Skin.String(CustomSearchTerm))" />
                <content sortby="file" limit="20" target="videos">plugin://plugin.video.themoviedb.helper?info=search&amp;type=movie&amp;query=$INFO[Skin.String(CustomSearchTerm)]</content>
            </include>
<!-- TMDB Helper TV Shows Results -->
            <include content="SearchResultWidget" condition="Skin.HasSetting(EnableBingieSearchTMDBHelper)">
                <param name="id" value="670" />
                <param name="layout">PosterPanelBingie</param>
                <param name="layoutwidth">search_widget_thumb_width</param>
                <param name="allow_showinfo_onclick" value="true" />
                <param name="visibility" value="!String.IsEmpty(Skin.String(CustomSearchTerm))" />
                <content sortby="file" limit="20" target="videos">plugin://plugin.video.themoviedb.helper?info=search&amp;type=tv&amp;query=$INFO[Skin.String(CustomSearchTerm)]</content>
            </include>`
```

**Comment by jurialmunkey** [comment]
Query cannot be blank otherwise it will popup keyboard. I'd recommend putting the whole content path in a variable that checks if the search string is not empty and otherwise returns nothing.

**Comment by matke-84** [comment]
Did you mean something like this or do I need some other condition?
`<value condition="!String.IsEmpty(Skin.String(CustomSearchTerm))" >plugin://plugin.video.themoviedb.helper?info=search&amp;type=movie&amp;query=$INFO[Skin.String(CustomSearchTerm)]</value>`

**Comment by matke-84** [comment]
Thanks. That's it. 😉
Is there a chance to search for movies and tv shows together? I mean, I can merge two lists but the result is always separate. For example, if I search x files I expect tv show to come out first and then the movie. But it happens that they first lists everything from movies and then after all movies lists tv show.
Is there any sorting method for tmdb helper search results?

**Comment by matke-84** [comment]
@jurialmunkey 
Is this a good list for tv shows?
`plugin://plugin.video.themoviedb.helper?info=similar&amp;type=tv&amp;imdb_id=$INFO[ListItem.IMDBNumber]`
I get  for movies but not for tv shows. I'm not talking about the search, just the list. I want to use it for similar stv shows.

**Comment by matke-84** [comment]
@jurialmunkey 
I found on kodi forum that it works like this. And it really works.
`plugin://plugin.video.themoviedb.helper?info=similar&amp;type=tv&amp;query=$INFO[ListItem.TVShowTitle]`

**Comment by jurialmunkey** [comment]
> @jurialmunkey Is this a good list for tv shows? `plugin://plugin.video.themoviedb.helper?info=similar&amp;type=tv&amp;imdb_id=$INFO[ListItem.IMDBNumber]` I get for movies but not for tv shows. I'm not talking about the search, just the list. I want to use it for similar stv shows.

Yeah it works for TV. Most likely the issue is that whatever tvshow you're looking at doesn't actually have an IMDb ID in IMDbNumber - often scrapers put TVdb or TMDb IDs in there instead. You should use `$INFO[ListItem.UniqueID(imdb)]` to make sure that you're getting the IMDb ID.

Better yet, the path accepts multiple query params `plugin://plugin.video.themoviedb.helper?info=similar&amp;type=tv$INFO[ListItem.UniqueID(imdb),&amp;imdb_id=,]$INFO[ListItem.UniqueID(tmdb),&amp;tmdb_id=,]$INFO[ListItem.UniqueID(tvdb),&amp;tvdb_id=,]$INFO[ListItem.TVShowTitle,&amp;query=,]$INFO[ListItem.Year,&amp;episode_year=,]`

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Lists-Related#lookup-parameters

**Comment by jurialmunkey** [comment]
Note that the lookup needs to be for the TVShow. So if you are looking up from a Season/Episode you shouldn't include the IDs because they will be for the episode rather than the show (just use query + episode year without IDs).

**Comment by jurialmunkey** [comment]
>  Is there a chance to search for movies and tv shows together? I mean, I can merge two lists but the result is always separate.

Not at the moment but I've been planning to add a multisearch option for quite a while.

**Comment by matke-84** [comment]
> Better yet, the path accepts multiple query params `plugin://plugin.video.themoviedb.helper?info=similar&amp;type=tv$INFO[ListItem.UniqueID(imdb),&amp;imdb_id=,]$INFO[ListItem.UniqueID(tmdb),&amp;tmdb_id=,]$INFO[ListItem.UniqueID(tvdb),&amp;tvdb_id=,]$INFO[ListItem.TVShowTitle,&amp;query=,]$INFO[ListItem.Year,&amp;episode_year=,]`

This is great. Thanks.

**Comment by matke-84** [comment]
> Not at the moment but I've been planning to add a multisearch option for quite a while.

Awesome.

**Comment by jurialmunkey** [comment]
BTW, I think that generally `info=recommendations` gives better suggestions than `info=similar`

Similar only looks at genres and keywords so it has fairly broad suggestions which often feel a bit random and disconnected. Whereas Recommendations also takes into account user ratings, so it is a bit more of a "other users who liked X also like Y" type of thing which leads to better suggestions.

**Comment by matke-84** [comment]
List limiting is not possible? For example.
`plugin://plugin.video.themoviedb.helper?info=trakt_popular&amp;type=movie&amp;limit=10`

**Comment by matke-84** [comment]
I found one mistake on wiki page. Trakt list Most Played (Across all Users) is not corect.
Also the new list you inserted most watched was not inserted on wiki. I tried with
`plugin://plugin.video.themoviedb.helper?info=trakt_mostviewers&amp;type=movie`
but it doesn't work. I haven't checked the other lists, but you check just in case. Maybe there is another mistake that needs to be corrected.

**Comment by matke-84** [comment]
> `plugin://plugin.video.themoviedb.helper?info=trakt_mostviewers&amp;type=movie` 

This works. My mistake.

**Comment by jurialmunkey** [comment]
> List limiting is not possible? For example. `plugin://plugin.video.themoviedb.helper?info=trakt_popular&amp;type=movie&amp;limit=10`

You can do limiting in the content tags
`<content target="videos" limit="10">plugin://plugin.video.themoviedb.helper?info=trakt_popular&amp;type=movie</content>`

**Comment by matke-84** [comment]
> You can do limiting in the content tags `<content target="videos" limit="10">plugin://plugin.video.themoviedb.helper?info=trakt_popular&amp;type=movie</content>`

Yes, I know about this but I wanted to try something else. Doesn't matter.

**Comment by matke-84** [comment]
I have another question. How it works in tmdb helper continue watching function. Whether it is connected to the trakt account or depends on player used.

**Comment by matke-84** [comment]
@jurialmunkey Is there a possibility to I get tmdb helper "artwork select" button in the info dialog screen? Is there an button id?

**Comment by matke-84** [comment]
> @jurialmunkey Is there a possibility to I get tmdb helper "artwork select" button in the info dialog screen? Is there an button id?

@jurialmunkey Sorry, is this possible?

**Comment by jurialmunkey** [comment]
> @jurialmunkey Is there a possibility to I get tmdb helper "artwork select" button in the info dialog screen? Is there an button id?

No button id. But it is possible to call the underlying function directly via Runscript in an `<onclick>` of a custom button.

`Runscript(plugin.video.themoviedb.helper,manage_artwork,tmdb_id=$INFO[ListItem.UniqueID(tmdb)],tmdb_type=movie)`

You _must_ have the tmdb_id. tmdb_type can be "movie" or "tv". 

For "tv" you must have the tmdb_id for the parent tvshow NOT a season or episode id. Optionally you can set season artwork for a tvshow by specifying the season number using the `season=` param

**Comment by matke-84** [comment]
> `Runscript(plugin.video.themoviedb.helper,manage_artwork,tmdb_id=$INFO[ListItem.UniqueID(tmdb)],tmdb_type=movie)`

This is ok, but can I get "choose art" window directly, to bypass context menu?
![unnamed](https://user-images.githubusercontent.com/74268331/168429226-f20f8876-e858-43a2-87fc-88110eca4454.png)
?

**Comment by jurialmunkey** [comment]
> This is ok, but can I get "choose art" window directly, to bypass context menu?

Now you can with latest.

Use `select_artwork` instead of `manage_artwork`

I didn't test but should work.

**Comment by matke-84** [comment]
@jurialmunkey Working. Thanks.

Is it possible for this button to be visible only in tmdb helper?

And one small visual suggestion. If there is a possibility to allow the chose art window to have preview of the currently selected art and not just the list with the name. In Kodi by default choose art window look like this. It's look like same when you enter in tmdb helper choose art a poster, clearart, clearlogo...

**Comment by jurialmunkey** [comment]
> Is it possible for this button to be visible only in tmdb helper?

Probably best approach is to use the same condition as context menu entry.
`!String.IsEmpty(ListItem.Property(tmdbhelper.context.artwork))`

**Comment by matke-84** [comment]
> Probably best approach is to use the same condition as context menu entry.
> `!String.IsEmpty(ListItem.Property(tmdbhelper.context.artwork))`

That's it. Thanks.

**Comment by matke-84** [comment]
> And one small visual suggestion. If there is a possibility to allow the chose art window to have preview of the currently selected art and not just the list with the name. In Kodi by default choose art window look like this. It's look like same when you enter in tmdb helper choose art a poster, clearart, clearlogo...

Think about this. I think this is a good suggestion because at the moment we don't have an insight into which artwork has been set up. 
This is kodi default choose art view.
![default kodi](https://user-images.githubusercontent.com/74268331/168487095-56da9842-51b7-406c-ac57-b80ab8778ec6.png)
TMDB Helper
![tmdb](https://user-images.githubusercontent.com/74268331/168487219-6c41a241-3201-4b45-8104-c138167ded31.png)

**Comment by jurialmunkey** [comment]
@matke-84 - Could you open the artwork preview as a separate issue. I think it is a good suggestion but it will need a bit of work to get running, so it would be good if it has its own thread to track it.

**Comment by matke-84** [comment]
@jurialmunkey 
Done.
