### ISSUE TITLE
[BUG] TMDB(4.7.29) Error Trakt list(s)

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#724]
**Describe the bug**
TMDB error when scanning library from Trakt list(s). only happens with macOS

**Debug log**

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/8647113/kodi.log)

**Screenshots**
<img width="1406" alt="Screenshot 2022-05-08 at 14 53 16" src="https://user-images.githubusercontent.com/2873112/167300080-7f706f17-4333-4f52-bd82-21548a457c90.png">

**Additional context**

**Checklist**
- [x] I have described the bug and included steps to reproduce the issue
- [x] I have included a full kodi debug log of the error

**Comment by jurialmunkey** [comment]
That's your library scraper making that error, not TMDbHelper. TMDbHelper's scan hasn't even started in your log. Those errors are related to your library scraper failing to scan your smb:// path 

I can see from the screenshot that TMDbHelper is pointing to a completely different path - specifically the `kodi/userdata/addon_data/plugin.video.themoviedb.helper` folder in your Kodi profile.

By the way, unless you've specifically added those TMDbHelper addon_data paths as Kodi library sources you're just wasting your internet bandwidth with those update options. Those library intregration options create strm files for the items in the linked lists (strm files are basically fake videos that open TMDbHelper when played). You still need to add them as sources in Kodi and scan the folders just like normal videos for them to show up in your Kodi library.

**Comment by Blurayx** [comment]
Regarding the different paths, I  didn't change them. it's the default settings.

Thanks

**Comment by Blurayx** [comment]
Update:

1) TMDbHelper(Disabled Trakt account, update library after update, Auto update library add new/missing episode 

2) Now using the stand-alone Trakt add-on

still getting the error using the Kodi manual update library option. I will do a fresh install

**Comment by Blurayx** [comment]
Update:
working after a fresh install 😀
