### ISSUE TITLE
[BUG] ListItem.Premiered/Year is incorrect for some cases

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/plugin.video.themoviedb.helper#728]
**Describe the bug**

Hi @jurialmunkey, the ListItem.Premiered is incorrect for some cases. For example, for tvshow https://www.themoviedb.org/tv/115646-lisa, the ListItem.Premiered is "01/25/2021255", which seems some unexpected numbers (255) appended to the date. Another example is https://www.themoviedb.org/tv/122551-viral, the ListItem.Premiered is "11/15/2021128". The ListItem.Year has the same problem.

Edit: After checking the themoviedb.helper addon with other skins, it seems it's the AH1 skin issue. The Estuary skin can show these correctly.

Edit2: It's caused by the WatchedEpisodes property of themoviedb.helper addon. For the line https://github.com/jurialmunkey/skin.arctic.horizon/blob/matrix/1080i/Includes_Object.xml#L40, the WatchedEpisodes is evaluated as empty, thus for the parts "$INFO[ListItem.Property(WatchedEpisodes),  |  [COLOR=main_fg_100]$LOCALIZE[16102] , $LOCALIZE[20163] [/COLOR]]$INFO[ListItem.Property(TotalEpisodes),[COLOR=main_fg_100],[/COLOR]]" of the line https://github.com/jurialmunkey/skin.arctic.horizon/blob/matrix/1080i/Includes_Labels.xml#L153

the first evaluation is empty due to the WatchedEpisodes is empty, but the TotalEpisodes is not, thus the result is concatenated to the ListItem.Year, which produced an incorrect result

**Debug log**
Include your FULL kodi.log file uploaded to https://paste.kodi.tv/
https://kodi.wiki/view/Log_file#Log_file_location

**Screenshots**

**Additional context**

**Checklist**
- [x] I have described the bug and included steps to reproduce the issue
- [ ] I have included a full kodi debug log of the error

**Comment by jurialmunkey** [comment]
Skin issue. You can work around it by disabling
`TMDbHelper Settings > Accounts > Unwatched counts only on in-progress tvshows`
