### ISSUE TITLE
[Feature] Artwork preview

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#729]
If there is a possibility to allow choose art window to have preview of the currently selected art and not just the list with the name. In Kodi by default choose art window look like this. It's look like same when you enter in tmdb helper choose art a poster, clearart, clearlogo... At the moment we don't have an insight into which artwork has been set up.

This is kodi default choose art view.
![default kodi](https://user-images.githubusercontent.com/74268331/168487095-56da9842-51b7-406c-ac57-b80ab8778ec6.png)
TMDB Helper
![tmdb](https://user-images.githubusercontent.com/74268331/168487219-6c41a241-3201-4b45-8104-c138167ded31.png)

**Comment by jurialmunkey** [comment]
Please try v4.7.35

It appears to be working well. I also reordered the types to better match the library. Plus made a small tweak to navigation so that selecting a new artwork will take you back to the main selection menu so that you can select other types (rather than refreshing the list immediately).

**Comment by matke-84** [comment]
It works great. Just one thing. I don't know if it's possible to just hide artwork for which there is no one on fanart or tmdb. It displays it in the list and when I click on it then it throws out that the artwork doesn't exist and then it disappears from the list.
![111](https://user-images.githubusercontent.com/74268331/169120319-c0ad3140-f2ac-4821-972d-947c101f7c9a.png)
![222](https://user-images.githubusercontent.com/74268331/169120350-8468587e-5322-4fdf-bcc7-6fcbf9a62585.png)

**Comment by jurialmunkey** [comment]
That would make it too slow to open because would need to check every artwork type first - so you would end up waiting a few seconds for the requests to complete

**Comment by matke-84** [comment]
Ok. Leave it like this then. It is much better to have speed.
