### ISSUE TITLE
Change Color of Movie or Episode Title

### ISSUE THREAD

**Issue by vitadome** [jurialmunkey/plugin.video.themoviedb.helper#73]
When searching for a movie or episode, I wanted the ability to change the font color from the other list items on the page.  For example, I want to change the movie title color to gold.  I see that I can change the colors for the other categories in the DETAILED_CATEGORIES section of the constants.py file but I'm not sure where to make the change to the actual Movie Title.  Any guidance is appreciated.  Thank you.

<Movie Title>
Cast
Recommended
Similar
Crew
Posters
Fanart
Keywords
Reviews

**Comment by jurialmunkey** [comment]
The detailed item is built in the `list_details` function in the `container` class in `container.py` module
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/container.py#L707

First item in the detailed categories is built here:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/container.py#L740-L750

**Comment by vitadome** [comment]
I appreciate the info.  I'm still a bit confused on where to place my [COLOR gold]test[/COLOR] tags.  Not sure if I'm way off base or not.  Any additional guidance is appreciated.

I'm not a developer but am learning everyday.

**Comment by jurialmunkey** [comment]
`firstitem.label` is the string containing the label of the item.
