### ISSUE TITLE
[Question] TMDB helper(Trakt sync)

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#731]
when I "Auto-update library from Trakt list(s)" on my  Nvidia shield and then update on my macOS it doesn't sync. it works when I use the Trakt app. 

<img width="936" alt="Screenshot 2022-05-19 at 03 03 14" src="https://user-images.githubusercontent.com/2873112/169189175-57906c71-89c9-44cf-a7d6-f708f7a2a11f.png">

Thanks

**Comment by jurialmunkey** [comment]
Sorry I don't understand what you're trying to do. Library updates don't have anything to do with syncing.

I think you might be misunderstanding what this function does. All it does is add to your kodi library things which are in your trakt watchlist. It creates a strm file (a fake video shortcut) that you can then scan to your local kodi library. The strm file opens tmdbhelper when  it is played.

**Comment by Blurayx** [comment]
I thought I didn't need the Trakt app if I activate my account in the TMDB helper. Basically, it doesn't replace  the Trakt app?

<img width="1638" alt="Screenshot 2022-05-21 at 05 23 19" src="https://user-images.githubusercontent.com/2873112/169635347-4ec12d68-3cbc-46d8-ba53-c3acbd422aa8.png">

**Comment by jurialmunkey** [comment]
> I thought I didn't need the Trakt app if I activate my account in the TMDB helper. Basically, it doesn't replace the Trakt app?
> 
> <img alt="Screenshot 2022-05-21 at 05 23 19" width="1638" src="https://user-images.githubusercontent.com/2873112/169635347-4ec12d68-3cbc-46d8-ba53-c3acbd422aa8.png">

No it is not a replacement for scrobbling via the trakt addon.

Authorising trakt in tmdbhelper allows you to browse trakt lists inside tmdbhelper.

The library settings are for creating items in your kodi library that will play using tmdbhelper. You would do that if, for instance, you use tmdbhelper to play items via a streaming service addon (eg Netflix, Hulu, Amazon etc) and you wanted those items to show up in your kodi library just like a normal video file.

For example, say I watch "the witcher" on Netflix but I want it to be in my library with the rest of my videos. Then I would add it to my trakt watchlist and on next update tmdbhelper will create in the library folder I specify a subfolder called "the witcher" containing strm files for the episodes. As long as I add that folder as a library source in kodi then it will get added to my library .  when I click one of those items it will open the strm file which is a shortcut which opens tmdbhelpers player function just like if I had clicked on it inside tmdbhelper.

That's all it does.

**Comment by Blurayx** [comment]
Ah!!!

Thanks
