### ISSUE TITLE
[Question] Play media

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#732]
I don't know if it's possible, but let me ask. I would like to insert a button in extendedinfo window that would play movies and tv shows from tmdb helper. I managed to do it for movies.
`Runscript(plugin.video.themoviedb.helper,play=movie,imdb_id=$INFO[Window.Property(imdb_id)])`
Is it possible to do the same thing for tv shows, more precisely is it possible to open season level from extendedinfo in tmdb helper?

**Comment by jurialmunkey** [comment]
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

**Comment by jurialmunkey** [comment]
Ah sorry I see what you're asking - you want a browse function.

Assuming that you're using TMDbHelper's version of extended info then there shouldn't be any need for this at all. `SendClick(8)` in videoinfo dialog should play/browse appropriately.

**Comment by matke-84** [comment]
I didn't write very well. I don't use extended info from tmdb helper. I have some reasons why I use a modified old extendedinfo script. So I asked for help. I don't know how to solve for tv show.

**Comment by jurialmunkey** [comment]
No idea, I don't use extended info.

Path in TMDbH for seasons is
`plugin://plugin.video.themoviedb.helper/?info=seasons&tmdb_type=tv&tmdb_id=XX`

So as long as you know the tmdb_id to put where XX is then you can call it using activatewindow()
https://kodi.wiki/view/Opening_Windows_and_Dialogs

`ActivateWindow(videos,plugin://plugin.video.themoviedb.helper/?info=seasons&tmdb_type=tv&tmdb_id=XX)`

Also remember that you need to use `&amp;` for `&` in xml files

**Comment by matke-84** [comment]
Thanks. I'll try something.
