### ISSUE TITLE
 issue with resume progress points

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/plugin.video.themoviedb.helper#734]
This started happening like four days ago when I go into my in progress episodes the resume points are not there ,The episodes show up in,, (Trakt) in progress episodes but with no resume points was wondering if anybody is experiencing these issue as well,, trying to figure it out if not maybe something got corrupted somewhere using K19.4 Nvidia Shield Pro 2019 AuraMOD 1.1.7

**Comment by xyzfre** [comment]
Just tried on a fresh install with AH and the same issue happens appreciate any help on this one

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/170113486-a9db36dc-5283-444a-988e-4d26725110ad.MOV

**Comment by xyzfre** [comment]
As you can see in the video my in progress episodes are there but they have no resume points I checked with a different add-on same set up and the resume points are there

**Comment by xyzfre** [comment]
These are my Settings![image](https://user-images.githubusercontent.com/49699869/170138112-55789df8-7e1a-4e0a-bb76-5ff186ccae24.jpeg)

**Comment by jurialmunkey** [comment]
~Debug log?~

EDIT: Nevermind. I can reproduce and know what the issue is.

**Comment by jurialmunkey** [comment]
@xyzfre - Okay I think I've fixed it. Looks like a race condition where the data was getting corrupted by multiple item threads working on it at the same time.

- Please install v4.7.40 https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.7.40
- Delete Trakt cache (`TMDbH Settings > Expert > Delete cache`)
- Restart Kodi and test

**Comment by xyzfre** [comment]
I installed 4.7.40 cleared Trakt cache, I can't see the resume points on the poster cover but it seems they're there here's a pic to explain better ,, using Nvidia shield 2019 Pro I'll test on PC shortly

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/170259179-377e042f-724d-49d5-a067-f85b25e1da64.jpeg)

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/170259231-deb5f862-a807-40c0-b6ec-5050ff991bf5.jpeg)

**Comment by xyzfre** [comment]
On PC ,Same behavior as the Nvidia shield,, I tested the resume points and they do work ,they're just not visual

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/170267263-ef0798b3-21be-44ff-8e74-677a22f652d9.MOV

**Comment by jurialmunkey** [comment]
Does this issue still exist in Nexus or was it resolved?

**Comment by xyzfre** [comment]
I have disabled Get resume points from Trakt, like 3 months ago but let me enable it and I will definitely get back to you ,thank you @jurialmunkey 💯
