### ISSUE TITLE
Query..... Never really ben answered for me.

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/plugin.video.themoviedb.helper#737]
Good Morning,

Firstly before I possibly make myself sound like an idiot.
A massive thank you for the time and effort you put into your addon with updates, and not to mention all the responses you give.

My question is..... I use library strm files a lot, 
But my set up (using auramod) takes a good 20 seconds or so when I select a movie, when it is constructing players, getting player dialogue etc....
Obviously spinning in the top right corner. 

I obviously have my default player already installed, but is there not a way that it just automatically goes straight to that, woth constructing players etc?

Apologies in advance if answered prior, I did try searching through before asking.

**Comment by jurialmunkey** [comment]
> But my set up (using auramod) takes a good 20 seconds or so when I select a movie, when it is constructing players, getting player dialogue etc....

It simply shouldn't take that long. It should only take a few seconds for TMDbHelper to do its job.

I just tested a strm and it took less than 3 seconds from pressing enter to showing the select dialog - and since the item details request involves an API call you would expect it to take a few seconds just like loading any webpage does.

Could you get me a debug log please?

**Comment by adamosborne83** [comment]
> 

Https://paste.kodi.tv/uranavanik

Thank you so much.

**Comment by adamosborne83** [comment]
Problem being that log only shows it taking about 3 seconds. I will try and get a log when it takes the time I mention.....
It's not consistent.

**Comment by jurialmunkey** [comment]
> Problem being that log only shows it taking about 3 seconds. I will try and get a log when it takes the time I mention..... It's not consistent.

Yeah I would need a log of the issue. A log of it working as expected doesn't tell me much!

Also FYI the log you linked appears to be empty (at least I don't appear to be able to open it).

**Comment by adamosborne83** [comment]
> > Problem being that log only shows it taking about 3 seconds. I will try and get a log when it takes the time I mention..... It's not consistent.
> 
> Yeah I would need a log of the issue. A log of it working as expected doesn't tell me much!
> 
> Also FYI the log you linked appears to be empty (at least I don't appear to be able to open it).

Apologies for the link, don't know what happened.....

Https://paste.kodi.tv/ifozujoquk

**Comment by adamosborne83** [comment]
OK kodi log uploaded doesn't seem to be working. 

Close this and ignore me until I can present the log.
Apologies

**Comment by jurialmunkey** [comment]
Okay no worries. Just let me know of you manage to get a log with it taking a long time.
