### ISSUE TITLE
[Feature] Adding Genres for Trakt to give you more of a selection like Seren.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/plugin.video.themoviedb.helper#738]
**Is your feature request related to a problem? Please describe.**
It is related to a problem im having. Tmdb does not give you many Genres and I think it would be a very useful and better feature to have. It gives you more Genres and a more variety of Movies and TV Shows. 

**Describe the solution you'd like**
What I would like to happen is to have a Genres button for Trakt in Movies and TV Shows Category and also having a Genres button in the Trakt category as well like how you implanted the Tmdb Genres. 

**Describe alternatives you've considered**
- Open Meta or Open info if they were still alive. (There dead)
- Finding an addon that would do the same as tmdb helper. (Doubt it)

**Examples of what i would like to happen**
- I Sadly Could not make a Movies Example. 

TV Shows Example
![TV Shows Example](https://user-images.githubusercontent.com/62456796/170289977-36953164-7e40-4cda-9b61-fccc0c3dda47.png)

Trakt Example
![Trakt Example](https://user-images.githubusercontent.com/62456796/170289992-5c300f4a-d5f5-4557-ae1c-566add734006.png)

Genre Icon Example
![genre](https://user-images.githubusercontent.com/62456796/170290527-fd8bd058-8414-43b8-be11-d01397ff697f.png)
- I gone ahead into photoshop and made this genre.png for you incase you would like to use it for your addon.

**Comment by drinfernoo** [comment]
What genres are you not being able to find?

**Comment by Goldenfreddy0703** [comment]
Hey so here are a few things i can't find when using tmdb genre. I did some comparisons with trakt genre and tmdb genre to answer your question. 

## TV Shows
TV Shows - For Action and Adventure for TV Shows are stuck together and you can't separate them unless there is a rule.
TV Shows - Sci-Fi and Fantasy are also stuck together and you can't separate them unless there is a rule.
TV Shows - There is not Romance genre unless that's what soup is.
TV Shows - There is no Anime genre and to make one, you would probably have to add a rule to that with the Keywords.
TV Shows - There is no Biography, History, Holiday, Home % Garden, Superhero, Mini Series, Music, Musical, Suspense, Thriller, Sporting Event, Short Genre (Trakt has all of these)

## Movies
Movies - There is no Anime genre and to make one, you would probably have to add a rule to that with the Keywords.
Movies - There is no Holiday, Musical, Short, Sporting Event, Superhero, Suspense, Romance( Trakt also has all of these)

**Comment by Goldenfreddy0703** [comment]
Hey if you guys do consider adding Trakt Genres to TMDB Helper. Here is a list of Trakt Icons i've Photoshop. The Source of these icons came from the Seren Genres category and these can be used for personal use, not commercial use. 
[Trakt Genre Icons.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/8777942/Trakt.Genre.Icons.zip)

## Trakt Genre Icons
![image](https://user-images.githubusercontent.com/62456796/170460561-993285f1-0103-4447-a282-b81a90b3f84c.png)

**Comment by Goldenfreddy0703** [comment]
Hey guys, I know it's been awhile and you guys have been busy with artic horizon 2 skin and I really love using the skin but anychance we could add Trakt genre's to Tmdb helper, I love using Tmdb helper for my android tv and everything just loads really fast. If you guys have time to add this, that would be wonderful. 
Thank you

**Comment by jurialmunkey** [comment]
Definitely will be including these. I've just got to write some code to allow dropping in an icon pack because some of these are non-commercial use only which is incompatible with the opensource GPL license that TMDbH has (GPL also allows commercial use).

So the solution is to include as a separate icon pack "module" and then have a button in settings to install it. That way it can be distributed with a different license.

**Comment by jurialmunkey** [comment]
Oh wait you were asking about the genres themselves not the icon pack. But yeah same again - will definitely be adding, I just need to get the spare time to write the code!

**Comment by Goldenfreddy0703** [comment]
Oh ok, thank you so much for telling me. I did not know some of these icons are incompatible with the opensource GPL license becouse seren has these icons for there genres, may need to tell doc or nixgates to change them and make some of my own. Thank you. 

You can also replace each genre with the trakt logo so it can be like tmdb genres

**Comment by jurialmunkey** [comment]
Yeah by default I will use that approach for the icons (use default trakt icon) and then will override if icon pack is installed.


And yeah "personal use only" or "non-commercial" licences are only "gratis" free (free as in beer) and not "libre" free (free as in freedom), so they aren't compatible with gpl because they have restrictions on use.

I have no problem with using a noncom restricted licence for other projects (all my skins are Creative Commons NonCommercial Attribution Required). Just need to make sure the licence of any assets used match with the project licence is all!

**Comment by Goldenfreddy0703** [comment]
> Oh wait you were asking about the genres themselves not the icon pack. But yeah same again - will definitely be adding, I just need to get the spare time to write the code!

Hey that's good to hear, thank you very much. You can just do the genres themselves if you like and just use this logo for each genre. 
![Trakt](https://user-images.githubusercontent.com/62456796/174696293-ece6ccf2-1831-4b6d-8f26-5e4dd0ec2119.png)

**Comment by Goldenfreddy0703** [comment]
> And yeah "personal use only" or "non-commercial" licences are only "gratis" free (free as in beer) and not "libre" free (free as in freedom), so they aren't compatible with gpl because they have restrictions on use.

Oh ok that makes sense, thank you

**Comment by Goldenfreddy0703** [comment]
Hey this is the same link:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/740#issuecomment-1178438171

**Comment by psp2111-ADSLGATE** [comment]
> Oh wait you were asking about the genres themselves not the icon pack. But yeah same again - will definitely be adding, I just need to get the spare time to write the code!

Trakt Genres will be an awesome addition to TMDbHelper cant wait for that 👍 .
because when I change the language and region to "Arabic Saudi Arabia" in the setting, the native TMDb Genres are lacking content and some have no result at all.

**Comment by jurialmunkey** [comment]
> 

I didnt think the genre listings were region specific on tmdb - they shouldnt be because the genres are just ids which a movie either has or doesn't.

If you mean the items themselves are missing info, then trakt genres won't solve that - practically all metadata comes from TMDb as trakt doesn't supply artwork or detailed information.

**Comment by psp2111-ADSLGATE** [comment]
> > 
> 
> I didnt think the genre listings were region specific on tmdb - they shouldnt be because the genres are just ids which a movie either has or doesn't.
> 
> If you mean the items themselves are missing info, then trakt genres won't solve that - practically all metadata comes from TMDb as trakt doesn't supply artwork or detailed information.

no no not missing info, I know the info need to be added in TMDb website for specific language to show up in the add-on

What I mean by the lake of content is the numbers of movies in specific section of genres.
for example: "Animation" section or in Arabic "رسوم متحركة" only show around 15 movies while in tmdb website there are 40000+ movies for that section alone.

@jurialmunkey you can test it really quickly by changing the language and country in the settings to Arabic Saudi Arabia and go to Movies Genres.
it is also affects other languages not only Arabic, I thought it was how TMDb API works, if it a BUG tell me I will report it.

**Comment by jurialmunkey** [comment]
Okay that's really odd! I had assumed language/region wouldn't matter for genres since it is ID based (and surely an Action movie is an Action movie everywhere in the world!)

**Comment by Goldenfreddy0703** [comment]
> Okay that's really odd! I had assumed language/region wouldn't matter for genres since it is ID based (and surely an Action movie is an Action movie everywhere in the world!) 

In a way, I don't think it's odd becouse if you think about region or language depending on where you live or speak, It would still be ID based but with rules added. It would be using your location or country your in, add the default language or region, then it would default to that depending on where you are. It's basically like tmdb advanced filtering system or trakt advanced filtering system.

**Comment by psp2111-ADSLGATE** [comment]
yeah I know, I discovered this last week when I was translating the addon.
that's why I think Trakt Geners will be a nice and a better alternative, specially if you add "Multi Select" function with it.
OH that's going to be the cherry on top. 🙏

**Comment by Goldenfreddy0703** [comment]
Thank you for discovering this @psp2111-ADSLGATE , now I can have more of a variety with tmdb rules especially by changing the region to Japan with anime as keyword.

**Comment by jurialmunkey** [comment]
Just realised it is because the TMDb API is filtering out movies without release information for your region.

Please try v4.10.20. I've added an option in general settings to `ignore region release filter` which will set TMDbHelper's region param to None. That will stop the TMDb API from filtering out items without release dates for your region (essentially sets the region to "any").

The region should still apply for providers / certifications / images etc. - it just removes the region release filter.

**Comment by psp2111-ADSLGATE** [comment]
> Just realised it is because the TMDb API is filtering out movies without release information for your region.
> 
> Please try v4.10.20. I've added an option in general settings to `ignore region release filter` which will set TMDbHelper's region param to None. That will stop the TMDb API from filtering out items without release dates for your region (essentially sets the region to "any").
> 
> The region should still apply for providers / certifications / images etc. - it just removes the region release filter.

OMG @jurialmunkey 😍
it is perfect now and working as it should be. thank you for the fast response.

Update: Discover section is acting weird, I cant add more than one rule?!
Update2: I think it is a Bug with AH2 not TMDbHelper, because I changed the skin back to Estuary and Discover is working as it should be. and I can add as many rules as I want with no issue.

**Comment by Goldenfreddy0703** [comment]
Hey, sorry for bothering but i just had a small question about the Genres for Trakt. Seren had a 2 options called "Base List Type for Movie/TV Genres" and what it did was it set each genre with the trakt category you picked. 
![image](https://user-images.githubusercontent.com/62456796/182276247-761b3bb5-1d6a-4836-bdbc-c1087fa46137.png)
Are you going to add an option or discover rule like this for tmdb helper and have categories like Most Popular, Most Played, Most Watched, Most Collected, Trending, Anticipated, ect?

**Comment by jurialmunkey** [comment]
@Goldenfreddy0703 - illl have to have a closer look at the api before deciding on exact approach but yes should be able to add a filter for these lists. I'd look for a better approach than a setting because I don't like how that locks you into one option - itd be much better to be able to mix and match filters/sort like you can with tmdb discover

**Comment by Goldenfreddy0703** [comment]
Honestly I agree, if you can get multiple filters for genres, I would love that so much and it will give me more sections to make more anime sections. 

Thank you very much and hope the api has more filters for genres.

**Comment by jurialmunkey** [comment]
@Goldenfreddy0703 - This one is also added now.

Using trakt genre slugs for the icon names, so should work with your existing icon pack for this one (the slugs don't change for language and they match the english name).

There is now a Trakt "Genres" directory inside Movies and TV. Opening the genres will then open a subfolder for the genre where you can pick whether to filter by trending, popular, most played, most watched, or anticipated.

Additionally, you can now do more advanced filtering of those trakt lists via plugin url - `%2C` is comma character for separating multiple genres

```
plugin://plugin.video.themoviedb.helper/?info=trakt_trending&amp;genre=action%2Cadventure&amp;tmdb_type=movie
```

Other possible filters as per Trakt API:
https://trakt.docs.apiary.io/#introduction/filters

More advanced filtering example:
Popular Action and Adventure Movies from 2010 to 2020 that have the keyword Aliens
```
plugin://plugin.video.themoviedb.helper/?info=trakt_popular&amp;genre=action%2Cadventure&amp;tmdb_type=movie&amp;years=2010-2020&amp;query=Aliens
```

**Comment by Goldenfreddy0703** [comment]
Hey sorry I was asleep but that is very interesting and it gives you more menu options for a certain genre, I like that. That is really interesting. Will have to look into this more this afternoon. 

Thank you

**Comment by xyzfre** [comment]
Thank you @Goldenfreddy0703 and @jurialmunkey for this new feature it really comes in handy I made a separate section in my personal AH2❤️💯build ,,AH2 is the best skin I've ever tried in years
