### ISSUE TITLE
(Request) Tmdb or Trakt; Latest releases

### ISSUE THREAD

**Issue by brentonv** [jurialmunkey/plugin.video.themoviedb.helper#74]
Would it be possible to include latest releases in either Tmdb or Trakt lists? The closest thing I can find is trending lists. Thankyou

**Comment by jurialmunkey** [comment]
TheMovieDb > Upcoming Movies
TheMovieDb > In Theatres
TheMovieDb > Airing Today
TheMovieDb > Currently Airing

**Comment by brentonv** [comment]
I've tried those lists but they aren't as good as the ones used in OpenMeta such as "Latest Releases (Trakt)". Thanks anyway

**Comment by drinfernoo** [comment]
@brentonv The list he linked at the bottom of his comment *is* the list you're referring to, that is "built in" to OpenMeta. Simply 👍 that list on the website, and it will show up alongside your own and other liked lists inside of TMDb Helper.

**Comment by brentonv** [comment]
Oh that's great. I've been wondering where this list come from. Thanks
again guys

**Comment by brentonv** [comment]
Oh that's great. I've been wondering where this list come from. Thanks
guys
