### ISSUE TITLE
[Feature] Extra fanart

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#742]
Is there a possibility to implement this function? I know that this function is supported in elementum (of course skin support is necessary). I also found an old elementum issue so I hope it helps you.
https://github.com/elgatito/plugin.video.elementum/issues/650

**Comment by jurialmunkey** [comment]
You do realise that thread you linked is saying to look at TMDbHelper for how it supports extra fanart?

**Comment by matke-84** [comment]
Hahaha. Now i realise. 
But for some reason it doesn't work for me. Should I turned on some option in the tmdb helper. In the elementum, as soon as I enable the option in the skin, the extrafanart works.

**Comment by jurialmunkey** [comment]
> Hahaha. Now i realise. But for some reason it doesn't work for me. Should I turned on some option in the tmdb helper. In the elementum, as soon as I enable the option in the skin, the extrafanart works.

Ah yep I made a mistake in one of the recent artwork updates and forgot to set language to false for fanart (most have no language so they were getting filtered out). 

Should be fixed now, you'll need to refresh artwork for cached items.

**Comment by matke-84** [comment]
Yes, now everything is working properly.
