### ISSUE TITLE
[BUG] Unable to authenticate trakt 

### ISSUE THREAD

**Issue by kagz-93** [jurialmunkey/plugin.video.themoviedb.helper#750]
**Describe the bug**
I just did a fresh install on my Kodi 19.4 and I am now having trouble logging into my trakt account. When I try to authorize trakt I am getting a confirmation on the trakt website but when I try to navigate trakt in TMDB Helper I am unable to navigate into my trakt lists. I get a busy loading spinner and then nothing happens. Any help would be really appreciated.

Thanks!

**Debug log**
https://paste.kodi.tv/takesenoju

**Comment by matke-84** [comment]
I can confirm that this is happening to me as well. Also it happens that it passes authentication, but the menu does not say that it is registered on the trakt.

**Comment by jurialmunkey** [comment]
Are you still having this issue? I'm unable to reproduce.

I deleted my `userdata/addon_data/plugin.video.themoviedb.helper` folder then started Kodi, authenticated Trakt and everything worked immediately.

**Comment by kagz-93** [comment]
> Are you still having this issue? I'm unable to reproduce.
> 
> I deleted my `userdata/addon_data/plugin.video.themoviedb.helper` folder then started Kodi, authenticated Trakt and everything worked immediately.

I confirm after deleting the addonss33.db folder and restarting Kodi I am now able to authenticate trakt. Thanks!
