### ISSUE TITLE
Last played show clear logo on OSD

### ISSUE THREAD

**Issue by kagz-93** [jurialmunkey/plugin.video.themoviedb.helper#751]
Hi Jurial,

I've noticed a small bug with clear logos in the OSD. If I play an episode or movie with clear logo available for the title in the OSD the clear logo displays correctly as the title on the OSD. If I then play a movie or episode that does not have a clear logo available the clear logo from the last played show or movie pops up in the OSD for the title rather than falling back to regular text and showing the correct movie or episode title. This isn't a huge issue but can be a little distracting as the clear logo is sometimes not correct and can get confusing. 

I'm not sure if this is a small fix but I just wanted to bring it to your attention.  

Thanks again for all your hard work I'm really enjoying the skin.

**Comment by xyzfre** [comment]
I have also experienced this occasionally I actually thought it was something on my end till I saw this post

**Comment by jurialmunkey** [comment]
Yeah I can confirm. Occasionally TMDbH doesn't clear out the old logo. I've had it happen with shows that do have logos, so I'm not 100% on what is actually the underlying cause.

**Comment by kagz-93** [comment]
> Yeah I can confirm. Occasionally TMDbH doesn't clear out the old logo. I've had it happen with shows that do have logos, so I'm not 100% on what is actually the underlying cause.

That's interesting, I was thinking the cause was the show or movie not having a clear logo, I guess not. It's not a huge deal it doesn't happen that often anyway.

**Comment by JacopoV** [comment]
I did noticed this issue too, but only in the case from content having clear logo to some that has none, just plain text. 

At least i ve noticed only in these occasions

**Comment by jurialmunkey** [comment]
@IG2022 @JacopoV @xyzfre - Looking at this again I had a bit of a lightbulb moment about what the cause might be and I *think* I've managed to fix it. Could you test v4.10.16 of TMDbH and see if it fixes things for you guys?

**Comment by JacopoV** [comment]
@jurialmunkey did some run to be sure they weren't a fluke and it seems indeed fixed.

Now if you test a video with clear logo > stop > play something else with no clear logo (pure text) it's all right.
No more clear logo from the previous video

**Comment by kagz-93** [comment]
> @IG2022 @JacopoV @xyzfre - Looking at this again I had a bit of a lightbulb moment about what the cause might be and I _think_ I've managed to fix it. Could you test v4.10.16 of TMDbH and see if it fixes things for you guys?

Looks like this might be fixed. I've tested it  and I didn't have any appearance of the previous clear logo. Thanks for sorting this out!

**Comment by xyzfre** [comment]
> @IG2022 @JacopoV @xyzfre - Looking at this again I had a bit of a lightbulb moment about what the cause might be and I *think* I've managed to fix it. Could you test v4.10.16 of TMDbH and see if it fixes things for you guys?

Did a bit of testing it looks like you have fixed the issue I'll do some more testing tonight so far so good like always thank you so much for all your AMAZING work

**Comment by JacopoV** [comment]
Tested more and deeply and I'd say it's fixed ✌️🎉

Thanks a lot for your work!!

**Comment by jurialmunkey** [comment]
Excellent thanks everyone for confirming -- Glad I finally figured out what the issue was as it was really bugging me!
