### ISSUE TITLE
[BUG] Preferred artwork for thumbs

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#753]
**Describe the bug**
Tmdb helper v4.8.6
Changing ‘next aired/ next episodes-preferred artwork for thumbs’ to fanart has no effect on ‘your next episodes’ artwork on home screen widget or within tmdb helper addon. Changing preferred artwork to thumbs/ landscape works fine. 

Tried enabling/disabling ‘use fanart.tv for widget artwork’ - clearing cache & rebooting each time - and deleted tmdb helper database, kodi thumbnails & textures13.db just to be as sure as I can that I’m not wasting your time) but no luck.

**Comment by jurialmunkey** [comment]
That's not what that setting does.

It changes artwork in the trakt calender.
