### ISSUE TITLE
TMDB Helper Your in progress episodes Trakt question

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/plugin.video.themoviedb.helper#754]
@jurialmunkey i was curious to understand why progress marks show up if I go directly into the TMDB helper Addon but not if I link to my home widget? Maybe a setting I am missing. Pics below

Pic shows home widget from TMDB Your in progress episodes 

![image](https://user-images.githubusercontent.com/63697905/172783747-18646dda-ce8c-4fdb-bb2a-34503444a29b.jpeg)

Pic shows going directly into TMDB Your in progress episodes 

![image](https://user-images.githubusercontent.com/63697905/172783879-9239ec72-00ef-4c3c-82f7-7274f0c4aef4.jpeg)

**Comment by jurialmunkey** [comment]
Are you using the setting to retrieve from trakt?

I think it is probably a tmdbhelper issue with path not matching library due to the widget param being appended.

I'm going to transfer this issue to db helper github.

**Comment by derrgoo** [comment]
> Are you using the setting to retrieve from trakt?
> 
In TMD helper I authenticate trakt tried checking get watched indicators from trakt. Still couldn't see on home widget. 

> I'm going to transfer this issue to db helper github. 

Thanks I couldn't find the group to post this.

**Comment by jurialmunkey** [comment]
Could you try v4.8.9?
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.8.9

Also make sure you have enabled 
`TMDbH Settings > Accounts > Get resume points from Trakt`

**Comment by derrgoo** [comment]
💥 perfect as usual. Thanks 🙏

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/172926348-508a6462-0c2c-4e20-b423-36d1906e89b8.jpeg) GREAT work these new resume progress icons are perfect
