### ISSUE TITLE
[Feature] Reload Widgets in context menu

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/plugin.video.themoviedb.helper#755]
Depending on the device (low end) it can take a long time to update widgets to adjust. A manual Reload Widgets would be very helpful on context menu. 

Thank you

**Comment by jurialmunkey** [comment]
Not possible. Kodi controls when containers reload.

**Comment by derrgoo** [comment]
Tikipeter had it on plug in. It would update that widget line.

**Comment by jurialmunkey** [comment]
That's not allowed on official repo.

**Comment by derrgoo** [comment]
Ok understand 👍😅
