### ISSUE TITLE
[Request] Create HBOgoeu player

### ISSUE THREAD

**Issue by webmaher** [jurialmunkey/plugin.video.themoviedb.helper#76]
I already contact author https://forum.kodi.tv/showthread.php?tid=339798&pid=2921427#pid2921427
and he will help us with minor modification...

**Comment by drinfernoo** [comment]
Until that developer does change his search path, there's not much that can be done. *After* that, creating a player should be as simple as following the wiki page. There really doesn't need to be an issue for *every* prospective player...

**Comment by webmaher** [comment]
i dont know what is right and what not... im just a poor old man :-)
