### ISSUE TITLE
[BUG] Does not work well in Hebrew

### ISSUE THREAD

**Issue by The-cpu-max** [jurialmunkey/plugin.video.themoviedb.helper#762]
**Describe the bug**
When I change the language to Hebrew, I can not enter - in series under the category of providers
Plus a lot of the extensions just don't work in Hebrew like Ghost

**Debug log**
Include your FULL kodi.log file uploaded to https://paste.kodi.tv/
https://paste.kodi.tv/owigiwaduw.kodi

**Comment by jurialmunkey** [comment]
Please provide exact steps to reproduce whatever the issue is. I have no idea what the hell "ghost" is.

I have no idea what you are talking about.

**Comment by The-cpu-max** [comment]
> Please provide exact steps to reproduce whatever the issue is. I have no idea what the hell "ghost" is.
> 
> I have no idea what you are talking about.

When I try to get into series - there is a category called Providers
It does not work when the language is Hebrew.
Same thing, when I try to play a movie with the  add-on called Ghost

**Comment by jurialmunkey** [comment]
I have nothing to do with that addon and I don't maintain 3rd party players.

Ask the author of that player and addon why it doesn't work with Hebrew.

**Comment by The-cpu-max** [comment]
> player
ok and why its not open Providers category ?
its on your addon
![image](https://user-images.githubusercontent.com/102416233/173185952-aae26126-b943-4baf-9fd3-7dce49dbf94b.png)

**Comment by The-cpu-max** [comment]
> I have nothing to do with that addon and I don't maintain 3rd party players.
> 
> Ask the author of that player and addon why it doesn't work with Hebrew.

ok and why its not open Providers category ?
its on your addon

**Comment by jurialmunkey** [comment]
Because tmdb api does not have providers for your region

Regions with provider data
```
results": [
    {
      "iso_3166_1": "AR",
      "english_name": "Argentina",
      "native_name": "Argentina"
    },
    {
      "iso_3166_1": "AT",
      "english_name": "Austria",
      "native_name": "Austria"
    },
    {
      "iso_3166_1": "AU",
      "english_name": "Australia",
      "native_name": "Australia"
    },
    {
      "iso_3166_1": "BE",
      "english_name": "Belgium",
      "native_name": "Belgium"
    },
    {
      "iso_3166_1": "BR",
      "english_name": "Brazil",
      "native_name": "Brazil"
    },
    {
      "iso_3166_1": "CA",
      "english_name": "Canada",
      "native_name": "Canada"
    },
    {
      "iso_3166_1": "CH",
      "english_name": "Switzerland",
      "native_name": "Switzerland"
    },
    {
      "iso_3166_1": "CZ",
      "english_name": "Czech Republic",
      "native_name": "Czech Republic"
    },
    {
      "iso_3166_1": "DE",
      "english_name": "Germany",
      "native_name": "Germany"
    },
    {
      "iso_3166_1": "DK",
      "english_name": "Denmark",
      "native_name": "Denmark"
    },
    {
      "iso_3166_1": "EE",
      "english_name": "Estonia",
      "native_name": "Estonia"
    },
    {
      "iso_3166_1": "ES",
      "english_name": "Spain",
      "native_name": "Spain"
    },
    {
      "iso_3166_1": "FI",
      "english_name": "Finland",
      "native_name": "Finland"
    },
    {
      "iso_3166_1": "FR",
      "english_name": "France",
      "native_name": "France"
    },
    {
      "iso_3166_1": "GB",
      "english_name": "United Kingdom",
      "native_name": "United Kingdom"
    },
    {
      "iso_3166_1": "HU",
      "english_name": "Hungary",
      "native_name": "Hungary"
    },
    {
      "iso_3166_1": "ID",
      "english_name": "Indonesia",
      "native_name": "Indonesia"
    },
    {
      "iso_3166_1": "IE",
      "english_name": "Ireland",
      "native_name": "Ireland"
    },
    {
      "iso_3166_1": "IN",
      "english_name": "India",
      "native_name": "India"
    },
    {
      "iso_3166_1": "IT",
      "english_name": "Italy",
      "native_name": "Italy"
    },
    {
      "iso_3166_1": "JP",
      "english_name": "Japan",
      "native_name": "Japan"
    },
    {
      "iso_3166_1": "KR",
      "english_name": "South Korea",
      "native_name": "South Korea"
    },
    {
      "iso_3166_1": "LT",
      "english_name": "Lithuania",
      "native_name": "Lithuania"
    },
    {
      "iso_3166_1": "MX",
      "english_name": "Mexico",
      "native_name": "Mexico"
    },
    {
      "iso_3166_1": "NL",
      "english_name": "Netherlands",
      "native_name": "Netherlands"
    },
    {
      "iso_3166_1": "NO",
      "english_name": "Norway",
      "native_name": "Norway"
    },
    {
      "iso_3166_1": "NZ",
      "english_name": "New Zealand",
      "native_name": "New Zealand"
    },
    {
      "iso_3166_1": "PH",
      "english_name": "Philippines",
      "native_name": "Philippines"
    },
    {
      "iso_3166_1": "PL",
      "english_name": "Poland",
      "native_name": "Poland"
    },
    {
      "iso_3166_1": "PT",
      "english_name": "Portugal",
      "native_name": "Portugal"
    },
    {
      "iso_3166_1": "RU",
      "english_name": "Russia",
      "native_name": "Russia"
    },
    {
      "iso_3166_1": "SE",
      "english_name": "Sweden",
      "native_name": "Sweden"
    },
    {
      "iso_3166_1": "TR",
      "english_name": "Turkey",
      "native_name": "Turkey"
    },
    {
      "iso_3166_1": "US",
      "english_name": "United States of America",
      "native_name": "United States"
    },
    {
      "iso_3166_1": "ZA",
      "english_name": "South Africa",
      "native_name": "South Africa"
    }
  ]
```

**Comment by The-cpu-max** [comment]
> Because tmdb api does not have providers for your region
> 
> Regions with provider data
> 
> ```
> results": [
>     {
>       "iso_3166_1": "AR",
>       "english_name": "Argentina",
>       "native_name": "Argentina"
>     },
>     {
>       "iso_3166_1": "AT",
>       "english_name": "Austria",
>       "native_name": "Austria"
>     },
>     {
>       "iso_3166_1": "AU",
>       "english_name": "Australia",
>       "native_name": "Australia"
>     },
>     {
>       "iso_3166_1": "BE",
>       "english_name": "Belgium",
>       "native_name": "Belgium"
>     },
>     {
>       "iso_3166_1": "BR",
>       "english_name": "Brazil",
>       "native_name": "Brazil"
>     },
>     {
>       "iso_3166_1": "CA",
>       "english_name": "Canada",
>       "native_name": "Canada"
>     },
>     {
>       "iso_3166_1": "CH",
>       "english_name": "Switzerland",
>       "native_name": "Switzerland"
>     },
>     {
>       "iso_3166_1": "CZ",
>       "english_name": "Czech Republic",
>       "native_name": "Czech Republic"
>     },
>     {
>       "iso_3166_1": "DE",
>       "english_name": "Germany",
>       "native_name": "Germany"
>     },
>     {
>       "iso_3166_1": "DK",
>       "english_name": "Denmark",
>       "native_name": "Denmark"
>     },
>     {
>       "iso_3166_1": "EE",
>       "english_name": "Estonia",
>       "native_name": "Estonia"
>     },
>     {
>       "iso_3166_1": "ES",
>       "english_name": "Spain",
>       "native_name": "Spain"
>     },
>     {
>       "iso_3166_1": "FI",
>       "english_name": "Finland",
>       "native_name": "Finland"
>     },
>     {
>       "iso_3166_1": "FR",
>       "english_name": "France",
>       "native_name": "France"
>     },
>     {
>       "iso_3166_1": "GB",
>       "english_name": "United Kingdom",
>       "native_name": "United Kingdom"
>     },
>     {
>       "iso_3166_1": "HU",
>       "english_name": "Hungary",
>       "native_name": "Hungary"
>     },
>     {
>       "iso_3166_1": "ID",
>       "english_name": "Indonesia",
>       "native_name": "Indonesia"
>     },
>     {
>       "iso_3166_1": "IE",
>       "english_name": "Ireland",
>       "native_name": "Ireland"
>     },
>     {
>       "iso_3166_1": "IN",
>       "english_name": "India",
>       "native_name": "India"
>     },
>     {
>       "iso_3166_1": "IT",
>       "english_name": "Italy",
>       "native_name": "Italy"
>     },
>     {
>       "iso_3166_1": "JP",
>       "english_name": "Japan",
>       "native_name": "Japan"
>     },
>     {
>       "iso_3166_1": "KR",
>       "english_name": "South Korea",
>       "native_name": "South Korea"
>     },
>     {
>       "iso_3166_1": "LT",
>       "english_name": "Lithuania",
>       "native_name": "Lithuania"
>     },
>     {
>       "iso_3166_1": "MX",
>       "english_name": "Mexico",
>       "native_name": "Mexico"
>     },
>     {
>       "iso_3166_1": "NL",
>       "english_name": "Netherlands",
>       "native_name": "Netherlands"
>     },
>     {
>       "iso_3166_1": "NO",
>       "english_name": "Norway",
>       "native_name": "Norway"
>     },
>     {
>       "iso_3166_1": "NZ",
>       "english_name": "New Zealand",
>       "native_name": "New Zealand"
>     },
>     {
>       "iso_3166_1": "PH",
>       "english_name": "Philippines",
>       "native_name": "Philippines"
>     },
>     {
>       "iso_3166_1": "PL",
>       "english_name": "Poland",
>       "native_name": "Poland"
>     },
>     {
>       "iso_3166_1": "PT",
>       "english_name": "Portugal",
>       "native_name": "Portugal"
>     },
>     {
>       "iso_3166_1": "RU",
>       "english_name": "Russia",
>       "native_name": "Russia"
>     },
>     {
>       "iso_3166_1": "SE",
>       "english_name": "Sweden",
>       "native_name": "Sweden"
>     },
>     {
>       "iso_3166_1": "TR",
>       "english_name": "Turkey",
>       "native_name": "Turkey"
>     },
>     {
>       "iso_3166_1": "US",
>       "english_name": "United States of America",
>       "native_name": "United States"
>     },
>     {
>       "iso_3166_1": "ZA",
>       "english_name": "South Africa",
>       "native_name": "South Africa"
>     }
>   ]
> ```



> "iso_3166_1": "AT",

Where did you find this file?
When I make it a widget it does work

**Comment by jurialmunkey** [comment]
It's not a file. It is the response from the server saying which regions tmdb api supports for watched providers.
