### ISSUE TITLE
[BUG] Player list construction

### ISSUE THREAD

**Issue by kolekan** [jurialmunkey/plugin.video.themoviedb.helper#765]
Although the addon id should be in lowercase, there are many video addons that include uppercase letters in their addon id string. For these ids `get_condvisibility (f'System.AddonIsEnabled ({i}) ')` always returns False.
So i think that it is better to use the json-rpc api to get the status of add-ons for the player list construction function.

**Comment by drinfernoo** [comment]
From [the Kodi wiki](https://kodi.wiki/view/Addon.xml#id_attribute):

> The id attribute is the unique identifier used for this add-on. It must be unique, and must use **only lowercase characters**, periods, underscores, dashes and numbers.

I know that many add-ons put uppercase characters, and they work "fine", but Kodi is *designed* to not support them, and that is a documented limitation.

**Comment by kolekan** [comment]
Actually i haven't seen any other malfunction on those addons caused by their addon id includes uppercase characters to say that kodi is designed to not support them.

**Comment by jurialmunkey** [comment]
Json rpc will be slower than an inbuilt boolean. I'm not making things slower because a few plugins unnecessarily break that convention. 

Tell the plugin author to fix their plugin id.
