### ISSUE TITLE
[BUG] Few Bugs with Trakt and its indicators and scrobbling. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/plugin.video.themoviedb.helper#766]
**Device Information**
OS: Windows 11
Version: Kodi 19.4
Addon: TheMovieDb Helper v4.8.12
Skin: Artic Horizon 2 v0.1.37

**Describe the bug**
Hey, im really sorry to bother but iv'e been having so much trouble with Tmdb Helper and i feel that there are a two bugs that i noticed these past few days. 

1st bug - On TV Shows, you don't see your resume points from Trakt unless you go to "Your In-Progress" Section.

2nd bug - Trakt is not scrobbling anything for some odd reason. I have tried it with players like Seren, Netflix, Ect and none of them are getting scrobbled with Trakt. (I only have Trakt setup for Tmdb helper, not the players)

**Debug log**
[kodi.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/8902693/kodi.zip)
I am sorry, i could not paste on the kodi log website for some odd reason. 

**Steps to Reproduce for 1st Bug**
1. Download Tmdb Helper and the player of your choice.
2. Login to Trakt and have your settings configured in Tmdb helper. (Do not configure Trakt in any of your players)
3. Try any TV Shows and complete an episode.
4. Go back to seasons and back into episodes again on the episode you watched. 
5. Notice the 1st bug that there is no indicators telling you if you watched it or not. 

**Steps to Reproduce for 2nd Bug**
1. After completing the 1st Bug Step, go to another episode but stop halfway. 
2. Go back to seasons and back into episodes again on the episode you watched. 
3. Notice the 2nd bug that there is no resume indicator 
4. Also go to Your In-Progress Episodes to see if there is a resume indicator of the episode you just watched. 

**Screenshots**
![image](https://user-images.githubusercontent.com/62456796/173643862-a8cb8eba-e0db-425e-b9dc-98c5b57edeb0.png)
These are the settings i set for Trakt. 
![image](https://user-images.githubusercontent.com/62456796/173656725-c04f9377-68bb-4f6b-81b3-096551470422.png)
Just Watched two episodes but nothing is updating sadly. 
![image](https://user-images.githubusercontent.com/62456796/173657078-c0890707-d4ba-4ee5-95eb-aeda723d333d.png)
Do not see the rick and morty episode i stopped on. 

**Additional context**
Idk if its just me but i tried asking others about this and everyone was dead or used other players that had there Trakt synced into them. I hope these are actually bugs cause I have tried everything even doing a fresh install as well and on other devices. 

**Checklist**
- [x] I have described the bug and included steps to reproduce the issue
- [x] I have included a full kodi debug log of the error
- [x] I have also tried this with other skins. 
- [x] I have also wiped the addon data completely and did a fresh kodi install as well.

**Comment by xyzfre** [comment]
I could be wrong but I think for your Trakt Scrobble to work properly for example you mention Seren ,you also need to set up your Trakt Info in Seren and any other plug-in you're using as well ,,and of course in TMDB Helper which you said you already set up hope this helps and my apologies if I'm wrong,, I'm using all the same versions you mentioned above but I do not have this issue (Using Nvidia shield pro 2019 K19.4 AH2 AMAZING Skin)😁

**Comment by Goldenfreddy0703** [comment]
What about tv shows, is there a resume indicater when looking looking up a specific TV Show or episode you stopped in the middle of something?

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/173684018-8e7675c8-6a5c-4b1f-b492-c3ae9c869859.jpeg)

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/173685922-1ce4f716-cca2-4781-9d7b-ad3e4d169307.jpeg)

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/173684149-dff42cd1-f5ac-496b-a14d-19a4d9203dd9.jpeg)

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/173685490-87324997-c294-49c0-8e6a-b74fb574aafc.jpeg) Movies

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/173685531-ee6f87f8-dbf3-4027-95a9-5579ed66f25b.jpeg)

**Comment by Goldenfreddy0703** [comment]
Ok go to the search bar and type a tv show like "FBI Most Wanted or "Russian Doll" and go to season 1, episode 8 or season 3, episode 5 and tell me if the resume indicater are on them.

**Comment by xyzfre** [comment]
Stepped away for a minute but will check the search soon I'll keep you posted but Trakt Scrobble Is working very well on my end

**Comment by Goldenfreddy0703** [comment]
Ok great, thank you

**Comment by jurialmunkey** [comment]
Tmdbhelper does not scrobble.

Use kodi trakt plugin to scrobble for library and also plugins using the correct setresolvedurl method. Plugins that shell out to a source script and use hacks to manipulate the xbmc.player will need to manage their own scrobbling 

many of these 3rd party plugins you mention use these hacks which break things such as Kodi's trakt script scrobbling - these hacks are not permitted in kodi repo but because the plugins are 3rd party they have unreviewed code and thus many hacks and so need their own scrobbling service as a result.

**Comment by Goldenfreddy0703** [comment]
> Tmdbhelper does not scrobble.
> 
> Use kodi trakt plugin to scrobble for library and also plugins using setresolvedurl. Plugins that shell out to a source script and use hacks to manipulate the xbmc.player will need to manage their own scrobbling
> 
> many of these 3rd party plugins use these hacks which break things such as Kodi's trakt script scrobbling - these hacks are not permitted in kodi repo but because the plugins are 3rd party they have unreviewed code and thus many hacks.

Ohhhh I actually thought it did because it had library integration and all and i thought Tmdb Helper scrobbles trakt this whole time, Thank you so much for telling me about this. Iv'e been asking people on discord about this and idk if it was me or if other people had issues like this. Thank you so much.

**Comment by Goldenfreddy0703** [comment]
I just have one last issue, the 2nd bug i was telling you about, resume indicators are not showing for tv shows. Is this a bug by anychance?

Seren
![image](https://user-images.githubusercontent.com/62456796/173711873-fa6c5b4d-e98e-434f-a8da-fe087505dadd.png)

Tmdb Helper
![image](https://user-images.githubusercontent.com/62456796/173711948-51b6413a-c364-44c8-b9ee-94f24b31b816.png)

I do have this setting enabled but do not see resume point indicators
![image](https://user-images.githubusercontent.com/62456796/173712104-754cedb8-d906-4940-9443-a8be4a2e1f3a.png)

**Comment by jurialmunkey** [comment]
Library integration just generates strm files for your library which are shortcuts that play with Tmdbhelper. Basically they are files that look like videos to the library so you can scan them but open a plugin url when played.

The point of library integration is so that you can add streaming content to your library from a trakt list eg I have a trakt list of shows that I watch with the Netflix plugin. so I integrate this list so I can have shows like Stranger Things and The Witcher show up in my library next to my local library content but play them using Netflix via tmdbhelper.

**Comment by Goldenfreddy0703** [comment]
Ohh ok that makes sense, Thank you so much for telling me about the library Integration, This helped me understand.

**Comment by jurialmunkey** [comment]
I don't know if that maybe resolves your question about resume points?

Basically for a resume point to display in tmdbhelper, the item progress must've been scrobbled to trakt. If it was local library content, that is via Kodi's trakt script (Netflix and slyguy plugins also appear to work with the official trakt script). If it was a 3rd party plugin using a xbmc.player hack then it must manage scrobbling itself.

As long as the data is on Trakt, tmdbhelper should show it.

**Comment by Goldenfreddy0703** [comment]
Hey sorry, i had to brb real quick but about resume points. The item progress was scrobbled to trakt using 3rd party plugins but the only issue with the resume points is that its just not displaying on tmdb helper for TV Shows. It does in fact display in "Your In-Progress" Items, just not in tv shows. 

For Example: TV Show: Komi Can't Communicate
![image](https://user-images.githubusercontent.com/62456796/173715252-75b51a17-aac2-402b-b377-15da990ebfc5.png)
Image of "Your In-Progress Episodes" In TMDB Helper
It Shows the resume indicator and it has been scrobbled. 

![image](https://user-images.githubusercontent.com/62456796/173715572-744735dd-b971-4eab-b98a-9d2e45fba46b.png)
Image of "Season 1" of Komi Can't Communicate In TMDB Helper
It does not show resume indicator but it has been scrobbled. 

The answer above did resolve my question and it did help but is there a reason why the resume indicator is not in the TV Show itself?

**Comment by jurialmunkey** [comment]
Okay that's definitely a bug. In progress indicator should also display in the episode list for the show (assuming youre in tmdbhelper of course!)

Let me see if I can replicate on that show.

**Comment by Goldenfreddy0703** [comment]
> Okay that's definitely a bug. In progress indicator should also display in the episode list for the show (assuming youre in tmdbhelper of course!)
> 
> Let me see if I can replicate on that show.

YES I KNEW IT WAS A BUG!!!! Thank you very much and your the best

**Comment by jurialmunkey** [comment]
Okay definitely can reproduce with this show and know what the cause is (really dumb obvious mistake on my part).

The weird thing is that it was working correctly for my other shows and I can't really explain why. It shouldn't have been working for any of them.

Can you try v4.8.13 and confirm if it fixes it for you
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.8.13

**Comment by Goldenfreddy0703** [comment]
Yes i will go ahead and test it

**Comment by Goldenfreddy0703** [comment]
Ok so i just tested and it seems to be doing what its supposed to now. Progress is now in the episode list and it its giving the correct percentage too. 

Thank you very much for fixing this bug. This really helped alot

**Comment by derrgoo** [comment]
This thread has led me to believe I cannot use TMDB for trakt progress because I must be using a plug in that has been set up wrong. Therefore it won't show correctly. 

I am just using the first fix which is clock and that works good for what I need😅

**Comment by jurialmunkey** [comment]
> 

If the data is synced to Trakt, then TMDbHelper will use it. As long as the end plugin is compatible with Kodi's official Trakt script or does its own scrobbling, then Trakt will get the data which TMDbHelper can then sync with.

**Comment by derrgoo** [comment]
> > 
> 
> 
>
As long as the end plugin is compatible with Kodi's official Trakt script or does its own scrobbling, then Trakt will get the data which TMDbHelper can then sync with. >

Trakt works and all that but as the one dev we were speaking with most if not all plug ins didn't code it officially so progress doesn't work right.

**Comment by jurialmunkey** [comment]
> > >
> 
> As long as the end plugin is compatible with Kodi's official Trakt script or does its own scrobbling, then Trakt will get the data which TMDbHelper can then sync with. >
> 
> Trakt works and all that but as the one dev we were speaking with most if not all plug ins didn't code it officially so progress doesn't work right.

It will still display in tmdbhelper. Tmdbhelper just can't pass the progress through to the end plugin. If the end plugin does its own scrobbling it will almost certainly also save resume points too. 

At worst you get prompted twice to resume - once by tmdbh and once by end plugin

Also if resume works correctly in the end plugin but not when you play via tmdbh using that same plugin, then that's an issue with the how the player file is configured , not tmdbh or the end plugin.

**Comment by derrgoo** [comment]
Yes, all works fine just no marks 😂. Anyway I've always used your skins. Won't stop now. Hopefully add ons improve proper progress code to follow correctly. 

Appreciate your hard work.
