### ISSUE TITLE
[BUG] Casts are missing from TV show information

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/plugin.video.themoviedb.helper#769]
The cast list for a TV show seems are only partial of major casts, for example, there are only 8 casts for The Big Bang Theory, where https://www.themoviedb.org/tv/1418-the-big-bang-theory/cast shows several hundreds. Don't know how this list in skin is populated, but I can see some important casts are missing. Can this list be extended to at least 20 or some reasonable number?

**Comment by jurialmunkey** [comment]
This issue will be to do with how the TMDb API returns cast credits. 

I agree though, parent tvshow should display full cast not just main cast; and then seasons/episodes should be main cast + guest stars.

I'll see if I can find a solution. Either way, TMDbH issue so I'll transfer to that repo.

**Comment by jurialmunkey** [comment]
Okay looks like the API had a new endpoint added for aggregate cast lists

Please try TMDbHelper v4.8.15 with AH2 v0.1.45 (or higher)
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.8.15
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.45

Adds an option in skin settings to aggregate cast and/or crew lists
`Skin Settings > Details > Aggregate full tv cast/crew list`

**Comment by Hawkedon** [comment]
Thanks @jurialmunkey! I tested the change, it works very well.

**Comment by jurialmunkey** [comment]
Excellent. Thanks for reporting the issue. I discovered a new API call that I didn't know had been added!

Cast being limited to the latest season for tvshows was something that had been bugging me for a while.

**Comment by xyzfre** [comment]
Wow GREAT work tested as well big difference with cast   Showing a lot lot more can't say it enough the skin is coming along AMAZING👏🏼🙌🏼
