### ISSUE TITLE
[Feature] additional context menu settings

### ISSUE THREAD

**Issue by SH1NKS** [jurialmunkey/plugin.video.themoviedb.helper#770]
Hi Jurial,
Would it be possible to have settings for the additional context menu addon so that items could be enabled and disabled please.

**Comment by Goldenfreddy0703** [comment]
Honestly, I would love to have an option to enable players in the context menu so that if it's an anime, I can always select an anime addon without going to select player. 

For example: Context Menu

- Play with (player)

**Comment by urs45** [comment]
I would love to see the context menu folder, tmdbhelper options, in the Standard Kodi Favourites Widget

**Comment by Blahkaey** [comment]
I would also like to disable/enable items from the context menu

**Comment by jurialmunkey** [comment]
Added in next release. Nexus only. Only affects base context menu items, not context menu addon

TMDbHelper Settings > Other > Context Menu

Options possible to disable:

- Browse Lists
- Trakt Options
- Manage Artwork
- Refresh Details
- Add to Library

**Comment by Blahkaey** [comment]
You're a legend mate
