### ISSUE TITLE
[Feature] Disney+ player

### ISSUE THREAD

**Issue by ChronoWerX82** [jurialmunkey/plugin.video.themoviedb.helper#771]
Your plugin is perfect and the player for Netflix and Amazon are amazing. Can you create a player for the Disney+ plugin from Slyguy?

I have problems with the variables. 

Thanks

**Comment by The-cpu-max** [comment]
That will be great
But who can make such a player?

**Comment by jurialmunkey** [comment]
Creation of player files is documented in the Wiki:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#player-files

You can easily adapt one of the other SlyGuy plugins to Disney+ (e.g. Stan, Hulu, and BiNGE are all SlyGuy plugins).

As of v4.9.0 there is a GUI based player file creator in the "Configure Players" section of the settings. This GUI creator won't necessarily make a perfect player but can help you get started by generating a player file for you that you can then edit in a text editor

I have included a SlyGuy plugin template, which should make it extremely simple to generate Player files for SlyGuy plugins.

**Comment by The-cpu-max** [comment]
> Creation of player files is documented in the Wiki: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#player-files
> 
> You can easily adapt one of the other SlyGuy plugins to Disney+ (e.g. Stan, Hulu, and BiNGE are all SlyGuy plugins).
> 
> As of v4.9.0 there is a GUI based player file creator in the "Configure Players" section of the settings. This GUI creator won't necessarily make a perfect player but can help you get started by generating a player file for you that you can then edit in a text editor
> 
> I have included a SlyGuy plugin template, which should make it extremely simple to generate Player files for SlyGuy plugins.

Wow!! You Are The Best 
Its works only when the movie db addon its in english
When I change the language to Hebrew, he searches for the film in Hebrew and then he writes that there are no results.
Is there a way the show will be in Hebrew and he will search for the movie in English so he can find it?
And the second thing, I wanted to know if there is a possibility to delete a player? Or add the delete option here?

**Comment by ChronoWerX82** [comment]
First thanks for your help

Stupid question, where I can find the 4.9.0? I only find 4.8.16

Work on the player. Search is working for movie and episode, play movie is working, but play episode isn't working ... my brain explodes

**Comment by kolekan** [comment]
> Wow!! You Are The Best Its works only when the movie db addon its in english When I change the language to Hebrew, he searches for the film in Hebrew and then he writes that there are no results. Is there a way the show will be in Hebrew and he will search for the movie in English so he can find it? And the second thing, I wanted to know if there is a possibility to delete a player? Or add the delete option here?

Edit your player's json with a text editor and add the following key
`"api_language"      : "en-US",`

**Comment by ChronoWerX82** [comment]
OMG all is working. And not only in english

**Comment by The-cpu-max** [comment]
> > Wow!! You Are The Best Its works only when the movie db addon its in english When I change the language to Hebrew, he searches for the film in Hebrew and then he writes that there are no results. Is there a way the show will be in Hebrew and he will search for the movie in English so he can find it? And the second thing, I wanted to know if there is a possibility to delete a player? Or add the delete option here?
> 
> Edit your player's json with a text editor and add the following key `"api_language" : "en-US",`

where i need to add that?

**Comment by The-cpu-max** [comment]
> OMG all is working. And not only in english

I try and its not work in hebrew

**Comment by ChronoWerX82** [comment]
> > OMG all is working. And not only in english
> 
> I try and its not work in hebrew

I speak from my player

**Comment by The-cpu-max** [comment]
> > > OMG all is working. And not only in english
> > 
> > 
> > I try and its not work in hebrew
> 
> I speak from my player

which player do you mean ?

**Comment by ChronoWerX82** [comment]
> > > > OMG all is working. And not only in english
> > > 
> > > 
> > > I try and its not work in hebrew
> > 
> > 
> > I speak from my player
> 
> which player do you mean ?

my programed

**Comment by kolekan** [comment]
> where i need to add that?

e.g.
    _"name"              : "Hulu",
    "plugin"            : "slyguy.hulu",
    "api_language" : "en-US",
    "priority"          : 100,_

**Comment by kolekan** [comment]
> where i need to add that?
e.g.
    _"name"              : "Hulu",
    "plugin"            : "slyguy.hulu",
    "api_language" : "en-US",
    "priority"          : 100,_

**Comment by The-cpu-max** [comment]
> "api_language" : "en-US",

    "plugin"            : "slyguy.disney.plus",
    "priority"          : 100,
    "is_resolvable"     : "true",
    "make_playlist"     : "true",
	"api_language"      : "en-US",
    "assert"            : {

It works
But it doubled itself 3 times

edit : its me It accidentally backed up three files for me
Now that's fine
Thanks
Do you know why it does not work on other plugs? Like Ghost?
