### ISSUE TITLE
[BUG] can't go to episodes list

### ISSUE THREAD

**Issue by georgew21** [jurialmunkey/plugin.video.themoviedb.helper#772]
If I am on movie information of a series and from widgets I select to go to a season it stays to movie information of series instead to go to episodes and seasons. 

The problem has to do that I have enabled information instead of play in kodi settings.

Steps to reproduce:
1. Enable in kodi settings default action to information instead play.
2. Go to a series and then choose a season.
3. It doesn't go to season

There could be maybe an option to Play in context menu so that can lead to episodes list.

**Comment by jurialmunkey** [comment]
TMDbHelper does not control the behaviour of the info dialog play button.

This issue is skin related. Please open a bug report on whatever skin that you use.
