### ISSUE TITLE
[Feature] BBC iPlayer Player

### ISSUE THREAD

**Issue by louisefindlay23** [jurialmunkey/plugin.video.themoviedb.helper#774]
### Is your feature request related to a problem? Please describe.

It would be great to have a player for the [iPlayer WWW](https://github.com/vonH/plugin.video.iplayerwww) Kodi addon to integrate with #401 BBC-iPlayer watch provider.

### Describe the solution you'd like

The creation of a player.json for file for the BBC iPlayer Kodi addon.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Creation of player files is documented in the Wiki:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#player-files

Additionally, as of v4.9.0 there is a GUI based player file creator in the "Configure Players" section of the settings. This GUI creator won't necessarily make a perfect player but can help you get started by generating a player file for you that you can then edit in a text editor.

The GUI player creator outputs files to:
`.kodi/userdata/addon_data/plugin.video.themoviedb.helper/reconfigured_players` 

Autogenerated player files will be named `autogen.PLUGINID.json`

Possibly after auto-generating a player it may work out of the box, or it might require tweaking in a text editor.
