### ISSUE TITLE
[Feature] Player language

### ISSUE THREAD

**Issue by The-cpu-max** [jurialmunkey/plugin.video.themoviedb.helper#775]
### Is your feature request related to a problem? Please describe.

Problem, when searching to play like Disney's SlyGuy plugins
The MOVIE DB must be in English to search for content

### Describe the solution you'd like

The line should be added automatically to prevent this
"api_language" : "en-US",

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
The wiki has information on setting up players and configuring them.

**Comment by The-cpu-max** [comment]
> The wiki has information on setting up players and configuring them.

This is a total line - which can save a lot of time
Can't just add it?

**Comment by jurialmunkey** [comment]
No. Overriding language is only necessary if the languages in both plugins don't match.

Adding this line will break things for people where the end plugin already matches their language.

**Comment by The-cpu-max** [comment]
> No. Overriding language is only necessary if the languages in both plugins don't match.
> 
> Adding this line will break things for people where the end plugin already matches their language.

So do not have to do much, just add in a line that it prepares the player .. Ask a question Do you want it to be in English?
Yes or No
Then it will do automatically

**Comment by jurialmunkey** [comment]
> So do not have to do much, just add in a line that it prepares the player

Feel free to submit a PR in that case and think through all the different scenarios and use cases and maintain backwards compatability and do unit testing and update the documentation.

It's also not hard for you to configure the player yourself as needed.
