### ISSUE TITLE
[Feature] Add "Do no show resume pop up window" option to "Accounts" > "Trakt API" settings

### ISSUE THREAD

**Issue by titelheld** [jurialmunkey/plugin.video.themoviedb.helper#780]
### Is your feature request related to a problem? Please describe.

**Problem: Double resume pop up** 

When using an addon such as Seren as player and "Get resume points from Trakt" is enabled the resume dialog pops up twice, once from TMDBhelper and once from Seren.

Since Seren is the player it prioritizes Seren's resume setting which are limited to "Ask", "Automatic" and "Do not resume" essentially making TMDBhelper's pop up redundant.

I am using TMDBhelper for widgets and Seren as a player. I really appreciate that TMDBhelper now indicated the watched progress in widgets, an amazing addition! But unfortunatly the double pop up is annoying... so it would be great if the TMDBhelper resume popup could be disabled in the settings.

### Describe the solution you'd like

The solution to this problem could be to add a "Do no ask to resume/Do not show resume pop up window" option in TMDBhelper's setting under "Accounts" > "Trakt API" just beneath the "Get resume points from Trakt" option.

This way the widgets can still show the resume points from Trakt but TMDBhelper would not show its resume pop up when playing a Movie/TV Show and leaves the resume pop up to the the addon used as player.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Not possible. It is a kodi function. Ask plugin author to support setresolvedurl properly and then this problem won't exist
