### ISSUE TITLE
[Feature] Prevent more than one player execution at any time

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#781]
### Is your feature request related to a problem? Please describe.

Sometimes, the underlying provider the player calls takes some time to respond (in my case the EmbyCon plugin) so it seems the player didn't work and sometimes it's just the user pressing too many times the play button. Whenever this happens, depending how many times the player has been executed, it could lead to the video restarting after a few seconds or Kodi freezing or crashing. 

### Describe the solution you'd like

Is there any way to limit the number of player executions at any one time?

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Not really. At least not once it has handed over to the end plugin because it isn't possible to tell what "correct" execution of the end plugin is. If it waited for playback but playback never happened then you would never be able to play anything again.

TMDbHelper could block further executions whilst it is running itself but that doesn't sound like the issue here, especially since generally TMDbHelper only takes a couple of second max to do its side of things.

**Comment by juanma-cvega** [comment]
In my case, most of the time the problem comes from my son trying to play his cartoons. He picks up the remote and starts pressing the play button. So I guess it could reduce the number of times the player is invoked when the button is pressed repeatedly but it wouldn't fix the underlying issue I guess.

**Comment by jurialmunkey** [comment]
I think any "solution" done in the plugin is going to be problematic -- e.g. what if you change your mind after clicking play; or there's some exception/error which stops the playback lock being removed and you're locked out until you restart.

Also, even when functioning properly, every extra click that is discarded will count as a playback failure to Kodi (code didn't run so it didn't get playback for that handle). Get a few in a row and Kodi pop-ups an error message using an OK confirm dialog and stops playback.

It's really something that would need to be addressed in core.
