### ISSUE TITLE
[Feature] Advanced-Filtering for Trakt. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/plugin.video.themoviedb.helper#783]
### Is your feature request related to a problem? Please describe.

It's not related to any problem im having but it would give you more of a selection from trakt. 

### Describe the solution you'd like

I would like to have Advanced Filtering for trakt so that it can be like Tmdb Discover categories. 

### Screenshots and Additional Info

Movies:
![image](https://user-images.githubusercontent.com/62456796/176254006-fec0c94b-1838-4a92-af6b-00dd0899279f.png)
TV Shows:
![1 YdtMAlEx73G6qS6DvjC9OQ](https://user-images.githubusercontent.com/62456796/176246503-c6d7c0d7-282f-4053-bd73-8588626af5b0.png)
Example:
![Discover](https://user-images.githubusercontent.com/62456796/176253287-74f1a937-22a4-46c9-9342-6237acb19212.png)
Sense Tmdb Helper allowed you to customize your own filters in "Discover" from TMDB, I feel that Trakt should also have the same thing so you can have more of a verity of stuff and customization. It was a really great idea to add filtering to TMDB and i think it would be really great to add filtering for Trakt. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Discover is a specific endpoint in the tmdb api. I'm not sure if trakt offers the same via their api.

**Comment by jurialmunkey** [comment]
What exactly are you trying to achieve here that isn't already possible with discover?

**Comment by Goldenfreddy0703** [comment]
Ok well it's basically to get more categories, so with Discover Trakt, let's say I created a category like most collected, I want to add a genre like Anime or Action, I can pick my terms, language, networks, status, ect and it's all from trakt, and not tmdb discover tab. 

Trakt gives you more categories and genres then Tmdb and I think it would be a great idea to have a Discover section for Trakt so you can get more out of it and have more of a selection. 

You probably think it might be the same but there is more to Trakt when it comes to more genres, more categories, more sort results, ect. It's amazing and I think it would be a great feature to add. Now it may take some time to add and all but it would be worth having more Sort Results and more categories to populate.

**Comment by Goldenfreddy0703** [comment]
One last thing, Tmdb Discover does not give you a bunch or Sort Results, I mean yeah you can put keywords but doesn't really mean you can add extra Sort Results:
![image](https://user-images.githubusercontent.com/62456796/176341453-cf55d40c-1455-4bba-bc68-0f0577fb4d02.png)

Trakt on the other hand does and you can add extra filters to it that Tmdb does not have:
![image](https://user-images.githubusercontent.com/62456796/176345273-865a5af1-af5c-46d8-a132-58a146e84d73.png)

**Comment by Goldenfreddy0703** [comment]
Hey so im gonna close this, In the Trakt Api Documentation, they have some filters and it would be hard to do this without Trakt Api's so sorry for making this feature request, I will close this but incase we have api documentation on this in the future, It's possible. Thank you for reviewing this feature request.

**Comment by jurialmunkey** [comment]
@Goldenfreddy0703 - 

> Trakt gives you more categories and genres

If you're looking for an "Anime" genre for tv shows on TMDb then you should use the "anime" keyword
https://www.themoviedb.org/keyword/210024-anime/tv

> In the Trakt Api Documentation, they have some filters and it would be hard to do this without Trakt Ap

Yeah the API doesn't provide many filters. It is really only genre, year, runtime, rating which can all be done with Discover already.

> Trakt on the other hand does and you can add extra filters to it that Tmdb does not have:

Yeah I wish those were possible via the API but unfortunately not. 

Some of these might be possible to achieve as individual sorting option by filtering the data against data from a sync list -- e.g. collection, watched, in-progress, watchlist, rated should all be possible (and also the inverse e.g. unwatched, not in collection etc.). 

The only problem is that lists like Trending are limited to a max item limit of 100 in one page, so there might not necessarily be enough items to make a full page once filtered (or even any at all). Also it might be slow -- needs to sync user data, pull trending list of 100 items, filter the list according to sync data, then manually paginate the list. 

But possibly it could work and I'm not opposed to attempting it as I can definitely see the benefit.


>One last thing, Tmdb Discover does not give you a bunch or Sort Results, I mean yeah you can put keywords but doesn't really mean you can add extra Sort Results 

I'm not sure what you mean here? Discover already has tonnes of sort methods:

![Honeyview_screenshot00137](https://user-images.githubusercontent.com/4618719/176347936-59d2c0b1-0c44-4794-bd28-75ed30651837.jpg)

**Comment by Goldenfreddy0703** [comment]
> If you're looking for an "Anime" genre for tv shows on TMDb then you should use the "anime" keyword
> https://www.themoviedb.org/keyword/210024-anime/tv

Did that and it does help alot especially with the Discover Section.

> Yeah the API doesn't provide many filters. It is really only genre, year, runtime, rating which can all be done with Discover already.

Your right, the api did not provide many filters to begin with.

> The only problem is that lists like Trending are limited to a max item limit of 100 in one page, so there might not necessarily be enough items to make a full page once filtered (or even any at all). Also it might be slow -- needs to sync user data, pull trending list of 100 items, filter the list according to sync data, then manually paginate the list.

I did read about this and it would be slow sense its pulling alot. 

> I'm not sure what you mean here? Discover already has tonnes of sort methods:

I mean it does but its just four or five sort methods, The rest of it is just the same thing but with ascending and descending.

Thank you very much for replying on this. I asked drinfernoo about some of this stuff and yeah main issue was the API Stuff. I should have realized about that but i was thinking about the similarities and Tmdb and Trakt and how Seren has a bunch or trakt stuff and it made me realize when creating this feature request. Thank you very much and for answering all of my questions and for helping me.

**Comment by Goldenfreddy0703** [comment]
Hey im going to go ahead and close this but if you want to reopen this, pls feel free to. Thank you
