### ISSUE TITLE
[BUG] Update broke certain players

### ISSUE THREAD

**Issue by MrC001** [jurialmunkey/plugin.video.themoviedb.helper#784]
### Describe the bug

Update broke certain players that use imdb id -- 

"assert"            : {
                          "play_movie":   ["imdb"],
                          "play_episode": ["epimdb"]
                        },
  "play_movie"        : "plugin://plugin.video.someplugin?action=play&id={imdb}", -- works
  "play_episode"      : "plugin://plugin.video.someplugin?action=play&id={epimdb}" -- episodes do not work anymore

### Steps To Reproduce

Use  TMDb to play episode from player that uses the above formats.  TMDB Helper will only list it now as available player when attempt to play movie only.  Player no longer shows up to be used to play tv show episodes.

Update:  Tried more episodes and they played.  EVIL season 3 ep 3 is on that will not play via player but plays if go straight into the player plugin.  Wierd .. I will leave this here, still some sort of bug.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Please read wiki about what `assert` does
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#assert-keys

**Comment by jurialmunkey** [comment]
No IMDb ID available for this episode on Trakt. Everything is functioning exactly as you've defined in the player. There is no epimdb value so the player is hidden as according to your assert value.

Here is the output of Evil S03E03 from Trakt. As you can see there is no IMDb number.

```json
{
  "log_request": "trakt",
  "response": {
    "season": 3,
    "number": 3,
    "title": "The Demon of Sex",
    "ids": {
      "trakt": 6453510,
      "tvdb": null,
      "imdb": null,
      "tmdb": 3775145,
      "tvrage": null
    },
    "number_abs": null,
    "overview": "Sister Andrea joins the team to fix a demonically possessed marriage, and Leland and Sheryl continue their crusade for Satan.",
    "rating": 7.75814,
    "votes": 215,
    "comment_count": 3,
    "first_aired": "2022-06-26T07:00:00.000Z",
    "updated_at": "2022-06-29T14:51:56.000Z",
    "available_translations": [
      "cs",
      "en"
    ],
    "runtime": 45
  },
  "url": "shows/evil/seasons/3/episodes/3?extended=full"
}
```

**Comment by MrC001** [comment]
I was at work but yes that what I was thinking ,  I was coming back to delete it..lol..

Thank you for the response... my bad ...  Brad Man Bad
