### ISSUE TITLE
[Feature/Question] Would you be able to add one of these three services? (Kitsu, MAL, Anilist)

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/plugin.video.themoviedb.helper#785]
### Is your feature request related to a problem? Please describe.

It is related to a problem for me because i have tried to sync one of these three services with my trakt but i could not achieve that sadly.  

### Describe the solution you'd like

A solution i would really like is to have at least one of these three services to see my progress sense i use tmdb helper most of the time. 

### Screenshots and Additional Info

1. [Kitsu](https://kitsu.io/) - A discovery platform that helps anime and manga fans track, share and discover more of what they love.
- [Kitsu API Docs](https://kitsu.docs.apiary.io/#)

2. [MAL](https://myanimelist.net/) - Basically the same thing as Kitsu except it provides you a list-like system to organize and score anime and manga and provides a large database
- [MyAnimeList API Authorization Documentation](https://myanimelist.net/apiconfig/references/authorization)
- [MyAnimeList API beta Version 2 Documentation](https://myanimelist.net/apiconfig/references/api/v2)
- [MyAnimeList API License and Developer Agreement](https://myanimelist.net/static/apiagreement.html)

3. [Anilist](https://anilist.co/home) - Also same thing as kitsu but this one is probably the easiest to add through there api.
[Anilist-APIv2 Docs](https://anilist.gitbook.io/anilist-apiv2-docs/)

**Important** - These are official API Documentations from each website, not from individual projects. 

 - If one of these could be added to the accounts settings, that would be great so i could have one of these services to see my anime progress. It would really be a big help and i would love to have something like this if possible. If not, its totally fine and i understand. 

**Note** - You do not have to add any anime categories, just accounts to see my progress like trakt. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have done extra research on this and it is possible to add something like this to an addon.
- [X] I have also included what im trying to achieve here.

**Comment by jurialmunkey** [comment]
Tmdbhelper does not do any scrobbling. Scrobbling should be done by a separate addon.

I can possibly add support for retrieving a list but it isn't tmdbhelper's job to track your progress.

**Comment by Goldenfreddy0703** [comment]
> Tmdbhelper does not do any scrobbling. Scrobbling should be done by a separate addon.

That is true and i do have a separate addon that supports scrobbling with Kitsu, MAL,and Anilist.



> I can possibly add support for retrieving a list but it isn't tmdbhelper's job to track your progress.

That would help a ton so i can see my anime content on tmdb helper to see if its completed, in progress, watching, pause, ect.

Btw about the post above, i actually meant to see my progress, not track my progress, sorry about that.

**Comment by jurialmunkey** [comment]
Yeah its very much a maybe but I'll have a look at the apis

**Comment by Goldenfreddy0703** [comment]
That's really great to hear, thank you very much. In the past when i was trying maintain Kaito, One of our contributors: Jkaw updated and improved watchlist in the past.

If you like, feel free to check out are code about the watchlist function and maybe that will help a little. 
https://github.com/Goldenfreddy0703/plugin.video.kaito.beta/commits/main

**Comment by drinfernoo** [comment]
https://kitsu.docs.apiary.io/
https://myanimelist.net/apiconfig/references/api/v2
https://anilist.gitbook.io/anilist-apiv2-docs/

**Comment by jurialmunkey** [comment]
As far as I can tell, none of these APIs provide TMDb IDs. Without a TMDb ID (or at least a Trakt ID) it is not worth it because the details look-up process starts getting really convoluted.

**Comment by Goldenfreddy0703** [comment]
Hey I'm sorry I was asleep but could this help by anychance? 
https://github.com/Goldenfreddy0703/plugin.video.kaito.beta/commit/9135f93cfde6674dbb128d034a47fb248ab7ade4

**Comment by Goldenfreddy0703** [comment]
Ok well if non of these services can work with TMDB Helper then its totally fine and i think our 4th option is to add support to Simkl sense it supports almost every service. 

There was also a feature request about it a month ago:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/718

From looking at the API Docs, it does contain ids from Tmdb and I am 100% guaranteed that it should be able to work.
 - Website: https://simkl.com/
 - Developer Tools: https://simkl.com/settings/developer/
 - Api Documentation: https://simkl.docs.apiary.io/ 
 - Get all items in the user's watchlist: https://simkl.docs.apiary.io/#reference/sync/get-all-items/get-all-items-in-the-user's-watchlist
 - Get items by ID: https://simkl.docs.apiary.io/#reference/redirect/mark-as-watched-from-your-website/get-items-by-id

**Comment by drinfernoo** [comment]
> I am 100% guaranteed that it should be able to work

Sounds very encouraging 😅

**Comment by Goldenfreddy0703** [comment]
> Sounds very encouraging 😅

Hehe yeah but in the past i have done extra research about Simkl  and its basically Trakt + all the other services with a database of almost every movie/tvshow/anime and it would be perfect to add to Tmdb Helper and maybe seren too and hey, they give you more genres then tmdb and trakt. 
![image](https://user-images.githubusercontent.com/62456796/176786588-15721852-74ce-47b3-8e98-a5cd6cbca05f.png)
It's crazy and amazing lol

**Comment by Goldenfreddy0703** [comment]
Hey @jurialmunkey sorry to bother you on this feature request but should i go ahead and close this and support #718 or change the title of this feature request? I'm not sure if your thinking of adding Simkl to help see our progress and im also not sure if its still worth it. If you could give me a reply that would great. 
Thank you.

**Comment by jurialmunkey** [comment]
Yeah I think close this one since there's already a simkl request

**Comment by Goldenfreddy0703** [comment]
> Yeah I think close this one since there's already a simkl request

Ok great thank you, i hope we can add simkl to tmdb helper sometime this year. 
Again, Thank you
