### ISSUE TITLE
[BUG] Empty search results

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#786]
### Describe the bug

Hi Jurial. I use in my skin property to search movies, tv shows and people. The part of code looks like this.
```
<variable name="SearchTMDBMovies">
        <value condition="!String.IsEmpty(Skin.String(CustomSearchTerm))">plugin://plugin.video.themoviedb.helper?info=search&amp;type=movie&amp;query=$INFO[Skin.String(CustomSearchTerm)]</value>
    </variable>
	
	<variable name="SearchTMDBShows">
        <value condition="!String.IsEmpty(Skin.String(CustomSearchTerm))">plugin://plugin.video.themoviedb.helper?info=search&amp;type=tv&amp;query=$INFO[Skin.String(CustomSearchTerm)]</value>       
    </variable>
	
	<variable name="SearchTMDBPeople">
        <value condition="!String.IsEmpty(Skin.String(CustomSearchTerm))">plugin://plugin.video.themoviedb.helper?info=search&amp;type=person&amp;query=$INFO[Skin.String(CustomSearchTerm)]</value>       
    </variable>
```
It happens sometimes that on Android the search result is empty with the log I sent you. Can you take a look at what this is about? Thanks.

### Steps To Reproduce

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Can you upload the log file rather than pasting it (zip it if file type won't upload). It loses formatting if you paste it so it is too hard to read.

**Comment by jurialmunkey** [comment]
Also almost certainly your string is empty to start with so no results and then your container hides because numitems is 0.containers don't update while hidden.

You need to make sure your container stays visible for it to update when the string changes.

**Comment by matke-84** [comment]
[kodi(1).log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9027117/kodi.1.log)

**Comment by matke-84** [comment]
> Also almost certainly your string is empty to start with so no results and then your container hides because numitems is 0.containers don't update while hidden.
> 
> You need to make sure your container stays visible for it to update when the string changes.

Yes, you're probably right. I have to check this out.

**Comment by matke-84** [comment]
Solved.
