### ISSUE TITLE
[Feature] play with "" - missing "is_resolable" flag

### ISSUE THREAD

**Issue by The-cpu-max** [jurialmunkey/plugin.video.themoviedb.helper#787]
### Is your feature request related to a problem? Please describe.

massage every time

### Describe the solution you'd like

Set the default for the message to appear

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Missing from where? What does this mean? It is up to the person creating the player file to configure it correctly.

**Comment by The-cpu-max** [comment]
> Missing from where? What does this mean? It is up to the person creating the player file to configure it correctly.

I mean I want this message to stop appearing

**Comment by jurialmunkey** [comment]
Then configure the player to have the is resolvable flag according to what the end plugin requires.
