### ISSUE TITLE
[BUG ?] Next Aired Trakt not working

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#788]
### Describe the bug

I have noticed in the past 4 days that Trakt tv shows are blank. I have reinstalled Trakt a few times on my Mac & Nvidia shield. Next Aired Library working without issues. Using the latest AH2 updates. 

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9032776/kodi.log)

[kodi.old.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9032777/kodi.old.log)

Thanks

### Steps To Reproduce

Clicking on the Next Aired Trakt icon(home screen)

### Debug log

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9032779/kodi.log)

[kodi.old.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9032780/kodi.old.log)

https://user-images.githubusercontent.com/2873112/176995994-c573be26-25f7-417f-902a-9acec148d28b.mov

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
`HTTP Error Code: 401` means that you haven't authorised TMDbHelper to access your Trakt account.

Goto `TMDbHelper Settings > Accounts > Authenticate Trakt account...`
Then copy the code it provides into https://trakt.tv/activate on a web browser.

**Comment by Blurayx** [comment]
Sorry I didn't realise I needed to authorise TMDbHelper. I signed out because I was having issues where my library tv show episodes were disappearing I will enable it again to see if I still have the issue.

Thanks
