### ISSUE TITLE
[Feature] Description  English Trailer if not available in the choose language

### ISSUE THREAD

**Issue by shahaf1122** [jurialmunkey/plugin.video.themoviedb.helper#789]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

Sometimes in the changed metadata language, there is no trailer but instead there is a trailer in English matadata
Is it possible that as soon as a trailer is not available in changed metadata language then there will be a trailer in English?

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
> Is your feature request related to a problem? Please describe.

Please answer the questions properly when making a request. It is important to describe the problem and how to reproduce it.

The proposed solution is not good as doing two lookups per item would be slow as you would effectively double the loading time.

**Comment by jurialmunkey** [comment]
However, there might be a way to get *both* the main language and english together -- but it might not be possible to filter which one comes first. What's more important? Getting any trailer? Or getting a trailer in your language?

**Comment by shahaf1122** [comment]
First of all to your question, it is better to have a trailer then not to have at all.
And is there possibility that once there is no trailer available in my language then a trailer button will still appear and then it will perform the search to trailer in English?

**Comment by jurialmunkey** [comment]
> And is there possibility that once there is no trailer available in my language then a trailer button will still appear and then it will perform the search to trailer in English?

No. I already explained why that's a bad idea.

**Comment by jurialmunkey** [comment]
You need to provide me with steps to reproduce the problem so that I can test, otherwise it is impossible for me to make sure any code I add is working
