### ISSUE TITLE
Your Recently Watched TV Shows issue

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#790]
Hi. Wanted to check if the following behaviour I've noticed over the last few weeks is a TMDb helper issue or not. Can only currently test with AH2 skin.

Thanks to TMDB helper's Next Episodes checks calendar option, an early morning 'Reload Skin' cron task populates Your Next Episodes widget with new episodes.

By the evening, TMDB helper's Your Recently Watched TV Shows is not displaying any unwatched episode badges for that same show. Marking something else as watched in Trakt will fix this, so maybe TMDb helper's 24 hourly Trakt sync hasn't happened and would likely be rectified by the next day? Not a problem.

However, I'm questioning this behaviour because when I go into TMDb helper's Your Recently Watched TV Shows (which at this point is displaying an unwatched episode badge), Up Next still points me to 1x01, not the latest episode it's telling me is available. Just wondered if this could be a bug and whether this is affecting time taken for unwatched episode badges to be displayed?

Edit: Not sure why I didn't also test this on my windows machine, which doesn't seem to have this problem that my osmc device does. Tried deleting everything in .kodi\userdata\addon_data\plugin.video.themoviedb.helper except for setting.xml and players, and seems to be working now.

**Comment by jurialmunkey** [comment]
Hard to say exactly without a log but I think I know the issue.

The reason the calendar check was added was because up next and watched data sync on the server are pegged to the watch activity on Trakt. That data only updates after watching something.

The calendar check essentially double checks the recently watched list against the recently aired calendar in case there were new episodes since the last watch data update. The side effect is that those new episodes won't be in that sync data so won't "count" in terms of episode watched/unwatched counts or up next.

There's no real solution. Using the calendar to check for new episodes is already a hack. To then combine it with sync data will be really messy and likely quite slow.

**Comment by ghost** [comment]
I closed this in the hope you wouldn't waste your time replying, so do appreciate the response! I didn't realise Your Recently Watched/ Up Next only sync after watching something. Though they'd update at some point automatically...that's good to know. 

I may have assumed this as Seren addon seems to do this automatically without me having watched anything - not sure how it accomplishes that. Anyway, clearing addon settings solved my main issue (unwatched episode badge displaying but episode not in up next) so must have been a corrupt file somewhere. Thanks man.

**Comment by jurialmunkey** [comment]
> Though they'd update at some point automatically...that's good to know.

It does eventually update just not always immediately. Sometimes it might be an hour or so, and other times it can be several days. Generally watching an episode forces it to update. Watching anything updates the sync/watched obviously, and then the individual up next for shows I'm not certain about what actually triggers the cache to refresh but it appears to generally update after watching something.

> I may have assumed this as Seren addon seems to do this automatically without me having watched anything - not sure how it accomplishes that. 

Probably is merging the calendar data with its local database and then basically rebuilding the progress data itself locally.  Nix is actually the person who reported the original issue with the individual up next sync on Trakt github.
