### ISSUE TITLE
[BUG] mdblist

### ISSUE THREAD

**Issue by BrownQ8** [jurialmunkey/plugin.video.themoviedb.helper#791]
### Describe the bug

cant use my mdblist even with my correct api !

### Steps To Reproduce

mdblist 2 yourlist

### Debug log

https://paste.kodi.tv/ibuvokoxin.kodi

### Screenshots and Additional Info

![1737DFAA-DFA2-42DC-96F0-E8146A88212B](https://user-images.githubusercontent.com/108634384/177553605-108d6078-7bd9-4b78-9ae7-d5a3b20bd3ee.jpeg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Full log please.

**Comment by BrownQ8** [comment]
that’s the full log but i click twice .. so it came same thing

**Comment by BrownQ8** [comment]
i have verison 4.10.0 in my tablet it working perfect!

**Comment by jurialmunkey** [comment]
> that’s the full log but i click twice .. so it came same thing

That's not a full log.

It doesn't even have system information.

https://kodi.wiki/view/Log_file

**Comment by jurialmunkey** [comment]
You'd only get this error if you have the wrong api key. I guarantee your api key is wrong.

**Comment by BrownQ8** [comment]
sorry :/ im still noob .. but u know i found the problem.. i delete the file on addon database and now its working!

**Comment by BrownQ8** [comment]
userdata/addon data/ plugin/ database v5 /mdblist .. i delete this file and my list showing

**Comment by BrownQ8** [comment]
also one last request if u dont mind .. if i make new list doesn’t showing first i have to delete same file then new list on !
