### ISSUE TITLE
[QUESTION] Custom cast list separators using includes and conditions

### ISSUE THREAD

**Issue by inb4after** [jurialmunkey/plugin.video.themoviedb.helper#793]
For the cast list service monitor property `Window(Home).Property(TMDBHelper.ListItem.Cast)` the separator is only available as `/`. In the past, TMDbHelper used `,` separators which looked better in some layouts.

Skins can use the workaround of includes and conditions using `Window(Home).Property(TMDBHelper.ListItem.Cast.X.Name)` where X is between `1-10`. I think 10 is the limit for the main property also.

My question is that if an item has a value for `ListItem.Cast`, can we assume that all the properties  for `ListItem.Cast.X.Name` are filled and not empty?

**Comment by jojobrogess** [comment]
I feel like I should mention, although I assume you both already know, it looks like in Kodi Nexus `ListItem.setCast()` is depreciated. 

I am running Kodi 20.0-Alpha1(compiled 06-27-2022) btw. 

Random [log](https://paste.kodi.tv/oyigefohuc.kodi) with this in it:
>ListItem.setUniqueIDs() is deprecated. Please use InfoTagVideo.setUniqueIDs().
ListItem.setCast() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setCast().
ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use  InfoTagVideo.

**Comment by jurialmunkey** [comment]
@jojobrogess - TMDbH is currently developed for Matrix only. It will still work in Nexus but I won't start on a Nexus only version until beta/rc stage


@inb4after - as long as there are 10+ cast then all props are filled. If there's fewer then the extra props are cleared.

You can deal with empties in your label by using positional affixes in the infolabel eg
`$info[window(home).property(tmdbhelper.listitem.cast.2.name),$COMMA ,]`

If a label is empty, its affixes aren't added either so you can line these all up in one label control to have comma separated without needing string.isempty() checks (just check for first position name so you aren't rendering a completely empty control)

**Comment by inb4after** [comment]
@jurialmunkey 

Thank you for the advice, I keep forgetting about that trick and remember you mentioned it a while ago.

My final question is unrelated, but if I have a two lines of space available for cast member names in a non-scrolling textbox control, is there a way to automatically remove further cast member names if they would overflow the width/height?

For example if we take Godzilla vs. Kong: `Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall, Brian Tyree Henry, Shun Oguri, Eiza González, Julian Dennison, Lance Reddick, Kyle Chandler, Demián Bichir`

How it looks in the skin:

`Starring Alexander Skarsgård, Millie Bobby Brown,`

`Rebecca Hall, Brian Tyree Henry, Shun Oguri, Eiza`

I'm trying to make it look more like:

`Starring Alexander Skarsgård, Millie Bobby Brown,`

`Rebecca Hall, Brian Tyree Henry, Shun Oguri`

Also, other items sometimes have even longer names in the cast list, which makes overflowing almost impossible to avoid.

**Comment by jurialmunkey** [comment]
Nope not possible unfortunately (at least I can't think of a way)

There's no way to control what the breaking characters in a textbox are, and that's really what you'd need to do (i.e. break on comma rather than space).
