### ISSUE TITLE
[BUG] Missing viewing percentage indicator

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#798]
### Describe the bug

Hi Jurial. I found one bug. When I'm watching an episode of some tv show and stop at some point, I don't get an indication of the percentage where I stop. I go to tmdb helper folder "your in progress episodes", the episode is there but also without the percentage indicator. I go to the settings of tmdb helper, delete the trakt cache, reset kodi and the indicator appears. This only happens with episodes, movies work fine.

### Steps To Reproduce

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Tmdbh doesn't manage scrobbling to trakt. You can only retrieve already scrobbled values (assuming you set the setting to retrieve progress).

This is why I'm always banging on about plugins using hacks. If the end plugin used setresolvedurl properly, then the local resume point would automatically be passed back to tmdbh without any need for trakt. Additionally, plugins which use setresolvedurl correctly will work with Kodi's trakt addon and be scrobbled by it. I know because I use a lot of slyguy plugins which all use setresolvedurl and i never have an issue with the trakt addon managing scrobbling of those - it's only ever the 3rd party addons using player hacks which it doesn't work properly with

**Comment by jurialmunkey** [comment]
In addition to the above, the other problem is that some of the trakt syncs are tied to watched status so will only update after watching something (ie status changes). The playback one should update on playback change but possibly just missing the changeover (eg plugin listing refreshing before server updated)

**Comment by jurialmunkey** [comment]
@matke-84 Could you try the version from the above PR #799 and let me know if that helps?
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/refs/heads/fix_playprogress_episodes.zip

**Comment by matke-84** [comment]
Something is not right with this version and I mean with the regular last version 4.10.13. I get lots of errors, can't open any episodes (blank page)... And this all happens when I turn on get resume points from trakt
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9118321/kodi.log)
.

**Comment by matke-84** [comment]
Sorry wrong log file
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9118342/kodi.log)

**Comment by jurialmunkey** [comment]
Can you try v4.10.14 -- fixes that bug with pickle not being imported and also adds the fix for playprogress update on paused_at not watched_at.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.10.14

**Comment by matke-84** [comment]
Everything works now. Thanks.

**Comment by xyzfre** [comment]
> Can you try v4.10.14 -- fixes that bug with pickle not being imported and also adds the fix for playprogress update on paused_at not watched_at.
> 
> https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.10.14
> 
> 

This latest version is working very well specially the fix for play progress (percentage icons) ,I had notice the same issue yesterday but I thought maybe it was a Trakt issue on their end ,,Thanks @jurialmunkey AMAZING work
