### ISSUE TITLE
[Bug] get_traktslug returns wrong results (Again!)

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/plugin.video.themoviedb.helper#80]
@drinfernoo @SerpentDrago - Can you test my latest commit. I found some other false positives with trakt slug (related to this PR https://github.com/jurialmunkey/plugin.video.themoviedb.helper/pull/78) 

Despite that PR, the most recent episode of "8 out of 10 cats does countdown" was getting the Trakt slug for Sopranos because the Countdown show tmdb_id matched a Sopranos episode tmdb_id. Since both are shows, the shows key was in both and thus slips by the check in that PR.

I realised that the search type syntax is incorrect (or maybe it has recently changed in trakt api). This commit https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/0d55311da90d9654eb472c15c9b5b1cb4d5654fb should fix the syntax, which means we should only get one result now if searching by ID. Regardless, I've added some double checking to make absolutely sure we are getting the correct slug.

Please test with the shows/episodes that you were getting false positives previously (ATHF and Eric Andre I think it was?) and confirm that everything is working correctly for you guys.

**Comment by drinfernoo** [comment]
I can't test right away, but the code looks sound. I'll take a look this evening.

**Comment by drinfernoo** [comment]
Actually I had a few minutes, seems to be working fine for ATHF at least.

**Comment by jurialmunkey** [comment]
Thanks! Yeah im pretty confident it should be working properly now - just wanted some confirmation.

After your PR I started paying closer attention with some additional logging and spotted that one. Thanks for bringing it to my attention as I probably would have never noticed myself as the plugin's I use for players don't take trakt slugs
