### ISSUE TITLE
[Feature] Add trakt resume point to Player Function

### ISSUE THREAD

**Issue by shahaf1122** [jurialmunkey/plugin.video.themoviedb.helper#804]
### Describe the feature that you'd like

I am using the get trakt resume function...
and if it possible that in the Player Function, will be a Key that output the resume point that get from trakt.

### Why is this feature needed? What problem does it solve?

I am using a Plugin that after select that it search
and it is not a setResolvedUrl() method for playback so the resume don't do nothing.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Ask the author of the plugin you are using to fix their plugin to use the proper setresolvedurl method of starting playback.

Most of these plugins have no reason not to use setresolvedurl, so they should fix their plugins to do things correctly.

**Comment by shahaf1122** [comment]
This plugin is no longer with maintenance…
There is no other way? To get the resume time? 
Like a commend? Database?

**Comment by jurialmunkey** [comment]
This type of workaround is not a good idea. It is like fixing a leaky roof by putting a bathtub in the attic.

It does not solve the issue and eventually will cause problems.

**Comment by audiosistem** [comment]
Hello! Excuse my insistence, but I hope you will reach the end with the addon and everyone will thank you! The problem now is remembering where the viewing was... in 10.32 it knows, in 11.8 it doesn't. No track, no local. Settings mine are ok. Have a good day!
