### ISSUE TITLE
Trakt list as submenu widget  not oppening

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/plugin.video.themoviedb.helper#805]
### Skin section

Home Widgets

### Current Behavior

I set my Trakt lists as a submenu widget. I have an error message notification when I try to open some lists.
Sometime it works just fine, sometime not. 

First I think that the issue were when a list contained special character but it's not the case..  Lists with special characters sometimes open and sometime not. 

(My lists are in french and I set ''Text'' as view type)

I gess you'll see the issue on line 1232  and 1269 of the attached log file

[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9190033/kodi.log)

### Expected Behavior

Being able to open all my trakt list from submenu widget

### Steps To Reproduce

1. Set Trakt list as submenu widget
2. select ''Text'' as view type
3. try to open some lists from the submenu widget

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by alKODIque** [comment]
So I try to open lists directly from the addon and same lists dont open too..
Maybe it's an issue with the items on those lists then..

So now I think I had to declare this issue for TMDbH and not AH2 :(

For example, This list dont want to open in TMDbH : https://trakt.tv/users/alkodique/lists/comedies-d-horreur-invraisemblables?sort=collected,asc

**Comment by jurialmunkey** [comment]
Yeah this is a TMDbH issue. I'll transfer it over there.

**Comment by jurialmunkey** [comment]
Pretty sure I know what the issue is. I'll add a fix tomorrow.

**Comment by alKODIque** [comment]
Hi!
Just to let you know that your commit resolved the  issue .
Thank you very much 👌

**Comment by jurialmunkey** [comment]
> Hi! Just to let you know that your commit resolved the issue . Thank you very much 👌

Thanks! Yeah it was just a silly error on my part so I was pretty certain about what the issue was last night. I just didn't want to write code right before I went to bed and risk creating another problem in the process!
