### ISSUE TITLE
[Question] Cast list in dialog video info

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#809]
Hi Jurial. One question. I implemented in my skin a tmdbh cast option in dialog video info. Everything works fine except for one thing. When I click on an actor, tmdb helper opens a context menu with the option to choose whether I want a movie, tv show... from the selected actor. When I click on one of these options, nothing happens. This works perfectly for me in the search window. Does this mean that this function cannot be called from the info dialog window?
![cast](https://user-images.githubusercontent.com/74268331/182019366-78b016f9-ca8f-424c-8709-b24be71c3ecd.png)

**Comment by jurialmunkey** [comment]
I think the videoinfo dialog prevents the new window opening. You'd need to close the videoinfo dialog first.

I'll have a look when I get the chance but I assume that's the issue. If it is I should be able to add an override to force close the dialog.

**Comment by matke-84** [comment]
I already tried that when I click on the actor, the info dialog closes first, but then the contest menu closes also. How can I make it close the info dialog when I click only on this context menu?

**Comment by jurialmunkey** [comment]
> I already tried that when I click on the actor, the info dialog closes first, but then the contest menu closes also. How can I make it close the info dialog when I click only on this context menu?

You would have to run the command manually via onclick in the list of cast members.

```xml
<onclick>Dialog.Close(12003,true)</onclick>
<onclick>RunPlugin($INFO[Container(ID).ListItem.FolderPath])</onclick>
```

Replace ID with whatever the ID is of the container.

**Comment by matke-84** [comment]
It works, but it's not an elegant solution. Try to see if there is a possibility to start the tmdb helper without closing the info dialog. let's say extendedinfo can do that, although I know this is a script and probably works differently.

**Comment by matke-84** [comment]
I just noticed, since I use the similar list from the tmdb helper in the info dialog window as well as the cast list, that when I click on a similar tv show, it opens the list of seasons without closing the info dialog. I'm just not sure these are the same things.

**Comment by jurialmunkey** [comment]
You can't have the info dialog opened and closed at the same time. When you click the related list it updates the container in myvideonav. You need to close the info dialog to see it.

There's lots of ways around it. You could use person info extended info replacement (see wiki). You could add these custom lists directly to the info dialog and set focus to them on click. You could add them to a custom dialog and open it on top of the info dialog.

But there's no way to have the window *under* the info dialog visible while the info dialog is on top of it. It's like asking why you can't change your socks when your shoes are on.

**Comment by matke-84** [comment]
OK. Just one more question. Is there a possibility to close the info dialog after I click on some option from the context menu, not before. If it can't, I'll play around with some other ways.

**Comment by jurialmunkey** [comment]
> OK. Just one more question. Is there a possibility to close the info dialog after I click on some option from the context menu, not before. If it can't, I'll play around with some other ways.

Not really. There are ways I can think to do it but they are a bit convoluted. It would make more sense to add an option to TMDbHelper to allow it to force close the info dialog on select.

The best approach would be to recreate the options in the skin via a custom dialog - then you can just open it on top of the info dialog and not need to close it -- that's what I do in AH2 with the recommendations dialog. 

These lists in the pop-up when you click a cast member are just the `stars_in_movies` `crew_in_movies` etc. related lists
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Lists-Related

**Comment by matke-84** [comment]
> It would make more sense to add an option to TMDbHelper to allow it to force close the info dialog on select.

This would be great, of course, if it does not lead to some other unwanted effects.

In the meantime, I found a bug, it seems. When I right-click on the actor or hold the ok button to bring up the context menu, the first context menu comes out like for a movie, with all the options (play, mark as watched...). Also, if I use the Kodi option, instead of playing the movie, to I get it show information, it also opens an info dialog as if it were a movie. I don't think this is necessary, is it?
![unnamed1](https://user-images.githubusercontent.com/74268331/182033795-3f4ee57a-33c7-4138-afbf-38887537761d.png)

**Comment by jurialmunkey** [comment]
Nothing can be done about the context menu. The python plugin api doesn't allow setting the actor db type so these are technically "videos". It also needs to be video to allow opening the person in info dialog. Side effect is that kodi attaches the context menu items. It isn't possible for a plugin to change the default context items.
