### ISSUE TITLE
wrong tvdb id being returned for a show

### ISSUE THREAD

**Issue by henryjfry** [jurialmunkey/plugin.video.themoviedb.helper#81]
For the show "Locke & Key" i keep getting the TVDB id returned for friends rather than the correct ID for this show.

The problem is with the trakt TVDB id lookup which happens in "Player.py", ive worked around the problem by making the following small modification

```
        if self.traktapi:
            slug_type = utils.type_convert(self.tmdbtype, 'trakt')
            trakt_details = self.traktapi.get_details(slug_type, self.traktapi.get_traktslug(slug_type, 'tmdb', self.tmdb_id))
            self.item['trakt'] = trakt_details.get('ids', {}).get('trakt')
            self.item['imdb'] = trakt_details.get('ids', {}).get('imdb')
            self.item['tvdb'] = trakt_details.get('ids', {}).get('tvdb')
#            tvdb_id = self.tmdb.get_item_externalid(self.tmdbtype, self.tmdb_id, 'tvdb_id')
	    self.item['tvdb'] = self.tmdb.get_item_externalid(self.tmdbtype, self.tmdb_id, 'tvdb_id')
            self.item['slug'] = trakt_details.get('ids', {}).get('slug')
```

So using "self.tmdb.get_item_externalid" to get the TVDB rather than using the incorrect Trakt one.  Possibly you could add this as a fallback method if the title of the item from the trakt results does not match what you are actually looking up?

**Comment by jurialmunkey** [comment]
Have you tested with the most recent version 2.2.55?

This commit should fix the issue with the wrong trakt slug being retrieved: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/0d55311da90d9654eb472c15c9b5b1cb4d5654fb

**Comment by henryjfry** [comment]
Yeah i updated and the problem was resolved, thats what i get for not keeping everything up to date. Cheers.

**Comment by jurialmunkey** [comment]
No worries!
