### ISSUE TITLE
[Feature] Trakt Your Next Episodes - showing infos 

### ISSUE THREAD

**Issue by JacopoV** [jurialmunkey/plugin.video.themoviedb.helper#810]
### Describe the feature that you'd like

Hi! 

I'm writing in here because i suspect is leaning more towards TMDHelper than AH2 skin (which i m using).

Currently, in the skin, for TV Show content related, at the bottom left is shown " x seasons y episodes z watched " .  
For example in the view for "In-Progress" you can get " 2 seasons 10 episodes 6 watched " . 

I noticed tho, in the Trakt list for "Your Next Episodes" that these informations are not shown. 
Considering your work is super solid, i suspect there is an explanation why these informations are not shown. 

Is it then ,even possible to retrieve and mix the data ? 

Many thanks

### Why is this feature needed? What problem does it solve?

More about consistency and also, by having a widget in the home for my next episodes, i don't know how many episodes are left. 

### Steps to reproduce.

For the comparison : 
1. open TMBHelper addon
2. navigate to Trakt
3. open "your in-progress TV shows"
4. notice at the bottom left of the skin ( in this case very tied up with AH2) the info data for the show
5. go back and open "Your next episodes"
6. notice at the bottom left of the skin the info data is now shown

### Screenshots and Additional Info

"your in-progress TV shows" with data : 

![PXL_20220801_092142332](https://user-images.githubusercontent.com/1202954/182117357-fbe5f266-a272-4f7f-a0a6-b10912e677b3.jpg)

"Your next episodes" without data :
![PXL_20220801_092200257](https://user-images.githubusercontent.com/1202954/182117385-75dd0128-abfd-4dba-8578-c44bdcf9db3d.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
That info only displays for tvshow dbtype, not episode dbtype. In-Progress Shows are tvshow dbtype so it displays whereas Your Next Episodes has episodes so it doesn't (the skin displays codecs/providers instead because the item is playable)

**Comment by JacopoV** [comment]
Thanks for the explanation =) I closing =)
