### ISSUE TITLE
Option to add content by aired date

### ISSUE THREAD

**Issue by brealer** [jurialmunkey/plugin.video.themoviedb.helper#811]
### Describe the feature that you'd like

It would be good to have the option to add content to the library by aired date.

### Why is this feature needed? What problem does it solve?

When adding old tv shows to the library the episodes show up in the recently added episodes list. It would be good to have the option for them to be added by the date the episode aired

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Tmdbhelper doesn't add anything to your library. It only makes strm files on disk which *you* can then scan to your library by adding the location as a library source. Kodi then adds the items to your library via your library scraper. Tmdbhelper has nothing to do with that end of the process.

You would need to request for this feature to be added in kodi. It doesn't really have much to do with Tmdbhelper.
