### ISSUE TITLE
[Feature] add option to sort providers/networks lists by release date

### ISSUE THREAD

**Issue by Mahava** [jurialmunkey/plugin.video.themoviedb.helper#812]
### Describe the feature that you'd like

lists:
tv shows providers
movies providers
all tv networks

i think currently theyre sorted by popularity?  id like option to sort by series release date so that newest released shows appear at top of list please and thanks.

### Why is this feature needed? What problem does it solve?

tried using discover but nothing comes up.  need to know latest or anticipated release for particular network.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
What did you try in discover? This works fine for me
Add rule > with watch provider > region > provider
Add sort > release_date.desc (movie) or first_air_date.desc (tv)
