### ISSUE TITLE
[Feature] Caching details

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#816]
### Describe the feature that you'd like

OK. After I inserted the service monitor into the skin, I noticed that tmdb helper does not save some things in the cache, but loads them again. For example, when the skin helper service once reads the director, writer... it stores them in the cache while the tmdb helper loads them every time. Is there a chance to cache this data?

### Why is this feature needed? What problem does it solve?

It would speed up data loading and visually it would look better.

### Checklist

- [x] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Everything is cached already. What makes you think that it isn't?

**Comment by jurialmunkey** [comment]
Don't confuse the fact that TMDbHelper clears the property first before retrieving the next item as it not being cached. 

By contrast, SkinHelper doesn't clear the property and just overwrites it. This makes the changeover less obvious but it also means that frequently SkinHelper is displaying the *incorrect* information because it is showing data for the previous item.

In all my tests, I would say overall TMDbHelper is generally faster than SkinHelper -- it's just that clearing the property first makes the changeover more obvious.

**Comment by jurialmunkey** [comment]
For instance, see the below video where I'm comparing SkinHelper and TMDbHelper side-by-side. The director properties are listed top left.

You can see that TMDbHelper is clearing the director property first before setting the next one but it is actually beating SkinHelper quite significantly in some cases (and in others they are about equal). The changeover is just much more obvious for TMDbHelper because it clears the property first

https://user-images.githubusercontent.com/4618719/184539823-49ca1cb9-bc4f-48d4-ac0d-14843eed9719.mp4

**Comment by matke-84** [comment]
Yes, I'm confused because when I enter, for example, in video dialog info awards from shs is already there, and for example creatos from tmdb appears again and again. Watch the video. Am I doing something wrong?

https://user-images.githubusercontent.com/74268331/184541844-e569b030-6f95-4613-bfa1-d8399f98eada.mp4

**Comment by jurialmunkey** [comment]
Looks like you are using widget containers. Did you set the widget container ID to the property?

`SetProperty(TMDbHelper.WidgetContainer,WIDGET_ID,Home)`

If you don't set the widget container ID then TMDbHelper will only do the lookup after you open the info dialog on a widget. You need to set an ID to TMDbHelper.WidgetContainer to tell TMDbHelper that you want it to do look-ups for a widget.

You can use an `<onfocus>` in the widget list container to set the ID for the widget when it gains focus.

**Comment by matke-84** [comment]
I completely forgot about it. Thanks.
I don't see on the wiki page how imdb top250 property is going.

**Comment by matke-84** [comment]
OK. I hit. top250. :-)

**Comment by jurialmunkey** [comment]
> I completely forgot about it. Thanks. I don't see on the wiki page how imdb top250 property is going.

Ah I need to add that to the detailed item page. Also need to add the ones for emmys and goldenglobes.

**Comment by matke-84** [comment]
I also see there is no tvdb ratings. I know it's not free anymore, but it's a good option for older tv shows. Well, maybe there is a suggestion to add that too.

**Comment by jurialmunkey** [comment]
> I also see there is no tvdb ratings. I know it's not free anymore, but it's a good option for older tv shows. Well, maybe there is a suggestion to add that too.

There's currently ongoing discussions with TVDb about how legitimate Kodi add-ons which rely on the old API (such as Skin Helper) might continue to retain free API access once the old API is switched off. I'm waiting to see what the outcome of those discussions are before I go to the trouble of adding TVDb support.

I will only ever add support for services which have a free option. I don't mind that they offer a subscription option; my complaint about it is that it would be required to use their API. Not going to waste my free time so that a company can profit without getting something in return.

**Comment by matke-84** [comment]
I totally agree with you.
I want to try tmdb helper extendedinfo but I need help. I didn't quite understand what was written on the wiki. Now I call extendedinfo via a button from the video info dialog. I understood that I need a custom window 1190 with those predefined things. How to create a custom window that will open all info like now when I open extended info? I saw in AH2 that it opens the extended info on slide down and then new window for actors, youtube... and for movies and tv shows it returns to the video info dialog.

**Comment by matke-84** [comment]
In order not to open a new issue, is this a bug in tmdb helper? When I focus on next button of any addon, these two things appear. While I was using skin helper property for year and additional info (genre, awards...) there was none of this. I can hide them in the skin but I want to check with you first.
![screen1](https://user-images.githubusercontent.com/74268331/184669756-ce7be588-6729-42dc-a661-3b6902523d01.png)

**Comment by jurialmunkey** [comment]
> I totally agree with you. I want to try tmdb helper extendedinfo but I need help. I didn't quite understand what was written on the wiki. Now I call extendedinfo via a button from the video info dialog. I understood that I need a custom window 1190 with those predefined things. How to create a custom window that will open all info like now when I open extended info? I saw in AH2 that it opens the extended info on slide down and then new window for actors, youtube... and for movies and tv shows it returns to the video info dialog.

Don't worry about the separate dialog in AH2. Just add your widgets to DialogVideoInfo like you would any TMDbHelper list. That's the point -- it is all the native info dialog. There is no separate scripted window.

You can open any item from any widget in a new info dialog by adding this onclick command to the widget container:
`<onclick>RunScript(plugin.video.themoviedb.helper,add_path=$INFO[ListItem.FolderPath],call_auto=1190)</onclick>`

Window 1190 is just a shell for a hidden list id=9999 which TMDbH will load that single item into from the onclick command. Once that item loads in that list, TMDbH simulates pressing Action(Info) on the item to open the videoinfo dialog.

- The `add_path=$INFO[ListItem.FolderPath]` tells TMDbH that you want to load the path from the item you are clicking on.
- The `call_auto=1190` tells TMDbH that the hidden list is in window 1190 and that you want TMDbHelper to automate the process of opening/closing the info dialog and adding/removing items from the list.

For widgets that aren't from TMDbHelper, you can use `add_query=` instead to do a lookup just like you can with a plugin:// path. You can also use add_query to do manual lookups -- for instance:
`<onclick>RunScript(plugin.video.themoviedb.helper,add_query=Harrison Ford,type=person,call_auto=1190)</onclick>`
`<onclick>RunScript(plugin.video.themoviedb.helper,add_query=Aliens,type=movie,call_auto=1190)</onclick>`

That's all there is to it. It's hard to explain but once you understand how it works, you will see it is actually incredibly simple and allows for a lot of flexibility.

**Comment by matke-84** [comment]
I wanted to do something different, but I have some problems.
I made a custom list, when the focus is on the item, the content appears on the right and it works fine.
![dialog info](https://user-images.githubusercontent.com/74268331/185113902-27362ec0-384e-4adc-a3b4-5ff3c8baed14.png)
However, if I want to open the context menu, everything disappears and throws this tmdb helper error.
```
2022-08-17 13:56:50.540 T:8668    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: get_items() missing 1 required positional argument: 'tmdb_type'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\plugin.py", line 7, in <module>
                                                       Router(int(sys.argv[1]), sys.argv[2][1:]).run()
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\items\router.py", line 46, in run
                                                       self.get_directory()
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\items\router.py", line 39, in get_directory
                                                       container.get_directory()
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\items\container.py", line 239, in get_directory
                                                       items = self.get_items(**self.params)
                                                   TypeError: get_items() missing 1 required positional argument: 'tmdb_type'
                                                   -->End of Python script error report<--
                                                   
2022-08-17 13:56:50.726 T:8668     INFO <general>: Python interpreter stopped
```
Do you have any ideas or advice on how to do this and keep it like this but it doesn't give me an error? Since the titan bingie mod skin is based on the netflix look, I'm trying to make it look as much netflix as possible.

**Comment by jurialmunkey** [comment]
Do you have variables nested inside other variables? Because there's a Kodi bug in Matrix where the nested variables don't resolve if a dialog opens. So if you use a variable for the type inside another variable for the path then when you open the context menu the type variable will be blank.

The only solution is to either use Nexus or avoid nested variables.

**Comment by matke-84** [comment]
Yes, I use it, so that's the problem. Total nonsense. I'll see if I can solve it somehow. How did you solve it?
A couple of quick questions and observations.
-Ignore next page items solved the problem only with tmdb helper and not with other addons.
-Is there a possibility that I can somehow get the creators of tv shows in the list as I have for the director and writer.
-Is there a possibility to remove numbers (number of played episodes in the tv show) that are next to names of the actors and crew in list.

**Comment by jurialmunkey** [comment]
Hard to explain but basically I set the paths and variables I want to use to window properties on load of the dialog so I have a fixed value. The other way is to flatten the variable so you only have one level but that's more of a pain I think.

Can't do much about next page items in other addons. There's no specific dbtype or common value that identifies a next page item. If all addons set item dbtype correctly it wouldn't be a problem because I could rely on item type rather than container type but alas plugins never set metadata correctly so that's not an option. My only option is to check if something uses the next page label that kodi has localised. Can't help other addons if they're using a different label.

Tmdbhelper.listitem.creator win prop gets the creators.

Not sure what you mean by numbers next to actors

**Comment by matke-84** [comment]
This.
![qqqq](https://user-images.githubusercontent.com/74268331/185154071-38f31368-2e49-43e0-9c66-3bad87d45e62.png)

And I noticed one more thing. It doesn't return the trakt rating for episodes.

**Comment by matke-84** [comment]
> Tmdbhelper.listitem.creator win prop gets the creators.

You didn't understand me. I want it list of movies and tv shows from, for example, Duffer brothers (stranger things creators), in extend info list.

**Comment by matke-84** [comment]
> Hard to explain but basically I set the paths and variables I want to use to window properties on load of the dialog so I have a fixed value. The other way is to flatten the variable so you only have one level but that's more of a pain I think.

I tried this and everything works except the first time I enter in kodi the list is empty. I exit from info dialog and enter again and everything is fine. I enter in list by clicking on the button and I set property on dialog info load. Where am I wrong?

**Comment by jurialmunkey** [comment]
> > Tmdbhelper.listitem.creator win prop gets the creators.
> 
> You didn't understand me. I want it list of movies and tv shows from, for example, Duffer brothers (stranger things creators), in extend info list.

Use the crew_in_tvshows and crew_in_movies lists

**Comment by jurialmunkey** [comment]
> > Hard to explain but basically I set the paths and variables I want to use to window properties on load of the dialog so I have a fixed value. The other way is to flatten the variable so you only have one level but that's more of a pain I think.
> 
> I tried this and everything works except the first time I enter in kodi the list is empty. I exit from info dialog and enter again and everything is fine. I enter in list by clicking on the button and I set property on dialog info load. Where am I wrong?

Need to set the property before the list loads. Set list visibility to false while the property is empty.

That's one of the reasons I use a separate dialog for these lists - let's me set the props and then open it. But visibility condition should work fine too.

**Comment by matke-84** [comment]
I can't solve this without your help. I specified property for the list on button click.
`SetProperty(AdditionalInfo,cast)`
The list is visible only by clicking on the button.
`<visible>String.IsEqual(Window.Property(AdditionalInfo),cast)</visible>`
In the dialog info, I set the property to be set on loading.
```
<onload>SetProperty(Path.Cast,"$VAR[Path_Cast]")</onload>
<onload>SetProperty(Path.Crew,"$VAR[Path_Crew]")</onload>
```
I also tried to put in a list condition. Nope. It won't work.
What am I doing wrong?

**Comment by matke-84** [comment]
> Use the crew_in_tvshows and crew_in_movies lists

I tried to get the crators for tv shows but it doesn't give any results. As info it returns the results
`$INFO[Window(Home).Property(TMDbHelper.ListItem.Creator)]`
but does not give me a list of movies and tv shows. I also tried only with one creator but nothing. Any solutions here?
`plugin://plugin.video.themoviedb.helper?info=crew_in_tvshows&amp;type=person&amp;filter_key=job&amp;filter_value=creator&amp;query=$INFO[Window(Home).Property(TMDbHelper.ListItem.creator.1.name)]&amp;exclude_key=title&amp;exclude_value=$INFO[ListItem.Title]&amp;nextpage=false&amp;fanarttv=false&amp;cacheonly=true`

**Comment by jurialmunkey** [comment]
> I can't solve this without your help. I specified property for the list on button click. [...] I also tried to put in a list condition. Nope. It won't work. What am I doing wrong?

Hard to say without seeing full code.


> I tried to get the crators for tv shows but it doesn't give any results. Does not give me a list of movies and tv shows.  I also tried only with one creator but nothing. Any solutions here?

Definitely need to use only one creator. Can only get crew_in and cast_in lists for a single person.

What tvshow are you trying this on? Possibly that creator only created the one tvshow (which your exclusion keys are excluding).

**Comment by jurialmunkey** [comment]
Definitely works for me:

`plugin://plugin.video.themoviedb.helper?info=crew_in_tvshows&amp;type=person&amp;filter_key=job&amp;filter_value=creator&amp;query=Larry David`

![Screenshot 2022-08-21 003919](https://user-images.githubusercontent.com/4618719/185751967-95426232-9073-42b0-8275-5a08b7980ead.jpg)

**Comment by matke-84** [comment]
> Hard to say without seeing full code.

I solved this. Thanks. ;-)

> Possibly that creator only created the one tvshow (which your exclusion keys are excluding).

Yes, you are right. Unbelievable that I tried on a couple of tv shows where there is actually creator have only one tv show.

> This. ![qqqq](https://user-images.githubusercontent.com/74268331/185154071-38f31368-2e49-43e0-9c66-3bad87d45e62.png)
> 
> And I noticed one more thing. It doesn't return the trakt rating for episodes.

Is there anything about this? Is it possible to make an option to turn off number of episodes next to the name of actor?
And as for the trakt raiting, it is not shown in the episode level. Can we get it in episodes too.

**Comment by jurialmunkey** [comment]
> Is there anything about this? Is it possible to make an option to turn off number of episodes next to the name of actor?

Latest version splits it appearances count into its own `ListItem.Property(episodes)` - might need to refresh the item details via context menu addon.

>  And as for the trakt raiting, it is not shown in the episode level. Can we get it in episodes too.

Probably not. The API call to get ratings from trakt only accepts trakt slugs and those aren't available from TMDb. The only way to get it would be an additional API call to lookup the slug on Trakt. Service monitor is very time pressured, so really need to limit additional calls to a complete minimum -- making two requests for a single rating just isn't worth the time cost.

**Comment by matke-84** [comment]
> Latest version splits it appearances count into its own `ListItem.Property(episodes)` - might need to refresh the item details via context menu addon.

Working. Thanks. ;-)

> Probably not. The API call to get ratings from trakt only accepts trakt slugs and those aren't available from TMDb. The only way to get it would be an additional API call to lookup the slug on Trakt. Service monitor is very time pressured, so really need to limit additional calls to a complete minimum -- making two requests for a single rating just isn't worth the time cost.

I agree. Anything that will slow down the opening is not worth it.

Did you change something in the code? I use these two lines and it no longer shows me the refresh and artwork button until I remove them.
```
!String.IsEmpty(ListItem.Property(tmdbhelper.context.refresh))
!String.IsEmpty(ListItem.Property(tmdbhelper.context.artwork))
```

**Comment by matke-84** [comment]
And I forgot one more thing. This sometimes throws when opening Kodi.And I forgot one more thing. This sometimes throws when opening Kodi.
```
2022-08-20 17:53:28.052 T:13876    INFO <general>: [plugin.video.themoviedb.helper]
                                                   lib.monitor.listitem.get_listitem
                                                   Error Type: RuntimeError
                                                   Error Contents: ('dictionary changed size during iteration',)
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\addon\logger.py", line 51, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\monitor\listitem.py", line 348, in get_listitem
                                                       self.set_properties(details)
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\monitor\common.py", line 136, in set_properties
                                                       self.set_indexed_properties(item.get('infoproperties', {}))
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\monitor\common.py", line 84, in set_indexed_properties
                                                       for k, v in dictionary.items():
```

**Comment by jurialmunkey** [comment]
> Did you change something in the code? I use these two lines and it no longer shows me the refresh and artwork button until I remove them.

Yeah I removed the context menu properties. It was always a bit of a hack to get the ContextMenu working on widgets and I've since found it has a bit of a performance impact to use that method.

ContextMenu items are now set using the proper internal addContextMenuItems. Side-effect is that they will only populate in standard media views (i.e. MyNav windows). To get the contextmenu on widgets, the user can install the [TMDbH ContextMenu Addon](https://github.com/jurialmunkey/context.themoviedb.helper) which, as of v1.1.1, will now work for all items -- I figure this also gives users a bit more flexibility if they don't want all these options by default.

If you want to check what the TMDbH item type for the listitem.folderpath (the tmdb_type= param) you can use the `item.type` property (tv is for shows/seasons/episodes; also have `collection` and `person` as options). This is a fairly effective method of determining if an item is from TMDbH and is of a type that can set artwork.
`String.IsEqual(ListItem.Property(item.type),movie) | String.IsEqual(ListItem.Property(item.type),tv)`

If you want a more generic check for TMDbH items then listitem.path will always be the same
`String.IsEqual(ListItem.Path,plugin://plugin.video.themoviedb.helper/)`

> And I forgot one more thing. This sometimes throws when opening Kodi.And I forgot one more thing. This sometimes throws when opening Kodi.

Yeah I've seen this on occasion. It is harmless and can be ignored. It's just a small race condition between the ratings thread and the main thread. I should fix it but it really only happens on startup when there is a significant performance choke point slowing it down.
