### ISSUE TITLE
[Feature] Calendar stacked episodes returned as TV Show

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#818]
### Describe the feature that you'd like

For stacked episodes in the calendar could we return the tv show and not the first episode.

At the moment if a show airs all it's episodes on the same day it returns the item for episode one in the list with all it's associated data like plot and dbtype episode.

Could it return the tv show.

Basically make the calendar list mixed content, episodes if it's a single episode or shows if it's multiple episodes.

Perhaps even make it an option weather to return stacked episodes as either an episode or a tv show?

Thanks

### Why is this feature needed? What problem does it solve?

The main reason I'd like this is that in the calendar if the item is stacked episodes then I'd like access the the tv shows plot and not the plot of the first episode.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
@roidy - Was this fixed? I can't remember if I fixed it or not...

**Comment by roidy** [comment]
It was never really broken, it was more of a feature request. 

However since you added the `library_airingnext` and `trakt_airingnext` lists I find myself not even using the calendar anymore.
