### ISSUE TITLE
[BUG] TMDB Helper error when trying to load Trakt Movies Watchlist in widget

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/plugin.video.themoviedb.helper#820]
### Skin section

Home Widgets

### Current Behavior

With one of the recent updates in the past day or two, my widget to display my Trakt Movies Watchlist from TMDBH no longer populates on the home screen.  I get a TMDBH error.  I will post the log section below.

I am able to navigate to my Movies Watchlist within the TMDBH addon just fine.  It just won't populate the home screen widget.

### Expected Behavior

Home screen widget should populate from Trakt Movies Watchlist within TMDBH.

### Steps To Reproduce

Create a widget pointing to Trakt Movies Watchlist within TMDBH.
The widget doesn't get populated/displayed, and an error is logged.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Can you upload the log as a file please. Really difficult to read as text dumped into a comment. Also full log, no snippets.

**Comment by eengert** [comment]
Sorry about that.  Here's a link to the full log file:  [https://paste.kodi.tv/otayebusox](https://paste.kodi.tv/otayebusox)

**Comment by jurialmunkey** [comment]
Excellent thanks. Much easier to read. TMDbHelper issue so I'll transfer this issue over to that repo.
Pretty sure I know what the issue is. Will fix later today when I'm back at home.

**Comment by jurialmunkey** [comment]
@eengert - Please try v4.10.28 of TMDbH. That should fix the issue if it is what I think it is. Pretty sure there's an item in your watchlist without a release date but Trakt is still setting the year field but putting in a null value. 

Can't compare NoneType to an Integer, so now I'm forcing it to be 0 instead. Not exactly ideal for sorting but there's no real way to determine if the item is just missing data (so possibly in the past) OR simply doesn't have a release date yet (so will be in the future) -- this will just bump all items without years to the back.

**Comment by eengert** [comment]
That fixed it.  Thanks so much!
