### ISSUE TITLE
The movie db helper. 

### ISSUE THREAD

**Issue by Greg0580** [jurialmunkey/plugin.video.themoviedb.helper#821]
Yes I have Api key/both MDblist API Key and OMDb API Key both have Been Activated.
Thank. You.
![20220819_134737](https://user-images.githubusercontent.com/70832868/185532737-5925d9d2-44ff-48b2-8684-7cfb0249b224.jpg)

**Comment by jurialmunkey** [comment]
If you are reporting a bug, please use the bug report template and follow it properly.

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBUG%5D+Description
