### ISSUE TITLE
[BUG] TV shows library_nextaired returns random data if days=14

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#823]
### Describe the bug

`plugin://plugin.video.themoviedb.helper/?startdate=0&amp;days=14&amp;info=library_nextaired&amp;widget=true&amp;reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]`

Returns random shows and episodes. Setting days to any other value works fine.

### Steps To Reproduce

1. From skinshortcuts add a TV Shows->Next Aired LIbrary->Next Fortnite
2. Resulting Widget is filled with random items that have never been in my library

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Probably incorrectly cached entry due to a failed kodi_db lookup. Delete Trakt cache and restart Kodi.

**Comment by roidy** [comment]
Thanks, that fixed it.
