### ISSUE TITLE
[BUG] MDbList Error "None"

### ISSUE THREAD

**Issue by 43v3rLoCo** [jurialmunkey/plugin.video.themoviedb.helper#825]
### Describe the bug

Trying to pull up mdblist lists is giving error 'none"

TMDB Helper 4.10.33

### Steps To Reproduce

Go to mdblist > choose any lists = error

### Debug log

https://paste.kodi.tv/cajucezede.kodi

### Screenshots and Additional Info

![screenshot00001](https://user-images.githubusercontent.com/13120383/185771300-05e82fb8-0c9f-4182-9b12-f5c648a5257f.png)

This log is from my pc and I thought it might have to do with the skin or maybe the pc, but I checked on my TVs with other skins and the same thing happened. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Did you add your mdblist api key?

**Comment by 43v3rLoCo** [comment]
I have and it seems to be fixed now. Must have been an issue on mdblist's side. Sorry

**Comment by jurialmunkey** [comment]
> I have and it seems to be fixed now. Must have been an issue on mdblist's side. Sorry

No worries!
