### ISSUE TITLE
[BUG] v4.10.37 causing Trakt and player error

### ISSUE THREAD

**Issue by 43v3rLoCo** [jurialmunkey/plugin.video.themoviedb.helper#827]
### Describe the bug

Updating to 4.10.37 causes errors  when trying to change player defaults and when trying to authorize Trakt. 
I tried a couple of older versions and found that .36 also causes the error, but everything is fine in 4.10.35

### Steps To Reproduce

Go to players > choose default player for movies > choose different player and ok > error pop

Go to accounts > authenticate trakt > enter code in trakt > wait for tmdb pop up to close > error pops up

### Debug log

https://paste.kodi.tv/kacacehike.kodi

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by alKODIque** [comment]
Same issue for me !
Can not set / change new player as default in TMDbH

I have this error in my log file:
` object has no attribute 'setsettingroute'`

EDIT: I can change default players manually in settings.xml with no issue

**Comment by jurialmunkey** [comment]
Please install v0.0.4 of script.module.tmdbhelper
https://github.com/jurialmunkey/script.module.tmdbhelper/releases/tag/v0.0.4

Should be in the repo soon.

**Comment by 43v3rLoCo** [comment]
That did it! Thank you!
