### ISSUE TITLE
[BUG] Episode thumbnail image stopped refreshing again for TV Shows

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/plugin.video.themoviedb.helper#829]
### Describe the bug

Hi @jurialmunkey,

Sometime back I reported this issue via ticket #794 and you sorted it at that time. However, it seems to have come back again. The issue is that the episode thumbnail image stopped refreshing for TV Shows. In your earlier fix I could refresh the thumbnail image using the context menu option "Refresh Details" but it's not working now. Could you please check and resolve it again?

### Steps To Reproduce

Go to any latest TV Show. For example, I'm using "She Hulk" for reference. The Season 1 Episode 2 image has been updated in TMDB website. However, even after you click on "Refresh Details" via the context menu for that episode the image is not getting updated. The image appears fine on other addons. See screenshot.

### Debug log

Kodi log:

https://paste.kodi.tv/sajufayoxo

### Screenshots and Additional Info

In TMDB Helper addon:

![IMG20220825210513](https://user-images.githubusercontent.com/65297828/186710040-02eb3b31-3e3d-4e85-b5f5-4538e59e0804.jpg)

In another addon:

![IMG20220825211706](https://user-images.githubusercontent.com/65297828/186710987-b4bbe166-49b7-4aac-808f-941629281ead.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Any updates about this please?

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
It's a bit difficult to test. I don't really see any reason why it would stop working.

How are you refreshing details? Via the context menu addon or the proper context menu items?

**Comment by AakashC2020** [comment]
> It's a bit difficult to test. I don't really see any reason why it would stop working.
> 
> How are you refreshing details? Via the context menu addon or the proper context menu items?

Hi @jurialmunkey,

I tried using refresh details option from both within the TMDB helper addon and also via the context menu addon from the home screen widgets. It seems to be not working at all in both the cases. Only when I delete the TMDB cache and restart Kodi, then the episode thumbnails seem to be updating. Please see the screenshots below:

![IMG20220827203446](https://user-images.githubusercontent.com/65297828/187036197-801e8818-177b-4378-9ebb-1d235c2f43af.jpg)

![IMG20220827203459](https://user-images.githubusercontent.com/65297828/187036214-aa0869f7-bb73-4f06-b1fd-2a62fea92d58.jpg)

In TMDB helper:

![IMG20220827203343](https://user-images.githubusercontent.com/65297828/187036226-a15b9ac8-02a8-41c4-b7d2-dd259620f419.jpg)

In another video addon:

![IMG20220827203747](https://user-images.githubusercontent.com/65297828/187036235-cde26c7e-ad49-468f-9896-5f6844a21dea.jpg)

Could you please check and kindly advise?

Thanks and Regards,
ShibajiCh.

**Comment by AakashC2020** [comment]
After deleting TMDB cache and restarting Kodi:

![IMG20220827205121](https://user-images.githubusercontent.com/65297828/187036633-e0e4d1d8-2e31-48e7-b053-e4dde943a44b.jpg)

**Comment by jurialmunkey** [comment]
Ok I was able to reproduce this today but I stupidly didn't backup my database before I started testing things. I'll have another look tomorrow when I've got another episode like this that is airing.

**Comment by jurialmunkey** [comment]
@ShibajiCh - Actually, I think this might be fixed now in 4.11.4. Can you test and confirm when you get a chance?

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

I installed TMDB Helper version 4.11.5 and checked with the TV Shows - "In The Dark" - Season 4 Episode 11, and "See" - Season 3 Episode 2. Both of them refreshed properly. I then tried to check "Animal Kingdom" - Season 6 Episode 13 but it didn't refresh even though the thumbnail has been updated on the TMDB website. However, I then checked on the other video addon and found out that the thumbnail for that episode has not refreshed there as well. So I guess it's not an issue. Maybe it takes time to sync between the TMDB website and API (addon). I guess you might be able to suggest better regarding this.

I didn't find any other TV Show where I could check further. I think it's fixed for now. You can close this ticket. I'll let you know if I notice this issue again mentioning this ticket number. Thanks a lot for fixing this issue!

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Okay great to hear that it is working.

Yeah I think there is a delay where we have to wait a bit for the server cache to refresh first. Probably takes a bit longer too for items in high demand (e.g. like a finale such as Animal Kingdom). I imagine it waits for a quiet spot where it is less in demand before doing a refresh -- i.e. if lots of people are asking for the same data then its a bad time to slow things down by refreshing the cache so better for the server to wait a bit rather than update immediately.

**Comment by AakashC2020** [comment]
> Okay great to hear that it is working.
> 
> Yeah I think there is a delay where we have to wait a bit for the server cache to refresh first. Probably takes a bit longer too for items in high demand (e.g. like a finale such as Animal Kingdom). I imagine it waits for a quiet spot where it is less in demand before doing a refresh -- i.e. if lots of people are asking for the same data then its a bad time to slow things down by refreshing the cache so better for the server to wait a bit rather than update immediately.

Hi @jurialmunkey,

Thanks a lot for the detailed explanation! 🙂👍🏻

Thanks and Regards,
ShibajiCh.
