### ISSUE TITLE
[Feature request] Search history

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#83]
Would it be possible for you to add a search history to tmdbhelper?

Thanks!

**Comment by jurialmunkey** [comment]
Yeah I've been thinking that this would be useful myself. I'll see what I can do.

**Comment by skyfsza** [comment]
Great.

I would suggest having a limit, maybe 10 or 20?

**Comment by jurialmunkey** [comment]
Please test latest commit.

Each search section will have it's own history.
It saves up to 10 queries for each section - let me know if it should be more.

**Comment by skyfsza** [comment]
Did a quick test, searching direct in TMDBhelper working great, search terms added to the search history.

I have taken across your search hub idea from AZ2 into AuraMod, when I do a search using the hub, the searched term does not appear in the search history inside TMDBHelper.

Example search path: plugin://plugin.video.themoviedb.helper?info=search&amp;type=tv&amp;query=$INFO[Skin.String(CustomSearchTerm)]

Can search terms from info=search also be added?

**Comment by jurialmunkey** [comment]
Try latest commit.

Adding `&history=true` to the plugin path should save the query param.

**Comment by skyfsza** [comment]
working, thanks!
