### ISSUE TITLE
[question] TVDb raiting

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#830]
Is this the right property for new tvdb rating? I'm trying with this but I'm not getting anything. I have updated the latest tmdb helper module and plugin.
`$INFO[Window(Home).Property(TMDbHelper.ListItem.TVDb_Rating)]`

**Comment by jurialmunkey** [comment]
TVDb does not have ratings anymore. They have favourites now. The new v4 api returns a "score" value but it is arbitrary and is only meant for internal sorting methods.

See here for more details: https://github.com/thetvdb/v4-api/issues/203

So until they implement passing along favourites in the v4 api there currently isn't a way to get any type of "rating" from tvdb.
