### ISSUE TITLE
[Question] MPAA rating prefix

### ISSUE THREAD

**Issue by shkope** [jurialmunkey/plugin.video.themoviedb.helper#833]
### Describe the bug

Hi !
Why sometimes I have the MPAA displayed and sometimes not?
Did I configure something wrong?

### Steps To Reproduce

.

### Screenshots and Additional Info

![Capture d’écran 2022-08-27 123151](https://user-images.githubusercontent.com/60546620/187026619-4049bccd-c06a-4e65-ba6b-c25125e2eb76.jpg)
![Capture d’écran 2022-08-27 123125](https://user-images.githubusercontent.com/60546620/187026620-5be520aa-cf7d-4502-8d79-2a9260173bf2.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Make sure you have enabled `TMDbHelper Settings > General > Get additional details and artwork from TMDb`

Otherwise you'll need to ask the skin author.

**Comment by shkope** [comment]
Thank you for your answer


Le sam. 27 août 2022 à 12:52, jurialmunkey ***@***.***> a
écrit :
