### ISSUE TITLE
[Question] Trakt anticipated sorting

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#836]
`plugin://plugin.video.themoviedb.helper/?info=trakt_anticipated&amp;tmdb_type=tv&amp;sort_by=released&amp;sort_how=asc&amp;widget=true&amp;reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]`

Quick question, Should I be able to pre sort this list into date order?

I've tried sort_by released and year, is this list even sortable?

**Comment by jurialmunkey** [comment]
No, it's pre-paginated by Trakt, so no point sorting it. Popular/Anticipated/Trending are all like this - these endpoints are essentially *all* items just with a filter and sort method pre-applied by Trakt server.

**Comment by roidy** [comment]
Ok thanks, I can safely rely on Kodi's content sorting to do the job then 👍
