### ISSUE TITLE
[Enhancement] Trakt Mgt dialog / notification

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#84]
When using Context Menu --> Add/Remove to watch list, TMDBhelper launches a confirm dialog before adding/removing to your watchlist.

When using RunPlugin(plugin://plugin.video.themoviedb.helper?info=details&amp;trakt=watchlist_add&amp;tmdb_id=$INFO[ListItem.Property(tmdb_id)]&amp;type=movie) 
There is currently no confirm dialog or notification confirming that the show/movie was added to the watchlist.

Is it possible to trigger the same Confirm dialog as context menu or have a notification that tells the user the RunPlugin ran successfully?

Thanks!

**Comment by jurialmunkey** [comment]
Is the issue that there isn't a confirm dialog or is the issue that there is no feedback that the item has been added?

I'm just wondering if both are needed?

**Comment by skyfsza** [comment]
First choice would be for the RunPlugin to function exactly the same as the Context menu does. Eg, instead of having a RunPlugin for add and a separate for remove, single add/remove with a confirm dialog.

If that's not possible just feedback confirming the item has been added or removed.

Thanks!

**Comment by jurialmunkey** [comment]
The feedback dialog is easy enough to add. Please test latest version - should now have an OK dialog once added/removed (also note that these dialogs are not actually checking if the item was added - it's just saying that the command ran and completed successfully - it's still on my to do list to check the trakt headers and actually confirm that trakt is returning feedback that it was successfully added/removed).

In what scenario do you need to use the RunPlugin approach where you can't use the context menu?

**Comment by skyfsza** [comment]
Thanks, in the latest version the feedback dialog works perfectly.

Use case is having a button in DialogVideoInfo for "Add to watchlist"

![screenshot004](https://user-images.githubusercontent.com/29917137/74144069-bc3e4880-4c04-11ea-9993-0dc9a6f99b12.png)

**Comment by jurialmunkey** [comment]
Ah ok. I'll have a look at adding another method that is add or remove in one.

**Comment by xyzfre** [comment]
> Thanks, in the latest version the feedback dialog works perfectly.
> 
> Use case is having a button in DialogVideoInfo for "Add to watchlist"
> 
> ![screenshot004](https://user-images.githubusercontent.com/29917137/74144069-bc3e4880-4c04-11ea-9993-0dc9a6f99b12.png)

This is a amazing feature to have in the video info screen looking forward to it

**Comment by jurialmunkey** [comment]
@skyfsza - Please test latest. You should now be able to do:
```
RunScript(plugin.video.themoviedb.helper,sync_trakt=watchlist,tmdb_id=$INFO[ListItem.Property(tmdb_id)],type=movie)
```
```
RunScript(plugin.video.themoviedb.helper,sync_trakt=watchlist,tmdb_id=$INFO[ListItem.Property(tmdb_id)],type=tv)
```
```
RunScript(plugin.video.themoviedb.helper,sync_trakt=watchlist,tmdb_id=$INFO[ListItem.Property(tvshow.tmdb_id)],season=$INFO[ListItem.Season],episode=$INFO[ListItem.Episode],type=episode)
```

Also can do `sync_trakt=history` and `sync_trakt=collection`

**Comment by skyfsza** [comment]
Thanks, this is brilliant!

For TV Shows Add and Remove works perfectly.
For Movies it only seems to Add and does not remove.

**Comment by jurialmunkey** [comment]
> 
> 
> Thanks, this is brilliant!
> 
> For TV Shows Add and Remove works perfectly.
> For Movies it only seems to Add and does not remove.

Remove works for me for Movies.

I think sometimes the last activities sync in Trakt sometimes doesn't update immediately. That's what the script uses to determine whether it should use the cached version of the synced list (i.e. don't hit-up trakt for it again if it hasn't changed since last use) or if it should retrieve a new version.

**Comment by skyfsza** [comment]
Thanks, will do some more testing and update if I am still having the remove issue.

**Comment by jurialmunkey** [comment]
I've just added a cache_refresh option which you can add to the command to force a refresh. Doesn't seem to be much penalty on a smallist watchlist but it might have some penalty on larger collections

RunScript(plugin.video.themoviedb.helper,sync_trakt=watchlist,tmdb_id=$INFO[ListItem.Property(tmdb_id)],type=movie,cache_refresh)

**Comment by skyfsza** [comment]
I did a bit more testing and was able to get the remove for Movies after a delay, however it seems erratic - some times I get remove some times still Add.

TV Shows I have not had any issues, no matter how quickly I try add and then remove.

When adding the refresh to the onclick, everything works as expected with Movies.

One small bug, with refresh added I get double TVDB Movie ID x label  in the dialog

![screenshot014](https://user-images.githubusercontent.com/29917137/74328028-df4c3200-4d95-11ea-951e-de55639678b8.png)

**Comment by jurialmunkey** [comment]
Yeah it's odd. I was experiencing the same behaviour with movies but it doesn't really make sense as it uses the same code to check last activities for tvshows as it does movies.

**Comment by jurialmunkey** [comment]
I did a few tests and I'm pretty sure it's an issue on the Trakt side of things and not in my plugin.

**Comment by skyfsza** [comment]
Yeah it seems likely to be a Trakt issue. 

I'm going to leave the refresh on as default, kind of like the idea of it refreshing each time anyway.

Thanks for adding this, been wanting a single add/remove feature for ages!

**Comment by jurialmunkey** [comment]
No problem. I think with watchlist it shouldn't be too bad to pull down the data everytime. History/collection is a bit of a different story since they can get big
