### ISSUE TITLE
[question] my custom category

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#840]
I'm trying to create my own categories with the discovery function, but I'm not sure if I'm doing it right. For example, I wanted to make a list of genres. So I tried with simplest function.
`plugin://plugin.video.themoviedb.helper?info=discover&amp;type=movie&amp;with_genres=horror`
But I don't get this genre, but some trending list. Can you help me a little with this function?

**Comment by jurialmunkey** [comment]
Capitalisation issue. Case matters when it comes to programming as H and h are different bytes. Need to match a genre in the dictionary to retrieve the ID. There is "Horror" not "horror":
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/c57305d7c821cd49d30702b24a94118e6d085b8d/resources/lib/addon/consts.py#L52-L56

If you are using static lists, you are better to skip the lookup altogether and use the ID directly with the `&amp;with_id=True` param instead. Only time to use lookups is when you don't know the IDs in advance.

e.g. `plugin://plugin.video.themoviedb.helper/?info=discover&amp;tmdb_type=movie&amp;with_genres=27&amp;with_id=True`

Quickest way to do this is to go to discover and put in your parameters then get the output of `$INFO[Container.FolderPath]` after opening the directory.

**Comment by matke-84** [comment]
> Quickest way to do this is to go to discover and put in your parameters then get the output of `$INFO[Container.FolderPath]` after opening the directory.

Sorry, I didn't understand this part.

**Comment by jurialmunkey** [comment]
Do you not use any skin debugging tools? At the very least you should make a custom window to act as a debug overlay to allow you to inspect the values of $INFO[]

Container.FolderPath is the plugin path that you have open in the library. If you go to TMDbHelper's discover section and input whatever values you want, then open the folder you can then get the plugin:// url for that folder with Container.FolderPath.

That's how I got the path above. I went to TMDbHelper > Discover. Choose Add Rule with_genres and chose Horror. Then I opened the folder and checked the contents of $INFO[Container.FolderPath]
`plugin://plugin.video.themoviedb.helper/?info=discover&amp;tmdb_type=movie&amp;with_genres=27&amp;with_id=True`

**Comment by matke-84** [comment]
That I understood later what I should do. I did exactly what you told me to do. I extracted from debug line with path. Thanks a lot.

**Comment by matke-84** [comment]
Sorry Jurial. Is it possible to combine movies and tv shows in discover function or in any other way. I would like to have movies and tv shows in some lists like Netflix has.

**Comment by jurialmunkey** [comment]
Unfortunately not. They're separate endpoints that have their own parameters. A lot of the parameters don't transfer across e.g. companies are not the same as networks; premiered is not the same as first aired; genre categories are different for movies and tv; and in general the tv endpoint is missing a lot of the options that the movies one has.

The best you can do is stack two `<content>` tags to have two separate lists end-to-end in the same container eg.
```
<content>plugin://moviespath</content>
<content>plugin://tvshowpath</content>
```
