### ISSUE TITLE
[BUG] New Episodes missing from Trakt Next Episodes list

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/plugin.video.themoviedb.helper#842]
### Describe the bug

On my Apple TV, Kodi 19, new episodes are not showing up in the Trakt Next Episodes list in TMDBH. This began happening about 2 weeks ago. Other Addons which integrate with Trakt correctly display the new episodes. This issue does not occur on Kodi 19 on my Mac. To be clear, this is happening only for newly released episodes. 

### Steps To Reproduce

Setup Trakt integration on Apple TV and check New Episodes list for an episode which was recently aired. It might be happening only for new episodes in series that are completely watched. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Have you enabled the setting to check against the calendar for new episodes?

**Comment by eengert** [comment]
Yes I have that setting enabled.

**Comment by eengert** [comment]
Here’s a debug log after starting Kodi and navigating to Trakt Next Episodes in TMDBH:  [https://paste.kodi.tv/ifezocolen](https://paste.kodi.tv/ifezocolen)

**Comment by jurialmunkey** [comment]
Ah you're using 4.11.1
Can you update to latest and retry? There was a small bug introduced in 4.11.0 where cache was not refreshing properly until restart (ie disk cache would refresh but not the in memory cache). That was fixed in 4.11.4 and is most likely the same issue here

**Comment by jurialmunkey** [comment]
Same goes for the other issue with the artwork.

**Comment by eengert** [comment]
After updating to v4.11.5 and clearing Trakt cache in TMDBH, this is working properly. But I don’t know why TMDBH isn’t automatically updating. I have auto updates enabled. AH2 auto updates. For some reason I have to go to the repo and manually click the Update button for TMDBH and Skin Variables.

**Comment by jurialmunkey** [comment]
> But I don’t know why TMDBH isn’t automatically updating. 

On Matrix there is a Kodi bug where addons that are also on official repo don't always automatically update from other repos even if you have setup to track properly. It's fixed in Nexus by this PR: https://github.com/xbmc/xbmc/pull/21581

If there ends up being a Kodi 19.5 release then that PR will also be backported.
