### ISSUE TITLE
[BUG] Random Kodi Crashes

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/plugin.video.themoviedb.helper#845]
### Describe the bug

Just recently when I scroll through my library movies, and click on recommended I get a total kodi crash.

### Steps To Reproduce

Select a movie,
Go to recommended. 
It then crashes.

I am using a fireCube with Auramod.

I am hoping your eyes see something mine do not 

### Debug log

Https://paste.kodi.tv/uduwivagiy

```ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: get_items() missing 1 required positional argument: 'tmdb_type'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/plugin.py", line 7, in <module>
                                                       Router(int(sys.argv[1]), sys.argv[2][1:]).run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/items/router.py", line 46, in run
                                                       self.get_directory()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/items/router.py", line 39, in get_directory
                                                       container.get_directory()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/items/container.py", line 246, in get_directory
                                                       items = self.get_items(**self.params)
                                                   TypeError: get_items() missing 1 required positional argument: 'tmdb_type'
                                                   -->End of Python script error report<--```

### Screenshots and Additional Info

_No response_

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Why do you think this crash is caused by tmdbhelper and not one of your other addons or the skin?

I see lots of references to umbrella which uses reuselanguageinvoker. The reuselanguageinvoker setting is well known to cause crashes.

I also see a few errors in your log which indicate the skin you're using is not properly configuring tmdbhelper paths.

**Comment by adamosborne83** [comment]
> Why do you think this crash is caused by tmdbhelper and not one of your other addons or the skin?
> 
> I see lots of references to umbrella which uses reuselanguageinvoker. The reuselanguageinvoker setting is well known to cause crashes.
> 
> I also see a few errors in your log which indicate the skin you're using is not properly configuring tmdbhelper paths.

Good Morning, and as always thanks for your time and reply.

I eliminated the language invoker as that is set to off, and although prior to that I was having crashes, that had sorted the issue for the past few weeks.

Also, I have used auramod skin for roughly 3 years now and I have alway had in my opinion a light set up in regards to addons, as you can see.

If you're saying it's not tmdbhelper, then I guess it will be one of those things, but it has all of a sudden started crashing 4/5 times a day, and usually when I go into 'recommended' which pulls the info from tmdb, that's is what made me think

**Comment by jurialmunkey** [comment]
Please disable the TMDbHelper plugin and see if you still get a crash. If you do then it indicates that TMDbHelper is not the problem and it is instead the skin or one of the other addons you have installed.

There's not really anything in your log to suggest TMDbHelper causing a problem. The exception error raised is due to a skin problem and will not cause a crash. The error message is just highlighting that the skin did not configure the path for TMDbHelper correctly and that the skin needs to fix that (else it gets 0 items in that container and error messages).
