### ISSUE TITLE
[Question] Additional prompt when selecting a player

### ISSUE THREAD

**Issue by KFC4Ever** [jurialmunkey/plugin.video.themoviedb.helper#846]
Hi There,

I recently upgraded to 4.11.5 after running a much older version for some time. I've noticed now that after I choose a player I seem to get an additional prompt asking 'Play with -name of player-?'. I don't recall seeing this extra prompt before upgrading. It'd just launch the player.

Is this prompt expected now in the latest versions? If it is, is there some setting or way to disable it? Since I've already selected the player I know I want I'd prefer not to have to confirm that choice right afterwards.

Thanks!

**Comment by jurialmunkey** [comment]
The default setting combines all players for a plugin into one entry, which why you get the second prompt - it's asking which one of the players for that plugin you want to use. There's a setting under players setting section to turn off combining which will restore the old way

i.e. Disable this setting:
`TMDbHelper Settings > Players > Combine all players for plugin into single entry`

**Comment by KFC4Ever** [comment]
Thank you! I just tried this and it works as before now.

**Comment by KFC4Ever** [comment]
Actually I have a follow up question. If the following are true:

1. I have "Combine all players for plugin into into single entry" set to Enabled.
2. My selected player/addon is only configured for a single action, and does not multiple actions to choose from

Would that second dialog still come up when I select that player/addon? In discussing with some other users they believe that if an addon/player is only configured for a single action, that second prompt should not appear. I'm trying to find out if that is the case.
