### ISSUE TITLE
Trakt+TMDB

### ISSUE THREAD

**Issue by audiosistem** [jurialmunkey/plugin.video.themoviedb.helper#847]
Hello, man! In v.4.10.23, there is the possibility to mark manually seen, if trakt doesn't do it. In the later ones, it doesn't work for me anymore. Can you look, when you have time? Thank you, in advance! You do an exceptional job!

**Comment by jurialmunkey** [comment]
Inside TMDbHelper there is a context menu option `Trakt Options > Mark as Watched`

For widgets on the home screen, you need the separate context menu addon. The context menu addon is available on my repo or can be manually downloaded from here: https://github.com/jurialmunkey/context.themoviedb.helper/releases

The context menu addon adds an extra entry at the bottom called "TMDbHelper Options". You can find the Trakt Options for widgets inside that menu.
`TMDbHelper Options > Trakt Options > Mark as watched`

**Comment by audiosistem** [comment]
I know what you're talking about. v 4.11.6 installed over 4.10.23, it doesn't mark manually. It came back 4.10.24,25...40...4.11...I don't uninstall, I just install, the settings made remain... Maybe you can still find out. Thanks!Beautiful evening!

**Comment by audiosistem** [comment]
Maybe English is not my strong point!
[TMDB.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9483168/TMDB.zip)

**Comment by jurialmunkey** [comment]
Works fine for me.

Screenshot of what option you are choosing please.

**Comment by jurialmunkey** [comment]
Ah I see what you mean. It is working for movies and tvshows, but not for individual episodes. I'll have a look and see if I can fix it
