### ISSUE TITLE
[BUG] Kodi Crashing

### ISSUE THREAD

**Issue by MattTheTekie** [jurialmunkey/plugin.video.themoviedb.helper#848]
### Describe the bug

Kodi Crashes after showing tmdbhelper widgets, unable to figure it out. Whats going wrong?!

### Steps To Reproduce

1. Open Kodi
2. Do nothing.

### Debug log

https://pastefg.hermietkreeft.site/?d2483eb735c6bb8d#w5ZpxyEY3SMr4AkENQHjks9mEgtDpKBXjyZf46YNJD9

### Screenshots and Additional Info

Edit: I forgot to mention I tried to debug for a few hours. I'm using the latest version of Linux lite, and never had this issue before with this setup. Please help.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
What makes you think this crash is caused by TMDbHelper and not one of your other addons?

**Comment by MattTheTekie** [comment]
> What makes you think this crash is caused by TMDbHelper and not one of your other addons?

Not 100% certian. It only happened after the system updated. It could be the theme but after changing to another theme that worked before it would stall while loading the widgets. I'm going to work it later today again. I spent a few hours yesterday debugging. Il close the issue I guess.
