### ISSUE TITLE
[Feature] Movie sets details

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#849]
### Describe the feature that you'd like

I noticed that I can't use some properties for the movie set. For example, genre is missing, and then total duration of set, directors, writers, studio... All these things exist in the skin helper service (https://github.com/kodi-community-addons/script.skin.helper.service/wiki/Listitem-Properties---Movie-sets), so I would like to see at least some of those things in the tmdb helper. Thanks in advance.

### Why is this feature needed? What problem does it solve?

/

### Steps to reproduce.

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
None of this information is available on TMDb for collections (except for genres which I'm not sure why I missed).
https://developers.themoviedb.org/3/collections/get-collection-details

Here is an example of what the collections endpoint provides. As you can see there isn't much information.
```
{
  "id": 10,
  "name": "Star Wars Collection",
  "overview": "An epic space opera theatrical film series created by George Lucas.\r The first film in the franchise was originally released on May 25, 1977, by 20th Century Fox, and became a worldwide pop culture  phenomenon, followed by two sequels, released at three-year intervals. Sixteen years after the release of the trilogy's final film, the first in a new prequel trilogy of films was released, again released at three-year intervals, with the final film released on May 19, 2005.",
  "poster_path": null,
  "backdrop_path": "/shDFE0i7josMt9IKXdYpnMFFgNV.jpg",
  "parts": [
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [
        12
      ],
      "id": 11,
      "original_language": "en",
      "original_title": "Star Wars: Episode IV - A New Hope",
      "overview": "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
      "release_date": "1977-05-23",
      "poster_path": "/AbJBXaVPrdXROwb8KmgWUPU2XJX.jpg",
      "popularity": 1.411624,
      "title": "Star Wars: Episode IV - A New Hope",
      "video": false,
      "vote_average": 7.7,
      "vote_count": 2472
    }
  ]
}
```

**Comment by matke-84** [comment]
Ohhh. Really little info about sets. Genres at least are something. :-)

**Comment by jurialmunkey** [comment]
^^^ Should be able to get genres now
`ListItem.Property(Set.Genres)`
`Window(Home).Property(TMDbHelper.ListItem.Set.Genres)`

Can also get genres of individual movies in the set
`ListItem.Property(Set.X.Genre)`
`Window(Home).Property(TMDbHelper.ListItem.Set.X.Genre)`

FYI if you need to get positional properties on listitems in a widget add `&amp;detailed=true` to the path.

As always, refresh item details if already cached.

**Comment by matke-84** [comment]
What it means "positional properties"?

**Comment by jurialmunkey** [comment]
Gets the property for a specific position in the group.
e.g. ListItem.Property(Set.2.Title) will get the title of the second movie in the set.

Anything with this format of `Foo.X.Bar` will not be available on standard listitems. However, these properties are always available in the window properties. To get them on the listitem you need to add the detailed=true param to the path.

**Comment by matke-84** [comment]
Ahh, that's what you mean. OK. Otherwise, the genres work. Thanks. ;-)
