### ISSUE TITLE
enhancement- Networks?

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#85]
First, just want to commend you on this addon so far. So fast and useful. Thank-You!!
So question, can a section/List be added for sorting by TV Networks?

**Comment by jurialmunkey** [comment]
You can get shows per TV network using the discover section. You need to get the tmdb id for the network from TMDb, as the api doesn't support looking up network ids by name. 

Other option is to use a trakt list for that tv network.

**Comment by drinfernoo** [comment]
A couple great sets of lists exist for that, as well! There's [ACLO_Networks' lists](https://trakt.tv/users/aclo_networks/lists) for TV networks, and [EnorMOZ's](https://trakt.tv/users/enormoz/lists) for streaming services 😎
