### ISSUE TITLE
TMDBHelper Crashes on fresh Kodi installation.

### ISSUE THREAD

**Issue by MattTheTekie** [jurialmunkey/plugin.video.themoviedb.helper#852]
### Describe the bug

Since the last issue, I decided to do a fresh install of Linux Lite again. I then got Kodi from the Kodi repository. Once I did that I installed the AH2 theme. The skin crashes when I add a widget with the location of `TMDBHelper -> Movies -> Popular.` It turns out that sometimes upon trying this again it would crash while building the skin shortcuts. It would then crash after opening. Please fix this add-on.

### Steps To Reproduce

1. Install Linux Lite.
2. Install Kodi from the Kodi repo.
3. Install AH2 theme.
4. Attempt to add a widget at the location of `TMDBHelper -> Movies -> Popular.`

### Debug log

Attached here --> https://litter.catbox.moe/6oh9pz.txt

### Screenshots and Additional Info

https://litter.catbox.moe/jh7cbx.mp4 < --Very bizarre bug shown breaking the skin and Kodi.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by xyzfre** [comment]
How do you install Kodi from Kodi Repo? I thought you had to install Kodi first to even have the Kodi Repo available, is it a Linux thing ,just curious

**Comment by xyzfre** [comment]
How do you install Kodi from Kodi Repo? I thought you had to install Kodi first to even have the Kodi Repo available, is it a Linux thing

**Comment by MattTheTekie** [comment]
> How do you install Kodi from Kodi Repo? I thought you had to install Kodi first to even have the Kodi Repo available, is it a Linux thing ,just curious 

https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux
"Use the command line terminal in Ubuntu, and enter the following commands. Follow the prompts as you would any other software installation.

`sudo apt install software-properties-common
sudo add-apt-repository -y ppa:team-xbmc/ppa
sudo apt install kodi`"

**Comment by MattTheTekie** [comment]
@jurialmunkey I was able to post a log and video of this bizzare issue. Do you have any ideas?

**Comment by MattTheTekie** [comment]
The video and log expire in 3 days

**Comment by jurialmunkey** [comment]
Thanks. I can't see anything in the log suggesting an issue with Tmdbhelper. I think it is far more likely that it is one of these skin engine issues on Linux where some of the features AH2 uses mysteriously cause a crash.

Could you try a simpler skin where you can still set widgets via skinshortcuts - eg Eminence. If it doesn't crash when using the widget there then that will rule out an issue with Tmdbhelper and point to it being more likely a skin issue of some kind.

**Comment by MattTheTekie** [comment]
I will try later today, i kept thinking the same but wanted to rule one thing out before the other. Thank you

**Comment by AdamNo2** [comment]
i have the same issue.
fresh default kodi installation + hts pvr addon + TheMovieDb Helper.
further, i added an OMDb API key in TheMovieDb Helper settings.
Now when i open  TheMovieDb Helper and hit any of the menu items like Movies, TV shows, People, ...
it hangs/freezes and i have to hard kill -9 kodi!
nothing in the log.

**Comment by AdamNo2** [comment]
same with arctic horizont 2 skin.
i added jurialmunkey Alpha repo, installed Program, Video and Skin addon.
i select Options>Add-ons>My add-ons>TheMovieDb Helper>Open>Movies
and it hangs!

**Comment by jurialmunkey** [comment]
@AdamNo2 please try in Estuary to confirm that it isn't a skin issue. Also log please.

**Comment by AdamNo2** [comment]
my first post was about default/Estuary skin.
anyway, i switched the current installation with AH2 back to Estuary with same result.

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9542388/kodi.log)

**Comment by jurialmunkey** [comment]
> my first post was about default/Estuary skin. anyway, i switched the current installation with AH2 back to Estuary with same result.
> 
> [kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9542388/kodi.log)

```
plugin.video.themoviedb.helper v4.4.0 installed
```

Extremely old version of TMDbHelper. Please install latest version (v4.11.18)
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases

**Comment by AdamNo2** [comment]
no crash and addon is working!
thank you very much!

but playback with UPnP doesnt work: "One or more items failed to play...."
`2022-09-11 14:56:42.811 T:53183   ERROR <general>: GetDirectory - Error getting upnp://
2022-09-11 14:56:46.038 T:53183    INFO <general>: CPythonInvoker(19, /home/ak/.kodi/addons/plugin.video.themoviedb.helper/plugin.py): script successfully run
2022-09-11 14:56:46.099 T:53183    INFO <general>: Python interpreter stopped
2022-09-11 14:56:46.115 T:51970   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.themoviedb.helper/?info=play&tmdb_type=movie&tmdb_id=238]
`
Can you help me with this too?

**Comment by AstaFatherSatan** [comment]
> > my first post was about default/Estuary skin. anyway, i switched the current installation with AH2 back to Estuary with same result.
> > [kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9542388/kodi.log)
> 
> ```
> plugin.video.themoviedb.helper v4.4.0 installed
> ```
> 
> Extremely old version of TMDbHelper. Please install latest version (v4.11.18) https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases

This hasnt helped ethier. It still crashes, i tried the 4.11.18 version on AH2

**Comment by MattTheTekie** [comment]
I'm still crashing on FTV, auramod, and the AH2 theme despite updating to `v4.11.18`. I'm not crashing on the estuary theme as I don't know how to set the TMDBHelper widgets there.

**Comment by AstaFatherSatan** [comment]
It crashes at
`2022-09-11 13:54:44.104 T:46604    INFO <general>: [plugin.video.themoviedb.helper]
                                                   Getting KodiDB movie FAILED!
2022-09-11 13:54:44.169 T:46544    INFO <general>: CPythonInvoker(15, /home/satan/.kodi/addons/plugin.video.themoviedb.helper/plugin.py): script successfully run
2022-09-11 13:54:44.180 T:46650    INFO <general>: initializing python engine.
2022-09-11 13:54:44.219 T:46544    INFO <general>: Python interpreter stopped`

I don't believe i saw that before updating the plugin.

**Comment by AdamNo2** [comment]
i installed Arctic Horizont skin and it crashes while it works with Estuary :(
i started kodi with Estuary, checked TMDbHelper and it was fine.
then i switched to Arctic Horizont 2 Skin, checked TMDbHelper and it crashed.
pls see attached log:
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9543502/kodi.log)

**Comment by jurialmunkey** [comment]
As I said before, please try a simple skin with widgets like Eminence.

Auramod and Arctic Horizon 2 are both complex and this is possibly a skin engine issue on Linux rather than anything to do with Tmdbhelper.

Eminence is a simple and very stable skin that still allows setting widgets via skinshortcuts.

**Comment by AdamNo2** [comment]
i installed Eminence from your jurialmunkey Alpha repo.
when i go to Videos>Video addons>TheMovieDb Helper> i.e. Movies>Popular
it crashed!

i attached the log, just in case?! 
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9547865/kodi.log)

BTW: Arctic Horizont 2 is a very beautiful and powerful skin. hope you find a fix soon.

**Comment by jurialmunkey** [comment]
Please reduce number of threads to 20 in expert settings for tmdbhelper and see if that helps.

**Comment by AdamNo2** [comment]
unfortunately no difference.

**Comment by AdamNo2** [comment]
i made a discovery that"s may be of some value.
on kodi start with Eminence i straight went to
Videos>Video addons>TheMovieDb Helper> e.g. Movies>Popular
and it crashed at latest on on first retrieving remote data.
but when i downgrade the add-on first via versions to 4.4.0 and then back to 4.11.18 i get back the first result page of e.g. Movies>Popular. Also "next page" works, i see 2nd page of popular movies.
but whatever i select next leads to a crash.
that way i can select something that retrieves data two time before 3rd attempt dies.

**Comment by jurialmunkey** [comment]
A few questions:

Is it only Popular Movies specifically, or does any list crash?
What are your language/region settings inside TMDbHelper?
Do you have the "get additional details from local Kodi library database" setting enabled? If so, can you try disabling it and see if that makes a difference.

**Comment by AdamNo2** [comment]
1) same with top rated i.e.
2) English (United States of America)
3) it's disabled

**Comment by AdamNo2** [comment]
some more details about how it behaves at my end.
as long i do not request a second level list per topic it does not crash!
i.e. Movies>Popular and then back via ..
Movies>Top Rated, back via ..
Movies>Upcoming Movies back via ..
and so on...

one level is fine. a second level list is displayed but triggers "something" and even selecting .. leads then to a crash.

**Comment by MattTheTekie** [comment]
> 1. same with top rated i.e.
> 2. English (United States of America)
> 3. it's disabled

I have same settings

**Comment by MattTheTekie** [comment]
Any updates?

**Comment by jurialmunkey** [comment]
No because I cannot recreate this crash (not even on a Linux virtual machine). I don't know what that causes is. If you can tell me what version it started occurring in then I can look at what code changes happened - otherwise I have no idea

**Comment by MattTheTekie** [comment]
Do you think it could be related to python on the latest Linux lite version? Can you fire up a VM with the latest Linux lite and try with that?

**Comment by MattTheTekie** [comment]
I think python versions will vary on each distro

**Comment by MattTheTekie** [comment]
@jurialmunkey can you test it in Linux lite? I want to see if it will reproduce as it's not just me unfortunately. I'm thinking it's affecting Ubuntu based distros potentially with python versions. One distro/OS won't have the same python packages typically.

**Comment by jurialmunkey** [comment]
I use Linux Mint in my virtual machine and that's Debian/Ubuntu based.

**Comment by MattTheTekie** [comment]
Oh... That's a good testing VM, that's kind of worrying that it's affecting me and a few others. Il test it on my android sometime this weekend.

**Comment by AdamNo2** [comment]
after updating Python3 from v3.10.4 to 3.10.6 it finally worked for me. no crash!

**Comment by MattTheTekie** [comment]
> after updating Python3 from v3.10.4 to 3.10.6 it finally worked for me. no crash!

im going to try that, thank you! il post a update tommorow

**Comment by MattTheTekie** [comment]
I'm going to close the issue until i attempt it after working on another system within 2 days. I will open it when I can update this.
