### ISSUE TITLE
Broken Context Menu

### ISSUE THREAD

**Issue by urs45** [jurialmunkey/plugin.video.themoviedb.helper#853]
On the Film Widget the option to choose player is missing in the Context Menu

**Comment by jurialmunkey** [comment]
Install the context menu addon
https://github.com/jurialmunkey/context.themoviedb.helper/releases

**Comment by urs45** [comment]
..but it works with serials without this addon still, when using the addon i have all the entries doubled now. Once directly on right clicking on an Episode and additionally in the Tmdbhelper options subfolder. So there is different behaviour for Film widget and serial widget now. I am using Tmdbhelpers widgets "today trending" for both, serials an Films. (Ok i understood now, I am leaving the widget when going to season/episode...anyway i liked the old version more. To have the choose player option directly in the context menu and not in a tmdbh options subfolder, because then it looked same in Film and Serial widget and media window and i could choose player in film widget directly on a right click, without going to subfolder first. But ok this is a cosmetical thing only.

**Comment by jurialmunkey** [comment]
Without the addon kodi will only add context menu items inside the media windows. It will not add them to widgets.

Previously I forced the context menu addon to ship with Tmdbhelper. Now it is optional.

**Comment by urs45** [comment]
When you could make work this new subfolder,
Tmdhelper options, work with kodi standard favourites widget would be great!

**Comment by urs45** [comment]
Ok i understood now, I am leaving the widget when going to season/episode...anyway i liked the old version more. To have the choose player option directly in the context menu and not in a tmdbh options subfolder, because then it looked same in Film and Serial widget and media window and i could choose player in film widget directly on a right click, without going to subfolder first. But ok this is a cosmetical thing only.
