### ISSUE TITLE
[question] fanart.tv suppressing retries

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#854]
Is this to tmdb helper, fanart.tv site or something else?
```
2022-09-09 20:42:38.444 T:2936     INFO <general>: [plugin.video.themoviedb.helper]
                                                   ConnectionError:  HTTPSConnectionPool(host='webservice.fanart.tv', port=443): Max retries exceeded with url: /v3/movies/1014676?api_key=xxxxxxxxxxx&client_key=xxxxxxxxxxxxx (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1128)')))
                                                   Suppressing retries for 30 seconds
```
ps xxxxxxxx is api

**Comment by jurialmunkey** [comment]
Sounds like fanarttvs ssl certificate was renewed and the service which provides kodi with authentication of certificates hasn't received the new one yet. If certs don't match for a https connection then it is rejected by kodi as it could be a domain hijack (it's like those warnings you get in a browser about a dangerous site telling you to go back) 

 It happened last year too when fanarttv updated its servers. Whatever provider they are using for certification lags in distributing to the one kodi uses.
