### ISSUE TITLE
player configuration for jellycon

### ISSUE THREAD

**Issue by cremonies** [jurialmunkey/plugin.video.themoviedb.helper#858]
### Describe the feature that you'd like

Adding the jellycon plugin to the list of video players.

### Why is this feature needed? What problem does it solve?

Opens tmdb helper to users that also use jellyfin server.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
There are instructions in the wiki about how to make players. I don't use this plugin so I cannot make a player for it.

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

**Comment by cremonies** [comment]
Thank you.
