### ISSUE TITLE
[question] cast extended info 

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#859]
I have an interesting situation. When an adult movie actress is found in some movie, and when I want to open her information and the movies she starred in, nothing comes up. Is there any restrictions on such actors and movies?

**Comment by jurialmunkey** [comment]
Yeah, pretty sure TMDb will filter these out
https://www.themoviedb.org/bible/people/59f747aa9251416e71000049?language=en-AU

The only way to include them is to use the setting "Include Adult Items in Search?" -- problem is that TMDbHelper currently doesn't have any account authorisation setup, so you're stuck with the default account settings.

I've never really added any account auth for TMDb because it is a total pain. It doesn't have an access code like Trakt and instead requires a website redirect, so not exactly a great setup for Kodi. Plus I generally think Trakt does most of those things like watchlist etc. better, so there really isn't any benefit for user account auth other than allowing porn content basically.

**Comment by matke-84** [comment]
Hmmm. But it is very interesting that it works with AH2. How did you manage to do that?
Example: Documentary, After porn ends 2, Lisa Ann

**Comment by xyzfre** [comment]
I hope in the future if something like this is Added that there will be a setting to disable adult content wouldn't want my family to see anything like that on my device I think if people want to watch adult content they should just use the web

**Comment by jurialmunkey** [comment]
> Hmmm. But it is very interesting that it works with AH2. How did you manage to do that? Example: Documentary, After porn ends 2, Lisa Ann


~That's not an adult movie though. It's a documentary *about* adult movies~
EDIT: Actually doesn't look like adult movies are being filtered out by TMDb anyway

I'm not doing anything special in AH2. It's just the standard cast list (plus whatever query etc. params you need)
`plugin://plugin.video.themoviedb.helper/?info=cast&amp;tmdb_type=movie` 

Then onclick action from cast list to call the info dialog (replace $PARAM[id] with cast container ID).
`RunScript(plugin.video.themoviedb.helper,add_path=$INFO[Container($PARAM[id]).ListItem.FolderPath],call_auto=1190)`

Same goes for the movies list itself. It's just standard stars_in_movies list (plus your query params etc.)
`plugin://plugin.video.themoviedb.helper?info=stars_in_movies&amp;tmdb_type=person`

**Comment by matke-84** [comment]
@jurialmunkey
Of course I didn't search for porn movies, I talk all the time about regular movies in which some porn stars have roles. I use the same parameters, but instead of the actress I mentioned, a completely different person with a similar name appears. And this is the case with many skins I tried that have an integrated tmdb helper, except for ah2, which is the only one that gives real results. That's why I asked how you did it. There is some secret in ah2. :-)

**Comment by jurialmunkey** [comment]
@matke-84 What is your onclick action for cast?

If you provide the tmdb_id= for the person you will get the exact person (or use TMDb cast list and pass the listitem folderpath)

If you use query params then the ID needs to be looked up. The TMDb search endpoint filters out adult results by default, so you won't get matches for adult movies/people etc. via a query.

**Comment by matke-84** [comment]
Since I'm using a tmdb list I'm using this one:
`<onclick>RunScript(plugin.video.themoviedb.helper,add_path=$INFO[ListItem.FolderPath],call_auto=1190)</onclick>`
But I also tried this function, but in the selection of actors there is no corresponding actress.
`<onclick>RunScript(plugin.video.themoviedb.helper,add_query=$INFO[ListItem.Label],type=person,call_auto=1190)</onclick>`

**Comment by jurialmunkey** [comment]
add_query= wont work because TMDb search endpoint filters out adult results.

**Comment by matke-84** [comment]
So which function should I use? Can you help me please?

**Comment by matke-84** [comment]
> If you provide the tmdb_id= for the person you will get the exact person (or use TMDb cast list and pass the listitem folderpath)

Did you mean this? If you are, I still don't get info about the actors (actors who are on the restriction list) or I'm getting the wrong information for these actors.
`plugin://plugin.video.themoviedb.helper?info=cast&amp;type=movie&amp;tmdb_id=$INFO[ListItem.UniqueID(tmdb)]`

![aaa](https://user-images.githubusercontent.com/74268331/190128573-8be1f255-5243-477a-9612-d8111e964110.png)
![bbb](https://user-images.githubusercontent.com/74268331/190128652-047e86db-beb7-480e-8850-c54232bcdb93.png)

For the onclick action, I don't know what query to put, because when I try with the tmdb_id instead of add_path, I get an error.
I looked a bit at ah2 and I see that there is nothing much different. I don't understand where I'm going wrong.

**Comment by jurialmunkey** [comment]
The onclick for the cast list in AH2 is 
` RunScript(plugin.video.themoviedb.helper,add_path=$INFO[Container($PARAM[id]).ListItem.FolderPath],call_auto=1190)`

You can use that for any TMDbHelper listitem and it will provide the exact item.

**Comment by matke-84** [comment]
I tried but I still get the same result. This is totally weird.

**Comment by jurialmunkey** [comment]
What's your full cast path?

Also make sure each container ID is unique and your onclick action references the specific container with `Container(1234).`

**Comment by matke-84** [comment]
I have variables in cast path, same  as in ah2, but without variables it would look like this for movies.
`plugin://plugin.video.themoviedb.helper?info=cast&amp;nextpage=false&amp;aggregate=true&amp;type=movie&amp;tmdb_id=$INFO[ListItem.Property(tmdb_id)]`

**Comment by matke-84** [comment]
I forgot to mention that movies she starred in appear, but the information about the actor, biography, date of birth is missing... or they are wrong. So the problem is only in the biography of the actor.

**Comment by jurialmunkey** [comment]
Hmmm that's really strange. I'm not doing anything different. That's same path I use (except I also use cacheonly=true and fanarttv=false but that won't make a difference).

And you're definitely doing this for onclick? (replace 1234 with container id for cast container)
`<onclick>RunScript(plugin.video.themoviedb.helper,add_path=$INFO[Container(1234).ListItem.FolderPath],call_auto=1190)</onclick>`

**Comment by matke-84** [comment]
I have used both. Everything works perfectly except for these adult actors. That's where it causes me problems.
`RunScript(plugin.video.themoviedb.helper,add_path=$INFO[Container($PARAM[id]).ListItem.FolderPath],call_auto=1190)`
`RunScript(plugin.video.themoviedb.helper,add_path=$INFO[Container(53001).ListItem.FolderPath],call_auto=1190)`

**Comment by matke-84** [comment]
I think the problem is how I pull the information. For example, a biography. I use:
`$INFO[Window(Home).Property(TMDbHelper.ListItem.Biography)]`
This works with standard actors. Maybe I should target some container for more detailed information?

**Comment by matke-84** [comment]
I did it like this, just tell me if there is another way, because it seems to me that it opens a few seconds slower.
I made a list:
   ```
 <control type="list" id="9999">
      <itemlayout />
      <focusedlayout />
      <content limit="1" target="videos">$INFO[Window(Home).Property(TMDbHelper.Path.Current)]</content>
    </control>
```
And then I pull the information like this:
`$INFO[Container(9999).ListItemAbsolute(0).Property(Biography)]`
Is this ok?

**Comment by jurialmunkey** [comment]
Yeah that's fine. But you shouldn't need the container reference. `ListItem.Property(Biography)` should be fine by itself in the info dialog.

And yeah, it was because you were using the service monitor window properties rather than the actual listitem.  The service monitor is failing for the same reason as add_query doesn't work -- when it does the search for TMDb ID based on the name of the item, it isn't getting those results.

**Comment by matke-84** [comment]
Thanks a lot as always. ;-)
