### ISSUE TITLE
[BUG] "Ended"/"Canceled"/"Returning Series" not localized

### ISSUE THREAD

**Issue by ArtyIF** [jurialmunkey/plugin.video.themoviedb.helper#861]
### Describe the bug

When viewing TV shows in skins that display the show status (like Arctic: Zephyr - Reloaded), the "Ended"/"Canceled"/"Returning Series" text doesn't get localized.

### Steps To Reproduce

1. Use a localization other than English
2. Use supported skin (like Arctic: Zephyr - Reloaded)
3. Open TV show and look at the show status (with media icons by default for AZR)
4. Text not localized

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Translation of the status should be handled by the skin.

Status is not translated by TMDb API. It also should not be translated by TMDbHelper otherwise skins have no way to check the status (because the skin won't know what language it has been translated into or what the specific translation is).
