### ISSUE TITLE
[Feature] Plot and time duration for tmdb videos (trailers)

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#863]
### Describe the feature that you'd like

Can I ask if there is a possibility to add properties for tmdb videos (trailers). If there is a plot for them, but duration is more important to me. I need it for a skin. Thanks in advance.

### Why is this feature needed? What problem does it solve?

/

### Steps to reproduce.

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Nope unfortunately not. This data isn't provided with the endpoint, so it would involve checking the video itself which would be slow. https://developers.themoviedb.org/3/movies/get-movie-videos

This is all the data given:

```
{
      "iso_639_1": "en",
      "iso_3166_1": "US",
      "name": "Fight Club - Theatrical Trailer Remastered in HD",
      "key": "6JnN1DmbqoU",
      "site": "YouTube",
      "size": 1080,
      "type": "Trailer",
      "official": false,
      "published_at": "2015-02-26T03:19:25.000Z",
      "id": "5e382d1b4ca676001453826d"
    },
```

**Comment by matke-84** [comment]
Ohhh. What a shame. Ok. Thanks.
