### ISSUE TITLE
[BUG] Default player for episodes

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#864]
### Describe the bug

Following a clean Kodi install, setting a default player for episodes throws up an error (setting default player for movies works fine). Never experienced this before so may be an issue with my particular setup, but thought I'd share this log in case it's a bug.  http://ix.io/4aEI

### Steps To Reproduce

TMDb Helper - Players - Default player for episodes 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by Galoup** [comment]
hello I have exactly the same problem I am on a CLEAN KODI installation I use the Artic Horizon 2 Skin
And the latest version of TMDb Helpers
And indeed when I want to add a default player for the episodes it gives me an error:
https://paste.kodi.tv/isolupuram


bonjour j'ai exactement le même problème je suis sur une instalation de KODI PROPRE j'utilise le Skin Artic Horizon 2
Et la dernière version de TMDb Helpers
Et effectivement quand je veut rajouter un players par défaut pour les épisodes celà me met une erreur :
https://paste.kodi.tv/isolupuram
