### ISSUE TITLE
[question] scripted recommendations

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#868]
I see there is news in the tmdb helper. Can you explain a little about the new function? I see that now extended info in ah2 loads very fast. 
Can it be applied in other skins as well?

**Comment by jurialmunkey** [comment]
Yeah I'll write up some proper documentation for the new scripted windows soon. For now you'll need to look at how AH2 does things for more detailed info.

XML name: `script-tmdbhelper-recommendations.xml`

`Runscript(plugin.video.themoviedb.helper,recommendations=5000|info=cast|true|info||5001|info=similar|true|info,tmdb_type=movie,query=Alien,year=1979)`

^^^ Loads recommendations for the movie Alien. Takes standard tmdb_type, tmdb_id, query, imdb_id, year type lookup params. This will put info=cast into list id=5000 and info=similar into list id=5001. You can stack as many lists as you like with `||`

List definition is `list_id|paramstring|is_related|command`. 
Set is_related as true when list needs ID lookup. 
Set command to info, play, browse, or a Kodi builtin. 

e.g. 

`5000|info=cast|true|info`
is
`info=cast&tmdb_type=movie&query=Alien&year=1979&nextpage=false&fanarttv=false&cacheonly=true`
and does the following onclick/oninfo/oncontext
`Runscript(plugin.video.themoviedb.helper,call_auto=1190,add_path=$INFO[ListItem.FolderPath])`

`5000|info=cast|false|SetFocus(6000)`
is
`info=cast&nextpage=false&fanarttv=false&cacheonly=true`
and does the following onclick/oninfo/oncontext
`SetFocus(6000)`

Window.Property(List_1234_IsUpdating) is set to True when content for the list is loading
Window.Property(List_1234_Visible) is set to True when content for the list finishes loading

**Comment by jurialmunkey** [comment]
Also note things are likely to change - hence why I haven't written proper documentation yet.

**Comment by matke-84** [comment]
Ohhh now it means there is an id for each section (cast, crew, similar...) and I actually don't call the list anymore, it's ready in recommendation, which means it loads quickly. Did I understand correctly?

**Comment by jurialmunkey** [comment]
No, there's no designated IDs. You can set any ID you like and any TMDbHelper path, and you can set as many as you like.

There isn't any pre-caching. The items are retrieved exactly the same as normal. That's how fast TMDbH is. The speed increase is all on the Kodi end of things.

Normally Kodi would need to initialise a separate python instance for each plugin directory. A scripted window runs in a single python instance so its skips that additional overhead. Also, a scripted window "owns" its containers so it can "inject" the items directly into the list rather than needing to do an end of directory handover back to Kodi.

**Comment by matke-84** [comment]
Yes, I got it and I did it. I tried to insert the tmdb video but I don't know how to set property. ListiItem.Vidoes does not exist. At the end, I put content like for youtube videos. Is there another way?
What is croplogo? I see it appearing in tmdb helper and ah2 but I can't understand what it is about.

**Comment by jurialmunkey** [comment]
`ID|info=videos|true|play` gives you trailers from Youtube via TMDb api. 

Otherwise, if you want to use Youtube, you can just create a normal widget with `<content>` tags. Don't include any widgets like that in the RunScript because you want Kodi to manage those.

CropImage is a an image function in the service monitor like Blur or Desaturate. It crops transparent space from the edges of a PNG to try to get a slightly better alignment for clearlogos. It really is only useful for the specific layout in AH2 and won't be much use to other skins.

**Comment by matke-84** [comment]
How can I open posters and fanarts from recommendation dialog?

**Comment by matke-84** [comment]
Can I set my custom onclick function?

**Comment by matke-84** [comment]
Now I saw that ah2 doesn't play trailers either. That's why I asked about the custom button.

**Comment by matke-84** [comment]
> How can I open posters and fanarts from recommendation dialog?

I solved this.

**Comment by matke-84** [comment]
I think it would be good to create another script that would separate the recommendation from the cast and crew in movies and TV shows, like in the old extended info. Then there would be a special dialogue that would contain info about the actors and movies and tv shows they starred in. Also, this dialog could be used independently of the recommendation dialog, just to call up info about the actors, but also in the recommendation dialog itself. The speed of calling and loading would be faster than when it goes through the info dialog.

**Comment by jurialmunkey** [comment]
You're jumping the gun. I've got some additions to come yet...

**Comment by matke-84** [comment]
Ok. Sorry. I just really like how quickly it opens lists on this way. I'm waiting for changes.

**Comment by matke-84** [comment]
After the last update of the tmdb helper, I was getting an error, and then I realized that something in the code had been changed. I saw in ah2 what kind of changes there are and everything works, but I still have one problem. When I click on an actor, for example, an info dialog about the actor opens, and when I go back, the recommendation window opens again, but this time with empty lists. Why is this happening?

**Comment by matke-84** [comment]
here is the log file
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9620195/kodi.log)

**Comment by matke-84** [comment]
Sorry, please, just one more observation. When I play the video, it does not close the recommended dialog like in the last update, but the video goes below it. With the previous update this worked as it should. And it seems to me that the recommended dialog never closes, but the info dialog goes over it.

**Comment by jurialmunkey** [comment]
> After the last update of the tmdb helper, I was getting an error, and then I realized that something in the code had been changed. I saw in ah2 what kind of changes there are and everything works, but I still have one problem. When I click on an actor, for example, an info dialog about the actor opens, and when I go back, the recommendation window opens again, but this time with empty lists. Why is this happening?

Check your include conditions. If you set properties ondown it will be the property from the previous window.
If you need to set a property to the recommendations window you can use `winprop_{propname}={propvalue}` in the Runscript.

> Sorry, please, just one more observation. When I play the video, it does not close the recommended dialog like in the last update, but the video goes below it. With the previous update this worked as it should. And it seems to me that the recommended dialog never closes, but the info dialog goes over it.

Yeah not everything is complete yet. Still working on a good way to handle play/browse. Possibly will change how the window manager works.

If you need to close the dialogs for Play button you can do:
`RunScript(plugin.video.themoviedb.helper,recommendations=onaction,window_id=1191,builtin=SendClick(8))`

Optionally can add `after=True` if you need the Kodi builtin command to run after the dialogs close instead. Note SendClick won't work with after=True because the id=8 play button is in the videoinfodialog and so won't exist after it is closed.

**Comment by matke-84** [comment]
I call the recommendation dialog onclic. I have a little more properties but it looks like this.
`<onclick condition="String.IsEqual(ListItem.DBtype,movie) | String.IsEqual(ListItem.DBtype,tvshow) | String.IsEqual(ListItem.DBtype,season) | String.IsEqual(ListItem.DBtype,episode) | String.IsEqual(ListItem.DBtype,set) | $EXP[Exp_IsPersonInfo]">Runscript(plugin.video.themoviedb.helper,recommendations=$VAR[Path_Recs],$VAR[Path_Recs_Query],$VAR[Path_Recs_Type],window_id=1191,winprop_Collection='$ESCINFO[ListItem.Set]',winprop_Director='"$VAR[Path_FromDirector_Name]"',winprop_Writer='"$VAR[Path_FromWriter_Screenplay]"',winprop_Genre='$ESCINFO[ListItem.Genre]',winprop_Studio='$ESCINFO[Window(Home).Property(TMDBHelper.ListItem.Studio.1.Name)]',winprop_Network='$ESCINFO[Window(Home).Property(TMDBHelper.ListItem.Network.1.Name)]',winprop_Year='$ESCINFO[ListItem.Year]',winprop_Fanart='$ESCINFO[ListItem.Art(fanart)]',winprop_Title='"$VAR[Label_Title]"',winprop_Poster='$ESCINFO[ListItem.Art(poster)]',winprop_Clearlogo='$ESCINFO[ListItem.Art(clearlogo)]',winprop_Tagline='$ESCINFO[ListItem.Tagline]',winprop_Rating='$ESCINFO[ListItem.Rating]',winprop_Votes='$ESCINFO[ListItem.Votes]',winprop_Premiered='$ESCINFO[ListItem.Premiered]',winprop_LastAired='$ESCINFO[Window(Home).Property(TMDbHelper.ListItem.Last_Aired)]',winprop_mpaa='$ESCINFO[ListItem.mpaa]',winprop_Season='$ESCINFO[ListItem.Season]',winprop_Duration='$ESCINFO[ListItem.Duration(mins)]',winprop_Budget='$ESCINFO[Window(Home).Property(TMDbHelper.ListItem.Budget)]',winprop_Revenue='$ESCINFO[Window(Home).Property(TMDbHelper.ListItem.Revenue)]',winprop_Status='$ESCINFO[ListItem.Status]',winprop_Plot='$ESCINFO[ListItem.Plot]',winprop_DBType='$ESCINFO[ListItem.dbtype]',winprop_Creator='"$VAR[Path_FromCreator_Name]"')</onclick>`

The result is this.
![recommended](https://user-images.githubusercontent.com/74268331/191672379-fe69fc1b-efc2-42da-885f-7714c9f4e08f.png)
However if I click on any list on the return I get this.
![blank list](https://user-images.githubusercontent.com/74268331/191672744-3dd0f649-4fa5-424d-881b-d17df6844879.png)

I put this command in dialogvideoinfo.xml because without it I get a black screen when I return and then I have to click back again to close it.
`<onunload>Runscript(plugin.video.themoviedb.helper,recommendations=onback,window_id=1191,setproperty=HideInfo)</onunload>`
I can't figure out what's going on here and why the lists don't load and the other properties I defined appear. (plot, tagline, poster...)

**Comment by matke-84** [comment]
Since there is no documentation, I relied a lot on the code from ah2, of course I adapted it to my skin.

**Comment by jurialmunkey** [comment]
What are your include and visibility conditions for the widgets?

**Comment by matke-84** [comment]
This is how a test example of a widget looks like. Of course, later I will make it for the others, but this will be the basis for the include. 
```
<!-- cast panel -->
                    <control type="group" id="5100">
                        <visible>!String.IsEmpty(Window.Property(List_5000_Visible))</visible>
						<visible>Skin.HasSetting(extendedinfo_details_cast)</visible>
                        <height>460</height>
                        <control type="label">
                            <posx>7</posx>
                            <posy>7</posy>
                            <width>1540</width>
                            <height>25</height>
                            <aligny>center</aligny>
                            <font>Bold31</font>
                            <textcolor>$INFO[Skin.String(BingieSecondaryTextColor)]</textcolor>
							<shadowcolor>$INFO[Skin.String(ViewDetailsHighlightTextShadowColor)]</shadowcolor>
                            <label>$LOCALIZE[206]</label>
                        </control>
                        <control type="panel" id="5000">
                            <posx>0</posx>
                            <posy>40</posy>
                            <width>1792</width>
                            <height>390</height>
                            <onleft>9000</onleft>
                            <onright>5000</onright>
                            <onup condition="!Skin.HasSetting(EnableTouchSupport)">5000</onup>
                            <ondown condition="!Skin.HasSetting(EnableTouchSupport)">5010</ondown>
                            <scrolltime>200</scrolltime>
                            <orientation>horizontal</orientation>
                            <itemlayout height="310" width="223">
                                <control type="group">
									<width>223</width>
									<height>310</height>
                                    <include>PosterPanelExtendedInfo</include>
                                  </control>
								  <control type="group">
									<left>-2</left>
									<top>294</top>
									<control type="label">
										<width>227</width>
										<label>$INFO[ListItem.Label]</label>
										<font>reg22</font>
										<textoffsetx>10</textoffsetx>
										<scroll>false</scroll>
										<align>center</align>
										<textcolor>$INFO[Skin.String(ViewDetailsTextColor)]</textcolor>
									</control>
									<control type="label">
										<top>27</top>
										<width>227</width>
										<label>$INFO[ListItem.Label2]</label>
										<font>reg22</font>
										<textoffsetx>10</textoffsetx>
										<scroll>false</scroll>
										<align>center</align>
										<textcolor>$INFO[Skin.String(ViewDetailsTextColor)]</textcolor>
									</control>
								</control>
                            </itemlayout>
                            <focusedlayout height="310" width="223">
                               <control type="group">
									<width>223</width>
									<height>310</height>
                                    <include>PosterPanelExtendedInfoFocus</include>
                                </control>
								<control type="group">
									<left>-2</left>
									<top>294</top>
									<control type="label">
										<width>227</width>
										<label>$INFO[ListItem.Label]</label>
										<font>reg22</font>
										<textoffsetx>10</textoffsetx>
										<scroll>true</scroll>
										<align>center</align>
										<textcolor>$INFO[Skin.String(ViewDetailsTextColor)]</textcolor>
									</control>
									<control type="label">
										<top>27</top>
										<width>227</width>
										<label>$INFO[ListItem.Label2]</label>
										<font>reg22</font>
										<textoffsetx>10</textoffsetx>
										<scroll>true</scroll>
										<align>center</align>
										<textcolor>$INFO[Skin.String(ViewDetailsTextColor)]</textcolor>
									</control>
								</control>
                            </focusedlayout>
						</control>
                    </control>
```

**Comment by matke-84** [comment]
Sorry Jurial. Do you have any ideas for this problem? It's driving me crazy. I would really like to finally replace the old extended info with tmdb helper extended info.

**Comment by matke-84** [comment]
OK. I finally fixed the problem with the empty list. I tried the latest version of tmdb helper and it still has a problem with opening seasons. When I click on a season, everything just closes and that's it. Tried it also in ah2 and the same thing happens.
I also noticed that in ah2 lacks trailers in recommendations. Just a note.

**Comment by matke-84** [comment]
@jurialmunkey 
Sorry if i'm a bit boring with my comments. I don't mean to bother you. I'm just trying to help with testing, because I know you can't predict all situations by yourself and I know you do all this for free for the community, and thank you very much for that.
Regarding the previous post, when I mentioned that it doesn't open seasons, it doesn't open seasons in the recommended window, the browse function doesn't work. There is also some delay (about 1-2 sec) when start playing video (tmdb trailers) from recommended dialog, but also when exiting the video info dialog if the recommended dialog and its content were opened before that. Both things happen in ah2 as well.
And sorry again if i bore you. That's really not my intention.

**Comment by Bequiet19** [comment]
@matke-84 Seasons in Artic Horizon 2 work for me when opened from the recommended window. Update to the latest version.

**Comment by matke-84** [comment]
@Bequiet19 Yes, it works now. Thanks for the info. Of course, thanks also to @jurialmunkey for this fix.
