### ISSUE TITLE
[Enhancement] Discover - Region

### ISSUE THREAD

**Issue by Demonseeed** [jurialmunkey/plugin.video.themoviedb.helper#87]
I believe adding the ability to select one or more regions in the query may be beneficial.

I also think just being to input the ISO 3166-1 country code should suffice, as it was very easy to find the list of codes after Googling it (since I didn’t even know what that was).

**Comment by jurialmunkey** [comment]
Added https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/a71722178dde6b273de166998092de81e689cdcd

**Comment by Demonseeed** [comment]
Sweet! I’ll have to wait till tomorrow for testing but I appreciate the fast response as always!

**Comment by Demonseeed** [comment]
Tested and works 😄👌

**Comment by jurialmunkey** [comment]
Excellent! Thanks 😁
