### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by Djej30** [jurialmunkey/plugin.video.themoviedb.helper#877]
### Describe the bug

my player don't work properly

### Steps To Reproduce

Hello,
I am using Artic horizon 2 skin with tmdb helper V5.
I created a player with the player creator and the "keyboard_dialog" function and there is a bug when I use it.
Indeed during the first use it works well (I click on a thumbnail, the keyboard opens and the title is typed automatically) but if I go out with "back", and I click on another thumbnail, the search starts and this brings me back to the previous result. I have to click "delete" for the search to start up again and work.

It works well with Estuary skin however.
Thanks for your help

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Log? Player file? Plugin name?

Can't help if you don't have a log and haven't supplied basic info about even what plugin it is or the file in question.

**Comment by Djej30** [comment]
[01_KODI.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9662665/01_KODI.log)
[autogen.plugin.video.vstream.txt](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9662678/autogen.plugin.video.vstream.txt)

**Comment by Djej30** [comment]
Thanks for your help @jurialmunkey

**Comment by jurialmunkey** [comment]
TMDbHelper is working fine and following the steps that you have defined. That entry point is probably not suitable. You will need to read the wiki about writing player files and possibly speak to the plugin author about writing a suitable player.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

**Comment by alKODIque** [comment]
@jurialmunkey 
I believe that @Djej30 Talk about the cache of the previous search remains when using the magnifying glass as in the video below. I guess it's not related to a player but a skin issue? (Maybe I'm wrong too)
I'm using an autogen player for the same addon (vStream) and don't have any issue when ''I clic'' on a thumbnail of a movie. 
EDIT: The search term remains in search bar even when I search from a TMDbH widget item)

https://user-images.githubusercontent.com/49578130/194710983-2ae15a04-2e98-489d-9642-7bbc56f233c4.mp4

**Comment by alKODIque** [comment]
Also, I think that using this search from the context menu don't work in other language than english...
When I use it and the title of a movie is translate in french, I have no result.
I'm pretty sure we have to move this issue to AH2 ;)

Here is a video and my  log file when I search directly from TMDbH addon
(Search began at line 6230 on my log file)
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/9739490/kodi.log)

https://user-images.githubusercontent.com/49578130/194712338-6ce0586b-8f12-4b80-8f86-721018b9be3f.mp4
