### ISSUE TITLE
Plex widget problem

### ISSUE THREAD

**Issue by webmaher** [jurialmunkey/plugin.video.themoviedb.helper#88]
On Sony Android TV  Kodi need about 20-40 second to connect on my Plex acc. 
This is too slow and Plex widget "Shows in progress" not appear on my main menu.... so I must go to "Customize home menu" settings and something change and apply and then widget become visible and work OK... 
I start KOdi 15 times and only 2 times widget show up because somehow connection time to my plex be fast enough...
Is any solutions for that?

**Comment by drinfernoo** [comment]
That is an issue with the Plex add-on, not this one.

**Comment by webmaher** [comment]
Options with widget delay time when Kodi start?
The only issue here is connection time to my Plex when Kodi start and widget also want to start but because plex not connected yet small problem is here :-)

**Comment by drinfernoo** [comment]
@webmaher Yes, it would be up to the add-on that's populating the widgets to try and delay those widgets, if even possible.
