### ISSUE TITLE
Trakt supposed to mark things watched?

### ISSUE THREAD

**Issue by MrC001** [jurialmunkey/plugin.video.themoviedb.helper#880]
Is TMDB Helper supposed to mark things watched after watching them, cause it doesn't..always have to manually mark as watched in trakt.  I assume it is else why have trakt in there?

**Comment by xyzfre** [comment]
Did you authorize Trakt in TMDb H settings I'm running all the current versions and everything is marked as watch almost instantly When I'm done watching something,, if you post a log that will be very helpful

**Comment by MrC001** [comment]
Yes is authorized.   Same with my dad's and my friends .... And is latest
... Will grab log when home.

**Comment by jurialmunkey** [comment]
No tmdbhelper does not scrobble items. Use the official trakt addon from the kodi repo for scrobbling.

For plugins that don't work with the official trakt addon because they don't use setresolvedurl properly, any scrobbling must be managed by the end plugin.

**Comment by MrC001** [comment]
Yes, after searching and more searching found that out.  Sorry to bother.
