### ISSUE TITLE
[BUG] Multiple Bugs in Recommendations Window with Arabic 

### ISSUE THREAD

**Issue by psp2111-ADSLGATE** [jurialmunkey/plugin.video.themoviedb.helper#882]
### Skin section

Video Info Dialog

### Current Behavior

Hi @jurialmunkey 

After update v0.4.22 Recommendations Section does not work properly with Movies or TV Shows that have an Arabic title.
weirdly the behavior is different if the content is Movies or TV Shows:

Movies: if I choose a movie in TMDb Helper with an Arabic Title and go to Recommendations section the letters in the title of the movie are reversed, as well as the title of the Genres section "Picture"

For TV Show it does not work at all with no error just goes back to the Information window. "I could provide a log if you needed it"

Picture: v0.5.7

![Screenshot_1-min](https://user-images.githubusercontent.com/80945174/192869166-ceb94706-53a4-46f4-a7f8-374e57852ccf.png)

### Expected Behavior

Recommendations Section should work as v0.4.22 "Picture 2"

Picture 2:

![Screenshot_2-min](https://user-images.githubusercontent.com/80945174/192869361-f1ec60cd-f107-46b0-ab1f-acecf5b9daea.png)

### Steps To Reproduce

1. Change the "Language and Country" to Arabic Saudi Arabia in TMDb Helper settings.
2. Try to go to Recommendations Section for any Movie or TV Show with an Arabic Title.

Note: No need for changing the interface language of Kodi to Arabic. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Tmdbh issue so moving there. I'll have a look after work and see if I can fix it.

**Comment by jurialmunkey** [comment]
@psp2111-ADSLGATE 

Can you try v0.5.9 of the skin with v5.0.3 of TMDbHelper?
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.5.9
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v5.0.3

Kodi has some limitations in passing RTL text via a script so I've knocked together a workaround (it's a bit ugly but appears to work fine as far as I can tell).

EDIT: Sorry should be 0.5.9 not 0.5.8 as there was an error.

**Comment by psp2111-ADSLGATE** [comment]
> @psp2111-ADSLGATE
> 
> Can you try v0.5.9 of the skin with v5.0.3 of TMDbHelper? https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.5.9 https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v5.0.3
> 
> Kodi has some limitations in passing RTL text via a script so I've knocked together a workaround (it's a bit ugly but appears to work fine as far as I can tell).
> 
> EDIT: Sorry should be 0.5.9 not 0.5.8 as there was an error.

It is working now for both movies and tv shows.

but the transition Animation from info window to rec section is a bit laggy and sudden.
it is not like going back from rec section to info window.

Sorry to bother you again but I found another Bug which is Wiki Feature does not work with any content with Arabic title and only give a blank window.

Thanks a lot @jurialmunkey for your hard work.
