### ISSUE TITLE
[BUG] Lost Sorting functionality in 'Discover' output    

### ISSUE THREAD

**Issue by jollyhiggler** [jurialmunkey/plugin.video.themoviedb.helper#883]
### Describe the bug

The order of the output from any 'Discover' query now defaults to something resembling "Popularity Descending" irrespective of the sort method selected. 

### Steps To Reproduce

Discover >> "Discover Movies" / "Discover TV Shows"
Repeatedly conduct any 'Discover' query, modifying only the sort method each time.  

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Oops, accidentally reused the param name for something else. I though the results seemed a bit off in a couple of discover lists I had.
