### ISSUE TITLE
Add/remove to watchlist button

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#890]
I have "add to my list" option/button in my skin and it works for local content. I would like to have the same button but to work with trakt. Of course, tmdb helper has that option, but I would only insert button "add to watchlist" without popping up the entire context menu. Is there any chance for that? Also, is there an option that would allow me to remove content from my watchlist? Thanks in advance.

**Comment by matke-84** [comment]
Sorry Jurial. Does this option already exists but maybe is not written in the documentation or must be implemented?

**Comment by matke-84** [comment]
Sorry Jurial, can something be done here? In the video you can see what I would like (this is a local library and works with bingie helper). I think it would be a good option for ah2 too as a quick way to add something to trakt watch list. It bypasses the part with opening the context menu, and I believe that many will use this, at least I have such requirements. Netflix has the same option. If by any chance there is a problem for this, just answer me to know. Thanks in advance.

https://user-images.githubusercontent.com/74268331/194700928-2fc44e8d-bf99-460e-bf8b-6714024fa5ef.mp4

**Comment by jurialmunkey** [comment]
No there is currently no way to add to watchlist directly without going through the sync menu.

If you want to make a feature request, please use the feature request template
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/new?assignees=&labels=enhancement&template=feature_request.yml&title=%5BFeature%5D+Description
