### ISSUE TITLE
[BUG] Wrong Reality TV genre suggestion

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#893]
### Describe the bug

Maybe it's not up to TMDB Helper, but it happens that for some reality TV it gives completely wrong suggestions for genre. I thought that maybe I did something wrong in the skin code, but then I noticed that the same thing happens in AH2.
![titan](https://user-images.githubusercontent.com/74268331/193638721-197a06f5-5e26-45b6-a101-c1eb0a5ea064.png)
![ah2](https://user-images.githubusercontent.com/74268331/193638754-d06bac46-2fdb-4516-8adb-c33400ef88fa.png)

### Steps To Reproduce

/

### Debug log

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
"reality TV" is not a genre on TMDb. The genre on TMDb is "reality". 
https://www.themoviedb.org/bible/tv/59f73eb49251416e71000024

You're seeing the default discover list because it has no params...
