### ISSUE TITLE
Tmdb helper question

### ISSUE THREAD

**Issue by bassemhelal18** [jurialmunkey/plugin.video.themoviedb.helper#894]
I need to ask a question if am using tmdb hepler and set the language to English us .and there is a lot of movies with backdrop but language is not set to them can the tmdb helper if it can't find a language for the backdrop use the one with no language set  (language not available)

**Comment by jurialmunkey** [comment]
If you enable fanarttv there is a setting to fallback to English artwork when no language artwork is found.
