### ISSUE TITLE
"Directed by" list from TMDb People

### ISSUE THREAD

**Issue by tpaniaki** [jurialmunkey/plugin.video.themoviedb.helper#896]
"Directed by X" is a very useful list to navigate filmography from a movie home page. However, it doesn't show up from the TMDb "People" page (if I search X I cannot access his/her filmography). Any reason?

**Comment by jurialmunkey** [comment]
Crew in movies shows all the movies the person directed, wrote or produced

**Comment by tpaniaki** [comment]
Thank you for your reply.

But that wasn't really my point. When I look for a filmography, I don't care whether the director is "executive producer" or "producer" of x or y. I'd like to know what films he's made, namely what's included in the list "Directed by".

**Comment by jurialmunkey** [comment]
That's a skin issue and up to the skinner to decide what to show.

**Comment by jurialmunkey** [comment]
As listed in the wiki, a skinner can apply exclusion and filter params to determine what parts of a list are shown
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Lists-Additional-Params#optional-exclusion-and-filter-parameters

**Comment by tpaniaki** [comment]
OK. Well I use your wonderful Arctic 2. Would you be open to a feature request on the dedicated github?
