### ISSUE TITLE
[question] Open recommendation script directly from actor info

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#897]
I tried to use the recommendation script directly from actro info but there are small problems. When I enter the actor info and run the recommendation script, everything works as it should. Then when I click on a movie to open the info, I get the result as in video I posted. It starts to open and then returns to the script. Also, when I want to exit everything, a black screen appears and then I have to click back again to exit. Is there a chance to use it in this way or must it be used exclusively from the recommended window. Thank you in advance for your answer and I apologize that in the last few days I may have been a bit boring with questions and requests. My intention is just to help make tmdb helper as good as possible.

https://user-images.githubusercontent.com/74268331/193998508-7acd6199-3f76-4884-919e-58d70a073552.mp4

**Comment by jurialmunkey** [comment]
I don't really understand what you're trying to do.

Actors work fine in AH2 using recommendations.

**Comment by matke-84** [comment]
No, no, everything works when you enter the recommended script in a regular way. That's all ok. I tried a slightly different way to enter. Just watch the video carefully.
Clicking on the name of the actor I open the info about the actor here.
`RunScript(plugin.video.themoviedb.helper,add_path=$INFO[Container($PARAM[id]).ListItem.FolderPath],call_auto=1190)`
Currently in this window I have info about the actor and I made buttons when they are in focus to open the lists cast in movies, cast in tv show... Since the list of 50 movies opens a little slower, I tested the click ondown to open the recommended info, like you do in ah2.
`Runscript(plugin.video.themoviedb.helper,recommendations=.........`
And it works. But then when I click on the movie, it starts to open the info dialog, but instead of opening it, it returns it to the script. When exiting after that I get stuck on a black screen and have to click back again to exit.
When I do all this from the recommended window, everything works as it should.

**Comment by jurialmunkey** [comment]
You can't mix the two window management methods.

Unnecessary anyway. Use the oninfo recommendations action. You can see how to use it from the cast list in AH2 video osd.

**Comment by matke-84** [comment]
Woooow. I didn't know this. That's it. The recommended script is full of secrets. :-)

One small suggestion, I don't even know if it's possible. When I call the oninfo action from the info dialog, when returning back from the recommended script, it takes me back to home instead of the info dialog. Is it possible to return me to the info dialog instead?

https://user-images.githubusercontent.com/74268331/194050415-df7b9660-299e-41b7-b99d-443c9ed6cc73.mp4

And one more little thing that can be seen on the video, which is that there is a slight delay when closing, a delay of a second (not my animation), does it have to be like that? This also happens when I open some info about the movie or the actor in the recommended window.

**Comment by matke-84** [comment]
I found one bug. When I enter recommendation script, then I open some content, for example, info about the actor, info about the movie... then I exit from recommendation script into the dialog info, when I want to go directly to the info about the actor with command
`RunScript(plugin.video.themoviedb.helper,add_path=$INFO[Container($PARAM[id]).ListItem.FolderPath],call_auto=1190)`
it starts to open and then a black screen appears and that's it. I then have to press the back button twice to get to the home page. I hope you will understand what I wanted to say on the video. 
I assume that this is about the fact that recommendation script is not actually closed until the dialog info is completely closed. Is there any solution here?

https://www.youtube.com/watch?v=38d6j-6srMo

**Comment by jurialmunkey** [comment]
Why are you trying to mix methods with the old one? Like I said before, you can't mix the two methods - you can't use the old call auto method with the new recommendations method . Pick one.

**Comment by matke-84** [comment]
How do you think I'm mixing methods? This should not be a mixing of methods. These should be two totally separate things. Please don't get me wrong. I know that you adapt most things to the ah2 skin, which is completely legitimate, both the skin and the helper are yours but I like to do some things differently. In the old original extendedinfo script this worked without problems. The old extended info had three separate scripts and each could be used separately. I think the biggest problem is that the script in the tmdb helper is not closed by exiting from script window, but must be exited from the dialog info. 
There is also another problem. If I were to use, for example, only the new method, when I call info about the actors from the recommendation script, it opens, but when I want to play a movie, I can't do that because the recommendation script is open in the background. I need like in ah2, for example ondown, to call recommendation script again in order to open a movie. But I would like to have everything in one window like in the picture.
![qqq](https://user-images.githubusercontent.com/74268331/194808178-9904e94d-2d60-4d40-8302-c9d4e07466e6.png)
In this window, I open lists when I focus on a button. Clicking on the movie, my idea was to play the movie, clicking on tv show to open the seasons. but that is unfortunately not possible as long as the recommendation script is running.
I would like these two scripts to work together a little better although I know it's not easy.
In the end, of course, if I want to use the tmdb helper extended info function, I will have to adapt to the way it works, and that's also fine. Sorry for such a long post.

**Comment by jurialmunkey** [comment]
You cannot use the `add_path=call_auto=1190` method with the scripted recommendations window. call_auto runs a different window manager -- if you mix this method with the recommendations window then you will have two separate window managers both running at the same time trying to open and close dialogs.

`call_auto=` and `recommendations=` are two different methods for doing exactly the same thing. You need to pick one.

If you want to use the new scripted recommendations window, then every call should be going through `recommendations=`
If you want to use the old native Kodi method, then every call should go through `call_auto=`

You cannot mix these two window management methods.

**Comment by matke-84** [comment]
We didn't understand. When I enter the recomendation script, by default, when I click on an actor, it starts the oninfo function. In ah2, in order to see cast in movies, cast in tv shows... you click again ondown and then a new window opens with that content. In my case, when I open the info about the actors, on the focus button, it opens the same lists in the same window. In this window, as far as I know, I cannot display the content as it works in the recommendation window, but they are classic lists. Correct me if I'm wrong. The problem is that in this way I can't do anything with that content (I can't play the movie, open the seasons...), I have to start a new window like in ah2, which I honestly don't like. But ok, if so I have to adapt to the situation.

https://user-images.githubusercontent.com/74268331/194827212-89f288a9-2502-41aa-8c5d-5d447dabd2bb.mp4

**Comment by matke-84** [comment]
Just tell me one thing. How do I start a movie from the recommendation window? How do I actually close the script to start watching the movie. When I click on the movie the script doesn't close and of course the movie goes below.

**Comment by matke-84** [comment]
I tried this old one first which worked perfectly.
`RunScript(plugin.video.themoviedb.helper,close_dialog=1191,playmedia='$ESCINFO[ListItem.FileNameAndPath]')`
Then I tried with this one I found in ah2.
`RunScript(plugin.video.themoviedb.helper,recommendations=onaction,window_id=1191,after=True,builtin='PlayMedia($ESCINFO[ListItem.FileNameAndPath])')`
I'm talking about starting the movie from info dialog when script is open. Also, if I enter tv show and open the season, when I go back it always ends with a black screen. It looks like the script is not closed. Then I have to go back once more to close the window.

https://user-images.githubusercontent.com/74268331/194864806-415edcbe-d965-4f15-8178-ce5285ba668c.mp4

**Comment by matke-84** [comment]
`RunScript(plugin.video.themoviedb.helper,recommendations=onaction,window_id=1191,after=True,builtin='PlayMedia($ESCINFO[ListItem.FileNameAndPath])')`
This actually works, the only thing is I made a another button for the info dialog when the script is active.
Sorry for several consecutive messages, but it is very difficult to do something without proper instructions and based on what was done in ah2. I hope you will make some documentation soon.
