### ISSUE TITLE
[Feature] All Seasons folder next to seasons views

### ISSUE THREAD

**Issue by florence-wolfe** [jurialmunkey/plugin.video.themoviedb.helper#899]
Having an All Seasons list, even paginated, would allow for playing any random episode of a show very easily using the [Play Random Videos add-on](https://kodi.wiki/view/Add-on:Play_Random_Videos) context menu, among probably other helpful functions

Some other add-ons like PlexKodiConnect already support this, but this may be native/default behavior for content in a Kodi library.

_Originally posted by @francis-robert in https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/748#issuecomment-1270878392_

**Comment by jurialmunkey** [comment]
Please use the feature request issue template. That's why I asked that you open a new issue
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/new?assignees=&labels=enhancement&template=feature_request.yml&title=%5BFeature%5D+Description
