### ISSUE TITLE
[Request] Trakt ID property

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#9]
Is it possible for tmdbhelper to add the movie/tvshows/episodes Trakt ID as a ListItem.Property?

Thanks!

**Comment by jurialmunkey** [comment]
I can add it for lists from trakt but not from TMDb. TMDb doesn't return trakt id/slug afaik.

Would that be useful? What are you trying to achieve with the ID?

**Comment by skyfsza** [comment]
That would be great, no problem with not having on items from TMDB lists.

Side question, when I use for example, info=similar or info=recommendations,  I assume thats coming from a TMDB?   if so, is it possible to add option to choose / default to Trakt?

Trakt ID would allow me to link into addons to gain features like Trakt Manager and in certain instances ability to trigger Play action.

Thanks!

**Comment by jurialmunkey** [comment]
> 
> 
> Side question, when I use for example, info=similar or info=recommendations, I assume thats coming from a TMDB? if so, is it possible to add option to choose / default to Trakt?

Similar and Recommended are lists provided by TMDb API. I don't understand your question though - if the list comes from TMDb, how would it be possible that it comes from Trakt? 

The Trakt API doesn't provide lists of recommendations/similar items based upon another item.

You can see what API endpoints each provide here:
https://developers.themoviedb.org/3/getting-started/introduction
https://trakt.docs.apiary.io/#

>
>
> Trakt ID would allow me to link into addons to gain features like Trakt Manager and in certain instances ability to trigger Play action.

On latest versions I've actually added some trakt management functions. When you browse into the detailed menu for an item it should show additional options to add/remove from watchlist/history/collection.

I also added a while back some functions for playing items by using `?info=play&tmdb_id={tmdb_id}&type={type}`

Currently it will only play items in local library but I'm thinking about adding a hook to run a command (i.e. open another addon) if the item isn't in the library. Would be useful for opening items in Netflix / Youtube etc.

**Comment by skyfsza** [comment]
Thanks for adding the Trakt Manager, I think that actually covers 90% of the reason I was looking for the trakt_id. 

For playing items, I have found a workaround with an addon that supports TMDB ID instead of trakt id.

Thanks!
