### ISSUE TITLE
Fallback player

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#90]
Would it possible to provide a fallback player for movies and TV shows?
I'm planning on using the EmbyCon plugin to play videos directly from the Emby server without synchronising with the Kodi database like what the Emby for Kodi addon does (so no library integration). The idea would be to have a backup in case the video is not in the Emby server so it would then use another addon.

**Comment by jurialmunkey** [comment]
If the default player fails it shows a dialog to select another player
