### ISSUE TITLE
[BUG] updating when new episodes have came out

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#901]
### Describe the bug

TMDb helper does not refresh episodes on startup, so when a new episode comes out the new episode is not shown in the number of episodes to watch, and by extension is then not shown in Trakt to watch episodes. TMDb helper refreshes episodes after something has been watched, but not on startup.

### Steps To Reproduce

1. Close Kodi one day.
2. The next day when a new episode of a tv show comes out (rings of power today for example) TMDb helper will not show that there is a new episode available.
3. Play anything in TMDb and then it will refresh and show the episode.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
What list are you talking about? There's already an option to use the calendar for next episode lookups which deals with this issue

**Comment by ghost** [comment]
Hi jurial :)
It’s the “Your Next Episodes” list in the Trakt folder. This mirrors what is shown on the Trakt website/app for what new episodes are available to watch.

**Comment by jurialmunkey** [comment]
As I mentioned, there's already a setting to address this issue
Settings - Widgets -  Next episodes checks calendar
