### ISSUE TITLE
[BUG] Your Next Episodes Thumbnail Issue

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/plugin.video.themoviedb.helper#902]
### Describe the bug

In TMDB Helper "Your Next Episodes" list some Thumbnails for few TV Shows are showing up as default fanart instead of the particular episode thumbnail. For example, I noticed these for 2 TV Shows: "Birds of Prey" (2002) and "Thundercats" (2011). In some other video addons the episode thumbnails are showing correctly. See attached screenshots.

### Steps To Reproduce

Go to "Your Next Episodes" list. Check the thumbnails for the mentioned TV Shows.

### Debug log

https://paste.kodi.tv/iwigawabud

### Screenshots and Additional Info

In TMDB Helper:

![IMG20221008192404](https://user-images.githubusercontent.com/65297828/194711809-97954e73-93a2-474d-8a6a-581a2e7e1016.jpg)

![IMG20221008192419](https://user-images.githubusercontent.com/65297828/194711816-fdea431e-a39d-482f-93c7-b1c98078ad8e.jpg)

In other video addon:

![IMG20221008192655](https://user-images.githubusercontent.com/65297828/194711827-0667e791-5d43-446b-bcce-48217fd1c7df.jpg)

![IMG20221008192724](https://user-images.githubusercontent.com/65297828/194711840-49be4f9f-5cd2-437d-be51-60939fc1c574.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

I checked on TMDB website and I think that TMDB has removed the Episode thumbnails for those 2 TV Shows that I mentioned. However, I'm not able to understand that how the other addon is pulling those Episode thumbnails. Is it pulling them from Trakt? I guess you can advise better regarding this?

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Trakt doesn't supply any artwork via the API.

For Birds of Prey, that's just one of the standard fanart backdrops.
https://www.themoviedb.org/tv/1469-birds-of-prey/images/backdrops

For Thundercats, no idea. Possibly it was just cached before it was removed. Possibly that addon scrapes another source.

Either way, I only get episode thumbs from TMDb, so if it isn't on there then TMDbHelper won't get a thumb.

**Comment by AakashC2020** [comment]
> Trakt doesn't supply any artwork via the API.
> 
> For Birds of Prey, that's just one of the standard fanart backdrops. https://www.themoviedb.org/tv/1469-birds-of-prey/images/backdrops
> 
> For Thundercats, no idea. Possibly it was just cached before it was removed. Possibly that addon scrapes another source.
> 
> Either way, I only get episode thumbs from TMDb, so if it isn't on there then TMDbHelper won't get a thumb.

Hi @jurialmunkey,

Fine. Thanks for the information!

Thanks and Regards,
ShibajiCh.
