### ISSUE TITLE
[question] playmedia resume in cast info

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#904]
I wanted it to immediately play a movie that has already started without an additional context menu to ask if I want resume or play from beginning. I am currently using this command.
`RunScript(plugin.video.themoviedb.helper,close_dialog=1190,playmedia='$ESCINFO[ListItem.FileNameAndPath]')`
I tried with various variants of the `resume` function but it doesn't work. In fact, there is a variant to work, but to build the player first and then to play the movie, but I would prefer that play immediately for local content. Where am I going wrong and is it even possible to do it right now?

**Comment by jurialmunkey** [comment]
Nothing to do with TMDbHelper. The dialog asking to resume or play from the beginning is a Kodi builtin. You can change the behaviour in Kodi settings.

**Comment by matke-84** [comment]
Can it be set in the old script to use the playmedia function as in the new one?
`RunScript(plugin.video.themoviedb.helper,recommendations=onaction,window_id=1191,after=True,builtin='PlayMedia($ESCINFO[ListItem.FileNameAndPath],resume)')`
On this way i can then force the resume function.

**Comment by jurialmunkey** [comment]
Just close the dialog using the RunScript and do the play action as a separate onclick. If you need to delay it for an animation then use an alarmclock

**Comment by matke-84** [comment]
Thanks. ;-)
