### ISSUE TITLE
Backdrop issue

### ISSUE THREAD

**Issue by bassemhelal18** [jurialmunkey/plugin.video.themoviedb.helper#905]
I don't know where the problem is but I will try to explain in photo 
The backdrop fanart for English movies are working fine ![image](https://user-images.githubusercontent.com/77381611/195445152-a09dd7a1-0d10-490d-a959-bfe2a1739827.jpeg)
![image](https://user-images.githubusercontent.com/77381611/195445239-bc6a2d75-c752-4bb1-a9eb-c558fd35b8c5.jpeg)
But in Arabic movies fanart doesn't available when the movie is written in Arabic
![image](https://user-images.githubusercontent.com/77381611/195445456-fd5805e2-0359-4c0d-8d63-984123b26782.jpeg)
![image](https://user-images.githubusercontent.com/77381611/195445596-ad93b495-e5a8-4690-8870-73c6e321d414.jpeg)
And when I searched for the same movie in tmdb the fanart available and the movie name in english 
![image](https://user-images.githubusercontent.com/77381611/195445955-43d42d63-4ce9-4eeb-a876-ee6432905649.jpeg)
![image](https://user-images.githubusercontent.com/77381611/195445830-599815d1-bf95-483c-81a4-4124c6f0f9b2.jpeg)
![image](https://user-images.githubusercontent.com/77381611/195445922-3a0869c1-2796-47d0-8619-321357217877.jpeg)
Hope that i have explained the issue 😅

**Comment by jurialmunkey** [comment]
Please use the bug report template if you wish to report a bug. It is important that people use the correct templates so that I can track issues properly
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBUG%5D+Description
