### ISSUE TITLE
Backdrop issue

### ISSUE THREAD

**Issue by bassemhelal18** [jurialmunkey/plugin.video.themoviedb.helper#906]
### Describe the bug

I don't know where the problem is but I will try to explain in photo 
The backdrop fanart for English movies are working fine ![image](https://user-images.githubusercontent.com/77381611/195445152-a09dd7a1-0d10-490d-a959-bfe2a1739827.jpeg)
![image](https://user-images.githubusercontent.com/77381611/195445239-bc6a2d75-c752-4bb1-a9eb-c558fd35b8c5.jpeg)
But in Arabic movies fanart doesn't available when the movie is written in Arabic
![image](https://user-images.githubusercontent.com/77381611/195445456-fd5805e2-0359-4c0d-8d63-984123b26782.jpeg)
![image](https://user-images.githubusercontent.com/77381611/195445596-ad93b495-e5a8-4690-8870-73c6e321d414.jpeg)
And when I searched for the same movie in tmdb the fanart available and the movie name in english 
![image](https://user-images.githubusercontent.com/77381611/195445955-43d42d63-4ce9-4eeb-a876-ee6432905649.jpeg)
![image](https://user-images.githubusercontent.com/77381611/195445830-599815d1-bf95-483c-81a4-4124c6f0f9b2.jpeg)
![image](https://user-images.githubusercontent.com/77381611/195445922-3a0869c1-2796-47d0-8619-321357217877.jpeg)
Hope that i have explained the issue 😅

### Steps To Reproduce

1-

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
What are your TMDbHelper settings in these sections:
API Keys > Fanart.TV
General > Region / Language

**Comment by jurialmunkey** [comment]
Also please fill out the "Steps to reproduce" section. What add-on / library etc. do I use? What section do I go into? What do I click on to make this happen?

**Comment by jurialmunkey** [comment]
Works fine for me...

![Honeyview_screenshot00176](https://user-images.githubusercontent.com/4618719/195529233-fb4b7e54-e63d-4c64-9c2f-d76c60bf1460.jpg)

**Comment by bassemhelal18** [comment]
Am using matrix zombib.GitHub.io  
I tried both language arabic and English and got the same

**Comment by jurialmunkey** [comment]
Exact steps to reproduce please. Artwork for Arabic titles works fine for me.

If you're talking about artwork in another add-on, then you will need to ask the author of that add-on why they don't have artwork.

**Comment by bassemhelal18** [comment]
Addon Matrix (zombib.github.io)
Go to movies
Go to Arabic movies 
Choose Akwam 
If you choose any movie from the list there is no backdrop

**Comment by bassemhelal18** [comment]
The artwork is available for English movies in same addon and

**Comment by bassemhelal18** [comment]
I think it's working fine if it's writing in english ![image](https://user-images.githubusercontent.com/77381611/195532420-3ce5631e-a20d-4490-9f8d-3d53e0ace162.jpeg) 
Even if you searched for it in arabic words it will appear with the english name

**Comment by jurialmunkey** [comment]
>   Even if you searched for it in arabic words it will appear with the english name

 No that is just the search term. The title is in Arabic. TMDbHelper is working fine. I can't fix another add-on for you. Ask the addon author why their addon doesn't supply artwork

Works fine in TMDbHelper regardless of whether search or title is in English or Arabic

![Honeyview_screenshot00177](https://user-images.githubusercontent.com/4618719/195536280-b2c2c08a-3feb-4acd-8845-e02a38aa3ce6.jpg)

**Comment by bassemhelal18** [comment]
Last AH2 update fixed the problem thank you so much 🙏🙏
