### ISSUE TITLE
[Feature] Add/remove from watchlist button

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#907]
### Describe the feature that you'd like

I would like to tmdb helper have option add/remove button from Trakt watchlist separated from trakt context menu which already exists. This is one of the last options I need to fully integrate my skin with tmdb helper. I would greatly appreciate for this option.

### Why is this feature needed? What problem does it solve?

Quick way to add something to trakt watch list. It bypasses the part with opening the context menu, and I believe that many skiners will use this. Netflix has the same option.

### Screenshots and Additional Info

This is how it works in my skin (titan bingie mod) with local library and bingie helper. It would be great if there was a possibility to work like this with tmdb helper and trakt.

https://user-images.githubusercontent.com/74268331/194700928-2fc44e8d-bf99-460e-bf8b-6714024fa5ef.mp4

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Creating script endpoints for add and remove watchlist is easy. 
The difficult part will be how you determine which one to run in your skin.

TMDbHelper hides these options behind a submenu to give it a chance to sync the data first and determine whether it needs to display add or remove. You won't know the sync status (at least not without syncing excessively) so you're left with two options:

1. I create separate add and remove endpoints. Your skin displays two buttons: "Add to Watchlist" and "Remove from Watchlist"
2. I create a single endpoint which decides what to do for you. Your skin displays a single button: "Add/Remove Watchlist"

You won't be able to achieve exactly what is in your video where the icon/label adapt to the watchlist status.

**Comment by matke-84** [comment]
I actually think the bingie helper has one button too.
https://github.com/matke-84/script.bingie.helper
The button status change on the video is only visible if movie/tvshow was added to my list. However, when it is removed from the list, it is not actually visible immediately, only when I exit from dialog info, the status of button change.

Maybe one button is enough, considering that the tmdb helper certainly gives a notification about the status change.

![add](https://user-images.githubusercontent.com/74268331/195527810-57ef4f73-99e8-4405-a7e2-d5d708419241.png)
![remove](https://user-images.githubusercontent.com/74268331/195527847-f2c2c25c-3365-4ff4-9c55-6ae9adf7330c.png)

Here's what those two buttons look like in my skin.
```
<!-- add to my list -->
        <control type="radiobutton" id="56">
		<visible>!$EXP[IsEpisodeDBType]</visible>
                <visible>Skin.HasSetting(videoinfo_button_mylist)</visible>
                 <visible>!String.IsEmpty(ListItem.DBID) + [$EXP[IsTvShowDBTypeNoFallback] | $EXP[IsMovieDBTypeNoFallback]]</visible>
		<visible>[!String.Contains(ListItem.Tag, mylist) + String.IsEmpty(Window(Home).Property(IsInMyList))] | !String.IsEqual(Window(Home).Property(IsInMyList), ListItem.DBID)</visible>
		<include>Bingie_InfoDialog_Button_Default_Defs</include>
                <include content="Bingie_InfoDialog_Button_Texture">
                        <param name="radiotexture" value="dialogs/videoinfo/info/plus.png"/>
                </include>
                <label>$LOCALIZE[31869]</label>
                <radioposx>17</radioposx>
                <radiowidth>22</radiowidth>
                <radioheight>22</radioheight>
                <onclick>RunScript(script.bingie.helper,action=togglemylist)</onclick>
        </control>
<!-- remove from my list -->
       <control type="radiobutton" id="57">
       <visible>!$EXP[IsEpisodeDBType]</visible>
       <visible>Skin.HasSetting(videoinfo_button_mylist)</visible>
       <visible>!String.IsEmpty(ListItem.DBID) + [$EXP[IsTvShowDBTypeNoFallback] | $EXP[IsMovieDBTypeNoFallback]]</visible>
       <visible>[String.Contains(ListItem.Tag, mylist) + String.IsEmpty(Window(Home).Property(IsInMyList))] | String.IsEqual(Window(Home).Property(IsInMyList), ListItem.DBID)</visible>
	<include>Bingie_InfoDialog_Button_Default_Defs</include>
               <include content="Bingie_InfoDialog_Button_Texture">
                <param name="radiotexture" value="dialogs/videoinfo/info/minus.png"/>
        </include>
        <label>$LOCALIZE[31870]</label>
        <radioposx>17</radioposx>
        <radiowidth>22</radiowidth>
         <radioheight>22</radioheight>
         <onclick>RunScript(script.bingie.helper,action=togglemylist)</onclick>
   </control>
```

**Comment by matke-84** [comment]
Or I don't know if there is a possibility if two buttons are placed separately, that the button add to watch list is displayed when the movie is not in the list and remove from watch list if it is in the list. To make some condition for that.

**Comment by jurialmunkey** [comment]
> Or I don't know if there is a possibility if two buttons are placed separately, that the button add to watch list is displayed when the movie is not in the list and remove from watch list if it is in the list. To make some condition for that.

I just explained why that isn't possible.

You need to make a choice between whether you want two buttons that will both display at the same time or if you want a generic "watchlist" button that makes the decision for you.

You cannot check the status of the item in the watchlist because the watch list needs to sync first which means you need to call the script first which you can only do if you click the button. You can't know the watchlist status until after the script runs.

**Comment by matke-84** [comment]
Well, I don't know, I think maybe one button (add/remove) is better in that case. What do you think?

**Comment by jurialmunkey** [comment]
Latest allows you to specify `sync_type` which will be the equivalent of choosing the option from the submenu

`RunScript(plugin.video.themoviedb.helper,sync_trakt,tmdb_type=movie,tmdb_id=348,sync_type=watchlist)`

^ That will add/remove the movie Alien from the watchlist. Standard query params can also be applied.

Options for sync_type
| key | description |
| :--- | :--- |
| `watched` | mark as watched |
| `unwatched` | mark as unwatched |
| `collection` | add/remove from collection |
| `watchlist` | add/remove from watchlist |
| `recommendations` | add/remove from your recommendations |
| `userlist` | add to a custom list you own |
| `progress` | reset progress mark to 0 |
| `comments` | open Trakt comments for item |

**Comment by matke-84** [comment]
Thank you so so much!!! And it's fantastic that you also gave the possibility of an individual menu for other trakt options.
