### ISSUE TITLE
[BUG] Trailers inside recommendation window

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#908]
### Describe the bug

This is more of a question, but since there is no more empty form, I had to do it this way. I'm trying to understand how the trailers in the recommended script work because I have one problem. I set it to play my trailers inside the script, like in ah2. The first thing I noticed was that there were no OSD controls and menus.But that's not the main problem. A very strange thing is happening on Android. When I enter the script and play the trailer everything works fine.But if I enter the script and first open some other content (open the info dialog of the movie I selected)then I go back, when I try to play the trailer I get a black screen and I hear sound.Now if I go in kodi  settings and turn off hardware acceleration the trailers work as they should.Ok thought android problem.I try the same thing with ah2, and then I see that in ah2 everything works as it should without turning off hardware acceleration.How is it possible?I use trailers in my skin in many places (on home, dialog info, before in extended script) without any problems, only this happens to me in tmdb helper recommended script.I'm trying to figure out where video is coming from without the osd controls (this is not big problem, I'll insert the controls but it's strange) and the menu and why it works in my skin when hardware acceleration is turned off but not when it's turned on and what did you do in ah2 differently to make it work without problems?Sorry for the long post and thanks in advance for your reply.

### Steps To Reproduce

/

### Debug log

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I'm having a hard time following this question. Are you asking why a skin "videowindow" control is not displaying video when hardware acceleration is enabled? Sounds out of the scope of TMDbHelper.

**Comment by jurialmunkey** [comment]
https://kodi.wiki/view/Video_Control

**Comment by matke-84** [comment]
No. I have no problem with "videowindow". I use it in many places in the skin with no problem. Only in the recommendation script it doesn't work as it should, and only in android. When you have time, read what I wrote, I know it's a long post, but it's really a strange situation. I'm afraid that there might be problems with other skins that would like to use this tmdb helper function (recommendation script).

**Comment by jurialmunkey** [comment]
Then what is your issue? To me it sounds like you are saying that the videowindow control is not displaying video. 

I don't see what that has to do with TMDbHelper other than by coincidence that you are in the recommendations window. TMDbHelper doesn't render video playback. Kodi renders video playback.

**Comment by matke-84** [comment]
Ok, videowindow control is not displaying video but in the recommendation script and in the case as I mentioned. I didn't say that this is a problem with the tmdb helper, I asked how it works to play a trailer under a script. I see that something is different, because there is no osd menu. I also used it in the old extended info script and there the trailer behaved like in any other window. I'm just trying to figure out where the problem is.

**Comment by jurialmunkey** [comment]
I suggest you read what the `,1` flag on the PlayMedia command is doing
https://kodi.wiki/view/List_of_built-in_functions#Player_built-in.27s

A "videowindow" control is just a normal skin object like an image control. If a videowindow control is visible and a video is playing, then Kodi will render the the videooutput to it. It is NOT the VideoFullScreen.xml window that has VideoOSD.xml

There are plenty of skin based reasons why Kodi can't get your hardware to render a videowindow control that you've defined. You might have two videowindow controls visible and your hardware can only deal with rendering one. You might have an animation that your hardware doesn't like. You might have a problem with your skin visibility logic. I can't diagnose skin code that I can't even see.

**Comment by matke-84** [comment]
Ok. I have to deal with this a bit. I am closing the issue because this is not a bug but a question. If I have someone extra, I hope you will have time to answer me.
