### ISSUE TITLE
[BUG] Close recommandation dialog

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#912]
### Describe the bug

I'm not sure if I understood this part:
Wiki, Recommendation dialog
If you need to close the window manager to perform an action, remember to run the recommendations=onaction command.
```
<onclick>RunScript(plugin.video.themoviedb.helper,recommendations=onaction)</onclick>
<onclick>YOUR ONCLICK COMMAND GOES HERE</onclick>
```
If I use this with custom content (e.g. youtube) i am getting an error.
Outside of the recommandation dialog I use e.g.
`RunScript(plugin.video.themoviedb.helper,recommendations=onaction,window_id=1191,after=True,builtin='PlayMedia($ESCINFO[ListItem.FileNameAndPath],resume)')`
and it works.

### Steps To Reproduce

/

### Debug log

```
2022-10-18 12:04:10.605 T:16368   DEBUG <general>: [plugin.video.themoviedb.helper]
                                                   lib.script.router - route_taken	recommendations
2022-10-18 12:04:10.670 T:16368   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: __init__() missing 1 required positional argument: 'window_id'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\script.py", line 7, in <module>
                                                       Script(*sys.argv[1:]).router()
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\script\router.py", line 120, in router
                                                       return self.routing_table[route_taken](**self.params)
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\script\router.py", line 88, in <lambda>
                                                       lambda **kwargs: importmodule('resources.lib.window.recommendations', 'WindowRecommendationsManager')(**kwargs).router(),
                                                   TypeError: __init__() missing 1 required positional argument: 'window_id'
                                                   -->End of Python script error report<--
```

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
The error tells you what you're doing wrong... You have to specify a window_id to tell it what window to close.

**Comment by matke-84** [comment]
If you think like this, then it doesn't work either. There is no error but it does not close the dialog.
`<onclick>RunScript(plugin.video.themoviedb.helper,recommendations=onaction,window_id=1191)</onclick>`

**Comment by matke-84** [comment]
Any solution for this?

**Comment by jurialmunkey** [comment]
Have you tried closing the recommendations dialog? 
`<onclick>Close</onclick>`

The onaction just closes the window manager. The wiki never said anything about it closing the recommendations dialog. It closes the info dialog, the custom window, and the window manager.

**Comment by matke-84** [comment]
Yes, I use the `close` function from the beginning. But it's not the best solution because it closes the recommendation dialog first and then with a delay of one second the info dialog. I really think that we need some function that will close the entire recommendation dialog. Do you want me to write a new request for that?

**Comment by jurialmunkey** [comment]
You can bundle it with onaction as the builtin

`<onclick>Runscript(plugin.video.themoviedb.helper,recommendations=onaction,builtin=Action(Close),window_id=1191)</onclick>`

**Comment by matke-84** [comment]
That's it. Thanks. Maybe you should put this on the wiki too, surely someone will need it.
