### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by SirRickie** [jurialmunkey/plugin.video.themoviedb.helper#913]
### Describe the bug

Since a while, every start gives me this error (see screenshot). Is there anything I can do ? Tnx.

### Steps To Reproduce

1. Start Kodi
2. Error appears

### Screenshots and Additional Info

![Schermopname (45)](https://user-images.githubusercontent.com/60318531/196664908-7b5f2243-2f7f-4988-824f-e19455e27425.png)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Full log please

**Comment by SirRickie** [comment]
Enclosed full log.
https://paste.kodi.tv/idebiveliw.kodi
