### ISSUE TITLE
[BUG] get_directory runtime error

### ISSUE THREAD

**Issue by rtuRgALp** [jurialmunkey/plugin.video.themoviedb.helper#915]
### Describe the bug

Every now and then I get an error from TMDBH. I use Arctic Horizon 2 and Fen. I cannot consistently reproduce the issue, but it happens either when I first start Kodi or after I finish playing content. 

### Steps To Reproduce

1. Open Kodi
2. Observe TMDBH error

### Debug log

https://paste.kodi.tv/yipuvunohe.kodi

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
What is the issue? What problem is this "error" causing or are you just saying you saw something in the log?

**Comment by rtuRgALp** [comment]
So it’s not preventing anything as far as I can tell. I can still use Kodi normally. It’s just an error that pops up in the UI and shows up in the logs.

**Comment by jurialmunkey** [comment]
Sorry I can't see what error you're referring to. What does the error say?

**Comment by rtuRgALp** [comment]
I wonder if the log was truncated. 

I unfortunately cleared the error highlighted by OpenWizard. 

I have been unable to reproduce. I will close this issue and re-open it if it comes up again.

I feel like these could be transient errors after first configuring the AH2 skin with widget shortcuts to Fen. Seems to clear up after force closing Kodi and restarting my box (Apple TV 4K 2nd Gen).

**Comment by rtuRgALp** [comment]
Ok it happened again when opening Kodi:

ERROR NUMBER 1:
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'RuntimeError'>
Error Contents: can't start new thread
Traceback (most recent call last):
File "/addons/plugin.video. themoviedb.helper/plugin.py", line 7, in ‹module>
Router(int(sys.arg[1]), sys.argv(2][1:J.run0
File "/addons/plugin.video.themoviedb.helper/resources/lib/items/router.py", line 46, in run self.get_directory
File"/addons/plugin.video.themoviedb.helper/resources/lib/items/router.py", line 39, in get_directory return container. get_directory (items_only, build_items)
File */addons/plugin.video. themoviedb.helper/resources/lib/items/container.py", line 266, in get_directory
items = self.build_items(items)
File *addons/plugin.video. themoviedb.helper/resources/lib/items/container.py", line 191, in build_items with ParallelThread(all_listitems, self._make_item) as pt:
File */addons/plugin.video. themovied.helper/resources/lib/addon/thread.py", line 66, in .
init
self._pool n].start0
File
"/private/var/containers/Bundle/Application/9989AF1C-6FA4-40AB-BCAC-DA74F43375AE/Kodi.app/Frameworks/lib/python3.8/thread
line 852, in start
_start_new_thread(self. _bootstrap, 0)
RuntimeError: can't start new thread

**Comment by jurialmunkey** [comment]
Interesting. Haven't seen that one before.

You should be able to fix it by reducing the max number of threads in tmdbhelper expert settings.

**Comment by rtuRgALp** [comment]
I'll give it a shot - thank you!
