### ISSUE TITLE
[Feature] Increase fanart quality from TMDB to w1920 in High Quality mode

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/plugin.video.themoviedb.helper#916]
### Describe the feature that you'd like

Increase fanart quality from TMDB to w1920 in High Quality mode

### Why is this feature needed? What problem does it solve?

If I'm not mistaken these are the resolutions:

High
Posters = w500 from TMDb
Thumbs = w1280 from TMDb
Fanart = w1920 from FanartTV and fallback to w1280 from TMDb

When a fanart is not available on FanartTV and It takes from TMDB, the change in quality is very noticeable.
This is especially noticeable in the full screen widget.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Not an option in the api sadly, otherwise it would be the setting

The options provided  by the api for backdrops are

w300
w780
w1280
original

Original is often 4k (or even higher) so not suitable for a reduced quality setting.

**Comment by jurialmunkey** [comment]
If you want full 1080p or higher artwork you must choose original as the quality setting. It is the only option the api provides for that size artwork.

**Comment by daviddia5** [comment]
Oh, what a pity.
My problem is that when I put it in Original, the posters come out without text (I already put it in another post).
But nothing happens, that's fine for me. Thank you!

**Comment by jurialmunkey** [comment]
That shouldn't happen. The size of artwork shouldn't have any impact on the artwork displayed. You probably just have old artwork cached at that quality and need to refresh the item details cache

**Comment by daviddia5** [comment]
I have cleared cache and still the same. If you want you can do the test:
Choose Spanish (Spain). Switch between Original and High artwork (clearing cache and temporary files) and check out the posters.

**Comment by daviddia5** [comment]
In Original, it takes the FanartTV posters (not TMDb) and those that are not marked as Spanish (es) it puts them as language 00 (no text).

In High it takes the TMDb posters and they are correct.

**Comment by jurialmunkey** [comment]
Ah sorry didn't realise you were talking about posters from fanarttv. Yeah that's normal then.

Fanarttv doesn't provide any image resizing options, so when you reduce the quality from original then tmdbhelper will pick posters from TMDb so that it can control the size. 

On the "high" setting, backdrops still come from fanarttv first because that's the only way to get 1080p. When you drop it lower then fanart comes from TMDb because the size can be lowered further.
