### ISSUE TITLE
please make an emby next gen player

### ISSUE THREAD

**Issue by daveftw84** [jurialmunkey/plugin.video.themoviedb.helper#917]
### Describe the feature that you'd like

would love to see a player for emby next gen

### Why is this feature needed? What problem does it solve?

embycon has trouble with random freezing. sometimes playback fails first or second attempt but emby next gen has improvemnents made to prevent this. playback is almost instant when using emby next gen. i love your addon to make widgets and menus on the skin and have a huge emby library that i dont want to have to sync.  

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
I don't use Emby next gen so I can't make a player for it.

There is extensive documentation in the wiki about how to make players. There are also template player configuration options in the settings that help to build a basic player via the GUI.

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

If you get stuck I can try to help, but I can't make the player for you as I don't use that addon.

**Comment by daveftw84** [comment]
everytime i try to use create a player. it ends up not saving the player
created.
