### ISSUE TITLE
[Feature] Add Trakt popular lists as default as well as watched lists

### ISSUE THREAD

**Issue by HastyBasher** [jurialmunkey/plugin.video.themoviedb.helper#918]
### Describe the feature that you'd like

Please make it so on the part where "Watched Movies" and "Watched TV Shows"  pops up when you click update from Trakt lists that the big lists like "Top 250" and "Released this week" and other stuff show there by default. 

### Why is this feature needed? What problem does it solve?

TMDB Helper isnt that great for what I need and for skins like bingie as you have to make your own lists where as if we could make it so the site made lists movies and shows were added to library it would be very useful. Currently I don't believe there is a way to add the lists I mentioned to your library. 

### Steps to reproduce.

Go to Settings, Add-Ons, TMDB Helper, Library, Update From Trakt Lists. This is where the big lists should be as default.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Any list that you "like"  will show as selectable

Like list on Trakt website:

![image](https://user-images.githubusercontent.com/4618719/197327153-d76d911d-ca94-4765-a08f-470839df5a71.png)


Select the list to monitor:

![image](https://user-images.githubusercontent.com/4618719/197327193-ba181ecc-f6de-4bf1-9184-c5b7288a314d.png)
