### ISSUE TITLE
Missing/Invalid TMDB API Key

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#92]
Getting this message on kodi boot, theres nowhere in the settings to enter  TMDB API key? 
Pic: 
![Screenshot_1](https://user-images.githubusercontent.com/45118866/74442876-458d8f00-4e40-11ea-8d92-a2cd00a4e78f.png)

**Comment by jurialmunkey** [comment]
Debug log please

**Comment by JayDee696969** [comment]
Ok, cleared TMDH addon data and resolved issue. Thanks!
