### ISSUE TITLE
[Feature] Trakt list view types

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#920]
### Describe the feature that you'd like

Is it possible to have a set view type for Trakt lists? At the minute they use the movies viewtype.

### Why is this feature needed? What problem does it solve?

Trakt lists that are used for tv shows have the view type as whatever the movie view type is set to

### Steps to reproduce.

Go to Trakt list that has tv shows, the view type is the same as the movie view type, changing the list view type also changes the movies view type.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
The content type of a trakt list is determined by the number of movies and tvshows it has - more movies and it becomes a movies content, more tvshows and it becomes a tvshows content type.

Or at least that is how it is meant to work. If it is not doing that, please provide a sample list to test.

**Comment by ghost** [comment]
Hi jurial :) no it is not currently doing that, I noticed it on my personal list which only has tv shows. A list you can use as an example is in Trakt > popular lists > IMDB top rated tv shows. The view type is whatever has been selected for movies

**Comment by jurialmunkey** [comment]
Ah yep you're right. Accidentally introduced a dumb typo at some stage and then never noticed because I use the same viewtype for movies and tv in my main setup.

**Comment by ghost** [comment]
Haha no problem man. Legend as always!
