### ISSUE TITLE
[Feature] Cast.X.Title

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#922]
### Describe the feature that you'd like

Is there any chance we can get this detailed item?

### Why is this feature needed? What problem does it solve?

My idea is that when the movie/tv show details are displayed next to the actor name, there is one of his movies that he is known for.

### Steps to reproduce.

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Added v5.0.21

ListItem.Property({movie|tvshow}.{cast|crew}.{x}.{property})

e.g. 
ListItem.Property(movie.cast.1.title)
ListItem.Property(tvshow.crew.1.title)

General properties available
title, tmdb_id, plot, rating, votes, premiered, poster, fanart

Cast specific properties:
character

Crew specific properties:
department, job

TV specific properties:
episodes

Must refresh item cache to see changes to existing items.

**Comment by matke-84** [comment]
I don't think you understood me. I don't need this property for person secific. I need it as a general property for movies and tv shows, as I wrote above, like you have:
`ListItem.Property(Cast.X.Name)`
`ListItem.Property(Cast.X.Role)`
`ListItem.Property(Cast.X.Thumb)`

![qwe](https://user-images.githubusercontent.com/74268331/197953940-b3cb8f37-0847-4dce-ab90-a40bd47cad2a.png)

**Comment by jurialmunkey** [comment]
You can already get those.

**Comment by matke-84** [comment]
How? I don't see that it has a title.

**Comment by jurialmunkey** [comment]
plugin://plugin.video.themoviedb.helper?info=stars_in_movies&amp;type=person&amp;query=$INFO[ListItem.Property(Cast.X.Name)]

**Comment by matke-84** [comment]
Wait. Do I understand correctly? I need to create a hidden list and extract the name from it?

**Comment by jurialmunkey** [comment]
Yes. You need to get this information using a hidden list.

This information does not come with the cast list api call. You can see the api docs to see what data comes with each call
https://developers.themoviedb.org/3/movies/get-movie-credits

Otherwise what you're asking for is hundreds of requests per movie.

**Comment by matke-84** [comment]
OK. I thought I could get the name of the actor movie as I get the role from the actor
`$INFO[Container(99950).ListItem.Property(Cast.1.Role)]`
It would be great if an regular property could do it, since I don't like so much hidden lists, but since that's the situation, nothing then.

**Comment by jurialmunkey** [comment]
Like I said - look at the api data scheme. That data is not provided with the movie credits api call. 

If the data is not available, it is not available. In order to retrieve it requires a separate request. That means hundreds of requests for a single movie because you'd need to get four calls PER cast member (cast movies, cast tv, crew movies, crew tv). If you had 50 cast members then TMDbHelper would be making 200 requests for a single movie just in the off chance you want to use this data.

**Comment by matke-84** [comment]
I understood everything. That's why I said "since that's the situation"... :-)

So that I would not open a new issue for the question if it is not a problem for you to answer two short questions.
1. `ListItem.Property(Next_Aired.Short) ` - does this use Kodi's display system (26. Oct), Can I somehow use it to write as in the long name (Wednesday, 26. October), full month without day (26. October)?
2. I would like some content to be visible to me if the tmdb or imdb rating is higher than 8.0. I tried with
`Integer.IsGreater` but is not working. I use integer for RT, it works there. Any chance for tmdb and imdb?

**Comment by jurialmunkey** [comment]
1. https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor#special-additional-properties
2. All ListItem.Property() values are strings. Any integer comparisons involve Kodi type converting from string to integer. Numbers with decimal places are floats not integers. It's the same as wondering why `Integer.IsEqual(Eighty,80)` doesn't work.
