### ISSUE TITLE
[BUG] clearlogo NAS cache

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#923]
### Describe the bug

Since a recent update (unsure which update sorry) the TMDb helper feature to set image cache to NAS has became bugged. Temp files are being saved to the NAS crop folder but it is then not saving the cropped files, meaning the clearlogos are uncropped and small. (See screenshot)

### Steps To Reproduce

Set image cache to NAS. TMDb helper will then start saving the temp clearlogo files to the NAS but will not save the full cropped files.

### Screenshots and Additional Info

![IMG_4536](https://user-images.githubusercontent.com/114344593/198108128-bc413362-e931-4404-9403-d78f67addb36.jpeg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by ambulancePilot** [comment]
I had the same issue when trying to move the blur and cropped folders. Are you using some variant of Android?

The only solution was to move the entire userdata folder to the external storage (in my case it was a locally connected USB drive). Using a NAS for this purpose might negatively impact your overall speed and fluidity so I wouldn't recommend it.

**Comment by ghost** [comment]
Hey :)
Yeah using android on Sony TV. This was working on a previous version but then stopped working. Yeah not fully confident in moving the entire folder to NAS so happy to wait to see if this may get resolved in the future.

**Comment by jurialmunkey** [comment]
Resolved by https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/8421944625470028f24a0734647df04fefaf0a88
