### ISSUE TITLE
[Feature] Order by year

### ISSUE THREAD

**Issue by The-cpu-max** [jurialmunkey/plugin.video.themoviedb.helper#924]
### Describe the feature that you'd like

Inside the menu, I click on "themoviedb" secession and after that on   "ALL TV NETWORK" and then I choose a production
And for some reason, all the series are messed up - new series with really old series
I would appreciate it if you added an option to sort by year of immigration
Just like on the website

https://www.themoviedb.org/network/363-hot3?sort_by=first_air_date.desc
https://www.themoviedb.org/network/644-yes?sort_by=first_air_date.desc

### Why is this feature needed? What problem does it solve?

Arrangement by years
will make order

### Screenshots and Additional Info

![image](https://user-images.githubusercontent.com/102416233/198843727-531f0872-1fca-4d15-a1b1-c6f68a3352b9.png)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Use the discover section. You can set whatever rules you like for sorting.
