### ISSUE TITLE
[Feature] Without Original Language

### ISSUE THREAD

**Issue by sharpordie** [jurialmunkey/plugin.video.themoviedb.helper#926]
### Describe the feature that you'd like

I would like to have the opposite of With Original Language aka Without Original Language as Rule in Discover TV shows.

### Why is this feature needed? What problem does it solve?

I would like to get all the Cartoons (Animation TV shows) without the Japanese Anime.

Here is the rules to get all Japanese Animation TV shows:

- With Genre Animation
- With Original Language: Japanese

But I didn't find how to do the opposite.
I think a Without Original Language rule could do it.

### Screenshots and Additional Info

![](https://user-images.githubusercontent.com/72373746/198882280-07beeb01-0b61-4362-bfb2-c44a5a86999f.png)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Not possible. It isn't an option provided by the api
https://developers.themoviedb.org/3/discover/tv-discover

However, you can do this a different way by using a without_keyword rule
```
with_genre = Animation
without_keyword = Anime
```

It isn't perfect but will filter out most of them.
