### ISSUE TITLE
[Feature] Add an option to refresh Trakt cache every time Kodi starts

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/plugin.video.themoviedb.helper#928]
### Describe the feature that you'd like

Add an option to refresh Trakt cache every time Kodi starts.

### Why is this feature needed? What problem does it solve?

My home widgets, and I think a lot of people's, are the Trakt trending widgets.
I think that it is automatically deleted every 24 hours, but I do it manually often because the information is constantly changing.
I think an option to do it automatically every time Kodi starts would be very useful. Thanks.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Sorry this won't be added as it would require rewriting how the cache works.

Trending etc lists are cached for 24hrs to reduce traffic to Trakt. Whilst the lists might change slightly, I think it is fairly excessive to force them to update more frequently. Given how many users of TMDbhelper there are, this would massively increase the amount of traffic from the plugin
