### ISSUE TITLE
[Feature] Trakt ~ Your In-Progress Combined (Movies + Episodes)

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/plugin.video.themoviedb.helper#929]
### Describe the feature that you'd like

Your In-Progress Combined (Movies + Episodes).
I don't know if it would be possible but it would be very useful.

### Why is this feature needed? What problem does it solve?

You could have your movie and episode progress in the same widget. Like Google TV, Netflix etc.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by ambulancePilot** [comment]
I too think this is a great feature request. I've got two widgets for those but each one only ever has 2 or 3 items in it at once. It would make a lot more sense to have that as one widget. Using things like autowidget or superfavourites to accomplish this is just janky and doesn't have the same feel.

**Comment by jurialmunkey** [comment]
You can achieve this using SkinVariables filter feature which allows you to combine multiple lists together.
