### ISSUE TITLE
Add fanart back to menus

### ISSUE THREAD

**Issue by Tonkapug** [jurialmunkey/plugin.video.themoviedb.helper#934]
### Describe the feature that you'd like

It appears a few updates back the fanart is no longer being displayed in menus. Is it possible to add the fanart back?

### Why is this feature needed? What problem does it solve?

Visually pleasing

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
What do you mean by "menus"? Fanart for what?

**Comment by Tonkapug** [comment]
> What do you mean by "menus"? Fanart for what?

In previous releases, the fanart included with the addon (fanart.jpg located in plugin.video.themoviedb.helper directory) was visible throughout the addon's menus.
