### ISSUE TITLE
The dependency on script.module.addon.signals version 0.0.6 could not be satisfied

### ISSUE THREAD

**Issue by Has3n** [jurialmunkey/plugin.video.themoviedb.helper#935]
### Describe the bug

A few weeks ago this error message started showing whenever I launched Kodi. I have tried to update TMdb helper, but only got same error message. Then I deinstalled and tried to install again, but it won’t, same error message. I had to check that I have newest Version installed below, but that’s obviously not true. What’s wrong? How can I reinstall and use TMdb helper?

thanks:)

https://paste.kodi.tv/qoxobukiyu.kodi

### Steps To Reproduce

Well, as described…installing won’t work, so no steps:(

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I have you tried installing the missing module?

Also check that you didn't disable it.

It is a standard module in the official repo so there shouldn't be any issue with installing that module unless you have disabled it.

**Comment by Has3n** [comment]
Oh, no I haven’t tried that yet. Didn’t know that it might have been caused by this. So I need to find out how to do that. Will try, thanks.
