### ISSUE TITLE
[BUG] Changing artworks doesn't work in hubs

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#936]
### Describe the bug

As the title says, changing the artwork is only possible in tmdb helper itself, but not in the hubs.
This worked fine until some version and now it doesn't work. I tried version 4.7.35 works the normally. Can you check what this is about?

### Steps To Reproduce

Open chose artwork in hubs
I change any artwork
No change happens

### Debug log

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by matke-84** [comment]
The last working version is 4.9.8.

**Comment by matke-84** [comment]
I hope this will help you a little.
I'd say it has something to do with these changes.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/d5b90d69b2f4c09827ee1783fa270726cdc868ad

**Comment by jurialmunkey** [comment]
What do you mean by "hubs"?

**Comment by matke-84** [comment]
Some skins, such as titan bingie mod, have hubs, which behave like a home screen only with other content (categories hub, my list hub...), each hub can have more widgets, different look...

**Comment by jurialmunkey** [comment]
How are you changing the artwork?

**Comment by jurialmunkey** [comment]
You probably just need to reload the list. The artwork won't change until you reload the list.

If you want TMDbHelper to reload lists for you when a change is made then you need to add the reload param. It will add this param automatically for skinshortcuts but if you have hard-coded lists in the skin you need to add it yourself.

`&amp;reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]`

**Comment by matke-84** [comment]
Skins based on the original titan skin, placing widgets in hubs works in a slightly different way.
When you want to insert a widget into the hub, you have to unlock the hub and then insert it by opening a menu like when you insert a widget using the skin shortcut. So I can't insert a "refresh widget" (I can for some widgets that I have defined in advance, but that is a small number) and it doesn't automatically refresh the widget like in the skin shortcut.
That's why I need the tmdb helper to do the widget refresh itself, as before version 4.10.0.

**Comment by jurialmunkey** [comment]
The old method was a hack that reloaded *all* widgets by forcing a library update. I'm not returning to that method as it is poor.

I'm sure you can figure out a way in the skin to add the required param.

**Comment by matke-84** [comment]
OK. You won't go back to the old way, your addon your decision. But considering that I did the integration of the titan bingie mod skin with the tmdb helper, I need you to tell me, considering that I use the button in the info dialog to change the artworks, is there a possibility when I click on the button to force a widget refresh?

**Comment by jurialmunkey** [comment]
The only ways to reload a widget are

- reload the skin
- update the library (reloads all paths after)
- change the path (which is what the param with the property does)

There is no other way to reload a widget.

I don't really understand what the issue is though - either you're adding the widget via skinshortcuts, in which case tmdbhelper automatically adds the param for you; Or the path is hardcoded in which case just add the param on the end.

I don't really understand what other method you could use to set the widgets unless it is some weird usage of favourites.

**Comment by matke-84** [comment]
> &amp;reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]

This doesn't help, it refreshes widget after a few minutes, which makes no sense. I need when the artwork changes to change immediately like it was before.

**Comment by jurialmunkey** [comment]
> > &reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]
> 
> This doesn't help, it refreshes widget after a few minutes, which makes no sense. I need when the artwork changes to change immediately like it was before.

The property is changed immediately after the artwork is updated. It happens at exactly the same time as it did previously. 

There is no difference in the timing of the two methods. They both cause the container to update. Any delay is your system being busy.

**Comment by matke-84** [comment]
It just doesn't work with titan skin based skins in hubs.
I edit two lines in the artselect.py file, more precisely returned them to the old method which works perfectly. I don't see any difference between these two methods when changing artworks, except that the new one doesn't work for me.
