### ISSUE TITLE
[Feature] "blur" and "crop" folder size

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/plugin.video.themoviedb.helper#937]
### Describe the feature that you'd like

A way to limit and clear these folders because the take up so much room when backing up. 

### Why is this feature needed? What problem does it solve?

Takes up a lot of room on a device. My build went from 1.50gb to 280mb after deleting the contents of these folders

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by adamosborne83** [comment]
What device are you using? I had this with my FireCube, but previously requested to be able to set the location of the folder which Jurial added. 

So if you can attach an External USB or hard drive then set the location there.

**Comment by Liquidrag** [comment]
> What device are you using? I had this with my FireCube, but previously requested to be able to set the location of the folder which Jurial added.
> 
> So if you can attach an External USB or hard drive then set the location there.

That's why the option is there! I guess I'll set an external folder. Thank you.
