### ISSUE TITLE
Kodi crash if episode name is Pilot

### ISSUE THREAD

**Issue by rapteev** [jurialmunkey/plugin.video.themoviedb.helper#938]
### Describe the bug

Hi
Using kodi 19.4 with latest versions of tmdb helper , artic horizon 2 and composite.
Everything work ok playing movies and episodes except if episode name is “pilot” (many series uses this name as 1st episode), or if episodes have no specific name (for example Peaky Blinders : episode 1, episode 2, etc.. 
In this case kodi blocks/crash and have to restart.

### Steps To Reproduce

1. Composite as main addon player on tmdb helper
2. Start tmdb helper and choose any tv show that 1st episode is named “pilot”
3. Try playing that episode 
4. Kodi stops/crash

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by rapteev** [comment]
On composite included player the search is made only by episode name!?? It should be made by tvshow/episode name.

**Comment by jurialmunkey** [comment]
I don't make that player. Ask the author of the player file.
