### ISSUE TITLE
Trakt Interface - getting lists sorted by add order not working 

### ISSUE THREAD

**Issue by KFC4Ever** [jurialmunkey/plugin.video.themoviedb.helper#939]
### Describe the bug

On my kodi skin (aeon silvo nox) I have several widgets and submenus pointing at TMDBHelper->Trakt - Your Lists with the option of sorting by add order. This is so I can see recently added items first in the lists. This no longer seems to be working as the pulled item lists don't seem to include the newly added items. They are all there when I check those custom lists on the Trakt website and when I pull them sorted by other options (release year, A-Z, etc). Only sorted by when added is not working. 

### Steps To Reproduce

See above

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [x] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
How are you applying this sort order?

These are ordered correctly for me using TMDbHelper's sorting methods
Your Lists > Context Menu > Browse Sorted List > Recently Added

**Comment by KFC4Ever** [comment]
Yes, I tried your steps above but am not seeing the added items. Please go ahead and close the case for now. I'm suspecting the issue may be with the unrelated Android Trakt app I use to update the lists. But I will need to test further.

**Comment by jurialmunkey** [comment]
Have you compared the same list with how it displays on the Trakt website sorting by recently added? If it matches what tmdbhelper has then you'll know that tmdbhelper is working correctly and the issue is somewhere else.

**Comment by KFC4Ever** [comment]
Yes, I've been doing some more tests and the additions to my lists are definitely showing up on the trakt.tv site (and on my various Android Trakt apps). They just aren't showing up on Tmdbhelper for some reason. I tried clearing my kodi cache as well but no luck. I'm going to keep testing to see what else I can find. I'll take a closer look at the Kodi logs for clues but am not seeing anything obvious so far (at least not to me).

**Comment by KFC4Ever** [comment]
Here are the Kodi logs that I have
https://paste.kodi.tv/nuyepinaza.kodi

**Comment by jurialmunkey** [comment]
Do you have an example Trakt list with the issue that you can make public and share here?

**Comment by KFC4Ever** [comment]
I'd prefer to keep my lists private but if I can set up a public test list I'll let you know. A couple of more observations - items that I added yesterday that didn't show up yesterday are showing up today. I did a memory clean on my Android TV box today so I'm not sure if that was a factor. I did a lot of memory cleans yesterday too though but those didn't help. Next I'm going to see if I can reproduce this on some of my other Kodi installations (Win PC, android phone).

**Comment by jurialmunkey** [comment]
> A couple of more observations - items that I added yesterday that didn't show up yesterday are showing up today.

I bet you have this option enabled...
`TMDbHelper Settings > Trakt > Cache items in custom lists you own for 24 hours`

**Comment by KFC4Ever** [comment]
Yes! This is the issue. After disabling this any changes I make to my custom lists are showing up immediately now. Thanks! Was this a recent change/feature in the code? I don't recall running into this issue until the last few weeks.

**Comment by jurialmunkey** [comment]
It was added three months ago in v4.11.5, so no not a new addition but not sure how frequently you update.

**Comment by KFC4Ever** [comment]
I only updated within the last month or so. That would explain things. Thanks for helping me figure this out.
