### ISSUE TITLE
[Enhancement] Video - Resume Playback

### ISSUE THREAD

**Issue by Demonseeed** [jurialmunkey/plugin.video.themoviedb.helper#94]
Hey Jurialmonkey!

Would it be possible to have the addon remember the time stamp of a movie that you last played and prompt to resume instead of starting over?

For example, I watch a movie and stop it halfway. If I go to play it later, it starts over. But if I go directly to the player’s addon, it prompts me to continue where I left off or start over (I assume it is getting this information from Trakt). 

Thank you!

**Comment by jurialmunkey** [comment]
I'm not sure if it's possible -- once the item plays, the instance of the tmdbhelper doesn't exist anymore to get the resume info. I'm not sure why the actual player addon being called wouldn't prompt for resume - I'll look into seeing if I can fix it, as it would be better for the player addon to handle resume points than tmdbhelper.

**Comment by Demonseeed** [comment]
Alright sounds good. Thank you again!👌

**Comment by drinfernoo** [comment]
It all depends on the playing add-on.

**Comment by jurialmunkey** [comment]
I'm not sure this is possible without some convoluted workaround, so I'm going to close the issue even though it's not resolved.

**Comment by Demonseeed** [comment]
Sorry for the late response, got a puppy that has been keeping me very busy. 

Thank you for looking at this for so long! 

I have a possible idea on this. What if there was some kind of endpoint/integration point that addon could pass on/receive to/from players, allowing this feature - if implemented from the player addon as well. 

Of course, it wouldn’t work out if the box with anything, but considering how immensely popular this addon is, I have no doubt addons will implement it (of course if this is even possible/feasible).
