### ISSUE TITLE
[BUG] image.tmdbhelper.org vs. images.tmdbhelper.org

### ISSUE THREAD

**Issue by ambulancePilot** [jurialmunkey/plugin.video.themoviedb.helper#940]
### Describe the bug

This is a weird one. I was having some issues surrounding posters not loading so I deleted my Thumbnails folder (over 5GB at this point) and deleted the Textures13.db file along with it. Since then, I can't load any artwork at all unless I force it to use fanart.tv from within the settings.

Either way, I am getting tons of errors in the log that the addon can't reach various URLs from image.tmdbhelper.org.

The problem is, I thought the URL was **images**.tmdbhelper.org? If I copy a URL from the log and paste it into my browser, it 404s. But if I add the 's' at the end of 'image', it works.

What's going on here? I feel like I am missing something. I don't mind grabbing artwork from fanart.tv (I donate for faster API access, so I think it's as fast/if not faster than TMDB) but the problem is when the artwork is not available from fanart.tv, it falls back to TMDB but it 404s because the URL is somehow wrong? I know the URL cannot be wrong because no one else is reporting this but how come adding an 's' to the end of 'image' makes the poster load in my browser? Something weird is going on.

Sorry if this is not related to TMDB Helper and is instead related to the video addon I am using. The only error notification that popped up in the corner was for TMDB Helper so I assumed but I think I might be wrong.

### Steps To Reproduce

See above.

### Debug log

https://paste.kodi.tv/izimojivit

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I can open all these images in from your log in my browser fine.

image (not images) is the correct location according to the api docs
https://developers.themoviedb.org/3/getting-started/images

Btw the error from TMDbhelper is unrelated and just a coincidence.

**Comment by ambulancePilot** [comment]
I think I've been banned from tmdb images API. I can grab data but not images.

After I deleted the thumbnails folder, I think it tried to download all of them again at once somehow (should add-ons not be coded to stop that from happening?). I checked my API stats on the tmdb website and normally I average about 150 requests a day, on this particular day it was over 1500 requests. I think I am out of luck... unless you have any ideas?

Thanks for helping even though this isn't related to your add-on!

**Comment by ambulancePilot** [comment]
Scratch that, I spoke too soon. Those URLs don't work from my mobile connection either. Seeing as how they are different IPs, I can't be banned.

Do you have any idea at all what could be causing me to suddenly not load images from tmdb?

Now that I think about it, the ban theory doesn't make sense because the whole reason I deleted my thumbnails folder was because images weren't loading (and I was using tmdb as my primary artwork provider across all add-ons).

**Comment by ambulancePilot** [comment]
Sorry I figured it out. My DNS ad filter was catching it for some reason. Thanks!

**Comment by jurialmunkey** [comment]
Haha no worries! 

I was almost going to suggest checking ad blocking filters but thought it'd be too much of a wild stab in the dark. 

Weird that url ended up in your filters

**Comment by xyzfre** [comment]
> Sorry I figured it out. My DNS ad filter was catching it for some reason. Thanks!

If you don't mind me asking how did you figure this out on my end I'm having the same issues started recently fanart covers take a while to load ,, Specially when going into recommendations screen ,weird part is I tried at work with a different PC and network and the same thing is happening

**Comment by ambulancePilot** [comment]
Well I use the nextdns.io DNS service. It allows you to block ads at the DNS level so the domain doesn't even get resolved. Saves bandwidth and network time. The caveat is that I'm pretty sure they know 100% of my browsing history.

Logging in to my account on that site, it was easy to see the image.tmdb.org domain was being blocked by the somewhat popular blocklist "Goodbye Ads." It had been recently listed at a "tracker".

**Comment by xyzfre** [comment]
I'm glad I came across this issue for the last couple years I've been using fanart.tv as my primary for movie posters and TV Show posters which lately they were taking longer to load,, so I decided to use TMDb instead and the fanart loads so much faster now and I liked there movie posters and TV show posters look way better
