### ISSUE TITLE
Choosing recommendation movie or show from pvr does nothing 

### ISSUE THREAD

**Issue by rapteev** [jurialmunkey/plugin.video.themoviedb.helper#942]
### Skin section

PVR and Live TV

### Current Behavior

Hi
With tmdbhelper look-ups for pvr windows turned on , if I go to pvr guide , choose a channel with a movie , information, and then browse for recommendations and choose one of recommended movies nothing happens.

### Expected Behavior

Choose a recommended movie when coming from pvr channel , open information/play that movie.

### Steps To Reproduce

1.go to live tv
2.select a channel that is playing a movie.
3. Select programme information on that channel.
4. Click down for recommendations.
5. Cast, recommended, similar, etc.. shows up.
6. Select one similar or recommended movie (nothing happens)

### Screenshots and Additional Info

…

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by rapteev** [comment]
Hi Jurialmunkey
Thanks for fixing this, it works very well now on latest nightly of kodi 20, but on kodi 19.4 it seems that is still not working.

**Comment by jurialmunkey** [comment]
The changes in the branches are identical. Make sure you have installed the latest version.
