### ISSUE TITLE
Trakt - Movies Collection - Retrieving list by Recently Added Order does not work correctly

### ISSUE THREAD

**Issue by KFC4Ever** [jurialmunkey/plugin.video.themoviedb.helper#943]
### Describe the bug

When viewing the Trakt 'Movies Collections" list using sort by "Recently Added" the list is not actually sorted from newest added to oldest added. The list is sorted instead from oldest to newest. For "TV Collections" viewing the list sorted by "Recently Added" shows the correct sort order. It's only for "Movies Collection" does there appear to be an issue with sorting by "Recently Added".

### Steps To Reproduce

See above

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Ah, that'd be because collection sync list doesn't have a `listed_at` value which is what recently added sorts by.

I've added a new sort method for collections `Sort by: Collected` which will allow for sorting by when the item was collected.

**Comment by KFC4Ever** [comment]
Thank you!
