### ISSUE TITLE
PVR id not working if date is present.

### ISSUE THREAD

**Issue by rapteev** [jurialmunkey/plugin.video.themoviedb.helper#944]
### Describe the bug

Hi
The plugin is doing a great job identifying pvr programs (movies/ tv shows) , but if program as date,  ex: Forrest gump (1994) , plugin do not identify it and do not show extra info. The same movie is correctly identified if as no date, ex: Forrest Gump.

### Steps To Reproduce

Select a live tv movie with year present 
Programme information 
Try to see extra info

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
It won't be perfect but that change should help somewhat.

**Comment by rapteev** [comment]
Hi 
This problem returned with the latest versions of the plugin.
Thank you
