### ISSUE TITLE
[BUG] Description thumbs missing in cinemas widget and upcoming movies widget

### ISSUE THREAD

**Issue by vbtony** [jurialmunkey/plugin.video.themoviedb.helper#945]
### Describe the bug

after updating a couple of versions ago, thumbs went missing in cinemas widget and upcoming movies widget, reinstalled previous version thumbs came back, this happens on windows and android, Rapier skin, I searched kodi log for errors, no errors found, movie info populates widget fine

![screenshot00000](https://user-images.githubusercontent.com/28744923/204321304-9a464286-fdc2-4e9a-b9f7-5cfc0541c071.png)

### Steps To Reproduce

install latest ver tmdb helper, reinstall previous version and it works fine

### Screenshots and Additional Info

![screenshot00000](https://user-images.githubusercontent.com/28744923/204321884-e24ef3ab-8d52-4bff-8542-baabbab6e352.png)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Posters work fine for me. Looks like the skin is using Art(thumb) when it should be using Art(poster)

ListItem.Thumb was depreciated. Previously Art(thumb) and Icon were linked. They aren't anymore and Art(thumb) is explicitly used only for thumbnails not posters.

The skin needs to be updated to use ListItem.Art(poster) for those widgets.
