### ISSUE TITLE
[Feature] Description

### ISSUE THREAD

**Issue by Andrea-1998** [jurialmunkey/plugin.video.themoviedb.helper#946]
### Describe the feature that you'd like

Instead of displaying a long string of numbers like: 23,500,000, it would be much more useful to display $23.5 Million.
Both methods can remain, the first one as: **ListItem.budget** and the second one as: **ListItem.budget.formatted**

This can be done in budget and revenue.

### Why is this feature needed? What problem does it solve?

Should be added because it simplifies the format and also because it reduces the display space, very useful for those with limited space and want to use both the budget and the revenue.

### Screenshots and Additional Info

Ex: 350,000,000 = $350 Million       ->   $350 $LOCALIZE[xxxxxx]     Milion/Milioni
     3,350,000,000 = $3,350 Bilion    ->   $3,350 $LOCALIZE[xxxxxx]  Bilion/Miliardi

Depending on the language selected in TMDB Helper, the most relevant word will be shown:
Eng: Milion     Eng: Bilion
Ita: Milioni      Ita: Miliardi

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
There's a big problem in that this approach is incredibly Euro/USA centric. 

Many countries around the world do not use groupings of thousands and use other numbering systems. For more details see: https://en.wikipedia.org/wiki/Long_and_short_scales#Current_usage

Asian countries (e.g. China, Japan, Korea) use myriad number groupings (10000s). Subcontinental Asian countries (e.g. India, Pakistan, Bangladesh) use lahk and crore groupings (100s above 1000). Neither of these align with Eurocentric groupings (1000s)
https://en.wikipedia.org/wiki/Myriad#Asia
https://en.wikipedia.org/wiki/Indian_numbering_system

| USA | Subcontinent | Asia |
| :--- | :--- | :--- |
| 10 thousand | 10 thousand | 1 myriad |
| 100 thousand | 1 lahk | 10 myriad |
| 1 million | 10 lahk |  1 hundred myriad |
| 10 million | 1 crore |  10 hundred myriad |
| 100 million | 10 crore |  1 myllion |
| 1 billion | 1 arab |  10 myllion |
| 10 billion | 10 arab |  1 hundred myllion |
| 100 billion | 1 kharab |  10 hundred myllion |
| 1 trillion | 10 kharab | 1 myriad myllion |

This is not a simple translation matter.

Additionally, in long scale countries (e.g. France, Argentina, Belgium, Germany etc.) a billion means what the USA would call a trillion. If the specific language is not translated then Kodi will revert to using the English translation. That will create confusion for these countries 
| USA | France |
| :--- | :--- |
| 1 million | 1 million |
| 1 billion | 1 milliard |
| 1 trillion | 1 billion |


I'm happy to consider a formatting approach IF there is a simple solution to these differences. However, I personally cannot see a simply approach here.

**Comment by alberto-1998** [comment]
Forgive me for answering just now, but I haven't had a chance to look at Github these days.

Ok, I understand that it can be confusing, but maybe it can be left only in US format, as other scripts already do, and it's only for those who want to use it, otherwise they can use the standard number format.
Then for those who want their own language, they can use a translation script already available in kodi:
https://forum.kodi.tv/showthread.php?tid=370094

Thus ListItem.Budget.formatted is used for US-formatted digits and ListItem.Budget for numeric digits.

This type of formatting is already used by other scripts (extended info) and by other skins (confluence zeitgeist and others...).


I think that's the best solution...

**Comment by Andrea-1998** [comment]
> There's a big problem in that this approach is incredibly Euro/USA centric.
> 
> Many countries around the world do not use groupings of thousands and use other numbering systems. For more details see: https://en.wikipedia.org/wiki/Long_and_short_scales#Current_usage
> 
> Asian countries (e.g. China, Japan, Korea) use myriad number groupings (10000s). Subcontinental Asian countries (e.g. India, Pakistan, Bangladesh) use lahk and crore groupings (100s above 1000). Neither of these align with Eurocentric groupings (1000s) https://en.wikipedia.org/wiki/Myriad#Asia https://en.wikipedia.org/wiki/Indian_numbering_system
> 
> USA	Subcontinent	Asia
> 10 thousand	10 thousand	1 myriad
> 100 thousand	1 lahk	10 myriad
> 1 million	10 lahk	1 hundred myriad
> 10 million	1 crore	10 hundred myriad
> 100 million	10 crore	1 myllion
> 1 billion	1 arab	10 myllion
> 10 billion	10 arab	1 hundred myllion
> 100 billion	1 kharab	10 hundred myllion
> 1 trillion	10 kharab	1 myriad myllion
> This is not a simple translation matter.
> 
> Additionally, in long scale countries (e.g. France, Argentina, Belgium, Germany etc.) a billion means what the USA would call a trillion. If the specific language is not translated then Kodi will revert to using the English translation. That will create confusion for these countries
> 
> USA	France
> 1 million	1 million
> 1 billion	1 milliard
> 1 trillion	1 billion
> I'm happy to consider a formatting approach IF there is a simple solution to these differences. However, I personally cannot see a simply approach here.

Forgive me for answering just now, but I haven't had a chance to look at Github these days.

Ok, I understand that it can be confusing, but maybe it can be left only in US format, as other scripts already do, and it's only for those who want to use it, otherwise they can use the standard number format.
Then for those who want their own language, they can use a translation script already available in kodi:
https://forum.kodi.tv/showthread.php?tid=370094

Thus ListItem.Budget.formatted is used for US-formatted digits and ListItem.Budget for numeric digits.

This type of formatting is already used by other scripts (extended info) and by other skins (confluence zeitgeist and others...).


I think that's the best solution...

**Comment by jurialmunkey** [comment]
Closing as not planned because there's no non-eurocentric approach that will work here.
