### ISSUE TITLE
[BUG] Provider Data Allowlist not working as expected

### ISSUE THREAD

**Issue by stefan-fast** [jurialmunkey/plugin.video.themoviedb.helper#947]
### Describe the bug

First of all, there might be a misunderstanding on my side on how the provider data allowlist in `Settings > Other` actually works.

My expectation is that when I only select "Netflix" for example, only shows and movies from Netflix will be listed in menus like `Movies > Popular` after clearing the item details cache. However, I'm still seeing stuff from other providers like Disney+, Amazon etc. in these menus.

### Steps To Reproduce

1. Deselect all the providers but "Netflix" under `Settings > Other`
2. Go to `Settings > Expert > Delete Cache > Delete Item Details Cache`
3. Open video addon TheMovieDb Helper
4. Navigate to `Movies > Popular` (or any other list really)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Misunderstanding.

The providers in Settings > Other is simply for skins that display provider icons in place of codecs (e.g. like in Arctic Horizon 2). It allows you to customise which provider icons are displayed in the skin.

If you want to create lists based on a specific provider then you should use the Discover feature with a with_providers rule.
