### ISSUE TITLE
[Enhancement] Episode Artwork

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#95]
Currently only Fanart, thumb and tvshow.clearlogo are being set for Episodes.

Would it be possible for you to set Poster and Landscape (from tvshow) for Episodes.

Thanks!

**Comment by jurialmunkey** [comment]
Works fine for me. 

For episodes it needs to be:
```
$INFO[ListItem.Art(tvshow.landscape)]
$INFO[ListItem.Art(tvshow.poster)]
```

**Comment by skyfsza** [comment]
Ok thanks, will add tvshow.poster and tvshow.landscape to the skin.
