### ISSUE TITLE
[BUG] Can't reopen recommendations window with original params

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#950]
### Describe the bug

A video is worth a thousand words:- https://streamable.com/9vh2y5

### Steps To Reproduce

1. Open DialogInfo.xml for an item (in the video a TV Show)
2. Call the recommendations window.
3. Back to original DialogInfo and call recommendations window with the same params - OK
4. From the recommendations window select an item to open a new DialogInfo.
5. Back out to the original DialogInfo
6. Call the recommendations window with original params and it fails to open :(

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by roidy** [comment]
Am I calling the script correctly?

`Runscript(plugin.video.themoviedb.helper,recommendations=5000|info=cast|true|info||5001|info=similar|true|info||5002|info=posters|true|browse,window_id=1191,$VAR[Type],$VAR[Query])</onclick>`

```
<variable name="Query">
    <value condition="!String.IsEmpty(ListItem.Property(imdb_id))">imdb_id=$INFO[ListItem.Property(imdb_id)]</value>
    <value condition="!String.IsEmpty(ListItem.IMDBNumber) + String.StartsWith(ListItem.IMDBNumber,tt)">imdb_id=$INFO[ListItem.IMDBNumber]</value>
    <value condition="String.IsEqual(ListItem.DBType,episode) + !String.IsEmpty(ListItem.TvShowTitle) + !String.IsEmpty(ListItem.Year)">query=$INFO[ListItem.TvShowTitle],year=$INFO[ListItem.Year]</value>
    <value condition="[String.IsEqual(ListItem.DBType,season) | String.IsEqual(ListItem.DBType,episode) | String.StartsWith(ListItem.Label,Season)] + !String.IsEmpty(ListItem.TvShowTitle)">query=$INFO[ListItem.TvShowTitle]</value>
    <value condition="!String.IsEmpty(ListItem.Title) + String.IsEmpty(ListItem.Year)">query=$INFO[ListItem.Title]</value>
    <value condition="!String.IsEmpty(ListItem.Title) + !String.IsEmpty(ListItem.Year)">query=$INFO[ListItem.Title],year=$INFO[ListItem.Year]</value>
    <value>query=$INFO[ListItem.Label]</value>
</variable>

<variable name="Type">
    <value condition="String.IsEqual(ListItem.DBType,movie) | ListItem.IsCollection | String.IsEqual(ListItem.DBType,set)">tmdb_type=movie</value>
    <value condition="String.IsEqual(ListItem.DBType,tvshow) | String.IsEqual(ListItem.DBType,season) | String.IsEqual(ListItem.DBType,episode)">tmdb_type=tv</value>
</variable>
```

I just can't figure out why once I navigate to any item in the recommendations window and return to the original DialogInfo window I can't then call the script again.

**Comment by jurialmunkey** [comment]
Yeah that looks right. I can't seem to recreate it though. 

I have had this behaviour happens on occasion but it's usually only when I'm trying to break things - eg reloading skin while script is running or aggressively pressing back so the script can't keep up will both introduce some weird behaviour. Definitely not just going back and forwards normally though. 

Do you have some sort of extra onclick action in your recommendations window (eg a close action)? Because that might be interfering. That's all I can think of off the top of my head.

**Comment by roidy** [comment]
> Do you have some sort of extra onclick action in your recommendations window (eg a close action)? Because that might be interfering. That's all I can think of off the top of my head.

Nope, nothing, no onclick's or onback's.

It also seems to be really random, on the same item it wont work half a dozen times then it will work one time and then wont work again.

**Comment by matke-84** [comment]
I have a similar problem. When I start the recommendation dialog from skin shortcuts, everything works as it should. But when I run it from an addon or videodb://movies/titles/ I have big problems. Best watch the video.
https://youtu.be/hPy7r8cnXuo

1.     Open DialogInfo.xml for an item from addon or videodb://movies/titles/
2.     Call the recommendations window.
3.     Back to original DialogInfo and call recommendations window again with the same params - OK
4.     From the recommendations window select an item to open a new DialogInfo or cast info
5.     Back out to the main Recommendations Dialog, all lists is gone
6.     Back out to the original DialogInfo
7.     Call the recommendations window again with original params and it fails to open

**Comment by matke-84** [comment]
@jurialmunkey
Is there any solution here? Am I doing something wrong? How is it possible that everything works perfectly from the home screen or skin shortcut, but it does not work when it is started directly via addon or library. What's the difference there? Is this up to tmdb helper, but am I doing something wrong? I would really appreciate your help.

**Comment by matke-84** [comment]
@jurialmunkey
https://streamable.com/9vh2y5 
Look at the video very carefully. As soon as you open something from recommendation dialog, you can see for a moment that the info dialog below is closed. The same thing happens to me. Maybe that's a clue.

**Comment by matke-84** [comment]
@jurialmunkey 
I must apologize. The bug was in my code. For some reason, my global background was conflicting with the recommendation dialog. Why this happened only in addons and not on the home screen is still not clear to me. I started by the system of elimination and came to the conclusion that this line was causing the problem. That's why the recommendation is for @roidy take a look at the code, maybe you have a similar problem.

**Comment by roidy** [comment]
>Yeah that looks right. I can't seem to recreate it though.

Hi, I'm revisiting this issue as after testing your Arctic Horizon 2 skin I have the exact same problem. Meaning it's not just in my skin and code.

Arctic Horizon 2 (0.8.17) TheMovieDBHelper (5.1.6~nexus)
1. Open Info for any item.
2. Press down to get the extended info.
3. Select any item to open it's new DialogInfo.
4. Press down again to get the extended info.
5. Now back out right back to your original items DialogInfo.
6. Press down to reopen the original items extended info and it just won't reopen.

More testing reveals that it works under Windows but fails when using CoreELEC or Linux.

**Comment by roidy** [comment]
@jurialmunkey Any idea why this works under Windows but fails under CoreELEC/Linux?
