### ISSUE TITLE
[Feature] Trigger Android Intent

### ISSUE THREAD

**Issue by webepg** [jurialmunkey/plugin.video.themoviedb.helper#953]
### Describe the feature that you'd like

Hi,

is there a way to trigger an Android Intent? I was able to trigger it from within Kodi favorites. But how do I do it to start it from TMDB Helper? 

### Why is this feature needed? What problem does it solve?

It would be great for services that don't have a Kodi addon but have documented addons, and also for apps that often change their API or security.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by webepg** [comment]
This is the way how I was able to start the android app from within the favorites.xml:

`<favourites>

    <favourite name="Appname" thumb="androidapp://sources/apps/com.app.png">StartAndroidActivity(&quot;com.app.name&quot;,&quot;android.intent.action.VIEW&quot;,&quot;&quot;,&quot;intentname://thisisatest&quot;)
</favourite>

</favourites>`

**Comment by jurialmunkey** [comment]
Above commit allows player files to execute [Kodi built-in functions](https://kodi.wiki/view/List_of_built-in_functions) by using the `executebuiltin://` path prefix

Example player file which launches the `Notification()` command to open a notification dialog with the title and year of the movie:

```json
{
    "name"          : "Notification",
    "plugin"        : "xbmc.core",
    "icon"          : "{}/resources/icons/other/kodi.png",
    "priority"      : 10000,
    "is_resolvable" : "false",
    "play_movie"    : "executebuiltin://Notification({title},{year})"
}
```

**Comment by webepg** [comment]
YOU ARE THE BEST!!!!! THANK YOU VERY MUCH!!!
