### ISSUE TITLE
Play a kodi library movie from Hub-Movies(Tmdb) gives error.

### ISSUE THREAD

**Issue by rapteev** [jurialmunkey/plugin.video.themoviedb.helper#955]
### Describe the bug

Hi
On moviedb helper - play local kodi library files is set to automatic.
If I go to movies library and play a movie it works fine, however if I go to hub-movies(tmdb) and try to play the same movie it gives error.
This behavior only happens on windows 11 setup. On same setup on android (nvidia shield) it works fine.

### Steps To Reproduce

1. Go to hub-movies(tmdb) 
2. Try to play a movie that exist on kodi library.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Full debug log please.

How can I possibly know what the error is if you don't upload a log.

**Comment by rapteev** [comment]
Hi
Sorry for that.
Here is log.
https://drive.google.com/file/d/1JuCmDyAkOCwVIWB62dLx8DnWzK5hP5Mx/view?usp=drivesdk

**Comment by rapteev** [comment]
.
