### ISSUE TITLE
[BUG] His Dark Materials is not showing the new season

### ISSUE THREAD

**Issue by fugkco** [jurialmunkey/plugin.video.themoviedb.helper#956]
### Describe the bug

There's a new season for the show His Dark Materials, but it seems it's not showing up in TMDB Helper. It's only showing season 1 and 2.

### Steps To Reproduce

1. Search for His Dark Materials under shows and open it
2. Notice there is no season 3

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Season 3 doesn't start until next week. 

Check tmdbhelper settings. You probably have hide unaired episodes enabled.

**Comment by fugkco** [comment]
My bad. It seems the dates are wrong in tmdb. Thanks!
