### ISSUE TITLE
Players Not working in Nexus

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#957]
### Describe the bug

Does anything have to change with the players files when using Nexus? The players show, however it does not open the addon for playback. Using 5.0.32~nexus on Nexus RC. On windows 11. The same players that were working on Matrix arent working on Nexus, for example Homelander.

### Steps To Reproduce

Open TMDBH, click on media, choose a player. The addon never opens to start scraping. 

### Debug log

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/10203810/kodi.log)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Players work fine for me on Nexus.

Though it is pretty clear from the log that player file is misconfigured. It's particularly obvious in the plot that the wrong encoding of keys is being used in the plugin:// URI.

See the wiki for how to apply different types of url encoding. 
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#special-suffixes-for-plugin-uri

Guarantee this plugin is expecting `{KEY_url}` type encoding but the player file has raw unencoded key types

Most of these third party players look like someone trying to find the secret cheat code to make it "work" by plugging random values into a copy of another player file rather than actually understanding what they're trying to do.

**Comment by JayDee696969** [comment]
Ok, thanks for the clue, ill give it a try. Its just odd that it works fine on Matrix, so I didnt look too hard. 
Thanks!

**Comment by jurialmunkey** [comment]
Well that's the thing about encoding: it only matters when you encounter special reserved characters. It will still work some of the time

e.g. 
maybe `The Breakfast Club` is fine but `Breakfast at Tiffany's` is not because the quote mark ends a string early
maybe `Monsters University` is fine but `Monsters, Inc.` is not because scripts use commas to separate params
maybe `Batman` is fine but `Batman & Robin` is not because plugin URIs use ampersands to separate keyword pairs

Encoding changes the special characters into codes which the plugin can then decode back into the character later.

**Comment by jurialmunkey** [comment]
Also worth mentioning that Trakt has been down all day, so if the plugin relies on Trakt and this issue has only started today then that's also a possible cause.

https://twitter.com/trakt/status/1602191569469071360?cxt=HHwWgICjhcyvkLwsAAAA

**Comment by JayDee696969** [comment]
Yea, im hoping its the Trakt issue. I tried adding the _+ to the keys that were missing them and had no luck.

**Comment by JayDee696969** [comment]
On the quest to figuring this out on my own. Whats the best way to get the steps the addon uses to play something? Is it maybe adding a Movie to Kodi favorites and seeing what the layout in there shows? I did that and I do see the simalar steps. I assume I would edit out the actual movie info and replace them with Available keys.

**Comment by jurialmunkey** [comment]
> Yea, im hoping its the Trakt issue. I tried adding the _+ to the keys that were missing them and had no luck.

_+ doesn't encode anything it just puts + instead of spaces. If the player has that in it for some keys then that's a good example of whoever made it not knowing what they're doing. 

The plugin very clearly uses percent encoding which you can tell by all the percentage signs

You use the _url affix to get standard percent encoding

**Comment by jurialmunkey** [comment]
> Is it maybe adding a Movie to Kodi favorites and seeing what the layout in there shows? I did that and I do see the simalar steps.

Yeah that's probably the simplest way to get the direct path. There are some better tools for inspecting listitem.folderpath but they take some work to setup

Also the alternative is to make something similar to the Netflix, Showmax or Hulu plugins that actually do the steps of searching - it's basically the same as if you were walking through the plugin clicking on things

Showmax is the one I'd use to start with as a template but also look at Hulu and Netflix for slightly different approaches
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/nexus/resources/players/showmax.json

The trick to doing one that steps through is looking for the search query path (so do a search, then go back to the saved search and favourite it, then replace search query with a title key).

There's also tools in the configure players dialog to help make new players from a template

**Comment by JayDee696969** [comment]
Appreciate the clues. Ill have to wait until Trakt is back up. Any search queries seem to use Trakt.

**Comment by JayDee696969** [comment]
Yea, so same players still work fine on Matrix, but not Nexus. Guess its not a Trakt issue. So Nexus must be a bit more fussy when it comes to the players being written correctly.

**Comment by JayDee696969** [comment]
Dam, Trakt is back but some players still dont work. They work in Matrix, but not Nexus. Guess Nexus is more picky about the players being written correctly.

**Comment by JayDee696969** [comment]
So another thing woth mentioning. While trying to figure out the option to create a player in TMDBH and it prompts you with Missing Query Key in URL, Ive tried a bunch of ways but doesnt accept it, I get I must be doing it wrong, but wish there was a way to cancel the window. If you get stuck there theres no way to cancel or exit. Have to force close Kodi.

**Comment by audiosistem** [comment]
https://bit.ly/3VYx8J9

**Comment by JayDee696969** [comment]
> https://bit.ly/3VYx8J9

Brooo, thank you!!!

**Comment by jurialmunkey** [comment]
> So another thing woth mentioning. While trying to figure out the option to create a player in TMDBH and it prompts you with Missing Query Key in URL, Ive tried a bunch of ways but doesnt accept it, I get I must be doing it wrong, but wish there was a way to cancel the window. If you get stuck there theres no way to cancel or exit. Have to force close Kodi.

@JayDee696969 - Basically the gist of the query template is that you first need to use the plugin normally to generate some kind of search history for both movies and tvshows. Then you use those saved search history paths as the base for the template by replacing the word you searched for with the term `QUERYKEY`

Here's complete steps:

1. Go to the plugin you're going to use and search for the movie "Alien" and the tvshow "Breaking Bad" to generate search history
2. Open TMDbHelper Settings > Configure Players
3. Select `create new player`
4. Select the plugin to use
5. Select `urlquery_default.json`
6. Navigate to that search history path you created for Movies -- e.g. Movies > Search > Alien -- and wait for the search results to show up
7. Select `Use current folder as search URL`
8. When asked to use same search URL for tvshows select `No`
9. Repeat the steps 6 & 7 but for tvshows instead
10. Replace the word `Alien` in the plugin:// url with the word `QUERYKEY` in all caps and do the same for the tvshow one -- e.g. you should end up with a path like `plugin://plugin.name.of.plugin/?action=movieSearchterm&name=QUERYKEY`
11. Enter a name for the player
12. Save

Alternatively, if you dont have a plugin that can make a search history then use the `keyboard_default.json` template instead. The basic approach is as above but you skip Step 1 and in Step 6 you instead go to "New Search" and then leave the keyboard blank.

**Comment by JayDee696969** [comment]
> > So another thing woth mentioning. While trying to figure out the option to create a player in TMDBH and it prompts you with Missing Query Key in URL, Ive tried a bunch of ways but doesnt accept it, I get I must be doing it wrong, but wish there was a way to cancel the window. If you get stuck there theres no way to cancel or exit. Have to force close Kodi.
> 
> @JayDee696969 - Basically the gist of the query template is that you first need to use the plugin normally to generate some kind of search history for both movies and tvshows. Then you use those saved search history paths as the base for the template by replacing the word you searched for with the term `QUERYKEY`
> 
> Here's complete steps:
> 
> 1. Go to the plugin you're going to use and search for the movie "Alien" and the tvshow "Breaking Bad" to generate search history
> 2. Open TMDbHelper Settings > Configure Players
> 3. Select `create new player`
> 4. Select the plugin to use
> 5. Select `urlquery_default.json`
> 6. Navigate to that search history path you created for Movies -- e.g. Movies > Search > Alien -- and wait for the search results to show up
> 7. Select `Use current folder as search URL`
> 8. When asked to use same search URL for tvshows select `No`
> 9. Repeat the steps 6 & 7 but for tvshows instead
> 10. Replace the word `Alien` in the plugin:// url with the word `QUERYKEY` in all caps and do the same for the tvshow one -- e.g. you should end up with a path like `plugin://plugin.name.of.plugin/?action=movieSearchterm&name=QUERYKEY`
> 11. Enter a name for the player
> 12. Save
> 
> Alternatively, if you dont have a plugin that can make a search history then use the `keyboard_default.json` template instead. The basic approach is as above but you skip Step 1 and in Step 6 you instead go to "New Search" and then leave the keyboard blank.

THANK YOU!. I was making it too difficult. When it said enter QUERYKEY, I thought it meant to use one of the keys like {KEY_url}, lol. Thanks!

**Comment by JayDee696969** [comment]
Nice, the player code looks sooo much cleaner using the create a player option.

**Comment by batarela** [comment]
Hi,
Does anyone have a working player for plugin://slyguy.hbo.max
tnx

**Comment by JayDee696969** [comment]
> Hi, Does anyone have a working player for plugin://slyguy.hbo.max tnx

Try the create a player option in TMDBH settings.
