### ISSUE TITLE
"Next Aired Library" feature is not working

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#959]
### Describe the bug

From about 3days ago "Next Aired Library" feature is not working.

log error message :
error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.themoviedb.helper/?days=14&info=library_nextaired&startdate=-14) failed

### Steps To Reproduce

1. Run themoviedb.helper addon
2. Move to Next Aired Library and Run

### Debug log

https://paste.kodi.tv/raw/winuzosadi

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
https://twitter.com/trakt/status/1602509838713589760?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet

Trakt is down past two days.

**Comment by ghost** [comment]
@jurialmunkey 
Trakt is back but still not working. Any API changes?

**Comment by jurialmunkey** [comment]
If you read their website and twitter you will see that the api is still off-line until next week.
