### ISSUE TITLE
Add to Kodi Library

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#96]
I noticed that the Add to Kodi Library option in the context menu only shows up if TMDBH has Trakt authorization. Is this behavior intended?  Because technically, you dont have to use Trakt if you just want to use the Kodi library correct? So i dont see why Trakt has to be linked for the Add to Kodi library feature to be enabled.

**Comment by JayDee696969** [comment]
Also, would it be possible to add the "Add to Kodi Library" option in the details section?

**Comment by jurialmunkey** [comment]
Ah yep whoops! Should be fixed now.

I'll look at adding to details section soon.

**Comment by JayDee696969** [comment]
Great, thanks!
