### ISSUE TITLE
[Feature] Add "Select Player" back to the main/primary context menu

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/plugin.video.themoviedb.helper#960]
### Describe the feature that you'd like

Would it be possible to move the "Select Player" item back to the main/primary context menu?

### Why is this feature needed? What problem does it solve?

I'm pretty sure it was there early in the Alpha phase, but at some point it was moved to a second menu under TMDBH Options. If others are at all like me, one of the primary benefits to using TMDBH is the ability to select different players without manually navigating within each separate addon. That makes it one of the most used features of the context menu (at least for me). So it's not as convenient to have to scroll down to TMDBH Options and click again to get to Select Player. It would be really nice to have Select Player back on the primary context menu dialog for easier access.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
See comment on other issue
https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/711#issuecomment-1364590375

Kodi issue which was fixed in Nexus
