### ISSUE TITLE
Using context menu Trakt options try clicking mark unwatched

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/plugin.video.themoviedb.helper#961]
### Describe the bug

Noticed today using 19.5 or Nexus when trying to mark a movie using the Context  menu Trakt options as unwatched The checkmark doesn’t go away but if I go into TMDb H settings and clearing Trakt cache and I go back to the home screen or within TMDb the checkmark is gone last time I use this feature it used to work on the fly didn’t notice when it started happening

### Steps To Reproduce

1. Finish a movie or mark it as watched 2. Open Context menu 3. Trakt options try clicking unwatched and the checkmark doesn’t go away 4. Go to TMDb settings clear Trakt cache 5. Go back to home screen or within TMDb and the checkmark is gone

### Debug log

Apologies didn’t get a chance to grab the log 

### Screenshots and Additional Info

//

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by xyzfre** [comment]
I also tried logging out from Trakt from TMDb H settings and logging back in,, I'm using the latest Nexus on Windows 11 Pro,, but I also did try on 19.5 to make sure it wasn't a Nexus issue

**Comment by jurialmunkey** [comment]
I can't replicate this issue.

**Comment by xyzfre** [comment]
On my end it still happens only with Movies with TV shows it works on the fly ,, bring up the context menu Trakt options and Mark as unwatched for TV Shows the check mark goes away instantly for Movies it doesn't if I clear Trakt cache in TMDb settings then The checkmark is gone K20.1 Windows 11 Pro

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/227073231-e3c9b63f-118a-410c-8b2f-a25f5381486e.jpeg)

**Comment by xyzfre** [comment]
These are my Trakt settings

**Comment by jurialmunkey** [comment]
I still can't replicate. Works fine for me on both tvshows and movies and on widgets and in library.

What happens if you mark as unwatched, quit Kodi and then reopen it?
Have you accidentally removed the reload paramater from your widgets? Widgets will not reload after actions if you removed the reload parameter

It will be `&widget=true&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]` on the end of the Action. If you've removed that then your TMDbHelper widgets will not reload after performing an action on them. If the widgets in question dont have that on the end then you should delete them and re-add them.

Also note you must wait for the widget to reload to see the change.

**Comment by xyzfre** [comment]
I have checked all my widgets action reload parameter they all have the  &widget=true&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)] on my Home Screen widgets ,but this also happens within TMDb H only for Movies not sure if it makes a difference but I don't use (library) only Trakt, and also checked the Trakt website after using the mark as unwatched and it does remove it from the website , weird part as I mentioned before if I clear Trakt cache from TMDb settings when I come back out the checkmark is gone,, it's like if it caches the checkmark

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/227383537-4d8ed1f6-2808-4949-9854-ad61e493a2d3.jpeg) The only place I don't see that reload parameter is here

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/227384071-4002e443-71ee-4a01-b7e9-625d20f79bd1.jpeg) The only place where I don't see that reload parameter is in my main sections here, but I've never change anything here or even tried

**Comment by xyzfre** [comment]
Sorry to bother you again with this issue maybe something got corrupt on my end ,is there any recommendation you can give maybe deleting something in user/addon/data ,, I'm on Windows 11 Pro and now K21 Omega

**Comment by Marcuzzo10** [comment]
I got this problem too. Marking a show / film as seen will update instantly the widget adding the checkmark, but removing it won't make the checkmark disappear.
The only thing that makes it update is cleaning the Trakt database file (cleaning Trakt cache).
This is not only happening with the widget but also inside the actual addon.
