### ISSUE TITLE
[Feature] Metacritic ratings for TV shows

### ISSUE THREAD

**Issue by badelie** [jurialmunkey/plugin.video.themoviedb.helper#963]
### Skin section

Other

### Feature description

Adding metacritic ratings for TV shows, similar to movies. I understand the current source for information (OMDB) does not provide metacritic ratings for TV shows, but MDBList provides this information and users can get their own API access (with a Trakt login). 

MDBList also allows for bulk API requests, e.g. retrieve ratings for multiple TV shows / movies at once, rather than one by one as the skin views load. I'm not sure how queries to OMDB are handled (per item, or bulk) in the skin, but if this is done on a per item basis, I imagine using MDBList could speed that up too.

_In addition, as a suggestion, MDBList also provides ratings from other sources, e.g. Roger Ebert, MyAnimeList and LetterBoxd which can also be added in addition to Metacritic._

### Why is this feature needed? Please justify and explain.

I often rely on critic reviews to choose what to watch, my main source of critic reviews is Metacritic. The current list of ratings provided for TV shows doesn't include any based on critic reviews, unlike the one for Movies which already includes Metacritic.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is a feature request for TMDbHelper or similar. Skins don't make any requests to APIs.

**Comment by xyzfre** [comment]
@jurialmunkey  To use the new API mdblist for ratings should we disable the OMDB API from TMDb H settings or do we leave both APIs trying to figure it out I'm not getting the metacritic ratings for TV shows but for some movies I am getting the Letterboxd ratings which they look good ,my apologies for asking in this closed request

**Comment by jurialmunkey** [comment]
Leaving both enabled is fine. Omdb has some things that mdblist doesn't like critics consensus and awards.

Metacrotic for tvshows is working fine for me. Make sure you enabled it in ratings settings. The ratings options for movies/tv are now separated so you can set either individually.

**Comment by xyzfre** [comment]
Thank you @jurialmunkey for your response, I did find some Tv Shows that show all the ratings now and some don't ,I guess it depends on the TV Show correct?

**Comment by xyzfre** [comment]
> Leaving both enabled is fine. Omdb has some things that mdblist doesn't like critics consensus and awards.
> 
> 
> 
> Metacrotic for tvshows is working fine for me. Make sure you enabled it in ratings settings. The ratings options for movies/tv are now separated so you can set either individually. 

Update: I guess it took maybe 24 hours for my mdblist API key To take full affect because today I'm getting all ratings for TV shows and the Letterboxd for Movies this is a AMAZING feature I love ratings and they look GREAT on AH2 thank you for adding this ,AH2 gets better and better 💯💯 thank you for all your hard work and dedication @jurialmunkey BEST SKIN ever 🙌🏼🙌🏼

**Comment by Yacoubs00** [comment]
> ### Skin section
> Other
> 
> ### Feature description
> Adding metacritic ratings for TV shows, similar to movies. I understand the current source for information (OMDB) does not provide metacritic ratings for TV shows, but MDBList provides this information and users can get their own API access (with a Trakt login).
> 
> MDBList also allows for bulk API requests, e.g. retrieve ratings for multiple TV shows / movies at once, rather than one by one as the skin views load. I'm not sure how queries to OMDB are handled (per item, or bulk) in the skin, but if this is done on a per item basis, I imagine using MDBList could speed that up too.
> 
> _In addition, as a suggestion, MDBList also provides ratings from other sources, e.g. Roger Ebert, MyAnimeList and LetterBoxd which can also be added in addition to Metacritic._
> 
> ### Why is this feature needed? Please justify and explain.
> I often rely on critic reviews to choose what to watch, my main source of critic reviews is Metacritic. The current list of ratings provided for TV shows doesn't include any based on critic reviews, unlike the one for Movies which already includes Metacritic.
> 
> ### Screenshots and Additional Info
> _No response_
> 
> ### Checklist
> * [x]  I have made a separate issue for each feature I am requesting.
> * [x]  I have searched the issues and this feature has not been requested.
> * [x]  I am using the most recent skin version.

I have been looking for something similar for days. It would be awesome if MyAnimeList could be added!
