### ISSUE TITLE
[BUG] player for plugin://slyguy.hbo.max

### ISSUE THREAD

**Issue by batarela** [jurialmunkey/plugin.video.themoviedb.helper#964]
### Describe the bug

Hi,
Does anyone have a working player for plugin://slyguy.hbo.max?
tnx

### Steps To Reproduce

the player for plugin://slyguy.hbo.max is not working properly

{
    "name"              : "HBOmax",
    "plugin"            : "slyguy.hbo.max",
    "priority"          : 100,
    "provider"          : "hbo.max",
    "is_resolvable"     : "true",
    "make_playlist"     : "true",
    "assert"            : {
                            "play_movie":       ["title", "year"],
                            "play_episode":     ["showname", "season", "episode"],
                            "search_movie":     ["title"],
                            "search_episode":   ["showname"]
                          },
    "play_movie"        : [
                            "plugin://slyguy.hbo.max/?_=search&query={title_url}",
                            {"title": "{title}", "year": "{year}"}
                          ],
    "play_episode"      : [
                            "plugin://slyguy.hbo.max/?_=search&query={showname_url}",
                            {"title": "{showname}"},
                            {"title": "Season {season}"},
                            {"season": "{season}", "episode": "{episode}"}
                          ],
    "search_movie"      : "plugin://slyguy.hbo.max/?_=search&query={title_url}",
    "search_episode"    : "plugin://slyguy.hbo.max/?_=search&query={showname_url}"
}

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Information about creating players is in the wiki
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

This is not a TMDbHelper bug as I did not create this player.

**Comment by jurialmunkey** [comment]
Information about creating players is in the wiki
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

This is not a TMDbHelper bug as I did not create this player.
