### ISSUE TITLE
.strm files not loading

### ISSUE THREAD

**Issue by Snapperito** [jurialmunkey/plugin.video.themoviedb.helper#968]
### Describe the bug

Starting today, when trying to play a .strm file from my library (specifically in playlists), tmdb helper seemingly hasnt redirected the source to play in a streaming addon. tried with umbrella & seren. On top or that, the addon has been impossibly slow out of no where. 

### Steps To Reproduce

Play any .strm file -> endless loading

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Debug log?
