### ISSUE TITLE
WatchNixtoons2 Player 

### ISSUE THREAD

**Issue by jrocketsx1** [jurialmunkey/plugin.video.themoviedb.helper#969]
### Describe the bug

Hello all!
 Any help would be greatly appreciated! I am trying to add player for the cartoons section in Watchnixtoons2 addon. Can anyone tell me what I am doing wrong. All it does is load and ultimately fails. The episode numbers on tmdb are different than on the addon so I don't know if that is part of the issue. Is it possible to go by episode title instead so they match up?
Thank you!

{ "name" : "WatchNixtoons2", 
"plugin" : "plugin.video.watchnixtoons2", 
"priority" : 500, 
"play_episode" : [ "plugin://plugin.video.watchnixtoons2/?action=actionCatalogSection&amp;path=%2fcartoon-list&amp;section=ALL&amp;{clearname_+}", {"title": "{clearname}"}, {"episode": "{episode}"} ] }

### Steps To Reproduce

![3](https://user-images.githubusercontent.com/121939687/210541919-122b888f-ebb7-4564-b979-90dd8c3a699e.jpg)
![4](https://user-images.githubusercontent.com/121939687/210541934-e682d4b1-a4a7-4697-9f10-48ca1f569e20.jpg)
![1](https://user-images.githubusercontent.com/121939687/210541954-91a0e6d3-0e51-4583-86b9-5d8571cc5144.jpg)
![2](https://user-images.githubusercontent.com/121939687/210541976-5c18f069-c0a8-4786-b751-fc9bc5c98d0b.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Not a bug.
