### ISSUE TITLE
[BUG] Playing from library fails

### ISSUE THREAD

**Issue by justinkruit** [jurialmunkey/plugin.video.themoviedb.helper#970]
### Describe the bug

Whenever I press an episode that I've added to my library through TMDBHelper it gets a popup that it failed to play. When I try to play it from the addon directly it works fine.

Weirdly I've also noticed that playing from the library does work if the show has only 1 season.

### Steps To Reproduce

1. Add a show with seasons to the library
2. Go to that show
3. Play from library
4. Get error

### Debug log

https://paste.kodi.tv/xequduvixo

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by rapteev** [comment]
Hi
Set “play local kodi library files” to never.
That way all files added to library play ok.
I have the same problem.

**Comment by jurialmunkey** [comment]
@rapteev - That sounds like a different issue. Please file a bug report as that is not a suitable workaround. You should still be able to play local files even if you also use strm files.

@justinkruit Are you using Arctic Horizon 2 with the combined seasons/episodes view? There was a bug in the skin from that view in the exact version of the skin you have installed (0.7.23) -- Updating the skin should fix it.

**Comment by jurialmunkey** [comment]
@rapteev - That sounds like a different issue. Please file a bug report as that is not a suitable workaround. You should still be able to play local files even if you also use strm files.

**Comment by justinkruit** [comment]
@jurialmunkey ah yes, all seems to be working fine now! Thanks again for your amazing addons and themes you write for Kodi, probably would've switched to something else if it wasn't for them ❤️
