### ISSUE TITLE
[BUG] Seren 3.0 / seren.smartplay.json play_episode stops playing after two episodes

### ISSUE THREAD

**Issue by booyakafoo** [jurialmunkey/plugin.video.themoviedb.helper#972]
### Describe the bug

I have noticed that TheMovieDb Helper addon when using the Seren 3.0 smartplay player will only play two episodes and then the playlist is empty after the second video starts to play.  I downgraded back to Seren 2.1.9 and the issue doesn't exist.  After upgrading Seren back to 3.0 the playlists break again.  Seren 3.0 doesn't have this issue when playing directly from its addon.  I prefer to use TheMovieDb Helper for widgets because videos play from the local library when the video exists locally and hands off to Seren when it doesn't exist.  I also really like the search integration in Arctic Horizon 2.  I'm sure something has changed in Seren to cause this but I hope it can be fixed.  Thank you

### Steps To Reproduce

TheMovieDb Helper 5.045 is installed
Seren 3.0.0 is installed

Configured players.  I have Seren, Youtube, and UPnP

Default player for episodes is seren.smartplay.json play_episode

TheMovieDb Helper Expert settings are the following.

I have tried changing these to different values but this was the best settings for not crashing and for continuous playing episodes whether they are local or handoff to Seren 2.1.9.  I don't fully understand what they do.

Dummy video 0.1 or 5
Delay after resolving 0.1 or 5
Stop before attempting playback is enabled
Restrict to library strm is enabled
Reroute PlayMedia to xbmc is disabled
Resend local files is enabled

Navigate to a show in TheMovieDb Helper addon that isn't in your Kodi library
Play an episode.  If you check the playlist when you start playing it shows one episode in the playlist.  After Seren is done scraping and the episode starts the playlist will populate with the rest of the seasons episodes.
After the episode is over the next episode in the playlist will start playing but the playlist queue clears and only the previously played and current episodes show in the playlist.  When the second episode is done playing you are returned back to the episode list in the addon.

### Debug log

[kodi.log]

### Screenshots and Additional Info

Playlist while handoff to Seren and scraping has started
![queue 1](https://user-images.githubusercontent.com/3913228/211131001-d9ba9d45-a536-44f5-a8cb-acb6b9984774.png)

Playlist after episode has started playing
![queue 2](https://user-images.githubusercontent.com/3913228/211131004-20a7b104-1a44-44ff-9ea0-6d3aa3e70eca.png)

Playlist after first episode has completed and second episode is playing
![queue 3](https://user-images.githubusercontent.com/3913228/211131005-cd24820f-4a7c-431e-ad2a-94c7b4d1ca99.png)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I dont make third party players. You will need to ask the author of the player and/or plugin. This sounds like a problem with how that plugin manages its playlist.
