### ISSUE TITLE
[Feature] sort options for watchlist

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/plugin.video.themoviedb.helper#973]
### Describe the feature that you'd like

I’m not sure to post in here or AH2 git but when I click on watchlist, I’d like an option to sort by date added. I know I can context menu then browse sorted lists. I use AH2 and the hub option has a section for watchlist and it shows the default list but I’d like to have it by date added. I think watchlist and AH2 hub watchlist are tied together. 

### Why is this feature needed? What problem does it solve?

To show the watchlist sorted as wanted. 

### Steps to reproduce.

Go to watchlist in either movies or tv

### Screenshots and Additional Info

How it looks in AH2 hub now with the current sort
https://imgur.com/iBGvcKD

What the watchlist sorted by date added when I context menu and browse sort list
https://imgur.com/wbK7kQJ

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
In AH2 you can create a Custom Hub with whatever custom nodes you like.

Set home menu item to custom hub
`Action > Common > Hub - Custom`

` - Customise hub` option will appear under Action

Under hub widget nodes you can setup the node widgets. You can create a custom node via `Choose widget > Custom Node X`

That will give you a ` - Customise node` option where you can select exactly which widgets you'd like to appear in that node. From there you can choose whatever Watchlist sort method you like to use as the widget.

Yes it will take a bit to setup everything but this will give you the control you're looking for.

**Comment by Liquidrag** [comment]
Thank you! I’ll definitely go do that. Love your work!

**Comment by Liquidrag** [comment]
@jurialmunkey are there any plans for nodes like this on the main screen?
