### ISSUE TITLE
Unable to add show to library

### ISSUE THREAD

**Issue by Snapperito** [jurialmunkey/plugin.video.themoviedb.helper#976]
### Describe the bug

I added a show to my library through TMDB helper but deleted the library file and am now unable to redownload the show to a different location. To clarify, i can add any other shows i hadn't previously downloaded. 

### Steps To Reproduce

1. Add any show (or movie) to your library
2. Delete the library source folder
3. Create a new library source folder and set TMDB helper to download files there
4. Try to download the same show (or movie)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Need to clean your library to remove entries that no longer exist (step 7 in link below)
https://kodi.wiki/view/Updating_or_removing_videos#Remove_Source

Then force TMDbHelper to update:
TMDbHelper Settings > Library > Update Library Now > Forced Update
