### ISSUE TITLE
[Feature] Add original movie/tv-show title

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/plugin.video.themoviedb.helper#979]
### Describe the feature that you'd like

None English Movies have a different title in their native language. This piece of information is available on imdb and tmdb. Could you pls amend this details to the fetched data. and then add an option in the setting to Show Original Tile or not

### Why is this feature needed? What problem does it solve?

Some websites uses this original title instead of the English one especially subtitle providers. If the subtitle addon uses the name not the imdbid, or the imdbid isn't available (which is the case in many Korean movies), the subtitle addon fails to find a match. 

When these cases occurred to me, I did a manual search and found the subtitle but under the original title not the English one.

It is a useful piece of information.

Appreciate your efforts
Thank you

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Ah you talking about playback? You can already use originaltitle for players.

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#available-keys

**Comment by Mr-7mdan** [comment]
> Ah you talking about playback? You can already use originaltitle for players.
> 
> https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#available-keys

@jurialmunkey Thank you. The original title you are referring to is the title in the original language.

I am not requesting this, Instead I am requesting the original title in English letters. which is available on IMDB
![image](https://user-images.githubusercontent.com/9439671/219627475-74ead81e-290c-41e5-8488-36a04b8f4d4b.png)

which is also available in the JSON response
![image](https://user-images.githubusercontent.com/9439671/219630845-af9679f7-ffd2-4d3b-af20-5ca58ab61f6e.png)

My request is to add it to the listitem upon creation. I am unable to amend or add properties to an existing listitem. I failed to find a way to do it.

**Comment by jurialmunkey** [comment]
You can override player api language to be english

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#force-api-language-and-country-override-slower

**Comment by mac-88** [comment]
Hello, I have another small question, I don't seem to understand something.
I have set TMDBhelper to German and start the content with a player for fen light. The title transfer to the addon should also be in German. Now I have the "language: de" in the player (not "api_language", because I set tmdbhelper to German) but the addon looks for the English title. I also try with "de_title" in the play_movie if i missunderstand something, but it dont work. Have I overlooked or misunderstood something or could it be that the addon itself resets the title? 

Thank you a lot for the help

```
{
    "name": "fenlight",
    "plugin": "plugin.video.fenlight",
    "priority": 500,     
    "language": "de",
    "is_resolvable": "true", 
    "play_movie": "plugin://plugin.video.fenlight/?mode=playback.media&media_type=movie&query={name}&year={year}&poster={poster}&title={title}&tmdb_id={id}&autoplay=false",
    "play_episode": "plugin://plugin.video.fenlight/?mode=playback.media&media_type=episode&query={showname}&year={year}&season={season}&episode={episode}&ep_name={title}&tmdb_id={tmdb}&premiered={firstaired}&autoplay=false"
}
```
