### ISSUE TITLE
[Feature Request] "Play Using" on Context Menu

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#98]
I'd love the ability to choose a different player, besides my default one, from the context menu. Is this doable?

**Comment by jurialmunkey** [comment]
Yeah it shouldn't be too difficult. I'll have a look and get back to you.

**Comment by jurialmunkey** [comment]
Okay, please test latest. There should now be a "Play Using" context menu item.

**Comment by drinfernoo** [comment]
Hey, it occured to me today this may interfere with the "stock" context menu item, "Play Using"... which also plays using an external player, but obviously not quite the same as our usage.

**Comment by jurialmunkey** [comment]
It shouldn't be a problem having two items with the same name, but the it definitely will be confusing.

I'm not quite sure what I should rename it to. Any ideas?

**Comment by drinfernoo** [comment]
Maybe "Choose Player"? I haven't tested it myself, but someone brought it to my attention, and it seems that they only get the stock behavior for "Play Using" 🤔

They were testing it on integrated items in a library view, so is it possible that TMDbHelper isn't showing that item on library items?

**Comment by jurialmunkey** [comment]
Yeah it won't show on strm files because there isn't really anyway to determine whether it is a tmdbhelper item or some other library item.

For library strm files I really would need a different method that checks the filepath (tmdbhelper items will have a tmdbhelper player plugin path) and then use that filepath to get the params to pass to the context menu player function.

**Comment by angelitto2005** [comment]
I think i found a way to display ”TMDB - Play Using” on Global ContextMenu. I can now choose that option even if i am on another addons, or from my library.
Please implement this in next version 🙏🏼 💗 
I did modified 2 files: ”addon.xml” and ”context-play.py”
[modified files.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/4466184/modified.files.zip)
![screenshot000](https://user-images.githubusercontent.com/29383306/79067046-55511480-7cc5-11ea-96e2-dc07f11563cc.png)
![screenshot001](https://user-images.githubusercontent.com/29383306/79067048-571ad800-7cc5-11ea-9cc2-78d1fc82c7a2.png)
