### ISSUE TITLE
Trakt List

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/plugin.video.themoviedb.helper#980]
### Describe the feature that you'd like

Good Afternoon,
I trust you're well.

I have a widget pointing to 'based on recently watched movies' which gives a really fantastic recommendations, I'm guessing it only picks on roughly the last 5 movies? Could that be increased at all? 

I know there is also a Based on Most Watched Movies, but, the recommendations are no where near as specific. Usually a lot of animie etc.

### Why is this feature needed? What problem does it solve?

Gives a much wider scope of recommendations and variety .

### Screenshots and Additional Info

![16743179364915427956782513981631](https://user-images.githubusercontent.com/78307374/213876220-d57e3340-a4aa-446a-ae30-54f2b0f6feea.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
You got it exactly - it picks randomly from last 5 recently watched (or most watched) on Trakt account and then grabs the tmdb recommendations for that randomly selected item

It shouldn't be too difficult to add a setting slider to increase the pool used.

**Comment by jurialmunkey** [comment]
Add in 5.0.47

Settings > Trakt > Random seed pool for recommendations

Can choose from between 5 to 20 items.

**Comment by daviddia5** [comment]
I'm asking here so as not to open another thread.
Would there be an option for "Because you watched (name of the movie)" to appear in the widget label?

**Comment by adamosborne83** [comment]
> I'm asking here so as not to open another thread.
> Would there be an option for "Because you watched (name of the movie)" to appear in the widget label?
> 

What skin are you using? As in works in AH2, as you can see in the picture I posted.

**Comment by daviddia5** [comment]
> > I'm asking here so as not to open another thread.
> > Would there be an option for "Because you watched (name of the movie)" to appear in the widget label?
> 
> What skin are you using? As in works in AH2, as you can see in the picture I posted.

AH2. But I mean in the widget, that information does not appear in the widget.

**Comment by daviddia5** [comment]
> I'm asking here so as not to open another thread. Would there be an option for "Because you watched (name of the movie)" to appear in the widget label?

Hi Jurial, any way to do this would be possible?

**Comment by jurialmunkey** [comment]
You can get the label from `ListItem.Property(widget)`
