### ISSUE TITLE
[BUG] Adding to library doesn't create files

### ISSUE THREAD

**Issue by justinkruit** [jurialmunkey/plugin.video.themoviedb.helper#986]
### Describe the bug

When adding a show to the library, it doesn't seem to create files. Adding a new show does create the folder and season folder, but no .nfo or .strm files. Same goes for updating already added shows that new episodes are not being added.

### Steps To Reproduce

1. Add a show to your library
2. Have it not shown up

### Debug log

https://paste.kodi.tv/iyigagoxeh
First I manually updated the library, and after that tried to add a show that's not in my library yet.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I can't recreate this behaviour on Windows. I need more information about how to reproduce it. Anything unusual about your setup? For instance on networked shares?

**Comment by smallieollie** [comment]
Obviously I am not the original poster of this issue, but I can give you some more info as I am experiencing the same.  I'm on Android and library is on smb.  I added a few shows last week with no issues, today I add and it does not create the folder or add the .nfo files.  I can get you logs if need be, but right now I am in the process of doing a forced update to library via tmdb settings.  I should have looked here before I started.

Update, so here is what I figured out with my issue.  I can add anything new that I previously have never had with no issues.  Anything that I have removed from my library in the past can not be readded.  Even after I clean library and do a forced update to library in Tmdb settings.  So this could be the original posters issue.  I will try and have a look again later and open a new issue with all my info.

Update 2

This is just to give you input on how I fixed my issue.  I noticed that there was a folder called pickle inside plugin.video.themoviedbhelper.  I could see the TV id for the shows I had previously had im my library that were cleaned and removed.  I created a backup of each of these files for the shows that were not adding and then deleted them.  Went back into Kodi, added them again and this time they added and create the folders and strm files.  Everything is back to working as it should.  Hope this helps.

**Comment by ZelKami** [comment]
I have this issue too. For shows that are not returning (they have the status ended or canceled), after deleting them and trying to re-add them my logs showed something like "[Show] not returning. Don't look for new episodes". I will try to get the exact log message later.
