### ISSUE TITLE
[Feature] Local library (nfo) studio info

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#987]
### Describe the feature that you'd like

Is there a possibility to somehow get information about the studio/network from the nfo file if it exists. I'm asking because I need it for the studio logo. There are users who want to get this information (logo) from the nfo file and not directly from tmdb.
I am using this code.
$INFO[Container(99950).ListItem.Property(Network.1.Name),resource://resource.images.studios.coloured/,.png]
$INFO[Container(99950).ListItem.Property(Studio.1.Name),resource://resource.images.studios.coloured/,.png]

### Why is this feature needed? What problem does it solve?

/

### Steps to reproduce.

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
`$INFO[ListItem.Studio]`

You don't need TMDbHelper to get local information. It already exists.

**Comment by matke-84** [comment]
You didn't understand me. I want to display studio logo. 
`$INFO[ListItem.Studio]`
This works if there is only one studio for movie, if there are two or more, logo will not be displayed. That's why I asked if there is a chance for tmdb helper to pick up info from the nfo file.

**Comment by jurialmunkey** [comment]
Enable retrieve Kodi details setting.

**Comment by matke-84** [comment]
The option is already turned on. Is there any other solution?

**Comment by jurialmunkey** [comment]
That's why I deleted my comment. I thought you were talking about a list of items

The service monitor only retrieves online info. It is "tmdb"heloer, not library helper.

If you want a splitter function, that should be done natively. You should ask kodi devs to add a way to retrieve single studios from the library as properties.
