### ISSUE TITLE
Dependency not met with this version

### ISSUE THREAD

**Issue by bulletremedy** [jurialmunkey/plugin.video.themoviedb.helper#988]
### Describe the bug

Dependency not met, now the older version and this version not working. Cannot get meta and Rotten ratings! AH2

### Steps To Reproduce

Downloaded from your git

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Log?
