### ISSUE TITLE
Episodes not being passed to Aura Mod as Episode media type?

### ISSUE THREAD

**Issue by abbaskip** [jurialmunkey/plugin.video.themoviedb.helper#99]
I'm not positive this is the case, but am assuming it's along these lines. When I add a landscape widget pointing to "Your Next Episodes" on my home screen they're not showing with the little red episode number ribbon, and instead show with full TV Show name, episode number, episode name grey textbox under the landscape tile.

Also is there no way to remove the appended episode number to the episode name. In Seren this can be disabled so that it doesn't show twice in Auramod. With TMDB Helper widgets it shows twice.

Screenshots for reference:
TMDB Helper widget
![Screenshot_20200218-141437_Remote Desktop](https://user-images.githubusercontent.com/31556078/74701351-934c3200-525a-11ea-9553-9ec5d2140927.jpg)

Vs
Seren widget
![Screenshot_20200218-141518_Remote Desktop](https://user-images.githubusercontent.com/31556078/74701374-a101b780-525a-11ea-8d77-8041c27b03e0.jpg)

**Comment by jurialmunkey** [comment]
Ask skin author. These are skin issues not plugin issues. 

Plugin is setting episode type for this list. 

Season and episode can be removed by skins using listitem.title instead of listitem.label

**Comment by abbaskip** [comment]
> Ask skin author. These are skin issues not plugin issues.
> 
> Plugin is setting episode type for this list.
> 
> Season and episode can be removed by skins using listitem.title instead of listitem.label

The addon shouldn't pass the episode number by default to remain consistent with how other addons and widgets work, surely? Seems strange that it works with Seren and Skin Helper Widgets, but not your addon and you're suggesting it's the Skin's issue. I would suggest that shows your addon isn't consistent with the rest of the community?

**Comment by abbaskip** [comment]
Venom widget below. 

![Screenshot_20200218-152204_Remote Desktop](https://user-images.githubusercontent.com/31556078/74703804-83385080-5262-11ea-9f40-4e8535a5d34d.jpg)

Basically widgets from all addons work, except yours... But it's the Skin's fault?

**Comment by abbaskip** [comment]
Finally i just checked default Kodi widgets. Regardless of what other addons do, i would hope default Kodi widgets show correctly... And surprise, they do.

Are we still saying it's the skin?
![Screenshot_20200218-152713_Remote Desktop](https://user-images.githubusercontent.com/31556078/74704048-2c7f4680-5263-11ea-8163-4d222c303429.jpg)

**Comment by abbaskip** [comment]
@jurialmunkey can you please have a second look at this. I really want to help as i love the addon, and it seems strange that Kodi default widgets, skin Helper widgets, Seren widgets and Venom widgets all show correctly, but yours doesn't.

**Comment by abbaskip** [comment]
I've just investigated further and found that your addon works properly if I make the shortcut to: TMDB Helper- Trakt - Your TV calendar - Last Week

So your addon is even passing correct info from there.

However if the shortcut is to TMDB Helper - TV shows - Your Next Episode it shows incorrectly

**Comment by jurialmunkey** [comment]
@abbaskip - As you can see in the debug overlay at the top right of this screenshot, the `Container.Content()` is correctly set to *episodes* and `ListItem.DBType` is correctly set to *episode*. @skyfsza would have more insight into why AuraMod is not treating this path as an episode widget, but I can say with certainty that my addon is setting the correct content type.

You can also see in this screenshot that `ListItem.Title` provides the episode title without any additions and `ListItem.Label` adds the season/episode number. It is up to the skinner to decide whether they show ListItem.Label or ListItem.Title, but it is standard practice for Kodi that Title will be the unaltered episode title whereas label can have other additions.

![Honeyview_screenshot508](https://user-images.githubusercontent.com/4618719/74723682-19826b80-528f-11ea-831e-e0b83b840909.jpg)

As you can see in this second screenshot from Kodi's recently added episodes library section, Kodi also appends the season and episode number for content which mixes multiple seasons and episodes together. So my addon is actually consistent with the default behaviour of kodi, and those other addons that you listed are not.

![Honeyview_screenshot509](https://user-images.githubusercontent.com/4618719/74723689-1ab39880-528f-11ea-8231-072907c7f4e1.jpg)

**Comment by jurialmunkey** [comment]
Looking at AuraMod code, my guess it is to do with this visibility condition which incorrectly mixes OR `|` and AND `+` operators without correctly bracketing them
https://github.com/skyfsza/skin.auramod/blob/master/1080i/Includes_WidgetMods.xml#L605

This part of the line doesn't have correct bracketing. Also have no idea what the point of checking for DBID here is, and is probably the other thing that is breaking stuff.
`[!String.IsEmpty(ListItem.Art(clearlogo)) | !String.IsEmpty(ListItem.DBID) + !String.IsEmpty(ListItem.Art(tvshow.clearlogo))]`

So yes, very certain that this is a skin issue.

**Comment by skyfsza** [comment]
@jurialmunkey  TMDBHelper is definitely setting the Container correctly in Library view and DBType for widgets, looks like something skin side is causing abbaskips issue.

@abbaskip  I dont have the same issue as you posted above with TMDB Helper "Your next episodes".  Open an issue on https://github.com/skyfsza/repository.auramod and I will try assist. 

![screenshot005](https://user-images.githubusercontent.com/29917137/74726572-6131d480-5248-11ea-8088-38366ebd400a.png)

**Comment by jurialmunkey** [comment]
@skyfza - Did you see my secondary comment. I think it might be because you are mixing an AND and a OR operator without bracketing it 
i.e. this part of the line:
`[!String.IsEmpty(ListItem.Art(clearlogo)) | !String.IsEmpty(ListItem.DBID) + !String.IsEmpty(ListItem.Art(tvshow.clearlogo))]`

Needs to be either:
`[!String.IsEmpty(ListItem.DBID) + [!String.IsEmpty(ListItem.Art(clearlogo)) | !String.IsEmpty(ListItem.Art(tvshow.clearlogo))]]`

or 
`[!String.IsEmpty(ListItem.Art(clearlogo)) | [!String.IsEmpty(ListItem.DBID) + !String.IsEmpty(ListItem.Art(tvshow.clearlogo))]]`

or
`[[!String.IsEmpty(ListItem.Art(clearlogo)) | !String.IsEmpty(ListItem.DBID)] + !String.IsEmpty(ListItem.Art(tvshow.clearlogo))]`

**Comment by skyfsza** [comment]
No idea why I had the DBID check in either, removing so it just checks for 
[!String.IsEmpty(ListItem.Art(clearlogo)) | !String.IsEmpty(ListItem.Art(tvshow.clearlogo))]

Thanks!

**Comment by abbaskip** [comment]
Thanks loads to both of you. Will install git versions of both addons today and see how it goes

**Comment by abbaskip** [comment]
The thumbs now work properly, thanks guys. I believe the Episode number being repeated is a skin issue, so will raise that there
