### ISSUE TITLE
In progress shows paginated with all episodes, 

### ISSUE THREAD

**Issue by Legacyconnor** [jurialmunkey/plugin.video.themoviedb.helper#990]
### Describe the feature that you'd like

An option to view in progress TV shows with season pagination, including watched episodes without the need for additional context menus.

The desired effect can currently be achieved by selecting Trakt -> Your In Progress TV Shows -> context Menu on show > browse lists -> seasons.

### Why is this feature needed? What problem does it solve?

While the desired effect can be produced using the steps noted above it can only be accessed from TMBD directly and not added as a widget (at least not within AH2).

I believe such a view would enable easier/quicker episode selection. Particularly in cases where trakt does not accurately reflect the users true viewing history. As would be the case for the majority of users who have watched television for longer than they have used trakt and providing trakt a complete viewing history is likely to prove impractical.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by Legacyconnor** [comment]
Just a correction to say the context menu can be accessed from a widget on Kodi v20 but not 19.5.

While it can be accessed In v20 removing the need to go through 2 menus every time to achieve the desired effect would be better solution.

**Comment by jurialmunkey** [comment]
>  Particularly in cases where trakt does not accurately reflect the users true viewing history

If your viewing history is not accurate, then in-progress is pointless anyway. The whole point is to keep track of where you are up to.

If you want to show recently watched TV shows, use the recently watched TV shows list instead of in-progress.
