### ISSUE TITLE
Error when searching and then attempting to play film

### ISSUE THREAD

**Issue by Ade-AV** [jurialmunkey/plugin.video.themoviedb.helper#992]
### Describe the bug

```
2023-01-30 22:04:40.003 T:6569    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'RuntimeError'>
                                                   Error Contents: can't start new thread
```

### Steps To Reproduce

Search for film in AH2, e.g. How To Train Your Dragon, select to play from the results, error

### Debug log

https://paste.kodi.tv/xuwuyesomo

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by Kaveon2022** [comment]
I have a very similar or the same exact issue.

**Comment by Ade-AV** [comment]
Well I can't replicate anymore! @Kaveon2022 do you have logs?

**Comment by Kaveon2022** [comment]
Try adding this URL http://bit.ly/gplayers to the update players from URL section in the settings. Its an updated player list for kodi 20 made by a user...all credit due to them. It resolved my issue hope this helps. I'm not using AH2 though.
