### ISSUE TITLE
[BUG] Bio missing for actors

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#993]
### Describe the bug

When filling a list with:-

plugin://plugin.video.themoviedb.helper/?info=cast

Only a very, very few of the returned items have the ListItem.Plot property set to the actors Bio.

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Yeah it's not returned by the api for cast list and it'd be too slow to do individual lookups (cast can sometimes be 200+ people). If the details are cached they get added (which is why some have plot) but it's just not worth it to lookup the entire list.

I use a hidden list with the detailed item to grab the info when using the service monitor isn't suitable.

``` xml
<!-- Hidden Details List -->
<control type="list" id="6502">
    <left>-1920</left>
    <width>1</width>
    <height>1</height>
    <orientation>vertical</orientation>
    <itemlayout />
    <focusedlayout />
    <content>plugin://plugin.video.themoviedb.helper/?info=details&amp;tmdb_type=person&amp;tmdb_id=$INFO[Container(6501).ListItem.Property(tmdb_id)]</content>
    <visible>!String.IsEmpty(Container(6501).ListItem.Property(tmdb_id))</visible>
</control>
```

```xml
$INFO[Container(6502).ListItem.Plot]
```

**Comment by roidy** [comment]
> Yeah it's not returned by the api for cast list and it'd be too slow to do individual lookups (cast can sometimes be 200+ people).

Yep, I didn't think the api returned that kind of detailed info for cast lists which I why found it strange that a few of them had the Bio filled in.

> If the details are cached they get added (which is why some have plot) but it's just not worth it to lookup the entire list.

I was just about to ask why some do return a Bio, but that edit explains it. 

Thanks for the reply 👍
