### ISSUE TITLE
[QUESTION] Setup fallback language

### ISSUE THREAD

**Issue by PlugPlayer** [jurialmunkey/plugin.video.themoviedb.helper#995]
### Describe the bug

I currently us 5.0.48~nexus.
I added a tvshow by adding it by naming it "tmdb/xxxxx". Everything was scraped corrently but the poster was missing. Then I noticed that it is not avaible for my prefered language. I headed to to setting and couldn't find any hint on fallback language. I searched around and found #654 which also mentioned the ability to set a fallback. But where do I this? Sorry for asking this but I am still struggling to finding out what the connection is between this addon here and scraper I am using. Who/What is responsible to maintain te fallback language? Can I set that on per tvshow?

Thanks in advance,
Dragoo

PS: Again sorry for subitmitting a question as bug. But I do not know where to asked such focused question. Maybe it's worth to introduce a "question" label? I really do not like the characteristics of those gigantic forum thread where I find it very hard to find anything. Just a suggestion.

PS2: I have other questions regarding "How to setup tmdbh to update my nfo files?". Okay for you if I write another Issue?

### Steps To Reproduce

see above

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by PlugPlayer** [comment]
I tried a enable **General -> Get additional details and artwork from TMDB** but with no luck. Thought it would may make it possible to choose the artwork from all languages. :(

**Comment by jurialmunkey** [comment]
Are you adding a strm to the library?

The library scraper you use will be responsible for setting your artwork, not tmdbhelper.

Think of the library strm file as a shortcut which opens tmdbhelper to play but to kodi looks like any other video like an mp4 or mkv. It won't have a poster or anything like that because that's what the library scraper does.

Also note you can use this to your advantage to customise it by adding your own posters to the folder just like any other videos in your library.

**Comment by jurialmunkey** [comment]
And on your second question - also not relevant. Tmdbhelper does not set any nfo for local strm. That's also up to the scraper. All tmdbhelper generates is an nfo with a link to the entry on the tmdb website to help a scraper find the correct entry. Tmdbhelper doesn't generate any metadata to scrape. All it makes is the strm (which is essentially the same as having videos in folders on your hard drive)

Just like any other video in your library, all the info and artwork metadata for the strm will come from your library scraper

**Comment by PlugPlayer** [comment]
@jurialmunkey Thanks for your detailed explanations. But unfortunately I actually do not know what a strm file is. 


 I just have video files "ABC SXXEXX" in a folder named "ABC". Maybe it is worth to mention that it is adult content so the normal scraping does not work here. So tried the approach from [here](https://kodi.wiki/view/Add-on:TMDb_TV_Shows) when I added the folder I used tmdb/12345 (just a dummy) and it worked. The metadata was scraped fine. The only exception was the Poster which was only available in japanese. That was were may "fallback language" came from. Also I asked myself if I add every single TVShow with this approach where is the actual data stored? Just in  the Kodi database? I thought there is a way to write those scraped data (title, posters...) back into the source directory in form of images and nfo file. Or in other words I want this process of adding a TVShow in that way to have just once even if I would remove it from the library then. When I would then re-add it the nfo file and images of the previous scrape due the tmdb/12345 approach just be there and have all the necessary data.

This was may thinking. Maybe I am wrong but with both topics (fallback language, nfo writing) I stubbled somehow over your addon. In #654 I thought that the discussion was about to be able to set a fallback language. And about "writing metadata back to the source folder" I also got some hint from the internet that this is possible. I if remember there is a option which mentioned "nfo" somehow. With the hint from the internet I thought I may misconfigured something and it should be possible to write the metadata back to the source directory.

I hope it makes my questions bit clearer. I really appreciate your explanations about that because I think this will help me a lot! Thanks in advance!

Dragoo

**Comment by jurialmunkey** [comment]
TMDbHelper is NOT a library scraper. It doesn't touch the info in your library at all and doesn't have anything to do with scraping.

TMDbHelper can be used by skins to do additional online lookups to fill in additional data (e.g. extra ratings and so on) that your scraper might not have added. However, it doesn't touch your library at all. These lookups are temporary. 

You need to speak with the author of whatever library scraper you're using.


Note that the TMDb library scraper is an entirely different addon. It has nothing to do with TMDbHelper other than that they both get data from the TMDb website api.

**Comment by PlugPlayer** [comment]
@jurialmunkey Thanks for the clarification!
