### ISSUE TITLE
[BUG] Next up not showing latest episodes

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#996]
### Describe the bug

I've noticed this problem in anime series. I have next up from Trakt as a fullscreen widget so whenever there is a new episode, I see the anime in the list. But once I browse the anime, instead of jumping to this episode for the current season, I'm shown a list that contains all episodes starting from the first one.
I think the problem comes from Trakt as I checked that their site doesn't show the episode either so I have to either wait a day or so for the list to be updated or go directly to the anime and search for the latest episode there. But given I'm using next up as I widget I don't understand how the widget shows there is a new episode that then is not there. 

### Steps To Reproduce

1. Create a widget with Trakt's next up as a source with a list of animes in it (or just one anime).
2. Have at least one anime in there were all episodes are marked as watched so it doesn't show up in the list 
3. Wait for a new episode to air.
4. See that the widget shows the anime.
5. Browse the list of episodes for the anime from the widget.
6. Verify the list starts from the first episode instead of showing the latest one and that this episode is not included in the list.
7. Check that the episode indeed exists by going directly to the anime and looking for it there.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
If it isn't on Trakt, it won't be in Up Next. That data comes from Trakt.

Also Trakt server caches some sync data for accounts -- so on occassion there can be a half a day ish delay before the watched sync data updates to include the newly added episode (new as in episode added on Trakt website -- air date doesn't matter) --- that's why you can sometimes see a discrepancy between a calendar and up next.

**Comment by juanma-cvega** [comment]
Sorry for the delay in the response, I've been away. I understand this comes from Trakt but what I don't get is why the anime is showing up in the widget. I'm using the fullscreen widget with up next for my private anime list so, if up next doesn't return any new episode, shouldn't it just not show the anime in that case? Where is the widget getting there is a new episode if not from up next?
