### ISSUE TITLE
[Feature] Don't load the list of players when using the default one

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#998]
### Describe the feature that you'd like

I have configured the addon to use a default player for everything. I would expect this player to be used and nothing more but when I play something, I see the notification on top that says 'Building players' that on my Shield 2019 pro could take 3 or 4 seconds (I only have 4 video addons and one is youtube). Is there anyway to speed this up by not loading the list? Or is it needed for the fallbacks when a player fails? (I have configured 2 players to fallback to in case the default one fails).

### Why is this feature needed? What problem does it solve?

It would speed up playback if it can be done.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
"Constructing Players" is a bit of a misnomer. A lot more is done that just building the player dialog in that stage. A log is required to draw any conclusions about what might speed things up.

Without a log, it's premature optimisation to skip building the players if you haven't actually properly identified it as the cause of the delay. Unless you have hundreds of players and plugins installed, it is fairly unlikely it takes much time to read your player files and construct the dialog entries.

What generally *does* take time is retrieving the ID lookup from Trakt and checking library to see if the item exists (if you have a very large library this will be slow, especially if the mem cache had expired and needed to be rebuilt). Again, these are guesses, and it is impossible to determine what is actually causing the delay without a log.

**Comment by juanma-cvega** [comment]
Ok, I understand now. I thought it was weird just building the players took that long. I've done more testing and it seems the time it takes to 'build players' changes from time to time so it may network/service latency as you mentioned. I'm closing this as it seems there is nothing to be done here.
